### ISSUE TITLE
wind turbines: do not show minor ones at zooms 15/16/17

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1017]
PR #248 converted into a ticket

@danstowell suggests that we don't want to render all wind-turbines at zoom 15/16/17, only those marked `man_made=tower`.

Wind-turbines are sometimes significant landmarks (usually standlone towers) and sometimes not (small building-mounted turbines). The carto style currently errs on the side of eagerly showing wind turbines, which for some examples of tiny turbines in the city is undue prominence. Here's an example in Birmingham:

![birmingham-turbine](https://f.cloud.github.com/assets/202965/1416106/a21698da-3f37-11e3-9d67-2846a41701c3.png)
http://www.openstreetmap.org/#map=15/52.4836/-1.8881

Here's an example in London:
![highbury-turbine](https://f.cloud.github.com/assets/202965/1416107/a807465e-3f37-11e3-98d8-6aadb48664b8.png)
http://www.openstreetmap.org/#map=15/51.5439/-0.1037

I asked on the "tagging" mailing list if anyone had suggestions. There wasn't much controversy, but not much definite direction. One suggestion was that `landmark=yes` could disambiguate. Seemed OK to me, but searching actual use, I don't see this actually used for wind turbines.

However, in Europe there are 427 wind turbines also marked with `man_made=*`, of which 133 are `man_made=tower`. (Other values include things not encouraged by the wiki such as `man_made=wind_turbine`, and things not relevant to landmarkness such as `man_made=power`.)

@gravitystorm 

So to follow-up our in-person discussion:
- Yep, I think it's good to differentiate, if possible. The rendering of wind turbines on this style is as much (if not more) about their giant landmarkness than their electricity supply interestingness.
- I don't like "landmark=yes", since it's completely subjective
- I worry that since they are all on towers of one height or another, then that doesn't distinguish

Perhaps a height, or a tower height tag?

@mboeringa

> This pull-request suggests that we don't want to render all wind-turbines at zoom 15/16/17, only those marked man_made=tower.
> ...
> I worry that since they are all on towers of one height or another, then that doesn't distinguish

I think the better solution to this, might be to consider the power output in kW of a turbine. Small turbines of less than say 50-100 kW, could be left out of the rendering at certain zoom levels, or drawn with a smaller icon. Larger turbines than these, are less likely to be found in dense city quarters, and if they do, like in industrial zones, they should probably be rendered.

Although it needs looking up in tag info for verification, I think the rated output may actually be also more consistently tagged on turbines, than the man_made=tower tag which is actually superfluous for a turbine, given the fact that turbines have their own tagging scheme.

The rated output of the turbine is, according to the new Power scheme, stored in either the "generator:output", or "generator:output:electricity" key, with the latter key the recommended one, but of course, the first option is likely to also exist in the OSM database. In a less optimal situation, the rated output of the turbine, might also have been tagged in the "plant:output(:electricity)" namespace, but this is inappropriate for a single turbine, at least not with "generator:output" as well.

**Comment by pnorman** [comment]
> I must admit I don't think there's anything we can do at the rendering end, yet - we just have to wait for a convention to emerge from tagging practice...

Has this changed?

**Comment by jeisenbe** [comment]
I'm considering this issue again, since I'm looking to adjust the icon positioning per #3176

We can hide wind turbines on buildings in the city by using the same code to check for location on rooftop or roof, as with towers and masts: `'power_' || CASE WHEN power IN ('generator') THEN power AND (tags->'location' NOT IN ('roof', 'rooftop') OR (tags->'location') IS NULL)) THEN power ELSE NULL END,
`
We could also use height to render short wind turbines later. I was not able to find the percentage of wind turbines that have a height listed, but we could render shorter turbines later and continue to render height=null at z15.

Thoughts?

**Comment by kocio-pl** [comment]
Sounds sane for me.

**Comment by mboeringa** [comment]
> Yes, we have almost all the keys available since v4.0.0 (except some filtered as non interesting for rendering on general map).

OK, of course, a combined filtering based on power output _and_ location is also a possibility. If one doesn't catch it, than the other one does.

**Comment by jeisenbe** [comment]
I checked taginfo, and generator:output:electricity seemed to be used only
500 times, versus 100,000+ wind turbines, but perhaps I did the search
wrong?

In the USA the average height of new wind generators is now over 80m! So
z15 is certainly reasonable for the average wind turbine.

**Comment by jeisenbe** [comment]
I would like to try rendering wind turbines at:
z14 >100m height
z15 for height > 50m, and if height is not tagged
z16 for height >30 m but less than 50m
z17 for height <30 m
No rendering for wind turbines on rooftops. (These are usually more for show than for producing significant amounts of energy. Urban areas are not good places for wind generators)

This would match other tall features for orientation in rural areas such as towers and masts.

I'd be happy to consider using generator:output:electricity instead, if someone can find how this would correlate with the size of the generator, and if it's used more often than height. Maybe someone else already has some data downloaded and can check?

The other thing I noticed is that the wind turbine icon is currently black, instead of man-made-icon gray. I would recommend changing this to match.

**Comment by Adamant36** [comment]
I don't know how helpful it is, but height is used on generator:method=* 6,352 times and 7, 999 times on generator:output:electricity. I don't know how you only came up with 500 uses of generator:output:electricity if 7,999 of them are tagged with height. That doesn't seem right. Also, I don't know how many of those are wind turbines. There's probably a math formula to figure it out that I'm just not privy to. 

Unfortunately there isn't any combination stats for generator:method=wind_turbine on Taginfo because the numbers aren't high enough and there's way to find it in combination section of the height page. They should lower the numbers required for things to show up in the database. 

86,700 buildings are co tagged with generator:method, of those 71,137 are tagged with generator:output:electricity. 

There's 90,180 uses of generator:source on buildings with 171,623 uses of generator:source=solar  overall. Given that generator:output:electricity is used 71,137 times and is obligatory for solar, I feel like you could come up with a formula that would subtract the amount of one of those from the other. Then divide or something. In order to figure out how many are used on wind turbines or something. I'm way out of my depth though. 

I do think if your not going to render wind turbines on roof tops you might be missing out on a lot of them though. It looks like some of them can be pretty substantial and you shouldn't not render them just because some people decide to map the more minor insignificant ones. The solution there might be rendering based on height also. Exclude rendering of ones shorter then 10 feet or something and you'll weed out all the minor ones. 
![roof wind turbine](https://user-images.githubusercontent.com/30259065/48398735-74193900-e6d6-11e8-848e-3f3eae88c8ba.jpg)
![roof wind turbine 2](https://user-images.githubusercontent.com/30259065/48398811-b5a9e400-e6d6-11e8-8dc0-d85bce0852fe.jpg)

**Comment by jeisenbe** [comment]
The most common value of generator:output:electricity is "yes" (about 67%) and that's what I've seen on several wind turbines.https://taginfo.openstreetmap.org/keys/generator%3Aoutput%3Aelectricity#values

According to this tag info, there are over 223,000 nodes tagged generator:source=wind (and just a handful of ways and relations). https://taginfo.openstreetmap.org/tags/generator:source=wind

I checked overpass in the Netherlands and found 2134 nodes with "generator:source"="wind". There are 621 nodes with "generator:source"="wind" and generator:output:electricity, but generator:source=wind with generator:output:electricity=yes was found 163 times, so only 458 nodes out of 2134, or less than 22%, have a useful electricity value. But only 221 in the Netherlands have "height", about 10%. 

In Scotland there are 2753 total; 21 with height and 1011-381 = 630 with generator:output:electricity (not =yes). 

California has 10363 total, only 159 have height. 3219 have generator:output:electricity but 2700 =yes, so only 519 have a useful value (about 10%). 

Unfortunately, the values of generator:output:electricity include MW or kW, so I'm not sure how to code this.

```
[out:json][timeout:60];
{{geocodeArea:Germany}}->.searchArea;
(
  node["generator:source"="wind"]["generator:output:electricity"="yes"](area.searchArea);
);
out body;
>;
out skel qt;
```

Another thing to consider for the PR would be to remove power_source=wind from the code, because this key is deprecated and power_source=wind is only used 200 times now: https://taginfo.openstreetmap.org/keys/?key=power_source#values  https://wiki.openstreetmap.org/wiki/Key:power_source

**Comment by Adamant36** [comment]
Thanks for the information. How do you do a TagInfo search for the amount of uses for only California?

**Comment by mboeringa** [comment]
> I checked taginfo, and generator:output:electricity seemed to be used **only 500 times**, versus 100,000+ wind turbines, but perhaps I did the search wrong?

> I don't know how helpful it is, but height is used on generator:method=* 6,352 times and 7, 999 times on generator:output:electricity. **I don't know how you only came up with 500 uses of generator:output:electricity if 7,999 of them are tagged with height**. That doesn't seem right. Also, I don't know how many of those are wind turbines. There's probably a math formula to figure it out that I'm just not privy to.

I agree this figure of 500 is likely way to low, just look at this Overpass Turbo query that selects wind turbines by both looking at the **generator:source=wind** and **generator:method=wind_turbine** tags to determine whether a tagged object is a wind turbine (I assume here anything tagged with **generator:source=wind** is a wind turbine even if it hasn't got an additional **generator:method=wind_turbine** tag, but although this assumption may theoretically be false, practically it should be fine given current technology - those [elusive wind harvesting kites](https://en.wikipedia.org/wiki/Crosswind_kite_power) are still not there in real world application.

Admittedly, a lot of the selected features, maybe 1/3 to 1/2 are just **generator:output:electricity=yes**, but the rest does have values in kW or MW.

[Overpass Turbo query selecting wind turbines](https://overpass-turbo.eu/s/DE3)

**Comment by jeisenbe** [comment]
@mboeringa you are right, I must have done the query wrong (perhaps I was using a smaller bounding box than I intended). 

It looks like 5% to 30% of wind turbines are tagged with generator:output:electricity with a useful value, depending on location, and this is at least twice as common as the height tag.

Does anyone know how we can do a SQL query that selects the numeric values, properly adjusted for units (W vs kW vs MG vs GW)?

**Comment by jeisenbe** [comment]
I have pushed two branches to my fork, and I can do a PR as soon as we decide which option is best

1) Uses SQL queries in project.mml to not select any power generators with location=rooftop or =roof
https://github.com/jeisenbe/openstreetmap-carto/tree/windturbine-not-rooftop

2) Uses location to render wind turbines at z19 if on rooftops / roof, and at z15 otherwise
https://github.com/jeisenbe/openstreetmap-carto/tree/windturbines-z19-rooftop

Both branches also change the wind turbine icon color to man-made-icon gray, 
and start rendering name labels for wind turbines in the same color as other man-made features.

**Comment by Adamant36** [comment]
Personally, id go with number 2. Its worth rendering ones on roofs. There doesn't seem to be any problem with them being rendered. So I don't see why not. Unless your deciding what to render and not render based on something completely arbitrary. Which could lead to a lot of other things not being rendered in other certain weird circumstances. So, there should be a standard. Either an item is rendered or not. There's shouldn't be an "uummm sure, but not in this instance." At least in this instance. I think rendering rooftop ones at z19 is a good compromise. Although, that's kind of arbitrary also. At least they are rendered that way though.

**Comment by jeisenbe** [comment]
The issue is that the icon will block building names and other POI icons
(for example, a cafe or shop in the same building) in some cases. At z19
this is less of a problem, but it will still occur.

**Comment by Adamant36** [comment]
Yeah, obviously. That's always an issue with things though. Its kind of a matter of if the wind turbine is in the same location of the POI or not. Id guess in most cases it wouldn't be. Your looking a slim probability based on the size of the building that it is. Especially if its only for Z19. If it does get in the way though, id assume, although I'm only speculating, that the POI icon would take precedence and the wind turbine just wouldn't display. Which is no big deal. Its kind of an "addon" feature in cases where they are part of a roof anyway.

**Comment by Adamant36** [comment]
Btw, I appreciate the energy and diligence you have been putting into issues the last couple of weeks. I was doing PRs at a pretty good pace for a few months there, but unfortunately I haven't been able to dedicate much time to it lately. So its nice to see someone picking up the slack. Especially considering that your dealing with more then a few issues that are out of my coding expertise.

**Comment by jeisenbe** [comment]
@kocio-pl, what are your thoughts about excluding all rooftop wind turbines vs rendering only at z19? Both options are ready for a PR.

**Comment by kocio-pl** [comment]
They are probably much less common there than chimneys, so maybe we could render them at all.

**Comment by jeisenbe** [comment]
kocio-pl  wrote:

> They are probably much less common there than chimneys, so maybe we could
> render them at all.
>
I’m sorry, I don’t understand.

>
>

**Comment by kocio-pl** [comment]
Chimneys on the roofs are never displayed, because there is a lot of them and it would dominate all the buildings, even on z19. Wind turbines on the roofs are not as popular, so it is probably safe to show them on z19+.

**Comment by jeisenbe** [comment]
Ok, thanks!
