### ISSUE TITLE
Render name of administrative boundaries on centroid

### ISSUE THREAD

**Issue by joakimfors** [gravitystorm/openstreetmap-carto#104]
Names of administrative boundaries should be rendered on centroid with the appropriate size (similar to place= nodes). Issues with name collisions might occur as some "places" are mapped as both a place node and an admin boundary as the current mapnik stylesheet doesn't support place= on areas correctly (see #103 ).

**Comment by kocio-pl** [comment]
If I understand this issue, current rendering is already made in centroids, using "interior" function.

Proper rendering however depends mostly on Mapnik's ability to move them aside when conflicting with admin capitals, which means that #2962 is needed (see https://github.com/mapnik/mapnik/pull/3780#issuecomment-347163806). Once "grid" method is available, we can use it for admin areas, but this ticket is rather not talking about it.

**Comment by matkoniecz** [comment]
> If I understand this issue, current rendering is already made in centroids, using "interior" function.

I am pretty sure that request "Render name of administrative boundaries on centroid" is fulfilled.

**Comment by kevinp2** [comment]
> > If I understand this issue, current rendering is already made in centroids, using "interior" function.
> 
> I am pretty sure that request "Render name of administrative boundaries on centroid" is fulfilled.

I don't see the name rendered in at least this case: https://www.openstreetmap.org/way/1393918259

This is one of the most straightforward cases: a closed way with these tags:

**admin_level=10
boundary=administrative
name=The Basin**

Is this a bug or by design?  I request to reopen this issue if necessary.  It would be helpful for Carto to render admin boundary labels.

**Comment by matkoniecz** [comment]
Are admin_level 10 administrative boundaries rendered at all?

Also, note date: for 8 year old issue it is better to open a new one not to comment on so old one.

**Comment by imagico** [comment]
This can be quickly cleared up: We deliberately render administrative boundaries only from boundary relations, not from closed ways.

And yes, this is a matter unrelated to the original issue from 2013 so it would have been a new issue.

**Comment by kevinp2** [comment]
> This can be quickly cleared up: We deliberately render administrative boundaries only from boundary relations, not from closed ways.
> 
> And yes, this is a matter unrelated to the original issue from 2013 so it would have been a new issue.

Hi @imagico , thanks for the update.  But see this object: https://www.openstreetmap.org/way/1150881164

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/a95a1648-843f-4ba6-9296-48c902788cb6" />

This is a closed way (not a relation) that renders the name nicely.  The full set of tags are:

**admin_level=10
boundary=administrative
description=Boundary of Osprey Ranch, Phase 1, Eden, UT
landuse=residential
name=Osprey Ranch
residential=single_family
website=https://www.osprey-ranch.com/**

Could it be that the **landuse** plays a part?  I am just trying to figure out a consistent way to map these residential subdivisions so that their names show up on the map.

**Comment by 1ec5** [comment]
Yes, the fill and label are coming from the `landuse=residential` tag. As I mentioned in one of the changeset comments, the kind of planned developments you’re mapping are normally modeled as landuse areas rather than boundaries. There was [some discussion on the forum](https://community.openstreetmap.org/t/mapping-neighborhood-boards-as-admin-boundaries-missoula-mt/110695/10) last year about whether some well-organized subdivisions should be administrative boundaries, but so far that approach hasn’t entered the mainstream.
