### ISSUE TITLE
Add rendering for man_made=cross

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1060]
related to #131

**Comment by daganzdaanda** [comment]
This note https://www.openstreetmap.org/node/26863070 made me think of this issue. 
It looks as if "man_made=cross" makes a "natural=peak" disappear. See http://overpass-turbo.eu/s/7OE for other examples. Or is it that all of the peaks are connected to paths?

**Comment by nebulon42** [comment]
@daganzdaanda I can confirm this in master. In the SQL `man_made` takes precedence over `natural`, but since `man_made=cross` is not rendered nothing is rendered. I think it is better to open a separate issue for that. This is another instance of a more general problem (see #1269).

**Comment by ppete2** [comment]
At least in Alpine regions it's very common that crosses are placed either on the peak or on some scenic viewing point on the mountain (but which is not the peak). For the first tagging `summit:cross=yes` is used, for the second `man_made=cross`. Both cases are usually tagged with `ele=*` to indicate their elevation which is an important atttribute of such "mountain crosses".

But sadly the elevation is just rendered for `summit:cross=yes` - not for `man_made=cross`. Please add it!

**Comment by imagico** [comment]
This issue is about adding rendering of `man_made=cross` - and has been closed because this has been added.

Note `ele` is currently labeled on natural=peak/volcano/saddle, tourism=information + information=guidepost, tourism=alpine_hut/wilderness_hut, amenity=shelter and mountain_pass=yes.  We do not interpret `summit:cross=yes` at all.

There are currently 641 nodes with `man_made=cross` and an `ele` value and no `natural=peak`.  Of those many are immediately next to a different feature (typically `natural=peak`) and duplicate the `ele` value of that feature.
