### ISSUE TITLE
Consider Noto fonts

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1067]
I just found the free font collection Noto from Google. http://www.google.com/get/noto/
Having no real insight into osm carto font support but there might be some less used fonts in noto which could be interesting for us.

**Comment by matkoniecz** [comment]
> The font is published under the Apache2 license.

Now it is OFL - see http://www.google.com/get/noto/updates/

> How do licenses on fonts work? Does it mean we need to hand out a copy of the Apache license with every tile?

From reading http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#2855b85f it seems that crediting authors would be necessary. It is not clear where. On the map? In LICENSE file? In the commit description?

**Comment by pnorman** [comment]
DejaVuSans.ttf has 6122 glyphs and NotoSans-Regular.ttf has 2410. It seems that to get support for all the languages, you need to include a few dozen different fonts, which will grow the list significantly

**Comment by sommerluk** [comment]
I like Noto also. It is designed with the goal to render all scripts and preserve a harmonic design between all these scripts. Noto is quite unique and quality and in internationalization coverage. For an international map style like openstreetmap-carto that renders many different scripts, but wants to preserve the same design in different countries, Noto might be the natural choise and could substiture all the other fonts. Furthermore, it offers for allmost all scripts also a bold typeface – nice to have. Its support for complex typography (like multiple combining diacritics on the same base character) is really good.

Quick guide: https://www.google.com/get/noto/help/guidelines/

It might be worth to use the “UI” version instead of the normal version. Quoting from https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md :

> What’s the difference between the UI and non-UI versions? The UI fonts were initially prepared for use in Android’s UI. They have tighter vertical metrics, and some glyphs that would be clipped are redrawn to fit within the constrained space. They can be used anywhere that has limited vertical space.

**Comment by kocio-pl** [comment]
See also this discussion:

https://lists.openstreetmap.org/pipermail/dev/2016-June/029294.html

**Comment by clkao** [comment]
@pnorman I think "Noto" here refers to the whole family, including the Noto Sans CJK, which is essentially the sam as Adobe Source Hans with 65535 glyphs

**Comment by matkoniecz** [comment]
Noto is also considered as replacement for fonts-droid 

fonts-droid has has been removed from Ubuntu 16 https://lists.ubuntu.com/archives/ubuntu-devel/2016-February/039159.html (see #2200)

**Comment by mxa** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/issues/2204#issuecomment-230020607 for a rendering example in China, Japan, Korea

**Comment by sommerluk** [comment]
Is there support for switching to Noto fonts? This could mean
- drop all currently used fonts
- use Noto (not only the Noto file for the Latin script, but use it also for CJK, Kannada, Arabic…) The list is long…
- requiere Noto as dependency (at least the Latin script, and other scripts to the degree that the user want to render labels in these scripts, like currently described in INSTALL.md, and requirering also Unifont)

If so, I would propose to wait until Mapnik3 is available on the openstreetmap.org servers and than go on with this issue (doing the testing also under Mapnik3).

**Comment by mxa** [comment]
This would be amazing and result in a much more consistent look of carto worldwide and especially when looking at border regions.

**Comment by math1985** [comment]
> If so, I would propose to wait until Mapnik3 is available on the openstreetmap.org servers and than go on with this issue (doing the testing also under Mapnik3).

+1
Font rendering is really different on Mapnik 2 and Mapnik 3, so I agree it would be best to wait until Mapnik 3 is rolled out, so we don't need to test on two Mapnik versions.
