### ISSUE TITLE
Render historic=tomb

### ISSUE THREAD

**Issue by Grillmannen** [gravitystorm/openstreetmap-carto#1068]
There are currently a little over 3000 uses of historic=tomb in the database,[1] and the wiki page is well written and has several different tomb tags with image descriptions.[2]

Rendering example would be a small religion neutral tomb stone.

Most historic=archeological_site that I find are actually tombs of some kind, so I think there are actually more tombs in the database but with the wrong tag. If tombs get rendered people will probably start to use the correct tag more frequently.

[1] https://taginfo.openstreetmap.org/tags/historic=tomb
[2] https://wiki.openstreetmap.org/wiki/Tag:historic%3Dtomb

**Comment by BertMule** [comment]
Just give me an icon, as already used while editing.
As frustrating as ever, 

Example of a landmark in a park.
https://www.openstreetmap.org/#map=19/51.99853/4.77250

**Comment by wlakom** [comment]
I think it's time to reopen this topic and add an icon representing a grave, similar to https://umap.openstreetmap.fr/en/map/new/#19/53.83448/18.10317

This icon shows that its dimensions are sufficient so that they don't overlap.

So, please create an icon for the tag "historic=tomb" for the OpenStreetMap.org map.
We already have entire cemeteries mapped, such as in Czarna Woda
 [​https://www.openstreetmap.org/#map=18/53.834347/18.102832](https://www.openstreetmap.org/#map=18/53.834347/18.102832)

[​https://taginfo.openstreetmap.org/tags/historic%3Dtomb#overview](https://taginfo.openstreetmap.org/tags/historic%3Dtomb#overview)

We also have an updated " Wyszukiwarkę grobów na OSM (OSM Grave Finder)" that allows you to display grave descriptions:

https://dotevo.github.io/gravemap-osm/#16/50.0759/19.9550

**Comment by imagico** [comment]
Re-opening would require convincing new arguments.  The case example pointed to is a graveyard where every single grave is tagged `historic=tomb`.  That speaks against rendering the tag under the premise of this issue (which is rendering `historic=tomb` as a class of historic sites).

For reference: Current use numbers:

* `historic=tomb`: 66k uses, 26k with `building=*`, 25k with `tomb=*`
* `cemetery=grave`: 100k uses.

Not really relevant here, but piece of advice: Before you add things like https://www.openstreetmap.org/relation/18092768 it might be a good idea to discuss with your local community first.  See also https://wiki.openstreetmap.org/wiki/Limitations_on_mapping_private_information

**Comment by wlakom** [comment]
Every grave is in fact historic.

This is not my opinion.

The current way of tagging graves has been very popular in Poland for a very long time and all graves on OSM are tagged in a similar way. Presumably there will be more and more of them, regardless of whether the community outside Poland likes it or not.

The community in Poland has developed the following procedure a long time ago. https://wiki.openstreetmap.org/wiki/Pl:Tag:landuse%3Dcemetery.

As I wrote before, the "Wyszukiwarka grobów na OSM" will allow increasing the number of graves in a similar way.

**Comment by imagico** [comment]
> The community in Poland has developed the following procedure a long time ago. https://wiki.openstreetmap.org/wiki/Pl:Tag:landuse%3Dcemetery.

That is interesting, thanks for the pointer.

That also explains that of the 5154 features double tagged `historic=tomb` + `cemetery=grave` [3504 are in Poland](https://taginfo.geofabrik.de/europe:poland/tags/historic=tomb#combinations).

Anyway - as already said: This issue is about rendering `historic=tomb` as a class of historic sites (in the sense of a site that has significance today in a manner that is detached from its original function - see also `amenity=place_of_worship` vs. `building=church`/`historic=church`).  Rendering contemporary graves, potentially differentiated by their design, would be a separate matter for a separate issue.  And for that the dominant tag is clearly `cemetery=grave`.

**Comment by wlakom** [comment]
Personally, I have nothing against it.

But my request and issue concerns the design of an icon representing a **grave in a cemetery**. 
So I don't care whether the icon represents `historic=tomb` or `cemetery=grave`. 
The important thing is to do it as soon as possible.
In that case, you can change the topic from **Render historic=tomb** to **Render cemetery=grave**.

**Comment by imagico** [comment]
> In that case, you can change the topic from Render historic=tomb to Render cemetery=grave.

We don't re-purpose issues like that.  If you want to request rendering `cemetery=grave` as representing an individual grave in a cemetery please open a new issue for that.

**Comment by dieterdreist** [comment]
sent from a phone

> On 31 Oct 2024, at 19:03, Christoph Hormann ***@***.***> wrote:
> 
> Not really relevant here, but piece of advice: Before you add things like https://www.openstreetmap.org/relation/18092768 it might be a good idea to discuss with your local community first. See also https://wiki.openstreetmap.org/wiki/Limitations_on_mapping_private_information


can you explain how the name of a person who died more than 50 years ago could be related to the concept of “private information”?

**Comment by imagico** [comment]
> can you explain how the name of a person who died more than 50 years ago could be related to the concept of “private information”?

I could, but not here. :wink:

**Comment by dieterdreist** [comment]
sent from a phone

> On 1 Nov 2024, at 12:19, Christoph Hormann ***@***.***> wrote:
> 
> I could, but not here. 😉


As you started the discussion here, and it is somehow relevant to the topic of rendering graves, I will still use the opportunity to tell you that according to the current state of things and my knowledge, birthdates and day of death and names of long dead people and the positions of their graves are not covered by privacy protection in jurisdictions I am aware of. Maybe there could be very rare exceptional cases where privacy interests of living descendants could be touched by publishing such information, but it is not to be generally expected.

**Comment by imagico** [comment]
I understood you the first time.  Yet again: this is not a discussion i am going to have here.
