### ISSUE TITLE
Render peaks in order of eleveation

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1084]
variant of #1083

Peak with untagged height currently may block one where height is tagged, lower may block label of higher one. In case of peaks showing on the same map ordering by elevation should work in nearly all situations.

Peaks below see level may be in theory troublesome - ordering by elevation may not work, missing ele tag should be assumed to be below lowest possible peak height to ensure that tag with missing ele tag will not be considered more important by one where peak is below see level. But at least currently these problems are theoretical. It seems that such peaks are rare http://www.openstreetmap.org/?mlat=31.1022&mlon=35.3796#map=13/31.1022/35.3796 

see http://www.openstreetmap.org/node/385115017#map=14/49.1838/20.0878 (Česká veža is not tagged with ele tag)

![selection_005](https://cloud.githubusercontent.com/assets/899988/4705468/1d1c7e42-587c-11e4-800a-bbd362fc867c.png)

compare http://www.openstreetmap.org/node/385115017#map=15/49.1868/20.0864

![selection_004](https://cloud.githubusercontent.com/assets/899988/4705427/c4c1fbb4-587b-11e4-91f8-82f8d547b352.png)

**Comment by math1985** [comment]
@pnorman Do you know how to validate whether a value is a float? We have
```
CASE WHEN layer~E'^-?\\d+$' AND length(layer)<10 THEN layer::integer ELSE 0 END AS layernotnull
```
for integers.

**Comment by pnorman** [comment]
> for integers. Can we do something similar for floats?

No. You could validate a subset of floats with `layer~E'^-?\\d(\.\\d)+$'`. Some form of length restriction is needed too. I *think* this is enough, but needs validating and the syntax checking.

**Comment by HolgerJeromin** [comment]
Some ele are in the unit foot in the database (see [talk-us](https://lists.openstreetmap.org/pipermail/talk-us/2015-March/014533.html)). Hikemap converts [some Tags](https://github.com/Ahlzen/Hikemap/blob/master/hikemap_tagtransform.lua#L65) to foot in a lua script on import time. Perhaps we should do something similar.

**Comment by pnorman** [comment]
Lua scripts would require a reload and aren't on the roadmap.

Since ele is recording a fact about the physical world, not based on signage, I'm inclined to require standard tagging - unitless, and in meters.

**Comment by matkoniecz** [comment]
Also

> Elevation of a point in metres in WGS84/EGM96. 

at http://wiki.openstreetmap.org/wiki/Key:ele Note http://wiki.openstreetmap.org/wiki/Key:ele#Local_Units

**Comment by dieterdreist** [comment]
2015-04-02 20:40 GMT+02:00 Paul Norman <notifications@github.com>:

> Since ele is recording a fact about the physical world, not based on
> signage, I'm inclined to require standard tagging - unitless, and in meters.



while it is a fact, it still has something to do with signage as well
(because many mappers copy the elevation values off signs). This btw. also
makes the numbers less reliable in general, because lots of lots of ele
values are copied directly from signs into OSM, without doing the necessary
conversion from the local/national reference system to WGS84. Signposted
elevation numbers are hardly every in WGS84, at least not in the areas
where I map. See also
http://wiki.osm.org/wiki/Key:ele#National_reference_systems (the US are
missing yet).
Another important part of this complex is the GPS system: z-information has
a much bigger error than x/y information has, so unless you are using a
barometric instrument which you set up correctly not too much time ago with
an external reference, you will not be able to measure elevation reliably.
