### ISSUE TITLE
Render waterway=ditch thinner and only from zoom 16 onwards

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#1101]
When using waterway=ditch on a way, the default Mapnik rendering shows it from zoom level 13 onwards and shows it rather prominently. In areas where ditches are used heavily for draining land, it can leave the map looking very crowded at lower zoom levels

Messy waterway=ditch example: http://www.openstreetmap.org/#map=13/54.7150/-8.7022

Clean barrier=ditch example: http://www.openstreetmap.org/#map=16/54.6648/-8.7823

Might I propose that similar to barrier=ditch... waterway=ditch does not appear until zoom level 16 and that it is rendered at a lesser thickness

Thanks,

C

**Comment by sommerluk** [comment]
The narrow rendering of waterway=ditch was bearly recognizable on the map. I would not rebder the line narrower.

But I think it could be useful to not render waterway=ditch from z=13, but from z=16 or even z=17.

**Comment by wmyrda** [comment]
I vote for having waterway=stream render from z13 onward just like now, but make it thinner so on z13 it is not as wide as the road system which is more important and wider in the reality as well.
See http://www.openstreetmap.org/#map=13/49.6863/22.5913
Waterway=ditch/drain should also be thinner and probably appear only from z14 unless it has width=>2 to have it appear on z13 only for wide ditches with 2 meters or above

This is related to the https://github.com/gravitystorm/openstreetmap-carto/issues/1781#issuecomment-235131091 Having more contrast for waterways would make it possible to see streams/ditches/drains even if one makes them thinner.

This might be related to https://github.com/gravitystorm/openstreetmap-carto/pull/975

**Comment by matkoniecz** [comment]
I think that it would make problem described in #2346 even worse, so I recommend closing this issue.

**Comment by jeisenbe** [comment]
I agree with closing this issue. As mentioned above, rendering ditches narrower and at higher zoom levels than streams would encourage mappers to mis-use the waterway=ditch tag for narrow streams (see #2346)

Some large drainage (or irrigation) ditches are as wide as many canals. And for understanding the waterway network they are as important as streams in most places.

We could instead consider adjusting the rending based on the `width=`, as suggested in more recent issue #3795 and in #3354

**Comment by pelderson** [comment]
I would like to ask for a slight reconsideration, i.e. to render waterway=ditch from z15 onwards instead of z14, OR render waterway=ditch shallower than now. 

I will illustrate why. Consider https://www.openstreetmap.org/query?lat=52.08096&lon=4.43810#map=13/52.0745/4.4877 
Please look at the rounded area below Stompwijk, and the area just left of it. Both have an elaborate system of parallel ditches. In the rounded area these have been mapped as water areas, while the area to the left of it has the ditches mapped as waterway=ditch. On the ground, these areas are similar in aspect. Now zoom to z14. Suddenly, the ditches all appear and the leftside area looks unrealistically blue, while the rounded area keeps blue and green realistic. At z15 the waterway=ditches look more realistic, at z16 it's ok. At z17, z18 and z19  the waterway=ditches are too narrow, but that's no big issue.

The "shallower rendering at z14" option (if it's applied to streams as well) would not lead to mappers abusing waterway=ditch for streams, I think. I can imagine mappers not knowing which one to take, because streams are frequently made to look like ditches and ditches are often styled as streams, but you can't solve that with rendering.

**Comment by imagico** [comment]
For info:  Starting zoom level for minor waterways was moved from z13 to z14 in #3467 without changing the styling so they appear very abrupt at z14 no matter how dense they are.

Most OSM based maps traditionally start minor waterways at z13, some at z12 (OpenTopoMap, most Thunderforest styles), few at z14 or later (and most which do tend to have a distinct non-rural focus).  Most which start at z12 or z13 start relatively subtly though.

**Comment by pelderson** [comment]
> For info: Starting zoom level for minor waterways was moved from z13 to z14 in #3467 without changing the styling so they appear very abrupt at z14 no matter how dense they are.
> 
> Most OSM based maps traditionally start minor waterways at z13, some at z12 (OpenTopoMap, most Thunderforest styles), few at z14 or later (and most which do tend to have a distinct non-rural focus). Most which start at z12 or z13 start relatively subtly though.

That change is about visual clutter below z14, I don't want to take a stand on that.  Just concerned with the abrupt appearance  of a very dominant water grid, especially compared to the way the almost identical ditches scale when mapped as a series of water areas. An even green area suddenly turns into a waterarea, then zooming in further it turns green again. 

I would welcome a more subtle appearance of ditches at z14. 

Having looked at more ditches in several countries, I drop the first option I mentioned. Most of these are less dense and less grid-like, and compared to other details z14 feels right for most ditches and streams to (subtly) appear.
