### ISSUE TITLE
Improve low zoom levels

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#1125]
The low zoom levels are currently not very pretty, and hard to read. 

See also http://www.reddit.com/r/openstreetmap/comments/2e2ohr/openstreetmapcarto_default_openstreetmaporg_style/ for detailed comments.

We should probably first think which features we find important on low zoomlevels.

#1107 will probably improve this.

**Comment by mkoniecz** [comment]
> dashes are computed on the length of the border on high zoom, not on the length of the border as you could measure in pixels on low zoom. That means that dashes become invisible on curly borders. Compare the England-Wales border, which nearly looks undashed, with the straight Sahara borders, which look fine.

@imagico Can you publish program used to generate data described in http://blog.imagico.de/rendering-boundaries/ ? It seems that it may fix this problem.

**Comment by imagico** [comment]
Well i guess i could but i don't think i'd really do anyone a favour by doing that.  It is very non-robust and scales badly to the point that is is not really usable for more than admin_level 2.

Realizing that i started looking into a more elegant and universal solution more in the line of what i did with the coastlines.  I did not yet have the time to finish that though.

The broader question here that would need to be addressed first anyway is if and how this style is going to include preprocessing of OSM data - there are other areas, most notably where NaturalEarth data is used right now, where this is an open question as well.

**Comment by kocio-pl** [comment]
I started to collect notes about improving low zoom level [on my Wiki page](http://wiki.openstreetmap.org/wiki/User:Kocio/low_zoom_rework). I guess this is so complex problem, that even meta-issue like this one would be too static, so we may make more readable version somewhere else on OSM Wiki.

I see 3 main areas here:
1. Showing names (continents, countries, states and country capitals)
2. Showing borders (countries and states)
3. Showing physical landcovers

I think [French fork makes most of it better](https://github.com/gravitystorm/openstreetmap-carto/issues/1402), so we may just copy that things, because it would be easiest and most effective. First easy question is if we would like to show the continents names at all.

The most important thing for me, yet quite simple to implement, would be to start using `text-label-position-tolerance` option, which allows areas labels to be placed so they [stop eclipsing cities (especially capitals!) labels](https://github.com/gravitystorm/openstreetmap-carto/issues/1391).

I like to test it, but I need to resolve a technical problem first: how to extract from planet.osm file only the features visible on 1-6 (or 1-7) levels. @matkoniecz [has already tried to do something like this](http://forum.openstreetmap.org/viewtopic.php?pid=514998#p514998), but hit the wall at the moment. If anyone else can help us with it, we would appreciate it a lot.

**Comment by matkoniecz** [comment]
@kocio-pl 

According to [mapnik documentation](https://github.com/mapnik/mapnik-reference) text-label-position-tolerance only works with placement:line in Mapnik 2.3 - so it can not be used to solve placement problems for areas. In addition it is missing/renamed in Mapnik 3.0

**Comment by kocio-pl** [comment]
The documentation is so dry that I find it hard to really understand it... 

I also have checked it and came to the same conclusion as you. But when I started to analyze [French placenames.mss file](https://github.com/cquest/osmfr-cartocss/blob/master/placenames.mss) and looking at French tiles, it became clear to me that it probably works anyway. My working theory is the "line" could be also closed, exactly like borders, and I need to test it.

**Comment by matkoniecz** [comment]
I think that this issue is not really useful. low zoom levels are worse than others, but I think that it would be better to open individual issues for each idea of improvement or noticed problem.

**Comment by kocio-pl** [comment]
For me it's just another meta-issue, which sooner or later have to result in more specific issues/PRs. I already have [my own special Wiki subpage](http://wiki.openstreetmap.org/wiki/User:Kocio/low_zoom_rework) dedicated for dealing with this quest, so the question of leaving it open or closing it is not crucial for me, I just think it's better if we have as much tools, documentation and discussions in one place as possible, so we can cooperate easier, especially on some complex issues like this one.

Real meta-issues with access granted for all GitHub users (not just issue author and repo owner/collaborators) or GitHub Wiki for this repo would be good, but in the absence of them I prefer to have this meta-issue open.

**Comment by matkoniecz** [comment]
Significant part of issues was fixed in great #1989 by @nebulon42 (and maybe also earlier changes) - especially https://github.com/gravitystorm/openstreetmap-carto/issues/1125#issuecomment-62509674 (see http://www.openstreetmap.org/#map=5/43.485/20.270).

**Comment by math1985** [comment]
#1107 has been merged (long time ago), and the rendering is now much better than in the included screen shot. There's still a lot that can be improved, but I'd suggest making separate issues for that when needed.

**Comment by matkoniecz** [comment]
From what I see everything is now either solved or has its own ticket (in case of something not covered by other issues - please, open a new one).
