### ISSUE TITLE
render buildings with historic=castle as major

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1176]
Currently, after https://github.com/gravitystorm/openstreetmap-carto/commit/b4aff69d4eae8f0d8f98bd4ae6358f5ca26b7a39 only buildings with amenity=place_of_worship are considered major. I propose to add also buildings with historic=castle as important tourism attractions and landmarks.

**Comment by mkoniecz** [comment]
There is a problem - according to http://wiki.openstreetmap.org/wiki/Tag:historic%3Dcastle "draw a way around the outline of the construction.".

@pnorman 
Is there a way to query whatever object is inside area tagged with historic=castle - without making it too expensive for a servers?

**Comment by pnorman** [comment]
When I initially rewrote the buildings, I wanted to take out the special handling of buildings that had an `amenity=place_of_worship` tag because it didn't work well with churches that weren't P.O.W.s, churches as nodes inside buildings, and anything other than the simplest `amenity=place_of_worship building=*`.

We should probably decide on the above before looking at how to handle historic=castle, which is, if anything, even more complicated because the POI polygon contains the building polygon, not the other way.

**Comment by Wuzzy2** [comment]
Yes, please render castles, these are major landmarks.

**Comment by kocio-pl** [comment]
I think this is bad idea, so I will close it now. Icons should be much better and clear: #3099.

**Comment by dieterdreist** [comment]
I liked the idea of having castles rendered as special buildings (this is
regardless of icons).

**Comment by kocio-pl** [comment]
I guess the icon and dark brown would be too much emphasis.

**Comment by dieterdreist** [comment]
2018-03-26 18:58 GMT+02:00 kocio-pl <notifications@github.com>:

> I guess the icon and dark brown would be too much emphasis.
>


I'd say it may depend, but often city gates are significant tourist
attractions, see for example:
https://en.wikipedia.org/wiki/Porta_Nigra
https://en.wikipedia.org/wiki/Porta_Maggiore
https://en.wikipedia.org/wiki/Porta_San_Sebastiano
https://commons.wikimedia.org/wiki/File:Speyer_BW_5.JPG
https://fr.wikipedia.org/wiki/Porte_des_Allemands
etc.

**Comment by kocio-pl** [comment]
I'm not sure if I understand you properly, but for city gates we have separate ticket (#152) and defensive towers are rendered now, so such popular objects would be visible anyway.

**Comment by dieterdreist** [comment]
sorry, mixed tickets
