### ISSUE TITLE
Merge power-towers and power-poles

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1179]
Currently we define two layers, `power-towers` and `power-poles`.

It would be a performance gain if these were merged into one layer, ordered with poles before towers in the SQL.

This would be a good task for someone wanting to learn how to edit the style.

**Comment by jragusa** [comment]
I'm preparing a PR to resolve this basic issue and I'm would also take the opportunity to separate the icon of `power=pole` (`square.svg`) which is also used by several other features (`railway=station`, `entrance=main`, `highway=bus_stop`) and move it to into the man_made folder.

Is there any objections or remarks ?

**Comment by Tomasz-W** [comment]
@jragusa As - you actually mentioned that - it is used by many features from different categories, I think this icon should be in general folder.

**Comment by Adamant36** [comment]
Three others isn't to many. The less icons in the main folder the better also. Another alternative might be to create a folder for icons that are mixed/used with multiple tags. As I think there are several. Something like a square isn't inherently man made though. Since its an abstract icon. Whereas, it makes more sense to put an icon for something like art in the shop folder, but then still use it for other tags. Since its at least semi related to an art shop in design.

**Comment by pnorman** [comment]
I'd keep the icons as-is.

**Comment by Adamant36** [comment]
@pnorman, how come? There's a plan to move a lot of them into their own folders. The main icon folder is pretty disorganized.

**Comment by jragusa** [comment]
For now, I change anything about the icon location.
