### ISSUE TITLE
add orthodox cross for religion=christianity icon (depending on denomination)

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1186]
see https://github.com/gravitystorm/openstreetmap-carto/pull/1185#issuecomment-68447380 for a possible icon

At least denomination=orthodox,  denomination=greek_catholic and denomination=russian_orthodox may use new icon.

EDIT, thanks to @mboeringa:

As there is a wide variety of COUNTRY_orthodox following query may be better (but it will catch also typos in country names):

religion IN ('christian') AND (denomination IN ('armenian_apostolic', 'greek_catholic') OR denomination LIKE '%orthodox%' OR denomination LIKE '%Orthodox%')

**Comment by mboeringa** [comment]
@mkoniecz, this seems a very incomplete list if compared to tagInfo. Taginfo shows that much of the orthodox denominations, seem to be declared country specific:

https://taginfo.openstreetmap.org/keys/denomination#values

An undoubtedly incomplete list (based on browsing through the first 20 or so taginfo pages for "denomination" and "orthodox" in the name of the denomination, and reading through some general Wikipedia pages about Christian denominations and orthodoxy):

'armenian_apostolic','bulgarian_orthodox','coptic_orthodox','ethiopian_orthodox','ethiopian_orthodox_tewahedo','georgian_orthodox','greek_orthodox','macedonian_orthodox','orthodox','romanian_orthodox','russian_orthodox','serbian_orthodox','syriac_orthodox','ukranian_orthodox'

Due to the diversity of these orthodox denominations, and the values in the OSM database, it might be better to try to catch them all using a more generic SQL statement like:

religion IN ('christian') AND (denomination IN ('armenian_apostolic') OR denomination LIKE '%orthodox%' OR denomination LIKE '%Orthodox%')

And shouldn't **greek_catholic** be **greek_orthodox**?

**Comment by math1985** [comment]
> And shouldn't greek_catholic be greek_orthodox?

Doesn't seem like it: http://en.wikipedia.org/wiki/Ukrainian_Greek_Catholic_Church

**Comment by mboeringa** [comment]
> Doesn't seem like it: http://en.wikipedia.org/wiki/Greek_Byzantine_Catholic_Church

I understand that there is a denomination=greek_catholic, but is it part of orthodoxy, and should thus use the same symbol in the renderer as e.g. denomination=orthodox or denomination=russian_orthodox? (It says "Separated from Greek Orthodox" on the page you linked in the frame on the right of the page...).

**Comment by mkoniecz** [comment]
Greek catholic is a special case - they are "in full union with the Roman Catholic Church" (pope as leader etc) but they kept traditional rituals - Orthodox churches, othhodox cross as a symbol etc.

see http://en.wikipedia.org/wiki/Eastern_Catholic_Churches

**Comment by mboeringa** [comment]
> Greek catholic is a special case - they are "in full union with the Roman Catholic Church" (pope as leader etc) but they kept traditional rituals - Orthodox churches, orthodox cross as a symbol etc.
> 
> see http://en.wikipedia.org/wiki/Eastern_Catholic_Churches

I think that photo of the cemetry settles it...: seems you are right!

**Comment by mkoniecz** [comment]
@mboeringa I like your query (added to the initial post) - but it will display also typos in country names (for example ukranian_orthodox seems to be a typo of ukrainian_orthodox).

**Comment by mboeringa** [comment]
> @mboeringa I like your query (added to the initial post) - but it will work also for names with typos (**for example ukranian_orthodox seems to be a typo of ukrainian_orthodox**).

Well, the specific example is actually a typo by myself, that I have corrected now in the first post.

I get the point though, do we enforce a strict tagging scheme only allowing some specific values, or try to "catch them all"?... I understand there is preference for the latter for consistency reasons, but with no really good formal tagging scheme yet for denomination (the current Wiki page http://wiki.openstreetmap.org/wiki/Key:denomination doesn't seem to correspond well with the tagging practice as per taginfo), it may mean missing a lot of denominations, although I think the list I compiled already includes the bulk.

**Comment by mboeringa** [comment]
By the way, i also see **ukrainian_greek_catholic**... so a "generic" variant of the query might need something like:

religion IN ('christian') AND (denomination IN ('armenian_apostolic') OR denomination LIKE '%orthodox%' OR denomination LIKE '%Orthodox%' OR denomination LIKE '%greek_catholic%' OR denomination LIKE '%Greek_Catholic%')

**Comment by nebulon42** [comment]
I think we shouldn't do a catch-all query but include the most common values. If some are missing there is always the chance to add them.

**Comment by gravitystorm** [comment]
> do we enforce a strict tagging scheme only allowing some specific values, or try to "catch them all"?

We must avoid catch-alls - see the final section of CARTOGRAPHY.md for an explanation.

**Comment by mkoniecz** [comment]
So long list of valid values is necessary. Preferably it would be list of all denominations fitting @mboeringa rule, except ones with typos.

**Comment by HolgerJeromin** [comment]
We can use

**Comment by mboeringa** [comment]
> So long list of valid values is necessary. Preferably it would be list of all denominations fitting @mboeringa rule, **except ones with typos.**

After your useful remarks, I corrected the typos in the list of the original post, and included the "greek_catholic" and "ukrainian_greek_catholic" in the list of denominations.

**Comment by kocio-pl** [comment]
Sounds interesting, it would be nice to see more detailed rendering of cross types.

**Comment by Tomasz-W** [comment]
icon link: https://github.com/gmgeo/osmic/blob/master/religious/christian-orthodox-14.svg

**Comment by Adamant36** [comment]
@kocio-pl Would be possible to maybe systematically go through and add icons for the religion/denomination tags like we did with shop types? And if so, can we put the icons in their own sub folder? I was just thinking the main symbols folder is getting a little messy. As it is, there are currently 9 religion related icons in it that could be put in a sub folder.  Then similar icons could be put there when need be. Instead of adding to the clutter in the main one.

**Comment by kocio-pl** [comment]
Sure, please create specific subfolder and change the style code accordingly. 

However I'm not sure what do you mean by "systematically go through and add icons for the religion/denomination tags like we did with shop types" - are there any icons missing (other than maybe orthodox christian cross)?

**Comment by Adamant36** [comment]
OK cool. On the shop thing I thought there was a meta ticket or something with a list of the ones that hadn't been rendered yet. I might of been confusing it with something else though, or Tomasz-W is just that good at coordinating things. As far as missing icons go, there is a lot of other Christian denominations that have their own symbols that could be turned into icons. I'm in the middle of compiling a list. I haven't looked into the usage numbers yet though. There's also a few more none Christian religions with symbols that we don't have icons for.

**Comment by sommerluk** [comment]
Honestly, apart from the cross in its normal or orthodox variant, currently I cannot imagine much other symbols for Christian denominations that I would reliably recognize as Christian. So I fear that, if we differentiate this much further by denominations, the map becomes unreadably (and therefore useless in this aspect) for everyone that is not an expert in symbology of Christian denominations – that would be bad for a general-purpose map that we are.

**Comment by dieterdreist** [comment]
sent from a phone

> On 26. Jul 2018, at 07:55, Lukas Sommer <notifications@github.com> wrote:
> 
> Honestly, apart from the cross in its normal or orthodox variant, currently I cannot imagine much other symbols for Christian denominations that I would reliably recognize as Christian.


a fish? It isn’t tied to one particular denomination, but neither is the cross.

**Comment by sommerluk** [comment]
> a fish? It isn’t tied to one particular denomination, but neither is the cross.

Exactly. That’s my point. The cross isn’t tied to one particular denomination, but it’s easy to recognize. When we substitute it by many different seldom-used unknown symbols individually for each denomination, then the normal map user will not recognize it at all – neither as a particular denomination nor as Christian in general. And that would be worse than the current situation.

Here is also the difference with shop icons: When I see a shop icon that I don’t recognize, I still know at least that it is _some_ type of shop because the purple colour is only used for shops, so that’s not worse than the generic dot icon. But when we would substitute the cross symbol by seldom-used not-well-known symbols, I cannot know that it is at least a church or a place of worship – because black is not exclusively used for churches, but for many other facilities.

**Comment by dieterdreist** [comment]
sent from a phone

> On 26. Jul 2018, at 14:19, Lukas Sommer <notifications@github.com> wrote:
> 
> Exactly. That’s my point. The cross isn’t tied to one particular denomination, but it’s easy to recognize. When we substitute it by many different seldom-used unknown symbols individually for each denomination, then the normal map user will not recognize it at all – neither as a particular denomination nor as Christian in general. And that would be worse than the current situation.


While the cross isn’t tied to a specific denomination, there are specific denominations who refuse to identify with the cross. Putting religious symbols as markers on our map which do not represent the feature, are problematic in general, and worse if it is about religious identity.

On the other hand I agree that the cross is the best symbol for most christians, commonly recognized everywhere (not just by christians).

**Comment by HolgerJeromin** [comment]
> specific denominations who refuse to identify with the cross

jehovahs_witness is not rendered with a cross #1079
do you have other examples?

**Comment by Adamant36** [comment]
Fishes are kind of associated with Evangelicals. Although I would question if that is really a unique denomination or just a particular movement within churches in general. 

There are a few religions that use the kneeling icon, who don't seem to kneel in front of alters as part of their religious practice at all or mainly if they do. and kneeling. For instance, Jains worship in a sitting meditative posture, Unitarians are none religious and don't kneeling in front of alters that I know of, and    Scientologists don't either (although there is only a number of their churches mapped right now, I could see it being an issues in the future). Jains already have an icon proposed for them and it might be worth using it. Even if the number of churches currently mapped is only a few hundred. The other two could wait, but id like to at least see a Unitarian icon even if the numbers are low. Having a maybe not recognizable icon is better then having one that doesn't properly represent the religion. Maybe they could be turned into dots with a uniform color at least though. 

On the Christian side there are more denominations that use a variation of the cross that we could add a unique icon for that would still be recognizable but help distinguish them.  

Maronite (85): Cross symbol

Apostolic (427) and New Apostolic (1494): Cross and sun symbol

Pentecostal (6440): Cross and flame symbol	

Church of Christ (248) and United Church of Christ (199): Cross and crown symbol

Methodist (16,659) and United Methodist (516): Cross and flame symbol

Maronite's have a unique cross symbol also but there is only 80 of them mapped at this point. 

There is also 40,000 Baptist churches and their symbol is a bible and the sun. 

Then there is the Quakers  (400 uses), who are based on Christianity but go out of their to say they are a fellowship or gathering, not a church. Plus, they don't use a cross or kneel in front of alters.

**Comment by matthijsmelissen** [comment]
> So I fear that, if we differentiate this much further by denominations, the map becomes unreadably

I agree. For this reason, I am going to close this issue.

**Comment by Adamant36** [comment]
I think this shouldn't of been closed and that it is worth rendering the original proposal at least. There's no reason adding one more cross has to be a slippery slope to rendering every religion. There's zero reason my advice on it has to be followed or that me suggesting other religious things that could be render means the whole thing should be thrown out. %100 ignore my thing and just render the original proposal. I'm perfectly fine with that. It seems like there was support for it. 

Ultimately, the conversation about it was valuable for future generations of mappers. Even if nothing else aside from orthodox cross gets rendered. Closing an issue 2 months later based on a personal preference is pretty uuggghh though.

**Comment by Tomasz-W** [comment]
After looking at a https://wiki.openstreetmap.org/wiki/Tag:religion%3Dchristian , I'm leaning to not adding dedicated icon for any of denominations. I know that current cross is not exactly a symbol of some denominations included in christianity, **but** if we add dedicated icon for one particular denomination, it would be not fair for other believers to not adding it for all the rest. Of course adding tens of special icons for all christian denominations is an absurd. I'm fine with religion=* level.

**Comment by jeisenbe** [comment]
I agree with not rendering an icon for each denomination.

We also discussed the same issue about the Jehovah's Witness denomination
tag this week, where there was also agreement against a more specific icon:
https://github.com/gravitystorm/openstreetmap-carto/issues/3282 ; so I
imagine that's why both these issues were closed together?

As argued above, an international, general-use map needs to be as neutral
as possible. If an eastern Orthodox Christian place_of_worship is rendered
differently, each similar category also needs a different icon. That would
be too much detail. And most denominations do not have a commonly used,
recognizable symbol.

Similarly, there are different schools, sects or traditions within Islam,
Hinduism, Buddism and other religions which are currently tagged with
"denomination." To be neutral, we would need an icon for every major
division of these religions as well. They would probably be tagged more
often if we had a better tag name ("Sunni" isn't a "denomination"). The
wiki pages shows 39 Jewish "denominations", 23 Buddist schools, 9 Muslim
groups, 5 Hindu subdivisions, etc:
https://wiki.openstreetmap.org/wiki/Key:denomination

Can each of these get a different symbol? I don't think it would be helpful
for mapper feedback or general map usability.

**Comment by jeisenbe** [comment]
Is Scientology as a Christian denomination? It's not on the list of
denominations in the Wiki. What tag is being used?
I only managed to find 4 uses in taginfo:
https://taginfo.openstreetmap.org/keys/?key=denomination#values
The Scientology building in Los Angeles as a cross on top, and they call
themselves a church, but their status as a religion is disupted, let alone
status as a Christian denomination.

I've not heard of Janeism. Do you mean Jainism?  It should be tagged
religion <https://wiki.openstreetmap.org/wiki/Key:religion>=jain
<https://wiki.openstreetmap.org/wiki/Tag:religion%3Djain>
In which case it would not be rendered with a cross, which is only used for
religion=christian

**Comment by Adamant36** [comment]
I dont remember now. It was a while back. I think it was that jainism and scientology both have the kneeling symbol when they dont kneel at an alter. Although the jains might, but I know scientologists dont.

In the Christian denominations though there is the quakers. They dont use the cross and they go out of their way to say they arent a Christian church. They consider themselves a "fellowship of friends." Whatever that means. So the cross isnt right for them. Like I said though, it can be brought up in another issue eventually if need be. Im fine with that.

**Comment by dieterdreist** [comment]
sent from a phone

> On 16. Sep 2018, at 10:03, Tomasz Wójcik <notifications@github.com> wrote:
> 
> Of course adding tens of special icons for all christian denominations is an absurd.


just because the cross is not working for very few exceptions does not mean every christian denomination should have a distinctive icon. The osm distinction between denomination and religion for the classification of theological beliefs must not necessarily be the same than how the people of these beliefs see them, some exceptions could be justified, it doesn’t imply we have to question everything.

**Comment by Adamant36** [comment]
Where was it implied in the discussion that every denomination should have its own icon. I don't think making special icons for the few exceptions where its needed has to be a slippery slope to rendering everything religious with its own unique icon. Me researching the numbers etc wasn't necessarily because I thought as much either. Its better to either not render an icon or have an obscure one for a group like the Quakers though, who have gone out of their way to distance themselves from normal Christianity, then to give them a cross that doesn't fit them. Id say the same for religions that are represented by kneeling when they don't kneel.
