### ISSUE TITLE
Icon outlines

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1189]
We might need outlines or halos around icons to make them distinguishable from the background. Especially since landuse colours are so saturated. See https://github.com/gravitystorm/openstreetmap-carto/issues/325#issuecomment-68612835 (second image) for why this might be needed.

Outlines cannot be part of the SVG (as Maki does for some icons) otherwise re-colouring with `marker-fill` won't work as intended. Unfortunately, `marker-line-` rules only work for markers that are specified with `marker-type`.

I have thought of stacking outline and fill with two separate SVGs. This has several drawbacks: First, we need two SVGs. The one comprising the outline has to be slightly bigger and should not have any inner holes. Second, we need to use `marker-allow-overlap: true`, which also allows overlap with any marker nearby. So this apparently does not work.

Did I miss something? IMO it would be easiest to be able to use `marker-line-` rules. I'm not sure if this is even technically possible. Should this be reported upstream?

Follow-up: If https://github.com/mapnik/mapnik-support/issues/27 and https://github.com/mapnik/mapnik/issues/2609 are related then at least Mapnik 3 could support it.

**Comment by nebulon42** [comment]
I still think this is rather important, but there was no support for it. A pity. Closing this.

**Comment by StyXman** [comment]
I have an update, I think, about this.

`mapnik` now supports marker stroke, stroke-width and stroke-opacity, which impacts the SVG stroke. The issue is that a stroke of N pixels means that half of those N pixels 'invade' the fill, while the rest become a 'halo'.

One thing that could be implemented is to add another layer with the same data and, for a halo of N pixels, set the stroke width to 2N. This of course means duplicating the layers, maybe it can be optimized with caching?

I also opened mapnik/mapnik#4246 , but I don't expect this to bubble up the stack (mapnik -> carto -> osm-carto) any time soon :(

**Comment by StyXman** [comment]
I hit mapnik/mapnik#4247 :(
