### ISSUE TITLE
too strong color for leisure=pitch, leisure=track

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1190]
It was noticeable before, now after building colour change it is quite bad. leisure=pitch, leisure=track should have muted/paler colour.

http://www.openstreetmap.org/#map=14/50.0735/19.9205

![selection_004](https://cloud.githubusercontent.com/assets/899988/5605157/1512299e-93ec-11e4-9916-ca9346d8b3d7.png)

**Comment by nebulon42** [comment]
Definitely, but I would also suggest considering desaturating all landuse colours so that they work better with the new buildings colour. I know that this is not the easiest task to do, though.

**Comment by math1985** [comment]
The landuse colours have been desaturated a lot already recently. Do you think all of them are too saturated, or some in particular?

**Comment by SomeoneElseOSM** [comment]
The colours that are used for "very large landuses where there are other things mapped" (e.g. farmland) are definite candidates.  Farmland at F4EBDF works quite well for me, but other similar ones (large landuses that are often adjacent to farmland) would need to change too.

**Comment by nebulon42** [comment]
> The landuse colours have been desaturated a lot already recently.

I didn't know that. I really like the lighter building colour. I also think that built-up landuse like residential, industrial, retail, commercial could use a bit fine-tuning so that they work better with the new building colour. Overall, landuse colour should be paler (also farmland, forest, grass/meadow). The colour @SomeoneElseOSM suggested for farmland is not bad.

But this needs more discussion, obviously. For now I would propose to adjust residential, industrial, retail, commercial and maybe construction and grass/meadow. Sorry for hijacking this issue, but I had a quick try:

![landuse_color_small](https://cloud.githubusercontent.com/assets/3531092/5606670/f958b8dc-9439-11e4-9944-25da6b43cef6.png)

Please note that the building outline is 5% darker on the right than on the left.

Some map previews:
http://www.openstreetmap.org/#map=17/48.21009/16.24593
![bildschirmfoto vom 2015-01-04 17 50 19](https://cloud.githubusercontent.com/assets/3531092/5606681/437ea7c8-943a-11e4-942b-829ce3946fe2.png)

http://www.openstreetmap.org/#map=16/48.1859/16.3825
![bildschirmfoto vom 2015-01-04 17 52 15](https://cloud.githubusercontent.com/assets/3531092/5606688/7dfc0b7a-943a-11e4-84b2-38e67037b1c3.png)

http://www.openstreetmap.org/#map=16/48.1758/16.4014
![bildschirmfoto vom 2015-01-04 17 53 49](https://cloud.githubusercontent.com/assets/3531092/5606695/ab21f452-943a-11e4-9698-381819aca887.png)

**Comment by daganzdaanda** [comment]
@nebulon42, I like your improvements. But maybe open a new issue for that?

**Comment by math1985** [comment]
For pitches, we could add icons like the [French rendering](http://tile.openstreetmap.fr/?zoom=16&lat=52.07577&lon=5.15176&layers=B0000000FFFFFFF) does. Perhaps than the colours don't need to be that distinct anymore.

**Comment by kocio-pl** [comment]
I like the french touch =} and agree that colours would not be that important then - the shape of pitch lines will be the key recognition feature.

**Comment by oddityoverseer13** [comment]
:+1: to the pitch lines from the french rendering. Any chance this could be added soon?

**Comment by pnorman** [comment]
> :+1: to the pitch lines from the french rendering. Any chance this could be added soon?
I thought we had an issue for that. Anyways, if you prepare a pull request then I can throw up some previews if needed to test the assortment of pitch combinations.

**Comment by kocio-pl** [comment]
The color is quite good, since even after modifications is still recognizable ([construction color does not work so good on lower zooms](https://github.com/gravitystorm/openstreetmap-carto/issues/2353)).

On sport centers (and other bigger campuses) even if they are weaker, there is no loss of visibility - z14:

Before
![rl5syqfs](https://cloud.githubusercontent.com/assets/5439713/18732722/d827f21c-8065-11e6-82a5-a41b2bf4314d.png)
After (lighten 5%, desaturate 5%)
![ib atgcj](https://cloud.githubusercontent.com/assets/5439713/18732725/db36cc1c-8065-11e6-9753-8222330caf75.png)
After (lighten 10%, desaturate 5%)
![cadu4hhn](https://cloud.githubusercontent.com/assets/5439713/18732733/ea86a930-8065-11e6-90b4-733fc9454eee.png)

On plain residential area with schools (small campuses) they are not so dominant any more - z15:

Before
![xbq0beaf](https://cloud.githubusercontent.com/assets/5439713/18732963/63875e8c-8067-11e6-9753-b6d572d4065b.png)
After (lighten 5%, desaturate 5%)
![z vgz7gv](https://cloud.githubusercontent.com/assets/5439713/18732945/45b4de98-8067-11e6-976a-2b5d214b706e.png)
After (lighten 10%, desaturate 5%)
![r8pvg6kc](https://cloud.githubusercontent.com/assets/5439713/18732927/24f8971c-8067-11e6-8c55-533e5ebe5bd9.png)

On z16 their visibility is back to normal on small campuses, despite being less strong - see also rare case of pitch on the residential area:

Before
![icbviglj](https://cloud.githubusercontent.com/assets/5439713/18733086/57500668-8068-11e6-94de-5f6fe580af9d.png)

After (lighten 5%, desaturate 5%)
![kvhfg7mq](https://cloud.githubusercontent.com/assets/5439713/18733092/5f8d9ffc-8068-11e6-8583-61b196350ff0.png)

After (lighten 10%, desaturate 5%)
![cinlxdhd](https://cloud.githubusercontent.com/assets/5439713/18733093/65fba866-8068-11e6-9e28-0964afcdf60e.png)

Another quite common case, pitch on a grass - z17:

Before
![sxk3imoq](https://cloud.githubusercontent.com/assets/5439713/18733246/7cb605c8-8069-11e6-9e73-9573d31553f5.png)
After (lighten 5%, desaturate 5%)
![ilz qryz](https://cloud.githubusercontent.com/assets/5439713/18733247/7f89ace6-8069-11e6-84cf-cef4bc66dc68.png)
After (lighten 10%, desaturate 5%)
![tdbjltf3](https://cloud.githubusercontent.com/assets/5439713/18733249/81afcfd2-8069-11e6-84f6-17428f36f424.png)
