### ISSUE TITLE
Junction=motorway_junction names are hard to read

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#1272]
Junction=motorway_junction names are hard to read. [Example](http://www.openstreetmap.org/#map=13/49.6328/5.9589).

**Comment by daganzdaanda** [comment]
Slightly OT: I'm a bit annoyed when all the names appear twice or more, see a bit further east: http://www.openstreetmap.org/#map=15/49.5886/6.0880
I believe there's no way we can change that with Carto-CSS. But are there any suggestions what could be done about that? If there were a relation that groups all the exits, could we let the name of the relation show once and don't show all the exits?

**Comment by gravitystorm** [comment]
@daganzdaanda There are at least six nodes marked as junctions there, when there is only one junction overall. There should only be one OSM element for the one feature.

It should be discussed elsewhere (e.g. tagging@) how best to tag junctions so that you don't repeat the main tag everywhere (c.f. station micromapping without using railway=station nodes on every platform)

**Comment by matkoniecz** [comment]
Is this change improving situation?

![selection_003](https://cloud.githubusercontent.com/assets/899988/8812196/fecfdd10-2ffa-11e5-9d5f-cfdf639197e5.png)

larger before/after: https://cloud.githubusercontent.com/assets/899988/8812174/e1363fec-2ffa-11e5-92c8-050c64d8204f.png

Personally I have no trouble with reading these names. I consider the new version a bit more readable, but I am clearly biased.

**Comment by matkoniecz** [comment]
@math1985 ping

**Comment by math1985** [comment]
Yes, I think it's much better now,
