### ISSUE TITLE
background color for amenity=social_facility

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#1295]
Current configuration on osm.org does not highlight the area: http://osm.org/relation/4568610
Proposing to handle it just like amenity=university.

**Comment by dieterdreist** [comment]
2015-02-07 21:59 GMT+01:00 jengelh <notifications@github.com>:

> Current configuration on osm.org does not highlight the area:
> http://osm.org/relation/4568610
> Proposing to handle it just like amenity=university.
>


-1, these are clearly very different. While universities are almost always
very important (even if you don't want to go there, they are often known by
lots of people and typically big, and can serve for orientation), while
social facilities come in every size and importance level imaginable.

**Comment by kocio-pl** [comment]
Universities can be also private university-level schools and we have it a lot in Poland - some are big (multi-building with the common area), some other are just using rented office space. I also know about social facilities that are located in such a rented space and also big like a school - especially orphanage.

And the ruke is simple - if it is small, no amenity background (just POI or building), if big - the background should be used. So no need to virtually differentiate both types by definition - the size will speak for itself.

**Comment by dieterdreist** [comment]
2015-02-18 14:16 GMT+01:00 kocio-pl <notifications@github.com>:

> Universities can be also private university-level schools and we have it a
> lot in Poland - some are big (multi-building with the common area), some
> other are just using rented office space. I also know about social
> facilities that are located in such a rented space and also big like a
> school - especially orphanage.




in my understanding, these would not be "universities" but "colleges".

**Comment by kocio-pl** [comment]
So I have to get deeper into anglo-saxon conventions of educational system. Once again there's something not clear and universal enough to me.

However it's irrelevant in this case. I sustain my claim, that if something like this is big enough, it should be shown and we don't have to judge it beforehand, because if we have the area with amenity=social_facility tagging, we can be sure it's about the right size. For example [orphanage may look just like a regular school with a pitch](http://www.openstreetmap.org/way/304204007) or [the social facilities can be grouped together in one fenced location](http://www.openstreetmap.org/way/39230878). If they are just inside the building or have no area to tag outside the building, we would treat automatically them the same as schools with no additional area.

Also amenity=childcare can also look like kindergarten with a playground, so i would add it too.

**Comment by matkoniecz** [comment]
I think that it is impossible to continue increasing number of different landcovers.

Using the same colour as educational/hospital areas seems to be a poor idea - this way it will not mean anything.

I close this as it is not really possible to render more landcovers.

**Comment by polarbearing** [comment]
The boundary should be shown as outline, the style shared with things like community_centre or hospital, see also discussion in #506 and #1624.

**Comment by pnorman** [comment]
> I propose to close this as it is not really possible to render more landcovers.

Yes - we're really past the limit of what is sensible

**Comment by polarbearing** [comment]
I would have found it more sensible to widen the title to "add area for social_facility" and keep boundaries in mind. Currently amenity=social_facility does not even get a label rendered.

**Comment by kocio-pl** [comment]
Light yellow background ("societal amenities") is now introduced by #2981.
