### ISSUE TITLE
Rendering highway=crossing

### ISSUE THREAD

**Issue by furban1** [gravitystorm/openstreetmap-carto#1318]
Would it be possible to render highway=crossing in the map?

**Comment by mkoniecz** [comment]
http://tile.openstreetmap.fr/ renders this tag

![selection_001](https://cloud.githubusercontent.com/assets/899988/6314090/74be7e8a-b9ce-11e4-9939-b0c69a706eb1.png)

**Comment by kocio-pl** [comment]
Nice, I would like it to have on the default OSM map. I'm only interested what to do with crossing=unmarked (and crossing=no)?

**Comment by furban1** [comment]
Great.

I think crossing=unmarked make no sense to render. Same with crossing=no

This crossing here (only for pedestian) is tagged as 
highway=crossing
crossing=traffic_signals
and should be shown as a traffic light with two lights as it will be shown in JOSM 

![auswahl_017](https://cloud.githubusercontent.com/assets/11025901/6318076/941f7384-ba7c-11e4-8ec0-6f01cd2e816c.png)

highway=traffic_signals
crossing=traffic_signals
should be a traffic light with three lights

**Comment by daganzdaanda** [comment]
That looks nice, but it only shows up on z=20. The main map only goes to 19. (The zoom scales seem to be a little different?)

**Comment by matkoniecz** [comment]
From looking at fr map I am not convinced that it improves map.

It is not conveying any additional information beyond what is showed by mapped footways and cycleways and is misleading (the same style for marked pedestrian crossings, unmarked pedestrian crossings, footway+cyclist crossing, cyclist only crossings...).

Separate rendering for every single crossing style would be nigthmare.

The only potential benefit would be in areas where people are using sidewalk tag instead of mapping footways as separate objects what for me is not convincing (if anything, encouraging this style of tagging for me would be a negative effect).

**Comment by twzkxkan** [comment]
This is a good idea, I hope it is implemented.

**Comment by d1g** [comment]
> From looking at fr map I am not convinced that it improves map.

@mackerski, it may be that implementation is not the best.

if crossing was tagged as single node with tags instead of separate way (as it should) then at least this partial information should be rendered to aid who walks on foot (everyone). Question is only about size of icon and zoom levels.
