### ISSUE TITLE
amenity=conference_centre on an area removes name rendering

### ISSUE THREAD

**Issue by ianmcorvidae** [gravitystorm/openstreetmap-carto#1431]
Recently I added this tag to the Tucson Convention Center (http://www.openstreetmap.org/way/34618996), in http://www.openstreetmap.org/changeset/29607695. Previously, with just landuse=commercial (which was not removed), the name rendered fine. With the addition of this it has stopped rendering. A gnis:feature_id was also added but I suspect this isn't the issue.

Expected behavior would be for the name to continue to be rendered, presumably as before (for landuse=commercial) or similarly.

**Comment by math1985** [comment]
I think this has been fixed already by #1349, which has been merged and will be soon rolled out.

"Checking the condition in the COALESCE is necessary to prevent unrendered tags blocking rendering of tags further down in the COALESCE."

If this problem is not resolved after the next version is rolled out, let us know and we will reopen the issue.

**Comment by ianmcorvidae** [comment]
Will do. Is there a way I can track when the version is rolled-out?

**Comment by math1985** [comment]
Yes, watch for the 'Update carto stylesheet to v2.28.1' line on http://git.openstreetmap.org/chef.git/. We normally also post a message to the [talk](http://lists.openstreetmap.org/pipermail/talk/) mailing list.
