### ISSUE TITLE
How to treat island labels on z4–z6?

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#1448]
Island labels start currently at z7.

@imagico had proposed to render it starting from z4. This would render labels on some very big islands, e.g. Spitzbergen.

Currently, for low zoom levels, this feature is part of the layer with the id: "text-poly-low-zoom". This layer renders only z7–z9. So I suppose when we want this, we need a new layer? How would that influence the performance? How is the policy for on low zoom levels? Would this interfer with other things on low zoom levels?

Would it make sense to render place=archipelago also? (But is not supported by osm2pgsql? 134 relations with this attribute.)

**Comment by imagico** [comment]
Since many islands at the moment have a label of an administrative unit, often wrong because it refers to a unit the island only belongs to, see for example:

http://www.openstreetmap.org/#map=4/79.07/47.99
http://www.openstreetmap.org/#map=7/30.458/-18.127
http://www.openstreetmap.org/#map=7/-57.880/-28.169

it would make sense to consider these two labeling problems together.

Rendering place=archipelago should be fairly easy in principle.  However the label of an archipelago should not be placed on one of the islands but somewhere near its center, possibly even over water.

**Comment by imagico** [comment]
I think now that we got rid of the multiple labels for admin multipart admin unit polygons it is much clearer where this would improve the map.  Examples where this would be nice to have:

http://www.openstreetmap.org/#map=6/-0.736/110.720
http://www.openstreetmap.org/#map=5/76.614/-100.327

http://www.openstreetmap.org/#map=6/78.864/17.688
http://www.openstreetmap.org/#map=6/79.642/95.713
http://www.openstreetmap.org/#map=6/73.846/57.678
http://www.openstreetmap.org/#map=6/74.894/141.812

http://www.openstreetmap.org/#map=6/-71.403/-72.246

z4 labels would be mostly of interest for archipelagos and less for individual islands (except for Canada and Indonesia).  It would be interesting to check if labeling archipelagos using `ST_PointOnSurface(ST_ConvexHull(way))` would be all right or if it leads to problem in some cases.

**Comment by kocio-pl** [comment]
What if we try [the same solution as with water area labels](https://github.com/gravitystorm/openstreetmap-carto/issues/1604#issuecomment-332697715)? I mean: start rendering island labels from z0, because we already use the same area limit (>3000). I would relax initial zoom level also for islets - if they are big enough to handle label, just render it there.

**Comment by kocio-pl** [comment]
OK, z0-z3 does not make sense, because we have no land labels before z3, and on z3 islands would compete with countries, so I support original call for z4+ for islands (Kosmtik export is not working again, so using shiny new Firefox screenshots feature):

Nunavut, Canada

z3
Before
![screenshot-2017-10-14 openstreetmap carto kosmtik before](https://user-images.githubusercontent.com/5439713/31573338-f608e464-b0b9-11e7-820a-883d1a106545.png)
After
![screenshot-2017-10-14 openstreetmap carto kosmtik after](https://user-images.githubusercontent.com/5439713/31573343-15c27f04-b0ba-11e7-9d64-a4ada150f0b0.png)

z4
Before
![screenshot-2017-10-14 openstreetmap carto kosmtik](https://user-images.githubusercontent.com/5439713/31573345-1e7aaf2c-b0ba-11e7-8dc7-5c594d989f99.png)
After
![screenshot-2017-10-14 openstreetmap carto kosmtik 1](https://user-images.githubusercontent.com/5439713/31573348-24c4e1f4-b0ba-11e7-9cb5-d8a43dd358e9.png)

**Comment by kocio-pl** [comment]
Spitzbergen would be not visible anyway, because it's tagged as a node currently:

http://www.openstreetmap.org/node/269078675#map=5/77.934/20.149

but some smaller island around would be from z4:

![screenshot-2017-10-14 openstreetmap carto kosmtik 2](https://user-images.githubusercontent.com/5439713/31573465-291b599c-b0bd-11e7-8e69-50a5f8b2d478.png)

**Comment by math1985** [comment]
+1

**Comment by kocio-pl** [comment]
I've just fixed the island relation for Spitsbergen, because it was there already, but not complete, so now it should also render the label:

http://www.openstreetmap.org/relation/1124190
