### ISSUE TITLE
*_link highways now rendering above 'normal' highways

### ISSUE THREAD

**Issue by rickmastfan67** [gravitystorm/openstreetmap-carto#1456]
https://www.openstreetmap.org/#map=16/40.4500/-78.8399
https://www.openstreetmap.org/#map=16/40.4898/-78.7496
https://www.openstreetmap.org/#map=17/40.44787/-78.43308

This looks pretty ugly IMO.  Seems something got changed in the last update to the map style that shouldn't have been.  Know this is happening with 3 of the 5 *_link type highways.  Still looking for tertiary & secondary bugged ones.

Hope this can be an easy fix to get it back to where the *_link renders under the main highways again.

**Comment by math1985** [comment]
Introduced by https://github.com/gravitystorm/openstreetmap-carto/commit/80a990a9e4706f09a04575165db4f076702ac613. I don't spot right away what causes this, @pnorman could you have a look at it?

**Comment by pnorman** [comment]
It's another subtle difference issue where the same thing is named differently at different points in the old query.

In the old query in the inner subselect  a link road would be `highway_primary_link` for the JOIN with the ordering table but would be `highway_primary` with link true in the feature column. Because this is fairly subtle (i.e. it took several reads to spot it, expecting it might be a related problem), I missed it when refactoring.

It's not immediately obvious to me how to best fix this. Adding _link to the feature column generation would solve it, but require changes to the MSS.

**Comment by math1985** [comment]
Thanks, also explains why I missed it when reviewing.

**Comment by math1985** [comment]
>  Adding _link to the feature column generation would solve it, but require changes to the MSS. 

That's a rather serious performance penalty (loads of duplicated layers in the .osm), so I'd prefer to avoid that.

**Comment by pnorman** [comment]
I wonder if we should move the order logic from the table to an `ORDER BY` clause. Otherwise we would need a ordering table with feature, link, prio.

**Comment by math1985** [comment]
This is still open, right? Would really need to be fixed, either way, before the next release.

**Comment by pnorman** [comment]
> This is still open, right?

Yes. I think the best approach is to move the order logic to an `ORDER BY` but haven't done anything about making a patch

**Comment by gravitystorm** [comment]
An alternative is to move the trimming of _link into the final wrapper select, so instead of `select *` do e.g.

```
        (SELECT way, (CASE WHEN substr(feature, length(feature)-3, 4) = 'link' THEN substr(feature, 0, length(feature)-4) ELSE feature END) AS feature, horse, foot, bicycle, tracktype, access, construction, service, oneway, link, layernotnull
          FROM ( -- subselect that contains both roads and rail/aero
            SELECT
                way,
                ('highway_' || highway) AS feature, --only motorway to tertiary links are accepted later on
                horse,
```
This means that the roads/rail/aero subselect contains unmanipulated highway values, and so joins correctly onto the joining table. The downside is a repetition of column names.

Thoughts? I tested this an it Seems To Work(tm).

**Comment by math1985** [comment]
Yes, fine with me. Could you write a PR?

**Comment by math1985** [comment]
As nobody has written a PR to fix this bug in the meanwhile, and it looks quite bad, I would propose to roll back the changes that originally caused this.

**Comment by pnorman** [comment]
Hoping to look at this on the weekend.

**Comment by gravitystorm** [comment]
I've made a PR with the change that I proposed, hopefully @pnorman can review it and/or propose a different way of fixing it.

**Comment by rickmastfan67** [comment]
Thanks for getting this fixed!  Rending is back to normal with *_link highways and looks 10x better. :)
