### ISSUE TITLE
Station area / station building / platform rendering issues. 

### ISSUE THREAD

**Issue by javbw** [gravitystorm/openstreetmap-carto#1457]
railway=station on an area causes other things inside the area not to be rendered. also, over-track stations (I assume they are common throughout the world) disappear under platforms. Platforms should follow the layer= tag, and railway=station on an area should behave like a landuse - as often the station's amenities are much larger than the station building (parking, taxi/bus circles, multiple entrances) but it is currently a fight between highway=pedestrian on an area and railways=station on an area, deciding who renders over everything else. For example, parking is not rendered over the station area. 

http://www.openstreetmap.org/search?query=maebashi%2C%20japan#map=18/36.38339/139.07296
Maebashi station - parking rendering error for the stations bus circle. This is an "undertrack" station, so the platforms being rendered over the station is fine. 

http://www.openstreetmap.org/search?query=maebashi%2C%20japan#map=17/36.37942/139.04747
Shimmaebashi Station. "Overtrack" station. the footpath bridge that goes from from the north over the tracks directly into the station's 2nd floor go into nothing. stairs down to the platforms similarly are orphaned. Platforms should either behave the layer tag.. or do I use tunnel=building_passage on the platform areas (and lines) under the building?  Shouldn't the building and the platforms use transparency?

This is an issue I noted in 2013(?) when I first started mapping, and it still seems to handle station areas and buildings really weirdly. 

Or am I just tagging things wrong?

**Comment by lest69** [comment]
According to [railway=station](http://wiki.openstreetmap.org/wiki/Tag:railway%3Dstation), it should be used on nodes only and not areas. If you want to map the landuse, use [landuse=railway](http://wiki.openstreetmap.org/wiki/Tag:landuse%3Drailway).

Is this style rendering railway=station areas? If it is, should it be? According to the wiki, it shouldn't.

**Comment by matkoniecz** [comment]
> According to railway=station, it should be used on nodes only and not areas.

Note that it is result of a recent edit http://wiki.openstreetmap.org/w/index.php?title=Tag:railway%3Dstation&diff=1140728&oldid=1115036

Significant usage on areas ( http://taginfo.openstreetmap.org/tags/railway=station )  indicates that this edit is likely to be against consensus.

**Comment by math1985** [comment]
> Note that it is result of a recent edit http://wiki.openstreetmap.org/w/index.php?title=Tag:railway%3Dstation&diff=1140728&oldid=1115036
> Significant usage on areas ( http://taginfo.openstreetmap.org/tags/railway=station ) indicates that this edit is likely to be against consensus.

So would you be able to revert it? The tendency in OSM to accept that the documentation on the wiki is wrong without trying to improve it is harmful for the project IMO.

**Comment by neiljp** [comment]
@matkoniecz @math1985 The edit was from a railway mapper, who knows of many issues with the area tagging, from what I remember and is heavily involved with working on developing railway tagging. I don't remember the details myself right now, but they can be contacted variously, including #OpenRailwayMap on OFTC, and the related mailing list, assuming there is one.

**Comment by matkoniecz** [comment]
@neiljp Probably tagging mailing list is a proper place, but before starting yet another discussion I would prefer to finalize some that are ongoing/finished - so I will not start a new discussion on this topic.

**Comment by Nakaner** [comment]
Hi,

thank you @neiljp that you notified me about this issue/discussion.

Railway stations (and halts) are mapped as nodes in German speaking countries (existing mapping as area has been changed to nodes for the last months) because there are three definition where the station's boundaries are.

1. Passengers describe the area around the platforms and the stations building as "the railway station". 
2. Freight customers would describe the neighbouring freight yard tracks as "the station". From railway company's point of view (1) and (2) are /one/ station. 
3. A railway enthusiast and railway staff (e.g. locomotiv drivers, people at the signal boxes etc.) have a third description of the station area. Usually all switches (in some countries, e.g. Germany, including the [entry signals](https://www.openstreetmap.org/node/2711611597/history)) are part of the station.

As a compromise, we decided not to map stations as areas. Stations should be mapped as a node near the platforms (even if they are not at the center of the area defined by (3)). A node near the platforms is the station, most people (i.e. map users) mean. If you need the area a station covers, you can calculate a convex hull around all members of the stop area relation (part of public transport tagging). For example, [OpenBusMap does this](http://openbusmap.org/?zoom=17&lat=48.99355&lon=8.40158&layers=TBTTT). (I think that OSM Carto does not have to do this, too, and should focus on more important topics)

Railway enthusiasts can map the station area (from entry signal to entry signal) as a polygon tagged with `landuse=railway`. A [operating site relation](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging#Operating_Site_.28Relation.29) connects [the station node](https://www.openstreetmap.org/node/2623664882/history) (`railway=station`), all [platform](https://www.openstreetmap.org/relation/4196831/history)s (`railway=platform` + `public_transport=platform`), all stop positions (`railway=stop` + `public_transport=stop_position`) and [the landuse area](https://www.openstreetmap.org/way/70908662).

There is another reason why adding bus stations to the station area is no good idea: Bus stations are usually operated by a different company than the railway infrastructure.

**Comment by javbw** [comment]
Thanks for the information Nanaker - I will read over it again to try to change my tagging. 

However, since I'm a novice and I've never made a relation, I have a question about the reasoning behind the method:

Every other single man-made structure can use a landuse=* or amenity=*, and the landuse can be named ( a school, hospital, business center, etc) since the individual buildings and amenities may have their own name.  Is there a reason a station doesn't follow that pattern? Is there a reason it can't be changed to be more in line with other OSM structure+landuse tagging?

The driveways, bus circles, taxi stands, walkways, parking, and other amenities belong to the station, therefore they should be included in the landuse - a public bus may have a bus stop at a mall, but the mall, it's driveways, parking, and that bus stop are all on the single landuse - so why should it matter if the bus stop is on the station's landuse? Is this just because I have railway=station on the area, and it is treated differently? I guess that relation ties it all together - but landuse=railway could be used for anything railway related - does the fact that a station node is inside the landuse or included in the relation make the landuse rendered differently? I would hope station area is rendered differently than just rail lines or yards, to help show where the station is and visually indicate where different access paths lead into it. 

I may not be able to correctly identify the entry/exit points on the railway line, but I can approximate it pretty well (which is better than nothing)  

What about the absolutely horrible rendering of platforms and station buildings? There's currently no transparency with the station buildings or the platforms, so showing what level they are at in -carto is impossible - which is why I chose these two sequential stations - they are the opposite of each other (track over station and station over track) - and one is dependent on clearly showing the footbridges that cross the tracks to access the station, but is rendered very poorly, so it is not possible to understand the connections between the station buildings, the platforms, and the walkways that connect them to the rest of transportation network. 

Is this rendering problem (platforms/ station building) a result of my incorrect tagging, or is this transparency issue between platform and station truly a rendering error?

**Comment by Nakaner** [comment]
`landuse=railway` is the area used for railway purposes and covered by tracks, disused tracks, locomotive sheds, stations building etc. but not by public roads. See the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Drailway) (no major  modification of content for about 5 years). The area in front of the station (bus stop, taxi booth, car parking, green space) does not fit this definition.

To describe that this area add the taxi booth and bus stop as separate objects (maybe `amenity=bus_station` if it is a large bus stop). You can add these objects to a [stop area relation](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area) to connect it to the station.

At railway infrastructure tagging to stations/halts are separate objects if they (the infrastructure, not the routes) are operated by different companies, are different train systems (e.g. a narrow gauge railway network and a national railway network) and/or have different names ([example](https://www.openstreetmap.org/#map=18/49.18849/9.21922)).

**Comment by matkoniecz** [comment]
@javbw It seems to be already reported as #327 (I closed that ticket as it seemed to be fixed). Can you confirm this?

**Comment by javbw** [comment]
Yes, This is the same issue. I was unfamiliar with Github to find my old ticket. I did search through tickets, but I guess I failed at finding it.

**Comment by matkoniecz** [comment]
In this case it is my fault, as I mistakenly closed it.
