### ISSUE TITLE
natural=* covered by freshwater or oceans treated inconsistently?

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#1473]
works nicely:
https://www.openstreetmap.org/way/336816028#map=17/46.18740/8.75470
there is bare rock on both sides of the rivers and also underwater.  The rendering is fine.

The same does not appear to work for natural=bare_rock which is across natural=coastline
and partly underwater - the whole area is rendered as rock and water is not shown
in that place.

What is right? Should we use something like natural=underwater:bare_rock ? Could
the rendering be made consistent whether the water is natural=water or natural=coastline?

**Comment by matkoniecz** [comment]
I would expect that rock areas under ocean/seas would not be tagged as natural=bare_rock, but http://wiki.openstreetmap.org/wiki/Tag%3Anatural%3Dbare_rock is not making it explicit.

> Could the rendering be made consistent whether the water is natural=water or natural=coastline?

The problem is that ocean/seas are not rendered - everything is assumed to be water and land areas is rendered over blue background. Than landcovers are rendered, with small water areas rendered on top.

It seems that this issue fits rather wiki/tagging mailing list - see my proposal on http://wiki.openstreetmap.org/wiki/Talk:Tag:natural%3Dbare_rock (please, continue discussion about how things should be tagged there, not on this bugtracker),

**Comment by RicoZ-OSM** [comment]
I have already asked the mailing list some time ago 
    http://permalink.gmane.org/gmane.comp.gis.openstreetmap.tagging/23465 

Fact is, there is an inconsistency between oceans and lakes/rivers in carto. Can that
be fixed? Should that be documented as unfixable?

**Comment by matkoniecz** [comment]
> Should that be documented as unfixable?

I think #426 is good enough for that purpose.

**Comment by matkoniecz** [comment]
See also #115 for very similar problem, but with reporter excepting exactly different handling of natural=* key.

**Comment by RicoZ-OSM** [comment]
there is also natural=cliff which is  rendered across rivers and ought to be, otherwise waterfall rendering would be pretty bad (nonexistent)..

Otoh for features like natural=wood, landuse=forest or natural=bare_rock it seems like a terrible fate to have to split them at every stream/riverbank.

So if needed for consistency it would be easier to add/honour a special tag for waterfall cliffs than dealing with forests being split at every creek.

**Comment by matkoniecz** [comment]
Creeks are not a problem as these are mapped as lines, not as areas (water as lines is displayed after various areas).

**Comment by RicoZ-OSM** [comment]
The areas do not seemto be a problem either.. afaics it just works. It would be even stranger to differentiate between plain rivers (lines) and rivers with riverbanks (areas).

**Comment by RicoZ-OSM** [comment]
Another somewhat related discussion http://wiki.openstreetmap.org/wiki/User_talk:RicoZ#Water_level_-_Over.2CUnder.2CIn_Between...

**Comment by jeisenbe** [comment]
This will be solved by #3738, I believe.

**Comment by jeisenbe** [comment]
The issue with bare_rock in particular is also solved by #3851

**Comment by jeisenbe** [comment]
Since #3738 `natural=water`, `waterway=riverbank` and the oceans (areas outside of the coastline) are rendered together, above the `landcover` layer, so the original issue is fixed
