### ISSUE TITLE
Building covers it's own label

### ISSUE THREAD

**Issue by brycenesbitt** [gravitystorm/openstreetmap-carto#1494]
This rendering looks wrong:

![selection_201](https://cloud.githubusercontent.com/assets/1294423/7259284/20912fca-e817-11e4-8bbb-ed60bf86fe10.png)
building=yes
leisure=horse_riding
name=Valley Horse Stables

https://www.openstreetmap.org/way/180609927/history

**Comment by math1985** [comment]
I think it's a caching problem - the tile on the right is new and the tile on the right is old. The label is not actually covered by the building, on the right it's just not rendered yet and the tile border happens to be at the same place as the building edge.

The right tile is updated too by now, so now the problem is gone.
