### ISSUE TITLE
Some streets that are not joining may on zoom out misleadingly appear to be joining #286

### ISSUE THREAD

**Issue by pmailkeey** [gravitystorm/openstreetmap-carto#1511]
![image](https://cloud.githubusercontent.com/assets/11827386/7429161/7f8c713a-eff4-11e4-9c55-9438f9d568ab.png)

True of square-ended lines but not the case of mitred.

If round-ended lines are preferred, perhaps looking at terminating nodes would be the first thing to look at options wise

**Comment by matkoniecz** [comment]
see https://github.com/gravitystorm/openstreetmap-carto/issues/286#issuecomment-98008062 https://github.com/gravitystorm/openstreetmap-carto/issues/286#issuecomment-97924922 and https://github.com/gravitystorm/openstreetmap-carto/issues/286#issuecomment-97925070

**Comment by pmailkeey** [comment]
Re terminating nodes cf 'turning circle'.

Mitred lines are used on runways.

**Comment by kocio-pl** [comment]
@matkoniecz :
> There is no known way of "looking at terminating nodes"

Why? As far as I understand, noexit=* tag is exactly saying "this is a terminating node". Then we could
(1) render the highways with square endings and 
(2) render circles on all the nodes belonging to highways without noexit=* (or with noexit=no) while
(3) not rendering anything special on nodes with noexit=*.

Does it sound reasonable or is it still flawed?

**Comment by gravitystorm** [comment]
It's unreasonable to ask that every terminating way in the entire world is tagged noexit.

**Comment by kocio-pl** [comment]
Of course we can wait until the software start recognizing topology. That would be the best.

But until then we don't need to ask anything, we can just use what is already known. Let's look at the numbers: Taginfo says noexit key (370 314) is used a bit more than highway=pedestrian (365 708) or highway=road (338 374) and half of highway=cycleway (774 735) or highway=living_street (668 816), so it's really quite popular!

Frankly speaking I'm very surprised, because currently we don't even render it and I'm sure it will get more popular once people will see it being rendered. What's more important, it will be useful for better rendering cases of "false joinings".

Does it still sound unreasonable now?

**Comment by pmailkeey** [comment]
"It's unreasonable to ask that every terminating way in the entire world is tagged noexit."

Completely agree - so haven't a clue why you'd even suggest it.

The terminating node effect is likely to be needed less than 1 in 20 or even 1 in 50 - just those rare occasions where an end is 'too close' to another road that at times may look close enough to be connecting.
