### ISSUE TITLE
Add highway=via_ferrata

### ISSUE THREAD

**Issue by sashazykov** [gravitystorm/openstreetmap-carto#156]
Via ferrata paths are not visible now, and people use highway=path instead.

http://wiki.openstreetmap.org/wiki/Proposed_features/via_ferrata

**Comment by RicoZ-OSM** [comment]
Wondering - if the proposal were approved or considered stable enough/de-facto - what would be rendered anyway? Does via ferrata rendering belong into all-purpose mapnik ? Should all ferratas be rendered or just certain difficulty grades?

**Comment by polarbearing** [comment]
There are already specialised renderers/overlays for climbing situations, such as
http://openclimbingmap.bstegmaier.de/#14/48.3943/9.7821
http://martinkoeller.github.io/ClimbingMap/example1.html
I'm against rendering ```highway=via_ferrata``` on the general map, and I am for correctly tagging them so specialised renderers can evaluate them.

**Comment by RicoZ-OSM** [comment]
@polarbearing : care to explain your reasoning a little bit? 

Those ferratas are in places that are not overcrowded optically so can hardly be a reason.

If the reason is that they are only for "very sportive" people it would also follow that we should not render paths marked as demanding_alpine_hiking among others.

I am digging into this because many people tag ferratas as paths with the reasoning that "some ferratas are much easier and safer than some paths and if mapnik shows extremely difficult paths but not easy ferratas people might be misguided to use the dangerous paths instead of the easy ferrata."

Btw your link http://martinkoeller.github.io/ClimbingMap/example1.html  seems dead.

http://openandromaps.org/ is another very nice alternative which renders ferratas.

**Comment by alexandrz** [comment]
My opinion is very similar to @RicoZ-OSM I think that it would be better to render ferratas on the general map.

**Comment by dbrgn** [comment]
I also agree.

**Comment by imagico** [comment]
Keep in mind some important criteria for a decision on rendering a certain feature are:

* is the tag well defined in the wiki
* is the tag the generally accepted way to map this kind of thing or are there competing taggings
* is the actual use of the tag consistent

In all of these points highway=via_ferrata seems to fare pretty badly.  It is not clear to me from either tag page or proposal for example what distinguishes a via ferrata from a normal hiking trail with mechanical aids like ropes, ladders, bridges, steps, railings etc.  (which is widely and quite undisputedly tagged highway=path).

This does not mean highway=via_ferrata won't be rendered in the standard style but you could probably improve the chances a lot by improving those points.

**Comment by map-per** [comment]
How about using black dots?

**Comment by ppete2** [comment]
Full support to what @Tyg-g wrote. `highway=via_ferrata` right now is an established tag and since they are well-known touristic attractions they should be rendered. Also they should be distinct from `highway=path`, cause climbing a via-ferrata is different from hiking pathes - even demanding pathes. For via-ferratas you usually have to preapare yourself by putting on safety gear.
