### ISSUE TITLE
add rendering for amenity=vending_machine

### ISSUE THREAD

**Issue by yarl** [gravitystorm/openstreetmap-carto#1561]
It's very nice, that we have waste baskets on map. I think, that vending machines also should be added, since they are also helpful.
- icon: [SJJB proposal](https://github.com/twain47/Open-SVG-Map-Icons/blob/master/svg/shopping/vending_machine.svg) (definitely too big, but good starting point)
- label: `name=*`, then, `operator=*`, then `ref=*`

**Comment by kocio-pl** [comment]
There's a lot of them (like 58k), so I have no doubt. However I think that maybe showing what can you buy there - if the related shop icon is available - may be more useful than generic vending machine icon?

**Comment by yarl** [comment]
Sure, that would be great, but I try to be realistic :smile:

**Comment by HolgerJeromin** [comment]
Is a generic vending machine really useful? 
On shops the name gives the missing information, but that doesn't work for vending machines.

**Comment by matkoniecz** [comment]
I think that in this case value of rendering it is rather low (though waste baskets are rendered) and rendering it in understandable way would be problematic.

**Comment by pnorman** [comment]
I'm inclined to agree

**Comment by HolgerJeromin** [comment]
At least white list only some `vending` values is IMO needed. But that has to wait for a db reload.

**Comment by kocio-pl** [comment]
For me this is dead easy, because we already have clear analogies mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/1745. Progression of size/importance would go like this:
- bank (z17) > ATM (z18)
- post office (z17) > post box (z18)
- prominent shop (z16) > typical shop (z17) > vending machine (z18)

(there are also few other examples of such progression)

As for the icons - I prefer reusing shop icons, because they're selling the same things just without a man behind a counter. It would be nice if we find acceptable general icon, but it's not a priority for me now.

I still haven't figured out however how to tag and render "paczkomat" (machine for sending/receiving parcels), which is very similar and gaining traction (at least in my city). I also don't have a clear vision of CDM (cash deposit machine) - should it look exactly like ATM and how should it be tagged?

**Comment by pnorman** [comment]
Closing, for reasons above

**Comment by Tomasz-W** [comment]
Packstations icon proposal:

![vending parcel](https://user-images.githubusercontent.com/25656654/37558947-b61db8ca-2a1c-11e8-80ab-aa08e3f512f0.png)

**Comment by kocio-pl** [comment]
I think packstation tagging is broken, since it has nothing to do with vending and uses a name of a particular brand - here is a draft of my solution (a bit old, but I plan to finish it):

https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_box

Which also makes tagging of similar objects more coherent and universal:

https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dlaundry_box

The icon is interesting. Maybe using [ as with tickets vending would make it more clear.

**Comment by Tomasz-W** [comment]
I though about use this icon for: `vending=parcel_pickup;parcel_mail_in` , `vending=parcel_pickup` , `vending=parcel_mail_in` . In total they have 3,4k uses.
I didn't use "[" because there is no "[" in the real shape, as it is in parking/ public transport ticket machines.

**Comment by Tomasz-W** [comment]
@matthijsmelissen Can you re-open this issue due to https://github.com/gravitystorm/openstreetmap-carto/issues/108#issuecomment-382985177 ?
It passed almost 3 years since oryginal discussion and usage of amenity=vending_machine has grown from 58k to 105k. I think we should consider rendering of most popular and most useful types like: 
* parking tickets (24k) -> https://github.com/gravitystorm/openstreetmap-carto/issues/2541#issuecomment-372300000
* public transport tickets (15k) -> https://github.com/gravitystorm/openstreetmap-carto/issues/2541#issuecomment-372300000
* fuel (5k)
* parcel (3,5k in total)

**Comment by Tomasz-W** [comment]
`vending=parcel_pickup;parcel_mail_in` , `vending=parcel_pickup` , `vending=parcel_mail_in` :

![vending parcel](https://user-images.githubusercontent.com/25656654/42159143-fe76efa4-7df2-11e8-93f6-3119170201d7.png)

Gist link: https://gist.github.com/Tomasz-W/18032cc646055bf17b866cb4eb48fa48

**Comment by kocio-pl** [comment]
Vending machine icon in direktvermarkter project (see https://farmshops.eu ) on MIT license:

https://github.com/CodeforKarlsruhe/direktvermarkter/blob/master/img/a-pin2.png

**Comment by Tomasz-W** [comment]
`vending=extrement_bags` (15,6k uses) icon proposal:

![vending extrement_bags](https://user-images.githubusercontent.com/25656654/44139967-fd5fad38-a078-11e8-94b3-9cedbcdd97c6.png)

**Comment by Adamant36** [comment]
@Tomasz-W, you want to come up with a generic vending machine icon or are we just going vending type? If you want to make one, it could look like the one in the first post or be something similar to a combination of the fuel and bureau_de_change icon. Or maybe the charging_station icon with a coin instead of the lighting bolt and minus the hose.

**Comment by Tomasz-W** [comment]
@Adamant36 Certain types of vending machines are so different from each other, that making good generic icon for all would be propably impossible, so please test following dedicated icons:

* `vending=parcel_pickup;parcel_mail_in` , `vending=parcel_pickup` , `vending=parcel_mail_in` https://gist.github.com/Tomasz-W/18032cc646055bf17b866cb4eb48fa48
* `vending=public_transport_tickets` https://gist.github.com/Tomasz-W/e2ada41172ec67de5131e68d44fcb900
* `vending=parking_tickets` https://gist.github.com/Tomasz-W/3a93d9a032725039b3ac24139f5d318c
* `vending=excrement_bags` https://gist.github.com/Tomasz-W/ad4720881ceb6e92bca9541b0221eddb

**Comment by Adamant36** [comment]
@Tomasz-W, really? They are all fundamentally a box with a hole to put money in and another one where stuff comes out right? I mean, I guess there's a difference between a soda machine and bathroom kleenex dispenser. But they are both still squarish and take money. Amenity=machine is generic anyway. So, its not like the icon for it can't be. 

Fine, fine...I'll just test the other ones instead. Jeez.

**Comment by Adamant36** [comment]
@Tomasz-W, what about one for public transport tickets? Its got 1500ish uses.

**Comment by Tomasz-W** [comment]
@Adamant36 It's provided above.

**Comment by Adamant36** [comment]
@Tomasz-W, oh yeah. Duh. My bad.

**Comment by Adamant36** [comment]
@Tomasz-W, So, I get that you don't think an icon would work for the default vending machine, it appears though after a lot of testing that because of the way the code/rendering priority works, if there are icons for a sub type like this it will render those icons on the default tag if it doesn't have anything to render for its self. Its a similar thing as to why the code for recycling had to be changed to "does not equal." I don't think there is a way to get around it without at least having a dot or something. I could be wrong though. Aside from that, It would be good if the default was rendered with something anyway, just so the names will render if nothing else or so people will know they are there and need a vending=* tag. 

@kocio-pl, do you know how we might get around this issue? Its a little out of my realm of knowledge. Personally, id prefer plain vending machines be rendered somehow, instead of just using a code trick to get around it, even if its just a dot, but Tomasz-W thinks an icon would be to generic. So..

**Comment by dieterdreist** [comment]
Am Sa., 6. Okt. 2018 um 13:32 Uhr schrieb Adamant36 <
notifications@github.com>:

> @Tomasz-W <https://github.com/Tomasz-W>, really? They are all
> fundamentally a box with a hole to put money in and another one where stuff
> comes out right? I mean, I guess there's a difference between a soda
> machine and bathroom kleenex dispenser. But they are both still squarish
> and take money. Amenity=machine is generic anyway. So, its not like the
> icon for it can't be.
>



they are very different based on what they sell. E.g. machines that sell
parking tickets are a kind of printers, machines that sell refrigerated
stuff have completely different requirements and often aspect than the
former (e.g. vending machines for bbq meat), there are also vending
machines for cooked, warm food, e.g. in the Netherlands you can get burgers
from vending machines (there are people cooking the stuff, behind the wall,
who fill the boxes). Machines for hot coffee, machines for cold drinks,
machines for postal stamps, machines for pre paid telephone top up, etc.
Some machines need internet access to work, some just electricity, others
are even working without electricity (not sure if "machine" is the right
term for these, maybe "automat" would suit better).

**Comment by kocio-pl** [comment]
This is a case when size rule would be helpful - ticket shop on z17+, ticket machine on z19+, so you can easily guess what it really is beside knowing what you can get there.

**Comment by kocio-pl** [comment]
I believe `vending=parcel_pickup;parcel_mail_in` is bad tagging scheme:

> Because these machines are not vending machines, the alternative tag `amenity=parcel_lockers` has been proposed. 

https://wiki.openstreetmap.org/wiki/Proposed_features/Parcel_lockers

I also tried to propose scheme but did not finish it:

https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_box

**Comment by jragusa** [comment]
I'm testing icon of @Tomasz-W and I would like to know if we need to also include name tag or just the icon ?

**Comment by kocio-pl** [comment]
I guess with a name. However without proper tagging it does not make sense for me.

**Comment by Tomasz-W** [comment]
@jragusa @kocio-pl I've checked some european cities in Overpass Turbo and vending machine's name tag in most of cases is like "Packstation" for packstations, "Tickets" for ticket machines or machine operator company name wrongly put in name tag, so I wouldn't render names here as it could mess a map with unnecessary unuseful information.

**Comment by kocio-pl** [comment]
Let's make some order, I got lost a bit... Which tagging scheme do you like to render and using which icons?

**Comment by Tomasz-W** [comment]
@kocio-pl See https://github.com/gravitystorm/openstreetmap-carto/issues/1561#issuecomment-427564831

**Comment by jragusa** [comment]
`vending=public_transport_tickets`
https://www.openstreetmap.org/node/3735097197
before
![public_transport_before](https://user-images.githubusercontent.com/9897203/50304778-33f56500-0491-11e9-9131-1febbb542269.png)
after
![public_transport_after](https://user-images.githubusercontent.com/9897203/50304788-38218280-0491-11e9-8c93-614addc7f0af.png)

`vending=parking_tickets`
https://www.openstreetmap.org/#map=19/46.19375/6.23334
before
![parking_ticket_before](https://user-images.githubusercontent.com/9897203/50304959-bbdb6f00-0491-11e9-8d83-21156f067467.png)
after
![parking_ticket_after](https://user-images.githubusercontent.com/9897203/50304963-c0a02300-0491-11e9-9650-470b53c695d6.png)

`vending=excrement_bags`
https://www.openstreetmap.org/node/4461667570
before
![excrement_before](https://user-images.githubusercontent.com/9897203/50305376-e843bb00-0492-11e9-8233-2717eb054a59.png)
after
![excrement_after](https://user-images.githubusercontent.com/9897203/50305324-c2b6b180-0492-11e9-9b93-e51f648e22ae.png)

**Comment by Adamant36** [comment]
Maybe the transport ticket could have a T in it to signify its for public transportation like the parking ticket has a P. Otherwise, it seems neutral. Also it might help to crop the images a little more, because it took me a minute to figure out where the icon was in the after image.

**Comment by Tomasz-W** [comment]
As "P" letter is intuitive for parkings, I think "T" wouldn't be an intuitive letter for public transport. Notice also that this machines with public transport tickets are usually near stations or tram/ bus stops, so it makes them more intuitive to understand.
@jragusa I think they should be in man-made gray as amenity-brown makes them looking more important than they actually are. Btw. @Adamant36 any news about https://github.com/gravitystorm/openstreetmap-carto/issues/3326?

**Comment by jragusa** [comment]
`marker-fill: @man-made-icon;`
![public_transport_after_manmade](https://user-images.githubusercontent.com/9897203/50339356-a0b34280-0517-11e9-9b78-4263681a8254.png)

![parking_ticket_after_manmade](https://user-images.githubusercontent.com/9897203/50339346-998c3480-0517-11e9-8469-95a8eccdd442.png)

![excrement_after_manmade](https://user-images.githubusercontent.com/9897203/50339367-af015e80-0517-11e9-9bfd-4a73cfe17b2e.png)

**Comment by Tomasz-W** [comment]
I'm always not sure about proper colour for the features like that: at the one hand they are small and simple, but at the other they may be very important for cityzens and also some of them are more 'interactive' somehow, so both amenity-brown and man-made-grey have advantages and disadvantages for vending machines. Another thing is that when looking on test renderings above I think if we would decide on rendering vending machines in man-made-grey we should change also amenity=atm icon to grey to keep map logical. I would like to read the opinions of others.

**Comment by kocio-pl** [comment]
In general I think of brown as something you can interact with, while grey is just for watching, so I would render them brown.

**Comment by jragusa** [comment]
Based on #3326 and #3402, I would leave `amenity=vending_machine` in amenity-brown, otherwise we also need to move `amenity=atm` in man-made colour.

I also would propose to render `operator` as label for `vending=public_transport_tickets`. 71.96 % of them have an operator tag and it's useful to distinguish them when there is more than one transport network. In the above example, there is both railway and public transports and the machine is dedicated to railway transport.

However, I noticed that operator is only render when a name is also added in the tags. For example this [one](https://www.openstreetmap.org/node/2139977781) does not have any label in contrast to this [one](https://www.openstreetmap.org/node/3525314473). Is that intentional ?

In the same example, I have to add a name tag to render the label
![public_transport_after_brownlabel](https://user-images.githubusercontent.com/9897203/50344919-6fde0800-052d-11e9-996d-8a83d45d29a9.png)

**Comment by Adamant36** [comment]
@Tomasz-W, I just did a PR for it. I didn't include anything related to recycling so it won't get derailed like last time, but everything else is included.

**Comment by Tomasz-W** [comment]
@kocio-pl What about packstations? I know you've proposed 
https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_box
but it seems to be stuck (and another thing is that propably "packstation" would be much more better name for them, compare google images of both names). Can you start a discussion about potential `amenity=packstation` tag (instaed of amenity=vending_machine for them) on Mailing list?

**Comment by kocio-pl** [comment]
I'm not ready to start any discussion on the list. Anyone else?

The name however should be different, since "Packstation" is used by DHL, so the best thing should be to go with already existing proposals - my proposition or this one (both are OK for me, maybe lockers is better than just box, since there are many of them):

https://wiki.openstreetmap.org/wiki/Proposed_features/Parcel_lockers

**Comment by Tomasz-W** [comment]
Ok, thanks. I would go with "parcel_lockers". I added my comment on the [talk page ](https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Parcel_lockers). I hope this proposal won't get stuck as yours one.

**Comment by kocio-pl** [comment]
You might contact the author, because if nobody will talk on the Tagging list, I feel there little chance that this would be ever used wider:

https://wiki.openstreetmap.org/wiki/User:SelfishSeahorse
