### ISSUE TITLE
Render lock_name rather than the name of the canal

### ISSUE THREAD

**Issue by bobkare** [gravitystorm/openstreetmap-carto#157]
The current rules for rendering labels on waterways add text-placement: point when they are tagged lock=yes, but the name tag mostly contains the canal name, so lock_name should probably be rendered instead. See http://osm.org/go/euzFr5X3C for an example.

I have a trivial patch at http://bob.cakebox.net/osm/lock_name.patch although that fetches the data from hstore which I'm not sure the tile.osm instance has.

**Comment by matkoniecz** [comment]
rendering lock_name was also discussed in #828

**Comment by geozeisig** [comment]
We should render the lock name in some way. However, there are several possibilities and I  would prefer the first.

1. Render lock_name in black horizontal  color (like man_made=bridge) . **For:** It is used about 4500 times.

2. Render name. **For:** As  dieterdreist says (see above) could we use the variants like localized names, alt_name etc.  **Against:** As the workaround on the wiki page describes, the name is already used for the channel. lock_name would become worthless. The lock name would in many cases not fit into the lock because of the length of the expression.

3. The name is written to the lock chamber natural=water + water=lock. **For:** It already works. **Against:** This is  "Tagging for the renderer". lock_name would become worthless.

**Comment by SomeoneElseOSM** [comment]
Just for info, https://map.atownsend.org.uk/maps/map/map.html#zoom=20&lat=52.9707228&lon=-1.293098 is an example of what this looks like (the ref is also appended in brackets)

**Comment by kocio-pl** [comment]
Thanks. However it looks we're undecided what we really want. :smile:

**Comment by matthijsmelissen** [comment]
Now we have hstore, I think we can implement the PR of @bobkare. Is anybody willing to test this?
