### ISSUE TITLE
Aqueduct and Canal

### ISSUE THREAD

**Issue by Nautic** [gravitystorm/openstreetmap-carto#1608]
area: 
waterway=canal
bridge=aqueduct
should be rendered as *area* (covering all under the area)

wrong rendering:
http://map.openseamap.org/?zoom=18&lat=49.33243&lon=11.0827&layers=BFTFFFTFTTF0FFFFFFFF

Thanks, Markus

**Comment by dieterdreist** [comment]
the bridge attribute doesn't define a feature by itself.
 waterways mapped as areas on a bridge should generally honor the bridge attribute (typically these would be canals)

**Comment by pnorman** [comment]
waterway=canal bridge=aqueduct is not generally an area, it's a linear feature. Additionally, a non-closed way is **never** an area.

Additionally, when providing examples, please use bare openstreetmap-carto, not something that layers on top like openseamap.org, preferably including a screenshot in the github issue so we can see what it is at a later date when the data may have changed.

**Comment by Nautic** [comment]
Hello Paul,

Shippable aqueducts sometimes are wide (50m in the example). 
Then we tag it as area.

You can select specific views in the menu "View":
Without seamark-layer it looks like this:
http://map.openseamap.org/?zoom=18&lat=49.33291&lon=11.08263&layers=BFFFFFTFFTF0FFFFFFFF
As DOP it looks like this:
http://map.openseamap.org/?zoom=18&lat=49.33291&lon=11.08263&layers=0FFFFFTFFTFBFFFFFFFF
If you need the data, select in the menu "Edit" > "Chart with JOSM remote".

Best regards,
Markus

**Comment by Nautic** [comment]
sorry - wrong button...

**Comment by imagico** [comment]
For clarification: the relevant feature here is:

http://www.openstreetmap.org/way/28733592

which due to the tag bridge=aqueduct should be rendered above roads etc. but is not.  This is an area (closed way with waterway=riverbank - formally this is correct, natural=water+water=canal would be better though).  The waterway=canal object 

http://www.openstreetmap.org/way/28733596

is not the problem here.

This can probably be fixed by introducing an additional layer water-areas-bridges above waterway-bridges.  Rendering a black casing to visually indicate a bridge and to separate it from waterways crossing below (the Schwarzach here) will not be easily possible though.

**Comment by imagico** [comment]
Additional note: ferry-routes should probably go above the waterway-bridges, see:

http://www.openstreetmap.org/#map=17/52.30374/8.92810

**Comment by dieterdreist** [comment]
2015-06-17 11:37 GMT+02:00 Christoph Hormann <notifications@github.com>:

> For clarification: the relevant feature here is:
>
> http://www.openstreetmap.org/way/28733592
>
> which due to the tag bridge=aqueduct should be rendered above roads etc.
> but is not. This is an area (closed way with waterway=riverbank - formally
> this is correct, natural=water+water=canal would be better though). The
> waterway=canal object
>
> http://www.openstreetmap.org/way/28733596
>
> is not the problem here.
>


the second link (linear canal) is a problem because of the bridge casing
that should not be visible in this case (area around it).

A dirty hack for the road rendering issue is to split it and add
covered=yes to it, similar to other situations, where a building covers the
road, and where it is done like this.

**Comment by imagico** [comment]
This is not a problem when the water area is rendered above.

**Comment by Nautic** [comment]
Similar to bridge rendering, 
I suggest a small black line marking both long sides of the aqueduct .

**Comment by pnorman** [comment]
To get layering of waterways correct everywhere would require moving them into the roads layer. I am **extremely** reluctant over this because it would make one of the most complicated layers even more so, and I don't think it's worth the gain in complexity.

**Comment by Langlaeufer** [comment]
Is there still now solution for the problem of channel bridges?
https://www.openstreetmap.org/#map=17/52.40563/9.58659
