### ISSUE TITLE
Stop rendering nature-reserve-boundaries on z7

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1669]
Is there a good rationale to render these boundaries from z7? I think that these features are not important enough to justify rendering them before even forested areas are displayed.

Is it intended as substitute for displaying forest, done for performance reasons?

**Comment by imagico** [comment]
One reason for rendering nature reserves at low zooms is because some of them are very large - see https://github.com/gravitystorm/openstreetmap-carto/pull/1147#issuecomment-66182705 for some examples.  If you start later you end up with screen filling sizes already at the starting zoom level.

But i agree that for a general purpose map rendering of nature reserves is too prominent at the lower zooms and rendering them less prominently would make them difficult to recognize.  Nature reserves IMO would be a perfect candidate for rendering as a separate overlay.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 20.07.2015 um 12:17 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Is there a good rationale to render these boundaries from z7? I think that these features are not important enough to justify rendering them before even forested areas are displayed.
> 
> Is it intended as substitute for displaying forest, done for performance reasons?
> 


important national parks are some of the few features that are displayed at this level, it is a cartographic decision by the former developers of this style. I believe it can be argued that national parks are features that many people know and that can serve for orientation.

cheers 
Martin

**Comment by jojo4u** [comment]
I am in favour of removing it. I find it quite distracting and without the name orientation is difficult.

**Comment by pnorman** [comment]
I would like to keep it.

**Comment by kocio-pl** [comment]
I'm not sure what to do with it, but it doesn't make sense to decide it now. We should rather start drafting [what we want to show on the lowest levels in general](https://github.com/gravitystorm/openstreetmap-carto/issues/1125) than concentrate on this particular feature alone.

**Comment by matkoniecz** [comment]
There is no clear consensus for change.

**Comment by matkoniecz** [comment]
This idea returned in #2925
