### ISSUE TITLE
do not render riverbank on low zoom 

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1670]
We discussed highway:area rendering and the problem people will forget the routing centerline. Solution was to render the area only on high zoom. 

Rivers have already both the linear waterway and riverbank area rendered. 
We have some imports which did not had a river centerline, but only the riverbank. 

Perhaps we could drop rendering the riverbank on low zoom, too, to force better tagging. 
I am not sure if this would work.

**Comment by imagico** [comment]
River lines are rendered from z=12 so leaving out river polygons would mean not rendering rivers at all at z<12.  Rendering river lines at low zooms would not work since rendering them all would just be a lot or unstructured blue in the map and there is no data differentiating important rivers from unimportant ones.

Also current tagging practice does not consequently distinguish between standing and flowing water areas.

**Comment by HolgerJeromin** [comment]
You are right. A classification is missing compared to highways...
