### ISSUE TITLE
Render amenity=concert_hall

### ISSUE THREAD

**Issue by SK53** [gravitystorm/openstreetmap-carto#1677]
Recent (July 2015)discussion on the talk mailing lists (https://lists.openstreetmap.org/pipermail/talk/2015-July/073528.html) highlights that concert halls have a wide range of tags, many of which of marginal accuracy. It would appear that much of these stems from "tagging for the renderer". As major concert halls are significant places in major cities it would be sensible to add these with a specific icon to distinguish them from theatres and to discourage the extension of amenity=theatre to also cover concert halls (and perhaps to also discourage fairly widespread double tagging of places such as the Musikverein).

I plan to write a simple pull request to address this shortly.

**Comment by kocio-pl** [comment]
I think we could use the same icon as we use for night clubs, because (size, genre and atmosphere aside) they both are for enjoying music and the icon is pretty general in that matter. However [changing this icon name](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/nightclub.18.svg) to something like "musical_note" would be good. :smile:

**Comment by matkoniecz** [comment]
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dconcert_hall is missing and usage is extremely low - 96 instances worldwide (see http://taginfo.openstreetmap.org/tags/amenity=concert_hall ).

Not present in JOSM preset.

I think that introducing new tag should start from editors, documentation and mapping - not from this rendering.

I propose to not render this tag for now.

**Comment by kocio-pl** [comment]
On the other hand - this is so rare type of place that [one can make a worldwide list of them](https://en.wikipedia.org/wiki/List_of_concert_halls) (I don't know how to count them easily), so the numbers will always be relatively low and this one is at least really used in the wild.

I agree, that we're not ready to do this yet, but here's what you can do:
- try to convince people on the Tagging list it's the right scheme for this type of objects (or some other maybe)
- add this rendering to as many objects from the list as possible (of course no edit wars advised)
- make a (short) Wiki page describing this tagging
- ask JOSM and iD developers if this preset could be added

In the meantime we can discuss what icon/labelling is right, so we're ready once the tagging is established.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 22.07.2015 um 13:49 schrieb SK53 <notifications@github.com>:
> 
> It would appear that much of these stems from "tagging for the renderer".


Current, long standing definition for the amenity=theatre tag is to use it for all/many kinds of performing arts (and use the theatre:genre subtag):
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtheatre

I'm not happy with this neither, just wanted to point it out

**Comment by matkoniecz** [comment]
> In the meantime we can discuss what icon/labelling is right, so we're ready once the tagging is established.

Given that time for tagging to be established will be measured at best in weeks/months I think it would be better to close this issue for now.

It is also possible that in the end some other tagging scheme will be used.

**Comment by kocio-pl** [comment]
Tagging is irrelevant for us to determine how we want to show it. Whatever scheme will eventually win (if it happens), we can show it as kind of theatre or as kind of musical place - or maybe in a different way (I guess not showing at all is not the option for such a big and important objects)?

**Comment by kocio-pl** [comment]
I propose to change the name of this ticket to something more general, so we could separate the problem of rendering we want for this type of objects from tagging details.

**Comment by SK53** [comment]
@kocio-pl I think the idea that they are so rare you can make a list of them is erroneous. A reasonable rule of thumb is that every city in the Western world with population > 100-150k will have at least one. 

@dieterdreist yes indeed this is the long-standing usage, and looking at my own edits have used it that way. But reviewing this in the light of ~6.5 years vs 6 weeks of editing OSM is that this clearly perpetuates a series of category errors. 

@matkoniecz  I would agree that fixing things in editors is also important, but this is a system problem. Treating it as a waterfall, tagging list, editr presets, etc. just means that the status quo remains. 

Fine if that is what you want, but I would prefer to work on means to improve OSM: and more appropriate rendering is one of the necessary steps, and possibly the simplest to implement.

**Comment by kocio-pl** [comment]
Sure, rendering it would be easy, but first we have to know which tagging scheme we should render. We need a proof that's what community wants to use for this type of object - it doesn't need to be hard proof (that would be impossible in such a distributed project), but it's still needed.

**Comment by imagico** [comment]
Since amenity=theatre + theatre:genre=* can probably be considered the dominating tagging for this at the moment i think rendering amenity=theatre with either a more generic symbol covering concert halls (the current one is fairly specific even within the non-musical performances) or with specific symbols depending on genre and treating amenity=concert_hall as a synonym for amenity=theatre + theatre:genre=[music stuff] would be a good idea.  Unfortunately theatre:genre is currently not available to the style.

**Comment by kocio-pl** [comment]
The discussion about right tagging scheme can now be followed [on Tagging list](https://lists.openstreetmap.org/pipermail/tagging/2015-July/025758.html).

**Comment by jojo4u** [comment]
First comes documentation in the wiki, then comes the rendering.

**Comment by SK53** [comment]
@jojo4u Fine I'll stop filing any issues here then. Consider this issue closed.

**Comment by pnorman** [comment]
Wiki documentation is not a barrier to rendering, nor for that matter does being documented on the wiki imply that it will be rendered.

That doesn't mean that the tagging is in a state where it's consistent enough to be rendered. I haven't reviewed the tagging of these objects, so can't answer that.

**Comment by dieterdreist** [comment]
there are currently 96 occurrences of this tag worldwide, together with no documentation (and a supposedly competing and documented tagging scheme) this doesn't seem mature to be rendered at this time.

**Comment by imagico** [comment]
Since the competing tagging is rendered - although incorrectly for concert halls - it would make sense to render it in a way that is neutral to the development of tagging and does not put mappers in a position to decide between a tagging that is not rendered and one that is incorrectly rendered - see my suggestion above.  This would mean putting this on hold until `theatre:genre` is available - which hopefully is not too far off.

I think there should be little doubt that in principle concert halls would deserve being rendered in this style.

**Comment by math1985** [comment]
I'd propose to render features like this (and similar features) with a name, but without icon. That way people can retag features as they like, and we're not flooded with features for rarely used features.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 30.07.2015 um 10:08 schrieb Christoph Hormann <notifications@github.com>:
> 
> Since the competing tagging is rendered - although incorrectly for concert halls -
> 


according to the wiki it is rendered correctly (a subitem of theatres). While I don't share this concept it still can be defended with arguments.


> e. This would mean putting this on hold until theatre:genre is available - which hopefully is not too far off.
> 


anyway, if the subitem (concert hall) is not a kind of theatre, the scheme would be broken and should not be supported 


> I think there should be little doubt that in principle concert halls would deserve being rendered in this style.
> 


+1

**Comment by kocio-pl** [comment]
I asked about right tagging on Tagging list, but discussion is dead at the moment.

**Comment by matkoniecz** [comment]
@pnorman 

> Wiki documentation is not a barrier to rendering

I think that lack of wiki documentation is a barrier for rendering, especially in case of tags used less than 100 times worldwide.

I think that it is desirable for tag to pass through proposal process (as it means that multiple people looked at tag definition and found no significant problems - some problems may be not obvious for everybody from the start).

It is a poor idea to allow proposal for new tags start and be discussed here. For multiple reasons turning this bugtracker into place for inventing new tags is a poor idea (there are already multiple places like this - further fragmentation is a poor idea, discussion volume would increase even more, signal/noise ratio would drop, closing issue would be even more significant choice etc etc).

> nor for that matter does being documented on the wiki imply that it will be rendered.

Obviously, just because something is documented does not mean that it would be rendered. Good documentation for me is prerequisite rather than guarantee to render.

Importance of passing proposal process would be far lower for widely used tags (checking whatever place=city passed proposal process is utterly pointless, in case of man_made=bridge is was nice thing, for tag used 96 times it is IMHO absolutely necessary).

**Comment by matkoniecz** [comment]
Overall I propose to close this ticket and wait for wider usage and/or passing through proposal process.

Wiki documentation is now available thanks to @SK53 - see http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dconcert_hall

**Comment by kocio-pl** [comment]
+1, let's see if it will catch on.

**Comment by pnorman** [comment]
> It is a poor idea to allow proposal for new tags start and be discussed here. For multiple reasons turning this bugtracker into place for inventing new tags is a poor idea (there are already multiple places like this - further fragmentation is a poor idea, discussion volume would increase even more, signal/noise ratio would drop, closing issue would be even more significant choice etc etc).

Yes, new tag proposals belong else where of course.

Usage is not sufficient right now to warrant adding to the style.

**Comment by imagico** [comment]
> I think that it is desirable for tag to pass through proposal process (as it means that multiple people looked at tag definition and found no significant problems - some problems may be not obvious for everybody from the start).

On a general note I would strongly advise against making this a criterion here (which is why i left it out of the list of criteria on https://github.com/gravitystorm/openstreetmap-carto/issues/1630#issuecomment-118359389) - the proposal process can help improving quality of tagging concepts but practically it often does not.  Cargo-culting it as a substitute for a thorough look if a tag and its use are well suited for rendering in a map is a very bad idea and would only lead to further degrade the proposal system towards becoming primarily a vehicle to push specific interests in mapping priorities.

As already said i would keep this issue open for when theatre:genre is available.

**Comment by geozeisig** [comment]
Meanwhile, the tag is used 200 times. This is not very much but should be the occasion to think about rendering again. These important places are not mentioned on the map otherwise.

**Comment by kocio-pl** [comment]
It's growing in a slow way (after temporary peak in 2010), probably there are just not that much of such features. How should it be rendered?

![taghistory 44](https://user-images.githubusercontent.com/5439713/51593210-e2a61e80-1ef1-11e9-991b-018cb9a11c89.png)

**Comment by matkoniecz** [comment]
Not at all, 200 usages worldwide is not worth rendering.

**Comment by polarbearing** [comment]
> 

This is easy: https://taginfo.openstreetmap.org/keys/?key=theatre%3Agenre#values

philharmonic 226, musical 82, chamber_music 75, opera 53, music 11, which is all more fine-tuned than a general 'concert_hall' which cannot even distinguish between a philharmonic or a rock concert. 

theatre:type=concert_hall is more helpful than dozens of amenity tags.

**Comment by jeisenbe** [comment]
Ok, it still sounds like the usage is probably too low for rendering at
this time, even with combining all possible tags

A proposal and better wiki documentation are the next step, if anyone wants
to take this on.

**Comment by jeisenbe** [comment]
Does anyone have an idea for a more generic theatre icon? The current icon
is related to plays, not music.

**Comment by geozeisig** [comment]
Question: How would you classify the [Verti Music Hall](https://www.openstreetmap.org/node/6058229940#map=18/52.50485/13.44333) (see: [verti-music-hall.de](https://www.verti-music-hall.de/))? Under the described theater:genre for music theater (opera, musical, ballet, philharmonic, chamber_music) no one has fit. I chose live␣music because it fit best from the taginfo list. Maybe the list theatre:genre still needs to be expanded.

**Comment by polarbearing** [comment]
This is really not the place to discuss the tagging of an individual object. I left my opinion on your changeset. Of course the list of values at theatre:genre is not limited, but 'live' is already in the definition of theatre itself.

**Comment by jeisenbe** [comment]
> Question: How would you classify the Verti Music Hall ?

Please ask about this on the Tagging mailing list
