### ISSUE TITLE
dashed rail also on lower zoom levels

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1704]
I am trying to modify railway=rail to make it harder to confuse with minor roads. One of ideas is to keep dashed style also on lower zoom levels.

Unfortunately to achieve truly good results it will be necessary to use overcomplicated SQL merging ways (as dash pattern has big problems with segmented ways, bridges are a typical problem).

Before doing that I want to check whatever the idea of dash style on lower zoom levels is considered as a good idea.

https://cloud.githubusercontent.com/assets/899988/8966556/4fa3601c-3632-11e5-8633-bf0ea717a6d4.png

**Comment by kocio-pl** [comment]
Simply amazing! :astonished:

**Comment by math1985** [comment]
Looks much better.

**Comment by matkoniecz** [comment]
Thank - has anybody already managed to merge ways split into separate ways into one linestring? https://github.com/gravitystorm/openstreetmap-carto/issues/497#issuecomment-42429080 seems to indicate that it is possible.

Here I would want to do it at least for z11, z12 for railway=rail without tunnel=yes.

On higher zoom levels the same effects happen but it is quite hard to notice.

![selection_004](https://cloud.githubusercontent.com/assets/899988/8967050/0280d668-3635-11e5-8daa-29ac6207886e.png)


ping @pnorman

**Comment by rmikke** [comment]
Wow. Simply wow.

**Comment by imagico** [comment]
What would be needed here is probably something like a global alignment for the dash pattern - this would also help to avoid odd interferences between the dash patterns of neighboring lines like here:

http://www.openstreetmap.org/#map=15/52.2528/10.5508

but i guess it would be somewhere between tricky and impossible to implement something like that.

**Comment by pnorman** [comment]
> Thank - has anybody already managed to merge ways split into separate ways into one linestring? #497 (comment) seems to indicate that it is possible.

Yes, and railways are a candidate for this. The technique is to use [ST_LineMerge](http://postgis.net/docs/manual-2.1/ST_LineMerge.html)

This comes with a few issues

* The SQL is more complicated
* It is slower
* It involves linestrings that differ depending on bounding box, resulting in artifacts at MT edges

Because we don't label railways, I don't think the MT edge problems matter here.

I would suggest importing a small area, doing `CREATE TABLE railways AS SELECT * FROM planet_osm_line WHERE railway = 'rail'` and then creating a view with the SQL you want to use. You can then use qgis to look at the view, and see exactly what is being produced and look at each linestring.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 29.07.2015 um 22:32 schrieb Paul Norman <notifications@github.com>:
> 
> Because we don't label railways, I don't think the MT edge problems matter here.


there might be small differences in the distances of the pattern at the edges, at worst there would be two black or white fillings in sequence.

**Comment by daganzdaanda** [comment]
Really nice indeed. 
I still would like to see it in a few more places. It does add a bit of noise, but at those zooms, we don't show many things that might interfere.

**Comment by kocio-pl** [comment]
Still great idea after all these years. :smile: 

> Because we don't label railways, I don't think the MT edge problems matter here.

Now we label some of them (#2687).

**Comment by daganzdaanda** [comment]
Hm, actually with the desaturated landuses and changes in road colour, this is not so necessary any more IMHO. The current rendering is much clearer than the example from the first post. Also, we show rail tunnels as dashed lines at the moment, which also works very well.

**Comment by kocio-pl** [comment]
There are also roads which are rendered as a simple dark lines, so making railways distinctive would be nice. But that's probably rather practical question - if @matkoniecz is willing to do this.

**Comment by kocio-pl** [comment]
I have just added rail pattern on z12 to make it look different than tram lines. I had no time to test also rendering on z11, because that would mean color testing (z12 shade is too dark for my taste) and this is not as important. 

Is there anybody who thinks that we should try this pattern on anything above z12 or this issue can be closed as resolved?

**Comment by kocio-pl** [comment]
Given skeptical comment from @matkoniecz (https://github.com/gravitystorm/openstreetmap-carto/pull/3488#issuecomment-443410482) I will close this now.
