### ISSUE TITLE
no crossing sign on private service and railway

### ISSUE THREAD

**Issue by wvanderp** [gravitystorm/openstreetmap-carto#1709]
there are no crossing signs here: https://www.openstreetmap.org/#map=19/35.45466/-97.49458
like here: https://www.openstreetmap.org/#map=19/35.43929/-97.51069

**Comment by mboeringa** [comment]
> there are no crossing signs here: https://www.openstreetmap.org/#map=19/35.45466/-97.49458

That is because it is another tag, **railway=crossing** versus **railway=level_crossing**. The latter is currently rendered, the former not. 

Note that **railway=crossing** according to the Wiki should only be used for pedestrian crossings, not for normal roads with vehicles (http://wiki.openstreetmap.org/wiki/Tag:railway%3Dcrossing). It seems the tagging may be wrong here, as the road is a **highway=service**, and probably allows motorized traffic as well.

**Comment by matkoniecz** [comment]
Closing as data issue.
