### ISSUE TITLE
Render amenity=fuel at z16

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#1764]
IMO, this is an important feature especially within car-centric countries and rural areas. Input is welcome.

**Comment by kocio-pl** [comment]
It might have some sense!

**Comment by dieterdreist** [comment]
. In Rome it would completely clutter the map for no good reason. Supermarkets, (many) libraries, churches and to some extent cinemas are usually important landmarks, fuel stations are very less so. Please keep them on z17, especially in the current situation where we can't distinguish between urban and rural areas.

**Comment by kocio-pl** [comment]
There is a separate issue for showing multiple objects earlier outside the city/town/village boundaries and some landuse probably: https://github.com/gravitystorm/openstreetmap-carto/issues/1705

**Comment by matkoniecz** [comment]
I agree that fuel stations are far less important than features mentioned @dieterdreist 

Current z-level seems to be a good compromise in absence of desity-based rendering.

**Comment by HolgerJeromin** [comment]
OK, than we should move car_sharing to later zoom. 
Many people use fuel stations, but very few have a car_sharing contract.

**Comment by math1985** [comment]
I wouldn't even mind dropping car_sharing from the default rendering. They are typically [insignificant features](http://2.bp.blogspot.com/-vkw2mqQ0yT0/U2_9qPlB0hI/AAAAAAABBXM/OVbRMkeyU_s/s1600/20140425045+NE+Amsterdam+KNSM+Eiland+NS+Green+Wheels+car+sharing+2+KSS.jpg), and nearly everyone having a car_sharing contract would use the map of their provider rather than OSM to find a car_sharing spot.
