### ISSUE TITLE
Labels for admin_level=3 are displayed too prominently and block display of more important cities

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1795]
Current rendering is OK for huge countries with important internal divisions (USA, maybe also other countries).

But in Europe it makes at most little sense. See http://www.openstreetmap.org/#map=6/49.611/18.040 - for example in case of Poland current rendering is absurd (prominence of admin_level=3 entities is significantly lower than this of large cities).

Unfortunately there is no method to tag whatever internal divisions are important (and it is anyway too subjective).

It is possible to 
- keep current rendering and accept that regions like Europe on low zoom levels is ridiculously displayed
- make subdivision of countries less prominent what would make USA and maybe other location look ridiculous
- somehow detect more and less important admin_level=3 entities
  - by hardcoding it (it would be nightmare to decide which countries have important subdivisions and which not)
  - use way_area - big entities are displayed before cities, smaller after (or somehow give them priority and order in one query)
  - solve #1069, apply it to admin_level=3 areas, make cities more important (similar to using way_area but more labels would be displayed)
  - something else?

At this moment nearly every map has better z4 - for example transport layer
![selection_001](https://cloud.githubusercontent.com/assets/899988/9563750/ba0ef44c-4e8e-11e5-8d4d-b290c2a87300.png) or
mapquest ( http://tools.geofabrik.de/mc/#4/49.6023/27.0194&num=2&mt0=mapnik&mt1=mapquest )
![selection_002](https://cloud.githubusercontent.com/assets/899988/9563753/cfe3d60c-4e8e-11e5-988f-c956a3ad8376.png)

**Comment by pnorman** [comment]
Updated rendering, but with older data. 

![image](https://cloud.githubusercontent.com/assets/1190866/10041592/ff68f83a-6199-11e5-9aad-42de9c98f677.png)

**Comment by jojo4u** [comment]
A more complete selections of different maps: http://tools.geofabrik.de/mc/#4/-3.9649/-55.5978&num=6&mt0=mapnik&mt1=nokia-map&mt2=bing-map&mt3=google-map&mt4=mapquest&mt5=mapnik-humanitarian 
Most other maps display labels only in big countries like USA/Canada/Brasil/China.

No hardcoding in the database. Hardcoding should be done in osm-carto. I find the maps with the names of the states much more pleasant (Bing, Google) instead of ref (OSM, HERE) - for example what use is "FI19" in Finland? If hardcoding will be done, only a few countries where names are fitting will remain.

**Comment by jojo4u** [comment]
The title is wrong, shouln't it be admin_level=4?

**Comment by kocio-pl** [comment]
I guess this was fixed somewhere along the way.
