### ISSUE TITLE
If inner way of multipolygon has the same landuse as the multipolygon, it is not rendered

### ISSUE THREAD

**Issue by aceman444** [gravitystorm/openstreetmap-carto#1819]
See way 207030429, which is an inner member of relation 1629218. Both of them have landuse=farmland. See https://www.openstreetmap.org/#map=16/48.8585/18.0352 (the non-yellow areas). This is not an old-style multipolygon, where the tags were on the outer way (or both). I would expect the polygon and inner areas to render in the same farmland color, thus making the inner areas invisible (unless crop is honored in the future). They are just worth to be separated in the polygon due to the differing crop tag (multipolygon has none).

**Comment by HolgerJeromin** [comment]
Seems like a osm2pgsql problem to me. 
We could add a light border to farmland, so the inner farmland would be visible.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 09.09.2015 um 09:32 schrieb Holger Jeromin <notifications@github.com>:
> 
> Seems like a osm2pgsql problem to me.


+1, the multipoligon processing seems a bit over engineered because it is trying to make sense even of clearly ill-shaped mapping by guessing what should be right, also because there was a change in how mp were mapped (tags on outer way vs tags on relation) and it was tried to process all of these different styles. In particular it deliberately omits some tags of inner islands if they are the same tags the outer member or the relation has. This leads to confusing results.

**Comment by aceman444** [comment]
Yeah. Even JOSM now emits warnings about old style multipolygons and promotes new style (tags on relation). They even want to make them visually stand out, see e.g. https://josm.openstreetmap.de/ticket/10529.

So maybe you could slowly move in that direction too. Of course if you can support both styles, that would be great, but if support for old style breaks correct new-style multipolygons, than maybe the old style can't be preserved.

**Comment by pnorman** [comment]
This is not a stylesheet issue, as the style does no parsing of multipolygons at all.

If there is an osm2pgsql issue, it should be discussed at https://github.com/openstreetmap/osm2pgsql/issues not here. If you are going to open an issue there, don't forget to check it's not fixed in the latest version, and provide a testcase.
