### ISSUE TITLE
tram_stop label is rendered earlier than bus_stop label

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1834]
Currently tram_stop name is rendered too early, from z>=14 [like railway=halt and aerialway=station](https://github.com/gravitystorm/openstreetmap-carto/blob/master/stations.mss#L51), but I think it should be rather [the same as bus_stop](https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss#L1762) (z>=17), because they are related closer to each other and now [tram stop names make unnecessary mess on the map](http://www.openstreetmap.org/#map=14/51.1127/17.0405).

**Comment by matkoniecz** [comment]
AFAIK Poland has lower than average distance between tram stops, most likely showing from z17 would be too much.

And counterexample - in Kraków labels from z14 work fine - http://www.openstreetmap.org/#map=14/50.0733/19.9127

**Comment by kocio-pl** [comment]
In my opinion it doesn't work even there, because on this zoom level I expect rather subdivisions of a city (like quarters/suburbs or even neighborhoods) than such small POIs, like on the Wikimedia map:

https://maps.wikimedia.org/#14/50.0733/19.9127

I also tend to think about the system: why tram stops should be more visible than bus stops? I find these two kind of transportation very similar (with metro/subway and railway halt/stations being different and shown earlier than them). Of course maybe there is a reason and I just don't see it.

**Comment by ajank** [comment]
I would argue that tram stop labels definitely should be more visible than bus stop labels. Because of their much higher unit capacity, trams typically form the backbone of public transport system in smaller cities that do not have a subway or urban rail system. Moreover, the tram network is much more permanent and prominent in the urban space than the bus network. Hence, I propose to render tram stops labels at z>=15.

**Comment by pnorman** [comment]
I support rendering tram stops earlier - that's not to say that z14 is or is not the right level, but it should be before bus stops

**Comment by jojo4u** [comment]
Note that in absence of widespread rendering support of public_transport=stop_position/platform, highway=tram_stop should also used by the more tram-like light rail systems since railway=halt does not fit well. Railway=halt is defined only once per halt and often the halts of the Stadtbahn are separated by some dozen meters, making the usage of highway=tram_stop, which is mapped on the rail and usually used two times per halt, more fitting. Example: https://www.openstreetmap.org/relation/905074

**Comment by kocio-pl** [comment]
Yes, it looks more like a tram stops, indeed.

>  Because of their much higher unit capacity, 

In this regard I find them rather similar - there are long and short buses in my city and there are single or double trams, so the difference is not that visible for me. Rough info from Wikipedia about maximum capacities:

"Newer model trams may be up to 72 metres (236 ft) long and carry 510 passengers at a comfortable 4 passengers/m2"

"Buses can have a capacity as high as 300 passengers."

2x more is still similar scale for me. 

I don't know what about light rails, cause I don't know have any experiences with this kind of transport, but Wikipedia says that:

"Light rail or light rail transit (LRT) is urban public transport using rolling stock similar to a tramway, but operating at a higher capacity, and often on an exclusive right-of-way."

...which seems like tram+ :smile:, so it would be useful to leave the tram the same as bus and LRT as more important and general scale would be then:

bus + tram < LRT < metro < railway (or maybe the same as metro?)

We could check if it's really more or less like this with rendering.

> trams typically form the backbone of public transport system in smaller cities that do not have a subway or urban rail system. 

In many smaller cities in Poland the buses are more popular than trams as a backbone network because of lack of the need for special infrastructure and easier changes of routes, so it's also similar.

> Moreover, the tram network is much more permanent and prominent in the urban space than the bus network. 

We talk here about name labels. For me tram network is perfectly visible and the dots are rendered much earlier than bus dots (z>=13 - maybe they should follow the label and stay at one zoom level earlier), so IMO it's enough to mark it's permanence (the prominence can be similar as I wrote).

However if you still insist that it should be rendered earlier than buses (z>=17), but not necessarily from z>=14, I have nothing against it and we can make decision much easier: 

1. Should the labels be shown from z>=15 or z>=16?

2. Should the dots be moved to z>=14 or z>=15 (accordingly)?

**Comment by ajank** [comment]
I agree with the progression schema and the idea that the stop labels should follow the stop dots and become visible one zoom level later. I would suggest to show tram stop dots at z>=14, and tram stop labels at z>=15. This would place tram closer to rail than to bus, since the rules for the latter are:
bus stop: dots at z>=16, labels at z>=17
rail halt: dots at z>=13, labels at z>=14.

We could also push tram stops one zoom level further (dots z>=15, labels z>=16), but to me this would be suboptimal. Current label density at z15 in Wrocław and in other cities looks acceptable to me. The problem is that it would be much better to show only a single label for the whole stop_area at z15, instead of the same label twice, but the generalization is a much bigger issue.

Or maybe this is the way to go, and we could show tram stop dots at z>=14, stop_area names at z==15 and stop labels at z>=16? I know, it is so simple only for stop_areas containing only tram stops, we would need a more complicated ruleset to handle all the possible combinations of means of transport...

**Comment by kocio-pl** [comment]
Could you try to explain what is a stop_area? Do you have any examples to show it?

**Comment by jojo4u** [comment]
Stop_area is a relation which groups the public_transport=stop_position and =platform (plus other) of together (http://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_area). See it here in action: http://www.öpnvkarte.de/?zoom=17&lat=48.77766&lon=9.18288&layers=TBTTT

**Comment by kocio-pl** [comment]
There's some problem with this link.

Ok, the problem is you think about trams, but this is:
> A relation that contains all elements of a train, subway, monorail, tram, bus, trolleybus, aerialway, or ferry stop. 

What do you want with it?

**Comment by ajank** [comment]
> What do you want to do with it?

I would take all stop_areas containing tram_stops, generate the midpoint of these tram_stops, and show in this midpoint the stop_area name. This would be only at z==15. At z>=16 I would show labels of individual tram_stops. (I know that this might be challenging with the existing rendering workflow.)

**Comment by HolgerJeromin** [comment]
Just for your information: 
öpnvkarte and the transport layer does not use the stop_area relation, but the same name of the highway=bus_stop.
The rendering of the same name above the covered area is visible here:
http://www.openstreetmap.org/?mlat=50.7694&mlon=6.0948#map=16/50.7694/6.0948&layers=T

I dont think a general purpose map should show a transport name on this low zoom. this works on the transport layer only with the outline. On a highzoom the features are too far away for rendering only one name.

**Comment by ajank** [comment]
> I dont think a general purpose map should show a transport name on this low zoom. this works on the transport layer only with the outline. On a highzoom the features are too far away for rendering only one name.

OK, got me convinced, we could display tram_stop labels at z>=16 only, z==15 might be indeed too early.

**Comment by jojo4u** [comment]
> öpnvkarte and the transport layer does not use the stop_area relation, but the same name of the highway=bus_stop.
The documentation of ÖPNVKarte says both relation and same name are used (http://wiki.openstreetmap.org/wiki/%C3%96pnvkarte#Stations)

> There's some problem with this link.
Seems to be a  bug with the umlaut here in Github. Try pasting the link into the browser bar.

**Comment by kocio-pl** [comment]
Moving only the tram_stop labels (not touching dots) from z>=14 to z>=16 in Wroclaw works for me.

z14 (before/after):
![wroclaw-tram-labels-14](https://cloud.githubusercontent.com/assets/5439713/10099452/0e4c882a-638a-11e5-8c85-afd21b258cc3.png)
![wroclaw-tram-14](https://cloud.githubusercontent.com/assets/5439713/10099455/157c1bba-638a-11e5-8dad-0063e488c691.png)

z15 (before/after):
![wroclaw-tram-labels-15](https://cloud.githubusercontent.com/assets/5439713/10099464/291285a6-638a-11e5-955d-97849e8ecde3.png)
![wroclaw-tram-15](https://cloud.githubusercontent.com/assets/5439713/10099465/2b885162-638a-11e5-9fed-8891cdced532.png)
