### ISSUE TITLE
Drop car_sharing rendering

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1891]
@math1985 https://github.com/gravitystorm/openstreetmap-carto/issues/1764#issuecomment-145229715
> I wouldn't even mind dropping car_sharing from the default rendering. They are typically [insignificant features](http://2.bp.blogspot.com/-vkw2mqQ0yT0/U2_9qPlB0hI/AAAAAAABBXM/OVbRMkeyU_s/s1600/20140425045+NE+Amsterdam+KNSM+Eiland+NS+Green+Wheels+car+sharing+2+KSS.jpg), and nearly everyone having a car_sharing contract would use the app of their provider rather than OSM to find a car_sharing spot (because such apps also indicate whether cars are currently available).

I'm in agreement.

**Comment by matkoniecz** [comment]
Also

> more advanced systems allow cars to be picked up and dropped off at any available public parking space within a designated operating area

https://en.wikipedia.org/wiki/Carsharing#How_it_works

I would not be against this change.

**Comment by jojo4u** [comment]
I'm against. These are essentially amenity=parking with low capacity and access=private, and this is rendered atm. 
Stuttgart is a city which as both systems. Car2go is free-floating and works like a taxi substitution (amenity=taxi). But even Car2go has many reserved parking spaces because public parking is scarce in the city. The other system Stadtmobil is not less-advanced but more like a substituion for car-rental where you reserve one specific car in advance (amenity=car_rental).
This would break the feedback loop. I don't see a "this is not useful for casual visitors" in CARTOGRAPHY.md. Probably point two "clear design" is fitting with this propoal. While I agree those are usually used via the OSM app, we should encourage mapping these spots in order to convince the operators to use OSM data.

**Comment by simonpoole** [comment]
Autsch, this one was really not on the radar. Car sharing is -very- popular in a number of countries (which typically have well developed public transport infrastructure) and not rendering it will at least raise eyebrows in classically OSM friendly groups.

**Comment by sfkeller** [comment]
Disagree with removing this too. In addition to the arguments of simonpoole and jojo4u, be aware that car sharing is more and more partnering with public transport where one can switch from train/bus to car (multi-modal travelling).

**Comment by datendelphin** [comment]
Sorry for the late response

I would like to disagree with
> nearly everyone having a car_sharing contract would use the app of their provider rather than OSM to find a car_sharing spot

I use car sharing. And all I get is a text describing how to get to the parking space based on the closest train station or similar land mark. And a Google map with a sloppily placed marker.
Those spots are sometimes hard to find. The "app of their provider" only shows the google map, which is definitely not detailed enough. Having it carefully placed on OSM with details to get orientation helps a lot. I would like to get the icon back.

**Comment by math1985** [comment]
Could the users disagreeing with removing this indicating where they are located, and perhaps how the system looks like in their country?

I'm familiar with the systems in the UK and Netherlands, which are quite similar. Car sharing points can mainly found in cities. Within the cities that are covered, there is basically a car sharing point on every street corner ([map of London](https://www.citycarclub.co.uk/locations/london-car-hire). Every car sharing point is a location of only one car. To reserve a car, you go to the operator's website or app to see what cars are available. You can only use cars of your own operator.

**Comment by SK53** [comment]
@math1985 last 3 all from CH, presume @jojo4u is from DE

**Comment by simonpoole** [comment]
Switzerland: one larger provider, often multiple cars available in one location.

**Comment by math1985** [comment]
Can you find a photo of such a location by any chance?

**Comment by datendelphin** [comment]
http://www.mapillary.com/map/im/9k0BmkWmM76y-aze4V8tKQ/photo
here on the left you can see a rather large one. all the yellow marked paring spots belong to mobility, the Swiss car sharing provider.

Except in the largest cities like Zurich or Bern, there is usually quite a distance between locations. But the locations usually host enough cars that at many times there is still a free one there when you need one.

**Comment by math1985** [comment]
I see, [this](https://www.google.nl/maps/@51.5460104,-0.1436673,3a,75y,246.99h,62.2t/data=!3m6!1e1!3m4!1s1BoWJM9aiBAZaJ0PixVrgQ!2e0!7i13312!8i6656!6m1!1e1) is a typical English car sharing spot (only the left bay).

There's clearly a large difference between the countries' systems. Now to decide which system to follow...

**Comment by jojo4u** [comment]
One reserved parking spot for free-floating Car2Go: http://static4.swp-plus.de/storage/pic/nachrichten/ulm/2014/november/1700849_1_GOPR1229.jpg?version=1414997142
One sport for Stadtmobil, reserved for the same car: http://www.zukunft-mobilitaet.net/wp-content/uploads/2014/07/stadtmobil-hannover-moltkeplatz_oeffentlicher_stellplatz.jpg

They are mostly on private parking lots with the car-sharing company reserving some spots. I think it's mostly comparable to disabled parking.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 31.10.2015 um 11:40 schrieb math1985 <notifications@github.com>:
> 
> I see, this is a typical English car sharing spot (only the left bay).
> 
> There's clearly a large difference between the countries' systems. Now to decide which system to follow...
> 


I can't agree this has to do with countries, it is rather something that depends on the system/operator. Modern systems might not use any stations at all (they're working with mobile apps for communicating the locations and gps in the cars, nothing to map here), others use dedicated parking lots, ranging from one to quite a bunch of lots. I'd consider those with fix spatial manifestations in the physical world worth rendering in this style sheet, while the rest will not be mapped anyway.

here are some examples:
http://www.enso-blog.de/wp-content/uploads/2012/10/teilAuto-und-Ladestation_groß.jpg

http://www.alamy.com/thumbsImages.aspx?url=http://c8.alamy.com/comp/A0J9A9/germany-berlin-smart-car-at-stattauto-car-sharing-station-A0J9A9.jpg&imageref=A0J9A9

https://de.m.wikipedia.org/wiki/DB_Rent#/media/Datei%3AFlinkster_Station_HBF_Frankfurt.jpg


https://en.m.wikipedia.org/wiki/DriveNow#/media/File:Electric_BMWs_Charging_at_Google_(9602705934).jpg


https://www.flickr.com/photos/sillygwailo/6842504607/

cheers,
Martin

**Comment by HolgerJeromin** [comment]
Rendering only with capacity > 1 would perhaps work.

**Comment by simonpoole** [comment]
It should be noted that systems that don't have fixed locations aren't more "modern" they simply aren't possible in the many many places which do not have unmanged parking.

**Comment by HolgerJeromin** [comment]
Most people mentioned that they need the position on a micro mapping level. 
So rendering it late would be OK, as a customer has a rough idea where the car is. 
We had it at 18 iirc.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 31.10.2015 um 13:06 schrieb Simon Poole <notifications@github.com>:
> 
> It should be noted that systems that don't have fixed locations aren't more "modern" they simply aren't possible in the many many places which do not have unmanged parking.


ok, I didn't want to depreciate systems with permanent stations, but the systems without these fix stations are only practically possible since the invention of the smart phone (after 2007), while other systems have been there before...

Well, in theory with lots of vehicles available, in dense areas, it could also work out without knowing beforehand the positions of the vehicles, you just take any (this approach e.g. is used by the bicycle renting service of German railways, where available).

**Comment by mxa** [comment]
I disagree. Car sharing stations are a vital part of mobility infrastructure and as more and more people in densely populated places decide not to own a car but use a mixed mobility with public transport,
bike and car sharing they are becoming even more important.

OSM is a community effort and you can see this in the data. There is great data for cyclists and pedestrians on OSM, because it is made by them. It sets OSM apart from other, commercial maps which are centred around the individually owned car.

The communal use of a vehicle makes sense for community minded people as OSM contibutors are.
The challenges of today with the climate talks in Paris ahead of us and the need for alternative ways of transportation seems to have escaped you. Especially hard to understand when on the other hand car_wash is added to the rendering. Wrong signal you set here. Makes no sense if you ask me.

> * Added rendering of the following tags:
>   - amenity=car_wash

While it's true that there are now car sharing providers that have a deal with the city to allow their vehicles to be parked on any available parking spot, the classic model with fixed stations still exists and is not replaced, but supplemented by the "park anywhere" kind. In Germany that's teilAuto or DB Flixter and their stations usually hold several cars. In Korea it is Socar and they too have designated stations.
