### ISSUE TITLE
Distinguishing road types, especially Motorways, isn't obvious enough in the new colour scheme

### ISSUE THREAD

**Issue by KenBW2** [gravitystorm/openstreetmap-carto#1946]
I take the point from that using the UK road colour scheme isn't _intuituve_, but it did a very good job of distinguishing between different types of road.

Particularly Motorways - there's a very big difference between a primary road and a motorway, and on long journeys it's far and away the preferred choice of road.

In the new colour scheme, both primary roads and motorways are near enough the same colour, and it's not obvious at a glance which is the motorway. See below for an example.

![digix5l](https://cloud.githubusercontent.com/assets/366540/10870441/f2bbc48a-80c2-11e5-94b7-6181e509a848.jpg)

I'd like to propose a new colour for motorways which reflects their importance relative to other road types.

**Comment by math1985** [comment]
Is this an issue that plays for you at all zoom levels, or are there particular zoom levels where this is a problem?

**Comment by KenBW2** [comment]
I'd say anything > Z12

![screenshot from 2015-11-01 18 39 41](https://cloud.githubusercontent.com/assets/366540/10870665/123e0214-80c8-11e5-9601-2f1c90cd7ae7.png)

![screenshot from 2015-11-01 18 39 20](https://cloud.githubusercontent.com/assets/366540/10870668/223a352a-80c8-11e5-8174-52cc719ef9f7.png)

![screenshot from 2015-11-01 18 38 57](https://cloud.githubusercontent.com/assets/366540/10870669/2a765be2-80c8-11e5-8601-d40c3826b9c5.png)

**Comment by jojo4u** [comment]
Yes, on first glance it's difficult to make out the motorways. But perhaps we are too used of this read-centric view. The goal of osm-carto is not a map showing roads as prominent as e.g. Google Maps.

**Comment by KenBW2** [comment]
Jack of all trades, master of none?

The original rationale of the change wasn't to make roads less prominent - it was because the UK colour scheme of Blue, Green, Red, Yellow wasn't considered intuitive. I personally don't like that that change was made, but I understand the reason for it.

But the change has become in my mind a regression. Where before motorways were easily distinguishable they're now almost invisible against the backdrop. I feel quite strongly that we find a colour that satisfies both requirements.

**Comment by AlbertJP** [comment]
I do not have so much trouble in finding the red motorways on the map. The first thing that struck me, was that motorways now have more emphasis compared to their surrounding area in zoom levels around 15, especially those running in forests. I suddenly start noticing the red names of junctions and exits overlaying the map, which did not catch my eye when they were blue.
To be honest my first thought was that OSM had become a map for motorists, and I am not one of them. I currently don't have problems with the red colour any more; I am however wondering, whether a darker or more saturated shade of red would be an improvement for both of us. I would like other users' input on this- I see we have very different reasons to dislike the red, because it's too prominent or because it's not prominent enough.

**Comment by RobJN** [comment]
If I recall there was a go at making motorways more purple but this then clashed with the admin boundaries. A lot has changed recently so perhaps someone could look at moving admin boundaries to a different colour thus freeing up more space to move the motorway into.

**Comment by KenBW2** [comment]
>I suddenly start noticing the red names of junctions and exits overlaying the map, which did not catch my eye when they were blue

Completely agree - I thought the font size was bigger now but maybe it's just the colour. I approve this change

>I am however wondering, whether a darker or more saturated (less pink) shade of red would be an improvement for both of us

I was thinking a darker would serve as a good compromise that can satisfy all parties. It's more prominent, but still within the same colour range hence satisfying the colour-indicates-way-type methodology.

Examples thrown together in Gimp:

![close](https://cloud.githubusercontent.com/assets/366540/10896826/5e5f64b6-81b4-11e5-8e09-fc0283e44328.png)

![mid](https://cloud.githubusercontent.com/assets/366540/10896863/97c8be78-81b4-11e5-9e79-dbcf0b1f691e.png)

![far](https://cloud.githubusercontent.com/assets/366540/10896914/e13eef0a-81b4-11e5-8d96-0aa5920471bb.png)

**Comment by Gazer75** [comment]
I hope one day there will be country specific rendering. Maybe it will be to confusing.

For me the first color that comes to mind when people say motorway is blue. All motorway signs have a blue background here in Norway. For this reason I really miss the old blue.

Current rendering is to similar to trunk though and should be changed to something else.

**Comment by BalooUriza** [comment]
On Tue, Nov 3, 2015 at 12:23 AM, Gazer75 <notifications@github.com> wrote:

> I hope one day there will be country specific rendering. Maybe it will be
> to confusing.
>
Certainly see problems at the data level for this, since reading a relation
is relatively cheap and geocoding, comparatively, isn't.   It would pretty
much mean eliminating road routes from tags on the way (eg ref=*) and
moving that to route relations (a transition that needed to happen years
ago, and the sooner we do it, the easier it's going to be).

**Comment by KenBW2** [comment]
I agree that country specific rendering would be great (Mapquest Open does this), but I think that's a separate feature request.

Let's keep this Issue focussed on the simple colour change.

**Comment by matthijsmelissen** [comment]
We have chosen to render four different colors of roads - and that inevitably means they are close together in the color space. I'm afraid I don't think there's much we can do here (without giving up the 4 color roads).
