### ISSUE TITLE
Road ref shields & others block too many road names

### ISSUE THREAD

**Issue by tomchance** [gravitystorm/openstreetmap-carto#1956]
I'm submitting this issue on the assumption that the default style wasn't supposed to be a car touring map, and that - certainly in cities - major road names are far more useful than refs.

Currently, refs (and in places labels for other features) mean many major road names don't render. This is especially noticeable at zoom levels 13-15, where some road names _do_ show up but are almost always left out in favour of ref shields.

Some examples:

![image](https://cloud.githubusercontent.com/assets/460737/10942515/60e1f7a8-8308-11e5-9b30-35901cc08e94.png)

![image](https://cloud.githubusercontent.com/assets/460737/10942555/753e95d0-8308-11e5-8156-901924d4ad59.png)

![image](https://cloud.githubusercontent.com/assets/460737/10942578/94d4964c-8308-11e5-8678-e26d041adcbe.png)

**Comment by dieterdreist** [comment]
> Am 04.11.2015 um 16:28 schrieb tomchance <notifications@github.com>:
> 
> that - certainly in cities - major road names are far more useful than refs.


yes, in cities the names are far more important while in villages and towns you'd more likely be interested in the refs, especially in medium to low zoom levels

**Comment by kocio-pl** [comment]
Example from my hometown: all streets around [this cemetery](https://www.openstreetmap.org/#map=15/52.2770/21.0372) has a lot of refs and not a single name.

@dieterdreist You're right. This reminds me about https://github.com/gravitystorm/openstreetmap-carto/issues/1705 or https://github.com/gravitystorm/openstreetmap-carto/pull/1884. The more I look at such issues, the more I think about domain- or environment-based rendering. I'd like this style to be more context sensitive (like for example "urban", "rural" or "outdoor"). What do you - I mean all of you here - think about it? Do you agree it is needed at all? Any remarks on how it could be done?

**Comment by mboeringa** [comment]
> @dieterdreist You're right. This reminds me about #1705 or #1884. The more I look at such issues, the more I think about domain- or environment-based rendering. **I'd like this style to be more context sensitive (like for example "urban", "rural" or "outdoor"). What do you - I mean all of you here - think about it?**

My problem with these kind of proposals and similar ones like "country" specific road type renderings or shields, that abound here and on the different mailing lists and forums, is that each of them, however sensible in its own right, tends to significantly add to the number of render rules that need to be defined and managed. It quickly adds up if you need to take care of dozens - or even hundreds - of zone specific renderings.

At some point, this will be completely unmanageable, and an intolerable burden for the render servers. Considering the style maintainers already strive for a kind of "max number of render rules" in this style due to the current complexity, I doubt it is very realistic to expect country or zone specific renderings in one and the same style on the same servers. This really requires dedicated country styles managed on separate servers, like osm-fr or osm-de.

As to the specific problem posted here: I think this would be ameliorated considerably if the ref shields used a much wider spacing / were less dense distributed, leaving space for road name labelling. There have been several related issues posted here:

* Uneven spacing of highway shields #303
* Render ref from route relationship #596

There are some major technical challenges here, especially discussed in #596.

**Comment by matkoniecz** [comment]
> At some point, this will be completely unmanageable, and an intolerable burden for the render servers. Considering the style maintainers already strive for a kind of "max number of render rules" in this style due to the current complexity, I doubt it is very realistic to expect country or zone specific renderings in one and the same style on the same servers. This really requires dedicated country styles managed on separate servers, like osm-fr or osm-de.

Render servers are not a primary problem. The primary problem is that urban/rural separation significantly increases complexity - it basically means maintaining two separate styles that are supposed to be used on the same map, some method to decide which one is supposed to be used at given location.

That is not a small tweak, that is a massive task that is highly unlikely to happen. Proposing it as solution without code that would implement this* is not useful.

Fundraising two times more money for servers will be probably easier than implementing urban/rural distinction for this style (note my bias here: I am more aware about how complex implementing this would be than about fundraising problems).

*attempting to make simplest proof of concept makes clear that it is more complicated than expected

**Comment by AlbertJP** [comment]
This is probably very country specific too. In my city of Utrecht, it is basically a non-issue because hardly any road inside the city has a ref. However we do have some roads out of town (notable example the N412 Universiteitsweg), where the ref is hardly used on signposts. Those would deserve a name on the map - but of course rendering engines don't have local knowledge like that!

**Comment by kocio-pl** [comment]
Solved by #3315.
