### ISSUE TITLE
Roundabout disappears when combined with landuse=grass

### ISSUE THREAD

**Issue by RicoElectrico** [gravitystorm/openstreetmap-carto#1976]
For some reason junction=roundabout + landuse=grass on a single way causes the road to disappear. While such tagging is not exactly pretty, the style should be fail-safe.
![fail3](https://cloud.githubusercontent.com/assets/1409116/11165016/8630d9d2-8b02-11e5-976a-8097f0ecef59.png)

**Comment by HolgerJeromin** [comment]
I am sure osm2pgsql is causing this. The way is not imported in the linear roads table. 
I don't think this tagging is valid enough to be supported.

**Comment by matkoniecz** [comment]
That is a really weird tagging and in addition it is wrong. Grass area is not starting in the middle of the road (where highway=* line is located).

**Comment by dieterdreist** [comment]
sent from a phone

> Am 14.11.2015 um 20:07 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> That is a really weird tagging and in addition it is wrong. Grass area is not starting in the middle of the road (where highway=* line is located).


while I see the problem like you, (and have for years been advocating for a mapping style which distinguishes between area borders, linear features and in particular highway ways not mixing with landuse, leisure or similar areas,) this tagging is not "weird" but rather common. It cannot necessarily be called wrong, because you could see the highway ways as having implicit width, half of which "naturally" you'd have to subtract to get to the actual area/landuse border. ;-)
I won't suggest we advocate to map with this model in mind (while it is "true" it isn't very maintainable or upgradable/refinable), but it has been brought up in the past.

**Comment by HolgerJeromin** [comment]
i know the scheme of reusing the nodes or a way for the area. But road and landuse one the same osm-way is not so common (i hope :-)
but we have the same issue with landuse + barrier. There is renders

**Comment by jojo4u** [comment]
The style does not be that foolproof, landuse and highway on the same way is just bad mapping. With landuse and barrier and landuse the barrier is much more linear than a highway.

**Comment by pnorman** [comment]
To how we're modeling things in osm2pgsql and the style, an object is either an area or a line, not both. I consider tagging that tries to say otherwise as invalid, so not something we'd want to support.

**Comment by dieterdreist** [comment]
2015-11-16 1:53 GMT+01:00 Paul Norman <notifications@github.com>:

> To how we're modeling things in osm2pgsql and the style, an object is
> either an area or a line, not both. I consider tagging that tries to say
> otherwise as invalid, so not something we'd want to support.
>


yes, I agree. But having landuse=* together with barrier=fence (for
example) is very common. I do not use this kind of mapping (am using
multipolygons mostly, an alternative would be an attribute like
fenced=yes). One might argue that these are shortcuts for modelling 2
things on one osm object. Obviously this is not very sustainable, because
it creates sooner or later ambiguities to which object a particular tag
relates (or the need to split into several objects).

Have a look here: http://taginfo.osm.org/tags/barrier=fence#combinations
10.7% of all fences have additional tags landuse or leisure (~190K objects)

Here's one example, and it looks as if it is supported by this style
currently. http://www.openstreetmap.org/way/270570223
Is yours a plea to remove support for situations like these? (I'm in favour
of discarding support).
