### ISSUE TITLE
Salt flats, like Salar de Uyuni

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#1995]
Could this be rendered on the map.
http://www.openstreetmap.org/relation/1769713#map=10/-20.1733/-67.6483
This is a major import flat and should be on the map.
With his own visual? as a salt_flat. Crystal salt

Maybe the tags are inappropriate.
natural=desert desert=salt
But what else?

natural=wetland wetland= something with salt (salt_flat)
http://wiki.openstreetmap.org/wiki/Tag:natural%3Dwetland

**Comment by imagico** [comment]
natural=desert was specifically removed from rendering since it is not well defined.

Regarding tagging - there was a thread on the ML some time ago:

https://lists.openstreetmap.org/pipermail/tagging/2015-September/026692.html

Rendering `intermittent=yes` (#996) and `salt=yes` (requires currently unavailable database key) on water areas would probably help to better represent salt flats/dry lakes with at least occasional water cover.  A specific rendering of permanently dry lakebeds could be considered within the general field of bare ground areas but only if a consistent tagging for those is established (which currently is not the case beyond the already rendered bare_rock/scree/shingle/sand).

**Comment by matkoniecz** [comment]
@AllroadsNL Can you point to wiki page describing tagging of salt flats? Also, are salt flats affected by tagging problems like deserts (see #1072).

**Comment by matkoniecz** [comment]
Closing as nobody responded to 

> @AllroadsNL Can you point to wiki page describing tagging of salt flats? Also, are salt flats affected by tagging problems like deserts (see #1072).
