### ISSUE TITLE
`place=suburb` rendering too visible on z14

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#2035]
Hello, there.

I mismodelled a neighborhood as `place=suburb` [here](https://www.openstreetmap.org/#map=14/48.3004/6.1364) and noticed something odd in its rendering:
- z13: not rendered;
- z14: rendered with a level 8 administrative subdivision, similar to Mirecourt, the town including the neighborhood;
- z15: rendered with the smaller `place=locality/neighborhood` font.

This rendering progression seems strange to me; I would say it should be improved, either by:
- rendering `place=suburb` with a font size between those of level 8 administrative subdivision and `place=locality/neighborhood`, which would keep the depiction that suburbs are more important than localities and neighborhoods, but less than a level 8 administrative subdivision; or
- rendering `place=suburb` all the same than `place=locality/neighborhood` to unify places rendering.

These are the two possibilities I have in mind, but there can be others, better ones I didn't think about.

I will keep the mismodelled `place` as it until the problem has been either acknowledged or discarded.

Regards.

**Comment by math1985** [comment]
I think this was caused by outdated (cached) tiles. As far as I can see, the problem seems to have resolved itself now.

The progression for suburbs is:
* small black letters from z12
* bigger light letters from z14 (and even bigger from z16)

Apart from this, place names don't get rendered if rendering them would cause the name to overlap another placename.

Code: https://github.com/gravitystorm/openstreetmap-carto/blob/master/placenames.mss

**Comment by Penegal** [comment]
In fact, the `place` tag was corrected by another user to `place=neighborhood` hours before you looked at it, even before I opened this issue, and I'm pretty sure it wasn't caching, as [the node did not exist before](https://www.openstreetmap.org/node/3984609477/history), I created it with `place=suburb`, and later saw a problem and opened this issue, but the other user corrected the node in the meantime, and that's for this node's changes. The sequence of events doesn't seem likely to produce such a caching glitch; should't someone attempt to reproduce the problem before discarding it?

**Comment by math1985** [comment]
I refreshed the page myself, and after that, I saw the rendering changed, so I'm sure there was at least some kind of caching issue.

if the issue is indeed like you described (larger font on lower zoom level), I think we should have seen it elsewhere as well. I also checked the code, and couldn't find anything that would cause this.
