### ISSUE TITLE
Access restrictions on motorways nearly invisible

### ISSUE THREAD

**Issue by Klaus-Tockloth** [gravitystorm/openstreetmap-carto#2053]
![bildschirmfoto 2016-02-21 um 17 38 20](https://cloud.githubusercontent.com/assets/5493128/13203892/20e1b502-d8c2-11e5-9e6b-d5b79adfdb3d.jpg)

Link: https://www.openstreetmap.org/#map=15/50.9541/7.0400

Possible solution: Use a non-transparent color.

**Comment by trigpoint** [comment]
Is that really a problem, in this case I would have tagged it as highway=construction, construction=motorway_link rather than use an access restriction.

**Comment by matkoniecz** [comment]
I tested access restriction stripes with all road types to avoid making them both too prominent and invisible.

Can somebody else give their opinion whatever motorway access restriction are too visible/hidden and require further tuning or are OK?

Also, this case it seems that there is no data problem - at least according to note on way this road is not under construction, it is closed due to construction taking place elsewhere.

**Comment by kocio-pl** [comment]
For me tuning would be useful, however if it proves to be complicated, I wouldn't push it too hard.

**Comment by HolgerJeromin** [comment]
For me the current version is quite visible. Tested on desktop and mobile screen.
