### ISSUE TITLE
use either name.size.ext or name-size.ext for all symbol files

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2062]
extracted from https://github.com/gravitystorm/openstreetmap-carto/pull/2042#issuecomment-182739807

**Comment by math1985** [comment]
I noticed that some other open-source projects have an 'easy' label for tickets that are easy to pick up for new contributors. I think labelling such tickets is a great way to make it easier for people to start contributing to open-source projects, so I'd like to start doing this in our repository as well.

This issue seems suitable, so I added the easy label to it.

**Comment by kocio-pl** [comment]
If someone is going to pick it up, then go ahead, I would not object, but if not, I'm self assigned to do this (mainly cleaning my mess).

**Comment by math1985** [comment]
Don't worry, it has always been a mess, long before you started with the files :)

**Comment by kocio-pl** [comment]
One could also play with SVG internals (like layer names and ids) or moving all 16px version to 14px.
