### ISSUE TITLE
Recolour leisure=golf_course to distinguish scrub

### ISSUE THREAD

**Issue by Yorkshire-Jack** [gravitystorm/openstreetmap-carto#2069]
# Problem:
## Golf course and scrub use same colour

Currently, golf courses and scrub use the same fill colour.  Near me, it is common to find gorse growing on golf courses, and it's mapped (correctly, IMO) as scrub. This leads to the scrub blurring into the course.  Additionally, since the scrub icon looks a little like long grass, people tag for the renderer and use it to indicate areas of longer grass or rough.
A typical example can be found in Edinburgh https://www.openstreetmap.org/#map=16/55.9102/-3.1955
![scrub_golf](https://cloud.githubusercontent.com/assets/17168780/13547113/1f2dc1fc-e2bc-11e5-8561-9846a2d2a73c.png)
## Golf course and water look quite similar

Also on the above example is a small lake on the course which has been tagged natural=water.  It's quite hard to distinguish, though that could be fixed if any changes are made as a result of current similarity to woodland, see #1781
## Tagging grass on golf courses

Note that the fairways in the above example have been tagged `landuse=grass`, which makes them visible. I consider this to be tagging for the renderer, as that's not what `landuse=grass` is for. Taginfo has 2500 golf courses worldwide,  and a similar number of `golf=green`s. Since golf courses have 9-18 greens, <10% of courses have `golf=` tagging, and of those that do, around 25% also have grass tagging, so this affects about 2% of total courses. The may be more which are tagged as `landuse=grass` but not `golf=`, but I can't find an easy way of counting those.
# Suggestions
## Use the same colour as grass

`natural=grassland`, `landuse=grass`, `landuse=meadow` `leisure=garden` and probably others all use the same colour.  Since that covers everything from manicured lawns to rolling open land with knee length grass, golf courses could fit into this easily. They would stay visible on the map because they also get an icon.  It would make the fairways in the above example disappear, whether that's a good thing probably depends if you consider it tagging for the renderer.
This option would be in keeping with the desire to simplify the map expressed in #1630.
## Use the same colour as sports pitches

Golf courses are somewhere you go to play a sport, just like a pitch.  The downside of this is that pitches are quite a dark colour, and golf courses are quite large, so they might receive undue prominence. This option also seems to fit #1630 reasonably well.
## Keep a unique colour.

Another option would be to keep rendering golf courses differently from grass and pitches, but chose another colour.  I do think it's worth making it different from scrub though.
# Interaction with #661

Rendering of various `golf=` tags has been requested.  That issue has been open for a 18 months with little action but it hasn't been closed wontfix so I'll assume it's still being considered but at low priority.  If you decide to render `golf=` features, then this will be the background colour.  In that case rendering `leisure=golf_course` as grass and `golf=` features as sports pitches might work well.

**Comment by polarbearing** [comment]
Probably all sport pitches, including golf, should be mapped as outline, see general discussion in #1624.

That would leave room for all landcover micromapping inside.

**Comment by Tomasz-W** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/426

As golf course is not a type of physical landcover (landuse=grass is) but kind of campus, I think it should be rendered with an outline, not green fill which apparently causes problems.

**Comment by jeisenbe** [comment]
@Tomasz-W, back in July you suggested that golf courses have an outline, but more recently suggested using the leisure color as fill. Any new thoughts on this? I think an outline may work better than fill with leisure color, because golf courses are rather large areas, and ideally each part of the golf course can be tagged specifically as rough, fairway, green, tee, bunker, forest, water and so on. With an outline, we could render the different areas within the golf course. 

The main problem will be deciding on a good display for "rough" (medium-tall grass) vs "fairway / tee / green" (short to very short grass). 

If a fill was used, we would probably need to render golf=rough the same as leisure color, so that the shape of the golf course does not disappear when fully mapped.

**Comment by Tomasz-W** [comment]
@jeisenbe Fill change to @_leisure_ colour at least + optional outline adding (see https://github.com/gravitystorm/openstreetmap-carto/issues/3045)

**Comment by mboeringa** [comment]
The current fill rendering causes people to mistag the **leisure=golf_course** as multipolygons, while this tag should be only on the outline of the facility. Instead, many of the multipolygons objects now tagged as **leisure=golf_course** are in fact on the areas with grass, and should have been tagged **landuse=grass** instead.

I routinely correct this situation whenever I encounter it, but it is a really common mistake due to the current fill rendering.

**Comment by Adamant36** [comment]
@mboeringa, according to the wiki areas within a golf course are suppose to be tagged as a multipolygon. Although I disagree with it, that might be why your seeing it. Also, according to the wiki they aren't supposed to be tagged as landuse=grass. As its tagging for the render. So that's probably wrong.

**Comment by mboeringa** [comment]
> @mboeringa, according to the wiki areas within a golf course are suppose to be tagged as a multipolygon.

@Adamant36 
The first sentence of the **How to map** section reads:

_"Create an area and tag it leisure=golf_course."_

There is no mention of the leisure=golf_course object needing to be a multipolygon on the Wiki page of **leisure=golf_course**:

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course

In fact, I don't see the word "multipolygon" mentioned anywhere on that page, so perhaps you are referring to some other page??

To me this reads simply as _"Draw a closed way around the perimeter of the entire course and tag it leisure=golf_course"_, although I agree it would be much better if that were stated explicitely ;-)

**Comment by Adamant36** [comment]
@mboeringa, my bad. I was reading the wiki page for golf=green. It says "If the green is within the fairway, it should be cut out with a relation of type multpolygon." Which I maybe wrongly assumed  would the whole ting an inner relation to the golf course, or something. 

If the green is a relation to the fairway, then it would make sense the fairway would be a relation to the course. I don't know. It should really be more clear. That's probably why there's issues. Although there is also rampant miss use of relations in general. So it could just be that.

**Comment by mboeringa** [comment]
@Adamant36, there is nothing wrong with people tagging the green as multipolygon, as long as they don't tag it additionally with leisure=golf_course. The green and golf course should be to distinct objects, with leisure=golf_course tagged on the outline of the facility.

Of course, if the golf course has two or more distinct parts separated by a e.g. a wide road (which is quite common), than using a multipolygon to wrap the outlines of both parts into one object tagged leisure=golf_course is also valid.

It is just the leisure=golf_course objects with dozens of inners (due to incorrectly combining the green and golf course tagging on one object), that is really wrong imo.

**Comment by Adamant36** [comment]
@mboeringa, oh. That makes sense. Thank's for the explanation. I agree about the bunch of inner relations. Totally wrong imo also.

**Comment by dieterdreist** [comment]
sent from a phone

> On 28. Nov 2018, at 19:04, mboeringa <notifications@github.com> wrote:
> 
> To me this reads simply as "Draw a closed way around the perimeter of the entire course and tag it leisure=golf_course", although I agree it would be much better if that were stated explicitely ;-)
> 


an area means any kind of area, it can be a closed way, or a multipolygon relation, or any other kind of area.

**Comment by mboeringa** [comment]
> an area means any kind of area, it can be a closed way, or a multipolygon relation, or any other kind of area.

Fully agree, that is why I also wrote in my last post that, in case the golf course consists of multiple disjunct areas e.g. separated by a road or agricultural field, that using a MP relation relation to combine the outlines of the areas in one object makes sense.

However, the Wiki page about **leisure=golf_course** certainly does not prescribe:

_"Create an area and tag it leisure=golf_course **creating a multipolygon and include all fairways or greens as inners of the multipolygon**"_

which is essentially what is happening now in many cases. Usually, the areas tagged as such, should be **landuse=grass**, because that is what it essentially is, or, more according to Wiki, **golf=fairway** (but that doesn't render). Actually, I am not entirely sure why the Wiki explicitely excludes using landuse=grass. I think there is not much wrong in a double tag **landuse=grass + golf=fairway**, which would suite both a generic renderer unaware of golf tagging, and more specialized renderers also recognizing golf=*. Yes, of course it is a little bit more work to tag, but landuse=grass isn't technically wrong, there is cultivated grass there after all.

**Comment by dieterdreist** [comment]
sent from a phone

> On 29. Nov 2018, at 19:47, mboeringa <notifications@github.com> wrote:
> 
> "Create an area and tag it leisure=golf_course creating a multipolygon and include all fairways or greens as inners of the multipolygon"
> 
> which is essentially what is happening now in many cases.
> 

excluding fairways and greens from a golf course doesn’t make sense

**Comment by mboeringa** [comment]
> excluding fairways and greens from a golf course doesn’t make sense

Agree, but this is what people do... I think about 30% of golf courses is tagged with such a multipolygon, e.g. this is just a small example:

https://www.openstreetmap.org/relation/7658268#map=17/50.75472/-1.26729

**Comment by jeisenbe** [comment]
I assume they are doing this so that they can tag the greens and fairways
as landuse=grass and be sure that it will render?

This suggests we could help fix this by rendering golf=fairway, golf=green
etc as grass or similar.

**Comment by jeisenbe** [comment]
This issue was mostly fixed by #3529, especially the first issue "Golf course and scrub use same colour", and the second point "Golf course and water look quite similar" may have been fixed by the earlier water color change. 

Probably this issue can be closed, since #661 is still open to consider different colors for various golf features.

**Comment by HolgerJeromin** [comment]
> Probably this issue can be closed, since #661 is still open to consider different colors for various golf features.

#661 is closed since 6 month :)
But still a +1 for closing this.

**Comment by jeisenbe** [comment]
Closed by #3529
