### ISSUE TITLE
leisure=nature_reserve labelled along boundary as well as at centroid 

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#2070]
Hi

Is this intentional:

![nature_reserve](https://cloud.githubusercontent.com/assets/9528328/13547717/c741bc00-e2d4-11e5-9a5e-bfe6ad1e51d8.JPG)

I don't remember it occurring previously.

**Comment by mrwojo** [comment]
Warmley Forest Park: http://www.openstreetmap.org/way/38757891

The boundary text was added in 2014, and is shown only when the NR appears large (at least 192,000 pixels, which if square would be about 438x438 px).

Area is not an ideal condition for showing boundary text, but in many cases I've seen it seems to be "good enough". The given example is especially awkward due to the coincidental placement of the text at the tip of a concavity right at the centroid.

Boundary labels on long and/or concave objects can be more readily seen than the centroid label. Consider "Elmer Feldenheimer State Natural Area":
http://www.openstreetmap.org/relation/1438877#map=15/45.9681/-123.9509

See also: #1028

**Comment by matkoniecz** [comment]
It is useful for really big areas like http://www.openstreetmap.org/#map=17/50.14531/19.67638 

![selection_001](https://cloud.githubusercontent.com/assets/899988/13549648/64c5e4b2-e30a-11e5-8bf9-bd638e8309f0.png)

Rendering at http://www.openstreetmap.org/#map=17/51.46274/-2.46999 is not the best, maybe increasing minimal NR size for it to appear may be a good idea.

**Comment by kocio-pl** [comment]
Any idea what size should be the lower limit for rendering boundary labels?

**Comment by kocio-pl** [comment]
I don't see such problems with rendering names of protected areas and this one doesn't look like a serious problem, therefore I close this issue now. It can be reopened if there is more input how should it be solved.
