### ISSUE TITLE
update list of shops rendered as dot

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2090]
Without any new filtering at this moment it would result in following changes (based on https://gist.github.com/matkoniecz/1a33e35fcf32ac4cccc3 generated based on https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/shop_values.rb and the current query):

Removed: "phone", "real_estate"

Added: "agrarian", "anime", "auto_parts", "bathroom", "cafe", "candy", "catalogue", "doors", "fishmonger", "glass", "haberdashery", "lamps", "marketplace", "nutrition_supplements", "party", "perfume", "plumber", "provisions", "storage_rental", "storage_units", "street_vendor", "supplements", "swimming_pool", "tableware", "watch", "water", "weapons", "wedding", "window_blind", "windows", "wood"

auto_parts seems to be a clear duplicate of car_parts, there are also other dubious entries.

But raising threshold to 150 gives much better results:

Removed: "builder", "building_materials", "camera", "car_service", "medical", "phone", "real_estate", "salon", "tanning"

Added: "anime", "fishmonger", "haberdashery", "lamps", "marketplace", "party", "storage_rental", "street_vendor", "water", "weapons", "window_blind", "windows"

Added entries make sense (and at least some are documented), removed are undocumented, some are in addition duplicates of documented more popular values.

I would only propose to not include shop=storage_rental as it is not a shop (see failed proposal at http://wiki.openstreetmap.org/wiki/Proposed_features/shop%3Dstorage_rental).

**Comment by matkoniecz** [comment]
Also shop=street_vendor may be worth excluding. What is it supposed to be? Shop selling street vendors? Or a separate tagging scheme not categorizing by what is sold but how?

I am not sure what makes less sense.

**Comment by HolgerJeromin** [comment]
We have amenity = marketplace approved

**Comment by matkoniecz** [comment]
Case of fishmonger is weird - it is appearing in https://github.com/gravitystorm/openstreetmap-carto/blob/6a7a9cc938f2529bcd6f55b277e17efb72f50c14/amenity-points.mss#L676 but it is not appearing in https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml so it is probably not rendered.

It is also not excluded by https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/shop_values.rb

Curious.

**Comment by HolgerJeromin** [comment]
It was planed to render. We had discussed this value.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 14.03.2016 um 23:21 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> I would only propose to not include shop=storage_rental as it is not a shop (see failed proposal at http://wiki.openstreetmap.org/wiki/Proposed_features/shop%3Dstorage_rental).


hasn't storage_units the same issues? Isn't candy a duplicate of confectionery?

**Comment by matkoniecz** [comment]
That is why I propose to raise threshold to 150 as it gives much better results:

>But raising threshold to 150 gives much better results:

>Removed: "builder", "building_materials", "camera", "car_service", "medical", "phone", "real_estate", "salon", "tanning"

>Added: "anime", "fishmonger", "haberdashery", "lamps", "marketplace", "party", "storage_rental", "street_vendor", "water", "weapons", "window_blind", "windows"

**Comment by dieterdreist** [comment]
2016-03-15 11:28 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> Removed: "builder", "building_materials", "camera", "car_service",
> "medical", "phone", "real_estate", "salon", "tanning"
>
> Added: "anime", "fishmonger", "haberdashery", "lamps", "marketplace",
> "party", "storage_rental", "street_vendor", "water", "weapons",
> "window_blind", "windows"
>


I feel many of these have issues and have not been discussed on the tagging
mailing list and there is no proposal. Some of those that now get removed
have been discussed on the other hand, e.g. "building_materials", "camera"
or are at least unambigous: "car_service", "real_estate" (maybe an "_agent"
should be appended), "tanning".

some issues that come to mind (from the added list):
* shop=marketplace does make no sense (or is this about
amenity=marketplace?)

* shop=party is not defined:
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dparty
* shop=storage_rental is rejected and there are only proposal and
discussion pages, no feature page:
http://wiki.openstreetmap.org/wiki/Proposed_features/shop%3Dstorage_rental

* shop=street_vendor as said before, this is not fitting into the general
scheme

* shop=water there is no definition and it is not a good tag (no clear
meaning, ambiguous, too generic):
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dwater

* shop=weapons no proposal and a restrictive definition that likely has
been sneaked unilaterally into the wiki:
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dweapons should be on a
proposal page, why is this not called "arms" or even "firearms" (like the
current definition suggests)?

* shop=window_blind there's no proposal and very few use, why's that a tag
page? http://wiki.openstreetmap.org/wiki/Tag:shop%3Dwindow_blind why isn't
this called "window_blinds"? There's barely a definition for this either.

* shop=windows has been unilaterally (AFAIK) discouraged, hasn't a
definition, wasn't discussed neither before nor after it was unilaterally
deprecated and has very few uses (compared to the kind of shop):
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dwindows

___

based on these considerations, I'd rather add only these as shop values:
anime
fishmonger
haberdashery
lamps

and from the other list:
building_materials
camera (s)?
car_service
real_estate_agent
tanning  (something like amenity=tanning_studio might make more sense, or
tanning_salon), also to disambiguate from shops that sell tanning equipment

on a general note I feel we should encourage more verbose tags, because
stuff like shop=water really doesn't work without further definitions,
especially in a global context.

**Comment by trigpoint** [comment]
> hasn't storage_units the same issues? Isn't candy a duplicate of confectionery?
Candy translates into English as sweets, confectionery is fancy cakes.

**Comment by dieterdreist** [comment]
2016-03-15 12:21 GMT+01:00 trigpoint <notifications@github.com>:

> hasn't storage_units the same issues? Isn't candy a duplicate of
> confectionery?
> Candy translates into English as sweets, confectionery is fancy cakes.



wikipedia has different opinions on this:
https://en.wikipedia.org/wiki/Confectionery

*Confectionery*,[1]
<https://en.wikipedia.org/wiki/Confectionery#cite_note-1>[2]
<https://en.wikipedia.org/wiki/Confectionery#cite_note-2>[3]
<https://en.wikipedia.org/wiki/Confectionery#cite_note-3>[4]
<https://en.wikipedia.org/wiki/Confectionery#cite_note-4> also called
*sweets* or *candy* is sweet food product. The term varies among
English-speaking countries.[5]
<https://en.wikipedia.org/wiki/Confectionery#cite_note-5> In general,
though, confectionery is divided into two broad and somewhat overlapping
categories, *bakers' confections* and *sugar confections.*[6]
<https://en.wikipedia.org/wiki/Confectionery#cite_note-6>


https://en.wikipedia.org/wiki/Confectionery_store

A *confectionery store* (more commonly referred to as a *sweet shop* in the
United Kingdom, a *candy store* in North America, or a *lolly shop*[1]
<https://en.wikipedia.org/wiki/Confectionery_store#cite_note-1> in
Australia) sells confectionery <https://en.wikipedia.org/wiki/Confectionery>
and is usually targeted to children. Most confectionery stores are filled
with an assortment of sweets far larger than a grocer or convenience store
could accommodate. They often offer a selection of old-fashioned treats and
sweets from different countries.


See also: http://www.oxforddictionaries.com/definition/english/confectionery


Until one year ago, this was the photograph in the OSM wiki:

http://wiki.openstreetmap.org/wiki/File:Sweet_Shop,_Chester.JPG  (I just
noticed now and will revert this)

changed here:
http://wiki.openstreetmap.org/w/index.php?title=Tag:shop%3Dconfectionery&oldid=1123242

**Comment by kocio-pl** [comment]
I was trying to clean the state of "dotted" shops, but still didn't finish it. I made [a list of different issues](http://wiki.openstreetmap.org/wiki/User:Kocio/shop_review) on my Wiki and I started [a discussion on a Tagging list](https://lists.openstreetmap.org/pipermail/tagging/2015-October/026828.html), which was detailed and quite intensive for some time, but it was in the fall and I still didn't summarise it before returning to the community with some outcome.

The whole thing is long overdue, but not abandoned - it's still on my radar.

**Comment by math1985** [comment]
shop=glass seems to be duplicate with shop=glaziery.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 20.03.2016 um 08:44 schrieb math1985 <notifications@github.com>:
> 
> shop=glass seems to be duplicate with shop=glaziery.


at least after you have declared it a duplicate in the wiki ;-)
As the meaning of shop=glass isn't inherent (unlike glaziery, which is a common word in English), and it isn't documented in the wiki, you hardly can tell. Please do not create feature pages for undocumented tags in the wiki without consulting the lists about possible meanings (and even then preferably create a proposal page rather than a feature page).

**Comment by matkoniecz** [comment]
Changes that I proposed have no clear support, there are some beneficial changes that now have PRs. So I am closing this issue.
