### ISSUE TITLE
stop rendering shop=yes

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2099]
Rendering shop=yes and not rendering rare shop values encourages to omit detail during tagging - for example I almost tagged https://www.openstreetmap.org/way/406428679#map=19/50.07983/19.87729 as shop=yes just to get it to render on map.

I think that it is not a desirable effect.

**Comment by aceman444** [comment]
So why do we not render any shop=*?

**Comment by HolgerJeromin** [comment]
@aceman444  We do not want to hide typos for example. shop=suprmarket would be not valid (or a bad idea at least), so the default map should not provide the feedback that this is a correct entry.

**Comment by moliha** [comment]
A general problem-icon could be usefull - this could be a small question mark. This could mark the node as questionable - but the name could be shown. Hiding problem-nodes is the worst "solution" for all:
- The responsible mapper gets no feedback.
- Other mappers, who might be able to fix the problem, are not alerted because it is hidden.
- Map users see nothing where 'something' (and a name) could be usefull.

**Comment by aceman444** [comment]
Holger, typoed values would only show as the dot, not the specific icon, so that would be visible.

**Comment by HolgerJeromin** [comment]
Oh, sure. This requires that you are familiar with the rendering of all valid shop values.
But shop=frame would look the same as shop=frames and 
shop=fabrics will look like the correct shop=fabric

**Comment by HolgerJeromin** [comment]
this style is no QA map. Many websites are using the tiles. There a question mark would be very confusing.

**Comment by pnorman** [comment]
My personal preference is to render shop=* as a dot, but instead we decided to whitelist specific shops. Given this choice, I'm not sure it makes sense to render shop=yes.

**Comment by sommerluk** [comment]
The example is a shop=flower_pot. Maybe, if shop=yes is not rendered anymore, people tend to use related, but wrong tags. I could imagine that someone would use shop=florist instead to get it rendered, and that would be worser than shop=yes…

**Comment by d1g** [comment]
For simplicity, render shop=* (except shop=no or shop=vacant) as dot.

Whitelist-only rendering both: is unrewarding for mappers and painful for style developers.

**Comment by martinum4** [comment]
i agree with sommerluk here, we get highly different names for the same stuff, especially regarding AE/BE there will be different writing of the same stuff then and it will be harder to clean it up afterwards...

**Comment by nighto** [comment]
Hello!

 

You have a new message, please read <http://aksozdokuma.com/broadcast.php?du>

 

nighto@nighto.net

**Comment by gorn** [comment]
I think that the solution is really easy. Render shop=* (except shop=no or shop=vacant) as dot and have specific icon for some often used types of shops. That way if the shop is something common you give visual feedback, that the type is set correctly (icon vs dot) and if it is a rare shop, than you do not encourage fake it by marking it as common category yet rendering it.

**Comment by jojo4u** [comment]
Either
* use whitelist and render shop=yes or
* drop whitelist and don't render shop=yes.

**Comment by aceman444** [comment]
Good point gorn. If any shop will not show at least the dot, people may fake the shop value to get it rendered. Faking as in using some close enough shop type, or just marking everything a supermarket or convenience.

**Comment by kocio-pl** [comment]
I think we should follow the buildings way: there are some special cases (major building rendered in dark brown and popular shops with their own icons), but most of them are just standard and we can just render them accordingly (light brown for most of the buildings, violet dot for shops) - including `building=yes` and `shop=yes`.

At this moment we have **two** shop white lists - popular shops and shop types we consider sane - which is an overkill for general style. One list should be enough. We have about 100 lines just to filter the less used ones and it would probably grow over time to include new types which have passed the lower limit.

It also means we try to take the responsibility to review this list from time to time to get rid for example deprecated ones. And it's not happening - [I've tried to do it year ago](https://wiki.openstreetmap.org/wiki/User:Kocio/shop_review), but got stuck in discussions on Tagging list, because in reality it's a cleaning/defining work, and it's even harder than proposing new types. @HolgerJeromin is right: [osm-carto is not a QA tool](https://github.com/gravitystorm/openstreetmap-carto/issues/2099#issuecomment-203133103). Maybe this attitude was useful some time ago, but the OSM ecosystem is growing and we should let some things go where they really belong to.

Therefore I'd like to implement [@gorn proposition](https://github.com/gravitystorm/openstreetmap-carto/issues/2099#issuecomment-220833412).

**Comment by d1g** [comment]
> Therefore I'd like to implement gorn proposition.

Well go ahead, because in my understanding _everyone_ supporting his view of generic icon/rendering - incuding  aceman444, moliha, pnormal and me


I personally don't understand proposition by @jojo4u - how can have generic style for shops with 
> drop whitelist and don't render shop=yes.

will we render shop=* instead of shop=yes? I think that's the same what pnorman and me said. 

Nobody objects gorn formulaiton?

**Comment by jojo4u** [comment]
> I personally don't understand proposition by @jojo4u - how can have generic style for shops with
>>    drop whitelist and don't render shop=yes.

> will we render shop=* instead of shop=yes? I think that's the same what pnorman and me said.

This same as gorn, only with additional proposition to drop generic shop=yes (somewhere in future) and use shop=* instead. Shop=yes is bad because it looses information and does not give a change to converge values via taginfo and wiki.

**Comment by kocio-pl** [comment]
[Shop=yes is used only for 3.44% of all the shop types](http://taginfo.openstreetmap.org/keys/shop#values), so not a big problem and we can consider dropping it after some passage of time. Currently it may be misused to get less popular shops rendered, so probably it will get even lower than today.

**Comment by HolgerJeromin** [comment]
[10% of shop=yes](http://taginfo.openstreetmap.org/tags/shop=yes#combinations) are combined with amenity=fuel (from old? JOSM preset) which are not rendered anyway as shop.

**Comment by kocio-pl** [comment]
BTW: there are quite a lot of actual "shop=*" tags in OSM database (though explicitly discouraged):

http://taginfo.openstreetmap.org/tags/shop=*

**Comment by dieterdreist** [comment]
I also don't like rendering shop=yes, because I share the concern that it will lead to less precise tagging. Rather than using a form shop=<shoptype> (which is not rendered at all for shop types not on our whitelist) some mappers will use shop=yes which is rendered.

I would either drop rendering support for shop=yes or render every kind of shop besides shop=no/vacant (and maybe some other values).

**Comment by kocio-pl** [comment]
@dieterdreist The numbers show me that although shop=yes misuse is a real problem, it's not as big as we all thought. Do you agree to start with rendering rare shops now and revisit the issue of shop=yes later if needed, as @jojo4u proposed? For me this would be the easiest and safest solution for now.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 19 ott 2016, alle ore 13:54, kocio-pl <notifications@github.com> ha scritto:
> 
> Do you agree to start with rendering rare shops now and revisit the issue of shop=yes later if needed, as @jojo4u proposed? For me this would be the easiest and safest solution for now.


+1
shop=yes could be discussed on the tagging ML, but it's use is already discouraged in the wiki: https://wiki.openstreetmap.org/wiki/Tag:shop%3Dyes

similarly issues are historic=yes, barrier=yes (both with significant use)

**Comment by kocio-pl** [comment]
Well, it's significant just in raw numbers, but the percentage is quite low and that's more important factor for me:
- historic=yes: 43 339 - 6.62%
- barrier=yes: 54 765 - 0.80%
- shop=yes: 81 483 - 3.44%

On the other hand we have also:
- building=yes: 167 196 748 - 82.12%

Any popular tag will have some general values and this may mean just lack of detailed knowledge. When the percentage is low, it's pretty healthy to state it clearly. Buildings may need some special treating, but I guess rendering is not the right tool to fix it.

**Comment by gorn** [comment]
This issue should be closed as declined.

**Comment by kocio-pl** [comment]
I guess it's better to change the title so it describes the problem more precisely.

**Comment by matkoniecz** [comment]
See #3697 - I proposed this change again as usage of shop=yes is growing.
