### ISSUE TITLE
Render man_made=obelisk

### ISSUE THREAD

**Issue by boothym** [gravitystorm/openstreetmap-carto#2126]
Noticed recently when I changed a node tagged as historic=monument to man_made=obelisk, it disappeared from the standard OSM map: http://www.openstreetmap.org/node/1963176957

Can man_made=obelisk please be rendered with the same icon as historic=monument? In the case of Aberdour Obelisk, it does not commemorate anything so it is correctly tagged, but it would be nice to see a large structure shown on the map. Especially as the historic=monument icon seems to be an obelisk!

**Comment by pnorman** [comment]
251 uses of [`man_made=obelisk`](http://taginfo.openstreetmap.org/tags/man_made=obelisk)

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 14 mag 2016, alle ore 21:24, boothym <notifications@github.com> ha scritto:
> 
> Can man_made=obelisk please be rendered with the same icon as historic=monument? In the case of Aberdour Obelisk, it does not commemorate anything so it is correctly tagged, but it would be nice to see a large structure shown on the map. 


+1, I support this, obelisks are very significant but they don't occur very often in the world. We should not only look at usage numbers when deciding which tag to show. (Yes, I am somehow asking for an exception for obelisks because I think they are worth it)

**Comment by boothym** [comment]
Don't think it matters how many uses there are in the world. In the example I gave, the obelisk was wrongly tagged as historic=monument - there's probably other examples where an obelisk has been tagged as a monument to ensure it gets rendered on the map.

**Comment by dieterdreist** [comment]
2016-05-18 13:22 GMT+02:00 boothym <notifications@github.com>:

> Don't think it matters how many uses there are in the world. In the
> example I gave, the obelisk was wrongly tagged as historic=monument -
> there's probably other examples where an obelisk has been tagged as a
> monument to ensure it gets rendered on the map.
>

+1
generally, there are not so many obelisks in the world, Rome is the city
with most monumental antique obelisks and it's only 13 (plus 5 modern
ones).  There are much more waste baskets in the world, and they are also
much more useful, because you can do nothing with an obelisk, it has no
useful function. Still, deciding only on this basis doesn't seem
reasonable. Obelisks are typically used (because of their phallic meaning)
as a symbol of power, therefor you can find them in many symbolic places,
e.g. at Washington DC, Pyongyang in North Corea, in front of the Vatican or
in Paris on Place de la Concorde (before Place de la Révolution, before
Place Louis XV).

My suggestion is to take also "obelisk:size" into account when deciding if
and when to render (after hstore becomes active).

https://en.wikipedia.org/wiki/National_Mall
https://en.wikipedia.org/wiki/Liberation_Monument

**Comment by matkoniecz** [comment]
I think that it may be a good idea, especially as it is reusing existing icon and current rendering encourages mistagging.
