### ISSUE TITLE
Render bridge=yes on highways only if an outline does not exist

### ISSUE THREAD

**Issue by cm8** [gravitystorm/openstreetmap-carto#2129]
[Tag:man_made=bridge](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge#Two_ways.2C_one_level) suggests to draw an outline of the bridge and put all relevant tags of the bridge onto this outline.

Currently this outline is rendered dark gray below the highways running across.

If these are tagged "bridge=yes" in addition (most of the time combined with layer=1), the renderer simply picks this up and draws yet another indication of a bridge, namely black encasings left and right of the line.

It would be nice, if the renderer could detect if a "bridge=yes" tagged highway has its end nodes connected to a bridge outline (man_made=bridge) and would then not render black encasings.

After all, if the bridge outline is rendered explicitly, we can treat the highways running across just as normal highways, _although_ they should continue to be tagged "bridge=yes" for backward compatibility, in case data consumers only filter for highway=* and drop bridge outlines from their dataset.

**Comment by polarbearing** [comment]
Currently ```man_made=bridge``` is just rendered as the footprint of the bridge without considering the layer. All ways are rendered on top, even if they are under the bridge. Thus the encasing still carries important information about the layering of the ways. 

Also I could imagine that, as bridge relations are not in fashion, detecting the dependency between the way and the bridge building would be quite complex.

I don't see the advantage of the proposal.

**Comment by pnorman** [comment]
> It would be nice, if the renderer could detect if a "bridge=yes" tagged highway has its end nodes connected to a bridge outline (man_made=bridge) and would then not render black encasings.

This isn't really practical.

**Comment by mboeringa** [comment]
The technical challenges of this seemingly logical proposal are far more complicated than is obvious at first sight, due to the need to render highway and railway data layered. There is _a lot_ more code and processing involved than the simple final rendering on the OpenStreetMap website ever suggests.

In addition, I am pretty sure many bridges and viaducts still need lots of work and attention in terms of adding appropriate layer and bridge tagging, and exactly matching up **highway=x** features with **man_made=bridge** features.

**Comment by cm8** [comment]
Yes, I know that this involves some thinking.  But unless "we" want to live with people removing "bridge=yes" tags when they add a bridge outline, this complexity seems necessary to accommodate mappers needs.

Tagging for the renderer is a reality, let's face it: when the result is not what people expect, they change data until it fits.

Of course you could argue:  If the outline is drawn, removing bridge tags from the highway is natural and logical - after all, we could lead data consumers filtering bridge outlines from their dataset to copy bridge data to the enclosed highways before throwing away the outline (which moves the workload from this proposal to another point, deliberately breaking backwards compatibility).

But this argument is not compatible with what the wiki suggest now:  Namely to tag bridge information twice in complex scenarios: On the highway and 'around' the highway, which _is_ superfluous, but backwards compatible.

I've been with the project for quite a while, so please don't tell me that it's oh so hard to render a "simple" looking map tile. I know it is. We're here for it.

**Comment by pnorman** [comment]
If you feel it can be done without excessive complexity or performance problems, please provide a PR.

If it turns out to be possible, we'd have to consider the cartography and if we want to, but right now that doesn't matter.

**Comment by polarbearing** [comment]
> But unless "we" want to live with people removing "bridge=yes" tags when they add a bridge outline

Do you have examples that people remove bridge tags from the highway when adding the outline? This would be against the wiki saying ```Ways across the bridge should be tagged with the same values of layer=* and bridge=* as the outline```. In the areas I am familiar with they are kept.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 19 mag 2016, alle ore 05:03, cm8 <notifications@github.com> ha scritto:
> 
> I've been with the project for quite a while, so please don't tell me that it's oh so hard to render a "simple" looking map tile. I know it is. We're here for it.
> 


problems with the procedure you describe are: 
- connected to any bridge area is not sufficient, must be connected to the same bridge area than it is itself on (must be inside, same layer)
-bridge highway might be split for different reasons rather than being one single way(would have to be recombined for the part inside the bridge area)
-part of a complex multiple bridge situation might be mapped as area, other not (requires maybe splitting of the highway bridge=yes way)
- bridge area might be a multipoligon relation rather than tags on ways

**Comment by mboeringa** [comment]
I think the only viable solution for this, that could be implemented easily and not require extensive code changes, is to introduce a new secondary tag that tells the renderer the bridge line feature has an associated **man_made = bridge** feature. Processing OSM bridge relations or doing global scale geoprocessing, isn't something easily implemented...

E.g., there could be a tag like
**hasbridgeoutline = yes**

With an extra tag, you would only have to do something like this in SQL, which is easily implemented:

**(hasbridgeoutline IS NULL OR hasbridgeoutline IN ('','no'))**

to exclude the bridge casings for those **highway = x** lines that have an associated bridge feature. This is far easier than any other solution.

However, there is the secondary problem of the fact that man_made = bridges probably do not display at the same scale ranges as highways, so in order to ensure we don't have a situation where bridge casings aren't shown, and neither man_made = bridge features, the two would need to be carefully matched in the style in terms of display scales / zoom levels.

**Comment by jojo4u** [comment]
location=bridge has been proposed for this: https://wiki.openstreetmap.org/wiki/Proposed_features/Simplify_man_made%3Dbridge_mapping#Ways_on_bridges

**Comment by mboeringa** [comment]
> location=bridge has been proposed for this: https://wiki.openstreetmap.org/wiki/Proposed_features/Simplify_man_made%3Dbridge_mapping#Ways_on_bridges

OK, I hadn't seen that page yet.

**Comment by cm8** [comment]
> Do you have examples that people remove bridge tags from the highway when adding the outline?

@polarbearing See e.g. http://overpass-turbo.eu/s/gkm for lots of instances in the city of Leipzig.

> problems with the procedure you describe are

@dieterdreist All true, but if we do not move on this issue it stays ugly as it is.
- An alternative to detect whether highway is connected to outline, is to depend on bridge-relation membership (i.e. do not render encasings of a highway if it's part of a bridge relation in role 'across').
- Another alternative is to depend on location=bridge as favoured by @mboeringa and @jojo4u (i.e. do not render encasings if a highway is tagged with location=bridge, regardless of bridge and layer tags)

> location key seems fine here

@jojo4u I agree, this might be a quick and sound solution and seems to be in conformance to established or proposed wiki documentation.  However, imho it will need to be highlighted that bridge=yes is _not_ to be deleted from highways and that location=bridge is only to be tagged in addition if an outline exists (else we get false positives when dropping black encasings).

We should also try to stress that layer=0 is to be used unless there are bridges running across bridges - i.e. the highway should have the same layer tag as the outline (which is by default none).  

Iirc josm validator complains about crossing high-/waterways if layer is not used.  However, if layer=1 is indeed used, this leads to rendering artifacts. E.g. for the render result of a highway with tramway tags in addition:  the half-round caps just use the highway fill color while the shape edge is transparent/not drawn.  This leads to the impression that the tramway on the bridge is disconnected to the continued layer=0 highways leading away from the river.
(This is presumably the reason why some mappers have removed layer=1 tags, independent from an outline being drawn or not.)

**Comment by mboeringa** [comment]
> Iirc josm validator complains about crossing high-/waterways if layer is not used. However, if layer=1 is indeed used, this leads to rendering artifacts. E.g. for the render result of a highway with tramway tags in addition: the half-round caps just use the highway fill color while the shape edge is transparent/not drawn. This leads to the impression that the tramway on the bridge is disconnected to the continued layer=0 highways leading away from the river.

Basically agree with bridges not necessarily needing layer = 1, most of them can stay at layer = 0.

Most renderers don't consider layer = x for waterways, and treat bridges as running on top of waterways always (and this is probably in 99.99% of cases true, except for aqueducts), so layer = 0 will still result in the highway feature being correctly displayed on top of the waterways.

However, contrary to my ArcGIS renderer in development, where setting the bridge to layer = 0 (more correctly: to the same value as the roads leading up to it) will avoid rendering artefacts at the connection between lines "on the bridge" and the ones connecting them, this _isn't_ a solution in Carto. @math1985 has explained this well in the lengthy discussion we had back in 2014 in this thread: #934

**Comment by jojo4u** [comment]
>  the highway should have the same layer tag as the outline (which is by default none). 

Layer=* is documented and in reality used (75%) for the outline?!

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge
https://taginfo.openstreetmap.org/tags/man_made=bridge#combinations

**Comment by dieterdreist** [comment]
2016-05-19 19:51 GMT+02:00 cm8 <notifications@github.com>:

>
>    - An alternative to detect whether highway is connected to outline, is
>    to depend on bridge-relation membership (i.e. do not render encasings of a
>    highway if it's part of a bridge relation in role 'across').
>
>
we should not require bridge relations to avoid rendering of bridge casings
for those cases, where a deficated bridge object (outline) is mapped. I'm
not even sure if we should remove the casing then. Likely should be handled
differently on different zoom levels (because highways will soon become
bigger than the bridge areas with lower zoom levels).



>
>    - Another alternative is to depend on location=bridge as favoured by
>    @mboeringa <https://github.com/mboeringa> and @jojo4u
>    <https://github.com/jojo4u> (i.e. do not render encasings if a highway
>    is tagged with location=bridge, regardless of bridge and layer tags)
>
> location key seems fine here
>
>

no, because it is a key that says something different, you can't use it
here for what you want it to do (state if there is a separately mapped
man_made=bridge object). For instance you would have to delete the
location=bridge tag for all highways on bridges, where these bridges are
not mapped as man_made=bridge, although the tag is not wrong.

**Comment by mboeringa** [comment]
> no, because it is a key that says something different, you can't use it here for what you want it to do (state if there is a separately mapped man_made=bridge object).

OSM tag interpretation is all about semantics: what meaning do we give to a certain key=value combination? The latter is (hopefully / usually) documented in the Wiki pages.

That means that it isn't wrong per se to use the location = bridge tag for this purpose, if this is the first (and documented) usage of this key / value combination. There are tons of similar cases where the literal interpretation of a tag doesn't always (perfectly) match the documented and practiced usage of a certain key / value combination.

> For instance you would have to delete the location=bridge tag for all highways on bridges, **where these bridges are not mapped as man_made=bridge**, although the tag is not wrong.

Following my reasoning, we need to question if the tag location = bridge has been used right in these cases, if the documented usage says something else?

Anyway, I am nitpicking here... I am OK with whatever tag people come up with and properly document in the Wiki.

**Comment by pnorman** [comment]
Given the above discussion, I'm going to close it. It either requires a spatial query that is likely to be too complex or will require tagging discussion and tagging changes, which are off-topic here.

**Comment by cm8** [comment]
> For instance you would have to delete the location=bridge tag for all highways on bridges, where these bridges are not mapped as man_made=bridge, although the tag is not wrong.

This is your subjective pov.  I feel it is very wrong to tag location=bridge if there is no man_made=bridge in the data that location=bridge could loosely refer to.

**Comment by cm8** [comment]
> Given the above discussion, I'm going to close it. It either requires a spatial query that is likely to be too complex or will require tagging discussion and tagging changes, which are off-topic here.

@pnorman This is closed way too early.  The only discussion that would be needed is, if location=bridge is understood/interpreted to refer to a bridge outline also part of the data.  This solution also avoids complex spatial queries which people have openly become lazy about.

**Comment by mboeringa** [comment]
> This solution also avoids complex spatial queries which people **have openly become lazy about.**

I doubt this is the case...

I am not a Carto maintainer, but from my own experience building a renderer from scratch (for ArcGIS), I am well aware what consequences such requests for spatial queries and geoprocessing have.

The two basic problems with these requests are:

- Each of these "spatial query" problems is often unique, instead of the mostly generic general "attribute based" selections that most of the rendering is based on. They require custom code, meaning the complexity of the rendering process increases with each of such request (and the rendering process is already pretty or hugely complex). Hence the reluctance to increase the complexity of an already highly complex process (also take into account the volunteer aspect here, people don't have unlimited time, and there are other priorities for the maintenance of the style as well).

- Spatial queries of the non-bounding box type, or even true geoprocessing by intersecting e.g. lines on lines to derive new features, are generally very much slower in comparison with basic attribute selections in any spatial database or GIS. Since the render databases and server need to facilitate the entire globe in near real time, this means they have significant impact on the ability to do so. It is one thing to do a one-off complex geoprocessing operation against a spatial database the size of OpenStreetMap and maybe wait a couple of days for it to finish, it is something different if this needs to be done in a continuously updated database in near real time... The size of the entire planet OSM database is just mind boggling by now, and it is growing fast!

**Comment by polarbearing** [comment]
> See e.g. http://overpass-turbo.eu/s/gkm for lots of instances in the city of Leipzig.

thanks. In the [first example](http://www.openstreetmap.org/way/357114161) I looked at, the bridge tagging was removed from a highway by a fresh mapper, without even connecting to the outline. The same mapper [moves playgrounds from their location](http://www.openstreetmap.org/changeset/34522469) to get a place name rendered :-(

As long as the well-established bride=yes on a highway is not officially deprecated, removing it because a man_made has been drawn, is a tagging error for me.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 20 mag 2016, alle ore 01:37, mboeringa <notifications@github.com> ha scritto:
> 
> Following my reasoning, we need to question if the tag location = bridge has been used right in these cases, if the documented usage says something else?


we should continue this discussion on tagging ml. IMHO what is suggested here would unnecessarily increase complexity and would not work (not enforceable). I m not against a tag in general that states on a highway on a bridge that there is an outline mapped for this bridge as well, but it should be a tag that says so explicitly, not something generic like "location" that would have to be bent in meaning to cater for the intended use.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 20 mag 2016, alle ore 02:12, cm8 <notifications@github.com> ha scritto:
> 
> @dieterdreist This is your subjective pov. I feel it is very wrong to tag location=bridge if there is no man_made=bridge in the data that location=bridge could loosely refer to.
> 


why that? Since when is there a connection between man_made=bridge and the location tag on another object? The location tag is about the location something is (e.g. roof top, underground, if you like also bridge), it doesn't say anything about other features.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 20 mag 2016, alle ore 09:57, polarbearing <notifications@github.com> ha scritto:
> 
> As long as the well-established bride=yes on a highway is not officially deprecated, removing it because a man_made has been drawn, is a tagging error for me.


+1, I'm against deprecating it. It is an attribute on the road and useful for many reasons

**Comment by cm8** [comment]
> +1, I'm against deprecating it. It is an attribute on the road and useful for many reasons

Seems all thread participants agree on this.  I also think extracting highway=* is very common task, just see osmand for instance.  And it'd be pretty hard and computationally expensive to re-add bridge=yes if it was removed from the ways.

> The location tag is about the location something is

It's an interpretation thingy and since there has not been an awful lot of discussion about it, there's also _room_ for interpretation.  If bridge=yes already says 'this part of highway runs across a bridge' then it'd be very redundant to use location=bridge to say the same.  _Unless_ there is a bridge outline in the data that this tag weakly refers to, that is.

If you do not interpret it (in this case only) as an indicator for a bridge outline then it is obsolete in the presence of bridge=yes. You've argued about the location tag as if it is stuck isolated in the highway tag list, when bridge=yes must be taken into account as well.

Of course we can make up and stuff yet another tag relating to bridge presence and relation into the tag list, but why, when we can use location=bridge for this?  (and bridge=yes as the generic tag for bridge presence -> we do not exchange those, because bridge=yes is presumably older than location=*)

> I doubt this is the case...

@mboeringa I did not want to be pushy in general, I was referring to this thread _only_.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 21 mag 2016, alle ore 00:44, cm8 <notifications@github.com> ha scritto:
> 
> The location tag is about the location something is
> 
> It's an interpretation thingy and since there has not been an awful lot of discussion about it, there's also room for interpretation.  If bridge=yes already says 'this part of highway runs across a bridge' then it'd be very redundant to use location=bridge to say the same. Unless there is a bridge outline in the data that this tag weakly refers to, that is.
> 
> If you do not interpret it (in this case only) as an indicator for a bridge outline then it is obsolete in the presence of bridge=yes.
> 


osm is a project with new contributors every day. If you don't have a lot of historical OSM knowledge and come along an object with bridge=yes and location=bridge you might recognize this as redundant, but it won't be clear which of the two is less important, and you surely wouldn't think that one of them is an indication whether there are other objects drawn nearby with a relation to this.

My suggestion for an additional tag would be something really explicit, like separate_outline=yes


cheers,
Martin

**Comment by pnorman** [comment]
> we should continue this discussion on tagging ml

Yes.
