### ISSUE TITLE
Improve lower mid zoom levels

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#2194]
There is a lot of room to improve the lower mid zoom levels (z6 to z9). They come across as rather unpleasant and hard to read.

Some alternative renderings that do, in my opinion, a much better job:
https://geodienste.lyrk.de/
http://korona.geog.uni-heidelberg.de/
http://www.cartogiraffe.com/
http://maps.sputnik.ru/
http://osm2vectortiles.org/
I'm not sure if they're solely using osm-data for these zoom levels though.

I wonder what improvements we could make to make these zoom levels look better?

Cc @matkoniecz

**Comment by math1985** [comment]
@matkoniecz also asked for examples from paper maps. In the Netherlands, the most well-known maps are the topographic maps from the government and the Bosatlas (an atlas).

I couldn't find much online from the Bosatlas, but here's at least a sample: https://s.s-bol.com/imgbase0/BOOKCOVER/FC/9/0/0/1/9/9001968996_2.gif

**Comment by kocio-pl** [comment]
From my old [wiki page on low zoom](http://wiki.openstreetmap.org/wiki/User:Kocio/low_zoom_rework) there are still some related issues open:
* https://github.com/gravitystorm/openstreetmap-carto/issues/621
* https://github.com/gravitystorm/openstreetmap-carto/issues/1391
* https://github.com/gravitystorm/openstreetmap-carto/issues/1604

I am also interested if we plan to show some physical landcover there?

**Comment by matkoniecz** [comment]
And some maps that ended on my list of "good mid zoom": http://mc.bbbike.org/mc/?lon=8.116896&lat=50.460645&zoom=5&num=6&mt0=mapbox-transportation&mt1=google-map&mt2=google-panoramio-physical&mt3=esri&mt4=mapnik&mt5=osm-roads&marker= (Esri, Google Maps, OSM Roads, Mapbox Transport).

**Comment by kocio-pl** [comment]
> And some maps that ended on my list of "good mid zoom"

My 5 cents:

1. None of them is good at showing rivers - and we could try it.

2. "OSM FR hot" looks interesting to me - even from z5 (z4 is overcrowded with names). Where is the code for this style available? It has some issues with borders to fix, but with current roads from osm-carto (and rivers) middle zoom could be quite nice.

**Comment by math1985** [comment]
I still like maps.sputnik.ru a lot. Does anybody know who is behind this rendering, and if their stylesheet is public?

**Comment by kocio-pl** [comment]
I don't know, but [on this site](http://corp.sputnik.ru/maps) there is an e-mail address you can try using (maps@corp.sputnik.ru).

**Comment by SomeoneElseOSM** [comment]
I've not read through it in detail, but there's a shed-load of information on the Russian forum about it: http://forum.openstreetmap.org/viewtopic.php?id=25565

**Comment by math1985** [comment]
I experimented with further lowering landuse colors, in particular forest. This seems to result in a large improvement:

Old - 
![screenshot_2016-08-14_23-05-27](https://cloud.githubusercontent.com/assets/5251909/17652064/d37bb330-6273-11e6-9792-f80986044695.png)

New
![screenshot_2016-08-14_23-06-47](https://cloud.githubusercontent.com/assets/5251909/17652063/cc712b2e-6273-11e6-8d58-1583e4689b4b.png)

This is only a first proof of concept of increasing lightness and decreasing chroma, I didn't select a particular color yet. Our final choice might be less extreme. Also we'd need to look in how this change would related to the other greens.

**Comment by kocio-pl** [comment]
I've been also thinking lately about something like this and I ilke your example. 

We already use such technique (desaturation on lower zoom levels), but in a very limited case ([service tram lines](https://github.com/gravitystorm/openstreetmap-carto/pull/1676)). I believe you've touched farmlands here, which is a second to the forest (Luxembourg does not suffer it as much as many other places, but I can see strong golden spots even here). 

In general I think we have quite too much yellow from mid-zoom up, as a color or just a tint (that was one of the reasons [I gave up yellow tertiary](https://github.com/gravitystorm/openstreetmap-carto/pull/2228#issuecomment-236075503)), so maybe aside from desaturating we could make the map less yellow. The land and farmland colors on the altered version are still so strong, that roads (especially orange ones) are not as visible as they were designed to be. [Proposed water color change](https://github.com/gravitystorm/openstreetmap-carto/issues/1781#issuecomment-235131091) will also bring more balance in that respect.

**Comment by pnorman** [comment]
> This is only a first proof of concept of increasing lightness and decreasing chroma, I didn't select a particular color yet. Our final choice might be less extreme.

I like the general direction.

> Also we'd need to look in how this change would related to the other greens.

Too many shades of green :(

**Comment by nebulon42** [comment]
Looks good for midzooms, but we should not lighten things further up at higher zooms. We already got "map is too pale" feedback and we would push the feedback loop - aesthetics balance further towards aesthetics.

**Comment by kocio-pl** [comment]
Do you plan to make a PR or you want to discuss something before? I would be happy to test the code.

**Comment by math1985** [comment]
Do you mean me? I'd like to make a PR indeed, but I have loads of other things going on as well so it won't be soon. If you would like to work on this too, feel free!

**Comment by kocio-pl** [comment]
Yes, I meant you. =} I believe the code is ready (and used for showing new rendering)?

**Comment by math1985** [comment]
I pushed my branch to https://github.com/math1985/openstreetmap-carto/tree/landuse-colors. As I said it's just a proof of concept though, I just made some large shifts in colour and didn't spend a lot of effort on finding the optimal colours yet.

**Comment by kocio-pl** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/1387.

**Comment by math1985** [comment]
Our feeling seems to be that mid zoom levels need weaker colours than higher zoom levels. I wonder what the design concept behind that is. Features are smaller on low zoom levels than on high zoom levels, so that would suggest the opposite (smaller features should be stronger). Any comments on this? @imagico maybe?

**Comment by imagico** [comment]
I think the preference for weaker colors at lower zoom level comes from the idea of fading out their visibility.  At the lowest zoom levels we currently do not render landcovers - not only because it is technically not feasible but also because it would be a mixture of inproper color mixing and rendering artefacts with relatively little meaningful information.  There is a transit zone at the medium zoom levels where reading the landcover rendering becomes increasingly difficult as you zoom out but dropping some landcover types while keeping others is not really helpful either, dropping the grass color in an area with mixed grass/wood landcover for example increases noise instead of decreasing it.  And ultimately it is quite arbitrary.  Fading them out is a logical alternative.

The other reason to me seems to be that the roads loose their casing at some point which makes them significantly more difficult to read in front of a structured background.  This can be compensated by weaker background colors.

Right now i think there is no area color that changes between zoom levels.  Introducing something like that would be a big change in overall concept.  The question is also what colors to change and what not.  Should the water color stay the same?  This would change the overall color balance and we always need to keep in mind that a certain map scale occurs at different zoom levels at different places so cross zoom level comparability is quite significant for practical use of the map.

**Comment by math1985** [comment]
> Right now i think there is no area color that changes between zoom levels. Introducing something like that would be a big change in overall concept

Exactly, so I'd like to first study if it's possible to keep the colours on all levels the same. Which is why I'm interested in finding out why we think we need different colours on different zoom levels in the first place. I hope #2448 is one of the things that will make this easier. Stronger road colours on midzoom might be another thing we need. Thanks for your comment.

**Comment by math1985** [comment]
I feel a bit stuck with this proposal. Does anybody have any suggestions on how to proceed with this?

**Comment by imagico** [comment]
I think it would be useful to have an idea how the map looks like at around z7/8 with all the area colors that are currently shown at z10+ but without the rendering artefacts that would normally be dominating at these scales (as evidenced by the appearance of wood/forest at z8 right now).

This would tell us to what extent the readability issues observed and which could as discussed be addressed by fading colors at the lower zoom levels are really an issue with the chosen colors at these scales and to what extent they are cause by limitations of the renderer that are just emphasized by use of relatively strong colors (and therefore just would be slightly concealed by using weaker colors).

I am not quite sure if there is an easy way to actually do such a test - simply doing a significantly higher resolution render of the landcover and water layers only and scaling down might be a reasonable approximation although color mixing is possibly a problem.  But you'd need a database with all the required data of a reasonably large area for that.

**Comment by math1985** [comment]
I'm still not sure how to proceed.

Highzoom seems to require dark saturated landuse colours to have sufficient contrast with white roads. Lowzoom seems to need light colours for sufficient contrast with the coloured roads.

Just for fun some screenshots of the map without roads:

Before:
![screenshot from 2016-12-06 01-03-40](https://cloud.githubusercontent.com/assets/5251909/20907685/05ae2ae2-bb50-11e6-8e66-7672be6f2b99.png)

After:
![screenshot_2016-12-06_01-06-56](https://cloud.githubusercontent.com/assets/5251909/20907746/5f006326-bb50-11e6-8ab6-2875a8e5ac75.png)

After:
![screenshot_2016-12-06_01-11-38](https://cloud.githubusercontent.com/assets/5251909/20907827/fcfba0c2-bb50-11e6-97ce-9456e097bd02.png)

Before:
![screenshot_2016-12-06_01-08-25](https://cloud.githubusercontent.com/assets/5251909/20907786/b159826a-bb50-11e6-875b-789d0d04352d.png)

**Comment by math1985** [comment]
With forest and grass adapted to the Sputnik colors:

![screenshot_2016-12-06_21-42-28](https://cloud.githubusercontent.com/assets/5251909/20942770/2936d8c6-bbfd-11e6-97bf-ddf86f5f4783.png)
![screenshot_2016-12-06_21-43-10](https://cloud.githubusercontent.com/assets/5251909/20942769/293614c2-bbfd-11e6-8cb7-c7cc1d5d556e.png)

**Comment by kocio-pl** [comment]
What are the Sputnik colors you mentioned?

Changing forest background color with grass and making grass lighter might have sense not only for mid zoom (however I would not touch parks). Where is the code branch you have used here?

**Comment by imagico** [comment]
You know i don't have much appreciation of isolated ad hoc color changes without a solid concept behind them.  If you are just sharing the results of trying a few things out without actual intentions for concrete changes that is perfectly fine of course.

Since you are primarily showing z10 here - the most obvious improvement would be to drop outline rendering of landuse=quarry and tourism=camp_site and drop rendering tourism=zoo at this scale.

What is also worth considering is unifying the urban landcovers into a common color at this scale - like the same color as used for the natural earth builtup areas at z8/9.

**Comment by kocio-pl** [comment]
The biggest problem I see there are forests and farmlands being too strong and water color being too weak.

**Comment by math1985** [comment]
> What are the Sputnik colors you mentioned?

The colors from http://maps.sputnik.ru/ I linked earlier.

> You know i don't have much appreciation of isolated ad hoc color changes without a solid concept behind them.

True, but I don't really know what the concept should be, so hopefully some examples will give us a better idea what aspects are important. Do you have any suggestions (others than the ones you shared in the cartography documentation PR)?

> If you are just sharing the results of trying a few things out without actual intentions for concrete changes that is perfectly fine of course.

At some point this should result in a concrete change of course, but I have the feeling we're still rather far away from that.

> Since you are primarily showing z10 here - the most obvious improvement would be to drop outline rendering of landuse=quarry and tourism=camp_site and drop rendering tourism=zoo at this scale.

True, but I think it's easiest too first adapt the common colours like grass/forest/residential/farmland, and then adapt the other colours to that.

Anyway perhaps I could prepare a request for your suggestions already.

> What is also worth considering is unifying the urban landcovers into a common color at this scale - like the same color as used for the natural earth builtup areas at z8/9.

Yes, that sounds like a good idea as well. Although on z10, harbour areas look quite big already.

**Comment by math1985** [comment]
> The biggest problem I see there are forests and farmlands being too strong and water color being too weak.

**Comment by math1985** [comment]
> The biggest problem I see there are forests and farmlands being too strong and water color being too weak.

That's a comment about the current rendering, right?

**Comment by imagico** [comment]
> Do you have any suggestions (others than the ones you shared in the cartography documentation PR)?

At the moment i am not even sure what exactly the problem is you are trying to solve.  If it is about readability of roads that my first thought would be changing the way roads are rendered.  If it is about readability of the landcovers themselves i don't think fading the colors will actually improve readability.

The three color scheme for water  proposed in #1781 by the way significantly improves contrast between water and landcovers, especially for rivers.  I specifically had these scales in mind when drafting that.

> Yes, that sounds like a good idea as well. Although on z10, harbour areas look quite big already.

Such things are always a compromise between what you gain and what you loose.  In this case i don't think the loss of identifying harbour areas as industrial is too severe and the gain in clarity in normal urban context with usually fairly fine grained divisions is likely quite significant.  Your mock-up without roads shows this quite well in the south.

**Comment by kocio-pl** [comment]
> That's a comment about the current rendering, right?

Yes. Sputnik colors improve the forest, but if I see correctly don't change farmlands and I'm still not able to distinguish rivers from roads, so 2 of 3 problems remain. Although on this particular area farmlands don't look bad, so maybe forest and water change would be enough.

**Comment by kocio-pl** [comment]
> At the moment i am not even sure what exactly the problem is you are trying to solve. If it is about readability of roads that my first thought would be changing the way roads are rendered. If it is about readability of the landcovers themselves i don't think fading the colors will actually improve readability.

Both are readable and more harmonic on Sputnik colors variant for me. Landuses have more common saturation level and work as a good, non intrusive background for lines, dots and names. It does not make individual landuses to be better readable, but it makes it easier to recognize them as the same class (areas).

**Comment by kocio-pl** [comment]
My Sputnik-esque take:
- forest color taken from grass
- grass made 5% lighter
- water from https://github.com/gravitystorm/openstreetmap-carto/issues/1781

Warsaw, z10

Before
![ta8lfrcy](https://cloud.githubusercontent.com/assets/5439713/20949530/1e901a14-bc1a-11e6-9fde-a80fe1cc9533.png)
After
![mm8u8klq](https://cloud.githubusercontent.com/assets/5439713/20949542/274f7b36-bc1a-11e6-8360-46a970007914.png)

1. Now the biggest problem seem to be too dark borders of nature reserves.
2. Water is clearly visible as an area, but is still too light/thin as a line.

**Comment by kocio-pl** [comment]
I don't know if this is a problem with tagging or just a different place, but on z10 in Japan dark water dominates everything:
![mm1exkrj](https://cloud.githubusercontent.com/assets/5439713/21101847/6fcae3cc-c07b-11e6-8900-1b4fb0e12a98.png)

however new water color without darkening works quite nice:
![w0lnx6ly](https://cloud.githubusercontent.com/assets/5439713/21101963/0c547780-c07c-11e6-883f-e734ea1b37b2.png)

**Comment by kocio-pl** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/1755, https://github.com/gravitystorm/openstreetmap-carto/issues/1936 and https://github.com/gravitystorm/openstreetmap-carto/issues/1935.

**Comment by kocio-pl** [comment]
Ireland, z10 - testing my midzoom branch with big natural=heath areas:

dark water
![1o2tz4xa](https://cloud.githubusercontent.com/assets/5439713/21298361/83b5caf4-c590-11e6-8713-20b08eab48f9.png)

new water color
![ajbjr3uq](https://cloud.githubusercontent.com/assets/5439713/21298362/8e66b6f2-c590-11e6-81d7-2fb083acde83.png)

**Comment by math1985** [comment]
I'm still trying to work on this.

Before:
![screenshot_2017-04-22_14-32-10](https://cloud.githubusercontent.com/assets/5251909/25304488/901d1ec0-2768-11e7-985b-82890fe2f208.png)

Suggestion:
![screenshot_2017-04-22_14-32-27](https://cloud.githubusercontent.com/assets/5251909/25304489/9028146a-2768-11e7-8076-04b9927497f4.png)

**Comment by kocio-pl** [comment]
For me it's simply better. I like dark grey areas (residential, I guess) and I think water color is more visible too (more blue than grey, so it's also easier to recognize as water).

**Comment by imagico** [comment]
I am trying to stay open minded towards these ideas although i have trouble with the concept of rendering landcovers as polygons in distinct colors without the intention for these colors to be discernible  (which is obviously no more the case here for the various green tones or farmland and the bare ground landcovers).

But independent of that and of the question if the concept of fading colors at lower zooms levels is a good idea i am very much against having something like that is the style without a broader concept for the lower zoom levels beyond z10/11 which you focus on here.  I am in particular thinking about z5-z8 which are the starting zoom levels new visitors see most prominently when they look at the map.

In addition specifically i don't think the extreme difference between residential and industrial in your example works very well.  I assume you just tuned the residential color as an afterthought here.

**Comment by kocio-pl** [comment]
Tuning also low zoom levels sounds good to me, middle zoom is just where the problem is the most visible for me.

**Comment by math1985** [comment]
> The use of white without casing for the minor roads is an interesting idea. I don't remember having seen this in another map before - did you have a model for that or did you just come up with that yourself?

Google Maps also does it.

**Comment by math1985** [comment]
> I assume you just tuned the residential color as an afterthought here.

In fact, it was the other way around: I wanted to make residential areas more visible (I might do that to industrial etc. as well), and as a consequence I had to find another colour for the unimportant roads.

**Comment by math1985** [comment]
> I assume you just tuned the residential color as an afterthought here.

In fact, it was the other way around: I wanted to make residential areas more visible, because I think that's one of the most important pieces of information to display at this zoomlevel (I might do that to industrial etc. as well). As a consequence, I had to find another colour for the unimportant roads.

**Comment by imagico** [comment]
All right, but then you should definitely unify residential, industrial and other builtup areas into a common tone - otherwise you get a bad mapping incentive.

It would by the way also be interesting to see how white minor roads look with the normal colors.  I don't think the gray roads at these scale are a particular problem but we have overloaded gray for line features for a lot of different things and reducing that would not hurt.

Still the primary need IMO remains to develop a concept that can be extended to the lower zoom levels and is not just for these intermediate scales in isolation.

**Comment by math1985** [comment]
> All right, but then you should definitely unify residential, industrial and other builtup areas into a common tone - otherwise you get a bad mapping incentive.

I agree, just didn't get to that yet.

> Still the primary need IMO remains to develop a concept that can be extended to the lower zoom levels and is not just for these intermediate scales in isolation.

The primary scope of this work is z8-z11. Zoom levels lower than z8 currently don't show landuse (and I'm not sure if we want to, performance-wise), so it doesn't make much sense to include them. Of course, I'll make sure that the changes on z8-z11 work well with other zoomlevels too.

**Comment by imagico** [comment]
> The primary scope of this work is z8-z11. Zoom levels lower than z8 currently don't show landuse (and I'm not sure if we want to, performance-wise), so it doesn't make much sense to include them.

Right now we do not vary area coloring between zoom levels at all.  If we decide to change that i think whatever approach we take should be evaluated for suitability also for the lower zoom levels - otherwise if and when we decide to also address the lower zoom levels we would end up with a new problem and yet another specific styling variation and ultimately essentially three completely different styles we would have to maintain in the long term.

And i don't think z8 is a particularly significant threshold.  The only thing that starts at z8 area wise is forests.  Overall we have the following starting zoom levels for areas at the moment:

z6: water areas and glaciers, water areas are already considered to be extended to lower zoom levels in #2507.

z7: nature reserves

z8: wood/forest

z9: bare_rock, scree and sand

z10: almost everything else

And from my perspective the problem about extending area rendering to lower zoom levels is not so much performance but the fact that the results would not really transport much information any more because they would consist almost exclusively of rendering artefacts (you can already see this quite well at z8).

**Comment by kocio-pl** [comment]
Resolved by https://github.com/gravitystorm/openstreetmap-carto/pull/2654.
