### ISSUE TITLE
osm default rendering of hiking trails names

### ISSUE THREAD

**Issue by billdonohue** [gravitystorm/openstreetmap-carto#2242]
Hi

I have been struggling with best practices for name tagging ways. As an example please view the 1779 Trail on which I have worked which is shared in part by the 1777W Trail, the Timp Torne Trail links included below.

What I have done here is

created a relation for each of the individual trails adding the name of the trail to the relation name.
leave the name tag on the way blank.

However a problem arises: On waymarked trails this portion of the trail is rendered as follows: http://hiking.waymarkedtrails.org/#route?id=6292324&map=18!41.3237!-73.9884 showing symbols for the 3 trails that the way.

On openstreetmap.org it is rendered as follows: https://www.openstreetmap.org/#map=19/41.32387/-73.98884 showing neither the symbols or the 3 associated trailnames.

I am wondering if it would make sense to have the default openstreetmap.org page render the name tag of each associated relation on hiking trails and if there are no relations then render the name tag of the way itself? This would be very helpful for people like myself who start on OSM knowing nothing with no-one there to guide us. If we saw the relation name tags rendered on the default osm page and then in editing that path we saw that the way has no name, we would understand better the best convention. In addition it would help overcome the urge to add a name to a way because we don't see it in the default osm window even though the proper names are there in the relations.

Bill

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 26 lug 2016, alle ore 00:45, billdonohue <notifications@github.com> ha scritto:
> 
> I am wondering if it would make sense to have the default openstreetmap.org page render the name tag of each associated relation on hiking trails and if there are no relations then render the name tag of the way itself?


From your description I agree with your tagging (presuming that the individual ways don't have names, just the routes). 

The suggested behavior seems more suitable for a hiking map, in a general map I'd expect to give priority to the individual way names (those that are typically signposted as street names on the ground), and eventually render route names afterwards, if there is still space, but it might be confusing unless we also render the routes themselves

**Comment by SomeoneElseOSM** [comment]
Whether hiking route relations are appropriate to be rendered on OSM's "standard" map I'm not sure (other rendering decisions in the last couple of years have reduced the visibility of some of the features that they run over) but if you're interested in doing it yourself based on a version of this style then it might be useful to have a look at http://www.openstreetmap.org/user/SomeoneElse/diary/38988 which explains how I did it using a map style based on an older version of this style.

It'd be best done by processing the relations in lua I think, so to happen here would need to wait for lua processing to be available.

**Comment by billdonohue** [comment]
Perhaps a good solution would be to add a "Relations" layer to the Map Layers page of www.openstreetmap.org  that currently shows Standard, Cycle Map, Transport Map & Humanitarian OR alternatively to Modify the "Map Data" checkbox on the Map Layers Page so that when checked it shows all relations of displayed items.

**Comment by HolgerJeromin** [comment]
waymarkedtrails.org has six views of the osm data. Who wants to decide which relation names to render? 
Why should hiking relation names be shown and not cycling or mtb? 
Even http://hiking.waymarkedtrails.org/#?map=15!52.0209!8.5065 only works with the colors and icons which is no option in this style.

**Comment by matkoniecz** [comment]
I am pretty sure that there is no enough space to display al trails at once in addition to other data. Even waymarkedtrails.org is not doing this.

**Comment by Adamant36** [comment]
is there a reason it wouldn't be a simple matter of displaying the relation name next to the trail name as is done with the display of ref #'s or other things like the numbers on highways?

**Comment by SomeoneElseOSM** [comment]
@Adamant36 For info I added trail names to the map at https://map.atownsend.org.uk/maps/map/map.html#zoom=14&lat=53.04983&lon=-1.83266 (that snippet has a couple of walking routes, a regional cycling houte and a long-distance horse route).  The things that I had to deal with included:
- tuning other things out of the colour space used by the new colours so that I could use red through purple for these.
- deciding what gets displayed at what zoom level for what feature (route, name or both)
- choosing the dot density for the route itself so that it's still clear but doesn't overwhelm everything else.  This is per zoom level of course.

It's doable, but setting it all up was far from a "simple matter"!

One more thing - if you switch that map link to the OSM layer you'll see a huge difference in approach between the two layers - the OSM map shows much less detail at that zoom level, and it would totally overwhelm things to include hiking trails there (the actual paths that the trails run over are barely visible)

What might be an interesting option (as suggested by @billdonohue) would be putting this new stuff into an overlay.  There are downsides (you can't easily avoid label collisions between an overlay and the underlying tiles) but it would be an interesting things for someone to try if they wanted to..

**Comment by matkoniecz** [comment]
reopening as my closure was based on misunderstanding

**Comment by jeisenbe** [comment]
I agree with closing this: if we only render the route relation names in places where there is no name tag on the way, this could lead to mappers removing the names from the ways to get the routes rendered, and that would be a bad mapping incentive. But we can't render the names from the route relations and from the ways at the same time. 

Even if osm2pgsql is updated to handle adding information from relations onto ways, it would be confusing unless we render the relations with some sort of linear representation.

**Comment by SomeoneElseOSM** [comment]
> this could lead to mappers removing the names from the ways to get the routes rendered, and that would be a bad mapping incentive.

(not commenting on whether this style thinks its appropriate to render route relation names or not but...) 

The mapping incentive is rather the other way around at the moment - some mappers like to add route names to ways "to get them rendered".  Where I live at least this is usually wrong; there are very few places where a street name is actually part of a long distance path of exactly the same name.

> But we can't render the names from the route relations and from the ways at the same time.

While it is technically possible to do this (I've done it in a map style based on the same technology), but doing it in a way so as not to confuse users would be difficult.  As people above have already said, I don't think that it would be a good idea to "render the name [in the same colour, font and everything else] from either the relation or the way but not both"

**Comment by jeisenbe** [comment]
The issue at https://github.com/openstreetmap/osm2pgsql/issues/230 is now fixed, so it would be technically possible to use the `name=` from the way and the `name=` from route relations at the same time. However, I still think it would be impossible to show this information in a way that would make sense on a general map style, since the same multi-use path might be part of several cycling route relations and several hiking or walking relations. 

Therefore I still recommend closing this issue, and suggesting that mappers and map users who are interested in seeing these relations should use a more specialized render like  http://waymarkedtrails.org/

**Comment by mboeringa** [comment]
> Therefore I still recommend closing this issue, and suggesting that mappers and map users who are interested in seeing these relations should use a more specialized render like http://waymarkedtrails.org/

Agree, it is actually a major feat what they did for Waymarked Trails, showing all of these routes as a vector overlay with symbols and such based on the OpenStreetMap relation information.

**Comment by jeisenbe** [comment]
Closed, with "thumbs up" support for my last comment https://github.com/gravitystorm/openstreetmap-carto/issues/2242#issuecomment-583793996 from 2 other contributors, in addition to the last positive comment, in favor of closing.

**Comment by SomeoneElseOSM** [comment]
>  However, I still think it would be impossible to show this information in a way that would make sense on a general map style, since the same multi-use path might be part of several cycling route relations and several hiking or walking relations.

I'd disagree pretty strongly with that - although, as I said higher up, it might not make sense to display hiking features since OSM Carto is not a hiking-friendly style, as it doesn't show "paths that you would want to walk on" at a useful scale.  

I'm also not convinced that https://github.com/openstreetmap/osm2pgsql/issues/230 was really the blocker here - it was more to do with not wishing to embrace what you can do with lua.  There may be other good reasons for that of course though, such as having "one big customer" with no ability to schedule a database reload and no desire to add features that would depend on it.

**Comment by jeisenbe** [comment]
If there is a way that this could be implemented in this style, we can reopen the issue. Do you have an idea of how it might work, @SomeoneElseOSM?

**Comment by SomeoneElseOSM** [comment]
The way that I've done it is to use lua to convert route relations to a new highway value, which is then rendered.  The result is something like https://map.atownsend.org.uk/maps/map/map.html#zoom=16&lat=53.8819&lon=-0.68143 - there you can see that someone's added the name "Wolds Way" to https://www.openstreetmap.org/way/48464157 etc. (probably in error) but it is also a member of 2 route relations.  https://www.openstreetmap.org/user/SomeoneElse/diary/38988 from 2016 explains how it's done (although the links to line numbers won't be valid any more).

**Comment by jeisenbe** [comment]
> The result is something like https://map.atownsend.org.uk/maps/map/map.html#zoom=16&lat=53.8819&lon=-0.68143

> https://www.openstreetmap.org/user/SomeoneElse/diary/38988 : "The “fill” is a short wide purple dot separated by a long gap from the next one. In the code (see the links above) at “line-dasharray” the “1” says “short and the “60” says “separated by a long gap” and further down the “line-width: 4” says “wide”."

> "... Long distance paths have to be different to distinguish them from road names, and so the text fill is purple, the text-dy larger to place it further from the road and text-spacing is further apart at higher zoom levels." 

Based on comments by @pnorman and @imagico about removing access rendering so that surface can be shown, I don't think this kind of rendering would be accepted for this style, since it would be trying to show too many different things on one feature.

**Comment by SomeoneElseOSM** [comment]
> I don't think this kind of rendering would be accepted for this style

I suspect that that's true...

> since it would be trying to show too many different things on one feature.

Taking a step back, there are three questions really - (1) is there a spare colour, (2) is there a spare "way of rendering", and (3) could it fit in with the rest of the style?

With (1) the shades of purple that I've used are not an option as that's used for boundaries, but if you look at https://www.openstreetmap.org/#map=15/53.8805/-0.6823 you can see quite a few different colours are used for names, and it would be possible to reuse one of those.  With regards to (2) I don't think that there is anything similar in OSM Carto to the "sequential dots" (in a different colour to purple) is there?  (3) is subjective of course.

**Comment by imagico** [comment]
In principle i would not mind someone exploring the options here but doing so without first reconsidering our physical footway/cycleway rendering in particular on the mid zoom levels would not be a very useful approach i think.

**Comment by Mashin6** [comment]
I see that I am here too late, but still I would like to strongly support this suggestion. There are now too many people around me that add name or color of the trail as a name to the footway and it is impossible to reason with them, because they want to see it on the default map. I was already accused of being "for-profit enterprise that wants to sabotage osm" and "deny people access to vital information".

Regarding (1) I would suggest blue color, but darker than waterways. (2) It could be as simple as showing `name=` or if absent then `symbol=`or `color=` values below the path line. Currently it seems the footway/path names are rendered above and roads have names on the line so there would be no clash. (3) I can't tell.

**Comment by jake-low** [comment]
I'd also like to voice my support for rendering route names when possible. I understand that Carto is not a hiking-specific renderer, but it is the renderer used on osm.org and the one that most editors first see. The absence of rendered route names can cause new mappers to think that data is missing and add it (incorrectly) to the individual ways instead.

I'd be completely satisfied with a special-case solution that showed the name tag from a route relation along a way which is part of that route only if (1) the way has no name of its own and (2) it isn't part of any other routes. That would cover the large majority of hiking trails in the areas I'm familiar with, and thus would avoid a lot of problems with new mappers incorrectly adding route names to individual ways.
