### ISSUE TITLE
Incorrect department store MSS spacing

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2262]
```mss
  [feature = 'shop_department_store'][zoom >= 16] {
      marker-file: url('symbols/department_store.p.16.svg');
      marker-placement: interior;
      marker-clip: false;
      marker-fill: @shop-icon;
  }
```

1616fa10ee059c960912a47d33e44b07e1653611 introduced a 4sp indent

**Comment by kocio-pl** [comment]
I see also some other small issues in this file, like https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss#L412 and some others - do we want to join and embed zoom level (to be consistent with our coding style) or it's better to leave it separately (because it makes it easier to change)?

**Comment by kocio-pl** [comment]
What do you think on other existing syntax style problems? It could be labeled as [easy](https://github.com/gravitystorm/openstreetmap-carto/labels/easy) if we think it's worth correcting at all.
