### ISSUE TITLE
What’s the difference between addr:housename=* and building= + name=* ?

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2298]
What’s the difference between addr:housename=* and building= + name=* ?

addressing.mss has different rendering of these. I want to go ahead with minimal font sizes, but I do not understand the reason for the rendering difference. Could I use the same rendering for both?

**Comment by polarbearing** [comment]
```addr:housename``` is part of the address scheme, and often occurs in areas where houses are not numbered. These house names are known to the postman, or even officially registered in the post office. 

A ```name``` on a building would be the name it is commonly known by, but which is not part of the postal address. This also occurs when a feature such as a shop is tagged on the building outline, so ```name``` would be the shop being identical with the building.

For rendering, my guess is that  ```addr:housename``` should be rendered equivalent to ```addr:housenumber```.

**Comment by geostonemarten** [comment]
Hi,

In this case it can result a problem if addr scheme containt one time housename and housenumber

Repeat building name in addresses is not necessary if name is same. in fact, residential complex can add same building name with multiple entrance name or ref...

There is conflict beetwen number and name if twice exists on same building.

I think if name is not set and only addr:housename is set, you can render this information as same as building=* + name=* because this is just a contribution choice. Don't repeat the same information...

If building=* + name=* exist with addr:housename=*, you can choice rendering name=* only

Rendered doesn't reflect the choice of tags in this case. Please set the same rendering if addr:housename is set in place of name if it coexist with building=* object

Thanks

**Comment by daganzdaanda** [comment]
> In this case it can result a problem if addr scheme containt one time housename and housenumber

That's almost certainly a tagging error, so you shouldn't worry too much about the rendering. Of course it's a common error, lots of addr:housenames are used wrongly instead of name on the building or some other object. 
addr:housename should exist only when there is no addr:housenumber. It is an alternative way of addressing a house for postal uses:

https://en.wikipedia.org/wiki/Address_(geography)#House_numbering_or_naming
> it is also common for houses in the United Kingdom and Ireland to be identified by name, rather than number, especially in small towns. In these cases, the street name will usually follow the house name. Such an address might read: "Smith Cottage, Frog Lane, Barchester, Barsetshire, BA9 9BA" or "Dunroamin, Emo, Co. Laois, Ireland" (fictional examples).


> For rendering, my guess is that  addr:housename  should be rendered equivalent to  addr:housenumber .

Yes, and I think [that's what we do](https://github.com/gravitystorm/openstreetmap-carto/blob/0c70682a69c91b833399c1dd74409eee79ce4af1/addressing.mss#L21), more or less.
See http://www.openstreetmap.org/node/3576826278 for a building with addr:housename with a nearby housenumber node to compare.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 24 ago 2016, alle ore 19:47, daganzdaanda <notifications@github.com> ha scritto:
> 
> addr:housename should exist only when there is no addr:housenumber


or if the name can be used as an alternative address.

**Comment by geostonemarten** [comment]
@dieterdreist 

> addr:housename should exist only when there is no addr:housenumber

 It's totally false in France. twice coexiste. You can have entrance, unit, housename, and housenumber in same address

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 25 ago 2016, alle ore 11:06, geostonemarten <notifications@github.com> ha scritto:
> 
> addr:housename should exist only when there is no addr:housenumber
> 
> It's totally false in France.
> 


you are misattributing this to me, I had written as well that it's not true

**Comment by geostonemarten** [comment]
> you are misattributing this to me

@dieterdreist That it is true and i edited my comment.  ;-)

**Comment by daganzdaanda** [comment]
> [In France] You can have entrance, unit, housename, and housenumber in same address

OK, I did not know that. I only knew of UK / IRL to really use a house name as a part of an official postal address. Here in Germany there are a lot of old farmhouses that have a name (called "Hofname"), but these are not used any more for the mail. I try to tag those as loc_name when they are displayed on the building.

To bring discussion back to OSM carto style... I think what we have is OK: we render addr:housename as small as addr:housenumber, and I guess that was a choice made on purpose to show that addr:housename does not mean the same as just a name=* on the building.

**Comment by dieterdreist** [comment]
2016-08-27 15:11 GMT+02:00 daganzdaanda <notifications@github.com>:

> Here in Germany there are a lot of old farmhouses that have a name (called
> "Hofname"), but these are not used any more for the mail.



while there might have been introduced new addresses, you can typically
still use the old addr:housename and your letter will likely arrive.

Cheers,
Martin

**Comment by sommerluk** [comment]
Thanks for commenting. I’ll try to just change the font size without touching the colours.
