### ISSUE TITLE
Rendering both, addr:housename and addr:housenumber?

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2328]
In #2298 there was also a discussion about cases where addr:housename and addr:housenumber coexiste. Currently, if both exist, we render only one of them.

There are about 278 000 objects with addr:housename in the database. About 56% of them have also addr:housenumber, this is a considerable part.

It might be possible to render in such cases both of them, with a line break as separator, like this:
```
addr:housenumber\n
addr:housename
```
Would this be desirable?

**Comment by neiljp** [comment]
If there is space (high zoom, or automatically determined), personally I would prefer parentheses or some other separator.
There was some talk elsewhere I remember regarding how to treat eg. petrol/gas stations, eg. with name (owner) vs operator vs brand, where something similar could also be done?

**Comment by nebulon42** [comment]
To me this would be desirable. I have done that in a fork I made for myself to try things out: https://github.com/gmgeo/osm-carto-gmgeo/blob/master/addressing.mss

**Comment by sommerluk** [comment]
Related to #735.

**Comment by aceman444** [comment]
If addr:housename is on the whole building, there will probably be a 'name' of the same value. So addr:housename rendering would be duplication. If addr:housename is on a node inside that building, then again, the building would have a "name" of the same value so that one would be rendered and no need to duplicate it on every addr node (e.g. shops) in the building.

addr:housename referencing a value that is NOT a 'name' on some building (the one around the node) would look like a tagging/logic error.

Am I missing something?

**Comment by polarbearing** [comment]
> If addr:housename is on the whole building, there will probably be a 'name' of the same value.

No. addr:housename is part of the postal address and often used only for this purpose. So the name=* tag might be absent. It could also have a different value, e.g. a shop name="Mary's Lollipops" residing in addr:housename=Hazelbrook.

**Comment by aceman444** [comment]
Yes, so if the shop Mary's has the address "Hazelbrook, No. street X, Town Y", why would the house itself NOT be named Hazelbrook? I'd expect it to. Why would a shop tell via the address that it is in the "Hazelbrook house", if the building wasn't named as such? So I'd expect the building to have name="Hazelbrook". Yes, in this case you would not be able to put all the shop tags on the whole building.
