### ISSUE TITLE
Oneway arrows missing from roads without name

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#2340]
Looks like a recent change have made oneway arrows disappear from many roads.
From what I can tell they do not appear unless the road have a name.
Many roads do not have name and are oneway. First that comes to mind are on and off ramps.
Limited access roads like motorways and motorroads may not have names as there are normally no direct property access from them. 

It basically removed the arrows from all motorways and motorroads in Norway :)

**Comment by HolgerJeromin** [comment]
Do you have an example?
https://www.openstreetmap.org/way/397173363 is rendering arrows. But i am not 100% sure the tile is fresh.

**Comment by rickmastfan67** [comment]
Same thing is happening here in the USA.  Even motorways that have a 'ref' tag have lost their 'oneway' arrows.  Those are necessary to spot when a section might have been accidentally been reversed.  Looks like this is a regression from #2320,

**Comment by rickmastfan67** [comment]
@HolgerJeromin I just made a change here: https://www.openstreetmap.org/#map=16/40.9782/-80.3001 Before I made the change, the arrows were rendering on the US-422 'motorway'.  Now, after the render refresh, they are no longer rendering on either the 'motorway' or 'motorway_link'.

https://c.tile.openstreetmap.org/16/18149/24576.png
https://c.tile.openstreetmap.org/16/18149/24576.png/status (proves it's a fresh render)

**Comment by Gazer75** [comment]
> Do you have an example?
https://www.openstreetmap.org/way/397173363 is rendering arrows. But i am not 100% sure the tile is fresh.
Refresh and you'll see its gone. Ctrl+F5 for Firefox, not sure if its the same for all browsers. It will bypass any browser cache data you might have.

**Comment by StyXman** [comment]
I just checked with the branch I used for developing this change and current master and I can confirm the bug exists. I'll try to figure out why, and come up with a solution, during the rest of the day.

**Comment by StyXman** [comment]
It's because I changed the `direction` class from `tunnels`, `roads-casing`, `bridges` and `roads-fill` to `roads-text-name`. I wonder it was there in the first three, given that the latter goes (always?) on top of them.

**Comment by lkernan** [comment]
Just for completeness, junction=roundabout are also missing arrows now as most don't include names (at least here).

**Comment by StyXman** [comment]
Found the fix, PR on the way.

**Comment by gravitystorm** [comment]
> I wonder why it was there in the first three, given that the latter goes (always?) on top of them.

I believe this is so that arrows are hidden by higher roads (usually bridges) that are crossing the road in question. Think of a bridge over a motorway, or as complex motorway junction. We don't want the arrow for the lower road showing on the upper road.

**Comment by StyXman** [comment]
Then the patch doesn't take that in account. I'll check the complex sectors I know and I'll report back.

**Comment by StyXman** [comment]
![one_way_too_many_arrows-broken](https://cloud.githubusercontent.com/assets/167327/18475576/3b69b2ac-79c7-11e6-8ceb-7e68c37aaf9b.png)

Yeap, that happens. See the highlighted arrows (sorry for the crude red things :) I guess we'll have to revert #2320 .

**Comment by StyXman** [comment]
In fact, now that you mention it, the whole `roads-text-name` layer suffers the same problem, so names also suffer from "through-layerness" (it's late, and my brain can produce proper English anymore...):

![one_way_too_many_arrows-broken_2](https://cloud.githubusercontent.com/assets/167327/18493292/0b645c1c-7a10-11e6-8784-827729535695.png)

![one_way_too_many_arrows-broken_3](https://cloud.githubusercontent.com/assets/167327/18493295/11eeb596-7a10-11e6-98ff-fed94eef8d7a.png)

**Comment by StyXman** [comment]
I sat down to see if `roads-fill` and `roads-*-text-(name|ref)` were mergeable, in an attempt to fix arrows and names, but I think it's impossible. There are a couple dozen layer in between, some of them not *clearly*[1] for a reason (for instance, `power-poles/towers/(minor)line`, `tourism-boundaries`, `admin`), but most of them yes (amenities, trees, stations, etc), so that's not possible.

I also went back little in the history and the labeling problem was still there, so I think we have two solutions: we either revert #2320, and we go back to `v2.42.0` state were road names had lower precedence than arrows; or we apply #2342 and live with the fact that labels and arrows from lower roads can show through upper roads. I don't think you can solve the 'render roads, then amenities and other stuff, then label the roads, but not those hidden by upper roads' with the painter algorithm or SQL magic.

--
[1] what I mean is that, given that I don have the whole layer history in my head, I can't figure out by myself with the code, and I don't know were to find relevant doc. I could open an issue about this.
