### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by giggls** [gravitystorm/openstreetmap-carto#2376]
Hello,

I now see v2.44.0 and v2.43.0 as newest tags, but still v2.42.0 as the latest release.

Are these supposed to be relases?

**Comment by gravitystorm** [comment]
2.41.0 and 2.42.0 were incorrectly processed. We just use tags, not github releases, but those two have github releases that need to be removed.

**Comment by giggls** [comment]
OK, polling for tags then

**Comment by math1985** [comment]
@gravitystorm Could you remind me what exactly the problem was with the Github release system?

**Comment by gravitystorm** [comment]
@math1985 there's nothing particularly wrong with it, it's unnecessary for our release process since we aren't distributing any compiled artefacts. We only use tags for releases, so we don't need particular tags treated differently. If we ignore the github releases then it removes a step from creating a new version (i.e. you can just push tags using git and that's all that needs doing).

The two choices are either:

* Use github releases for every release (extra work, no benefits, in my opinion)
* Don't have any github releases at all

The other option, to have a mixture like now, is the worst, since all the tags newer than a github release are hidden.

**Comment by pnorman** [comment]
Deleted the github "releases"

**Comment by pnorman** [comment]
Forgot to close this.

It might be interesting to provide compiled artifacts to avoid the need to compile with carto, but that's not an immediate plan.
