### ISSUE TITLE
Too much places in zoom 9, 10 . Rendering in order of population?

### ISSUE THREAD

**Issue by yopaseopor** [gravitystorm/openstreetmap-carto#2393]
As you see in this http://www.openstreetmap.org/#map=9/42.5055/1.7715 and in this http://www.openstreetmap.org/#map=10/41.3948/-3.6282 there are too much places in this new rendering way. Also you cannot difference a little town from medium Spanish cities. In some places big cities like Sitges (Barcelona) (pop. 28.171 ) are not shown but others like Olivella (pop. 3.609)  or Canyelles (pop. 4.345) are shown at these levels.
Is there anyway to work in order of population with the tags population and the order of importance with the tag admin_level at these two zoom levels?

**Comment by mboeringa** [comment]
At least some of them could do with re-tagging from villages to hamlets. E.g., this "village":

http://www.openstreetmap.org/node/1460477956#map=18/41.51607/1.43580&layers=D

only has a population of 97 inhabitants according to the tagging. According to the Wiki page:

http://wiki.openstreetmap.org/wiki/Key:place

this would put it more likely in the "hamlet" category _("smaller rural community typically with fewer than 100-200 inhabitants, few infrastructure"_) than village.

**Comment by jojo4u** [comment]
I checked the area between Andorra and Barcelona with Overpass Turbo http://overpass-turbo.eu/s/iUC (only nodes, since they are rendered; values depend on screen resolution)
1260 villages
973 villages with population
I exported the 973 nodes to JOSM and searched for "population<200" and got 448 matches, 303 for "population<100".

So around 300-400 of 1260 villages shown are should probably tagged as hamlet with the current data. 300 other ones of the 1260 don't have population tag to check.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 02 ott 2016, alle ore 20:04, jojo4u <notifications@github.com> ha scritto:
> 
> I exported the 973 nodes to JOSM and searched for "population<200" and got 448 matches, 303 for "population<100".


IMHO rather than looking at the pure population numbers we should look at the functional level. Is there any of church, bakery, shop, school, kindergarten, hairdresser, community center, town hall, etc? If there's 2 or more they could remain village, otherwise (very probable with a low population count) hamlet is indeed more appropriate. But it's nothing you can do without local knowledge, also because you don't know whether the place value or the population value is wrong

**Comment by sommerluk** [comment]
place=village should render starting from z12. I do not understand why it renders at z9 at all.

Typical example is a village node that is part of a relation:

- node: http://www.openstreetmap.org/node/1446994133 (is part of a relation)
- relation: http://www.openstreetmap.org/relation/347836

Does anyone know why this renders?

**Comment by sommerluk** [comment]
cc @nebulon42

**Comment by nebulon42** [comment]
I think this is because I have made a mistake in the WHERE clause in https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml#L1607.

It should read `AND (capital IS NULL OR capital != 'yes' OR (capital = 'yes' AND admin_level != '2'))` instead. Notice the additional parenthesis. Otherwise the two OR clauses override the `place IN ('city', 'town')` and villages with `capital=*` get promoted to placenames-medium.

@sommerluk Can you confirm?

**Comment by sommerluk** [comment]
I haven’t tested it, but it looks reasonable for me.
