### ISSUE TITLE
Mapnik 3 requirement

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2401]
With the Noto font changes (https://github.com/gravitystorm/openstreetmap-carto/issues/2397#issuecomment-251598708) we have ended up requiring Mapnik 3 features without realizing it at the time.

I propose updating the docs to reflect our need for Mapnik 3, tagging 3.0.0 from this, and tagging 2.44.1 with the Noto changes reverted.

We should also hold off doing any merges to make the git stuff simpler.

**Comment by nebulon42** [comment]
I'm much in favour of moving forward in this regard. This would also enable us to re-introduce the spacing parameters for placement labels, which where removed in #2374 due to problems with Mapnik 2.

I also suggest to revisit the requirement of supporting old Carto versions. Having to care about 2 year old Carto versions just hinders innovation. And it should be quite easy for anyone to upgrade Carto anyway.

**Comment by math1985** [comment]
> I'm much in favour of moving forward in this regard

+1

I wouldn't like to spend time or effort on supporting software older than the one running on openstreetmap.org. If people are running older software, they can just choose not to upgrade their openstreetmap-carto version. It's not like we're releasing critical security updates.

**Comment by kocio-pl** [comment]
I'm confused: it was fixed in [Mapnik 2.3.x](https://github.com/mapnik/mapnik/issues/2274#issuecomment-51865784), so AFAIK we don't _need_ to jump to Mapnik 3.x now. 

But I also don't like lagging too much, because OSM.org page should be our primary concern, not the other people that may be using this style. It's just a matter of our upgrading policy, and it leads us back to the [real issue](https://github.com/gravitystorm/openstreetmap-carto/issues/2198).

**Comment by pnorman** [comment]
There is no Mapnik 2.3.x version released, its just a label which was applied to development versions.

**Comment by gravitystorm** [comment]
On the other hand, released software (like the latest release of Tilemill) used 2.3.0 versions of mapnik. https://launchpad.net/~developmentseed/+archive/ubuntu/mapbox/+packages

**Comment by pnorman** [comment]
> On the other hand, released software (like the latest release of Tilemill) used 2.3.0 versions of mapnik. https://launchpad.net/~developmentseed/+archive/ubuntu/mapbox/+packages

Ya - but 2.3.0 doesn't refer to anything specific, it's anything after the latest tagged 2.2.x version and the first 3.0.0 RC. Based on the dates the tilemill PPA doesn't have the changes mentioned in https://github.com/mapnik/mapnik/issues/2274#issuecomment-51865784.

Because this change doesn't break development on 2.2, I don't see the need to do the git tagging mentioned anymore, and we state

> Mapnik 3 is required for acceptable rendering of most non-Latin scripts, particularly those with complicated diacritics and tone marks.

I still see the need for a v2.44.1 with the regression fixes #2404 (unmerged) and #2403

**Comment by nebulon42** [comment]
We still have suboptimal distance between placename labels that could be improved by requiring Mapnik 3.
