### ISSUE TITLE
Overlap between landuse=landfill and natural

### ISSUE THREAD

**Issue by Autharite** [gravitystorm/openstreetmap-carto#2410]
Hello. When there is an overlap of landuse=landfill and natural=scrub or natural=scree, the brown colour of the landfill rendering disappears. However, when there is an overlap of landuse=landfill and natural=wood, the result is the brown colour of the landfill scattered with tree icons. I think this is not consistent (either the brown colour should always disappear or it should never disappear).
Note: when there is an ovelap of landuse=landfill and landuse=forest (which should not happen imho), the brown colour of the landfill rendering disappears too, and we get the green colour of the wood scattered with tree icons.

**Comment by imagico** [comment]
Correct, for scrub this is being addressed in #2395.

For scree and bare_rock the situation is a bit different since these are not individual symbol patterns so rendering them above a different background color would appear as a completely different land cover and not a combination of scree/bare_rock and something different.  Therefore separating base color and the pattern is not really desirable here.

Note in any case which base color is rendered depends on the ordering of the layer which is by size.  So natural=scree (or any other natural or landuse area fills) will be rendered above landuse=landfill only if the polygon is smaller.

**Comment by imagico** [comment]
Closing this - for scrub this is addressed in #2395 and as explained it is not desirable to do the same for the bare ground landcovers.
