### ISSUE TITLE
render shop before amenity

### ISSUE THREAD

**Issue by ligfietser** [gravitystorm/openstreetmap-carto#2416]
shop=supermarket with amenity=atm is being rendered as teller machine.
I removed the amenity tag here but it should be better if the shop/supermarket is being rendered and not it's facilities like a teller machine: https://www.openstreetmap.org/node/1973701375/history

**Comment by kocio-pl** [comment]
Now it makes sense, because supermarket is probably much not the same object as ATM and that was just tagging error.

**Comment by jojo4u** [comment]
I guess this could be closed since fine-tuning of rendering when amenity=* and supermarket=* is used on the same object should be not necessary. This is the job for QA-tools.

**Comment by HolgerJeromin** [comment]
This would be a major problem with amenity=fuel plus shop=kiosk 
19 442 objects = 6.27% of fuels

**Comment by Circeus** [comment]
> This would be a major problem with amenity=fuel plus shop=kiosk 

Shop=kiosk is not exactly a very good tag in any case. It's literally a minuscule shop=convenience (the difference in goods sold is _not_ predicated on the nature of the shop, but **on its size**) with a built-in building=kiosk tag. Besides, if the fuel isn't _in the shop itself_, it shouldn't be double-tagged in the first place: [example](http://www.openstreetmap.org/node/300998335), [another](http://www.openstreetmap.org/node/304343462)

**Comment by HolgerJeromin** [comment]
You are right. I mixed both value. Thanks for pointing it out.

**Comment by Robou** [comment]
I don't really understand because I just tagged a node with `amenity=fuel; compressed_air` and `shop=convenience`. 
I just saw that it rendered the shop.
So I separated them : I created a node for the `shop` itself. But now nothing is rendered because I also precised "`compressed_air`" as amenity. Should I write a separate issue or am I doing it wrong ? I think I am correct and tagged it according to the wiki.
The node I am talking about is [located here](http://www.openstreetmap.org/node/4492927574).
Thanks !

**Comment by HolgerJeromin** [comment]
@Robou tagging one object with multiple values seperated with ; is not supported (or wanted) with this style, thats why the whole amenity tag is ignored.

**Comment by Robou** [comment]
@HolgerJeromin thank you for your answer and the correction of my tagging on osm! I did not see that we could use `compressed_air` as a `key` because I only read the french wiki page and it's not clearly indicated. I will enhance the french wiki page so.
And concerning the `shop=*` + `amenity=fuel` on the same node : as @Circeus said, I agree that they best fit into 2 separated nodes. But I think this situation describes the great majority of the cases : the fuel is **never** _in the shop itself_.  So what to do with all the fuel stations tagged with a shop and are thus not rendered as fuel stations ?

**Comment by kocio-pl** [comment]
I guess this ticket was about single issue, not a general rule? It would be hard to tell if amenities or shops are more important to be rendered first. If so, I think it could be closed.
