### ISSUE TITLE
Should not render closed ways with waterway=canal as area

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#2424]
https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dcanal says that it should not be used on areas and also to `Consider adding width=* to indicate the width in meters, for example width=5 or alternatively use waterway=riverbank to create an area for the canal in addition to the linear 'canal' feature along the centreline.`

Since it's a linear feature only, we should not have it rendered as an area when it's mapped as a closed way.

Example of a canal being wrongly used to render the whole canal area:
https://www.openstreetmap.org/way/230145073
![](https://cloud.githubusercontent.com/assets/982338/19901005/a84edc20-a04c-11e6-83c4-b984f716bc71.png)

And places where it seems to be properly mapped and tagged, but are being wrongly rendered as areas:
https://www.openstreetmap.org/way/192657911
![](https://cloud.githubusercontent.com/assets/982338/19901222/8a0fa982-a04d-11e6-8e65-143566165384.png)

https://www.openstreetmap.org/way/114691942
![](https://cloud.githubusercontent.com/assets/982338/19901403/3170986c-a04e-11e6-815f-91da5c713ca1.png)

**Comment by dieterdreist** [comment]
are you sure those circular waterway features are correctly tagged as "canal"?

**Comment by kocio-pl** [comment]
I have visited both links and it looks like a real issue:

https://www.openstreetmap.org/way/192657911
https://www.openstreetmap.org/way/114691942

**Comment by imagico** [comment]
Correct.  This should indeed be changed.

The historical context:  Before the [water details proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Water_details) in 2011 there was no way to distinguish between rivers and canals in terms of area mapping so some mappers suggested using `waterway=canal` like `waterway=riverbank` in case of canals.  This was not a good idea of course since the tag was already used for line features with a different meaning.  Today the solution is clearly tagging `natural=water` + `water=canal` and use of `waterway=canal` on areas has for a long time been documented not to be valid.

Changing this would not only ensure the rare cases of circular canals are rendered correctly, it would also support the widely accepted tagging practice and discourage incorrect use of tags.

**Comment by pnorman** [comment]
With the osm2pgsql C transforms currently in use a feature is put either into the line or polygon table based on if it is closed and the .style file, so all waterway=* features are polygons when possible.

We will be switching to the lua transforms, and this is handled differently in them: https://github.com/gravitystorm/openstreetmap-carto/blob/3652b34d/openstreetmap-carto.lua#L42

**Comment by imagico** [comment]
Not rendering waterway=canal on areas would still be possible with the current setup.

**Comment by kocio-pl** [comment]
I wonder if adding area=no could be used as a workaround.

**Comment by Klumbumbus** [comment]
> I wonder if adding area=no could be used as a workaround.
Yes this works, but it should not be necessary since waterway=canal is a line tag only. Therefore adding area=no would be a bit tagging for the renderer.

The number of valid closed waterway=canal ways is low. So the more important part of this issue is to not render wrongly mapped objects as areas anymore (like https://www.openstreetmap.org/way/230145073), so the mapping error is more obvious.

**Comment by Klumbumbus** [comment]
An osm file with all closed ways and multipolygons with waterway=canal tag from today can be downloaded here: https://josm.openstreetmap.de/attachment/ticket/13877/canals2.osm.bz2
(2243 ways and 62 multipolygons)

**Comment by kocio-pl** [comment]
@imagico 
> Not rendering waterway=canal on areas would still be possible with the current setup.

What do you mean exactly?

**Comment by imagico** [comment]
> What do you mean exactly?

Obviously dropping canal from

https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml#L265

**Comment by kocio-pl** [comment]
It would just stoop rendering them at all, I guess. I'm not sure which is better in this case (wrong rendering or lack of rendering) and if it's worth changing, even if time frame for switching to lua branch is unknown at this moment.

**Comment by pnorman** [comment]
👍 to removing them, and the other reference in https://github.com/gravitystorm/openstreetmap-carto/blob/e4a4fd71656d0c716b31083901340d4ef0738974/water.mss#L29

We have the implicit assumption that we can tell if an object is supposed to be an area or linear feature based on its tags, and this will be explicit with Lua. How we're treating waterway=canal breaks this.
