### ISSUE TITLE
Residential area address should be rendered as would a building address

### ISSUE THREAD

**Issue by stragu** [gravitystorm/openstreetmap-carto#2460]
_[first time reporting an issue for the standard style, sorry if it is too subjective or if I miss something in the reporting process]_

I would suggest that area tagged as `landuse=residential` should have labels rendered as a residential building would. i.e., if it has a value for `addr:housename` and/or `addr:housenumber`, those should be rendered as labels. See this screenshot from the OSM website ([see map and data](http://www.openstreetmap.org/#map=19/-27.48672/153.00778)):

![standard-residential-area-labels](https://cloud.githubusercontent.com/assets/1747497/20549336/0342596e-b177-11e6-9348-3368fbf9ed23.png)

In the screenshot, two residential areas are used to group apartment buildings, and it is the residential area that contains the address tags as they are the same for all buildings inside the area.

Currently, there are no labels, whereas another single apartment building that has an address shows both `addr:housename` and `addr:housenumber values`.

However, the value for `name` is currently rendered identically in both cases (and has priority over the address labels in the case of a single building).

Should the style be changed to have the same label rendering for both residential buildings and residential areas?

**Comment by pnorman** [comment]
There's nothing specific about residential here. I thought we did render addresses on landuse areas, but I looked into it and it's always been `building is not null` for polygons. I guess the examples I remembered were a point within a landuse polygon, which makes our current rendering somewhat inconsistent.

**Comment by HolgerJeromin** [comment]
Thanks for reporting. This issue is discussed here #1746

**Comment by mboeringa** [comment]
> Should the style be changed to have the same label rendering for both residential buildings and residential areas?

IMO a big no!

This is mis-usage of the residential tag to make addresses visible. Residential areas should not cover single buildings or small groups of buildings that are not some kind of administrative entity besides a single address.

At least here in the Netherlands, this is generally considered a really poor tagging practice... and mostly reverted. It is clear that supporting this, will quickly lead to millions of tiny "residential" areas being added.

**Comment by stragu** [comment]
@mboeringa so what would be the preferred way to tag a site that has several buildings at the same address?

**Comment by mboeringa** [comment]
@stragu. The general practice is to simply place a single node with the address tags somewhere appropriate, e.g. near the main building (if any), or the entrance to the area.

I realise this will not give you the "these building belong together" information, but residential areas were not designed to solve this. If there is a fence, wall or hedge around the perimeter, you could consider adding that, but please only add the feature where it actually exists, and not artificially around the entire perimeter just to make the perimeter show up.

**Comment by dieterdreist** [comment]
2016-11-23 10:33 GMT+01:00 mboeringa <notifications@github.com>:

> Should the style be changed to have the same label rendering for both
> residential buildings and residential areas?
>
> IMO a big no!
>
> This is mis-usage of the residential tag to make addresses visible.
> Residential areas should not cover single buildings or small groups of
> buildings that are not some kind of administrative entity besides a single
> address.
>

administrative entities have completely different tagging
(boundary=administrative and admin_level), landuse can have any extension,
and nowhere it says you couldn't use it on a single plot (as the wiki never
gave any scale what is "too small" to get such a tag).

IMHO we should render addresses on all kinds of areas that have an
addr:housenumber or housename tag, regardless of other tags that are there.
"housenumbers" - despite their name - being (legally) associated to
buildings is just one kind of construct you can find in the real world,
others are building plots (parts of Germany) or even entrances (Italy,
including some "potential" entrances) and maybe more.



> At least here in the Netherlands, this is generally considered a really
> poor tagging practice... and mostly reverted. It is clear that supporting
> this, will quickly lead to millions of tiny "residential" areas being added.
>


what is the problem with small areas having landuse=residential attached to
them (potentially reusing existing polygons) could be discussed on the
tagging ML if you like.

**Comment by dieterdreist** [comment]
2016-11-23 13:05 GMT+01:00 mboeringa <notifications@github.com>:

> I realise this will not give you the "these building belong together"
> information, but residential areas were not designed to solve this.



it will also mean you don't convey information about the spatial extension
of the housenumber, and would have to repeat the address information for
all POIs at the same address (as opposed to inheriting them from an
enclosing addr-object)

**Comment by mboeringa** [comment]
> what is the problem with small areas having landuse=residential attached to them (potentially reusing existing polygons) could be discussed on the tagging ML if you like.

Residential areas are generally used cartographically to display build up areas at mid and low zoom, and thus have a pretty vital function in openstreetmap. It is likely that this proposal will stimulate a mass import of cadastral data / parcels as residential areas, with potentially tens of millions of parcels being added as residential areas, making the rendering of residential a real problem.

> IMHO we should render addresses on all kinds of areas that have an addr:housenumber or housename tag, regardless of other tags that are there.

I only see an option for this with an _exclusion clause_ for any area tagged as **landuse=x**, as landuse is the most likely tag to be combined with addresses (besides building=x), e.g.:

**landuse IS NULL AND addr:housenumber is NOT NULL**

This will then require users to draw a secondary way for these features without a landuse tag if they want the address to show up, which is less of problem as the object will then become an OSM feature on its own with its own specific OSM ID (and they can still re-use nodes, but not the closed way of an existing feature).

For other keys like **leisure=x** this is less of a problem, because generally (but not always), the address's and leisure facility's outer perimeter will coincide, whereas clearly with residential or industrial areas, this is not the case.

**Comment by dieterdreist** [comment]
2016-11-23 14:29 GMT+01:00 mboeringa <notifications@github.com>:

> For other keys like *leisure=x* this is less of a problem, because
> generally (but not always), the address's and leisure facility's outer
> perimeter will coincide, whereas clearly with residential or industrial
> areas, this is not the case.
>

you seem to imply that landuse=residential is for a "residential area" as
kind of place (a settlement part), but it is rather about the use of land.
You can have different landuses inside a residential area (for instance)

**Comment by mboeringa** [comment]
@dieterdreist, I agree there are multiple landuses that may also be used inside a residential area, like landuse=grass and landuse=forest, that are more used as landcover.

However, just look at a lot of the OpenStreetMap webmaps out there: they often use the following landuses at mid and low zoom scales to depict build-up areas:

- landuse=residential
- landuse=industrial
- landuse=railway
- landuse=commercial
- landuse=garages

Among others like Sputnik, certainly _Standard_ and _Fietskaart_ do this clearly... Humanitarian only really shows industrial landuse clearly at mid and low zoom. There is no good alternative for this.

**Comment by dieterdreist** [comment]
2016-11-23 18:17 GMT+01:00 mboeringa <notifications@github.com>:

> Among others like Sputnik, certainly *Standard* and *Fietskaart* do this
> clearly... Humanitarian only really shows industrial landuse clearly at mid
> and low zoom. There is no good alternative for this.
>

I'm aware of this, and am also aware that there is no out-of-the-box
alternative. Still, for rendering raster maps there is no big difference
whether an area is made of several smaller parts (connected and with the
same landuse tag) or is mapped as one. You could also compute simplified
and or generalized landuse polygons out of many smaller landuse polygons
with you own rules, e.g. for mid- or low-zoom level rendering, or to make a
more quiet map. On the other hand, you won't be able to calculate a more
detailed version out of simplified/generalized landuse.

**Comment by stragu** [comment]
Interestingly, the "Address" page on the OSM wiki states that "it's possible to add a perimeter to the site which contains the addr tags and other general tags such as the name"; however, it does not say what the perimeter should be tagged as.

https://wiki.openstreetmap.org/wiki/Addresses#Multiple_buildings_for_one_housenumber

And just because, I checked how many `landuse=residential` are associated to a `addr:housenumber` value, I found about 46800: https://taginfo.openstreetmap.org/tags/landuse=residential#combinations

**Comment by mboeringa** [comment]
> And just because, I checked how many landuse=residential are associated to a addr:housenumber value, I found about 46800: https://taginfo.openstreetmap.org/tags/landuse=residential#combinations

That's exactly why I think this is a potential bad development, before you know it, landuse=residential can no longer be used for what it was initially intended, because millions of these features will be added from cadastral registers.

> however, it does not say what the perimeter should be tagged as.

And that is what I suggest: write a proper Wiki proposal for a tagging scheme for (cadastral) parcels, to combat the mis-usage now arising.

Don't get me wrong: I do understand the desire to tag (cadastral) parcels, I just think it a inherently bad idea to use landuse=residential for that.

Please develop an alternative on the Wiki if you have interest in this.

**Comment by imagico** [comment]
Discussion seems to be completely about tagging now which does not belong here.  As it has been mentioned above #1746 seems to cover what this issue is about (that is showing addresses of non-building polygon features).  Unless @stragu has additional and independent concerns here that are not covered in #1746 i think we can close this issue.

**Comment by pnorman** [comment]
> I guess the examples I remembered were a point within a landuse polygon, which makes our current rendering somewhat inconsistent.

The inconsistency is a problem for me with the current rendering, I find the current situation unexpected.

**Comment by imagico** [comment]
Yes, but I think that is covered in #1746.

**Comment by mboeringa** [comment]
> however, it does not say what the perimeter should be tagged as.

@stragu I now noticed there is actually a tag that seems to cover (cadastral) parcel: **place=plot**. It is a while since I last checked the place key Wiki page, and it seems to have been added since I visited it the last time, at least I don't recall seeing it before:

http://wiki.openstreetmap.org/wiki/Tag:place%3Dplot

For larger groups of adjacent buildings that aren't plots, but also not the size of - or known as - a neighbourhood, there is now also **place=city_block**:

http://wiki.openstreetmap.org/wiki/Tag:place%3Dcity_block

Of course, this doesn't automatically get you a rendered address in the Standard style, but at least there seems to be a suitable tag now for defining these type of features with a corresponding Wiki page.

**Comment by dieterdreist** [comment]
sent from a phone

> On 3 Dec 2016, at 13:56, mboeringa <notifications@github.com> wrote:
> 
> @stragu I now noticed there is actually a tag that seems to cover (cadastral) parcel: place=plot. It is a while since I last checked the place key Wiki page, and it seems to have been added since I visited it the last time, at least I don't recall seeing it before:
> 
> http://wiki.openstreetmap.org/wiki/Tag:place%3Dplot
> 


I believe a boundary value would be better than place for this 


cheers,
Martin
