### ISSUE TITLE
Arabic line height excessive

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#2485]
Noto Kufi Arabic is really tall: It has a line height of 1.9x em. This is compared to 1.36 em of Noto Sans UI and Noto Naskh Arabic UI - sadly there is no UI variant of Kufi. Maybe reconsider decision to use Kufi instead of Naskh (style.mss:  _Noto Kufi Arabic is the one that is most similiar to a Sans style_) 

[Casablanca](http://www.openstreetmap.org/relation/392915#map=8/33.516/-6.721) - first Kufi then Naskh (the middle line is the local Shilha)
![kufi](https://cloud.githubusercontent.com/assets/156724/20862849/b98b24ca-b9b6-11e6-812f-40bfe704c5de.png)
![naskh](https://cloud.githubusercontent.com/assets/156724/20862851/d0067f6a-b9b6-11e6-9902-1ac637bff1da.png)

Also a road shield from #2478 in Tunisia ([link](https://www.openstreetmap.org/#map=16/36.7281/9.1974))

Line heights here: https://gist.github.com/jojo4u/0b9284abc03278559a5ccd8dc49d4c0e (divide text height by EM size).

**Comment by sommerluk** [comment]
Yes, this seems to be a good idea.

The good thing about Kufi was that it seemed to be more legible at the same font size. However, the high line spacing seems to be a fixed design property of the arabic script, so that’s the price we have to pay when using Kufi.

Apart from the line spacing, there might be another argument for Nashk: Following Googles Noto page, it covers more languages and regions, so I assume it has some more glyphs than Kufi. Furthermore, it has an UI version.

BTW: It seems that in the Noto alpha version, both Kufi Arabic and Nashk Arabic are no longer available, but there is a Sans Arabic (also UI version available).

**Comment by jojo4u** [comment]
The alpha "Noto Sans Arabic UI" is between Kufi and Naskh in style. So this might be an alternative in the future.
![noto kufi arabic](https://cloud.githubusercontent.com/assets/156724/20946640/d2569578-bc0b-11e6-8e59-d1b7d7b2237f.png)
![noto naskh arabic ui](https://cloud.githubusercontent.com/assets/156724/20946638/d24f430e-bc0b-11e6-9193-47b01d97cca9.png)
![noto sans arabic ui](https://cloud.githubusercontent.com/assets/156724/20946639/d252ecc0-bc0b-11e6-8056-4e84235998a5.png)
