### ISSUE TITLE
Rendering of building=train_station and railway=platform/highway=platform(?) does not respect layers

### ISSUE THREAD

**Issue by jc86035** [gravitystorm/openstreetmap-carto#2504]
See [22.4482°N, 114.0046°E](https://www.openstreetmap.org/#map=18/22.44828/114.00461). The small light rail platforms (1, 2 and 3 to the northeast) should ideally be rendered below the large train station building (or in a tunnel casing, if possible), and the train platforms (and station building) should all be rendered above the road junction. However, currently all are rendered below the road, and platforms do not change rendering with `tunnel=yes`/`covered=yes`.

In addition, the new brown rendering of `building=train_station` is [being a little annoying](https://www.openstreetmap.org/#map=18/22.27921/114.18325). Although the "station building" is underground, the brown is rendered above the buildings located over the station. I know the solution in this particular case is probably to change the station to pedestrian passageways + platforms with a `railway=station` node, but the brown casing could instead be made transparent.

**Comment by kocio-pl** [comment]
It's quite old and known problem - see especially https://github.com/gravitystorm/openstreetmap-carto/issues/688 and https://github.com/gravitystorm/openstreetmap-carto/issues/327.

The general problem with layers is that we don't have "universal" layers. They work only inside the single class of objects and it's a designer decision to make some classes be located on top of some others.

However I'm curious now if we could make a special, separate layer just for train stations and make it located above all the roads and platforms. This exception could be compromise worth having, because train stations in big cities should be visible as landmarks and we're not able to show their inner structure in a usable way without layer viewer, so they tend to suffer the most:

Berlin - http://www.openstreetmap.org/node/3856100103
New York - https://www.openstreetmap.org/way/265947358
Paris - http://www.openstreetmap.org/way/67825345
London - http://www.openstreetmap.org/relation/6036811
Warsaw - http://www.openstreetmap.org/way/367491792

**Comment by geozeisig** [comment]
> They work only inside the single class of objects and...
It does not even work with the platforms. In the case of the Berlin example, the upper platform merges with the lower platform. It should be recognizable by a margin who lies over whom.

**Comment by mboeringa** [comment]
> In the case of the Berlin example, the upper platform merges with the lower platform. It should be recognizable by a margin who lies over whom.

Just for your information: even if a style would support rendering platforms in a layered fashion (which isn't trivial to implement), the Berlin example would fail, as the platforms are only tagged with level=x, not layer=x:


I

**Comment by jc86035** [comment]
Could `building=train_station` be rendered with the same layering as other buildings? There are several (above-ground) railway stations which have taller structures above them, and the brown obscures the other buildings.

**Comment by nebulon42** [comment]
@jc86035 Could you provide links to examples of what you mean?

**Comment by dieterdreist** [comment]
sent from a phone

> On 12. Dec 2016, at 20:50, mboeringa <notifications@github.com> wrote:
> 
> the Berlin example would fail, as the platforms are only tagged with level=x, not layer=x:


one might argue that level should be taken into account similarly to layer. In general the Berlin station is too complex to make sense in one plan alone, especially if it's not a cross section but a floor plan

**Comment by Gazer75** [comment]
building=roof + layer=1 really should be above a platform, but that is not working currently.

**Comment by jc86035** [comment]
At some point `building=train_station` started being layered correctly (this could be a side effect of #3426), and covered platforms are now also being hidden (even if I think it probably have been better to give them some sort of tunnel casing). As such, the issue has been completely resolved.
