### ISSUE TITLE
Render amenity=studio

### ISSUE THREAD

**Issue by abdeldjalil09** [gravitystorm/openstreetmap-carto#2518]
amenity=studio should be rendered with and icon and his name
http://taginfo.openstreetmap.org/tags/amenity=studio

**Comment by jojo4u** [comment]
**A studio used for creating radio or television programmes and broadcasting them. It can also be used to mark a music recording studio.** 
Accepted proposal from 2008 (that's why the amenity key), documented wiki page, 4000 instances, no open problems in Talk page.

**Comment by kocio-pl** [comment]
Standard questions for a start:
1. Do we want to have this icon?
2. How should it look like (real 14px examples are preferred, but not required)?

**Comment by HolgerJeromin** [comment]
The feature is IMO only useful to have its name rendered. 
Most people does not want to go to a amenity=studio (if this is not a leisure=themepark)
An icon (microphone, TV/movie screen) will let me think about a night club or cinema.

**Comment by kocio-pl** [comment]
What about generic brown dot?

**Comment by dieterdreist** [comment]
sent from a phone

> On 20 Dec 2016, at 16:59, Holger Jeromin <notifications@github.com> wrote:
> 
> The feature is IMO only useful to have its name rendered.
> Most people does not want to go to a amenity=studio (if this is not a leisure=themepark)
> An icon (microphone, TV/movie screen) will let me think about a night club or cinema.


the tag is weakly defined, it can be used for things as different as a tv studio, a radio studio or a music recording studio, it isn't suggested for film studios though. TV Studios are usually quite important and significant for the area they are in (and beyond), radio studios can be smaller and music recording studios come in all sizes.

**Comment by jojo4u** [comment]
> he tag is weakly defined

You say as if there is something wrong with the tag. If somebody wants to differentiate between radio/tv/music (and film) the subtag studio=* exists and is documented.

**Comment by dieterdreist** [comment]
sent from a phone

> On 21 Dec 2016, at 01:02, jojo4u <notifications@github.com> wrote:
> 
> You say as if there is something wrong with the tag. If somebody wants to differentiate between radio/tv/music (and film) the subtag studio=* exists and is documented.


yes, IMHO there is something wrong with this tag. There's really no hint in the key/value that this is a tag for tv and radio and music recording studios (quite different, these) but not for film studios, dance studios, art studios, kitchen studios, photo studios, and what ever studio else there might exist. http://taginfo.osm.org/keys/amenity#values

A tv studio is typically a place where visitors are common (attending tv shows etc), it is generally huge, with administration areas, parkings etc., while a music recording studio is a place where visitors/spectators are usually not admitted, and which might more often than not be just a room with certain acoustical properties.

There's no sense in arbitrarily mixing together some very different kinds of studios while keeping others like film studios out.

It is also not clear whether "and broadcasting them" is meant as an exclusive "and" or as "or" / "and or". Should places where only broadcasting is organized get the tag? Is broadcasting required or can "record-only places" get the tag as well?

The studio key is even more confusing, as it includes studios that are not included in amenity=studio http://taginfo.osm.org/keys/studio#values

IMHO this style should not support this tag, because it is not clearly defined thus apparently not consistently applied to similar object, examples:
https://i.kinja-img.com/gawker-media/image/upload/s--nU_xR2g8--/c_scale,fl_progressive,q_80,w_800/17kom8oradz91jpg.jpg

http://www.studivoxson.com/immagini/studi/voxson-studio5-b.jpg

**Comment by abdeldjalil09** [comment]
In humantarian style , amenity=studio is rendered with microphone icon.

**Comment by d1g** [comment]
@dieterdreist my understanding that only few cities have recording studios without broadcasting equipment. Your example was about `amenity=studio + studio=audio` see osmwiki for details about `studio=*` sub tag

I would change "and broadcasting them" to "and **usually** broadcasting them"

**Comment by Tomasz-W** [comment]
This tag is very diversified, and it would be hard to make an universal generic icon matching all studio types. Another option is to project separate icon for each studio=* tag, but - as someone said here earlier - this information wouldn't be useful for average map user. IMO rendering just studio's name, or it's name with simple dot (rendering amenities without icon as a dots is considered -> #108 ) would be enough.

**Comment by dieterdreist** [comment]
2018-01-10 14:30 GMT+01:00 Tomasz-W <notifications@github.com>:

> This tag is very diversified, and it would be hard to make an universal
> generic icon matching all studio types.
>


+1, this is something that should go to the tagging ML, the tag name is far
too broad, it is defined as "A studio used for creating radio or television
programmes and broadcasting them. It can also be used to mark a music
recording studio.", i.e. it could be a broadcasting or a recording studio
(or both), but there are many other things that can be called "studio", so
a more explicit tag name seems appropriate.

**Comment by kocio-pl** [comment]
I think microphone is a common element for all kinds of the studios and we could render it.

**Comment by Tomasz-W** [comment]
I like this icon. 
Another option is to use office-blue generic dot for this feature, because is not an amenity for common-use.

**Comment by jragusa** [comment]
https://www.openstreetmap.org/way/209429260 (radio station)

brown amenity colour:
![studio](https://user-images.githubusercontent.com/9897203/38582233-6040237e-3d0f-11e8-879a-9b2b4f62e26d.png)

steeblue (#4863A0) office colour:
![studio_office](https://user-images.githubusercontent.com/9897203/38582604-98d5e132-3d10-11e8-8ee6-72ad46b06c7b.png)

**Comment by Tomasz-W** [comment]
I vote for office-blue

**Comment by dieterdreist** [comment]
I stand by my previous comments and would not render this feature because it is badly defined, or would at least also look at the studio=* tag (IMHO it is sufficient to only look at studio=* and ignore amenity=studio as it doesn’t add anything)

**Comment by Tomasz-W** [comment]
> I stand by my previous comments and would not render this feature because it is badly defined

I wouldn't say it is badly defined, it's just quite "wide" tag. A common part od all subtypes is audio recording, so studio microphone shape fit here very well.

**Comment by dieterdreist** [comment]
2018-04-11 11:54 GMT+02:00 Tomasz Wójcik <notifications@github.com>:

> I stand by my previous comments and would not render this feature because
> it is badly defined
>
> I wouldn't say it is badly defined, it's just quite "wide" tag. A common
> part od all subtypes is audio recording, so studio microphone shape fit
> here very well.
>

a television broadcasting studio doesn't have to record audio, and also if
they do, it wouldn't be represented well by a microphone (IMHO). I also
wouldn't think we should display tv studios and small music recording
studios (or podcast studios) with the same priority and starting from the
same zoom levels.

**Comment by matkoniecz** [comment]
I think that given this tag is supposed to be used for features that are unlikely to be orientation points, not used by general public and tag itself is problematic for reasons mentioned in

> yes, IMHO there is something wrong with this tag. There's really no hint in the key/value that this is a tag for tv and radio and music recording studios (quite different, these) but not for film studios, dance studios, art studios, kitchen studios, photo studios, and what ever studio else there might exist. http://taginfo.osm.org/keys/amenity#values

I propose to decline rendering.

**Comment by Tomasz-W** [comment]
@kocio-pl Can we re-open this issue and try with office-blue generic dot for this feature?

**Comment by HolgerJeromin** [comment]
> Can we re-open this issue and try with office-blue generic dot for this feature?

Nothing has changed IMO [since the closing](https://github.com/gravitystorm/openstreetmap-carto/issues/2518#issuecomment-382760136). 
Having (the possiblity to add) a dot should not result in having a dot for all "other" stuff.

**Comment by matkoniecz** [comment]
I am strongly against reopening as this tag is fortunately not clearly accepted by community and as described in https://github.com/gravitystorm/openstreetmap-carto/issues/2518#issuecomment-268472441 this tag is really poorly describing reality.

If it is office then replacing it with/additionally tagging it with office=* is desirable.

**Comment by Tomasz-W** [comment]
> this tag is fortunately not clearly accepted by community

Actually only you and @dieterdreist have some problems with tagging scheme of this feature. See https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dstudio

Reading discussion here and on the Wiki, for other users everything seems to be ok and understandable.

**Comment by kocio-pl** [comment]
Closing discussion is not the technical problem, you can still discuss it, as it is done now. However the discussion does not seem to be settled yet, so I'm reopening it to show the real state.

**Comment by Adamant36** [comment]
@matkoniecz, what if it was only rendered with studio=type? There's currently 438 uses of studio=audio, 276 uses of studio=video, 587 uses of studio=television, and 957 uses of studio=radio. The numbers are low, but its about how many studios there are overall. Maybe it be an incentive for people to add the tags to amenity=studio, or at least give us a way to revisit it later when the numbers are higher. Because as you say, amenity=studio along is a little to vague as it is, but maybe not with studio= values added to it.

**Comment by jeisenbe** [comment]
@dieterdreist, @matkoniecz, others: 
What are your thoughts on rendering amenity=studio only when studio=audio, studio=video, studio=television, or studio=radio?

**Comment by matkoniecz** [comment]
It makes more sense to me, but I have little knowledge about this type of tagging. Is there some discussion on tagging mailing list or documentation on OSM wiki reviewed by people with more knowledge on this topic?

**Comment by dieterdreist** [comment]
Am Di., 23. Okt. 2018 um 06:28 Uhr schrieb jeisenbe <
notifications@github.com>:

> @dieterdreist <https://github.com/dieterdreist>, @matkoniecz
> <https://github.com/matkoniecz>, others:
> What are your thoughts on rendering amenity=studio only when studio=audio,
> studio=video, studio=television, or studio=radio?
>


I am generally against support of amenity=studio because it is problematic
tagging and should not be encouraged. There is no benefit from this kind of
tagging (grouping all imaginable kinds of studios in one tag and shifting
the meaning on the second level). There is also amenity=tanning_studio for
example. I would encourage people to tag amenity=video_studio,
amenity=radio_studio etc.

**Comment by jragusa** [comment]
Any improvement about this issue ? `amenity=radio_studio|tanning_studio` as suggested by @dieterdreist are only used twice and have no wiki page and `amenity=video_studio` is not used while there is 7137 `amenity=studio`. Moreover, `studio=radio` is used 1316 times, `studio=audio` 581 times and `studio=video` 368 times.

I think that rendering the icon for `amenity=studio` + `studio=radio|audio` would satisfy everyone regarding the discussion and it's easy to implement. If necessary, different colour can be used to distinguish radio (blue) from audio (brown).

All that remains is to develop an icon for `studio=video` @Tomasz-W if you have time.

**Comment by Adamant36** [comment]
@jragusa, you should create a Wiki page for studio=*. Aslo, if studio=video is going to be rendering it  would be useful to render studio=television along with it so there isn't miss-tagging to get it to render. Plus, it would just be useful to have. Although there's only 870 uses :(. Seems like a lot studios serve multiple purposes, or there would probably be more.

**Comment by geozeisig** [comment]
@jragusa I have created wiki pages for studio. So far, there are 4 values: [audio](https://wiki.openstreetmap.org/wiki/Tag:studio%3Daudio), [radio](https://wiki.openstreetmap.org/wiki/Tag:studio%3Dradio), [video](https://wiki.openstreetmap.org/wiki/Tag:studio%3Dvideo), [television](https://wiki.openstreetmap.org/wiki/Tag:studio%3Dtelevision). Please look at it and add or correct it.
The problem with this key is that there are many values that should reject.
In the 2008 proposal, it was suggested that the type (audio or video) of the study should be specified with type = *. This collided with the tags of the multipolygon, which also uses type = *. As a result, the use of studio = * or studio: type = * was suggested on the English discussion page 2014. It was agreed on studio = *. At the beginning of 2016, the preset was adjusted accordingly in the editor JOSM.
An overview of the values can be seen in [taginfo](https://taginfo.openstreetmap.org/keys/studio#values).

**Comment by dieterdreist** [comment]
sent from a phone

> On 22. Nov 2019, at 17:39, geozeisig <notifications@github.com> wrote:
> 
> @jragusa I have created wiki pages for studio. So far, there are 4 values: audio, radio, video, television.


I believe amenity=studio is not a good tagging concept because it is too generic, a video studio is something completely different than a movie studio, an audio studio doesn’t seem a good concept either, is this about radio or recording? A television studio is something quite different as well, why would we want to discern these just by subtags? What about a denstist‘s studio? Architect‘s studio? Artist studio? Dance studio? IMHO we should abandon amenity=studio in favor of more specific main tags...
(sorry for writing all this here and not to the tagging ml, but somehow it felt relevant as points for discourage the tag by not supporting it)

**Comment by jragusa** [comment]
@dieterdreist I agree with you about the broad definition of `amenity=studio` and the subtag `studio`have to resolve this uncertainty. The taginfo link provided by @geozeisig shows that we can distinguish a television studio from a video (generic value) or a cinema studio. Likewise, we can separate a radio studio from a recording studio (audio). Even photography, dance and graphic are already used.

Here I propose to only render radio studio (`amenity=studio` + `studio=radio`) and audio studio (`amenity=studio` + `studio=audio`) because they are well populated and the icon fits with them. The difference lies on different colour rendering: office blue for the `studio=radio` and amenity brown for `studio=audio`. `amenity=studio` alone won't be showed and will need the additional studio tag to be considered.

**Comment by dieterdreist** [comment]
sent from a phone

> On 5. Dec 2019, at 12:48, Jérémy Ragusa <notifications@github.com> wrote:
> 
> The difference lies on different colour rendering: office blue for the studio=radio and amenity brown for studio=audio. amenity=studio alone won't be showed and will need the additional studio tag to be considered.


my point is we should move tagging away from amenity=studio as it is too broad to be meaningful and unnecessarily complicated evaluation of this data as well as tagging (you need 2 tags of which one is meaningless). We could have amenity=television_studio / radio_studio / audio_recording_studio / film_studio etc. and make everybody’s life easier

**Comment by wmisener** [comment]
I don't really understand the opposition to rendering this, at least as equivalent to a non-specific office with a blue dot. This tag is documented, used almost 10k times all around the world, an iD preset, and there are no moderately-used or even formally proposed alternative tagging schemes even though this issue has been open for over 4 years. Even if some mappers have personal issues with the tag, shouldn't the existing predominant use be rendered rather than trying to somehow guide the community to come up with an alternative that may or may not gain traction and hasn't happened so far?

**Comment by dieterdreist** [comment]
sent from a phone

> On 9 Feb 2021, at 06:44, wmisener <notifications@github.com> wrote:
> 
> I don't really understand the opposition to rendering this, at least as equivalent to a non-specific office with a blue dot.


every office is an office, but what are the common properties of an audio recording studio, a film studio, a tv transmission studio, an architecture studio, a yoga studio?

**Comment by ArloJamesBarnes** [comment]
This might be enough of a tangent that it needs a new issue, but why not just consider the 'secondary tag' being discussed here a primary tag -- that is, consider it even in the absence of the `amenity`-based tag?

I'm not sure I buy that offices generally are the same thing as each other, but I agree that it's important that if someone believes a building or room to be an office that they be able to tag it as such with a specific value for that key and have it render at least in a basic fashion. The same could be said for a studio. Indeed, looking at https://en.wiktionary.org/wiki/studio#Etymology it seems directly comparable to the usage of the word 'office' or 'workshop' (https://wiki.openstreetmap.org/wiki/Key:workshop, as another point of reference) as a place outfitted for an intended labour. And it's a digression anyway, since it has been brought up that a tag that specifies the type of studio is possible, either under the `amenity` or `studio` key, and (I'd like to assert) either considered primarily or secondarily in a rendering context. Since there seems to be widespread agreement that the specific tags are suitable, why not establish specific rendering at least for now?

Discussion about whether a particular tagging is suitable for consideration as a destination seems to be about the amenity key more generally (and I agree with the sentiments expressed), but not really about whether these kinds of places should receive rendering support. This isn't an issue ticket for a routing software, so whether a POI is a destination or not does not seem relevant.

I also think this thread needs a lot less repetition so the issues at the root can actually start getting addressed and progress made, either by closing it permanently or establishing some kind of rendering.

**Comment by Adamant36** [comment]
IMO, someone should put the effort into tagging the 9,000 or so uses of this with the appropriate studio=* tags. Then revisit this once that happens so specific ones with high enough usage can be rendering instead of treating things like this can be rendered as a general catch icon that people will somehow magically understand when that's clearly not the case. If not, then I say close it. Or really, close it in the meantime anyway. Its not like it can't be reopened when someone actually does something to make it renderable instead of just complaining.

**Comment by imagico** [comment]
@ArloJamesBarnes - you make some very good points here.  We don't want to render tags because they are widely used, we render them because they are used consistently for something well defined and meaningful.  amenity=studio as has been pointed out by several people does not qualify as such (at least not on its own without more specific tags in addition).  Furthermore we have several tag groups (like craft=*, office=* and workshop=*) that overlap and compete with it and there is no clear consensus among mappers about the delineation of these groups.

Rendering specific values of studio=* with well defined meaning, broad acceptance and consistent use - either as standalone tag or when in combination with amenity=studio - is a different matter but that would be a matter for separate issues.

Closing this again as there does not seem to be a chance for support for this in rendering as suggested.
