### ISSUE TITLE
Add rendering for landuse=logging

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2531]
23 787 uses already and has a wiki page. I think it should be rendered the same as landuse=industrial, since logging is clearly related to wood industry.

**Comment by dieterdreist** [comment]
sent from a phone

> On 3 Jan 2017, at 03:34, kocio-pl <notifications@github.com> wrote:
> 
> 23 787 uses already and has a wiki page. I think it should be rendered the same as landuse=industrial, since logging is clearly related to wood industry.


-1, I would rather render it like forest, maybe like farmland but definitely not like industrial

**Comment by kocio-pl** [comment]
I was also thinking about industrial background + tree pattern. Forest rendering makes little sense, since they are mostly inside the forest (so we have no white spaces, but we're effectively not able to recognize them), and I guess farmland is rather for growing than cutting.

**Comment by pnorman** [comment]
This seems to only be used in Russia and parts of Eastern Europe.

**Comment by dieterdreist** [comment]
2017-01-04 10:12 GMT+01:00 Paul Norman <notifications@github.com>:

> This seems to only be used in Russia and parts of Eastern Europe.



to me this tag has a lot of problems and it seems to require a subtag
"logging":

https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dlogging
This wikipage is substandard and likely would not have passed our standard
proceduce for tag development (proposal process) in this form.

from the wiki:

"Describes logging areas. For the natural or intentional reforestation
areas may be used in combination with natural
<https://wiki.openstreetmap.org/wiki/Key:natural>=scrub
<https://wiki.openstreetmap.org/wiki/Tag:natural%3Dscrub>. "


--> scrub explicitly is not for forest areas (which would be both,
"intentional" and "natural reforestation" )


from the wiki:

"Additional tags:

   - logging
   <https://wiki.openstreetmap.org/w/index.php?title=Key:logging&action=edit&redlink=1>
   =clearcutting
   <https://wiki.openstreetmap.org/w/index.php?title=Tag:logging%3Dclearcutting&action=edit&redlink=1>
   - all trees in an area are uniformly cut down;
   - logging
   <https://wiki.openstreetmap.org/w/index.php?title=Key:logging&action=edit&redlink=1>
   =selective_cutting
   <https://wiki.openstreetmap.org/w/index.php?title=Tag:logging%3Dselective_cutting&action=edit&redlink=1>
   - only some trees in an area are cut down (for example, sanitation cutting);
   - logging:start_date
   <https://wiki.openstreetmap.org/w/index.php?title=Key:logging:start_date&action=edit&redlink=1>
   =* - logging date (using the format yyyy-mm-dd)."



as the logging will likely be done in a short time frame, this tag will
soon have to be removed again in case of "clearcutting", while "selective
cutting" implies the forest to remain (i.e. the tag is not chosen well,
because incompatible with landuse=forest).

Generally, the most significant information of this tag seems to be able to
add a "logging:start_date", while landuse=forest already implies
landuse=logging (at some point in time).

-1 for supporting this tag, it is incompatible with the rest of the tagging
scheme and its usage should be discouraged.

**Comment by imagico** [comment]
That is not necessarily a problem IMO (considering the non-uniform distribution of woodlands and the non-uniform distribution of community interest in those globally).  But the tag is very vague at the moment, in a wide sense it could be used for any secondary woodlands (which have been cut down at some point in the past) that are currently used for wood production - which would apply to at least 2/3 of all woodlands in Germany for example.  We would need to consider if we actually want to render that in this style.

I would prefer to concentrate on rendering physical properties like leaf_type/leaf_cycle and possibly secondary vegetation layers (should we ever have a tagging scheme established for that).

**Comment by dieterdreist** [comment]
2017-01-04 10:49 GMT+01:00 Christoph Hormann <notifications@github.com>:

> That is not necessarily a problem IMO (considering the non-uniform
> distribution of woodlands and the non-uniform distribution of community
> interest in those globally). But the tag is very vague at the moment, in a
> wide sense it could be used for any secondary woodlands (which have been
> cut down at some point in the past) that are currently used for wood
> production



+1
IMHO this should become/remain a property "logging" to indicate if and how
logging occurs. No need to also add "landuse=logging", "logging" is not a
landuse, or it is for very short time in places that are the rest of the
time forests.

**Comment by pnorman** [comment]
> That is not necessarily a problem IMO (considering the non-uniform distribution of woodlands and the non-uniform distribution of community interest in those globally).

Ya, but I'd expect something in North America, Western Europe, or anywhere but those two areas.

> I would prefer to concentrate on rendering physical properties like leaf_type/leaf_cycle and possibly secondary vegetation layers (should we ever have a tagging scheme established for that).

Yes, I worry that this would take valuable cartographic space, which would make additional tree detail harder.

**Comment by polarbearing** [comment]
The tag describes a part of the forestry life-cycle, and as such it conflicts with landuse=forest. As a forest life-cycle is longer than e.g. on farmland, a sub-tagging would make sense. 

Thus I disagree with rendering the tag as it is.

**Comment by kocio-pl** [comment]
> The tag describes a part of the forestry life-cycle, and as such it conflicts with landuse=forest. As a forest life-cycle is longer than e.g. on farmland, a sub-tagging would make sense.

Thanks, this sounds right for me - it needs some discussion on Tagging list how it should be done properly. It's interesting to me however what type of landuse will be here after the logging is done - scrub does not look like analogy to a brownfield.

**Comment by dieterdreist** [comment]
2017-01-04 17:03 GMT+01:00 kocio-pl <notifications@github.com>:

> this also what I found in the city sometimes



what you find in the city is completely different to the situation (e.g.
soil) you will get after logging a forest.

**Comment by kocio-pl** [comment]
This tag is still raising, maybe some Tagging mailing list discussion should be resurrected to decide what to do with that wiki page:

https://wiki.openstreetmap.org/wiki/Tag%3Alanduse%3Dlogging

![taghistory 49](https://user-images.githubusercontent.com/5439713/46130175-e3c38980-c238-11e8-9d77-d0e473644ab7.png)

**Comment by ghost07tula** [comment]
The main difference of landuse=logging vs landuse=forest is that in Russia, unfortunately, not all loggings are restored with new trees. The common case is to clear cut the wood, wait about 5 - 10 years and then start using it as a residential area. And in this 5 - 10 year period this area is still registered as a wood.

**Comment by Adamant36** [comment]
@ghost07tula, its same way in California. There's a bunch of square spots in northern California that are tagged as landus=forest due to being used for logging, but they never grew trees back there for whatever reason. So just patches of ground that are rendered as trees when they shouldn't be. Its still considered managed logging forest though.

**Comment by kocio-pl** [comment]
My understanding is that it is no longer a forest there and it should be excluded from this area. Maybe this note should be added to the wiki page.

**Comment by ghost07tula** [comment]
For some period of time (up to 10 years) you don't know whether the forest will be restored in this area, or it will be formally excluded from it. Landuse=logging is exactly for this case

**Comment by kocio-pl** [comment]
This is exactly why I think such area should be excluded from the forest and probably tagged as logging. It should be clear then why this is excluded. When the forest is back (or whatever else), it should be tagged accordingly.

**Comment by ghost07tula** [comment]
Makes sense. So the correct way would be to tag logging as landuse=logging and exclude it from the forest, right? Then we face the question about logging rendering again.

**Comment by kocio-pl** [comment]
I reopen the ticket to show that the problem is discussed again.

Hm, it is similar to brownfield. Maybe something similar would make sense anyway.

**Comment by Adamant36** [comment]
Brownfield with the forest pattern maybe?

**Comment by kocio-pl** [comment]
Makes sense for me. Could you test that?

**Comment by jeisenbe** [comment]
Are we certain that this tag landuse=logging is only used for areas devoid
of trees?

Might it be used as a synonym for landuse=forest in the sense of “land used
for growing trees which will be cut down for wood/lumber in the future?”

The wiki page suggests that it may be an area of “selective logging” where
only some trees have been cut: “logging=selective_cutting - only some trees
in an area are cut down (for example, sanitation cutting);”

Someone should submit a proposal for this tag to define it better.

**Comment by Adamant36** [comment]
Sure. I can add it the list and give it a try. I've been wanting to learn how to do the code for patterns.

**Comment by kocio-pl** [comment]
@jeisenbe Would you like to take care of discussing this problem on Tagging list?

**Comment by jeisenbe** [comment]
Sorry, I’ve already got 2 proposals in the RFC stage, and I don’t know if
any examples of this tag in the areas where I map.

Dimitry, would you be willing to send an email to the tagging mailing list
about this?

**Comment by Adamant36** [comment]
Logging=clearcutting has 2016 uses and logging=selective_cutting only has 175 uses. In case it makes a difference. To me that makes it seem like its mostly used for clear cut areas. Plus, that's what the picture on the side shows. Instead of brownfield rendering we could always go with landuse=construction with tree pattern though. Maybe it would fit better. Or if nothing else, industrial with tree pattern. Also, it says the tag can be combined with scrub. If it was meant at all for still forested areas, I doubt scrub would work with it.

**Comment by kocio-pl** [comment]
@ghost07tula Great! You just need to register here:

https://lists.openstreetmap.org/listinfo/tagging

Then you simply write to the list address, and everybody else get their copy and the archive is created along the way.

**Comment by jeisenbe** [comment]
Good info. So both are pretty rare compared to the large number of uses of
the main tag.

**Comment by dieterdreist** [comment]
Am Do., 27. Sep. 2018 um 10:39 Uhr schrieb Adamant36 <
notifications@github.com>:

> @ghost07tula <https://github.com/ghost07tula>, its same way in
> California. There's a bunch of square spots in northern California that are
> tagged as landus=forest due to being used for logging, but they never grew
> trees back there for whatever reason. So just patches of ground that are
> rendered as trees when they shouldn't be. Its still considered managed
> logging forest though.
>



no, in osm, these areas are not considered landuse=forest, because they are
_not covered with trees_. It doesn't matter how they are legally
classified, all that matters for OSM is how they are actually used.
For me, "landuse=logging" for cut down areas seems semantically
problematic. "landuse=logging" is semantically describing that the area is
currently logged. Shouldn't this be "logged"?

**Comment by almccon** [comment]
I've been using `man_made=clearcut` + `natural=scrub` as recommended on the [man_made=clearcut](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dclearcut) wiki page.

It seems to me that `natural=scrub` is an apt description for these recently-logged areas, and the rendering also looks great and understandable. It's true that these areas might be scrub only temporarily, but that also agrees with the wiki description: "[Scrub] may be the mature vegetation type in a particular region and remain stable over time, or a transitional community that occurs temporarily as the result of a disturbance, such as fire."

So I'd suggest we either:

1. Simply render `landuse=logging` the same way that we render `natural=scrub` (and probably do the same thing for `man_made=clearcut` too).
2. Don't render `landuse=logging` and encourage editors to add `natural=scrub` in addition when they tag these features. The wiki page for [landuse=logging](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dlogging) already suggests this.

**Comment by dieterdreist** [comment]
I would add natural=scrub (if this is what is there now, even if
temporarily), and would not add man_made=clearcut (a tag that is not in
significant use and has neither been discussed nor proposed nor approved),
because the feature doesn't fit well under the "man_made" key.

**Comment by Adamant36** [comment]
I don't think natural=scrub would work because its for areas that have natural woody plant growth. Its not a given that the area left over from logging will contain that though. Some of them are just dirty areas, with maybe grass and left over logging tree waste. Tree waste doesn't count as scrub though. I don't think immature, replanted seedling trees count as scrub either. Its for a specific thing. Or, if scrub is there then add natural=scrub and landuse=logging. Because its the difference between landuse and land cover. It doesn't stop being logging land though just because the trees are chopped down.

**Comment by kocio-pl** [comment]
I don't see any clear solution here, so I close this ticket. Probably this area should be tagged with something more specific.
