### ISSUE TITLE
Add rendering for abandoned:highway=*

### ISSUE THREAD

**Issue by Fod90** [gravitystorm/openstreetmap-carto#2551]
Apologies for introducing another issue similar to #2030, but this is slightly different:

Whereas railways should be marked with `railway=disused` or `disused:railway=rail` if the tracks are still existing and `railway=abandoned` if the tracks have been removed (see [Key:railway](https://wiki.openstreetmap.org/wiki/Key:railway) ), highways should be marked with abandoned:highway=* if some physical infrastructure is still left (See [Key:abandoned](https://wiki.openstreetmap.org/wiki/Key:abandoned:) and the [comparison of life cycle concepts](https://wiki.openstreetmap.org/wiki/Comparison_of_life_cycle_concepts)).

Shouldn't [these](http://overpass-turbo.eu/s/lj5) be rendered (unless already rendered as [something else](http://overpass-turbo.eu/s/lj3))?

-- 
Jakob

**Comment by mboeringa** [comment]
While I know there is the special case of railways (and even that is disputed at times), which has the slightly special property of the abandoned or disused tracks often remaining in place for decades, or otherwise the former route visible in the landscape through embankments and cuttings, you really have to ask yourself the question with the **abandoned:x=y** tagging: _**where do we stop?!**_.

Would you also consider it desirable to see all **abandoned:amenity=waste_basket**s rendered in your own neighbourhood? Probably not... This is all ignoring the fact that rendering any abandoned/disused/razed tags, will also cause the already huge style to become even more bloated and unmanageable. 

These kind of questions regarding rendering of **abandoned/disused/razed:x=y** always make wonder how it would be to live in a centuries old medieval house, and still receive post for all the dozens of generations of dead people that once lived there... that is the  kind of feeling I get when these questions pass by.

I really think that Overpass Turbo is where this type of question belongs, that is, dynamically displayed when needed to answer some question.

**Comment by BalooUriza** [comment]
I see potential for a special case for highways as well.  These tend to be
substantial installations.  For example, there's approximately two miles of
I 44 near Catoosa, Oklahoma, including an entire toll plaza, that still
exists, yet was abandoned in 1992 when the Creek Turnpike opened.  To date,
the only things that have changed since then is that the OTA removed the
toll plaza buildings to recover for scrap money and avoid an attractive
nuisance; and the Pine Street overpass was removed, replaced by an
embankment that simply buried both carriageways of the abandoned toll
motorway when the overpass was deemed structurally deficient.  The overpass
over Spunky Creek immediately southwest, as far as I can tell, is no longer
certified to carry any traffic, and there are no plans to remove it,
either.  https://binged.it/2jHfVT3 has the current bing aerial.
 (Coincidentally, this puts the Spunky Creek overpass in the same category
as the old Southwest Boulevard overpass over the Arkansas River in downtown
Tulsa, at https://binged.it/2jHob5i , for which there is no money to
improve the bridge for even cycleway traffic, but even less money available
to demolish the bridge, even though it also is not suitable for any traffic
whatsoever today).

**Comment by imagico** [comment]
Almost all of these features are `abandoned:highway=track` of which the vast majority are from some import in Cameroon.

And valid uses of this tag with no remaining function as a path of some sort do not really make much sense to be rendered here i think.  Features we render usually have either a functional or a physical definition in the present of some sort, this has neither.

**Comment by mboeringa** [comment]
@BalooUriza :
Nothing prevents you from adding the former highway's bridges or viaducts as [man_made=bridge](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge)  area features. Just don't add ways over it tagged with **highway=x**, as otherwise routing engines will see it as a current road... not an abandoned one. Similarly, you can use [man_made=embankment](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dembankment) to delineate the raised banks of the former road as a topographical feature if they are still there.

No need to render **abandoned:highway=x** for this.

**Comment by dieterdreist** [comment]
sent from a phone

> On 17 Jan 2017, at 22:29, mboeringa <notifications@github.com> wrote:
> 
> Nothing prevents you from adding the former highway's bridges or viaducts as man_made=bridge area features. Just don't add ways over it tagged with highway=x, as otherwise routing engines will see it as a current road... not an abandoned one


bridges of abandoned highways and railways are often still very useful for hikers, I could imagine tagging like highway=path abandoned:railway=rail, bridge=yes making some sense.

**Comment by BushmanK** [comment]
That's quite hard to imagine how `highway=path` `abandoned:railway=rail` should be rendered differently from `highway=path`. Tagging, indeed, makes perfect sense - often, "abandoned railway" means that at least ties/sleepers are still there.

**Comment by imagico** [comment]
Closing this since no convincing arguments have been brought forward why former roads should be shown independent of their current function and physical characteristics.
