### ISSUE TITLE
Render name for waterway=dock

### ISSUE THREAD

**Issue by boothym** [gravitystorm/openstreetmap-carto#2557]
I found a previous discussion on #2088 about floating dock rendering, and it was suggested to open a new issue for just the name, so here is that new issue. 

Some docks were recently edited to add the name, but it is not rendered - for example: https://www.openstreetmap.org/way/467652902. I think it should just be rendered the same as other water features.

**Comment by boothym** [comment]
@math1985 (or anyone else who is active here!)

Any chance this change can be made? I'm unsure of exactly what to edit otherwise I'd submit the PR myself (though I wouldn't be able to render it).

**Comment by SomeoneElseOSM** [comment]
@boothym - what would be useful wold be to look at the usage of waterway=dock worldwide and to see what type of "dock" they refer to, since "dock" has different meanings in different varieties of English.  If the same tag is used for physically different features, there's a problem that needs fixing before it can be rendered.
- Andy

(not a maintainer here but mentioning it since I looked at "dock" among other features such as "harbour" for another syle).

**Comment by boothym** [comment]
@SomeoneElseOSM well that's a different issue altogether, which needs some people to go through all the docks to confirm whether they should be piers or not.

However waterway=dock areas are already rendered the same way as water - I just want the name added as well.
