### ISSUE TITLE
Incorrect rendering of an area

### ISSUE THREAD

**Issue by ghost07tula** [gravitystorm/openstreetmap-carto#2571]
For already about a year there is something strange with rendering in this location: http://www.openstreetmap.org/#map=17/55.85612/37.38317 See the screenshot: 
![capture](https://cloud.githubusercontent.com/assets/4715637/23022695/3af03ae6-f463-11e6-8395-c15b3225e5e5.PNG)
If you reload the web page by [Ctrl]+[F5] old tiles are shown in different places each time. Not sure if it is actually related to style or to rendering server cashes, but there is a suspicion that it is somehow related to rendering of natural=water + water=river tags

**Comment by ghost07tula** [comment]
P.S. it's easier to reproduce this on a maximum zoom level

**Comment by imagico** [comment]
Since what you observe are rendering inconsistencies between individual tiles this quite clearly has nothing to do with the style so this is the wrong place for this issue.

Since a lot of things have been edited in the area recently you need to expect this kind of result.  Not every tile your browser is served with is based on the same state of the data.  If the problem persists in the long term (i.e. you get this kind of inconsistency between individual tiles even when nothing was changed for weeks) this might indicate a problem with tile updates in general but so far i see no indication for this being the case here.

**Comment by daganzdaanda** [comment]
Hi @ghost07tula , I think this is a case of a "hiccup" with the changeset http://www.openstreetmap.org/changeset/30659602 
Possibly there was an error when the tileservers for the main style were updated with the data in this changeset, so that the additions, changes and deletions never arrived at the tileserver. 
An example seems to be https://www.openstreetmap.org/way/341791764 which was uploaded 2 years ago and not changed since then. It's in the database and rendered on the humanitarian layer, but not on the main layer.

One possible solution is to move every node a little bit. Then a new update should fix most of the mistakes on the tileserver. 
Some artefacts may remain, though, especially where things have been deleted in the old changeset. I had a similar case a while ago where I used a partial revert to undelete a way from an old changeset, and then deleted it again to bring the tileserver's copy of the database in line with the current database: https://www.openstreetmap.org/way/91295473/history
