### ISSUE TITLE
Parking node without icon when housenumber is tagged

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2586]
When an addr:housenumber is tagged, nodes with amenity=parking show the housenumber instead of the "P" icon. It would make more sense to prioritise the icon, as is done when the parking is mapped as a way. 

Examples:
http://www.openstreetmap.org/node/1540323229
http://www.openstreetmap.org/node/4035219789
http://www.openstreetmap.org/node/795888551
http://www.openstreetmap.org/node/3918195757

**Comment by nebulon42** [comment]
The reason for that is that parking nodes are in the `amenity-low-priority` layer so the address takes precedence.

Maybe it would be good to handle `parking=multi_storey` differently so that this does not end up in the low priority layer. But this would be only possible after the database schema change.

**Comment by jragusa** [comment]
I noticed this issue is partially resolved for underground parking, when fixing to `amenity=parking_entrance`, icon is now displayed.

**Comment by jragusa** [comment]
https://www.openstreetmap.org/node/2493312559
before
![parking_multistorey_before](https://user-images.githubusercontent.com/9897203/50375170-67530380-05f9-11e9-8014-2ea423e4357a.png)
after
![parking_multistorey_after](https://user-images.githubusercontent.com/9897203/50375175-6fab3e80-05f9-11e9-9cf6-a1031905a69a.png)
