### ISSUE TITLE
Construction highways width optimizations

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#2595]
Related to #2477.

Highways under construction (`construction=*`) should have the same width like their finished counterparts (`highway=*`) on a given zoom level.
For example residential highways under construction are much wider on lower zooms than residential roads. See also the image linked in #2477.

**Comment by naoliv** [comment]
While fixing this (the issue with `construction` being wider than `highway`, as we can see in the pictures below), could it also be made less prominent?
As it is now, it draws more attention than the residential highways.
Maybe it could be more faded or have lighter colors?

Zoom level 13:
![](https://user-images.githubusercontent.com/982338/28780102-f6879aca-75db-11e7-82d2-3c4b320d4ef8.png)
14:
![](https://user-images.githubusercontent.com/982338/28780106-fa97cc3e-75db-11e7-965f-24be129863cc.png)
16:
![](https://user-images.githubusercontent.com/982338/28780107-fac3a69c-75db-11e7-9ea9-a2836102bfaa.png)

**Comment by kocio-pl** [comment]
Anybody willing to fix this? Should be rather easy.

**Comment by jeisenbe** [comment]
I've been working on this. It's not a simple fix, because there are multiple issues with the current highway=construction rendering, several of which are hidden by the narrow width of the lines.

1. Highway=construction does not follow proper layering order. Link roads (eg construction=motorway_link) can render on top of construction=motorway, and minor highways sometimes render on to of major highways. The layering order will sometimes reverse between different zoom levels.

- This might need a new SQL query to fix. I'm not yet competent in this area. 

2. The current yellow highway=secondary fill is quite light, and it can be hard to see construction=secondary at z12 and z13. This is also noticeable with a wider line at low zoom levels

- #3540 will improve this, but the problem would still be noted with construction=tertiary. However, we could render construction=secondary and =tertiary later and use a grayish casing instead of white. 

3. Highway=construction with construction=null or =road and =track, =footway, etc currently render with a dark blue-gray color, which can look quite similar to an intermittent stream or river. 

- I would recommend changing this to the same gray used for minor highways under construction (#aaa)

4. Dashed white and colored lines are quite prominent. This is problem is reduced at high zoom levels currently, because highway=construction is rendered much narrower than major highways (motorway thru tertiary). It is very obvious right now with highway=service vs construction=service at z14 to z16, and with highway=residential vs construction=residential. If we make the motorways thru primary wider at lower zoom levels, they will appear very prominent.

- This could be fixed for motorway thru primary by using light gray instead of white for the dashes, and adjusting the length of the dashes vs the fill color. 
- However, this is harder to fix for secondary highways, where the lightness is high, and for minor highways which are rendered in white

Should I open a new issue for these problems, or just address them in the PR?

**Comment by kocio-pl** [comment]
In general I like more compact code, but your code is usually packed with changes, so I prefer more independent PRs. But you may discuss problems here, I guess.

**Comment by jeisenbe** [comment]
One more issue:

5. Highway=construction with construction=road, =pedestrian, =living_street and =raceway currently render starting at z12. In fact, all highway=construction without construction=* are rendering at this level, and all unspecified values of construction=* get rendered at z12. This should be changed, so that only known values of construction=* are rendered, and no sooner than z15.

**Comment by jeisenbe** [comment]
I've opened a PR to address the main issue: small roads render wider than they should. This PR will also address: 3. "Highway=construction with construction=null or =road and =track, =footway, etc currently render with a dark blue-gray color, which can look quite similar to an intermittent stream or river," and 5." Highway=construction with construction=road, =pedestrian, =living_street and =raceway currently render starting at z12. In fact, all highway=construction without construction=* are rendering at this level, and all unspecified values of construction=* get rendered at z12".

I believe this PR (#should close this issue; I will open a new issue for the remaining problems with highway=construction rendering that I mentioned recently, #3579
