### ISSUE TITLE
railway:preserved=yes + railway=rail not rendering as preserved

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#2615]
There will be more and more use of this tag so that one can also add what kind of preserved railway it is.
Basically railway:preserved=yes + railway=*

Suggest add this in so that it will work like the more common railway=preserved.

Better option would be to just move over to railway:preserved=yes only to encourage better tagging.

**Comment by Lukas458** [comment]
I support this suggestion. If the preserved railway tracks are "rail tracks" (railway=rail) with a "normal" gauge like 1435 mm in germany for example, it would be very good idea to render this (railway=rail + railway:preserved=yes) in the same way like railway=preserved. The OSM community accepted this as a general more actual practic for tagging preserved railways with default-gauge. But this should only be then, if the preserved railway is really "rail", and not something like "tram", "subway" etc.

**Comment by Gazer75** [comment]
Old one, but I've noticed the above tagging is rendered as the old railway=preserved if the section also have a tunnel tag it seems. Any progress on this problem?

**Comment by jeisenbe** [comment]
The original tag `railway=preserved` is still nearly twice as common (~10k vs ~6k), but it has not increased in usage for several years, while `railway:preserved=yes` is increasing at over 1000 objects per year, so it may become more common in ~2 years. 

It would not make sense to render all `railway:preserved=yes` features the same as a `railway=preserved`, because several hundred have tags like `railway=razed`, `railway=abandoned`, `railway=disused` and `railway=construction:` http://overpass-turbo.eu/s/RB8

Also, it might be better to render the `railway=*` style for those that are combined with `railway=funicular` or `railway=miniature`. 

Should `railway=narrow_gauge` + `railway:preserved=yes` be rendered as "narrow gauge" or as "preserved"?

The main case seems to be `railway:preserved=yes` + `railway=rail` - which currently renders like a major railway (`railway=rail` with no service tag). That is misleading.

**Comment by Gazer75** [comment]
Combination of railway:preserved=yes and railway values like abandoned, razed abd disused are not valid obviously. Construction might be an ok combination if its like a repair of a line like this.
Its supposed to be used on heritage lines that (usually) have seasonal traffic for tourists or for groups that order a trip.
IMO any line like that no matter the gauge should be rendered as a preserved line. It is kind of the reason for the railway:preserved=yes tag, so that the railway=* can be free to describe the rail.
It will visually indicate that it is a heritage/tourist attraction line in operation.

**Comment by DaveF63** [comment]
I support this proposal for the reasons state here:
https://wiki.openstreetmap.org/wiki/Tag:railway%3Dpreserved#Alternatives_to_railway.3Dpreserved

Being less popular than railway=preserved isn't a reason for it to not be rendered. It clearly has tagging advantages.

**Comment by jdhoek** [comment]
`railway:preserved=yes` is now the more popular option. [A proposal is underway](https://wiki.openstreetmap.org/wiki/Proposed_features/Discourage_railway%3Dpreserved) to actively discourage the use of `railway=preserved`.

A good start may be to at least render `railway=rail` + `railway:preserved=yes` in the same way as as `railway=preserved`.

**Comment by DaveF63** [comment]
I'm interested to know why this request has not been acted upon in over 5 years.

IMO there's no requirement for discussion as the two tagging schemas are for exactly the *same* feature.

`railway=preserved` will still be rendered.

`railway=rail + railway:preserved=yes` is clearly more popular.

https://taghistory.raifer.tech/#***/railway/preserved&***/railway:preserved/yes

Even if it wasn't, rendering it would make no difference as it's the *same* feature. 

It seems illogical to render the *same* feature two different ways.

**Comment by Gazer75** [comment]
Funny thing is the rendering works if there is tunnel tag as well. No idea why this is still not fixed...
The old railway=preserved is dying slowly, but as long as carto keep rendering that tag differently it will not die.

**Comment by hiddewie** [comment]
I have prepared a pull request to correct the rendering for `railway = rail` combined with `railway:preserved = yes` in https://github.com/gravitystorm/openstreetmap-carto/pull/4965.
