### ISSUE TITLE
Shop rendering suggestion

### ISSUE THREAD

**Issue by MaestroGlanz** [gravitystorm/openstreetmap-carto#2619]
You might think "Oh no, not again." 

I read a bit into #2444, but I don't think my ideas fit into the discussion.

I can do programming, but I dont know, how osm-carto works. Therefore I might suggest things already implemented. 

1. osm-carto should not limit the shop icons. If something is forked from it, this maybe useful (i.e. an interactive shopping map).
2. osm-carto should only map the 20 (or what-number-ever) most often shops (see https://taginfo.openstreetmap.org/keys/shop#values)
3. Which kind of shops are or arent mapped should be determined by a stylesheet (list of booleans). For every zoom level, there can be another stylesheet. i.e. on zoom level x only the 5 most often mapped shop types are rendered.
4. Introduce another highest zoom level with the same zoom of the highest level. If you enlarge it to the largest (and most detailed size), it renders simplified. If you zoom in once again, it doesnt enlarge anymore, but shows the shop icons. This is just an idea.

In addition, I have several icon contributions:
[On my wiki user page](https://wiki.openstreetmap.org/wiki/User:MeastroGlanz)
- There should be definitely a ruins icon. I can add a ruins icon for things like houses and churches, if requested.
- tyre shops and funeral directors are one of the more frequent shops
- the perfumery icon is an alternative since the current one contains particles which affect the readability.

**Comment by dieterdreist** [comment]
sent from a phone

> On 24. Apr 2017, at 13:17, MaestroGlanz <notifications@github.com> wrote:
> 
> There should be definitely a ruins icon.


-1 for the ruins icon. IMHO an icon would make ruins too prominent, there could rather be a special rendering for building=ruins.

Ruins is such a generic term that you can't determine significance of the individual feature from it, all you know is that something isn't working/functioning any more, which means that it likely isn't interesting for many people.
In case of significant ruins they are mostly better tagged as or within an archaeological site anyway

**Comment by MaestroGlanz** [comment]
I agree on that. building=ruins shouldn't be rendered, because there are too many meaningless ruins. But imho building=castle;ruins=yes should be rendered that way. Most (german) maps differentiate between several types of sights (church, castles and abbeys) and have a corresponding ruins icon for every type.

**Comment by HolgerJeromin** [comment]
Please open only one issue per request. Ruins/castles are handled here: #744 #331

**Comment by imagico** [comment]
Hello MaestroGlanz, thank you for the suggestions but please separate different subjects into different issues - ruins have nothing to do with shops and should not be discussed in the same issue.  What shops to show at which zoom level is also fairly separate from what types of shops to show at all.

Otherwise your suggestion four is outside the scope of of this project, this would involve larger changes in the rendering framework and in map display on the website.

Design wise we quite definitely do not want to decide on priorities purely based on how frequently things are mapped.  While normally mappers tend to map things important for them with priority there are many cases where important types of features (like types of shops) are fairly rare in reality while less important ones are more frequent so with that approach you would often get a map that is not very useful.  There are also other influences that distort mapping frequency like imports and visibility differences and there is an immense cultural bias in this approach as well (most mapping is done in Europe so shop types rare in Europe but frequent and important elsewhere would not have a chance in global statistics).

**Comment by kocio-pl** [comment]
Most of your icons look nice for me, but are not readable in 14px, which unfortunately is how they appear on the map. I have some hopes only for shop=funeral_directors and I believe shop=tyres is good enough for osm-carto.

**Comment by kocio-pl** [comment]
I will close this issue, since it contains many problems, which makes this ticket hard to manage and discuss. Please fill individual tickets for each of them.
