### ISSUE TITLE
Drop name attribute from layers

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2626]
The version of CartoCSS Kosmtik comes with complains that

```
Warning: using the name attribute for layers (like building-text here) is deprecated and will be removed in 1.0.0. Use id instead.
```

Are we specifying a high enough minimum version (0.16.0) to drop this attribute?

**Comment by nebulon42** [comment]
No, this was introduced in 0.17.0. Since seemingly I'm not able to release a CartoCSS version without regressions the next version will be 1.0 instead of 0.18.

I would like to elevate the minimum version to 0.17, since there is also a new feature that allows to specify some attributes with `none` which would save use some duplicated code. But I refrained from suggesting it since I'm not sure how much of hassle it would be for downstream projects and it would require us to increase the major version again.

**Comment by pnorman** [comment]
I'd be okay with bumping to 0.17 for 4.x. I don't think it's an issue for anyone who's already meeting our requirement of 0.16.

**Comment by nebulon42** [comment]
I will try to release a new version shortly before we tag 4.x. Most likely 0.18. So we can fix it to that and benefit from the latest improvements.

Yes, upgrading carto from 0.16 to another version would be no problem for anyone that already has 0.16.

**Comment by pnorman** [comment]
Do you think you'll do this soon enough to fit it into 4.x?

**Comment by nebulon42** [comment]
Yes, I had some more plans for the next version. But I think I will just release 0.18 as it is now in master.

**Comment by math1985** [comment]
We have forgotten to specify this dependency change in the release notes and the communication to the OWG.

**Comment by sommerluk** [comment]
Not sure why, but I still see the warning message on my computer…

**Comment by nebulon42** [comment]
@sommerluk I guess that depends on the version of Kosmtik you use. See https://github.com/kosmtik/kosmtik/pull/242.

**Comment by sommerluk** [comment]
Ok, thanks.

2017-08-22 21:01 GMT, Michael Glanznig <notifications@github.com>:
> @sommerluk I guess that depends on the version of Kosmtik you use. See
> https://github.com/kosmtik/kosmtik/pull/242.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/gravitystorm/openstreetmap-carto/issues/2626#issuecomment-324150485


-- 
Lukas Sommer
