### ISSUE TITLE
Render trees before streets

### ISSUE THREAD

**Issue by ftrebien** [gravitystorm/openstreetmap-carto#2665]
Trees placed close to streets end up rendered on top of them, sometimes resulting in something similar to [this](https://github.com/gravitystorm/openstreetmap-carto/pull/2394#issuecomment-261665117). Some examples include [here in Paris](https://www.openstreetmap.org/#map=17/48.88130/2.28550) and [here in Berlin](https://www.openstreetmap.org/#map=17/52.49525/13.42066).

Regardless of whether trees are being mapped as intended, I think trees are more relevant at high zoom levels, in which they usually don't overlap with streets. So it's probably safe to render them before streets, at least at lower zoom levels. What do you think?

The same logic probably applies to tree rows too, like [here in Amsterdam](http://www.openstreetmap.org/#map=17/52.35018/4.89153). It seems that mappers have tried to work around this by mapping tree rows as forest areas, like [here](https://www.openstreetmap.org/#map=19/52.36178/4.85099).

**Comment by imagico** [comment]
Trying to give a bit of context here: We deliberately draw roads in an abstract width which is wider than they are in reality at all but the highest zoom levels.  Same also applies to trees and tree rows.  Doing this is normal in maps but usually requires moving the objects (a process called _Verdrängung_ in German - not sure if there is an exact equivalent term in English).  We can't do that because it is technically difficult to do so automatically and it would severely affect mapper feedback - hence we inevitable get overlaps.  This is not specific to roads and trees, we also get this with lots of other stuff.

I think as a general rule we should in such cases preferably draw the smaller objects above the larger ones - which in this case as it is currently rendered and which is also kind of the intuitive order - unless there is a bridge trees are located above roads.

With a different drawing order you would also end up with partial trees which are difficult to interpret for the map user (what does a green half circle symbolize again?)

**Comment by Circeus** [comment]
This is really a debate on the zoom level at which trees ought to be displayed (cf. issue #838 ). There's going to be complain no matter the zoom level.

**Comment by ftrebien** [comment]
Interesting. Maybe one possible solution is to make trees (and tree rows) fainter at zoom level 17 (like in OSM-FR) and fainter still - or not rendered at all - at level 16.

**Comment by matkoniecz** [comment]
> a process called Verdrängung in German - not sure if there is an exact equivalent term in English

In Poland it seems to be considered as part of something that has English name "cartographic generalization".

**Comment by matkoniecz** [comment]
I also think that the only thing that can be done here is too make trees fainter/smaller/invisible on list zoom levels, changing order is going to introduce more hard interpret symbols.

**Comment by math1985** [comment]
> Maybe one possible solution is to make trees (and tree rows) fainter at zoom level 17 (like in OSM-FR) and fainter still - or not rendered at all - at level 16.

+1. Trees are currently too prominent, with more and more trees being added.

**Comment by matkoniecz** [comment]
And maybe it would be feasible to show important trees earlier (name, maybe also things like presence of tags like tourism=attraction or Wikipedia tag - though it is tricky, denotation tag is not too useful and physical size is not helpful at all).

**Comment by matthijsmelissen** [comment]
https://www.openstreetmap.org/#map=18/49.62184/6.15306

**Comment by dieterdreist** [comment]
sent from a phone

> On 24. Apr 2018, at 19:29, Matthijs Melissen <notifications@github.com> wrote:
> 
> https://www.openstreetmap.org/#map=18/49.62184/6.15306
> 


works for me, I’d rather add them (less prominently) in z17 than removing them from z18. I believe it is right we show the trees in this zoom level and context, they are a significant part of the road and contribute significantly to the appearance of the space. With their green color they are not in concurrency with the highways

**Comment by jeisenbe** [comment]
Closing, we had several comments against this idea. However, there was support for rendering trees smaller at the lower zoom levels, so that idea could be tried as a PR or opened as a new issue.
