### ISSUE TITLE
render vehicle=destination as the same as access=destination

### ISSUE THREAD

**Issue by Lukas458** [gravitystorm/openstreetmap-carto#2690]
I think, mapnik should render vehicle=destination either instead of or at least as the same as access=destination. In OpenStreetMap, we actually have the problem that access=destination is often tagged wrong and it would be vehicle=destination right. We need to avoid "mapping for the renderer", so I think it would be a good idea to render vehicle=destination on corresponding highways.

**Comment by HolgerJeromin** [comment]
This would make this style "osm carto" (mapnik is only the render software) car centric...

**Comment by Lukas458** [comment]
Hmm, okay. I understand this but I'm askig myself then, why there is a special rendering for highways like residentials which are tagged with "access=destination". In most cases (I'm sure more than 98 per cent) "access=destination" is tagged wrong or better to say it is tagged only for the renderer, and vehicle=destination or motor_vehicle=destination is / would be the only right, as I said before. The thing is, there are very few ways which are accessible only by "destination" for all road users, including pedestrians. I'm not sure then, whether acess=destination is worth rendering anymore. "destination" is not a really "access" tag, it is used mostly with "vehicle".  Does anyone also think it would make sense not to render "access=destination" anymore?

**Comment by Lukas458** [comment]
I mean, some other "access" values like "access=delivery" oder "access=customers" are also not rendered, although they are used very currently and in most cases there, the "access" key is CORRECT, in contrast to "destination". My question is, why "destination" is then worth rendering, when something like "delivery" or "customers" as access-tags are not rendered. The two values I just mentoined restrict the general access for, lets say highways, in a similar way like "destination". Does anyone understand what I mean?

**Comment by daganzdaanda** [comment]
> Does anyone also think it would make sense not to render "access=destination" anymore?

Yes, see for example @simonpoole in https://github.com/gravitystorm/openstreetmap-carto/pull/2257#issuecomment-240955651 and the linked issue #214
It really is a messy business... and I agree with you that access=* is very often used wrong.

We could decide to drop all hints of access restrictions, because they are not reliable and too complex for the main map. But then there would be no "mapper feedback", which is one of the goals that this map style has.

We could try to show a different rendering for different restrictions. This is very hard and probably will look bad and be hard to understand for the user, but it would maximise mapper feedback.

We could show all access restrictions in the same style. This would still give some feedback, it would probably look not too bad, but it would also be pretty useless or even confusing for the viewers of the map (think of bicicle=no on a big street).

We could try to show more than just access=no and delivery, but not all restrictions. Making this choice is hard (car vs other uses?), but it might lead to a useable compromise. (Which in turn might again lead to tagging for the renderer.) 

Showing or dropping restrictions depending on the type of road or other tags might be a cool thing to try but it would be really too complicated and not worth the code complexity for this style.

**Comment by Lukas458** [comment]
Tanks for your comment and the link. The linked discussion seems to be interesting.

**Comment by Lukas458** [comment]
closing this issue because the headline "render vehicle=destination as the same as access=destination" does not lead to any rsult. access is a big issue to discuss, but not here (anymore). My originally idea is a wrong thing, I see and doesn't have to be discussed further, so this issue has not to be open anymore.
