### ISSUE TITLE
Render waterway=drain + location=underground equivalent to waterway=drain + tunnel=yes

### ISSUE THREAD

**Issue by flacombe** [gravitystorm/openstreetmap-carto#2720]
Hi,

tunnel=yes isn't always appropriate to tag a drain/stream/river going underground. Just because tunnel=yes may be understood to be an actual drain inside a tunnel where humans can go.

I use to tag underground drains as waterway=drain + (man_made=pipeline) + location=underground without any tunnel tag.
https://www.openstreetmap.org/way/243333009

It makes them appear on OSM Carto like overground ones.
I find location=undergound enough to show them with dashes

Thank you in advance to consider this potential issue

**Comment by mboeringa** [comment]
I think you should be adding **tunnel=culvert** to this type of feature if you consider it a true waterway, and not just a pipeline:

http://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dculvert

This is the tag designed for this situation of "covered-but-not-human-accessible-tunnel", and is quite unambiguous in meaning no human access.

I know, culverts are generally not that long, but the difference between a pipeline and culvert is essentially meaningless once you start tagging pipelines with waterway tag as well, and expect to see it rendered on the map.

**Comment by gustavecha** [comment]
Hi, thank you for your answer.

I would agree with tunnel=culvert particular definition.
By the way, tunnel key also indicates "For a structure that carries water or another liquid some considerable distance then it may be more appropriate to tag it as a pipeline using man_made=pipeline."
That's why I'm using man_made=pipeline, because the feature I took as an example is about 14km long.

I was looking last year a good way to distinguish water carrying tunnels (very low slope, long distances) and penstocks (high slope, short distances near a hydraulic power plant).
Pentsocks are of course tagged with man_made=pipeline but according to tunnel's definition, water carrying galeries had to also.
tunnel=culvert can make the difference I was looking for.

Anyway, it would be great to render location=underground like tunnels in main render.

**Comment by pnorman** [comment]
With under [1k uses](https://taginfo.openstreetmap.org/tags/waterway=drain#combinations) and other ways to tag it, this seems like a tagging error and not something we'd want to render.

**Comment by gustavecha** [comment]
I agree it's not a well used combination of tags but it doesn't make it semantically wrong.
Furthermore, it's easier to tag overground features than underground ones, and location will be implicit for overground (but any overground river CAN be tagged with location=overground).

I've heard of some speleologists who tracks underground rivers (let's say waterway=stream), but no tunnel because water is flowing between bedrock, siphons and so on. Their work will be rendered as overground river :(

There are +2k use of waterway=* in combination with location=*
https://taginfo.openstreetmap.org/keys/waterway#combinations

Then what does it take to add location=underground beside tunnel=* in your style sheet for waterway=* ways ?

**Comment by mboeringa** [comment]
As I said before, add **tunnel=culvert** if you really want to see this feature in the map displayed as a waterway instead of pipeline. 

You clearly do **not** consider this a pure "pipeline" case (which often also would imply active pumping, versus the likely gravity fed nature of this feature), so tunnel=culvert seems applicable.

This should be rendered on the map right now without requiring any modifications to the style.

**Comment by gustavecha** [comment]
I got your point regarding tunnel=culvert but tunnel=* key won't cover all cases of underground water flows.

That's why I think rendering location=underground just like tunnel=* on waterways can be a more sustainable fix for this issue than editing data and add tunnel=culvert.

The pipeline=* key on the feature doesn't regard the underground location. It's relative to penstock scheme for power plants.
Anyway, pipelines aren't rendered in carto and it's not my point to change this.

**Comment by pnorman** [comment]
> Then what does it take to add location=underground beside tunnel=* in your style sheet for waterway=* ways ?

Established use.

**Comment by dieterdreist** [comment]
sent from a phone

> On 10. Aug 2017, at 18:35, Gustave <notifications@github.com> wrote:
> 
> That's why I think rendering location=underground just like tunnel=* on waterways can be a more sustainable fix for this issue than editing data and add tunnel=culvert.


+1, waterways can run underground besides actual tunnels or culverts, e.g. in a cave. Adding tunnel=culvert to the latter would be plain wrong. I wouldn't expect too many of these mapped, so less than 1K is not necessarily a problem.

**Comment by mboeringa** [comment]
> +1, waterways can run underground besides actual tunnels or culverts, e.g. in a cave. Adding tunnel=culvert to the latter would be plain wrong. I wouldn't expect too many of these mapped, so less than 1K is not necessarily a problem.

While I basically agree with this statement, there remains the question whether the style should render ***any*** possible form of underground waterway, or just specific ones, like man made culverts. 

E.g. adding rendering for a rather generic location=underground, could, as you say, potentially lead to quite a number of complicated and potentially deep "natural" cave systems being mapped. That by itself may not be an issue, but the rendering in a specific style like this one might be.

This is just an open question: would it be acceptable to see some intricate underground carst waterway system being displayed over e.g. a dense city center?

If not, than sticking with specific man made "tunnel" type underground waterways / culvert may be better. The other types would then be for dedicated styles or dynamic overlays.

**Comment by matkoniecz** [comment]
For things like 10+km underground pipes or carst waterway system (thanks @mboeringa for great and scary example) any type of special rendering that makes sense is removing them from map.

And I guess that waterway = drain on https://www.openstreetmap.org/way/243333009 is tagging for renderer and is not correct.

**Comment by gustavecha** [comment]
As underground features, impact on surface urban buildings would be low (since landuse=residential can hide them.
The point is to show them when noting else can be seen.

I never tag for renderer, and waterway=drain is intended to include this high flow feature into the waterway topological graph. A whole river is diverted inside it, then if the diverted river is rendered, we must render the tunnel since pretty all water goes inside it.

It's a two component data model :
* waterway for water flowing system, and drain is the most valid value for it
* man_made pipeline to let know it's a man_made structure designed to carry fluids.
* tunnel culvert can be a third component for the design of the man made infrastructure but doesn't prevent to use man_made=pipeline

**Comment by matkoniecz** [comment]
> A whole river is diverted inside it

In that situations usually waterway=river is used

**Comment by gustavecha** [comment]
No because the natural river contnues to exist.
The point is to divert a major part of it (without remove it from the natural environment) to feed an hydraulic power plant.

Then, the river : https://www.openstreetmap.org/relation/1067839
and the diversion, which is not a river : https://www.openstreetmap.org/way/243333009

**Comment by dieterdreist** [comment]
sent from a phone

> On 11. Aug 2017, at 22:27, mboeringa <notifications@github.com> wrote:
> 
> This is just an open question: would it be acceptable to see some intricate underground carst waterway system being displayed over e.g. a dense city center?


yes, in some cases this is not wanted, but then we will have to actively omit those waterways, because ignoring the location tag would lead to these waterways rendering as if they were on the surface

**Comment by gustavecha** [comment]
A recent waterway tagging improvement add a nice tunnel=flooded value to map underground water conduits. As it covers many situations where tunnel=culvert wasn't suitable and make tunnel=yes less acceptable for waterways, this would make everyone happy regarding this issue.

See https://github.com/gravitystorm/openstreetmap-carto/issues/3179

**Comment by jeisenbe** [comment]
@flacombe it looks like we can close this issue in favor of #3179 - which will be reopened once tunnel=flooded becomes more widely used. 

I don't believe it is a good idea to render all kinds of underground canals, drains, rivers and streams which are not in tunnels or culverts, because their location is rarely verifiable. See #3349 which was also closed.

**Comment by flacombe** [comment]
Ok for me, recommended usage of waterway=drain has been converted to waterway=canal with the introduction of tunnel=flooded.
Relevancy of this issue is lower now.
