### ISSUE TITLE
Tramway tracks are rendered wrong when comined with a psv road

### ISSUE THREAD

**Issue by menzo2003** [gravitystorm/openstreetmap-carto#2781]
In Amsterdam there are lots of tramways that are paved where next to trams only psv vehicles are allowed.

The tags are commonly: 
access=no
electrified=contact_line
frequency=0
gauge=1435
highway=service
oneway=yes
psv=yes
railway=tram
voltage=600

Up till recent it was rendered as a road with a black line trough the middle. Now it is sometimes rendered as a road with access=no (dashed white road)

This is a good example of the problem: 
http://www.openstreetmap.org/#map=18/52.36308/4.87601

**Comment by math1985** [comment]
@pnorman Could this have been introduced by #2732?

**Comment by pnorman** [comment]
I'm not able to reproduce. I went into my database and set one row to have
```
┌─[ RECORD 1 ]──────┐
│ highway │ service │
│ railway │ tram    │
│ oneway  │ yes     │
│ access  │ no      │
└─────────┴─────────┘
```

I'm not too surprised to see problems with ways tagged with both highway and railway tags, they've always been a headache and most maps don't handle them.

Since I can't reproduce it, I can't bisect, but I'm guessing it comes down to ordering, differences between the two times the road is selected, but not in the roads fill or casing layers.

**Comment by kreed** [comment]
This is a regression from #2732. Both features have the same z_order because they are created from the same database row, so the ordering is now undefined.

Same problem occurs with combined highway/taxiways

**Comment by pnorman** [comment]
> This is a regression from #2732. Both features have the same z_order because they are created from the same database row, so the ordering is now undefined.

Perhaps the easiest solution is to add `feature` to the sort

**Comment by dieterdreist** [comment]
sent from a phone

> On 27. Aug 2017, at 20:29, menzo2003 <notifications@github.com> wrote:
> 
> The tags are commonly:
> access=no
> electrified=contact_line
> frequency=0
> gauge=1435
> highway=service
> oneway=yes
> psv=yes
> railway=tram
> voltage=600


are there separately mapped footways or other parallel roads? Maybe not a big issue (because nobody likely does tram-routing), but I think you are excluding trams with this tagging (one might argue they are psv, but the wiki doesn't seem to define it like this, and there are typically also non-psv trams (not in service or maintenance vehicles)). Rather than access=no you could add vehicle=no (according to the wiki, vehicle doesn't contain trams)

**Comment by SomeoneElseOSM** [comment]
http://www.openstreetmap.org/user/Yevgeshik/diary/42210 may be an example of a similar issue in Riga.
