### ISSUE TITLE
can't use multiple mss file

### ISSUE THREAD

**Issue by nafis042** [gravitystorm/openstreetmap-carto#2814]
I opened my project on tilemill and create different styles by changing style.mss file and its working fine. Now I have more .mss files like shapefiles.mss, roads.mss etc. But the styles written on those file is not working. But when I copy that style code into style.mss then its working.I checked my project.mml file and there all the .mss files are written in this way:
```
  "Stylesheet": [
    "style.mss",
    "fonts.mss",
    "shapefiles.mss",
    "landcover.mss",
    "water.mss",
    "water-features.mss",
    "road-colors-generated.mss",
    "roads.mss",
    "power.mss",
    "placenames.mss",
    "buildings.mss",
    "stations.mss",
    "amenity-points.mss",
    "ferry-routes.mss",
    "aerialways.mss",
    "admin.mss",
    "addressing.mss"
  ],
```
But only those that are inside style.mss are working. how can I reference those mss file so that all the mss code are not written inside style.mss?

**Comment by pnorman** [comment]
Tilemill is [not supported](https://github.com/gravitystorm/openstreetmap-carto/blob/ebbde69f7836713b92aa84dd82c7113f4ae039db/INSTALL.md#dependencies)

In particular, editing through the Tilemill UI instead of an external text editor is going to be a problem. Anything that changes `project.mml` will force it to be rewritten in JSON, which is what seems to have happened here. You'll also be unable to edit all of the MSS files through its UI on most monitor widths.

If you do use Tilemill, make sure that you're using a version from source, not a released one.

**Comment by nafis042** [comment]
okay so now I need help. I want to have a map of my own. I have a postgis database and then I have osm carto. Now how can I export a map like osm? can anybody please guide me through or give me any link of tutorial? I saw a tutorial which uses tilemill to do that but that's not working in my case.

**Comment by SomeoneElseOSM** [comment]
https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ is a "how to set up a map like OSM" guide.  I'd also thoroughly recommend the various guides at https://ircama.github.io/osm-carto-tutorials/ .  For "live" help, ask in one of the OSM IRC channels such as #osm-dev .
