### ISSUE TITLE
Please display amenity=public_bath on the map

### ISSUE THREAD

**Issue by SelfishSeahorse** [gravitystorm/openstreetmap-carto#2856]

**Comment by kocio-pl** [comment]
How should it be displayed?
We have 1332 uses and a wiki page:

https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dpublic_bath

**Comment by SelfishSeahorse** [comment]
Just the name would suffice. It is currently only displayed when public_bath is combined with building, but not when on a separate node or area. Maybe the same icon iD uses for public_bath could be used?

By the way, there are many thermal baths wrongly tagged as swimming_pool or water_park (presumably because their names aren't displayed otherwise) so the number of uses would certainly increase if public_bath were rendered.

**Comment by RobJN** [comment]
Having been to Japan this year for sotm, I can see how this would be useful for Japan (assuming they tag onsens this way). All the tourist maps showed these as significant map features.

**Comment by kocio-pl** [comment]
> Just the name would suffice. It is currently only displayed when public_bath is combined with building, but not when on a separate node or area.

I'm not sure how to display it as an area, but I would rather display general brown dot than just a name to show it's more pointy feature.

> Maybe the same icon iD uses for public_bath could be used?

I will check that later.

**Comment by SelfishSeahorse** [comment]
Or maybe something like this could be used as icon:

![public_bath](https://user-images.githubusercontent.com/14875493/30823133-83c0bee6-a22b-11e7-9c94-361fbb08b239.png)
[public_bath.svg.txt](https://github.com/gravitystorm/openstreetmap-carto/files/1330349/public_bath.svg.txt)

**Comment by kocio-pl** [comment]
Nice idea, but what color should we use then - brown probably?

**Comment by SelfishSeahorse** [comment]
I don't know your guidelines, but brown seems to be fine.

**Comment by kocio-pl** [comment]
In general (social) amenities are brown, but I wonder if other color would not work better in this case. It can be also other icon design, like bathtub with two simplified persons (like in a playground or prison for example). Could anybody test them and try how the icons look like on the rendering?

**Comment by HolgerJeromin** [comment]
Is a bath not a leisure thing and could be colored green?

**Comment by kocio-pl** [comment]
We should test. I guess proposed symbol is so abstract, that can be hard to recognize without proper color (like blue), but bathtub might be different color wise.

**Comment by RobJN** [comment]
In Japan there seemed to be a pretty universal symbol which is close to the proposed but the bath is circular. These were seen as an amenity so brown would be ok but I think blue works well too.

![onsen](http://selected-ryokan.com/wp-content/uploads/2016/07/1ac1ace9123a70397a66e07dd10e976f.jpg)

**Comment by MKuranowski** [comment]
Hi, so I actually did some work on this - I prepared two icons:

* The standard Japanese onsen icon: 
![steam](https://user-images.githubusercontent.com/16469272/36068291-5b27931a-0ed2-11e8-9c97-e7c634d26779.png)

* And, as an experiment "a person in water" icon:
![man](https://user-images.githubusercontent.com/16469272/36068312-afd3c3f2-0ed2-11e8-9545-962e0025c49f.png)


Here are exmaple renderings with the onsen icon:
![steam_blue](https://user-images.githubusercontent.com/16469272/36068330-2dd43eda-0ed3-11e8-8cfa-7553e0d88d21.png)
![steam_brown](https://user-images.githubusercontent.com/16469272/36068331-2df1fe66-0ed3-11e8-9b7b-aef124c0a6ae.png)
![steam_green](https://user-images.githubusercontent.com/16469272/36068332-2e11a07c-0ed3-11e8-8bc8-b5f7ff1e35e5.png)


With the "experiment" icon:
![man_blue](https://user-images.githubusercontent.com/16469272/36068342-917ef178-0ed3-11e8-99c5-a2193a50d98d.png)
![man_brown](https://user-images.githubusercontent.com/16469272/36068343-919d9b0a-0ed3-11e8-8131-c81804e37dad.png)
![man_green](https://user-images.githubusercontent.com/16469272/36068344-91be58c2-0ed3-11e8-9fa2-da6c4b579159.png)


I personally would go for the brown-onsen icon, but it's open for discussion :)

**Comment by kocio-pl** [comment]
Thanks! While both icons are nice, I like experimental icon more, because it's less abstract and not tied to Japan (for example Iceland [is also known for such amenities](https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dpublic_bath#Icelandic_hot_baths)). However I think the space between water line and a person shape should be bigger to make them distinct.

Brown works the best for me - this shade of blue is about transport/journey and green is more about physical activity, while this amenity is about resting.

**Comment by matthijsmelissen** [comment]
>  I like experimental icon more, because it's less abstract and not tied to Japan

+1

**Comment by MKuranowski** [comment]
Hmm, is this ok, or should I add even more space?
![man](https://user-images.githubusercontent.com/16469272/36078602-3f59761a-0f79-11e8-9f56-d9ad49e1a0e8.png)

Rendering:
![rendering_2](https://user-images.githubusercontent.com/16469272/36078681-3e294706-0f7a-11e8-9f94-867c52932f37.png)



And, I'm sorry @Tomasz-W, but I kind don't get what you mean by "a little bit of space between body and shoulders". Do you literally mean a white box between body and arms?

**Comment by kocio-pl** [comment]
Thanks, now the space is OK for me!

Current shape of man has no visible space between shoulders and body, adding a narrow gaps would make it more clear probably. If you're not sure what do we mean, just publish the vector icon as gist so we could modify it.

**Comment by MKuranowski** [comment]
I'm still kinda not sure, so just to be safe, I have uploaded it here...:
https://gist.github.com/MKuranowski/d43f172510d9a1908615c00150b5b596

**Comment by kocio-pl** [comment]
Thanks - I meant something like this:
![public_bath-1](https://user-images.githubusercontent.com/5439713/36079007-80620e1a-0f7e-11e8-8d6c-2b5b901b2210.png)

It would be good to make this shape more pixel aligned and symmetric (currently it's a bit shifted and made of parts) - could you fix it?

**Comment by MKuranowski** [comment]
Oh, I see now, thanks!

So I tried making it more aligned, but still the arm separators and the head is ¼ px off, otherwise the icon started looking wired...
![man](https://user-images.githubusercontent.com/16469272/36079729-87fe8db2-0f86-11e8-994b-c31c579e8d83.png)

(Aligned to full pixel, for reference only:)
![man_fullyaligned](https://user-images.githubusercontent.com/16469272/36079733-9074f9c2-0f86-11e8-8c81-85bd8fc3cbc3.png)

I'll squash it into one path just before PR, it makes it easier to edit the icon like this 😃.

**Comment by kocio-pl** [comment]
Great! Pixel aligning is good to have, but most of the times the matrix is too small, so it's not always possible if we want some meaningful shape. First image is nice (at least at this scale), so we can go on with it. Since I find it to be mostly complete solution of this issue, could you prepare a pull request?

BTW: I have also found mikveh tagged this way, which is a ritual in Judaism, so this icon is better than just a Japan hot bath symbol.

**Comment by MKuranowski** [comment]
So, PR created 😄

**Comment by polarbearing** [comment]
double bath
<img src="https://cdn.rawgit.com/polarbearing/e4784fc736fbeb3e8eb47b935e92aa7b/raw/40a766a3c4f02d6b9b9b6b8dfb9b4656056d1da9/bath_double.svg">
