### ISSUE TITLE
Consider usage=* for railways?

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2859]
I saw this and am not sure if it's a tagging error or an error on our side:

![e6090a66-d97f-4fd2-8269-b7c595b6f158](https://user-images.githubusercontent.com/7693297/30744234-77ce32a8-9fa1-11e7-8877-a14e6fb9e693.png)
https://www.openstreetmap.org/#map=11/48.2530/10.8133
![1c68f3a4-e5a6-4035-b22f-81af05f9335b](https://user-images.githubusercontent.com/7693297/30744275-9a5c87c0-9fa1-11e7-8f5d-bf51fa12f43d.png)
https://www.openstreetmap.org/#map=15/48.2634/10.8254

The [tracks in this industrial area](https://www.openstreetmap.org/way/211749891) are tagged with railway=rail and usage=industrial

The [wiki on usage=*](http://wiki.openstreetmap.org/wiki/Key:usage) says

> A track is either tagged with usage=* or with service=*! This rule does not apply for industrial (harbours, mines, large industrial complexes) and military railway infrastructure. These tracks may be tagged with both usage=industrial/usage=military and service=*.

[About the service tag](http://wiki.openstreetmap.org/wiki/Key:service), the only possible value would be service=spur

> This tag is used for short tracks connecting a factory or power plant to the railway network.

This has been done in the example case, the [track that connects the industrial area to the network](https://www.openstreetmap.org/way/87337663) is tagged as service=spur.

So should the tracks inside the industrial area also get tagged with "service=spur", even if they are not short connectors? 
Or should we look for usage=industrial and render these the same as service=spur?
The usage=* tag is used more than 800k times, but more than 500k is "main", 145k is "branch", 89k is "industrial".

**Comment by HolgerJeromin** [comment]
cc @nakaner

**Comment by Nakaner** [comment]
Thank you @HolgerJeromin for the mention.

Treating `usage=industrial` as `service=*` might be a good option but I would suggest render tracks with `usage=industrial` but without `service=*` on zoom >= 13. Tracks with `service=*` are currently rendered on zoom >= 14. The effect would be visible in large industrial facilities (chemical plant, large mining areas).

Everything written above also applies to `usage=military`.

If I were a maintainer of OSM Carto, I would ignore `usage=main/branch` because the usage of this key is different than most non-railway mappers expect. Its more a technical distinction. Main lines have more/better signalling and a higher standard of operation with more safety regulations, i.e. less crossings, exit signals at all stations, barriers at most level crossings. On the other hand, branch lines might have stations without exit signals (or even no signals at all – "dark territory" in the US) and lots of level crossings with just a saltire. There are branch lines which have a train every 10 minutes (they have lots of signals of course) while some main lines are only used by one train per hour.

**Comment by matkoniecz** [comment]
Maybe I misunderstanding something, but I would expect that in this case service=spur would be used.

http://wiki.openstreetmap.org/wiki/Key:service#Spur_Track seems to confirm my expectation.

**Comment by matkoniecz** [comment]
Given that service=spur should be used here and that tagging is already supported I see no reason to change rendering.

In case that I am mistaken and service=spur should not be used here - please correct me.
