### ISSUE TITLE
Some streets that are not joining may on zoom out misleadingly appear to be joining

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#286]
See http://www.openstreetmap.org/?mlat=50.06873&mlon=19.91165#map=18/50.06873/19.91165 and zoom out, on levels 17, 16, 15, 14 it appears to be joining. Fixing it should be feasible at least on levels 17 and 16.

Other example may be http://tools.geofabrik.de/mc/#18/51.4990/-0.1678&num=2&mt0=mapnik&mt1=google-map (Rutland, Rutland Mews). Note that Google maps have the same problem.

**Comment by kocio-pl** [comment]
Maybe rendering noexit=yes would be useful here?

**Comment by matkoniecz** [comment]
@kocio-pl 

http://wiki.openstreetmap.org/wiki/Key:noexit

> Use the noexit=yes tag at the end of a highway=* to indicate that there is no possibility to travel further by any transport mode along a formal path or route.

For example in that case one may travel further on foot (see http://www.openstreetmap.org/?mlat=50.06873&mlon=19.91165#map=19/50.06867/19.91185 - road is touching footway and https://www.google.pl/maps/@50.068822,19.911596,3a,75y,207.97h,79.85t/data=!3m4!1e1!3m2!1sDLjr_acb3dq4OQyWQNPFxg!2e0 ).

**Comment by kocio-pl** [comment]
I think if noexit=yes tag is used, we should assume the tagging is right and we can act accordingly, so we would catch at least all the clear cases.

This example is probably not a candidate for using such tagging, so we may not able to show it. However it seems this is special case when the footway is not separate (which makes this part a highway=living_street or a service area IMO). If only the footway was separate, that would be dead end. Or the tagging scheme should be extended to recognize also other values than "yes" (like noexit=motor_vehicle).

Another approach may be software analyzing if the node is terminating a highway and render it the same as tagged dead end. It is more costly, of course, in terms of computing power. However if we will not try that hard and take only tagged dead ends, it should be an improvement, because noexit=yes has 360 916 uses. Probably only part of them looks like a (false) junction, but changing rendering will do no harm.

**Comment by pmailkeey** [comment]
Hi debaters,

Firstly, there should be no problem terminating dead-end roads squarely - so the roundy bit doesn't protrude onto a nearby road. It should also be possible to shorten the dead-end road by half a road width so as one zooms out, the 'gap' gets bigger - but more of it gets covered by the fatter road equalising out the effect so that the gap remains clearly visible.

That's tackling the issue from the 'dead-end' point of view and will solve peculiarities like:
![image](https://cloud.githubusercontent.com/assets/11827386/7415220/36b829b8-ef4f-11e4-8259-e4a6f4fff290.png)

The following vert/horiz roads:
![image](https://cloud.githubusercontent.com/assets/11827386/7415484/22a139b8-ef51-11e4-805a-98f23be59c36.png)

are not connected yet they appear to be rendered as such.

Surely they should render as:
![image](https://cloud.githubusercontent.com/assets/11827386/7415525/7c075e6a-ef51-11e4-9588-dbefeeeca2d3.png)

**Comment by matkoniecz** [comment]
> there should be no problem terminating dead-end roads squarely

Unfortunately - it is a problem. As @pnorman already mentioned

> I'm pretty sure it's not possible, given the lack of topology.

In other words: it may be done for for either all ways or for none, it is impossible* to do things like "ways that end and are not followed by another way should be displayed differently".

*strictly speaking - not proved to be impossible but nobody has any idea how it may be done.

**Comment by pnorman** [comment]
> Firstly, there should be no problem terminating dead-end roads squarely - so the roundy bit doesn't protrude onto a nearby road. It should also be possible to shorten the dead-end road by half a road width so as one zooms out, the 'gap' gets bigger - but more of it gets covered by the fatter road equalising out the effect so that the gap remains clearly visible.

If it should be no problem, please supply a pull request as neither myself nor @math1985 see a possible way.

**Comment by pmailkeey** [comment]
Better ask your runway designers - they achieve square ends:

![image](https://cloud.githubusercontent.com/assets/11827386/7422839/f8fa9208-ef87-11e4-8a7a-63c5a127aa6a.png)

Just a case of rendering lines with mitred ends instead of round ones - basic buggering about with lines stuff. If there's a desperate need of rounded-end segments, that could be built into the node.

**Comment by pmailkeey** [comment]
Possibly another option could be a terminating node - like 'turning circle' but trims back the extent of the line and squares it off

**Comment by math1985** [comment]
> Just a case of rendering lines with mitred (or square) ends instead of round ones - basic buggering about with lines stuff. 

That would give us rendering artefacts like this:

![screenshot from 2015-05-01 01 20 27](https://cloud.githubusercontent.com/assets/5251909/7424963/6c881bb0-efa0-11e4-8f5b-a31c5a1e9a2e.png)
![screenshot from 2015-05-01 01 20 23](https://cloud.githubusercontent.com/assets/5251909/7424964/6c8901e2-efa0-11e4-9c82-3a4954569df9.png)

**Comment by pnorman** [comment]
Locking, as any change from wontfix would have to be accomplished by a pull request (i.e. code).

**Comment by math1985** [comment]
Unlocked, because I think educating others about how CartoCSS and this particular style works is also useful.

[Here](https://github.com/gravitystorm/openstreetmap-carto/issues/1511) @pmailkeey suggests mitred line-ends. I don't think that's supported in CartoCSS though?

The other suggestion was to look at terminating nodes. How would we determine what a terminating node is, though?

**Comment by matkoniecz** [comment]
> look at terminating nodes

AFAIK this is impossible ("osm2pgsql rendering database has no notion of topology, so two streets are never connected").

**Comment by pmailkeey** [comment]
A turning circle can be used as a terminating node - it modifies the end of the line. It's up to us to apply a terminating node where necessary - i.e. to avoid an apparent connection forming.

I started this in the iD discussion - wondering if a line could be shortened automatically to avoid it looking connected to another road. However, it was 'pointed out' that it's a rendering issue really - caused by lines having a width. So even 'terminating nodes' is really a bodge. It's something the renderer should deal with automatically.

It appears that roads visually connect when they meet. I don't know what causes this but it'd be nice if the effect was removed at all places other than connecting nodes - if possible !

**Comment by gravitystorm** [comment]
Locked again. This conversation simply isn't going to progress to a solution. It's a HARD problem. 

If you want to talk endlessly, please use the mailing lists. If you are interested in solving the problem, then please read all the conversation above, think about it, and propose your solution in the form of a pull request.
