### ISSUE TITLE
Please display icon for leisure=swimming_pool + sport=swimming on the map 

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#2870]
Please display leisure=swimming_pool + sport=swimming on the map. It could have the same icon as leisure=water_park but in blue color.

**Comment by HolgerJeromin** [comment]
I think leisure=sports_centre + sport=swimming (#2018) would be better.

**Comment by kocio-pl** [comment]
There's a discussion at Tagging currently, so we should make sure that the tagging is relevant.

**Comment by geozeisig** [comment]
Statistics:

- **leisure=swimming_pool + sport=swimming** there are about 40000 times. They are swimming pools outside as well as inside. Maybe a minimum size should be considered.

-  **leisure=sports_centre + sport=swimming** there are about 8000 times. These are mostly indoor swimming pools.

**Comment by dieterdreist** [comment]
2017-09-28 10:03 GMT+02:00 geozeisig <notifications@github.com>:

> Statistics:
>
>    -
>
>    *leisure=swimming_pool + sport=swimming* there are about 40000 times.
>    They are swimming pools outside as well as inside. Maybe a minimum size
>    should be considered.
>
>

IMHO the minimum size is the requirement to be able to "swim". If you can't
swim (too shallow, too small), it shouldn't get sport=swimming (tagging
error).
What about those with no sports tag? That's the vast majority (there are a
total of 744 393 leisure=swimming_pool, 456 547 of them are tagged with
access=private, this leaves us with 287.846 potentially public swimming
pools (or 274.997 without any access tag). I'd be reluctant to render only
those with sport=swimming, because it will encourage people to add this tag
also to diving pools, splash pads, recreation pools, thermal pools,
whirlpools, etc. in order to make them render.



>
>
>    - *leisure=sports_centre + sport=swimming* there are about 8000 times.
>    These are mostly indoor swimming pools.
>
>

Thank you for having the patience to check all those 8000 objects.

Cheers,
Martin

**Comment by SelfishSeahorse** [comment]
The result from the discussion on the tagging mailing list is that public indoor as well as outdoor swimming facilities should be tagged `leisure=sports_centre` + `sport=swimming` and that `leisure=water_park` should only be used for real water parks (amusement parks featuring slides, wave pools etc.).

Therefore I think it would be best to use the swimmer icon for `leisure=sports_centre` + `sports=swimming` (#2018) and to change the icon for `leisure=water_park` for a water slide or similar (as one doesn't swim there).

**Comment by matkoniecz** [comment]
Can somebody give example of places where it would improve rendering?

**Comment by SelfishSeahorse** [comment]
It would improve rendering of swimming pool facilities (i.e. `leisure=sports_centre` + `sport=swimming`) in general, but especially of indoor ones, because you won't see a pool on the map.

Here are some examples:

* http://www.openstreetmap.org/node/5233379038
* http://www.openstreetmap.org/node/1599802306
* http://www.openstreetmap.org/node/373736746

Besides, the fact that `leisure=water_park` is rendered with a swimmer icon (which BTW is unsuitable) but swimming pool facilities aren't is inconsistent and could lead to mistagging them as water parks.

**Comment by HolgerJeromin** [comment]
We should not mix leisure=swimming_pool with leisure=sport_centre+sport=swimming here!
All examples from @SelfishSeahorse have a sport_centre tag!

If don't want to render leisure=swimming_pool + sport=swimming this issue should be closed.
Icons for all this pools seems to be not improve rendering:
 

![image](https://user-images.githubusercontent.com/2410353/34470603-516521a6-ef35-11e7-92c6-6eaddb0e024e.png)

**Comment by matkoniecz** [comment]
I agree that icon for every single swimming pool, as proposed in this issue, would work poorly.

**Comment by matkoniecz** [comment]
> Besides, the fact that leisure=water_park is rendered with a swimmer icon (which BTW is unsuitable) but swimming pool facilities aren't is inconsistent and could lead to mistagging them as water parks.

Pleas, open a separate issue if separate unreported issue exists ( https://github.com/gravitystorm/openstreetmap-carto/issues/new )

**Comment by matkoniecz** [comment]
Closing as icon for every single swimming pool, as proposed in this issue, would work poorly in places with more than one swimming pool.

**Comment by matkoniecz** [comment]
Note that maybe icon for something like leisure=sport_centre+sport=swimming may make sense (one would need to check what is the correct/dominant tagging as part of creating an issue).

**Comment by SelfishSeahorse** [comment]
> Pleas, open a separate issue if separate unreported issue exists ( https://github.com/gravitystorm/openstreetmap-carto/issues/new )

 A separate issue already exists: #2018.

> Note that maybe icon for something like leisure=sport_centre+sport=swimming may make sense (one would need to check what is the correct/dominant tagging as part of creating an issue).

There was a discussion on the tagging mailing list and the result was that swimming pool facilities should be tagged `leisure=sports_centre` + `sports=swimming`. I'll search for the link to the discussion and will add it to #2018.
