### ISSUE TITLE
Parking too prominent

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#2904]
Parking is currently rendered too prominent. Compare for example the following renderings.

Before:
<img width="321" alt="screen shot 2017-10-24 at 00 45 24" src="https://user-images.githubusercontent.com/5251909/31916786-ab8d8492-b854-11e7-97bc-5ec59c2b4898.png">

After (possible):
<img width="325" alt="screen shot 2017-10-24 at 00 45 28" src="https://user-images.githubusercontent.com/5251909/31916777-a56ec17a-b854-11e7-8de3-4b33f3598523.png">

In the 'before' rendering, the parking is rendered more prominently than the buildings (including the supermarket). Can we tone down the rendering? Light gray like in the possible 'after' might be going too far, but do we have any other options?

**Comment by math1985** [comment]
Lighter yellow might work:

<img width="399" alt="screen shot 2017-10-24 at 01 04 49" src="https://user-images.githubusercontent.com/5251909/31917365-60f93d06-b857-11e7-8523-fcbbcc82444e.png">

The color is still not very intuitive to me, it doesn't immediately scream 'parking'.

**Comment by kocio-pl** [comment]
Thanks, looks to me like a real issue worth taking care of. Lighter yellow might be similar to social amenities however. Another possibility would be something based on garages area.

**Comment by kocio-pl** [comment]
> it doesn't immediately scream 'parking'.

Well, that's very good IMO. I don't like any objects to "scream" if they are not of special importance by design (like military area or health related features). Parkings are currently too prominent because of two properties: 
- very intensive color for area (second to reds probably), especially if this area is big,
- quite big letter with a color which is also intensive (strong blue is very visible on land features).

My initial idea was to push the letters down a bit (#2171), but maybe we could do the other way around and left the "P" markers as they are, but instead make area color neutral, just to see the shape. 

I feel that gray is good: if you're looking for a parking, you can still easily spot them, and the real shape and size is perfectly visible once you choose which one you're interested in. "Transportation gray" would make things unified (as in #2763).

Dropping yellow would also work for visibility of secondary roads ("After" rendering shows it clearly) and probably social amenities too.

**Comment by kocio-pl** [comment]
Examples of parking area colored like aerodrome:

Parking near LaGuardia airport (New York):
Before
![v4i5hl3p](https://user-images.githubusercontent.com/5439713/32080317-45cfbe74-baaf-11e7-9042-bd66ee35a60f.png)
After
![wxvipwlo](https://user-images.githubusercontent.com/5439713/32080308-3ea8d7a2-baaf-11e7-88c4-adfc7d88a88a.png)

Parking on LaGuardia airport (New York):
Before
![gzvgdni5](https://user-images.githubusercontent.com/5439713/32080329-4dd2e876-baaf-11e7-8559-e21084ef392b.png)
After
![zozusfbr](https://user-images.githubusercontent.com/5439713/32080334-522e1652-baaf-11e7-96cf-7eb12e83f650.png)

**Comment by kocio-pl** [comment]
Examples of parking area colored like garages:

Warsaw:
Before
![ekeykkve](https://user-images.githubusercontent.com/5439713/32098629-a060fff2-bb0d-11e7-87a5-c68bdee7acbe.png)
After
![ijj1geth](https://user-images.githubusercontent.com/5439713/32098647-a75ac252-bb0d-11e7-85ef-9c162872949a.png)

Parking near LaGuardia airport (New York):
![18l8az_f](https://user-images.githubusercontent.com/5439713/32098925-8b12f780-bb0e-11e7-8bde-4aa7987f31c9.png)

Parking on LaGuardia airport (New York):
![rudibwui](https://user-images.githubusercontent.com/5439713/32098933-938a0886-bb0e-11e7-88a5-b4f85e6fd399.png)

**Comment by printmaps** [comment]
Some hints for rendering parking space:
- parking area, no restriction (e.g. public) = yellow
- parking space, access permission (e.g. customers) = yellow with hatch
- parking space, private or no access = pale (same as garages)

**Comment by Tomasz-W** [comment]
I don't see any problem with current parkings colour. Current yellow with "P" letter is intuitive, and parking borders are visible good. Parkings with restricted access are rendered with lighter "P", and for me, it's enough to distinguish them.
Changing it to almost unvisible kind of pale brown colour, will make parkings hard to see.

**Comment by kocio-pl** [comment]
>  Changing it to almost unvisible kind of pale brown colour, will make parkings hard to see.

"Too prominent" means "too easy to see (=at the expense of other elements)", but making them less prominent does not mean they will be "hard to see". The letter "P" is still easily visible, so it's still easy to see the parking location, just not the shape.

**Comment by matkoniecz** [comment]
Gray parking areas would become invisible on landuse=residential and other gray areas.

**Comment by kocio-pl** [comment]
Well, it depends on the size - the bigger it is the more visible it became, which is very good. I like the original proposition (`#eeeeee`), because it's bright enough, yet parkings stop being more important than buildings, roads and societal areas as it is currently (which I find to be just ridiculous).

No landuse:
Before
![twr4wqzm](https://user-images.githubusercontent.com/5439713/32401964-a7382cb6-c11a-11e7-80cd-afc9812e6f72.png)
After
![_op5eogf](https://user-images.githubusercontent.com/5439713/32401944-503ba67c-c11a-11e7-824c-260f8f1328e8.png)

Residential with buildings - good contrast for big parking, at the same time small parking don't "scream":
Before
![_j72_8k7](https://user-images.githubusercontent.com/5439713/32401991-2d94a898-c11b-11e7-9e5c-49fb6b2c8760.png)
After
![usx grx](https://user-images.githubusercontent.com/5439713/32401988-2a16e348-c11b-11e7-8948-a436d7e571d8.png)

Before
![r6a4pthw](https://user-images.githubusercontent.com/5439713/32402139-abb4bf68-c11d-11e7-9632-0236d61d8250.png)
After
![ahv4wbno](https://user-images.githubusercontent.com/5439713/32402140-b140a9a6-c11d-11e7-899b-5d5116035a0a.png)

Big and small parking on commercial with buildings:
Before
![o0w mo4x](https://user-images.githubusercontent.com/5439713/32402042-08b98d62-c11c-11e7-9ea1-661bb9f90a19.png)
After
![y18p_bhq](https://user-images.githubusercontent.com/5439713/32402044-0bf7668e-c11c-11e7-9726-3aebb096980a.png)

Near secondary roads:
Before
![b0qkeich](https://user-images.githubusercontent.com/5439713/32402057-7e5af164-c11c-11e7-9d90-75fc14f37bc7.png)
After
![za7sw4ew](https://user-images.githubusercontent.com/5439713/32402059-8389b986-c11c-11e7-96b2-b9e7d7ea350e.png)

**Comment by kocio-pl** [comment]
Another example illustrating that it's a real problem and that a big parking are still visible with gray area - east side of Chicago:

Before
![gh8qb64o](https://user-images.githubusercontent.com/5439713/32405759-be8b941a-c16b-11e7-8256-68e629b602e2.png)
After
![pxx7hwri](https://user-images.githubusercontent.com/5439713/32405762-c49d46be-c16b-11e7-8ecf-eba10874cb00.png)

Before
![kve_febz](https://user-images.githubusercontent.com/5439713/32405784-09829bb2-c16c-11e7-8bb3-caf70889ff7d.png)
After
![wzmm_dnn](https://user-images.githubusercontent.com/5439713/32405786-0e04d1a0-c16c-11e7-8998-bbaed2d72a05.png)

**Comment by lakedistrictOSM** [comment]
Will you change amenity=bicycle_parking areas too for consistency?
eg http://www.openstreetmap.org/way/419572766 @ z19
![bicycle_parking_lancasteruni](https://user-images.githubusercontent.com/20193716/32558541-e6b75616-c49c-11e7-8b74-4ecee1fb5ea7.PNG)

**Comment by kocio-pl** [comment]
Another case when parking is too visible - big underground facilities in yellow make park look like a beach probably:

http://www.openstreetmap.org/way/230629285#map=18/41.88262/-87.62070

**Comment by kocio-pl** [comment]
@Tomasz-W Maybe P combined with the down arrow on the bottom could work for underground parking? It could be simple and readable, I hope. What do you think?

**Comment by Tomasz-W** [comment]
What about "P" under horizontal line? "P" with arrow is planned for https://github.com/gravitystorm/openstreetmap-carto/pull/2875

**Comment by kocio-pl** [comment]
Could you check both? I meant lower part of the letter to be an arrow, not two elements with smaller P, like in parking entry.

**Comment by Tomasz-W** [comment]
Ok, I'll try.

Btw. I think underground parking areas should be hidden the same as we hided underground platforms, I don't see a reason for showing them as they are covered by another elements (see the example above), so parking shape is invisible or hard readable anyway.

**Comment by kocio-pl** [comment]
Yes, my current idea is to hide all the areas (better than yellow, but still strange and misleading), but leave the mark on lower zoom level and show entries on higher zoom. I guess this would be enough and we don't have to remove the mark.

**Comment by Tomasz-W** [comment]
1. ![amenity parking underground 3](https://user-images.githubusercontent.com/25656654/45897079-6a5e0e00-bdd6-11e8-91bd-b870ab3e46d4.png)
2. ![amenity parking underground 1](https://user-images.githubusercontent.com/25656654/45896878-bfe5eb00-bdd5-11e8-9cc0-3f8b3dd65d6a.png)
3. ![amenity parking underground 2](https://user-images.githubusercontent.com/25656654/45897078-6a5e0e00-bdd6-11e8-80a2-849f86e53fbc.png)

Gist link: https://gist.github.com/Tomasz-W/b9655543be00a01d51c975b03009c654

**Comment by kocio-pl** [comment]
Comparison of [example with 3 underground parkings in Chicago](https://www.openstreetmap.org/#map=17/41.88271/-87.62252) on z17:

Before

![lftqmgc5](https://user-images.githubusercontent.com/5439713/45898156-65e72480-bdd9-11e8-9d7f-3f406448a553.png)

After (3 versions)

![siem2s c](https://user-images.githubusercontent.com/5439713/45898161-6a134200-bdd9-11e8-94ba-d2e4dd6de10b.png)
![gdhi ooc](https://user-images.githubusercontent.com/5439713/45898163-6b446f00-bdd9-11e8-8952-99e59602c46e.png)
![dmruosu7](https://user-images.githubusercontent.com/5439713/45898166-6d0e3280-bdd9-11e8-8ee3-59cd9c396fca.png)

**Comment by kocio-pl** [comment]
What about bigger triangle on v3, like the whole width and probably P letter cut a bit on the bottom to make it fit?

**Comment by Tomasz-W** [comment]
4. ![parking underground 4](https://user-images.githubusercontent.com/25656654/45898880-98921c80-bddb-11e8-9485-9152b6aeff7c.png)
5. ![parking underground 4](https://user-images.githubusercontent.com/25656654/45898901-ac3d8300-bddb-11e8-852e-8d06989f4410.png)

Gist link: https://gist.github.com/Tomasz-W/b9655543be00a01d51c975b03009c654

**Comment by Tomasz-W** [comment]
@kocio-pl Is possible to use there dashed parking outline there (without filling)? Can you try it?

PS. At this point I think it would be better if you will open new issue for underground parkings, because working on something in closed ticker which was about something different always makes discussion more complitated.

**Comment by kocio-pl** [comment]
I don't think the outline is good, it will be hard to know what is it. I will open new ticket once I get some time, I have too many things currently.

**Comment by jragusa** [comment]
My 2 cents: why not a roof over the "P" like [this one](https://www.alamy.com/stock-photo-white-sign-parking-house-on-blue-background-137194037.html)

**Comment by Tomasz-W** [comment]
Because it would fit rather parkings under `bulding=roof `(eg. https://ecofriend.com/wp-content/uploads/2012/08/vanguard-1_DRCPI_7071.jpg) than underground ones ;)

**Comment by polarbearing** [comment]
Not just in building=roof but also parking=multi_storey; but indeed not underground.

**Comment by kocio-pl** [comment]
I've made v6 simply by making v5 wide for the whole matrix:

v4
![eod47es8](https://user-images.githubusercontent.com/5439713/45931871-754ea500-bf74-11e8-9257-912f9ba3bbc7.png)

v5
![ou5vosk](https://user-images.githubusercontent.com/5439713/45931889-cb234d00-bf74-11e8-8298-ac77e1eabeab.png)

v6
![i0yj9nyt](https://user-images.githubusercontent.com/5439713/45931900-27866c80-bf75-11e8-9ad3-9361408ab1ee.png)

**Comment by Tomasz-W** [comment]
v4 or v5

**Comment by Tomasz-W** [comment]
Please continue further discussion about underground parkings in https://github.com/gravitystorm/openstreetmap-carto/issues/3506.
