### ISSUE TITLE
What is the name of this map style?

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2927]
https://github.com/gravitystorm/openstreetmap-carto/issues/103#issuecomment-170016812 has

> Just as an aside, please refer to these stylesheets as "openstreetmap-carto", not "Mapnik"

by @gravitystorm 

https://github.com/gravitystorm/openstreetmap-carto#openstreetmap-carto has

> OpenStreetMap Carto

https://github.com/gravitystorm/openstreetmap-carto/blob/c4270e5ccc3b4486507cc0692eb4803203b94e72/DOCKER.md#running-openstreetmap-carto-with-docker has

>  OpenStreetMap Carto

https://github.com/gravitystorm/openstreetmap-carto/blob/c4270e5ccc3b4486507cc0692eb4803203b94e72/DOCKER.md#importing-data has

> openstreetmap-carto needs a database populated (...)

**Comment by kocio-pl** [comment]
I think of it as "OpenStreetMap Carto", because "openstreetmap-carto" is just a technical limitation related to construction of URLs. 

See also:
- https://github.com/giggls/openstreetmap-carto-de#openstreetmap-carto-german
- https://github.com/h5bp/html5-boilerplate#html5-boilerplate
- https://github.com/FortAwesome/Font-Awesome#font-awesome-v470-

In general it's not clearly named, since it's a standard layer on OSM.org and is often seen like this (hence "Standard" or "Mapnik" monikers to just to differentiate from other layers):

https://wiki.openstreetmap.org/wiki/Talk:Standard_tile_layer#Name

**Comment by matkoniecz** [comment]
And https://github.com/gravitystorm/openstreetmap-carto/blob/master/RELEASES.md#notifications has openstreetmap-carto

Overall it is a low priority, but it would be nice to use one name.

**Comment by sommerluk** [comment]
The name always appears a little bit technical to me. And it’s easy to misinterpret because this style is really not the only style that used both, OSM and CartoCSS. But I also don’t know an alternative…

**Comment by skylerbunny** [comment]
I called it openstreetmap-carto on the Standard Tile Layer osm wiki page, BECAUSE of the comment that started this issue – which was directed at me – and because prior to that, said page was horrible about distinguishing this template and Mapnik at all. You have my Permission, if a name that is not 'openstreetmap-carto' is agreed on, to change any instance of it in the Wiki, because I'm probably the one responsible for that change in the first place.

The alternative was leaving the wiki alone, where it was pretty horrible about ANY distinguishing name, and often confused the various roles of the rendering engines, badly.

**Comment by skylerbunny** [comment]
One follow-up: whether we call it OpenStreetMap Carto, openstreetmap-carto, or TheHenHouse, **anywhere** this css style is referenced by "Mapnik" or "Standard" in a place it can be (like a readme or wiki, as opposed to an archived email thread), it **should** be.

1. Not having it consistently referenced makes it very confusing to find this project by name. Mapnik isn't 'this', and Mapnik and this project do completely different things.
2. There may come a day when this style isn't the Standard layer. iD calls it 'Standard' for user convenience, but it may change.
3. If we come up with a good name for it that we all agree is the Name, a change request can be sent **to iD** to tell them to call it that. 'Standard' is about as descriptive as calling a default choice in a dropdown 'Default'.

**Comment by kocio-pl** [comment]
The name "OpenStreetMap Carto" was added at the top of README file in the [first commit ever](https://github.com/gravitystorm/openstreetmap-carto/commit/f5f8a8238d82ea29cd3b93ab0636300723f8cfdb) and is human readable, so I think it can be assumed as a canonical name, not influenced by URL limitations and conventions (usually low letters and no space allowed).

**Comment by skylerbunny** [comment]
SGTM. In that case, there should probably be a pull request if necessary to change any plain text instance of it within the documentation here, and possibly other efforts beyond here (other projects, wiki, etc.) to make naming consistent.

**Comment by skylerbunny** [comment]
It also may be a good idea to suggest to openstreetmap.com and/or the iD project to call 'this', when referenced, 'OpenStreetMap Carto' and not say, 'Standard', 'Mapnik layer', or whatever else, when this stylesheet is the lowest level underpinning.

**Comment by kocio-pl** [comment]
I guess it's more or less clear now, so I close this issue.

**Comment by harry-wood** [comment]
The tricky thing is there's actually three different things which _could_ be given different names in any given set-up: the rendering software, the stylesheet, and the instance/hosting of a tile service.

I think it's clear that it was a mistake to call this thing "Mapnik". You will still see that in places because that's what we called it for many years in the early days. We should definitely ask people to stop calling it that though.

"OpenStreetMap Carto" is the name of this github repo (occasionally hyphenated purely for technical reasons), and so this is the name of stylesheet (it's a CartoCSS stylesheet), and the "project" to develop the cartography here.

Then there's "Standard", which I'm not so sure about. It's certainly a name I have used a lot, and I think we *could* say this refers to the tile service i.e. "OpenStreetMap's standard tile service" (which uses the openstreetmap-carto stylesheet).  ...but then again I have also joined in with muddying the water by saying things like the "OpenStreetMap standard stylesheet". And I ask myself if somebody set up their own Mapnik server running the openstreetmap-carto stylesheet, would they be wrong to refer to this as "OSM standard"? I think the way people use that name is a little bit muddled still to be sure.

**Comment by kocio-pl** [comment]
I guess you're right. Dropping of the "Mapnik" name is accelerating as we talk more about "OpenStreetMap Carto", so it's just a matter of time to eradicate it. 

The difference between style and OSM.org deployment is clear from the context most of the time and is important mainly with technical questions - especially with bugs like #1465, which has nothing to do with a style and is dependent on a Mapnik (I mean real Mapnik :smile:) bug on OSMF servers.

This way or another I consider this problem to be mostly solved.

**Comment by gravitystorm** [comment]
> Then there's "Standard", which I'm not so sure about.

I take that to mean the map layer on osm.org since the layer menu is about the only place you'll find it written. You could rewrite history a bit, and say that the "Standard" map layer used to be powered by "OpenStreetMap XML" and is now powered by "OpenStreetMap Carto" and in future might be powered by something else.

Of course it's hard to distinguish between the map layer and the free service offered by OSMF. But imagine if the OSMF offered multiple map layers, only one would still be the "Standard" layer on osm.org, so in my mind that's where the name rests i.e. it's the name of the layer, not the service, and not the stylesheets.

In addition, you'll can note that **none** of the map layers on osm.org are the name of the underlying map style or stylesheet project. So it's not an anomaly to have "Standard" instead of "OpenStreetMap Carto", since there's also "Humanitarian" instead of "HDM-CartoCSS", "Cycle Map" instead of "OpenCycleMap" and so on.

> OpenStreetMap standard stylesheet

Capitalise the "Standard" and "OpenStreetMap Standard stylesheet" becomes synonymous with "the stylesheet that is (currently) powering the OpenStreetMap Standard layer (which is OpenStreetMap Carto)".

> And I ask myself if somebody set up their own Mapnik server running the openstreetmap-carto stylesheet, would they be wrong to refer to this as "OSM standard"?

It gets into splitting hairs quite quickly, because most people just don't care about the differences :-)

**Comment by kocio-pl** [comment]
> Being the style chosen to be rendered on the OSMF infrastructure and prominently used on the OSM website is a privilege that has to be earned and every developer here should keep that in mind.

Off topic 1: I don't like to think of it in terms of privileges and honors. It's also a "privilege" for us that people do engage in designing and coding, which is not a given thing too. And we should be grateful for the data that can be styled... Well - it's a collaborative project and we just share different resources for the common good.

> Somewhat off topic here - but i think the names used on the website could be improved.

:+1: 

Stretching this off topic a bit more: maybe adding some basic links in the legend would be good to have (like where's the general description, where to report bugs or where's the full legend in our case).
