### ISSUE TITLE
Add point for cemetery=grave

### ISSUE THREAD

**Issue by WlaKom** [gravitystorm/openstreetmap-carto#2942]
Please add a point in the cemetery as "cemetery = grave"  when zooming the cemetery above z19.
http://www.openstreetmap.org/#map=19/53.83441/18.10357

**Comment by kocio-pl** [comment]
That would make it unreadable. Current rendering is very good, but z19 is still too low for such features:

https://overpass-turbo.eu/s/sTH

**Comment by WlaKom** [comment]
The current rendering does not show graves.

**Comment by kocio-pl** [comment]
Sure. My link shows how dense would they be on z19.

**Comment by WlaKom** [comment]
API showed circles instead of points.
See this cemetery under JOSM.

**Comment by kocio-pl** [comment]
One should make a code and test rendering to know for sure, but I believe just dots would be still too dense and not clear enough.

**Comment by WlaKom** [comment]
Do not closed this issue. Not done.
How is it possible for points 3 meters away from each other to be too dense?
A similar distance is often between buildings and no one denies it.

.

**Comment by kocio-pl** [comment]
Closing issue does not mean nothing can be done and I don't plan to lock conversation. It's just a tool for a team to know if this is likely to be done. If somebody else believe it is useful, he can reopen it. I don't.

I would not render just dots, rather brown tombs (like [this](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/grave_yard_generic.svg)). Dots are needed for amenities and offices, which usually have names and you can't expect where they are, so it will be useful. Cemetery is the area where mostly tombs are expected, so it's not a big information gain, and names would be seen only for some of them, so it would just show which parts of the cemetery contain them. With z20/21/22 it would make sense for me, but on z19 it's too early in my opinion.

**Comment by WlaKom** [comment]
I meant only the maximum zoom.

**Comment by matkoniecz** [comment]
>  above z19

Note that the openstreetmap.org is not allowing to zoom above z19 - z20 tiles are not available and z19 are maximum.

Even with z20 rendering added it would be invisible for a typical user.

I think that z19 would be too early for a typical cemetery to render all graves.

**Comment by SomeoneElseOSM** [comment]
For info re maximum zoom levels - the Humanitarian layer goes to z20, and that's the maximum zoom supported by mod_tile "out of the box".  It's possible to change that (I've done it for a map style I use for the UK and Ireland), but it's a change that would need thinking about for various reasons.  You could submit a pull request for cemetery=grave rendering to the Humanitarian layer at https://github.com/hotosm/HDM-CartoCSS or to mine at https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT but there's little point in the UK and Ireland as this tagging is hardly used there: https://overpass-turbo.eu/s/sUG .

**Comment by WlaKom** [comment]
I would like to know that many people in the OSM community believe that every grave is historical.
So, no matter whether it is a grave that was created yesterday or a hundred years old.
They add, automatically, to the tag "cemetery=grave", tag "historic=tomb".
I gave you an example of a cemetery completely mapped, but, currently, we have tombs / sarcophagi just adding that tag, they do not fill the whole area.

We also have places with sarcophagi tagging "historic=tomb" but without "cementary=grave", as they are not in the cemetery but in the underground of the castle.
http://www.openstreetmap.org/#map=19/50.05460/19.93560

The grave finder also considers the tag "historic=tomb":
http://osmtools.org/groby/#lat=50.05464&lon=19.93548&z=19

So perhaps it is worth to link the visualization of the grave with the tag "historic=tomb"?
I do not know. Think about it.

**Comment by wlakom** [comment]
I think it's time to reopen this topic and add an icon representing a grave, similar to https://umap.openstreetmap.fr/en/map/new/#19/53.83448/18.10317

This icon shows that its dimensions are sufficient so that they don't overlap.

So, please create an icon for the tag "`historic=tomb`" or "`cemetery=grave`" for the OpenStreetMap.org map.
Every grave is in fact historic.
This is not my opinion.

For example: We already have entire cemeteries mapped, such as in **Czarna Woda**
https://www.openstreetmap.org/#map=18/53.834347/18.102832

https://taginfo.openstreetmap.org/tags/historic%3Dtomb#overview

https://taginfo.openstreetmap.org/tags/cemetery%3Dgrave#overview

We also have an updated " **Wyszukiwarkę grobów na OSM** (OSM Grave Finder)" that allows you to display grave descriptions:

https://dotevo.github.io/gravemap-osm/#16/50.0759/19.9550

The current way of tagging graves has been very popular in Poland for a very long time and all graves on OSM are tagged in a similar way. Presumably there will be more and more of them, regardless of whether the community outside Poland likes it or not.

The community in Poland has developed the following procedure a long time ago. https://wiki.openstreetmap.org/wiki/Pl:Tag:landuse%3Dcemetery.

As I wrote before, the "Wyszukiwarka grobów na OSM" will allow increasing the number of graves in a similar way.

**Comment by matkoniecz** [comment]
https://github.com/gravitystorm/openstreetmap-carto/issues/2942#issuecomment-343518358 - z20 seems still too dense
