### ISSUE TITLE
Start rendering cave entrances at a higher zoomlevel

### ISSUE THREAD

**Issue by hikemaniac** [gravitystorm/openstreetmap-carto#2977]
In some cave-prone areas many caves are mapped, not just big ones but also small ones. As caves currently start to be rendered on zoomlevel 15, the result in these cave-dense places is an overcrowded, confusing map.

![cave dense](https://user-images.githubusercontent.com/31667811/33785461-6f2a3970-dc65-11e7-8b69-b412c3dc1607.png)

Zooming closer doesn't really make things better (z16):

![cave dense 2](https://user-images.githubusercontent.com/31667811/33785468-7552a224-dc65-11e7-81ae-ed7559d1e46a.png)

I suggest to start rendering caves from zoom 17 as no specific information can be shown by the cave markers on lower zoom levels anyway. Most users won't really be interested in caves when hovering over the map on a low zoom level and for those who are interested, they won't really have a problem with looking for them on higher zoom levels as both their locations are more precise and still a large enough area is shown on zoomlevel 17. I know that there had already been a counterproposal in #1102 to start rendering caves on lower zoom levels so I'd really like to know what the community and the developers think about it.

**Comment by kocio-pl** [comment]
It depends on how many such places exist?

**Comment by hikemaniac** [comment]
Well, I believe that there aren't a lot of these places. Nevertheless I do not really understand why cave entrances are rendered from z15. I don't think that many people profit from rendering them early.

**Comment by kocio-pl** [comment]
I can't be certain why z15 has been chosen, but in general I can say that whatever you do, there will always be some problems, because you can't control data from the whole world on all the scales. We also try to be universal, which makes it even more complicated - it would be easier when you care only for bicycles or public transport, because you have less elements.

It's easy for me to understand why such elements are needed so early - it would be good for somebody interested in the outdoor activities. Cave entrances can be interesting to plan a trip and it's good to see them earlier than many other things (like shops). In the rural places practically all the things are rare and should be rendered earlier than in the big city as the orientation points.

The problem you have shown is not drastic in my opinion and probably rare, so I will close the issue. However you can still comment and discuss this issue if you feel it's needed.

**Comment by hikemaniac** [comment]
You are right, outdoor people will be interested in caves, so am I. But still I think the icon is too prominent. 
![grafik](https://user-images.githubusercontent.com/31667811/33849131-f87c2836-deaf-11e7-9f7d-ddf6ab3cf4d7.png)
In the given example both caves shown are actually closed to the general public. Nevertheless the size of their icon is so prominent that they block the actual peak of the mountain out of view. 
As it probably won't be a good idea to stop rendering caves on z15 can we at least use a less prominent icon on them just for z15 (maybe a greyish circle)? On a higher zoom level, I suppose the original icon won't interfere with the other features anyway. And if you decide this is too much of a change can we at least hide the name label on z15 as they also block parts of the path?

**Comment by kocio-pl** [comment]
I'm currently busy with some more important things and this is quite subtle issue. If you could provide the code with practical solution, it can be discussed and merged eventually, otherwise I don't see it happening.

**Comment by kocio-pl** [comment]
Some more exact ideas how to change rendering would also help. I'd like to make peaks more visible (see #2848) and I think that's both more important and much more common, yet other people didn't see this a problem. It would solve at least part of your problem if we know how to do it.

**Comment by HolgerJeromin** [comment]
#1262 was about rendering private cave different/lighter.

**Comment by matkoniecz** [comment]
In other situations rendering caves earlier would be desirable. See  Render named cave_entrance on z14 #1102

I think that in this case z15 is ok and without some thorough research it should not be changed.

**Comment by kocio-pl** [comment]
Do you have the opinion on the proposed shade/color change?
