### ISSUE TITLE
landuse=depot is not being rendered

### ISSUE THREAD

**Issue by ghost07tula** [gravitystorm/openstreetmap-carto#2989]
Hi all,

it seems it makes sense to add rendering for `landuse=depot` tag. It is widely used and big areas are left white. I.e. [HERE](http://www.openstreetmap.org/relation/2400268#map=17/55.74595/37.50470) I think that the best color would be the same as for `landuse=industrial` or `landuse=railway`
Any thoughts on this?

**Comment by matkoniecz** [comment]
Used less than thousand times, I would not call it widely used.

**Comment by polarbearing** [comment]
The tag was introduced without voting, the value is ambiguous, it could be understood as a chemical depot as well as the train depots mentioned on the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:landuse=depot), or building materials as in the [draft proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Depot). The landuse for the train case is still railway etc.

The [proposal for subtagging the major landuses](https://wiki.openstreetmap.org/wiki/Proposed_features/*%3Dvehicle_depot) with specific depot properties makes more sense to me.

**Comment by SomeoneElseOSM** [comment]
For what it's worth I mapped it across to "industrial" in another map style; see [here](https://map.atownsend.org.uk/maps/map/map.html#zoom=19&lat=52.981962&lon=-1.177372) for an example.  A quick sample of usage via https://overpass-turbo.eu/s/tVy doesn't suggest obvious confusion about what is being mapped to me.

**Comment by mboeringa** [comment]
I think I am with @polarbearing on this one. Subtagging with other new keys instead of landuse makes more sense here.

If it is a goods, bulk cargo, or chemical depot, it is still landuse=industrial. If it is a train depot, it is still landuse=railway. If it is a bus depot, it is likely still a landuse=industrial, as almost all of these type of public transport depots are situated at the outskirts of cities as part of some industrial zone.

**Comment by matthijsmelissen** [comment]
Closing per the above.
