### ISSUE TITLE
Landuse & barrier tags on the same polygon object problem 

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#3000]
Hi
A closed polygon tagged with, say, landuse=cemetery or farmland (it may occur with others, I haven't tested them all) and barrier=hedge renders the polygon as as a filled hedge colour at z16+

This doesn't occur when the barrier tag is a wall. 
http://www.openstreetmap.org/#map=19/51.40595/-2.45302

Is there a reason for this?

**Comment by matkoniecz** [comment]
Sounds like #971

Is is result of tagging two different objects as a single element, typically may be fixed by more detailed mapping of hedge as usually (?) it is not fully enclosing areas and there is an entrance or by mapping area and barrier add two object (line for barrier, multipolygon with this line as outer for an area).

Mapping barrier and area as a single object is in this situation causing problem as we have fill rendering for hedge areas, and we have no fill rendering for wall areas.

**Comment by matkoniecz** [comment]
In short: it is data issue, as result of violating role of having single OSM object for single feature data interpretation gives unexpected results - and interpreted it as a hedge area.

**Comment by polarbearing** [comment]
A closed hedge makes no sense in reality, the area would have an entrance which forms a gap in the hedge. As @matkoniecz said, it's a mapping error.

**Comment by aceman444** [comment]
Well, making a node with barrier=entrance (or gate or whatever) would create the gap in the hedge, without needing the hedge be an unclosed line. But I understand that the example is violating the rule.

**Comment by dieterdreist** [comment]
sent from a phone

> On 29. Dec 2017, at 22:10, polarbearing <notifications@github.com> wrote:
> 
> A closed hedge makes no sense in reality, the area would have an entrance which forms a gap in the hedge. As @matkoniecz said, it's a mapping error.


yes, it is a (common) mapping error which mixes different things into the same object (and cannot automatically be split into different objects in this case, because hedges can be mapped as areas too). Still a closed hedge could exist in reality.

Similarly, most mappers are mixing buildings and POIs into the same object (but nobody complains about this error, because it renders fine).

**Comment by SomeoneElseOSM** [comment]
(at the risk of stating the bleeding obvious) "area" handling of hedges has been in OSM Carto probably since forever.  The bit that turns area hedges green is at https://github.com/gravitystorm/openstreetmap-carto/blob/master/landcover.mss#L735 .

Whether that's a good idea or not is a different matter; I seem to remember it came up on a mailing list a few years ago and someone found one or more "deliberately mapped as areas" hedges.
