### ISSUE TITLE
do not render boundary of an underground nature reserve (location=underground)

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#3018]
https://www.openstreetmap.org/way/510671596#map=18/49.98105/20.07812

![selection_003](https://user-images.githubusercontent.com/899988/34884695-ce556de8-f7bd-11e7-9ed4-e27d5d05b941.png)

I have doubts whatever name should be rendered,

**Comment by kocio-pl** [comment]
For the record: that's an example of a more general problem with underground features (including parkings) related to #1977 and #552.

**Comment by mboeringa** [comment]
To be honest, I think this is misclassified, even though the Polish name indeed seems to carry "nature" in it (which is unfortunate).

What "nature" is there a possible 1000 meters underground (except the rare bacteria species able to survive at these depths)? This is a geological monument, not a nature reserve, and as such should likely carry a:

**boundary=protected_area**
**protect_class=3** (Natural Monument or Feature: ... protect a specific natural monument, which can be a landform, sea mount, submarine cavern, **_geological feature such as a cave_** or even a living feature such as an ancient grove. They are generally quite small protected areas and often have high visitor value. Cultural and archaeological important. )

and have the **leisure=nature_reserve** tag removed.

This is also corroborated by [this Wikipedia page](https://pl.wikipedia.org/wiki/pl:Rezerwat%20przyrody%20Groty%20Kryszta%C5%82owe?uselang=nl) linked from the tag list of the feature, that talks about a "Polish database of representative **_Geosites_** selected for the European Network" instead of "nature reserves".

I also think that whatever measures are taken to not render it, people will likely re-tag it to something that does render, because people want to see this stuff rendered, and certainly if it is visitable tourist attraction, although this incentive could be reduced by a adding a node with tourism=attraction tag to already have something on the map.

**Comment by matkoniecz** [comment]
I created https://www.openstreetmap.org/note/1266528 and replied there. If you believe that I am wrong please reopen that note and comment there.

**Comment by mboeringa** [comment]
@matkoniecz , see the note and my comments.

**Comment by jeisenbe** [comment]
The wikipedia article on this area says:

"Pierwszy w Polsce rezerwat podziemny. Zajmuje powierzchnię 1,04 ha, zaś jego naziemna otulina liczy 2,065 ha[1]."

" The first underground reserve in Poland. It covers an area of 1.04 ha, while its above ground buffer covers 2.065 ha [1]."

So the above ground protected area is actually larger than the underground area. The area mapped appears to be about 120 x 100 meters (https://www.openstreetmap.org/way/510671596), which is probably just the underground area, however.

There are only 6 protected_area and nature_reserve features with the tag location=underground, so I don't think this is common enough of a problem to be worth fixing: http://overpass-turbo.eu/s/SEb

So I am closing this issue. However, if someone else wants to submit a PR to fix this, we can still consider it
