### ISSUE TITLE
Hide some indoor objects

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3031]
There's a problem with some indoor objects visible on the map. The case of artworks in Louvre is evident here and I would just hide them:

https://www.openstreetmap.org/node/4549412825#map=19/48.86058/2.33905

Are there any other objects which are used indoor and should not be visible? What about toilets, for example - there are here also, but many of them (if not all) are indoor really for weather/privacy reasons, even if not tagged this way:

https://www.openstreetmap.org/way/457696553#map=19/48.86095/2.33843

This issue is also related to hiding underground features - see #1977.

**Comment by dieterdreist** [comment]
2018-01-22 15:57 GMT+01:00 kocio-pl <notifications@github.com>:

> There's a problem with some indoor objects visible on the map. The case of
> artworks in Louvre is evident here and I would just hide them:
>
> https://www.openstreetmap.org/node/4549412825#map=19/48.86058/2.33905
>

they are all tagged incorrectly. The tag tourim=artwork is for "Public
piece of art", which they aren't. Public art, according to Wikipedia,
is "art in any media that has been planned and executed with the intention
of being staged in the physical public domain, usually outside and
accessible to all."

**Comment by polarbearing** [comment]
Yes a different tag would be appropriate, like exhibition=artwork or so. 
As for the toilets, they are typically in their own or in another building anyway, so they should be rendered. Here it would be interesting if they could be used on their own (with fee or without, e.g. museum foyer); or if they are part of paying admission to the facility. In the latter case the redering could use the halftone as in the parking-P, but there seems no particular tag for this property

**Comment by kocio-pl** [comment]
I don't see a problem with tagging. Public is true in this case - it's not private, it just requires a fee, it's also definitely tourism-related. Even when you consider Wikipedia, "usually outside and accessible to all" is just a practical hint (usually), not strict definition.

**Comment by polarbearing** [comment]
Sorry but you are stretching the "public" and "tourism-related" to the contrary of what the [wikipedia article](https://en.wikipedia.org/wiki/Public_art) describes. It is all about directly accessible pieces, not exhibits in museums.

**Comment by kocio-pl** [comment]
For me this part supports more general interpretation:
> Public art may include any art which is exhibited in a public space including publicly accessible buildings, but often it is not that simple.

This museum is not only national (which is not important on OSM, because we don't follow property type, only the object itself), but also "publicly accessible" - it's not `access=private` for example.

**Comment by dieterdreist** [comment]
2018-01-22 16:35 GMT+01:00 kocio-pl <notifications@github.com>:

> I don't see a problem with tagging. Public is true in this case - it's not
> private, it just requires a fee, it's also definitely tourism-related. Even
> when you consider Wikipedia, "usually outside and accessible to all" is
> just a practical hint (usually), not strict definition.
>

the term is "public art" and this implies a piece of artwork in the public
space, i.e. "on the street", not in a museum, especially not in a museum
which requires an entrance fee to be paid for admittance. Wikipedia was
just an example, you can look this up in other places if you don't trust WP.

**Comment by dieterdreist** [comment]
2018-01-22 16:55 GMT+01:00 kocio-pl <notifications@github.com>:

> This museum is not only national (which is not important on OSM, because
> we don't follow property type, only the object itself), but also "publicly
> accessible" - it's not access=private for example.




these articles are written for people who generally understand the terms,
that's why they can also be missunderstood by people who do not know the
terms. Please read more, and also in different places, if you do not yet
understand the term "public art".
This is IMHO an example for public art in a building:
https://www.openstreetmap.org/node/5253735916
This is a picture of it:
https://commons.wikimedia.org/wiki/File:Mother_with_her_Dead_Son_02.jpg
From the outside:
https://www.google.it/maps/@52.5174846,13.395662,3a,44.1y,357.68h,93.45t/data=!3m7!1e1!3m5!1sf_QLo3HBoc9HovA5L5tHOA!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3Df_QLo3HBoc9HovA5L5tHOA%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D257.79907%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656

You can simply walk in (or look at it from the outside), no entrance fee.

**Comment by kocio-pl** [comment]
I'm trying to look from the OSM point of view, which might be not the same as Wikipedia (though it's always good if we don't diverge too much from common knowledge without strong reasons). However when I was thinking of a fee as the only visible difference, that would mean probably `access=customers`, which is different than `access=public`, hence not a "public art". That would of course mean that tagging should be different. Do you agree with that interpretation?

If we don't find indoor objects currently visible on osm-carto which should be rather hidden, I will close this ticket in a few days.

**Comment by dieterdreist** [comment]
I would see "public art" as art in "public space", and while some buildings
might qualify as public space (although rarely), a museum generally
doesn't. The fee is not the only difference, because in museums you can be
excluded at will, e.g. you're too loud or singing (inappropriately
behaving), smelly, not appropriately dressed, don't want to do a security
search and seizure, want to take your rucksack with you, or your dog, etc.

**Comment by kocio-pl** [comment]
All of the people on the Tagging list thinks that you are right, so I will soon update the wiki to reflect it. It was proposed to use `exhibit=*` key instead in cases like these mentioned here.

Since there were no other examples of indoor data that we would like to hide, I'm just closing this issue.
