### ISSUE TITLE
Operating osm-carto in Offline Mode

### ISSUE THREAD

**Issue by 92Emzee** [gravitystorm/openstreetmap-carto#3059]
I am trying to operate osm-carto in Offline mode by giving the paths of the tiles generated by myself. 
To change the online paths of the tiles to Offline paths(file:/// etc.) , what and where are the changes required?

**Comment by matthijsmelissen** [comment]
Use kosmtik, and then something like http://localhost:6789 (kosmtik will give the exact url).

**Comment by SomeoneElseOSM** [comment]
I'm guessing that this is the same question as https://stackoverflow.com/questions/48494559/how-to-operate-osm-carto-in-an-offline-mode - as I said there, there are likely no OSM Carto changes needed at all.  

If something isn't working for you maybe give a few more details of what the problem is (and the stackoverflow question is likely the best place for that, since it's not really a problem with this map style).
