### ISSUE TITLE
Change barrier=block areas rendering

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3098]
Currently barrier=block + area=yes is rendered as barrier=* default outline with grey dot in the middle.

Example:
https://www.openstreetmap.org/way/491424279

This is how this place looks really:
http://cdn1.codziennypoznan.pl/201606241325/pub/img/full/71/1c58d-a9.jpg

I think it would be better to render blocks areas as grey shapes, and left these dots only for barrier=block nodes.

**Comment by Tomasz-W** [comment]
@vovenarg @alexander-ii @geowas-github Can you explan why are you against this change?

**Comment by alexander-ii** [comment]
@Tomasz-W  
Because you have decided to map street furniture elements as a barrier. But you shouldn't. It's not so far from [tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer).
The wiki page (https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dblock) says this tag may be used only on nodes. And it's describing the tag as "big solid things made of concrete **for stopping larger vehicles**". 

What I see in the link above is more like benches which represented by stone blocks. It doesn't look like a barrier to restrict access for someone.

**Comment by Tomasz-W** [comment]
What I see on the picture is a group of concrete blocks. You can interpretate them and use whatever you want - as benches, as steps, as raised footway etc., but they are still a concrete blocks.

As blocks can be big enough to map them as area, and eg. `barrier=wall` can be mapped as area, mapping block "as node only" restriction make no sense for me. I'll ask about it on mailing list and go back to this topic later.

**Comment by geowas-github** [comment]
@Tomasz-W 
alexander-ii  says it all.

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Aug 2018, at 20:40, Tomasz Wójcik <notifications@github.com> wrote:
> 
> What I see on the picture is a group of concrete blocks. You can interpretate them and use whatever you want - as benches, as steps, as raised footway etc., but they are still a concrete blocks.


it seems quite clear from the picture that these aren’t barriers, or at most they could be disguised barriers (does not look like, but maybe you have more information than what is apparent from the foto)
