### ISSUE TITLE
Private parking icon should have priority lower than normal parking icon

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#312]
http://www.openstreetmap.org/?mlat=50.0462&mlon=19.8828#map=15/50.0462/19.8828 displays private parking icon

blocking nearby parking icon - see http://www.openstreetmap.org/?mlat=50.0460&mlon=19.8824#map=16/50.0460/19.8824

IMHO private parking should not block rendering of normal parking icon as it is way less useful and important information

related to #70

**Comment by matkoniecz** [comment]
I think that after other changes related to parking icons it is no longer a problem. Solving it would just add more complexity to style that is not currently necessary.

**Comment by math1985** [comment]
+1

**Comment by kocio-pl** [comment]
BTW: as already [mentioned in a different issue](https://github.com/gravitystorm/openstreetmap-carto/issues/720#issuecomment-118184026), I guess maybe for showing not-public parking icon we should rather use the code like:

```mss
    [access != null][access != 'yes'] {
      marker-opacity: 0.33;
    }
```

because "access=public" [is defined just for toilets](https://github.com/gravitystorm/openstreetmap-carto/issues/720#issuecomment-118166013) and [it's not sure if we should use [access != ''] syntax](https://github.com/gravitystorm/openstreetmap-carto/issues/720#issuecomment-118185621)?
