### ISSUE TITLE
distinct icons for theatre:genre

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#3138]
The OSM tagging scheme puts a lot of different places in the amenity=theatre category. With all tags available we can now look at the theatre:genre key for better matching icons.

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtheatre

E.g. philharmonic theatres:
https://www.openstreetmap.org/relation/3626485
see also #1677

**Comment by Tomasz-W** [comment]
For me, the current symbol of two masks is enough for all spectrum.

**Comment by lakedistrictOSM** [comment]
I agree with @Tomasz-W, it might make the map confusing if we introduce different icons for all the different theatre types. Also, none of the values have that many uses, in the grand scheme of things.

See https://taginfo.openstreetmap.org/keys/theatre:genre#values

**Comment by kocio-pl** [comment]
I agree, therefore I will close it now. We can get back to this later and collect design ideas until the numbers will get higher (and this doesn't mean it will using be under the same tagging scheme - we'll see).

**Comment by dieterdreist** [comment]
sent from a phone

> On 21. Mar 2018, at 08:19, Tomasz Wójcik <notifications@github.com> wrote:
> 
> For me, the current symbol of two masks is enough for all spectrum.


did you have a look at the values? Clearly we don’t need a distinct icon for most of them, but grouping music theatres and other theatres differently would improve the map significantly, the mask icon does not work well for music (with opera being between the groups)

**Comment by kocio-pl** [comment]
Yes, I was thinking about theatre types for some time. However it needs quite a lot of designing work to find "clusters" of similar types and depict them with a set of icons, which should share a common visual thread to some degree. It took us some time and effort to do that for towers and castles, so the basic thing is to find somebody willing to do both things - otherwise it doesn't look too realistic for me currently. If your proposition is more detailed than original idea you described or you're willing to go further with it, we can reopen it of course.
