### ISSUE TITLE
Add rendering natural=fell 

### ISSUE THREAD

**Issue by 3mg4** [gravitystorm/openstreetmap-carto#3165]
natural=fell is still not rendered !

it should be rendered, or a valuable reason why it is not rendered should be given.

It has a wiki page with examples, even pictures, so the definition is clear. Whats the delay?

**Comment by 3mg4** [comment]
- It is not poorly defined 
- Maybe people outside regions where fell can be found are not familiar with the unique "look" of fell its NOT grassland, and not scrub and most definite not scree or meadow.
- so we can delete the wiki page and the tag, because according to the this discussion fell is useless, because it can be mapped with other tags, or how should we understand this?

**Comment by SomeoneElseOSM** [comment]
@3mg4 Perhaps if you'd like the people in charge of this map style to consider your opinions a slightly more polite approach from you would help?  Starting the conversation with "natural=fell is still not rendered !" is unlikely to win any friends or influence people.

No-one is saying "so we can delete the wiki page and the tag"; just that the discussion over whether or not to render this tag has been happening elsewhere.  There are other map styles that already render it (see https://github.com/gravitystorm/openstreetmap-carto/issues/2923#issuecomment-341887747 for links to one, and the complications of doing so).

**Comment by 3mg4** [comment]
@SomeoneElseOSM 
I don't mean to be unfriendly or not polite, just want to stick to the topic without much fuzz. 

I opened a new topic because the old one is very old, and nothing is happening 

Correct nobody is saying that so clear, but they imply it in the other thread when they wrote that natural fell is "mapable" "drawable" "tagable" with already existing tags (e.g. grassland, scree, rock, wetland etc. see also comment [https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-98479426](url) But clearly he dosen't know what a _moraine_ is.

**Comment by imagico** [comment]
> I don't mean to be unfriendly or not polite

> But clearly he dosen't know what a moraine is.

Right.

Every few months someone comes along here and complains about natural=fell not being rendered - either not understanding the previous discourse on the matter or ignoring it.

Based on the previous decision in #545 to not render natural=fell I am closing this issue as duplicate and wontfix.

I could suggest you try arguing your point in substance (in #545) rather than superficially with strawman arguments but it seems so unlikely to me this would actually lead to something that i will refrain from doing so.  What i will do instead is suggesting to you to familiarize yourself a bit with the basics of OSM.  Some links that might help here:

https://wiki.openstreetmap.org/wiki/Good_practice
https://wiki.openstreetmap.org/wiki/User:Joto/How_to_invent_tags
https://wiki.openstreetmap.org/wiki/Verifiability

It might also help to familiarize yourself with the geography and ecology of those regions where natural=fell is actually used:

https://taginfo.openstreetmap.org/tags/natural=fell#map

If after that you have a solid understanding on the meaning of natural=fell in OSM (meaning what the tag is actually used for which is not the same as the meaning of the term 'fell' in some regional context of what someone copied into the tag page on the OSM wiki from Wikipedia or elsewhere) and you still think this should be rendered in this style in compliance with its goals (https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md) that would be a viewpoint of interest (though as said this seems highly doubtful).

**Comment by 3mg4** [comment]
@imagico 

and again no improvement, maybe the dice argument from the other thread is true...;-)
