### ISSUE TITLE
Tower baseline alignment

### ISSUE THREAD

**Issue by georgek** [gravitystorm/openstreetmap-carto#3176]
There are a few icons representing tall objects now shown on the map. For example, wind turbines and communications towers. But the icons are aligned such that the centre of the icon is over the actual node position which leads to them looking misplaces, especially at lower zoom levels.

An example can be seen here with the wind turbine in the middle: https://www.openstreetmap.org/#map=16/52.5975/1.2626 It looks like it's in the water but it's not.

Can the alignment be changed so that the bottom of the icon is at the node position?

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Apr 2018, at 08:23, geozeisig <notifications@github.com> wrote:
> 
> The icon is a symbol and not a small reflection of reality. This can lead to small inaccuracies in the placement.
> 


-1, the icons should be placed in a way that it is intuitive to understand to which spot they refer to. In case of e.g. a tower, pole, chimney or mast, this is the base.

**Comment by matkoniecz** [comment]
The icons should be placed in a way that it is intuitive to understand to which spot they refer to. In case of e.g. a tower, pole, chimney or mast, this is the base.

@dieterdreist I reposted your comment as I agree with it and Github mail-to-cmment transform hides it (maybe it expects to post reply above quoted text? or to delete text of an original message?)

**Comment by jeisenbe** [comment]
This looks fixable with
`      marker-transform: 'translate(0,6)';`
This code will move the marker icon up by 6 pixels, which should work for most 14 pixel icons.

Here's an initial test in Honolulu, Hawaii
z14 Communications towers Original
![z14-honolulu-0](https://user-images.githubusercontent.com/42757252/48302762-0806cb80-e544-11e8-8296-ef771ddcbf9a.png)
Up 6 pixels
![z14-honolulu-6](https://user-images.githubusercontent.com/42757252/48302774-44d2c280-e544-11e8-9ba4-bcd52c915a84.png)

z18 Lighting towers original
![z18-honolulu-0](https://user-images.githubusercontent.com/42757252/48302776-50be8480-e544-11e8-8ffc-b309fa8e8c88.png)
Up 6
![z18-honolulu-6up](https://user-images.githubusercontent.com/42757252/48302778-587e2900-e544-11e8-863b-8072e8537e75.png)

z15 Lighthouse, Original
![z15-diamondhead-0](https://user-images.githubusercontent.com/42757252/48302781-5fa53700-e544-11e8-99d5-3f69683d8fbc.png)
Up 6
![z15-diamondhead-6up](https://user-images.githubusercontent.com/42757252/48302782-65028180-e544-11e8-827a-5f02b7736262.png)

**Comment by jeisenbe** [comment]
List of icons to be modified:

man_made communications_tower
man_made mast
man_made tower & man_made water_tower
man_made chimney
man_made lighthouse
man_made windmill
man_made obelisk & historic monument
power generator wind turbine

Any others?

**Comment by jeisenbe** [comment]
Cranes examples:
Big Willi centered z17:
![](https://user-images.githubusercontent.com/42757252/48177893-80aa3400-e35a-11e8-9633-602bee057063.png)
Big Willi  up 6 pixels z17:
![willi-up6-z17](https://user-images.githubusercontent.com/42757252/48307866-a5d8b580-e599-11e8-9e22-375aa161b0c3.png)

Singapore centered z17:
![](https://user-images.githubusercontent.com/42757252/48177897-84d65180-e35a-11e8-89bc-8f529e6e8ca7.png)
Singapore up 6 pixels z14:
![z14-singapore-up6](https://user-images.githubusercontent.com/42757252/48307871-c0ab2a00-e599-11e8-98ea-173ffc8c06f4.png)

**Comment by jeisenbe** [comment]
**Monuments in Beirut**, before
http://openstreetmap.org/#map=17/33.89653/35.50498
![monuments-before](https://user-images.githubusercontent.com/42757252/48308429-0a9b0c80-e5a8-11e8-83ad-68e033418c99.png)
Monuments up 6 - this is too much in my opinion, because the base of the monument is so thick
![monuments-up6](https://user-images.githubusercontent.com/42757252/48308431-1ab2ec00-e5a8-11e8-983b-04f21fb7c1b4.png)
Monuments up 4 - _better_
![monument-up4](https://user-images.githubusercontent.com/42757252/48308915-64ec9b00-e5b1-11e8-8a16-9042f277b25e.png)

**Mast in Lebanon**, before
![mast-before](https://user-images.githubusercontent.com/42757252/48308423-e5a69980-e5a7-11e8-8b39-d1c581cea3a3.png)
Up 6 pixels
![mast-up6](https://user-images.githubusercontent.com/42757252/48308424-e9d2b700-e5a7-11e8-8d74-ff3da39573a9.png)

**Watertower before** (Note that these are mapped as circular ways and tagged building=yes)
![watertower-before](https://user-images.githubusercontent.com/42757252/48308918-6d44d600-e5b1-11e8-91c1-4791a2425f83.png)
Watertower up 5 pixels
![watertower-z17-up5](https://user-images.githubusercontent.com/42757252/48308924-8b123b00-e5b1-11e8-887b-31940d296cbe.png)

**Windmill in rural Lebanon** before
![windmill-before](https://user-images.githubusercontent.com/42757252/48308921-8188d300-e5b1-11e8-9bde-aa95130981f2.png)
Windmill up 6p
![windmill-up6](https://user-images.githubusercontent.com/42757252/48308926-8d749500-e5b1-11e8-9e8a-4a8232b3bb09.png)

**Wind Turbines** Hawaii
Before z15
![windturbinesz15-before](https://user-images.githubusercontent.com/42757252/48308929-96656680-e5b1-11e8-95ac-73c2b1d06f50.png)
z15 up 6
![windturbinesz15-up6](https://user-images.githubusercontent.com/42757252/48308930-9d8c7480-e5b1-11e8-84af-22a4c908dbcf.png)
Before z17
![windturbinesz17-before](https://user-images.githubusercontent.com/42757252/48308931-a1b89200-e5b1-11e8-8bea-01af6af46534.png)
After z17
![windturbinesz17-up6](https://user-images.githubusercontent.com/42757252/48308932-a4b38280-e5b1-11e8-89f6-e5b43b2cbfde.png)

**Comment by jeisenbe** [comment]
Adjusted Lighthouse up 4 pixels rather than 6; better I think:
z15 original
![](https://user-images.githubusercontent.com/42757252/48302781-5fa53700-e544-11e8-99d5-3f69683d8fbc.png)
z15 up 4 pixels
![Uploading lighthouse-up4.png…]()

Man_made Obelisk, Washington DC:
z15 original
![obelisk-before](https://user-images.githubusercontent.com/42757252/48309304-6a021800-e5ba-11e8-95b9-1a2b75e3f284.png)
z15 up 6 pixels (thin base, tall icon)
![obelisk-up6](https://user-images.githubusercontent.com/42757252/48309305-6cfd0880-e5ba-11e8-970a-f14b9b7ab6b3.png)

Man_made Chimney
Before z16
![chimneys-before](https://user-images.githubusercontent.com/42757252/48309295-5951a200-e5ba-11e8-8a21-7d8d6ab92c4b.png)
Up 6 pixels z16
![chimneys-up6](https://user-images.githubusercontent.com/42757252/48309302-67072780-e5ba-11e8-8b70-d8dd10183b92.png)

**Comment by kocio-pl** [comment]
On thing that still bugs me (sorry if that's stupid and you have put a detailed explanation - I just have no too much time currently): what if Obelisk, Washington DC had no label, would it be centered then?

**Comment by jeisenbe** [comment]
The text label does not change the placement of the icon, it renders in the
same place (centered on the node or polygon centroid) whether or not there
is a name

**Comment by kocio-pl** [comment]
So it will be displaced off the center? I didn't have the time to review this yet, but I don't like this effect.

**Comment by Adamant36** [comment]
My only thing is if this is done on points and the icon is moved up a few inches on the map, does that then translate to it moving a few feet in real life and how would affect other POI's mapped extremely close to it. I know the position of the icon isn't a "coordinate accurate" position in the first place, but the original position was chosen as a default for a reason and its something I think about.

**Comment by meased** [comment]
Where is this idea going? Everything that "stands up" gets an offset icon? embassy? fuel? cafe? camping? golf? picnic? waste_basket?

What is the problem that this idea solves?

This is a 2D map, not a 3D map. Icons represent an object, they don't have to look like a vectorized aerial image of the object.

**Comment by jeisenbe** [comment]
While the original PR showed changes for all tower-like features, the
current version only changes icons that have 2 parts:

1) Towers and 2) masts with “communication waves” coming out of the top

3) Chimneys with “smoke” at the top.

The last icon is the most confusing, because the position of the chimney is
in the lower left corner of the 14x14 pixel icon. As shown in the most
recent images, this leads to the chimney appearing about 4 pixels left of
its real position. The center of the chimney also appears below the node.

By shifting the icon up and right by 4 pixels, the PR now makes the icon
appear to be centered over the node.

I agree that it would be silly to shift every icon. I would only like to
shift icons that are made of 2 parts like this.

I’ve looked through all of the SVGs, and most are fine. Only 1 or 2 others
have this problem due to being composed of 2 parts, for example drinking
water. But only the towers, may and chimney are rendered on low enough zoom
levels for it to be a real problem.

**Comment by jeisenbe** [comment]
Re: “the original position was chosen as a default for a reason”

I don’t think this issue was considered before. The default of centering
the SVG is usually fine, because most icons are symmetrical or at least
square-shaped.

**Comment by jeisenbe** [comment]
I believe this issue is going to closed as wontfix, correct?

**Comment by matthijsmelissen** [comment]
Jep, thanks.
