### ISSUE TITLE
Add font for Aramic

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#3184]
In checking osm-carto's behavior for Aramaic for a [wikimedia issue](https://phabricator.wikimedia.org/T112948#4146501) I realized we don't have it in our fonts list.

**Comment by sommerluk** [comment]
Reading a little bit in Wikipedia, as far as I understand, Aramaic can be written with various writing systems, among them Hebraic, Syriac and (following Noto’s web page) also Samaritan. All of these are yet available in openstreetmap-carto. Imperial Aramaic is not. Is it used still today, or should it be treated like a dead script (means: not in fonts.mss)?

**Comment by sommerluk** [comment]
I’ve downloaded all 122 nodes and 2 ways (but not relations) with name:arc in OSM into JOSM. At difference to overpass-turbo, in JOSM Unicode support is not broken, so we can filter for Imperial Syriac script.

Results for `name:arc`:
- 3 times Tifinagh script
- 1 times Latin script
- 1 times Arabic script
- all others have Syriac script
- none with Imperial Aramaic script

Results for `name`:
- none with Imperial Aramaic script

So it seems that not only the `name` values, but even the `name:arc` values do not actually make use of the Imperial Aramaic script.

**Comment by sommerluk** [comment]
I found a way to work around the overpass-turbo bug: Using `[name~".*[𐡀𐡁𐡂𐡃𐡄𐡅𐡆𐡇𐡈𐡉𐡊𐡋𐡌𐡍𐡎𐡏𐡐𐡑𐡒𐡓𐡔𐡕𐡗𐡘𐡙𐡚𐡛𐡜𐡝𐡞𐡟].*"]` instead of `[name~".*[𐡀-𐡐].*"]`. Result: Not a single object in OSM with this script.

I will close this issue considering that the Imperial Aramaic _script_ (at difference the the Aramaic _language_) is a dead script and therefore should not be listed in `fonts.mss`. Feel free to reopen if I got this wrong.

**Comment by matthijsmelissen** [comment]
Thanks for great investigation!
