### ISSUE TITLE
Motorways on low zoom levels are very hard to notice and look like rivers

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#319]
example: http://www.openstreetmap.org/#map=6/49.561/16.078

to compare: http://tools.geofabrik.de/mc/?lon=9.06148&lat=50.87875&zoom=5&num=3&mt0=mapnik&mt1=google-map&mt2=mapnik-german

related: #315 (problems with labels on low zoom levels), #102 ("Secondary and trunk color too similar to landuse colors")

I suggest:
saturated red for motorway
red for trunk road (current Primary road colour)
dark orange for Primary road
light orange for Secondary

(expansion of https://github.com/gravitystorm/openstreetmap-carto/issues/102#issuecomment-22529306)

**Comment by math1985** [comment]
> to compare: http://tools.geofabrik.de/mc/?lon=9.06148&lat=50.87875&zoom=5&num=3&mt0=mapnik&mt1=google-map&mt2=mapnik-german

For reference, the colour scheme the German rendering uses is in fact the colour of the Michelin maps.

**Comment by RAytoun** [comment]
Hi math1985,
Thank you for taking the time to respond to my weighty start.
Sorry, but I am not trying to push things or be insistent, I am involved in
the Missing Maps Project where we are starting to map the more remote areas
that have not been done before and may need humanitarian intervention. It
is in these areas of water deprivation, flooding and natural disasters that
will require the use of lesser used symbols such as intermittent waterways
and wadis, dry lakes and salt pans.
I posted the full query covering my problem.
Thanks for the information regarding the base colour scheme for the maps, I
am familiar with and have worked with the Michelin Map series and
atlases.....they are first and foremost International Road Maps orientated
and less of the geographic background detail. In these remote areas the
source of water is a paramount and geographic features their only way of
navigating. In some instances of first base mapping we even show individual
trees as points of navigation until people on the ground can add more
tangible information.
But I am labouring the point, I have just heard from imagico that the
depiction of the intermittent rivers is already in hand and for that I
thank you. I have been told by my fellow mappers that the adding of
waterway information is poor because of people lacking the knowledge and
understanding of depicting them. I will try to help with this problem.
I think the guys sorting the rendering are doing a great job and for that I
really appreciate your work and will help in any way I can with my
specialist knowledge.
Thanks for your response
Ralph

**Comment by math1985** [comment]
I responded here: https://github.com/gravitystorm/openstreetmap-carto/issues/1255#issuecomment-71386369

**Comment by RobJN** [comment]
Worth noting that colour isn't everything. The motorways stand out more in the geofabrik link at the top of this issue due to line thickness as well. But the thicker you make the roads the more you are sayig "this is a road map".

In regards to rivers, Google is using a much stronger (more vivid) blue and very pale backgrounds. Perhaps we can test that?

**Comment by RAytoun** [comment]
The depiction of roads in maps varies with the scale of the map.
The smaller the scale of the map (from 1:1000000 ) the greater the need to
differentiate between roads and rivers so many international reference
atlases depict the motorway at this scale as a parallel double red solid
line with a white fill (also popular is a thinner double black line with a
red fill) but as they get down to country and street plans this tends to
change to a parallel double bolder blue line with a thin blue centre line
with a white or pale blue fill because the uniformity and straightness of
the road and the inclusion of the centre line makes it visually different
to the rivers. (examples..Philip's Atlases; Harper Collins Atlases;
National Geographic Atlas; Times World Atlas; USGS)
In these and most other atlases the depiction of rivers is as you
say....with a solid blue line and a pale blue fill. this also allows for
the intermittent symbol of a pecked blue line but with a continuous pale
blue fill (the fill does not become pecked with the line). This style of
depiction will also work for lakes, ponds etc. and intermittent lakes or
areas liable to flooding.
