### ISSUE TITLE
Do not show substation rendered as point

### ISSUE THREAD

**Issue by jragusa** [gravitystorm/openstreetmap-carto#3214]
Related #230, #252, #511, #569, #2259

### Expected behavior
Substation rendered as point should be removed and only substation areas or buildings should be kept.

### Actual behavior
Substations displayed as points show a somewhat weird rendering. Their name are rendered alone without any icon or something else. Despite distinct colour and font, they may create confusion with some localities (hamlet, etc). In addition, these small features (when rendered as point) are not especially good markers in the landscape. 

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/node/2880672907

z=17
![substation_z17](https://user-images.githubusercontent.com/9897203/39629444-82fcdd76-4fac-11e8-819e-073273b4113c.png)

z=19
![substation_z19](https://user-images.githubusercontent.com/9897203/39629479-a4f09e36-4fac-11e8-8fbf-21e41698fc39.png)

**Comment by jeisenbe** [comment]
Currently there are over 62, 000 `power=substation` nodes (compared to 300,000 ways) and mapping as a node is allowed on the wiki page, so I believe we should continue rendering this feature on nodes. The text rendering is only shown at z17 and up. Adding a dot marker would be a possible improvement.

**Comment by jeisenbe** [comment]
#3878 will restore rendering of substations on points, which was temporarily lost unintentionally.

**Comment by jeisenbe** [comment]
Closing this issue: we currently render name labels for all sorts of area features when they are tagged as points. If this were to change, it would need to be addressed in a more general fashion.

I believe we should continue showing labels from the nodes (only at high zoom levels) because it's a reasonable way to map an area feature when good aerial imagery is not yet available.
