### ISSUE TITLE
Render overground power cables

### ISSUE THREAD

**Issue by M1dgard** [gravitystorm/openstreetmap-carto#3217]
### Expected behavior
Gas insulated cables are now becoming common in high voltage substations around me. They have to be mapped with `power=cable` instead of `power=line`, since the insulation is the discerning factor between these tags.

I'd propose to render **cables the same as power lines** if they have a **location** tag that is **different from `underground` and `underwater`**.

### Actual behavior
Power cables are never rendered, which makes substations that use gas insulated cables have gaps on the map.

### Links and screenshots illustrating the problem
![screenshot_2018-05-06_22-56-42](https://user-images.githubusercontent.com/4283376/39677761-0934fa30-5170-11e8-9e30-8dd79ca53975.png)

**Comment by kocio-pl** [comment]
Looks OK - there's a wiki page and 13k+ uses:

https://wiki.openstreetmap.org/wiki/Tag%3Apower%3Dcable

Could you prepare a code for rendering this feature?

**Comment by M1dgard** [comment]
> Looks OK - there's a wiki page and 13k+ uses

Do note that most of those are underground: 8k+ of those 13k+ are combinations with `location=underground`.

> Could you prepare a code for rendering this feature?

I haven't worked on carto yet and never used Mapnik, but I'll try it out! :)

**Comment by mboeringa** [comment]
What is the minimum voltage these "gas insulated cables" operate on? To prevent potential junk added by users showing up, like adding power=cable in their personal home, an extra selection on a minimum voltage (e.g. > 1kV) might be a preventative measure.

Of course, such a selection will also require a voltage setting for the features to show up at all. I don't know the tagging status regarding such voltages within substations...

Note: I haven't actually seen "home cables" yet, but there are loads of mis-uses in other tags, and with the recent spade in indoor tagging, I could well see someone adding something like this... There are certainly low voltage (230/400V) outdoor home connections in e.g. towns and villages being tagged though with power=line, which isn't wrong by itself, but also requires filtering based on voltages to distinguish them from true distribution lines and prevent cluttering.

**Comment by M1dgard** [comment]
@mboeringa The cables I saw carried the highest voltage in my national grid, 380kV. But lower voltages may be interesting too:

Everything above 1kV AC is considered high voltage. For DC (frequency=0), the threshold is 1.5kV. For the power grid (which is AC everywhere in the world with some DC long-distance lines), high voltage starts at around 63kV depending on where you live. Between 1kV and 63kV it's distribution voltage. You can find those to and inside local substations and industrial plants.

*I am not a power professional. I read up on power grids in order to be able to map them in OSM. This information might not be entirely accurate.*

**Comment by Penegal** [comment]
This added rendering for lower-level cables (https://www.openstreetmap.org/#map=18/47.95900/6.80918):
![image](https://user-images.githubusercontent.com/13777824/46295021-65981780-c597-11e8-8d77-505aeff02659.png)

This clutters the map with things displayed as major lines, whereas these are only the cables powering individual buildings. This seems a major drawback to me, at least in the current version.

**Comment by kocio-pl** [comment]
Is it about lines like that https://www.openstreetmap.org/way/512818816 ?

I'm not sure why this is not tagged as a minor line:

> These heavier cables should not be confused with light-weight uninsulated power distribution lines supported by pylons and poles, for which power=line/power=minor_line are normally more appropriate.

https://wiki.openstreetmap.org/wiki/Tag:power=cable

> Uninsulated power lines carried on poles physically smaller than the high voltage pylons/towers and used for power distribution, are tagged as power=minor_line. 

https://wiki.openstreetmap.org/wiki/Tag:power%3Dminor_line

**Comment by Penegal** [comment]
@kocio-pl : these are insulated cables; the majority of the French distribution network is based on insulated cables, not uninsulated ones, hence the `power=cable` tag.

**Comment by jeisenbe** [comment]
Penegal, I think it might be a mistake to tag small power distribution
lines as power=cable. It appears that this tag was originally meant for
large power cables, analogous to power=line, not for the minor lines that
lead directly to residences and businesses. But the wiki is confusing, so I
see how some minor lines that are insulated have been tagged as power=cable
due to this confusion.

power=minor_line is meant for "lines forming the distribution grid, 100V
... to 45 kV, usually carried by single poles"

I'll ask on the tagging mailing list for clarification. The wiki (English
and French) may need updating to reduce confusion.

Joseph

**Comment by Gazer75** [comment]
Might want to look at voltage as well to determine rendering of cables.
The local 230V lines should really be given a new "minor_cable" value to set them apart from the rest.
Yes I know that is not a used value, but I doubt the initial thought was to map anything below around 11kV. 
Mapping the local 230/110V poles and lines will create a massive clutter in OSM, not just in rendering, but the overall map data.

In Norway I've mapped a lot of the higher voltage lines. Anything at 22kV and down get minor line and poles.

**Comment by Adamant36** [comment]
@Gazer75, rendering based on voltage has been discussed in #3019, but it was closed. So my guess is not well. Feel free to look through it. I seem to remember thinking it was a cool idea at the time. Maybe you can revive it somehow.

**Comment by jeisenbe** [comment]
I read up on [#3019](https://github.com/gravitystorm/openstreetmap-carto/issues/3019) and [#510](https://github.com/gravitystorm/openstreetmap-carto/issues/510); it looks like the issue with using voltage to distinguish between types of power=line was that there is also a power=minor_line tag which can be used.

Since there is not yet a tag for power=minor_cable, it could be correct to tag overhead insulated power wires that are carrying 220 volts directly to houses. Someone said that I should tag the cable that connects my house to the nearest pole with power=cable!

I'd prefer for there to be different tags for wires used for transmission, distribution and for connecting individual customers (eg the wires to my house), but we don't have that distinction with power=cable.

So it makes sense to render power=cable the same as power=minor_line when the voltage is below 42kV, unless someone wants to do a proposal for new tagging schemes.

(I'd also support moving all lines below 400V to a higher zoom level)
