### ISSUE TITLE
Add icon for leisure=outdoor_seating

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3241]
https://wiki.openstreetmap.org/wiki/Tag:leisure=outdoor_seating
2k uses.

Icon proposal:

![leisure outdoor_seating](https://user-images.githubusercontent.com/25656654/40282267-07596694-5c6d-11e8-809d-a975c08b6f5d.png)

**Comment by polarbearing** [comment]
Good idea. The umbrella is a bit dominant compared to chairs+table. What about dropping the middle pole?

**Comment by geozeisig** [comment]
`leisure=outdoor_seating` belongs to a restaurant, cafe etc. and should be tagged together with this one with `outdoor_seating=yes` (72k times). You can create icon for restaurants with and without outdoor seating, but I think that's too complicated.

**Comment by Tomasz-W** [comment]
@geozeisig Please read Wiki page of this feature. `Leisure=outdoor_seating` is for permanent seating areas (eg. build on wooden terrace or equiped with heavy umbrellas) and `outdoor_seating=yes` is for small ones, which are bring outside only on sunny days.

**Comment by polarbearing** [comment]
Indeed I have seen them on separate objects, the restaurant node/area inside the building and the node or area for the outdoor area, naturally, outside.

**Comment by SomeoneElseOSM** [comment]
@Tomasz-W The wiki does not say that (see https://wiki.openstreetmap.org/wiki/Key:outdoor_seating) and I have not seen mappers do what you suggest.

@geozeisig It wouldn't be complicated to split restaurants into categories in lua and have the Carto code only differ by icon (that's how I've done the pubs and fast food at https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=-24.988106&lon=135.17649 for example).  Whether this style wants to make more use of lua like this is a different issue of course.

**Comment by eehpcm** [comment]
I'm late to this party, and everyone has gone home.  I only just realized this icon had been incorporated because I'd mapped several outdoor seating areas and noticed one of them now had an icon.  Cool.  Unfortunately, it's a very misleading icon for what I've mapped.

**None** of the areas I've mapped have umbrellas or parasols or roofs or canopies.  No protection from rain of any sort (which is amusing, given how often it rains here).  I see that since I mapped them the wiki has added a mention of the undocumented and little-used complementary tag "weather_protection" and although it mentions all sorts of possibilities, it doesn't mention "weather_protection=no", which I think probably ought to be the default.

Any chance of another variant of this icon without the umbrella and OSM carto taking into account weather_protection for deciding which variant to use?  I.e., without umbrella for weather_protection=no or weather_protection not specified and with umbrella for weather_protection specifying anything other than "no"?

**Comment by polarbearing** [comment]
@eehpcm - you should not take the icons too literally. They are a symbol that there is a particular feature, not a drawing of the feature itself. Fast-food has a burger icon even if the food itself is kebab.

**Comment by eehpcm** [comment]
@dieterdreist 

I view tourism=picnic_site as being a case where the only thing provided is the seat/table, usually a picnic bench (because it's too large and heavy to be easily stolen) and with no conditions for use.  One picnic site I've mapped doesn't even have seating/tables, you're expected to sit on the grass.  It's inapplicable to the cafes and pubs I have mapped: the seating is outdoor patio furniture (easily portable) and the condition for use is that you purchase food/drink there and consume only the food/drink you've purchased there (exceptions usually exist for baby bottles).

The problems with amenity=bench are that it is public (no preconditions for use) and there is no indication that there is a table.

The problems with amenity=shelter for mapping outdoor seating at a cafe/pub is that (in the cases I've mapped) there is no shelter; it doesn't visually indicate there's a table and it doesn't visually indicate there is seating.  Definitely unsuitable.

Using leisure=picnic_table is better.  Marginally.  It indicates there is seating.  It indicates there is a table.  It doesn't falsely indicate there is shelter.  But you can't indicate the extent of a seating area and if you try to put in as many picnic tables as there are tables most of them don't render.

Basically, I don't understand why the icon for outdoor_seating has an umbrella when none of the ones I've seen have an umbrella.  Yeah, that may be a peculiarity of where I live, and in other countries it's rare for such things not to have rain protection, but somebody has already added weather_protection=* to the documentation for outdoor_seating to distinguish between the various types of rain protection (maybe that should have been outdoor_seating:weather_protection but that's a different discussion for a different forum).

Anyway, going by my part of the world, outdoor seating without rain protection is the norm not the exception.  If that's the case elsewhere then the icon should be modified.  If it's a regional variation then we ought to have two icons and take account of weather_protection=*.  Because if I'm a tourist and it is raining, so I plan where to eat based on the icon showing outdoor seating with rain protection I'm going to be unhappy when I get there and find there's no rain protection.

**Comment by eehpcm** [comment]
@polarbearing 

In my part of the world (the bits I've seen so far) rain protection is the exception, not the rule.  If I'm a tourist choosing where to eat based upon whether or not it has outdoor seating I'd take that icon to mean it **does** have rain protection.  If it's raining then I'm going to be unhappy when I go there and find there is no such protection.

Is it actually more common than not to find rain protection elsewhere in the world?

Or, another way of looking at it.  The shelter icon shows a roof.  Would it be a suitable icon for a walled area without a roof or canopy?  I think not.

**Comment by polarbearing** [comment]
This is a general map, we cannot display all the fine differences here. Feel free to render a gastronomy map where you can focus on distinguishing the umbrellas as well as the cuisine.

**Comment by eehpcm** [comment]
@polarbearing 

I take your point that it is impossible to display everything.  Even though we do make distinctions between restaurants, cafes and fast food places (so your gastronomy analogy isn't entirely correct).

This isn't about adding **more** detail than can be displayed.  This is about rendering alternate versions of a symbol that _is already displayed_ to prevent the map being misleading.  I'd say that if outdoor seating without shelter is more common than with shelter then the icon should be redesigned to cater to the common case if we can't have two variants.  But two variants would definitely be better and any argument about that making the map "too crowded" or "too detailed" is, in this particular case, unhelpful.

Incorrect information is **worse** than no information.  So I'll probably remove the seating areas.  That means anybody using a tool to search for seating areas won't find them.  But it does mean that somebody looking for sheltered outdoor seating won't be led astray.  The presence or absence of shelter could be a deciding factor in somebody's plans and it's better that somebody avoid outdoor seating with shelter than make a special journey to outdoor seating that has no shelter.  Maybe I'll put a picnic table there instead: misleading but not entirely incorrect.

**Comment by kocio-pl** [comment]
Please don't ever tag for rendering. It's one of the worse problems in OSM, there's even special page about this (which is about breaking data):

https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer

Every icon is kind of misleading. For example basket icon in OSM Carto means convenience shop and in HOT it means shop - even if not every shop has baskets and there's no way to tell which map style is proper (so the second must be wrong).

Gastronomy rendering is also not showing the full possibility - there are for example bubble tea drinking places or milky bars, which are somewhat off currently shown categories.

**Comment by eehpcm** [comment]
@kocio-pl 

I'm fully that I should not use an incorrect tag to get the renderer to display something properly.  However, I am not proposing doing that.  I am proposing forgetting that a seating area exists and not tagging it at all rather than have something misleading be displayed.  I wouldn't delete anybody else's tags for that reason, but I am deeply unhappy with the current rendering.  As far as I'm concerned, I made a tagging mistake which I will rectify.  I mistakenly tagged a seating area **with a shelter** and there is no such thing there.

Yes, icons are kinda misleading.  Some more so than others.  I'm still interested to know if sheltered outdoor seating predominates globally because that definitely isn't the case around here.  And it rains a **lot** here, so people visiting here would like to know about sheltered seating if it exists.  If sheltered outdoor seating is far less common than unsheltered, which I suspect to be the case, a sensible interim solution would be to modify the icon.

**Comment by kocio-pl** [comment]
I guess picnic is about bringing your own stuff, while outdoor sitting is just about sitting out of the place, but with what you buy there, so I wouldn't mix them.

It's still about details - chairs alone can be used for different purposes. In my country I find shelters to be dominant, but it's rather umbrella against the sun than against the rain (there are also some more solid outdoor sittings with roof or tents).

**Comment by polarbearing** [comment]
> So I'll probably remove the seating areas.

Pleas keep tagging the world as it is. OSM data are not just rendered on one particular map, there are plenty with different specialisation, and other applications evaluating POIs with all their details. So even if in this map the icon is not perfect for your place, another application might build exactly on this detail.
