### ISSUE TITLE
Don't render the name of an area:highway.

### ISSUE THREAD

**Issue by BjornRasmussen** [gravitystorm/openstreetmap-carto#3247]
### Expected behavior: 
The name of squares is rendered.

### Actual behavior
The name of every "area:highway = ****" is rendered, causing the names of roads to appear in random places along the road.

### Links and screenshots illustrating the problem

![badareahighwayrendering](https://user-images.githubusercontent.com/37753777/40593710-48b0d24a-61f8-11e8-8fdc-ada97df01e30.PNG)
![badareahighwayrendering2](https://user-images.githubusercontent.com/37753777/40593740-7a6c1434-61f8-11e8-89ee-3217ecd2b1c5.PNG)

Location: https://www.openstreetmap.org/#map=15/35.9298/-79.0563

The reason for this is because a lot of roads are [added as areas](https://overpass-turbo.eu/s/z7O) in Chapel Hill, NC.

**Comment by pnorman** [comment]
This is nothing to do with area:highway, which we do not render. What you're seeing is that someone has tagged a named junction at each of those locations. This is an error. Named junctions are not commonly found in North America, where instead streets have names.

**Comment by BjornRasmussen** [comment]
Thanks!  I will fix the tagging at those locations.

**Comment by dieterdreist** [comment]
2018-05-28 5:07 GMT+02:00 Paul Norman <notifications@github.com>:

> This is nothing to do with area:highway, which we do not render. What
> you're seeing is that someone has tagged a named junction at each of those
> locations. This is an error. Named junctions are not commonly found in
> North America, where instead streets have names.
>

It is disputable if these are tagged as "named junctions", but it is clear
that osm_carto interprets the tagging as named junctions. According to the
wiki, junction=yes indicates "The presence of a road junction as such" (as
property on a road), while highway=junction represents a junction:
https://wiki.openstreetmap.org/wiki/Key:junction and
https://wiki.openstreetmap.org/wiki/Proposed_features/highway%3Djunction
IMHO the tagging of this place indicated a piece of road (as polygon) and
the qualifier junction=yes stated it is at a junction.

Inheriting a name for the (implicit) junction from the road polygon because
of the property junction=yes does not seem a consistent interpretation.
