### ISSUE TITLE
Coal heaps

### ISSUE THREAD

**Issue by chazanov** [gravitystorm/openstreetmap-carto#3270]
I am thinking about the rendering of coal heaps at power plants. They are mostly tagged as [landuse=landfill + substance/resource=coal](https://overpass-turbo.eu/s/zDK).

![At Scherer Plant](https://user-images.githubusercontent.com/39840300/41530683-462fea7e-72f1-11e8-85a5-c1ae7861116c.png)

Before proposing something I would like to figure out how to do it in code. Would this work (landcover.mss)?

```
[feature = 'landuse_landfill'] {
    [zoom >= 10] {
      polygon-fill: #b6b592;
      [way_pixels >= 4]  { polygon-gamma: 0.75; }
      [way_pixels >= 64] { polygon-gamma: 0.3;  }
    ['resource'='coal'] {
      polygon-fill: #374341;
    }
  }
```
Thank you.

**Comment by kocio-pl** [comment]
Please read about basic osm-carto facts and try to install development environment, so you could test the code using Docker containers:

https://wiki.openstreetmap.org/wiki/Standard_tile_layer
https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

If you will need some help, write about it here.

**Comment by chazanov** [comment]
Kosmtik fails because I'm missing a bracket in my code, but just can't find which one. Do you know a good bracket highlighter?

**Comment by SomeoneElseOSM** [comment]
@chazanov I've always used emacs to edit .mss files for exactly that reason (and when I used to use it with things like TileMill , they did use to "play nice" together - TileMill reloaded on file change by an external editor.  I'm guessing that Kosmtik will work the same way.).

**Comment by chazanov** [comment]
@SomeoneElseOSM emacs was a good hint.

My hassle started when I've cherry-picked a commit from https://github.com/imagico/openstreetmap-carto/tree/alternative-colors

Do you know where to get the z(!scale_denominator!) from?

```
kosmtik_1  | [httpserver] /openstreetmap-carto/tile/4/10/6.png?t=1529416267004 500
kosmtik_1  | Postgis Plugin: ERROR:  function z(numeric) does not exist
kosmtik_1  | LINE 46:               (CASE z(3.40282e+38)
```

**Comment by matkoniecz** [comment]
Is special rendering really needed in this case? I think that landuse=landfill is sufficient.

**Comment by Adamant36** [comment]
Tagging of coal waste sites as landuse=landfill seems wrong because the majority of currently active or former coal waste sites were at one-point ash ponds that contained water.  Even if they are dry now. Therefore, tagging them as an intermittent basin or reservoir be more appropriate. Some of them are already tagged that way. For reference there is over 310 coal ash landfills and 735 ash ponds in the USA. So only a little less than half are landfills. Although an argument could be mad for tagging them differently based on their current state, I think an intermittent water body would be the best middle ground.  Unfortunately, water=reservoir doesn't seem to have good reservoir_type tag for ash ponds. So that might be an issue. 
Another issue is the use of a landuse tag with either landuse=landfill, landuse=reservior or landuse=basin. Since ash ponds are usually on the grounds of power plants, which should already be tagged as landuse=industrial. Mapping the ponds as natural=water + water=reservoir + intermittent=yes + reservoir_type (or resource etc) would solve that though. 
The resource and substance tags have their own problems also. Even though resource=coal has 2493 uses, a lot of them probably aren’t associated with ash ponds. Whereas Substance=coal only has 33 uses. On top of those, there is also material=coal with 55 uses. Not to mention landfill:waste=ash. Although it only has 1 use. Along with 127 uses of the plant:source=coal. 
Out of all of them, plant:source=coal makes the most sense to use in this situation. Since coal in an ash pond or landfill is essentially a waste by product and not a resource, the resource=coal tag makes no sense. Neither does substance because an ash pond contains both water and ash. So, it is not comprised of a single substance. Material=coal doesn’t make sense for the same reason. Therefore, it makes more sense to just tag the whole industrial plant area or main building with plant:source=coal, which leads to the assumption that any waste product of it would also be coal, and leave it at that. 
Although I know tagging discussions are generally not to be had here, I felt like it would be useful to go over the current state of the tags that @chazanov  wants rendered. As its clear by doing so that there are some issues with rendering them that should probably be resolved before doing so. The different material tags could use some consolidating first. Along with the different types of landfills and reservoirs being expanded to incorporate something like an ash pond. It might be worth bringing up in the talk mailing list or the forums. Since there are over 1000 ash ponds in America alone that could be added to OSM and uniquely rendered on the map. If the tagging was more unified. Until then though, they probably shouldn’t have their own special rendering.

**Comment by chazanov** [comment]
@Adamant36 I'm totally open on the tagging. My proposal was only meant for coal heaps, not dealing with ash at all!

It would be bogus to tag an ash _pond_ as landuse=landfill.

reservoir_type could be a good choice, but IMHO ash ponds are not water reservoirs, but rather artificial basins.

**Comment by chazanov** [comment]
Do you know http://wiki.openstreetmap.org/wiki/Talk:Tag:landuse%3Dlandfill ?

**Comment by Adamant36** [comment]
@chazanov From my understanding coal heaps are created through mining and then sent to power plants for burning where they become ash correct?  Therefore, ash ponds are the only thing that would qualify for the landfill tag, because the tag is suppose is to be used for waste and coal heaps at power plants aren't waste until they become ash ponds. And I agree with you that they shouldn't be tagged as one. A few of the landfills tagged with the resource=coal tag are old ash ponds though. So it does happen. Also, the picture you included in your original post is of a dried up ash pond is it not? 

Although I'm aware that ash ponds are more like artificial basins and not water reservoirs, reservoir is the only slightly related tag that already has a type sub tag. I could almost see ash ponds fitting in as a type of reservoir since its similar to sewage, which has a tag, in the fact that its water stored with some substance. Whereas basin only seems to classify the different types into things that "catches storm water," which isn't the purpose of an ash pond. Plus it says nothing about holding substances. When the water leaves, there is an assumption the basin is empty. That's why I kind of thought the natural=water tag with resource and intermittent added it to would be good. There's a few lakes out there tagged with intermittent that have been empty for years. 

I'm aware of the Fine-grained classifications on the landfill discussion page. It doesn't look like they got integrated into the tag though and I still think the coal landfill example they give is more like an old ash pond. Especially since its next to a large body of water. I need to look into the process of burning coal more. I think it would help to bring this stuff up on the discussion pages of the tags and the mailing list to though. Maybe you could revive the suggestion in the landfill discussion page and see what other people think. I really have no clue what's best at this point. I just think rendering it should be held off until its figured out.

**Comment by dieterdreist** [comment]
I agree coal heaps aren’t correctly described with landfill. Tagging should be discussed elsewhere, my suggestion would be something like man_made=storage_area

cheers,
Martin

**Comment by kocio-pl** [comment]
It has only 37 uses now, which is much too few, and has no wiki page:

https://taginfo.openstreetmap.org/tags/man_made=storage_area#overview

I will close this ticket now until discussion on Tagging list will create some output we could use. Then it can be easily reopened.
