### ISSUE TITLE
Labeling priority

### ISSUE THREAD

**Issue by niquepolice** [gravitystorm/openstreetmap-carto#3278]
On the screenshot taken at zoom level 8 you can see Нижний Новгород(Nizhniy Novgorod) and Дзержинск(Dzerzhinsk) cities, but on the level 7 Nizhiny Novgorod disappears, though Dzerzhinsk, which is in fact several times smaller city, remains on the map. Is there any reason for that?

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=8/56.263/43.863
![image](https://user-images.githubusercontent.com/27158260/41861976-5504e4f4-78ab-11e8-969e-530f0c1fa6ee.png)

https://www.openstreetmap.org/#map=7/56.263/43.863
![image](https://user-images.githubusercontent.com/27158260/41861930-35b5c9f6-78ab-11e8-8e4d-1b817b67e79f.png)

**Comment by sommerluk** [comment]
> Is there any reason for that?

Yes. On z7, the label for [Нижний Новгород (Nizhniy Novgorod)](https://www.openstreetmap.org/node/27505889#map=11/56.3211/44.0620) is hidden by the label for [Нижегородская область (Nizhny Novgorod Oblast)](https://www.openstreetmap.org/relation/72195#map=7/56.341/45.198). The former is a `place=city`, which represents big cities. The latter is a boundary relation with `admin_level=4`, which represents federal states. In case of conflict (both labels cannot be rendered at the determined position because they would overlap), the boundary relations with against the city, because we consider it more important.

(The perfect solution might be to shift slightly the label for the boundary relation, but that’s technically not so easy…)

**Comment by niquepolice** [comment]
Thank you for your reply. I guess that label shifting is not a big algorithmic problem nowadays but unfortunately I'm not familiar enough with Carto's rendering process to understand technical difficulties. 

As for relative importance of federal state labels and big city labels, maybe ideally it should depends on the country, for example, on Google maps there no federal state labels in Russia and Kazakhstan by default, while in China and the US federal state labels have higher priority than cities.

**Comment by sommerluk** [comment]
In general, we try to use the same algorithm all over the world to create a consistent feeling of this rendering style, so likely we won’t treat Russia different from China.

In #1391 some there is yet some discussions about using “grid” placement to solve this problem. Therefor, I’ll close this issue as duplicate. Thanks for your report! Discussion can be continues in #1391
