### ISSUE TITLE
Add icon for denomination=jehovahs_witness

### ISSUE THREAD

**Issue by HALCONDEORO** [gravitystorm/openstreetmap-carto#3282]
Hello everyone I want to propose the change of icon for the Christian religion = jehovahs witness, now we can see it like this:
![indice](https://user-images.githubusercontent.com/13104419/42117772-f41c4c98-7bfe-11e8-9881-aa53f7faccbd.png)

As an icon of a person kneeling praying, I think it is the generic one for those who do not have a common denomination.
From there I want to change it and present this icon, it's my first time presenting some improvement to the map, so if I have something else forgive me.

Here the icon:
![jw icon](https://user-images.githubusercontent.com/13104419/42117746-d0486f4a-7bfe-11e8-921f-3c128529c3c0.png)

Currently has almost more than 5000 uses, we can see here:
https://taginfo.openstreetmap.org/search?q=jehovahs_witness#values

**Comment by Adamant36** [comment]
@Tomasz-W they have the Watchtower symbol. There's some pretty simplistic versions of it online that would a good icon. Maybe it could be combined with the JW or something so its not confused with a regular watchtower. Although it would be SJ in polish, JW is probably pretty universally well known as their abreviation and it would theoretically be easy to tell the meaning from it being attached to a church building or religious area. Where as there is nothing catographically speaking about social justice warriors that I know of. They dont have meetings, own buildings, etc etc. So I doubt anyone would mistake it for that. Although, honestly I think if done right the watchtower symbol would probably work good enough. By itself.

**Comment by sommerluk** [comment]
In general we keep this style region-agnostic, what would mean avoid letters in a particular script within icons. 5000 uses is not so high usage, so the symbol must be really intuitive to work. If not, it’s just a symbol that is seldom used and nobody will recognize it because you don’t remember in which context you have seen it last time. I think a watchtower is _not_ intuitive.

**Comment by Adamant36** [comment]
@sommerluk my bad. I thought the general OSM rule is that it goes by British English. Like the use centre instead of center. I wasnt aware that didnt extend to the style. I do agree that letters in icons is probably not a good idea in general. I think people who know what the watchtower is and are looking for a church from that particular denomination will understand it though. Id guess most people know  including myself dont know what a kissing gate is let alone do I, but there is still an icon proposel it. So there are icons already that only appeal to a certain nitch. 
As a related side note, I happen to be looking at the values for the name tag the other day and there are currently over 2000 uses of the name "Kingdom Hall of Jehovah's Witnesses" Thats about half as many as are tagged. I dont know if each individual kindom hall has its own unique name or not, but id guess at lot of those are probably named that in violation of the name rule so people can tell them apart from just a normal Christain church on the map. Adding an icon would probably help with that a lot.

**Comment by Adamant36** [comment]
Isnt the Hinduist symbol Sanskrit letters that mean Aum or Om?

**Comment by meased** [comment]
According to [the wiki,](https://wiki.openstreetmap.org/wiki/Key:denomination) I believe the church in the original post is tagged wrong (but there is no link). It shouldn't be `religion=jehovas_witness`, it should be:

```
amenity=place_of_worship
religion=christian
denomination=jehovas_witness
```
It would then be rendered with a cross, which I believe is the most appropriate icon ("JW" is not an icon, it's just more text).

**Comment by HALCONDEORO** [comment]
They do not use a cross to identify themselves as Christians as we can see here, their official website:
https://www.jw.org/en/jehovahs-witnesses/faq/cross-belief/
I do not think it is convenient to use an icon that does not represent them, it may be convenient to surround the acronym JW or the symbol of the watchtower is convenient.

**Comment by lakedistrictOSM** [comment]
> They do not use a cross to identify themselves as Christians as we can see here, their official website:
https://www.jw.org/en/jehovahs-witnesses/faq/cross-belief/
I do not think it is convenient to use an icon that does not represent them, it may be convenient to surround the acronym JW or the symbol of the watchtower is convenient.

They probably are tagged correctly, but there's code to render them without the cross:
https://github.com/gravitystorm/openstreetmap-carto/blob/85918db08c0e5df3d16276906f2597380ddd0663/amenity-points.mss#L558-L561

eg https://www.openstreetmap.org/way/343416512

**Comment by meased** [comment]
> I do not think it is convenient to use an icon that does not represent them

Taco Bell has a burger icon. An icon is supposed to be symbolic. There is already special rendering to avoid the cross, and I think the kneeling figure is the next best icon (for both JW and non-JW). I don't see an issue here.

**Comment by dieterdreist** [comment]
sent from a phone

> On 30. Jun 2018, at 22:31, meased <notifications@github.com> wrote:
> 
> Taco Bell has a burger icon.


this is not a suitable analogy, people do not believe in burgers. It is better not to put an icon than one that is not appropriate.

**Comment by HolgerJeromin** [comment]
Ref #1058

**Comment by matthijsmelissen** [comment]
Thanks for all the work on this. However, I think adding an icon for Jehovah's Witnesses is way too specific. If we do this, we'll end up adding an icon for every single denomination. I think the silhouette of the worshipping perfect is perfectly fine.

I'd propose therefore to reject this issue.

**Comment by dieterdreist** [comment]
sent from a phone

> On 1. Jul 2018, at 09:44, Matthijs Melissen <notifications@github.com> wrote:
> 
> I think adding an icon for Jehovah's Witnesses is way too specific. If we do this, we'll end up adding an icon for every single denomination.


currently used 5700 times

**Comment by sommerluk** [comment]
> I'd propose therefore to reject this issue.

Yes, me too. “JW.org” isn’t an icon, but an Internet address. The usage is with 5 700 not really so high that is needs an own icon, and the map usage will be less intuitive. (By the way, I have in general the feeling that recently our icon set becomes a little bit over-differentiated.)

**Comment by kocio-pl** [comment]
Ok, so thanks for the report, but I agree that the current icon is better than proposed solution, so I close the issue. If there will be another solution in the future, it could be reopened.

**Comment by Slawek234** [comment]
Hallo. I propose cross + crown in one symbol. Examples: https://upload.wikimedia.org/wikipedia/commons/6/65/Crosscrown_2.png https://en.wikipedia.org/wiki/File:Crosscrown.svg
A more modern form that I suggest:
https://s33.postimg.cc/fvvy50ny7/cross.png

**Comment by kocio-pl** [comment]
Where did you get this idea? How is it related to JW?

**Comment by Slawek234** [comment]
> Where did you get this idea? How is it related to JW?

From the Internet e.g key words "jehovah's symbol" https://duckduckgo.com, http://google.com, https://yandex.com,

**Comment by HolgerJeromin** [comment]
> From the Internet e.g key words "jehovah's symbol" https://duckduckgo.com, http://google.com, https://yandex.com,

Have you done more than a visual image search? :-)

https://jehovahswitnessesexhibition.weebly.com/items-and-artifacts.html
>  Since 1936, Jehovah's Witnesses have rejected the belief that Jesus died on the cross. They believe that the place of death was a wooden stake. 


> @Slawek234 
> The ID editor during work shows the correct religion symbol.

iD renders a cross. The whole github issue comes from the point hat the cross is a wrong icon for JW.

**Comment by jeisenbe** [comment]
This is a great idea for this specific issue (JW),, but I don't believe it
would work well as a general rule. It isn't practical to render different
symbols for every denomination tag. It would be too difficult for the map
user to interpret several different shapes of cross for different Christian
denominations, for example.

We could decide that certain demoninations are different enough that they
count as different religions, but that would be controversial. While I
personally consider JW and LDS (mormons) to be different religions, they
self-identify as Christians. There are many similar non-orthodox sects in
Africa and Asia.
And what about Orthodox vs Catholic vs Protestant? Sunni vs Shia vs Ahmadi
other Muslim sects? Wikipedia lists: Khawarij, Ibadi, Zaidiyyah, Twelver,
Kektashisa, KalmaIt etc.

Sticking with rendering the religion type only is probably the most useful
solution for the general map user, since the names and symbols of the
largest religions are well known, while those of denominations or sects are
not.
