### ISSUE TITLE
Add bowlings

### ISSUE THREAD

**Issue by IVAN-RSM** [gravitystorm/openstreetmap-carto#3297]
The bowling alleys are well-known places and there are thousands all over the world. The icon should be made.

Tag: leisure=bowling_alley

**Comment by Adamant36** [comment]
I was looking at this the other day. Its got 1764 uses. So it might be worth having an icon. There's also sport=9pin and sport=10pin that could be considered to. They have 1136 and 2277 uses respectively. There's 3,413 of them. Which is a thousand more then leisure=bowling_alley has. So they might be getting tagged with leisure=sports_centre instead of leisure=bowling_alley. Unfortunately the combinations being used with them wont show up. But at least it means there are more then just the ones tagged as leisure=bowling_alley that would potentially make it worth adding an icon. Not to mention their potential for mapping. 

Any suggestions on a potential icon might help move things along

**Comment by dieterdreist** [comment]
sent from a phone

> On 9. Jul 2018, at 14:31, Adamant36 <notifications@github.com> wrote:
> 
> I was looking at this the other day. Its got 1764 uses. So it might be worth having an icon. There's also sport=9pin and sport=10pin that could be considered to. They have 1136 and 2277 uses respectively. There's 3,413 of them. Which is a thousand more then leisure=bowling_alley has.


if I understand leisure=bowling_alley correctly, it is for a dedicated facility which typically has many bowling lanes (and maybe a restaurant, a parking, etc.). The sport tag might be applied to individual bowling lanes as well, either in a bowling alley, but also for situations with just 2 or so lanes, for example in a pub, hotel or similar.

**Comment by Tomasz-W** [comment]
Icon proposal:

![leisure bowling_alley](https://user-images.githubusercontent.com/25656654/42503665-89bc817c-8439-11e8-9ef2-277b2c5aafd4.png)

**Comment by Tomasz-W** [comment]
I agree to use the icon also for `sport=9pin` and `sport=10pin` tags

**Comment by dieterdreist** [comment]
sent from a phone

> On 10. Jul 2018, at 12:21, Tomasz Wójcik <notifications@github.com> wrote:
> 
> I agree to use the icon also for sport=9pin and sport=10pin tags
> 


for which features? The „sport“ key is a property.

**Comment by Adamant36** [comment]
I dont think it would work for sport=bowls as going by the discription the game doesnt use pins. It might be worth doing another issue for though. Especially considering its use is pretty high.

**Comment by Adamant36** [comment]
@dieterdreist You might be right about how the sport tag should be applied, but going over some of the 9pin and 10pin key uses on Overpass Turbo it seems to be pretty varied. There's usages attached to buildings of bowling alleys, bars, hotels, sports centers and just normal buildings. So it seems like they are often used more as a property for other only vaguely related things that aren't necessarily bowling alley related or as points/areas inside other things. You can't change a hotel icon to a bowling one just because the building has sport=9pin attached to it, but that doesn't mean 9pin shouldn't have an icon either.  So I don't know. I guess its something to figure out. Maybe a better definition of their tagging is needed on the wiki pages. At this point 9pin is just a stub, which probably contributed to the problem.

**Comment by dieterdreist** [comment]
sent from a phone

> On 11. Jul 2018, at 10:10, Adamant36 <notifications@github.com> wrote:
> 
> There's usages attached to buildings of bowling alleys, bars, hotels, sports centers and just normal buildings. So it seems like they are often used more as a property for other only vaguely related things that aren't necessarily bowling alley related or as points/areas inside other things.


this usage is probably ok (although it doesn’t scale, with only one tag for it and reluctance for multiple values), it is how the sports tag is intended, but for osm carto it means we should look for those combinations (with a feature) that merit the icon. For example a shop dedicated to selling bowling equipment would also get the sport tag, but should not be rendered like a bowling alley.

**Comment by Tomasz-W** [comment]
I didn't know about whole "properties" category: https://wiki.openstreetmap.org/wiki/Properties , but after bowling shop example I can understand the problem.

Anyway, I don't think it is an argument for not adding icons for sport=* key at all. We can distinguish them to green icon for combination with` leisure=sports_centre` / `leisure=pitch` and violet for combination with `shop=*`

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/6f76878b09bee58b091ef84867a0a2b2

**Comment by Adamant36** [comment]
@Tomasz-W I think we should probably do the pull request for this one on its own and have seperate issues for 9pin/10pin. Since it seems like they need to be worked out seperately.

**Comment by Tomasz-W** [comment]
@Adamant36 I checked the icon, everything is ok.

**Comment by kocio-pl** [comment]
It has 1 813 uses and a wiki page:

https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dbowling_alley

The icon is nice and I don't see competing tag scheme, so I'm going to merge it. Usage is increasing at high rate, so I think it's safe to do it:

![taghistory 23](https://user-images.githubusercontent.com/5439713/43138734-1e37a860-8f50-11e8-82df-b167090c52a6.png)

**Comment by Adamant36** [comment]
@Tomasz-W Thanks. Looks ok to me too. I say its mergable.
