### ISSUE TITLE
Riverbanks aren't rendered

### ISSUE THREAD

**Issue by Robot8A** [gravitystorm/openstreetmap-carto#3333]
### Expected behavior
They are rendered

### Actual behavior
They aren't

### Links and screenshots illustrating the problem
![imagen](https://user-images.githubusercontent.com/19521377/43770429-9c33252c-9a3c-11e8-9179-46fa149da793.png)

https://www.openstreetmap.org/#map=16/41.6543/-0.8646

**Comment by imagico** [comment]
That is most likely because the multipolygon is broken which will be the case most of the time with unmaintainable crap like this:

https://www.openstreetmap.org/relation/16319

So the solution is to break this into well manageable pieces and they will show up nicely in the map (except for the low zoom levels of course where you will have to actively ignore the effects of #2873).

PS: You always should provide a link to the place where you observe a problem so people do not need to waste time in researching where you look at first.

**Comment by Tomasz-W** [comment]
@Robot8A You can look for potential relation gaps/ errors here: http://ra.osmsurround.org/analyzeMap?relationId=16319

**Comment by Robot8A** [comment]
User Edvac changed the tagging to natural=water without changing any of its members and now it gets rendered

**Comment by mboeringa** [comment]
@Robot8A ,

There was actually a single node that appears to have been accidentally moved at the very end of the Rio Ebro where it flows into the Mediterranean Sea, that caused a self intersection the riverbank multipolygon.

This was easily detectable in JOSM, and the only error reported.

I have now fixed it. Actually, while I was on it, someone else (user Edvac) seems to have detected the same issue and already moved the offending node a bit to solve the self-intersection, causing a conflict with my edit. I resolved that, and than moved the node to a more appropriate location at the center of the riverbank, as Edvac forgot to do this.

So the issue should now be fine and resolved.

**Comment by mboeringa** [comment]
> User Edvac changed the tagging to natural=water without changing any of its members and now it gets rendered

This has likely little to do with it. If the waterway=riverbank was rendered before, it should have been now without a change to natural=water, water=river. The self-interesection is a likely cause of a rendering error though, but now also resolved.

**Comment by kocio-pl** [comment]
Since it's a tagging problem, I will close it.
