### ISSUE TITLE
Render elevation with different tourism objects

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3382]
Currently we render elevation data only for `tourism=alpine_hut` and `amenity=shelter`:

https://github.com/gravitystorm/openstreetmap-carto/blob/0ba5691dd2c4075ed35bd3ce5884dd92f0e4b985/project.mml#L2105-L2106

but I've found that there can are other similar objects with `ele=*` tag, like [this wilderness hut](https://www.openstreetmap.org/node/5864496999) and for example [2 556 hotels](https://taginfo.openstreetmap.org/tags/tourism=hotel#combinations).

**Comment by Tomasz-W** [comment]
I'm not sure if adding `ele=*` value to labels of elements different than peaks/ volcanoes is a good direction. As I was in mointains this summer, I can say that elevation of peaks was surely enough (for me), so I would even exclude alipine huts and shelters to avoid map cluttering.

**Comment by kocio-pl** [comment]
My take would be that in the outdoor we have a lot less objects (POIs) and the clutter is not a problem there in general. And I find it common to give the elevation information as one of the most important things for mountain accommodation places - for example: http://www.schronisko-ornak.pl/o-schronisku/informacje.html

We have also added it lately for guideposts, see https://github.com/gravitystorm/openstreetmap-carto/pull/3198#issuecomment-385201427.

**Comment by dieterdreist** [comment]
sent from a phone

> On 6. Sep 2018, at 10:54, Tomasz Wójcik <notifications@github.com> wrote:
> 
> As I was in mointains this summer, I can say that elevation of peaks was surely enough (for me), so I would even exclude alipine huts and shelters to avoid map cluttering.


I am in favor of rendering ele for alpine huts. Besides the name it is quite an important information in the mountains to know the elevation. And it is therefore typical to show it on maps. These are also typically/often signed at the location (although general uncertainties about the reference system apply, like for all ele tags)

**Comment by jragusa** [comment]
I'm also support to add elevation for wilderness hut. It's an important information to estimate the required time to access it.

**Comment by matkoniecz** [comment]
> 2 556 hotels.

I see no reason to display elevations for hotels.

**Comment by matkoniecz** [comment]
Primarily, because (in overwhelming majority) hotels will be accessed not by mountainous hiking route but rather by car/bus/aerialway.

As result importance of elevation is much lower.

Also, hotels are less likely to be located near mountaintops compared to alpine huts.

Second problem is that there is no good way to distinguish "hotel in mountains" and "hotel not in mountains" and would encourage tagging for rendering (removing elevation data in cases where people dislike rendering it)

**Comment by kocio-pl** [comment]
Do you have opinion on rendering elevation for other accommodation objects?

**Comment by matkoniecz** [comment]
In general - I think that alpine huts are exception, with location in mountains and access primarily by mountainous hiking routes (and even then I am unsure about rendering elevation data).

Wilderness huts may be a candidate, but based on my (limited) experience and knowledge this type of object tends to not occur in high mountains where elevation info is very important.

So overall I think that current situation is OK.

**Comment by Adamant36** [comment]
According to the wiki wilderness huts dont explicity exclude mountainous huts. The example picture of one looks likes a mountainous hut also. According to Wikipedia "usually located in wilderness areas, national parks and along backpacking and hiking routes." Id all those scenerios could either potentially qualify as mountanious, or at least have enough elevation change between wilderness huts that it would be useful to know if the difference in elevation between them would be worth the hike to another one or not.

 In general, I doubt out of 6 million uses of elevation that alpine huts and shelters are the only useful combinations worth displaying. Theres also plenty of situtations where elevation is useful outside of just mountainous areas. Any wilderness thing could potentially benefit from elevation. Otherwise why are there so many instances of it? 

Id like see it rendered on lakes, since I visit and map them a lot. And it would be good to know their elevation before trecking my bike out to them. So I'll have a good idea of the itensity of the ride before hand and can plan accordingky. Not having it rendered makes me less inclined to add it once I get out there also. Im not requesting it be rendered, but I think it should be for wilderness huts for the reasons given by me and others above.

**Comment by HolgerJeromin** [comment]
Numbers attached to names collides with housenumbers. 
So tagging for the renderer or be confused (osmand adds housenumber behind) are both two problems to avoid.

**Comment by Adamant36** [comment]
Would it be possible to render elevation based on an elevation check so things below a certain elevation just wouldn't get rendered with it?

**Comment by sommerluk** [comment]
Technically: Yes (In the SQL query. For waterfalls, for example, we are yet filtering values lower than 0 because these values doesn’t make sense and are tagging errors. The same would work with different thresholds.)

However it is doubtful that we manage to have a reasonable threshold. In some higher regions, you might have a plateau with towns on it and don’t want the elevations (almost all of Spain is a plateau, for example, and there are not so many mountains). Other regions might have lower elevation, but nevertheless mountains that are difficult to access and which are typical hiking regions.

Having the elevation value sometimes rendered and sometimes not, based on an arbitrary threshold, would probably be surprising and therefore confusing for the mappers. As feedback for mappers is one of our primary goals, I wouldn’t do this.

**Comment by kocio-pl** [comment]
Given lack of approval, I will close this ticket. If somebody will find suitable kind of object where it would make sense, we can discuss it further.

**Comment by jragusa** [comment]
I guess that an approval can be reached about `tourism=wilderness_hut`. We can admit that some of them occurred in mountain locations as indicated by the [comment](https://github.com/gravitystorm/openstreetmap-carto/issues/3382#issuecomment-423770572) of @geowOSM. Concerning low elevated locations, I would like to raised that `amenity=shelter` is also concerned since they are even mapped in cities and it is not necessary to render elevation in this case.

So if we want to be consistent, I think we have two possibilities:
1/ adding rending of elevation to `tourism=wilderness_hut` to support mountain huts or,
2/ removing elevation to shelter if we consider that's not recommended for low elevated location (both shelter and wilderness_hut)
