### ISSUE TITLE
Add rendering for leisure=dog_park

### ISSUE THREAD

**Issue by alexandre-mbm** [gravitystorm/openstreetmap-carto#341]
[leisure=park](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpark) is used for  public recreation spaces in Brazil. These parks can contain dog parks. But **[leisure=dog_park](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Ddog_park)** isn't rendering over leisure=park. [See here](http://osm.org/go/PT3umyZfZ).

It would be interesting a [leisure=garden](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgarden) similar rendering, adding a soft edge in order to contrast the green background.

**Comment by neiljp** [comment]
Given some recent objects I've come across, it would be interesting to see these rendered (darker/hatched green? little dog image inside?), and with waste=* tags and the waste bins starting to be rendered, these combined features would make dog walking a useful application of OSM :)
(I'm not a dog walker/owner, though)

**Comment by 1ec5** [comment]
There are standalone dog parks, too, and it’s unfortunate that those parks are left unstyled and unlabeled.

**Comment by kocio-pl** [comment]
I think that might be another candidate to have [colored borders](https://github.com/gravitystorm/openstreetmap-carto/issues/1628#issuecomment-117995646).

**Comment by dieterdreist** [comment]
I propose a highly transparent black fill (won't change colors), eg rgba 0,0,0,0.15

These will typically have fences, hence an outline.

**Comment by jdhoek** [comment]
Based on the icon contributed by Giardia, I have created a first draft of this feature. Comments welcome.

* Fill colour is `darken(@park, 5%)`, visible from zoom-level 10 onwards
* Dog paw icon is drawn from zoom-level 16 onwards
* No outline

I have omitted the outline, because the tag `leisure=dog_park` can mean either a standalone fenced of area, or a larger area in a park where there may not be any fence (instead relying on natural boundaries and attentive dog owners). The latter is the case in the example shown here, which is a real park in The Netherlands.

## Examples

Screenshots from Kosmtik. Please ignore the misaligned bridge, that was a mistakenly moved point since restored.

### Zoom 16

![dog16](https://cloud.githubusercontent.com/assets/683699/16660692/cf6c30ca-446f-11e6-96e2-dfef4865d4d0.png)

### Zoom 17

![dog17](https://cloud.githubusercontent.com/assets/683699/16660694/cf6e8ca8-446f-11e6-803b-4f568e57f195.png)

### Zoom 18

![dog18](https://cloud.githubusercontent.com/assets/683699/16660766/1053d9a8-4470-11e6-8fe3-11e7ce24d8e0.png)

### Zoom 19

![dog19](https://cloud.githubusercontent.com/assets/683699/16660765/105306b8-4470-11e6-8eda-e1cc277d5c85.png)

**Comment by kocio-pl** [comment]
Nice idea, but looks to me too like natural=scrub. Could you try to modify it to be easier to recognize?

**Comment by jdhoek** [comment]
Slightly more explicit paws, darker and larger. Compare with the `natural=scrub` on the left.

![dog17a](https://cloud.githubusercontent.com/assets/683699/16661609/009884ba-4474-11e6-937a-04c2c45bfa0e.png)

I'd rather not change the hue of the green in order to stay with the park's fill colour.

**Comment by kocio-pl** [comment]
Thanks, it works for me!

**Comment by jdhoek** [comment]
Great. PR will follow when I finish implementing the bit for point as well as the area.

**Comment by jdhoek** [comment]
Points now show just the paw icon.

![dogs](https://cloud.githubusercontent.com/assets/683699/16666067/5109aca0-4486-11e6-9cf1-aa9cdf077554.png)

I am happy with the polygon area which in this sample has a name, but I can't figure out how to render the name of the point below its icon, without also moving the text of the polygon down. That is, I can add `text-dy: 12`, and the name of the point will show up neatly below the paw icon, but that also moves the text of the polygon dog-park down. Anyway to achieve what I want without that happening?

**Comment by jdhoek** [comment]
This is what happens when I introduce `text-dy: 10`.

![dogstoolow](https://cloud.githubusercontent.com/assets/683699/16666193/d986496c-4486-11e6-9fda-75b9f551fa4b.png)

The point looks great, but the polygon has its text too low. Is there a way to apply styling only to point-based targets?

**Comment by math1985** [comment]
Looks nice, thanks for your work!

For areas, we use italic text that scales with area size. See for example the rules for the text for forest. Perhaps it works to create two different rules, one for areas and one for points?

I don't think we currently distinguish between areas and points, but maybe it works to pass an extra constant in the relevant SQL queries (there is one query for areas and one for points)?

**Comment by jdhoek** [comment]
![dogsitalic](https://cloud.githubusercontent.com/assets/683699/16667330/3411e698-448c-11e6-8a79-c1ba196251fd.png)

This adjusts the styling to match common area styling.

**Comment by jdhoek** [comment]
Perhaps I'll leave it like this for now. If a dog park has a name, it won't be shown if the park is defined on a point, but behaves as expected when defined on a polygon. Most dog parks appear to be polygons. I have no idea how many dog parks actually have names — the one I added (and which lead me to this issue) is part of a larger park.

**Comment by HolgerJeromin** [comment]
I think detail mapping with a name is often combined with mapping as an area.
