### ISSUE TITLE
Orange dot for gastronomy on z17

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3410]
Follow up to #2945.

Now that we have special color for gastronomy, using orange dot on z17 should be clear enough. I also got used to the idea of urban priority on universal map (see https://www.openstreetmap.org/user/kocio/diary/44769 ) and dots are better known than it was a year ago (entrances have squares, we used blue dots for offices).

I would just leave food court icon on z17, since this is about bigger eating space, it would also distinguish it from restaurants.

[Warsaw, Old Town](https://www.openstreetmap.org/#map=17/52.24948/21.01222)

Before
![3gineevx](https://user-images.githubusercontent.com/5439713/45925087-0b4fe480-bf0f-11e8-9e89-39adf2b19ec6.png)

After
![r5vj1hit](https://user-images.githubusercontent.com/5439713/45925088-0c811180-bf0f-11e8-989a-603cfc94529e.png)

[London, Soho](https://www.openstreetmap.org/#map=17/51.51348/-0.13332)

Before
![48esq1ph](https://user-images.githubusercontent.com/5439713/45925168-ab5a3d80-bf10-11e8-9023-1d58afe988ee.png)

After
![e7cizqu5](https://user-images.githubusercontent.com/5439713/45925170-aeedc480-bf10-11e8-9ad5-2587e609a4c0.png)

**Comment by Tomasz-W** [comment]
Generally I like this idea, but I can see a little problem with it at the moment - if you change all gastronomy objects to dots at z17, then eg. memorials, artworks or post boxes becomes "more important objects". I think it denies 'size rule' which you are promoting by yourself. I propose to finish https://github.com/gravitystorm/openstreetmap-carto/pull/3372 and https://github.com/gravitystorm/openstreetmap-carto/issues/1745 first, and then test dots for gastronomy objects. I also thought about leaving an icon for amenity=restaurant, because culturally it's usually taken as more serious object than eg. amenity=fast_food. Another example is amenity=theatre vs amenity=nightclub. Is really one of these places always more important than the second? I'm not sure,

**Comment by matthijsmelissen** [comment]
I’m strongly in favour of this proposal.

It will make dense urban areas easier to read, while still making map users aware of the location of gastronomy amenities.

**Comment by kocio-pl** [comment]
> if you change all gastronomy objects to dots at z17, then eg. memorials, artworks or post boxes becomes "more important objects"

Post boxes are small and deserve demoting to z19+ anyway, artworks can be of different size and it looks like their density is not too big, as I was afraid initially, memorials also have different sizes and it looks that they are OK between monuments and plaques (but initial zoom level for general monuments might be tuned when we have more subtypes rendered due to #3356).

> I think it denies 'size rule' which you are promoting by yourself.

I'm still trying to shape it so this is more useful in practice, not just a slogan or intuition.

Changing icon does not change initial zoom level (they are still there) and I find it to be a good compromise. It was hard for me to get along with the similar idea for shops, but in the end this seemed to be the only consensus we could get. I like it now and gastronomy makes the same problem in some places, so I think it makes sense to have better clarity without demoting them.

> I  also thought about leaving an icon for amenity=restaurant, because  culturally it's usually taken as more serious object than eg.  amenity=fast_food. 

The reason for this change is visual clutter, not lack of importance or size issues. I'm afraid that restaurants alone can make most of the clutter themselves, so they are actually first to be touched here:

![taghistory 33](https://user-images.githubusercontent.com/5439713/44884485-df4c9500-acbb-11e8-8ff8-49e89ea2fa74.png)

> Another example is amenity=theatre vs  amenity=nightclub. Is really one of these places always more important  than the second? I'm not sure,

This is categorization problem and again it's not about importance. Cultural/entertainment objects do not clutter the space as gastronomy does in general. Night club is both drink bar and dancing or concert place, so it's on the edge of categories.

**Comment by polarbearing** [comment]
While this is a good idea for those inner cities, a lone in the countryside is harder to spot then. 

A solution would be to make the dot-vs-icon decision based on density of these features, not sure how difficult that is to code.

**Comment by kocio-pl** [comment]
I agree that urban/outdoor differentiation would be proper solution. However this is huge general problem, still unsolved, see #1957.

**Comment by Adamant36** [comment]
I was thinking about this the other day. It might be possible to do it based on population density of an area as a variable for what to display and how. I was actually reading something about it somewhere. Although, doing it that way might have its own problems. Like, I don't know if population density is a good correlative to how many gastronomy related places are actually in an area. Plus, a lot of places might not have population data in the first place.

**Comment by kocio-pl** [comment]
It would be useful for all kind of objects, not just gastronomy. Please look at this ticket and see some ideas at the end. Let's discuss outdoor problem there.

**Comment by dieterdreist** [comment]
2018-09-23 10:55 GMT+02:00 Matthijs Melissen <notifications@github.com>:

> It will make dense urban areas easier to read, while still making map
> users aware of the location of gastronomy amenities.




it only makes it easier to read if you are aware that the orange dots are
standing for fast food, cafe, bar, restaurants and nightclubs, but it add a
new problem: distinguishing purple and orange dots, and if you are not
aware of the meaning of orange, you cannot read the map any more (as
opposed to before, where you did not have to know the colors, because the
icons told you specifically what is was).

Usually, you are not looking for any of a pub or a restaurant or a
nightclub or a fast food. These are all very specific and if you look for
one, the others won't do (generally).

**Comment by kocio-pl** [comment]
For me this is the same case as with shops: you see the dot, you make zoom in and see what kind of objects with this color are there, and you know their meaning very soon.

**Comment by kocio-pl** [comment]
> Another example is amenity=theatre vs amenity=nightclub. Is really one of these places always more important than the second? I'm not sure,

After some more thinking, I guess we should simply recategorize nightclub as entertainment/cultural object, because drinking is not the main thing there, rather dancing, live shows (like stand-up or anything like this) etc. Moreover this is not even in the same league of clutter as gastronomy POIs:

![taghistory 51](https://user-images.githubusercontent.com/5439713/46575582-4e529300-c9b8-11e8-95f1-2c6392cd50bf.png)
