### ISSUE TITLE
Adjust rendering of man_made=mast and communications_tower based on height

### ISSUE THREAD

**Issue by boothym** [gravitystorm/openstreetmap-carto#3414]
https://wiki.openstreetmap.org/wiki/Tag:man%20made=communications%20tower

It's rendered from z13, which is how I noticed these in the first place - they are quite prominent compared to other masts/towers. You can see five of them in this location:
![screenshot_2018-09-24 node 5117170551 openstreetmap](https://user-images.githubusercontent.com/16965772/45947979-20e80b80-bfee-11e8-9952-7652b9a9ef81.png)
However as you can see, none of these are "huge towers" as defined by the wiki: 
- https://binged.it/2OH6Ubz 
- https://binged.it/2QUlyO4 
- https://binged.it/2xILZO9 
- https://binged.it/2xMs68Y 
- https://binged.it/2xMslko

And having looked at overpass-turbo I'm guessing most of the 4,000 objects in OSM are incorrectly tagged as well - varying from small mobile (cell) sites, to towers <100m and tall masts. 

To me it seems like a redundant tag to render - one solely used for huge towers - when OSM-carto already renders masts and towers at different zoom levels according to their height. 

**Many of these communications_tower objects are already tagged with their height, so there'd be no difference if they were retagged as a tower.**

To further show how redundant this tag is:

- the 2nd tallest in Germany isn't a communications_tower: https://www.openstreetmap.org/way/10612387
- even the example photo in the wiki is not tagged as a communications_tower - again it is a tower with height: https://www.openstreetmap.org/way/119400748

yet both are still rendered from z13.

### **Mast rendering at z13/14**

Also related to this is the lack of rendering of tall masts at z13. For examples, the tallest structure in the UK at 350m is only rendered from z15: https://www.openstreetmap.org/node/2512753621

This is even more noticeable around the town of Dover. There is a 111m tower rendered to the east, a smaller communications_tower (which looks like this: https://goo.gl/maps/MBXpcRBKTvK2) rendered to the north east - but the 243m mast does not appear at z14! https://www.openstreetmap.org/node/866619623#map=14/51.1316/1.3002

**So my proposals are:**
- remove the icon for man_made=communications_tower (it's a good icon, maybe use it for something else - towers > 100m?)
- render masts from z13, with similar height logic as towers
- retag communications_tower objects as masts/towers (might need a discussion on the tagging list)

P.S. - I can't find much discussion about rendering this tag when searching this repo, so might be worth reviewing how it was implemented in the first place.

**Comment by dieterdreist** [comment]
as your suggestion is to retag things and or redefine tags you should first get this done or at least start a discussion about it to see what is the opinion of others, then the rendering can be adjusted to the new situation.

**Comment by boothym** [comment]
> then the rendering can be adjusted to the new situation.

To be honest I'd quite like the rendering adjusted to the **_current_** situation before going any further - which would be to not render this tag in the first place!

It is poorly defined - given it is essentially a duplicate of man_made=tower + tower:type=communication + height>100 - and inconsistently tagged as shown in the OP. There doesn't seem to have been any discussion about adding the tag, which only has 4k uses compared to towers + masts with 239k + 75k.

If I was to retag things, then I'd suggest that most of these objects would no longer be tagged as man_made=communications_tower - at that point I don't think it would make sense to render it either.

**Comment by kocio-pl** [comment]
It was my understanding that this is special kind of towers, but since it was the whole set of towers, it was not discussed more clearly. I'm happy with tuning it now, however definition was OK for me and I also like to see the discussion if you think it's wrong or there is some confusion.

**Comment by dieterdreist** [comment]
2018-09-24 14:38 GMT+02:00 Michael Booth <notifications@github.com>:

> It is poorly defined - given it is essentially a duplicate of
> man_made=tower + tower:type=communication + height>100
>


this is a tagging discussion



> - and inconsistently tagged as shown in the OP. There doesn't seem to have
> been any discussion about adding the tag, which only has 4k uses compared
> to towers + masts with 239k + 75k.
>


4k usage is not few for a tag that describes big television towers. If most
of these are corresponding to the wiki description, I would not see a point
where it could be critizized. Inconsistent application is generally
something to be worried about. If these are singular problems, they should
be retagged, if it is a significant systematic problem, something more has
to be done (e.g. remove support here).

**Comment by boothym** [comment]
>4k usage is not few for a tag that describes big television towers. If most of these are corresponding to the wiki description, I would not see a point where it could be critizized. Inconsistent application is generally something to be worried about.

The point I am making is that most of these do **not** correspond to the wiki description. None of the examples in the OP are "big television towers" and I doubt many (if any) of the ~240 examples in the UK are either. 

If I was proposing to render this for the first, it would rightly be scrutinised and probably rejected! Especially as CARTOGRAPHY.md says one of the purposes of the style is it "helps to prevent unfavorable fragmentation of tag use.".

**Comment by dieterdreist** [comment]
sent from a phone

> On 24. Sep 2018, at 21:00, SomeoneElseOSM <notifications@github.com> wrote:
> 
> A quick check of ones near me (UK) seems about 50/50 used "correctly" and misused. In many cases it's possible to tell based on the changeset comments (e.g. "cell phone tower" is likely wrong) or other tags ("operator=Arqiva" is likely correct).


I would also expect these to be mostly fixable by remote (for significant towers you will usually find a lot of material online, the shadow in aerial imagery can also be useful to confirm huge structures).

**Comment by kocio-pl** [comment]
Does anybody plan to do tagging corrections? I think this is preferred option and I would be happy with this too.

**Comment by kocio-pl** [comment]
BTW: another example of wildly misused tag is monument instead of memorials, it would be good to make some retagging action too:

https://www.openstreetmap.org/node/4861514021

![screenshot_2018-09-25 zestaw zmian 54003907 openstreetmap](https://user-images.githubusercontent.com/5439713/46026901-bff32d00-c0ec-11e8-8035-81199b0da07f.png)

**Comment by geozeisig** [comment]
There are indeed many wrongly tagged communications_tower. But you have to ask why? I found very old entries from a time when there was no wiki page. It may also be due to the editors who do not support it. In JOSM only tower is considered. Mast and communications_tower are missing. I once wrote a [ticket ](https://josm.openstreetmap.de/ticket/16121)but it was closed. Alternatively, you can use a preset [Communication Towers](https://josm.openstreetmap.de/wiki/Presets/Communication_Towers).
There is still a lot to do, if many help we will succeed.

**Comment by boothym** [comment]
@SomeoneElseOSM - had a look in your area and it seems that most have been added/changed recently, including this one (which has the operator tag) that should really be retagged as a 25m tower with tower:type=communication instead:

https://www.openstreetmap.org/node/3340470839/history
http://tx.mb21.co.uk/gallery/eastwood.php

I've found small mobile phone "masts" and towers, large lattice towers and very tall guyed masts tagged as communications_tower. But none of the ones I've seen in the UK look like the example in the wiki of the tall concrete tower with an observation deck, [of the style found in Berlin](https://en.wikipedia.org/wiki/Fernsehturm_Berlin).

Mobile phone "masts" are not big enough and a [351m guyed tubular mast](https://en.wikipedia.org/wiki/Belmont_transmitting_station) or a [219m lattice tower](https://en.wikipedia.org/wiki/Crystal_Palace_transmitting_station) are better tagged as a mast and tower - so there's not much left to tag as man_made=communications_tower!

@kocio-pl I'm going to post on the mailing list about the tagging. But for osm-carto, at the very least you must consider whether communications_tower should be rendered so prominently at z13, without at least checking for a height tag like you do for mast or tower.

My other request in the OP was to "render masts from z13, with similar height logic as towers" - should I create a new issue for that? Because it would be a shame if correctly tagged masts weren't rendered at z13/14, but towers are.

@geozeisig most of them are from Potlach2 where it is a preset, don't know when that was added though. Fortunately iD and JOSM don't have it as a preset as more people would no doubt be (mis)using it!

Also, the number of communication_towers is not increasing according to the history graph, which is good: http://taghistory.raifer.tech/ Hopefully we can get all parts of the puzzle - rendering, tagging, wiki, editors - sorted.

**Comment by kocio-pl** [comment]
If this will be the only outcome (so it's not effectively a meta-issue), I don't think we need another ticker, just the title change to make it clear and somebody to make the code. I think your proposition about height is sane, we just need to discuss details.

**Comment by boothym** [comment]
Ok, I've changed the title.

Currently man_made=tower + tower:type=communication is always rendered at z17,  and also at:
z15 = height>30
z14 = height>50
z13 = height>100

This should be copied for man_made=mast as that is currently rendered from z18, and at height>20, 40 and 80 for z17, 16 and 15.

For man_made=communications_tower I would suggest the same, although by definition there shouldn't be any tagged with height >100.

**Comment by boothym** [comment]
I could by just copying the tower code, but as I don't have a way to test the rendering I'd rather someone else did it.

**Comment by lakedistrictOSM** [comment]
> I doubt many (if any) of the ~240 examples in the UK are either.

@boothym I'd say that Radio City Tower in Liverpool fits the man_made=communications_tower definition, although currently it's just tagged as building=tower. The top of the tower houses the radio studios and broadcasting suites, with DAB transmission aerials on the very top. Originally it was opened as an observation tower, although radio is now the primary use. 

https://www.openstreetmap.org/way/204479301
https://en.wikipedia.org/wiki/Radio_City_Tower

**Comment by boothym** [comment]
@lakedistrictOSM thanks for that, I suppose the BT tower in Birmingham is another example. Looks similar to the TV tower in Berlin which seems to the basis for the man_made=communications_tower tag.

However as you mention a building tag, and looking at the [highest structures in Germany](https://en.wikipedia.org/wiki/List_of_tallest_structures_in_Germany) the top 6 have a building plus their man_made tag:

https://en.wikipedia.org/wiki/Fernsehturm_Berlin - communications_tower
https://en.wikipedia.org/wiki/Europaturm - tower
https://en.wikipedia.org/wiki/Fernmeldeturm_N%C3%BCrnberg - communications_tower
https://en.wikipedia.org/wiki/Olympiaturm - communications_tower
https://en.wikipedia.org/wiki/Telemax - tower
https://en.wikipedia.org/wiki/Heinrich_Hertz_Tower - communications_tower

So perhaps simply adding a building tag to man_made=tower + tower:type=communication + height would make the communications_tower tag redundant?

**Comment by SelfishSeahorse** [comment]
> So perhaps simply adding a building tag to man_made=tower + tower:type=communication + height would make the communications_tower tag redundant?

Towers aren't buildings because they aren't built for living, but for another purpose. In my opinion, adding a building tag to man_made=tower is mistagging for the renderer (just as adding a building tag to historic=ship or man_made=storage_tank).

**Comment by dieterdreist** [comment]
sent from a phone

> On 8. Oct 2018, at 19:21, SelfishSeahorse <notifications@github.com> wrote:
> 
> Towers aren't buildings because they aren't built for living, but for another purpose


 towers are typically a good fit for the building tag as well. There is no requirement for „building“ to be built for living.

**Comment by HolgerJeromin** [comment]
> Towers aren't buildings because they aren't built for living, but for another purpose. 

With this definition you could delete million garages, huts, sheds, greenhouses, industrial and office buildings

**Comment by SelfishSeahorse** [comment]
>
> With this definition you could delete million garages, huts, sheds,
> greenhouses, industrial and office buildings
>
You are right, my definition doesn't make sense. I rather meant staying or
being accessible than dwelling (and being closed). After rethinking, i
agree that towers that are accessible can be called buildings -- but for
example not lattice towers.

**Comment by jeisenbe** [comment]
I can do test renderings for the masts, if we can decide on the right levels. 

I think it might make sense for masts to continue to render 1 zoom level later than towers, because they are less visually prominent.

Man_made chimney also renders about 1 zoom level later than towers, and never sooner than z16

How about for masts:
zoom 14 for height >100
zoom 15 for height >50
zoom 16 for height >30

Should we also render man_made chimney at z15 for height >100, perhaps?

**Comment by jeisenbe** [comment]
@kocio-pl - I just read through the discussions about rendering towers, #3158 and #2671, but I didn't see a clear discussion of the initial zoom levels and heights for towers vs masts vs chimneys. Perhaps I missed it?

Is there a reason that towers are rendered as early as z13 but masts only at z15? Can we have them all render at z14 as the earliest, or should towers still render at z13?

I would also consider #1017 rendering wind turbines based on height
And rendering monuments and obelisks earlier based in height. 

I've already made the code, should I post some test renderings?

**Comment by kocio-pl** [comment]
Most probably I focused on towers and did not test masts and chimneys, I just found sane defaults for some testing places, so they don't dominate the area. Both are less solid and more popular than towers, so I made them less prominent.

If you have something more detailed, you can post it of course. I was thinking about showing some huge monuments earlier, so I'm happy to hear that.

**Comment by jeisenbe** [comment]
Ok, great!
Since we are no longer rendering building outlines on z13, I will also test
removing the tower rendering and communications_tower from z13 to be
consistent.

**Comment by jeisenbe** [comment]
I'd like to start rending masts, towers, communication_tower and radio telescopes from z14 at >100m, z15 at >50 meters. Examples:

Honolulu, Hawaii z13 before
![honolulu-z13-with-towers](https://user-images.githubusercontent.com/42757252/48390753-e7f32a00-e746-11e8-9333-24585f5088da.png)
Honolulu z13 after
![honolulu-z13-no-towers](https://user-images.githubusercontent.com/42757252/48390793-107b2400-e747-11e8-84fb-0750684b7b70.png)
Honolulu z14 (same before and after)
![honolulu-towers-z14](https://user-images.githubusercontent.com/42757252/48390950-b2027580-e747-11e8-90e2-5717d7e6c013.png)

Zwedru, Liberia
z13 Before
![zwedru-z13-tower](https://user-images.githubusercontent.com/42757252/48390836-3a344b00-e747-11e8-8407-9b156aa3dfd1.png)
z13 After
![zwedru-z13-no-towers](https://user-images.githubusercontent.com/42757252/48390829-30aae300-e747-11e8-8170-6d0c09910d06.png)
z14 (same)
![dover-towers-z14](https://user-images.githubusercontent.com/42757252/48390857-50daa200-e747-11e8-92d2-451c4b93b6f4.png)

Dover, England
z13 Before
![dover-z13-towers-before](https://user-images.githubusercontent.com/42757252/48390841-3ef8ff00-e747-11e8-9fd6-481e14f60b6e.png)
z13 After
![dover-z13-after](https://user-images.githubusercontent.com/42757252/48390849-47e9d080-e747-11e8-8e70-b945877df0ba.png)
z14 (same)
![dover-towers-z14](https://user-images.githubusercontent.com/42757252/48390872-60f28180-e747-11e8-9a4a-cc8d183c9264.png)
 
Southwest of Dover
z14 Before (200m mast not rendered)
![sw-dover-mast-before-z14](https://user-images.githubusercontent.com/42757252/48390877-66e86280-e747-11e8-9ef7-4b2ebf03fa3a.png)
After
![sw-dover-mast-z14-after](https://user-images.githubusercontent.com/42757252/48390957-b9298380-e747-11e8-9861-913f3da708a2.png)

Washington DC
z13 Before
![washington-z13-before](https://user-images.githubusercontent.com/42757252/48395170-b768bb80-e759-11e8-974e-2e27c9fe6590.png)
After
![washington-z13-after-no-towers](https://user-images.githubusercontent.com/42757252/48395168-b6378e80-e759-11e8-8456-f3fdae8031f8.png)

**Comment by jeisenbe** [comment]
These things are already rendered based on height. I am simply adjusting
the rules to be more consistent.

However, I do think it would make sense to render tall monuments and
obelisks earlier, again to be consistent with the rules for towers and
masts.

We render large areas earlier, based on waypixels (height x width). Tall
objects are visible over a large area due to their height, so it makes
sense to render them earlier as well, but not too early.

I believe z14 is reasonable for a 120m tower or crane; that’s 400 feet or
about 40 floors for an office building, so these things are all
“skyscraper” height.

But there are 6 meter and 12 meter cranes and cell phone masts, and these
should not be rendered sooner than z17

**Comment by Adamant36** [comment]
I agree that area and height should be rendered for thing that are mapped as large ways. A wider area thing is obviously different then a less wider one and should rendered at different zoom levels. Id also agree with about uber tall towers versus smaller cell towers. Except cell towers are tagged as such and their rendering could level just be based on that. Not on the fact that they are a part of the higher category of "towers" and happen to have a height tag. Height is to arbitrary in those situations, they all look like dots on a satellite map anyway, and know one would understand the rendering inconsistency because its not stated anywhere. If anything, they might consider it a bug. Plus, as I said before, is someone just suppose to zoom around wildly until they find the correct zoom level for the tower they want to add to see if its there or not?

What about things like multi story buildings? Should they be rendered at different zoom levels because they have different stories? or should we render stairs differently based on how many individual stairs there are? I don't why see there should be an exception here. Unless it has an actual benefit to mappers. What actual real world benefit does it provide? We have been trying to clean up zoom levels. Not make them more cluttered or complicated. Just saying it should be done in this case because its done in others isn't a good reason.

**Comment by jeisenbe** [comment]
Does anyone have comments on the test renderings above? https://github.com/gravitystorm/openstreetmap-carto/issues/3414#issuecomment-438154173

I believe it would work to have z14 as the initial zoom level for the tallest towers and masts. I would also adjust radio telescopes to render no sooner than z14, and add sooner rendering for tall monuments and obelisks. 

Is >100m at z14 the best option?
Another option would be to use the current values for masts, but add one level; 
So >160m at z14,
>80m at z15
>40m at z16
This would ensure that only skyscraper-height objects are rendered at z14.

Another consideration is that z14 is where power line towers are first rendered, though with a very small square symbol. At z15 power=tower have a slightly larger square icon, though still much smaller than the pictographs used for masts, monuments etc.

**Comment by jeisenbe** [comment]
Michael, have you seen PR #3536 ?

I’ve shown rendering examples of the planned changes and given an
explanation for them.

Please comment there, if you have a chance to review the changes. Link:

https://github.com/gravitystorm/openstreetmap-carto/pull/3536

**Comment by Adamant36** [comment]
@boothym, my point was that five different zoom levels for rendering a single object based an obscure variable like height of the object isn't the most intuitive thing for most people or something they would probably even consider when look at the map to see if something is there or not. For instance, most people don't know or care that their local cell tower is 80ft and not 79 feet. 

If they were looking for the objects on the map, they might zoom into z15, see a tower there, wrongly assume all towers are rendered at that zoom level, then think a tower doesn't exist somewhere else because its displayed at z16 instead. Since again, height is a useless distinction to most people, for most people. Unless your talking about the difference between the Eiffel Tower and a local cell tower, but that's more about its cultural significance then how tall it is. But by doing it this way your essentially put all towers, even meaningless ones on the same importance level as the Eiffel Tower, which they aren't,  simply because the they are the same height. 

Maybe it would be different if there was only like two height variables. 5 is out of the range of usefulness or meaning though. Especially considering there's map legend to explain it and the person would have to inspect every object to know that's the variable being used, because again its just not intuitive. 

Yes there's lots of other things people need to zoom in to see, but what aboutisms don't really work good in a case like this where your talking about hundreds of different objects with different properties and rendering priorities. Cool freeways are rendered at a different zoom level then residential roads, but they are different objects and serve different purposes on the road way. freeways aren't rendered 5 different ways based on their road width though (which I think is a bad idea). All of them are rendered the same irrespective of how wide they are. So its not even comparable. If they where then it might be.

**Comment by Adamant36** [comment]
As an alternative you could render them based on tower:type and leave it at that. That would be way less arbitrary, would incur-age adding the tag, and would not render insignificant ones at the same level as significant ones. The vast majority are communication towers, or other similar tower types, where height doesn't even matter. Only a small minority are like the Eiffel Tower. So I don't know why height even needs to inter into the equation. Again, its a completely irrelevant variable.
