### ISSUE TITLE
Render capacity of amenity=bicycle_rental and amenity=bicycle_parking nodes

### ISSUE THREAD

**Issue by tpikonen** [gravitystorm/openstreetmap-carto#3428]
It would be nice to see the capacity tag of bike sharing stations and bicycle parking places rendered as text.

The capacity text should probably only be visible at at z>=18, so there will be enough free space around the node (bicycle_parking is only rendered at z=18 and above).

I will try to submit a PR with this change when I have time, but if someone beats me to it, I won't mind.

**Comment by kocio-pl** [comment]
I would rather not render anything other than names/refs on general style.

**Comment by boothym** [comment]
Perhaps we could copy OpenCycleMap, which shows the capacity number only when it's >=20. https://www.opencyclemap.org/docs/ (and a bigger icon)

Or if you don't want to show the capacity at all, how about rendering bicycle parking at z17 (same as bicycle rental) when it has a capacity >=20?

**Comment by kocio-pl** [comment]
I try to focus on some other non-obvious things, so it's hard for me to imagine all the aspects here. What do other people think about it?

**Comment by Adamant36** [comment]
It would be cool if there was a specific zoom level dedicated to other information for things besides name that can't be shown in an icon. Like restaurant style, materiel, capacity, elevation, etc. I forget which zoom level it was now, but one of them is almost exactly like the next zoom down and would probably work for it. I don't how it work for things that are only rendered below that zoom level, but whatever. 

Outside of that, if an exception is made for bike parking capacity by itself, then it might open the doors to people wanting a bunch of other similar tags being rendered later on, which has the potential to add a massive amount of clutter if not done right. So, if it is rendered, it should be a part of wider design goal and not done individually. That's not to say id be against it. Id just like to see that kind of information rendered on its own zoom level, as a standard or something though. Maybe by tag type. Instead of making an exception for one tag or subset.

**Comment by kocio-pl** [comment]
I think that it makes more sense to use the car parking approach: if they are big enough, they should be tagged as an area and then we could show the symbol earlier.

**Comment by Tomasz-W** [comment]
I'm cycling a lot (1000-1500 kilometers/ year) and I find this information useless. I don't care what is the capacity of the parking, because it could be very big but fully loaded. Maybe in veeery late future there will be possibility of live-rendering for free stands on certain parking by the moment, that would be useful and great. In current situation I find it more as map cluttering.

**Comment by tpikonen** [comment]
I made a PR which renders the capacity as a superscript to the *parking and bicycle_rental markers, resembling an exponential.

Undoubtedly this increases 'clutter', but at z>=18 I don't think this is that much of a problem. As for the benefit of this change, the larger the size of the parking place, the bigger the chance of finding a free parking place soon.

**Comment by Adamant36** [comment]
Z18 was the zoom level I was thinking of. I think its currently under utilized as its own zoom level. Maybe it could be the "extra information" zoom level or something.

**Comment by kocio-pl** [comment]
> I've never seen it displayed on any OSM based map, including the cycling map on the main site. 

https://www.openstreetmap.org/way/352186626#map=19/52.25611/20.98316&layers=C

However the same place on OSM Carto shows the space it in a visual way:

https://www.openstreetmap.org/way/352186626#map=19/52.25620/20.98316

**Comment by matthijsmelissen** [comment]
I agree with the comments above. As there seems to be no support for the proposal, I'm going to close this issue. Thanks for the idea though!

**Comment by polarbearing** [comment]
Just to agree with the issue being closed, the capacity tag is used on many objects, from parking spaces over hotel beds to size of schools. Thus it is useful for evaluating a particular POI as in the database, but not useful for rendering on the general map.
