### ISSUE TITLE
Scrub overlaps danger area

### ISSUE THREAD

**Issue by momu** [gravitystorm/openstreetmap-carto#3454]
### Expected behavior

The danger area[1] should be above the beach and scrub[2].

### Actual behavior

Scrub and beach are above the danger area.

### Links and screenshots illustrating the problem

![map](https://user-images.githubusercontent.com/1451642/47044905-b744c280-d191-11e8-81ca-8b227a710853.png)
[0]: https://www.openstreetmap.org/#map=18/54.15019/13.82067
[1]: https://www.openstreetmap.org/way/307904554/
[2]: https://www.openstreetmap.org/way/578224669

**Comment by matthijsmelissen** [comment]
Strange indeed.

This forest also gets rendered incorrectly: https://www.openstreetmap.org/way/134745853

Example of scrub/military rendered correctly: https://www.openstreetmap.org/#map=17/52.11047/4.31424

**Comment by uswoods** [comment]
@kocio-pl @matthijsmelissen You have taken over this style – and then you don't know any reason for such behaviour? Are you maybe a little bit overchallenged by your work?

**Comment by sommerluk** [comment]
@uswoods This is a volunteer’s project. The contributors sacrifice part of their spare free time to improve this rendering style. Please be more polite.

**Comment by jragusa** [comment]
I suppose that order in queries is important in `project.mml` so we probably need to move military_ query (l.132) after natural_ and wetland_ (l.133 & 134).

**Comment by HolgerJeromin** [comment]
Text from jragusa as a permalink:
https://github.com/gravitystorm/openstreetmap-carto/blob/6d259cadf12c6218046e73164a1e2812f056c160/project.mml#L132-L134

**Comment by Adamant36** [comment]
It seems fine on wetland though. So if order was the issue, you would think it wouldn't be. 
https://www.openstreetmap.org/#map=16/39.1482/-121.3907
![wetland](https://user-images.githubusercontent.com/30259065/47147193-8e502a80-d282-11e8-8b8e-7b5edd0232ac.png)

**Comment by Adamant36** [comment]
Here's a place with scrub that's fine also. I think it might have something to do with how it overlays outside of the military area or maybe that its a relation. Although the sand doesn't seem to be. Maybe something mapped under them that's screwing the order up?
![scrub](https://user-images.githubusercontent.com/30259065/47147423-0c143600-d283-11e8-8d9c-bd2dfe67ff7a.png)

**Comment by matthijsmelissen** [comment]
I see the cause of this issue now. My example was a landuse=military while this is a military=danger_area.

The tag military=danger_area should be rendered from landuse-overlay (just like landuse=military already is), rather than from the landcover layer. Good catch, @momu.

This requires changes to project.mml and landcover.mss. Following the example of landuse=military for military=danger_area should work. Is anybody willing to try?

**Comment by jragusa** [comment]
![danger_area](https://user-images.githubusercontent.com/9897203/47268072-685dab00-d54c-11e8-8419-9c87eb90011c.png)

**Comment by matkoniecz** [comment]
@uswoods 

> @kocio-pl @matthijsmelissen You have taken over this style – and then you don't know any reason for such behaviour? Are you maybe a little bit overchallenged by your work?

It is preferable to not comment at all rather than leave hostile comments. See https://github.com/gravitystorm/openstreetmap-carto/blob/master/CODE_OF_CONDUCT.md for details.

In addition:

"weird, I have no idea why it is happening" is something completely normal during developing or maintaining software and it is reaction that typical programmer encounters frequently

Nobody is obligated to spend any time maintaining this project.

One of main reason for stopping contributing to projects like this is repeated negative feedback and lack of positive (basically, where everything goes OK noone comments, where anything goes poor in any way someone will complain). Adding hostility to that is not helpful.

**Comment by kocio-pl** [comment]
I suspect this issue might have the same problem: #1285.
