### ISSUE TITLE
Add rendering for man_made=crane

### ISSUE THREAD

**Issue by Ti4goc** [gravitystorm/openstreetmap-carto#3478]
Why cranes do not appear rendered in OSM?

Wiki: https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcrane

Examples: https://www.openstreetmap.org/node/6000837250

**Comment by kocio-pl** [comment]
We need an icon for that, but the usage is OK:

![taghistory 18](https://user-images.githubusercontent.com/5439713/47465065-97de1300-d7eb-11e8-83a4-f27ac9248bf1.png)

**Comment by Tomasz-W** [comment]
`man_made=crane` icon proposal:

![man_made crane](https://user-images.githubusercontent.com/25656654/47564772-69b11e00-d926-11e8-93f2-274fe83f8ffc.png)

**Comment by kocio-pl** [comment]
It's OK for me.

**Comment by Tomasz-W** [comment]
Notice also that this icon should match very different types of cranes, e.g. [portal crane](https://www.google.pl/search?q=portal+crane&client=opera&hs=xiq&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjSqYGD9aTeAhXFZ1AKHZbbDhYQ_AUIDigB&biw=1920&bih=977) or [gantry crane](https://www.google.pl/search?q=gantry+crane&client=opera&hs=s3V&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj1ptOJ9aTeAhWPHsAKHW26DrwQ_AUIDigB&biw=1920&bih=977).

**Comment by jeisenbe** [comment]
Is there a link to the svg?

**Comment by jeisenbe** [comment]
crane:type=portal_crane 900
crane:type=Container_crane 474
crane:type=Gantry_crane 282
crane:type=Travellift=231

Vs 6000 cranes globally, so probably one icon is best for now.

**Comment by jeisenbe** [comment]
I believe cranes can render based on height, as with as towers. The "height" tag is not as common with cranes as with towers, but it can range from as little as 6 meters (2 storeys) to over 120 meters. About 170 are tagged with height so far.  

The smaller cranes may be at industrial buildings or rail yards in cities, where it would not be appropriate to display them at z15, but a 120 meter tall crate at a seaport can be shown as early as z14 with no problems. Name labels and cranes without height tagged would display at z17.

```
    [zoom >= 13][height >= 100],
    [zoom >= 14][height >= 50],
    [zoom >= 15][height >= 30],
    [zoom >= 16][height >= 15],
    [zoom >= 17] {
```

Most cranes are in big rail yards or ports, like the **port in Singapore:** https://www.openstreetmap.org/#map=17/1.2655/103.7928
z16 no cranes visible (no heights tagged); but they would be lining the waterfront. I hope mappers will add height tags later so that they will render earlier. 
![singapore-z16](https://user-images.githubusercontent.com/42757252/47600114-34283580-d9f7-11e8-8711-75cfe3cbf1a2.png)

z17 cranes visible
![singapore-z17](https://user-images.githubusercontent.com/42757252/47600116-35596280-d9f7-11e8-9d8a-a152236d00c7.png)


Rail yards provide the possibility for cranes to be in the center of an urban area, such as this 128 meter tall crane in right next to the **Porta Garibaldi train station in Milan, Italy.** This is probably the most extreme example in the database: https://www.openstreetmap.org/#map=15/45.4851594/9.1832991
z14
![milano-z14](https://user-images.githubusercontent.com/42757252/47600119-39858000-d9f7-11e8-8a18-2c8049b19596.png)

z15
![milano-z15](https://user-images.githubusercontent.com/42757252/47600120-3c807080-d9f7-11e8-91c5-4469f1df502f.png)

z16
![milano-z16](https://user-images.githubusercontent.com/42757252/47600121-40ac8e00-d9f7-11e8-96d9-3f43c919cf77.png)


But most cranes are going to be on the edge of urban areas in industrial lands or along rivers and coasts:
**Port of Venice, Italy:**  https://www.openstreetmap.org/#map=15/45.4729014/12.2435279
z14 largest >100m cranes visible
![venice-z14small](https://user-images.githubusercontent.com/42757252/47600128-5b7f0280-d9f7-11e8-939a-708ce630e17d.png)

z15 
![venice-z15](https://user-images.githubusercontent.com/42757252/47600131-5fab2000-d9f7-11e8-917b-6dded012c7c2.png)

z16
![venice-z16](https://user-images.githubusercontent.com/42757252/47600132-62a61080-d9f7-11e8-8048-7668329e6134.png)

z17 other (no height tagged) cranes visible
![venice-z17](https://user-images.githubusercontent.com/42757252/47600134-646fd400-d9f7-11e8-88cb-b95d4c4284ca.png)


**Port of Santiago, Cuba:** https://www.openstreetmap.org/#map=15/20.0252605/75.8440889
z15 largest 60m crane visible (there are two but one is blocked by the other)
![cuba-z15](https://user-images.githubusercontent.com/42757252/47600136-73568680-d9f7-11e8-88bd-7e56c22410dd.png)

z17 other cranes visible
![cuba-z17](https://user-images.githubusercontent.com/42757252/47600148-941edc00-d9f7-11e8-923f-b0e7fca67959.png)


**River port crane with name, Blauer Kran, height 24m:**
https://www.openstreetmap.org/#map=16/50.1129065/8.7519599

z15 icon
![blauerkran26m-z15](https://user-images.githubusercontent.com/42757252/47600151-a26cf800-d9f7-11e8-8959-0834b1cac404.png)

z16 
![blauerkran26m-z16](https://user-images.githubusercontent.com/42757252/47600154-a6991580-d9f7-11e8-8f0a-0d65ff4daa55.png)

z17 icon and name label
![blauerkran26m-z17](https://user-images.githubusercontent.com/42757252/47600156-a8fb6f80-d9f7-11e8-9361-958403b51450.png)


**Small river crane with name, height 12m:**
https://www.openstreetmap.org/#map=17/51.2551612/6.741607
z16 not visible
![bigwilli-z16](https://user-images.githubusercontent.com/42757252/47600162-b7498b80-d9f7-11e8-87c0-b0e194a79875.png)

z17 icon and name label
![bigwilli12m-z17](https://user-images.githubusercontent.com/42757252/47600164-ba447c00-d9f7-11e8-8343-222941cd8cb8.png)


**Crane on a closed way with name label at z17:**
https://www.openstreetmap.org/#map=17/50.1131957/8.7441295
http://openstreetmap.org/way/282295510
z17
![evo-z17](https://user-images.githubusercontent.com/42757252/47600165-c29cb700-d9f7-11e8-919c-1ec8054ae463.png)

I just need an .svg version of the icon to finish the code, if others believe this is ready for a PR

**Comment by kocio-pl** [comment]
Great piece of research, nice to see such evidence based design! I think this is ready for PR as soon as vector icon is available.

**Comment by polarbearing** [comment]
Lovely :-)

**Comment by Tomasz-W** [comment]
After wider research I decided to design dedicated icons for each crane type:

* generic `man_made=crane`:
![man_made crane](https://user-images.githubusercontent.com/25656654/47601358-c7e60b80-d9cf-11e8-972e-8cdcc138d681.png)
* `man_made=crane` + `crane:type=portal_crane`:
![man_made crane portal](https://user-images.githubusercontent.com/25656654/47601256-31651a80-d9ce-11e8-8050-c997a67dd9ca.png)
* `man_made=crane` + `crane:type=floor-mounted_crane`:
![man_made crane floor](https://user-images.githubusercontent.com/25656654/47602005-9d4c8080-d9d8-11e8-8bd1-bedc3bea63f5.png)
* `man_made=crane` + `crane:type=travel_lift`:
![man_made crane travel](https://user-images.githubusercontent.com/25656654/47601758-88222280-d9d5-11e8-9c98-c231d61e2a16.png)

Gist link: https://gist.github.com/Tomasz-W/ed6c01e147616e786faff2690fcce686

**Comment by jeisenbe** [comment]
For gantry crane can we use the same icon as portal crane? It seems like
they are the same on the wiki page, and the icon looks like a gantry crane,
I think? Wikipedia says gantry and portal are used interchangeably

**Comment by Tomasz-W** [comment]
@jeisenbe As `gantry_crane` is quite popular type, but it's not added to Wiki list, I'll add it. Anyway, for gantry cranes I would use a `travel_lift` icon (it's a kind of gantry crane with a wheels under it). I'll also do a clean up of some tagging mistakes, because on TagInfo I can see some tags duplicated.

**Comment by jeisenbe** [comment]
What is the distinction between a gantry_crane, a portal_crane, and a travel_lift? I couldn't find a good definition.

**Comment by Tomasz-W** [comment]
@jeisenbe I've recently updated Wiki page to make things more clear, see:

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcrane

**Comment by lakedistrictOSM** [comment]
For now, I'd just use one icon for all crane types. The generic crane icon is the best one.

Although cranes are very tall, they tend to have small footprints so I'd skip rendering at z14.

**Comment by jeisenbe** [comment]
The tall ones are also quite long, especially those at sea ports. The huge
post-Panamax cranes have to be big enough to cover an 18-container wide
ship over the water. I believe a 100m tall crane will usually be about 100m
long.

We currently render 100 meter man_made=tower at z14, and these usually have
smaller footprints than cranes.

**Comment by jragusa** [comment]
same question: why not using the `@man-made-icon` color instead of black ?

**Comment by jeisenbe** [comment]
It was black because I was testing with a png instead of an svg. With the
svg it should render properly. I’d show some examples, but both of my
laptops are refusing to start up.
