### ISSUE TITLE
forest track hidden under a boundary

### ISSUE THREAD

**Issue by PontiacCZ** [gravitystorm/openstreetmap-carto#3490]
### Expected behavior
Boundary=administrative with admin_level>=7 should be rendered more transparent so it does not obstruct forest tracks in zoom 15 and closer (see the link).

### Actual behavior
Administrative boundaries are easily mistaken with tracks. Tracks are covered by boundaries.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/370418393#map=15/49.3462/17.7475

![obrazek](https://user-images.githubusercontent.com/9153595/47902577-9a430b80-de82-11e8-854a-cf7c43d39a93.png)

**Comment by Tomasz-W** [comment]
I see it as a collision of 2 things:
* mapping admin boundaries as relations including `highway=*` ways (which I consider as very reasonable and "keeping map clean-like" behaviour)
* boundaries colour (see https://github.com/gravitystorm/openstreetmap-carto/issues/3489), where I'm worried that every choosen colour would be coliding at the same level

I think that the best solution would be to render highways and admin borders side by side, but I'm not sure is it technically possible. @kocio-pl ? I believe it is, as it's possible to render cycle routes (also relations) side by side to highways, like in this map (dotted ways): http://mapaszlakow.eu/#16/52.3988/16.9445

**Comment by dieterdreist** [comment]
Am Fr., 2. Nov. 2018 um 11:45 Uhr schrieb Tomasz Wójcik <
notifications@github.com>:

> I see it as a collision of 2 things:
>
>    - mapping admin boundaries as relations including highway=* ways
>    (which I consider as very reasonable and "keeping map clean-like" behaviour)
>
>
+1

I think that the best solution would be to render highways and admin
> borders side by side, but I'm not sure is it technically possible.
> @kocio-pl <https://github.com/kocio-pl> ? I believe it is, as it's
> possible to render cycle routes (also relations) side by side to highways,
> like in this map (dotted ways): http://mapaszlakow.eu/#16/52.3988/16.9445




regardless of technical feasability, I believe it would be wrong to render
both side by side, because if the situation is that the highway is defining
the boundary, it would (visually) remove it from one of the admin entities
and put it completely into the other, while the actual situation would be
it is a border for both neighbouring admin entities.

Another solution could be to use a different style for the boundary:
thicker and below the track, so that both are rendered and visible. For
highways with broader rendering (most highways), the desired behaviour
would be the opposite: render it not too thick and above the highway. ;-)

**Comment by pnorman** [comment]
> I think that the best solution would be to render highways and admin borders side by side, but I'm not sure is it technically possible

Not really, and we want to stay away from modifying geometries.

> Another solution could be to use a different style for the boundary:
> thicker and below the track, so that both are rendered and visible. For
> highways with broader rendering (most highways), the desired behaviour
> would be the opposite: render it not too thick and above the highway. ;-)

Sadly, we can't have boundaries both below and above highways.

Given our constraints and lack of alternative ideas, I think the current rendering is okay.

**Comment by jeisenbe** [comment]
We could improve this at high zoom levels by changing the track rendering to be a double line at z18 and z19, where most tracks are physically wider than the rendered line. 

I'm also working on the borders. It's possible to improve this a little for some admin boundary levels, but due to the constraints of using `comp-op darken` and standard-pixel size rendering, we don't have too many options, so I won't claim that the new borders will resolve this problem.
