### ISSUE TITLE
Contributing workflow with git and GitHub

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3503]
As a new contributor without prior experience with git and GitHub, it's been difficult to figure out the preferred workflow for PRs. I've also had a problem with prior commits showing up on new branches when I make a PR. I've been reading the Pro Git eBook, but it appears that different development teams use very different workflows.

When is it appropriate to rebase a branch versus merging?
When should a commit be amended?
How many separate commits should be added for a PR?

If there is an agreed-upon workflow, perhaps we can update contributing.md with more detailed instructions

**Comment by matthijsmelissen** [comment]
My opinions:

> When is it appropriate to rebase a branch versus merging?

It is helpful to the maintainers if contributors rebase their pull requests themselves whenever conflicts arise. The maintainers might rebase as well before merging.

> When should a commit be amended?

Please avoid amending commits after they have been pushed, it makes it harder to review changes. 

> How many separate commits should be added for a PR?

Please add at least one new commit every time changes are pushed. The maintainers will decide if it's better to squash the commits into one commit, or merge each individual commit.

**Comment by kocio-pl** [comment]
Does this comment answer your questions? If you need some more informations, please ssk here, otherwise I think it should be closed.

**Comment by jeisenbe** [comment]
Yes, thank you @matthijsmelissen and @kocio-pl 

I found that using `$ git rebase -i upstream/master` before pushing a new topic branch was very helpful. It showed that I had a number of old commits from a prior branch that could be deleted, because they had already been squashed and merged.

I would also recommend that new contributors take care when they create a new topic branch. Make sure it is based off of the most recent master branch. Use `$ git checkout -b FeatureBranchName origin/master` to make a new branch called FeatureBranchName based on  the Master branch at gravitystorm/openstreetmap-carto, assuming that you have set gravitystorm/openstreetmap-carto as "origin". (It might also be named "upstream", depending if you cloned your fork or the main repository)

Then, make sure to check `git diff` before you add each file or `git diff` after each commit, to catch any whitespace errors or mistakes in adding the changes to the wrong branch, for example. 

Before you use `git push` to send the new branch to GitHub, make sure to do another test rendering, and reload the page in your browser.

Then, after you make a pull request, don't use `git rebase` or `git commit --amend` if you have to make any changes. Use `git diff` before you add any changed files, and `git show` after you commit the changes, and test the rendering again, before you push the new commit to GitHub. Hopefully this will avoid the need to send multiple commits due to small mistakes (i.e. "Do as I say, Not as I do" 😄 ) 

Does that sound right?

Recommended reading  “Pro Git” by Scott Chacon, free online ebook
https://git-scm.com/book

**Comment by Adamant36** [comment]
What I do is just have a master branch that I never code off and only use to create branches from. Then I update up it by doing a rebase before a create a new working branch every time. Its worked good so. Except there has been some commit bleed over between branches even after they were commited and were supposedly clean. I just now figured how to rebase a branch. 

As far as amending commits go, I usually do an amend when the change isn't that drastic. If I am adding something completely new to the PR I will create a new commit. Although, most of the time new commits are only due to minor adjustments or small screw ups on my part. So, more often then not I just amend them. Since the change usually still upholds the intent of the original PR and commit message. That's just how I do things though. It seems like there's usually twenty different ways for github to do the essentially the same thing. I don't think any one way is necessarily the "correct" way. It would help a lot to have more information on this stuff in the how to contribute file though.

**Comment by kocio-pl** [comment]
The question is answered, so I'm closing this ticket.
