### ISSUE TITLE
Add rendering for aboriginal areas

### ISSUE THREAD

**Issue by almccon** [gravitystorm/openstreetmap-carto#3520]
Aboriginal areas (also called [Indigenous Protected Areas](https://en.wikipedia.org/wiki/Indigenous_Protected_Area), Native Reserves, First Nation Reserves, [Indian Reserves](https://en.wikipedia.org/wiki/Indian_reserve), [Indian Reservations](https://en.wikipedia.org/wiki/Indian_reservation), etc., depending on the country) are important features that belong on the map.

There had been some discussion in #603  about protected areas in general, but that discussion seems to have narrowed to discuss only natural protected areas, not cultural ones. So if #3509 proposes closing #603, we need to have a new issue to discuss aboriginal protected areas.

Setting aside the debate about whether administrative boundaries belong in OSM at all (the ship has sailed on that one), it seems obvious to me that aboriginal areas are at least as important as many other boundaries we currently show, such as municipal boundaries, or even state/province boundaries. However, I also agree that they should not be overly prominent either (some have proposed that they be mapped as `admin_level=2` which seems extreme). In many cases, you can cross in or out of an aboriginal area without knowing it or seeing other evidence on the ground. But in other cases, the boundaries are clearly marked on the ground, and sometimes even travel permits are required to enter these areas. Often there are different laws in effect within aboriginal areas, which seems like an important thing for a map user to know about.

Within OSM there does not appear to be a consensus about whether the tagging should be [`boundary=aboriginal_lands`](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Daboriginal_lands) or whether we should use [`boundary=protected_area`](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area) along with `protect_class=24`. Both are in relatively wide use, and I propose rendering both options until a tagging consensus has emerged. `boundary=aboriginal_lands` is quite popular in Canada and parts of the US, while `boundary=protected_area` + `protect_class=24` is popular in South America and Australia. It's also worth noting that mappers have been doing a lot of tagging for the renderer, for example using `leisure=nature_reserve` incorrectly to get these indigenous areas to show up on the map, especially in Brazil.

Overpass query for `boundary=aboriginal_lands`: http://overpass-turbo.eu/s/DV4
![screen shot 2018-11-22 at 22 nov 11 18 51](https://user-images.githubusercontent.com/1212178/48921447-b9670480-ee54-11e8-92de-bfe1b87b7061.png)

Overpass query for `protect_class=24`: http://overpass-turbo.eu/s/DV5
![screen shot 2018-11-22 at 22 nov 11 14 31](https://user-images.githubusercontent.com/1212178/48921452-bec44f00-ee54-11e8-89fe-f4879d56f2ca.png)

![taghistory](https://user-images.githubusercontent.com/1212178/48921473-e0253b00-ee54-11e8-901c-6dbe732fc04f.png)

These areas vary widely in size: some Indian Reservations in the United States are larger in area than many European countries, but in other cases, such as the [Nooksack Reservation](https://en.wikipedia.org/wiki/Nooksack_people) near where I live, they can be as small as one acre (0.4 hectares). For this reason, we need a cartographic style that varies appropriately according to zoom level, and filters out smaller reservations at low zoom levels.

I propose adapting the current `leisure=nature_reserve` styling, but using a brown color instead of green. Nature reserves have a nice subtle fill color at low zoom levels, but when you zoom in, the fill goes away and they only show a light outline. This level of detail seems appropriate for aboriginal areas as well. The aboriginal areas start showing up at z8, which is the same time we first see national parks and military areas. As with those other features, the aboriginal areas are filtered by area, so only large ones show up. At z10, there is no more polygon fill, just an outline.

Here's southern Arizona at z8, before the change. Note the large empty spaces, some of which are actually occupied by large native reservations.
<img width="1098" alt="screen shot 2018-11-22 at 22 nov 9 16 32" src="https://user-images.githubusercontent.com/1212178/48921489-f9c68280-ee54-11e8-9257-8e3a4b566ea7.png">

Here's the same view, with the change applied.
<img width="1115" alt="screen shot 2018-11-22 at 22 nov 10 20 28" src="https://user-images.githubusercontent.com/1212178/48921517-0fd44300-ee55-11e8-9462-470537eeb38e.png">

Here it is with a different brown:
<img width="1134" alt="screen shot 2018-11-22 at 22 nov 10 25 33" src="https://user-images.githubusercontent.com/1212178/48921519-14006080-ee55-11e8-9673-07762073187a.png">

In the first screenshot I started with the html "brown" color #835c3b (hsl(28, 38%, 37%)), but then in the second screenshot I adjusted the hue more in the direction of yellow away from red, to avoid too much similarity with the existing red military areas. Currently I'm using #82643a (hsl(35, 38%, 37%))

A few more samples:

With #835c3b (reddish brown):
![screen shot 2018-10-11 at 11 oct 5 17 22](https://user-images.githubusercontent.com/1212178/48921611-ba4c6600-ee55-11e8-914c-60e0926281f2.png)

With #82643a (orangey brown):
![screen shot 2018-11-22 at 22 nov 11 04 23](https://user-images.githubusercontent.com/1212178/48921539-2da1a800-ee55-11e8-8d50-94cf89b51ca2.png)

![screen shot 2018-11-22 at 22 nov 11 08 00](https://user-images.githubusercontent.com/1212178/48921540-30040200-ee55-11e8-89ce-e867b44c627c.png)
![screen shot 2018-11-22 at 22 nov 11 09 40](https://user-images.githubusercontent.com/1212178/48921544-32665c00-ee55-11e8-99ce-285c6d54883a.png)
<img width="646" alt="screen shot 2018-11-22 at 22 nov 10 35 28" src="https://user-images.githubusercontent.com/1212178/48921545-35f9e300-ee55-11e8-8232-5141d7ab621a.png">

Here are some cases in Canada where aboriginal areas were also tagged with a `type=boundary` relation (perhaps tagging for the renderer): https://www.openstreetmap.org/relation/2227709 and https://www.openstreetmap.org/relation/2092741. The interaction of the dashed purple boundary line with the solid brown aboriginal_area line is a bit weird, but not terrible IMO. Once we have correct aboriginal rendering, we can remove these unnecessary boundary tags.

![screen shot 2018-11-22 at 22 nov 11 36 45](https://user-images.githubusercontent.com/1212178/48921551-3d20f100-ee55-11e8-81e7-5393c944aaa3.png)
![screen shot 2018-11-22 at 22 nov 11 44 04](https://user-images.githubusercontent.com/1212178/48921554-3f834b00-ee55-11e8-933b-4949d43d7de6.png)

I've tested this change for Arizona and Washington State in the US, and British Columbia in Canada. I would have tested against Brazil, but most of the areas tagged with `protect_class=24` there are incorrectly tagged as `leisure=nature_reserve`, so they already show up on the current rendering, just in green, not in brown.

Note: I based my code as closely as possible on #3509, which adds more natural protected areas to the map. If that PR gets merged first, I realize that this PR #3521 will probably need to be rebased to avoid some conflicts.

**Comment by bdiscoe** [comment]
When I created the Nez Perce reservation (USA, Idaho, https://www.openstreetmap.org/relation/3907949) in 2014, the only tagging I could find was boundary=protected_area + admin_level=5; it has subsequently been changed from admin_level to protect_class=24, which is apparently more correct, but also had the effect of making it vanish.  I'll be delighted to see rendering of the area resume.

**Comment by Adamant36** [comment]
I was just reading about a place in India with an aboriginal tribe that is technically under the control of the Indian government, but the tribe kills anyone that goes near them. So they are mostly considered autonomous and don't get prosecuted for anything. 

There's also some places in South America where land that was once owned by indigenous people got taken over by farmers and was subsequently informally given back by the government, but in a lot of cases the farmers still live there with the indigenous people essentially squatting on their farms, on what "legally" might be the farmers land (but not really outside of that). 

Here in America though most native tribes have their own laws, court systems, and clear boundaries as to what is their territory. There's also a few places here that have been stuck in legal limbo since the early sixties that are still in dispute as to ownership and know one lives there, but could probably still be classified as a protected area. So, I agree with @jeisenbe that both tags might be necessary. Since its not so cut and dry. Talking about it on the mailing list wouldn't hurt either though.

**Comment by matkoniecz** [comment]
Can you consider making new proposal/updating existing at https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:boundary%3Daboriginal_lands ?

Currently it is completely unclear to me what is represented by this areas.

**Comment by almccon** [comment]
Thanks for the comments so far! You're all right that we should try to settle the tagging question at the same time as discussing the style. 

I updated the existing proposal at https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:boundary%3Daboriginal_lands and I sent an [email to the tagging list](https://lists.openstreetmap.org/pipermail/tagging/2018-November/041072.html) requesting that we start voting. Since it's been 10 years since the original proposal for `boundary=aboriginal_lands`, I hope we can quickly decide whether or not we need that tag or if we should deprecate it in favor of `boundary=protected_area` + `protect_class=24` only. Please join in the tagging discussion via email or on the wiki.

**Comment by almccon** [comment]
Also thanks @kocio-pl for pointing out the similarity with `tourism=zoo`. I hadn't thought of that.

Currently, we use #734a08 for `tourism=zoo` and `tourism=theme_park`. That's hsla(37, 87%, 24%, 1), which is fairly similar to the #82643a I'm using, which is hsla(35, 38%, 37%, 1). 

The two colors are very similar in hue, somewhat similar in lightness, but the zoo color is much more saturated. The zoo/theme park labels are in bold type, while the aboriginal areas are in non-bold italics. 

My gut feeling is that the colors are different enough to be distinguished, in the rare cases where there would ever be any confusion. I think in most cases the zoos and theme parks will be significantly smaller than aboriginal areas, and filled with very different types of features. So confusion will be extremely rare. Note that the largest zoos in the world are on the order of 100 acres (40 hectares). Most aboriginal reservations are much larger, but there certainly are a few that are that small.

But then there is the concern about what kind of message it sends to the map reader if they notice that we're using a similar color for zoos and for reservations. 

Here are a few examples of zoos and theme parks, for context:

Woodland Park Zoo, z16: https://www.openstreetmap.org/#map=16/47.6680/-122.3517
<img width="614" alt="screen shot 2018-11-24 at 24 nov 7 46 02" src="https://user-images.githubusercontent.com/1212178/48975265-a48b9c00-f021-11e8-8bf5-fff5f1e5e37f.png">

San Diego Zoo, z15: https://www.openstreetmap.org/#map=15/32.7360/-117.1517
<img width="472" alt="screen shot 2018-11-24 at 24 nov 7 47 14" src="https://user-images.githubusercontent.com/1212178/48975296-cbe26900-f021-11e8-920b-fe05ded90f8f.png">

Berlin Zoo, z14: https://www.openstreetmap.org/#map=14/52.5068/13.3378
<img width="479" alt="screen shot 2018-11-24 at 24 nov 7 48 06" src="https://user-images.githubusercontent.com/1212178/48975306-ec122800-f021-11e8-95cf-07a2af7f23a3.png">

Paris Disneyland, z12: https://www.openstreetmap.org/#map=12/48.8505/2.7287
<img width="273" alt="screen shot 2018-11-24 at 24 nov 7 49 59" src="https://user-images.githubusercontent.com/1212178/48975317-30052d00-f022-11e8-818f-b8c99666fb22.png">

**Comment by jeisenbe** [comment]
While the tourism boundary color appears much more saturated on the HSL
scale, by Lch it has a similar chroma to the proposed new color:

#734a08 is Lch(35,43,74) - lightness 35, chroma 43, hue 74

#82643a is Lch(44,29,77) - lightness 35, chroma 29, hue 77

Perhaps a hue on the orange side would work, especially if it is a bit
brighter, eg #ba5d1c is hsla(25,74%,42%,1) and Lch(50,61,57), or similar

Military is #f55, or hsla(0,100%,67%,1) or Lch(60,74,30), so it is still
far enough away from #ba5d1c


(BTW, why are tourism boundaries and military areas in landuse.mss but
national parks and nature reserves are in admin.mss?)

**Comment by matkoniecz** [comment]
> But then there is the concern about what kind of message it sends to the map reader if they notice that we're using a similar color for zoos and for reservations.

Yeah, it would not be unreasonable to interpret it in way that would be really poor to OSM community.

**Comment by matkoniecz** [comment]
> (BTW, why are tourism boundaries and military areas in landuse.mss but
national parks and nature reserves are in admin.mss?)

First two may be more about how land is used, next two can be considered to be more about a legal status. But it may be a result of the history of code or requirements for layering order rather than result of a classification like this.

**Comment by pnorman** [comment]
> #734a08 is Lch(35,43,74) - lightness 35, chroma 43, hue 74 #82643a is Lch(44,29,77) - lightness 35, chroma 29, hue 77

Without calculating the exact values, I believe these colours are distinguishable before the transparency, but that's not enough in this case. The colour difference formulas work well for something like commercial vs industrial landuse where they're both similar concepts. Zoos and aboriginal reserves aren't similar concepts, so it needs to be very clear they're different. This could be done by different drawing methods, or different colours. I like the inset semi-transparent border look for this, so it means a different hue needs picking.

> Perhaps a hue on the orange side would work, especially if it is a bit
brighter, eg #ba5d1c is hsla(25,74%,42%,1) and Lch(50,61,57), or similar

At full saturation the 70-80 hue range is a yellow-orange. This makes it difficult to get zoos different without making their lightness and chroma wildly different than the other inset transparent areas.

When I was in Boulder I went to the map library *specifically* to look at Indian reservations on maps. There were two cartograpies in use: Green, identical to nature reserves and parks, and brown. Green is a bad choice because it renders them similar to parks and nature reserves.

I'd rather move zoo's brown towards the green, perhaps 90, and use something like hue 70-60 for reserves


![image](https://user-images.githubusercontent.com/1190866/48979940-f9a5cd00-f076-11e8-8584-30b069192fcf.png)
*Washington Atlas & Gazetteer (Delorme, 2006)*

![image](https://user-images.githubusercontent.com/1190866/48979909-8dc36480-f076-11e8-83b9-307852bdb853.png)
*Washington Road & Recreation Atlas, 1:1400000 scale (Benchmark Maps, 2007)*

![image](https://user-images.githubusercontent.com/1190866/48979882-2b6a6400-f076-11e8-83ab-eb8efd9a1f1c.png)
*Washington Road & Recreation Atlas, larger scale (Benchmark Maps, 2007)*

**Comment by almccon** [comment]
FYI everyone, it was pointed out to me that on the wiki proposal I still didn't have a good description of what these features actually are in the real world. I added a lot more description there: https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:boundary%3Daboriginal_lands#Proposal

Sorry for the confusion for people who live in countries where these features don't exist. I hope the new description on the wiki will help clarify things.

**Comment by almccon** [comment]
@pnorman in your Delorme photo, I think the green there is landuse, not a fill for the reservation. Looking at the larger crop of the same map that you shared in Slack, I see that they're indicating the boundary of the reservation with a small dashed black line (which is very hard to see because it mostly follows roads). They aren't using any fill color for the reservation.

Compare this larger photo with the boundaries of the Lummi Reservation that we have in OSM, which are correct.

![delorme reservation](https://user-images.githubusercontent.com/1212178/48983136-130f3f00-f0a0-11e8-9af9-e15a836b66c2.png)

![screen shot 2018-11-22 at 22 nov 11 09 40](https://user-images.githubusercontent.com/1212178/48921544-32665c00-ee55-11e8-99ce-285c6d54883a.png)

**Comment by pnorman** [comment]
> reservation with a small dashed black line (which is very hard to see because it mostly follows roads). They aren't using any fill color for the reservation.

Ah, well spotted. I think that serves as an example of why a dashed line is bad cartography when it's likely to overlap with other features.

I'm sure I could find an example of green for reservations,

**Comment by matkoniecz** [comment]
@pnorman thanks for gathering this examples!

**Comment by arecvlohe** [comment]
@almccon I would like to speak on the idea of what the tags would be. I am a developer and member of the Muscogee (Creek) Nation so I have some insight into this. 

Tribal areas are mainly split into two areas: reservations and boundaries. Reservations are areas which exist within a state, or across states, that are domains where mainly tribal members reside. Then there are tribal boundaries, which are areas where both Native and non-Native communities exist but that share jurisdiction between Native and non-Native governments. Examples of tribal boundaries can be found in OK with tribes such as the Muscogee (Creek) Nation (http://mcngis.com/images/stories/maps/MCN_JURISDICTION_2016.pdf), and Cherokee Nation (http://geodata.cherokee.org/CherokeeNation/) just to name a couple.

Then things get more complex. For example, some tribes who were not set aside reservations will instead put land into trust for tribal members or for the government as a whole. An example of this would be the Thlopthlocco Tribal Town in Okemah, OK (http://tttown.org/about.html). In Florida, there is a band of traditional independent Seminoles who do not believe in land ownership and so have land that is put into trust for them by an outside organization (https://indianlaw.org/projects/past_projects/seminole).

Ideas that I have for tags would be: `tribal_reservations`, `tribal_boundaries`, and `tribal_trust_lands`. These things can be very nuanced so I think tags which speak to each one would be ideal. It's very possible that there just might not be any information, or any one willing to share the information, in regards to tribal trust lands. So that one may prove to not be helpful.

Now on to semantics. In the United States it's common for American Indians/Native Americans to just call one another Native. In South America, it's more common to hear Indigenous. And in Australia, it is more common to hear Aboriginal. This is mainly due to historical reasons and the same goes for the naming conventions above. For example, `tribal_boundaries` is used to refer to areas in OK, i.e. https://www.okhouse.gov/Documents/Districts/14-1101%20OK%20House%20and%20Tribal.pdf. The terms are certainly dated but it makes sense in terms of historical context.

But I suppose you would like to find something that unifies them. If that is your goal then a more all encompassing term would be `aboriginal` with any term afterward referring to jurisdictional matters, i.e. `aboriginal_lands`, `aboriginal_trust_lands`, `aboriginal_reservations`. That would be what would make the most sense to me. 

I hope this helps!

**Comment by Adamant36** [comment]
@arecvlohe, thanks for the extra information. It sounds semi complicated and like there might be a better tag possible for these areas then aboriginal lands. If you haven't already, it might be worth bringing up the same in the proposal for the tag. I don't remember seeing anything similar mentioned when I was reading through it and I think it would help people make a better decision to if its a good tag or not if they have the extra information. 

https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:boundary%3Daboriginal_lands

**Comment by kocio-pl** [comment]
@arecvlohe There is a pending discussion on Tagging list about it, it would be great if you could join it with your knowledge on this topic. There is also voting started on `boundary=aboriginal lands` (ending 8.12), which you might be interested in:

https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:boundary%3Daboriginal_lands

**Comment by kocio-pl** [comment]
It looks like `boundary=aboriginal lands` is going to be approved, so the next questions is what about alternatives? Will there be just one and the second will be discouraged or both will be used as currently?

https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Tag:boundary%3Daboriginal_lands

**Comment by matkoniecz** [comment]
With the current situation I would render both for now.

Unfortunately different regions use different tagging and neither is horribly wrong.

**Comment by turnsole80** [comment]
Well Australians do eat their national animal mascots, so gastronomy orange
might not be as far from the mark as you think ;)

**Comment by Tomasz-W** [comment]
@almccon Orange outline for zoos and theme parks was already proposed here: https://github.com/gravitystorm/openstreetmap-carto/issues/3045#issuecomment-361734148, please continue discussion about outlines colour change there. As we might use current brown outline for museums, we can use orange for zoos and/ or theme parks.

**Comment by almccon** [comment]
Thanks @Tomasz-W, I wasn't aware of that other issue. I agree that whatever color we pick for aboriginal areas needs to be coordinated with many other color outlines. 

It's also a bit of a chicken-and-egg problem. I would like to get aboriginal areas rendered sooner rather than later, without having to wait for the resolution of that other ticket, which has been open for almost a year.

Maybe we can find a "good enough" color for aboriginal areas to start with, and then potentially change them later in conjunction with changing several other boundary colors at the same time in #3045.

**Comment by kocio-pl** [comment]
I also think that the outline cleaning task should not be holding back everything. It just did not work as well as expected (nothing bad happened - just like many other interesting rendering ideas), so it's time to move on and maybe it will catch up later; who knows?

It seems to me that in general more intensive colors should be used for smaller features, so big ones do not dominate everything. So using above examples (which are quite similar to what I would pick), I think we could use strong violet for zoos/attraction park (more visible, related to attractions and emotions) and orange for museums (quite close to the brown, but not too strong because the outer line is darker), so simple brown (muted color) will be OK for aboriginal areas, because they are quite big.

**Comment by matkoniecz** [comment]
> I also think that the outline cleaning task should not be holding back everything.

Yes, there is no obligation to solve issues in some order - but it may have some ideas that may make easier to solve this zoo collision issue.

**Comment by jeisenbe** [comment]
we could use strong violet for zoos/attraction park ... and orange for
museums

👍 +1

Especially since attractions render with purple text, so a zoo or theme
park with tagged individual attractions (eg animals, rides) will look good
with a similar color for the border.

**Comment by Tomasz-W** [comment]
I propose:

* brown outlines for `aboriginal_lands` and `museum `(because they both have historical heritage protection character)
* orange outlines for `zoo `and `theme_park` (violet is used for industrial areas fill and shop icons, while orange only for gastronomy icons, so I would use less loaded colour for it, as they all match to these features at the same level to avoid unnecessary confusions)

**Comment by polarbearing** [comment]
I find the 'historical heritage' argument a bit dangerous with respect to the owners of the land. It is a reservation because it is _their land_, not because it is historic.

**Comment by Tomasz-W** [comment]
> I find the 'historical heritage' argument a bit dangerous with respect to the owners of the land. 

Maybe I wasn't precisious. I mean that both areas types function is to save cultural heritage.

**Comment by kocio-pl** [comment]
> violet is used for industrial areas fill and shop icons, while orange only for gastronomy icons, so I would use less loaded colour for it, to avoid unnecessary confusions as they all match to these features at the same level

I don't think we can try match areas to lines and nodes.

**Comment by pnorman** [comment]
> Maybe I wasn't precisious. I mean that both areas types function is to save cultural heritage.

I have to disagree, or take a view on preserving cultural heritage that is so wide as to be useless. People live there. There are elements of preserving culture, but the same is true of libraries, universities, malls, and most places people congregate.

I'd like to see this tested if anyone has the time.

> I'd rather move zoo's brown towards the green, perhaps 90, and use something like hue 70-60 for reserves

**Comment by kocio-pl** [comment]
My feeling is that it's do stretched, that in fact it's tagging for rendering - these are for cultural and political protection, not nature... I'm happy that this code is finally in the repo.

**Comment by almccon** [comment]
I just saw my first aboriginal areas showing up on osm.org! Thanks again to everyone who helped get these on the map.
<img width="368" alt="Screen Shot 2019-03-16 at 16 Mar 9 05 58" src="https://user-images.githubusercontent.com/1212178/54485168-51885f80-4831-11e9-81c7-684183671ac1.png">
<img width="1101" alt="Screen Shot 2019-03-16 at 16 Mar 9 05 17" src="https://user-images.githubusercontent.com/1212178/54485169-51885f80-4831-11e9-88b8-c9bc3126ecaf.png">
<img width="496" alt="Screen Shot 2019-03-16 at 16 Mar 9 03 27" src="https://user-images.githubusercontent.com/1212178/54485170-51885f80-4831-11e9-85af-9ac9395cbd8e.png">
<img width="543" alt="Screen Shot 2019-03-16 at 16 Mar 9 02 32" src="https://user-images.githubusercontent.com/1212178/54485171-51885f80-4831-11e9-8c1a-c19e49ddc501.png">

**Comment by kocio-pl** [comment]
Good to see that fixed. I hope Brazil is OK now and I guess Australia still needs retagging of some areas:

![Screenshot_2019-03-17 OpenStreetMap](https://user-images.githubusercontent.com/5439713/54487975-7960dd00-489c-11e9-958b-5874d48d0c72.png)

**Comment by jeisenbe** [comment]
At first I thought those areas in Australia were mistagged, but they are
actually areas where the environment has been protected by the local
indigenous community, so they are a type of nature reserve area.

https://en.m.wikipedia.org/wiki/Indigenous_Protected_Area

“
Description
An Indigenous Protected Area is a class of protected area used in Australia
formed by agreement with Indigenous Australians, declared by Indigenous
Australians, and formally recognised by the Australian Government as being
part of its National Reserve System”
Desc
An Indigenous Protected Area is a class of protected area used in Australia
formed by agreement with Indigenous Australians, declared by Indigenous
Australians, and formally recognised by the Australian Government as being
part of its National Reserve System”
