### ISSUE TITLE
Render some patterns from z13

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3593]
Some patterns starts rendering on z14.

Example place where it causes a problem:
https://www.openstreetmap.org//#map=13/34.2229/-117.8636 (scrub)
https://www.openstreetmap.org/way/222247331#map=13/36.3148/-121.2710 (vineyard)

Rendering some of patterns from z14 causes incomplete rendering of some areas when they are big.

This problem affects following areas:
* vineyard
* orchard
* garden
* plant_nursery
* cemeteries (?)
* marsh, saltmarsh, wet_meadow (`wetland_marsh`)
* reedbed (`wetland_reed`)
* mangrove (`wetland_mangrove`)
* swamp (`wetland_swamp`)
*  bog, fen, string_bog (`weteland_bog`)
* beach, shoal (`beach`)
* gravel, fine_gravel, pebbles, pebblestone, shingle, stones, shells (`beach_coarse`)
* scrub (`scrub`)

**Comment by jeisenbe** [comment]
I've tested in the Azores, because these islands have very detailed landuse and landcover patterns, including vineyards, orchards and scrub. 

There are also many small gardens,  and allotments, but none of them are big enough to be seen on z13. This does make me concerned about how much performance loss we will see, for a small improvement.

Flamengos village, Azores (remember this from the Allotments test images?)
https://www.openstreetmap.org/#map=13/38.5503/-28.6145
- The patterns are hardly visible because the areas are too small
z13 Before
![z13-flamengos-master](https://user-images.githubusercontent.com/42757252/50503804-e25e6300-0aac-11e9-9c08-45c44f01e5f6.png)
After
![z13-flamengos-patterns](https://user-images.githubusercontent.com/42757252/50503808-e5595380-0aac-11e9-82da-7267c739e551.png)

Caldeira https://www.openstreetmap.org/#map=13/38.5887/-28.7161
- Many thin areas of scrub, and a moderately large marsh, just big enough to show the pattern
z13 before
![z13-caldeira-master](https://user-images.githubusercontent.com/42757252/50503810-e8544400-0aac-11e9-8a96-eceddf838e15.png)
After
![z13-caldeira-patterns](https://user-images.githubusercontent.com/42757252/50503812-eab69e00-0aac-11e9-9590-a2ae0ef46ac8.png)

Magdalena - Vineyards, large to the south, smaller northeast of the town
https://www.openstreetmap.org/#map=13/38.5111/-28.4603
z13 before
![z13-magdalena-master](https://user-images.githubusercontent.com/42757252/50503816-eee2bb80-0aac-11e9-8ea1-b932ab12f7d8.png)
After
![z13-magdalena-patterns](https://user-images.githubusercontent.com/42757252/50503818-f1451580-0aac-11e9-80c2-4f39c68d2a10.png)

Sete Cidades - mountain with very detailed forest and scrub following drainage lines
- scrub pattern is just visible
https://www.openstreetmap.org/#map=13/37.8759/-25.7421
z13 before
![z13-sete-cidades-master](https://user-images.githubusercontent.com/42757252/50503822-f4d89c80-0aac-11e9-8e77-33a4364a0112.png)
After
![z13-sete-cidades-pattern](https://user-images.githubusercontent.com/42757252/50503825-f86c2380-0aac-11e9-8674-c61a8ad72ffd.png)

Monte Escuro - large area of scrub to the south, smaller orchards in the northeast (near Sâo Brás)
https://www.openstreetmap.org/#map=13/37.7890/-25.3962
z13 before
![z13-escuro-master](https://user-images.githubusercontent.com/42757252/50503828-fdc96e00-0aac-11e9-8960-be3cacfdf345.png)
After
![z13-monte-escuro-patterns](https://user-images.githubusercontent.com/42757252/50503830-04f07c00-0aad-11e9-8a44-1b192dc1a215.png)

**Comment by Adamant36** [comment]
Its a small improvement if you test it somewhere small. That aside, At least its more consistent and its not like @kocio-pl can't have it tested if need be. Z13 isn't all that zoomed out either. I think if it was at a more zoomed out level then that it would be an issue, but like you say its usually only small areas anyway.

**Comment by jeisenbe** [comment]
Wales: scrub, beaches, bogs, marshes, plant nurseries and cemeteries in Wales

Near Llyn Brenig lake - scrub and other green areas
https://www.openstreetmap.org/#map=13/53.1059/-3.4848
z13 Before
![z13-llyn-brenig-master](https://user-images.githubusercontent.com/42757252/50504235-83e6b400-0aaf-11e9-8dfe-1502804f8ee0.png)
After
![z13-llyn-after](https://user-images.githubusercontent.com/42757252/50504889-fb1e4700-0ab3-11e9-89ab-5ffd406b13b8.png)

Gellilydan - scrub, marsh and bog
https://www.openstreetmap.org/#map=13/52.9349/-3.9033
z13 before
![z13-gellilydan-master](https://user-images.githubusercontent.com/42757252/50504237-85b07780-0aaf-11e9-813b-9c000152a874.png)
After
![z13-gellilydan-after](https://user-images.githubusercontent.com/42757252/50504462-23f10d00-0ab1-11e9-98db-2eccca8a062f.png)

Gronant - beaches, wetland, cemetery, scrub
https://www.openstreetmap.org/#map=13/53.3439/-3.3186
z13 before
![z13-gronant-master](https://user-images.githubusercontent.com/42757252/50504238-85b07780-0aaf-11e9-8d9f-6fbccec6011a.png)
After
![z13-gronant-after](https://user-images.githubusercontent.com/42757252/50504624-34ee4e00-0ab2-11e9-8c05-9b3237716339.png)

Bryn Euryn - cemeteries, allotments, plant nursery and garden (rather small, but just visible)
https://www.openstreetmap.org/#map=13/53.2968/-3.7009
z13 before
![z13-bryn-euryn-master](https://user-images.githubusercontent.com/42757252/50504239-8943fe80-0aaf-11e9-81ea-d0a3b6ff8e47.png)
After
![z13-bryn-after](https://user-images.githubusercontent.com/42757252/50504473-33705600-0ab1-11e9-9e77-266d91c9864d.png)

- The cemetery patterns are particularly widely spaced; this means an area needs to be rather large before the pattern is visible. 
- This is less of a problem with vineyard, orchards, gardens and nurseries, though the latter two are often small areas.

**Comment by jeisenbe** [comment]
Mangroves will certainly benefit from a pattern at z13. This area of mangroves would fill my whole screen even at z12. (Reminder to self - add a background fill color for mangroves)

https://www.openstreetmap.org/#map=12/-5.1675/137.7358
z13 before
![z13-mangroves-master](https://user-images.githubusercontent.com/42757252/50505500-556cd700-0ab7-11e9-8fa1-21b0e4b8c103.png)
After
![z13-mangroves-after](https://user-images.githubusercontent.com/42757252/50505502-57cf3100-0ab7-11e9-99ce-30caa7032e1b.png)

**Comment by Adamant36** [comment]
Looks like both mangroves and beaches would.

**Comment by Adamant36** [comment]
What about just not rendering patterns at z13 anymore? Like you say, its mostly smaller areas, woods are the exception, and its not like the fill colors aren't good enough.

**Comment by jeisenbe** [comment]
Large marsh area in Delaware; there are several along the bay.
https://www.openstreetmap.org/#map=13/39.2592/-75.4425
z13 before
![z13-marsh-before](https://user-images.githubusercontent.com/42757252/50522471-744a8800-0b0e-11e9-8bd3-d2f9026b678f.png)
z13 after
![z13-marsh-after](https://user-images.githubusercontent.com/42757252/50522473-76144b80-0b0e-11e9-82bb-c70fc86e4a02.png)

Great Cypress Swamp:
https://www.openstreetmap.org/#map=13/38.4833/-75.2247
z13 before
![z13-cypress-swamp-before](https://user-images.githubusercontent.com/42757252/50522460-6b59b680-0b0e-11e9-8905-f1d1f07ddb37.png)
After
![z13-cypress-swamp-after](https://user-images.githubusercontent.com/42757252/50522464-6eed3d80-0b0e-11e9-8058-7404eebcc9e4.png)

Cape Henlopen - marshes, also beach and scrub pattern visible
https://www.openstreetmap.org/#map=13/38.7707/-75.0920
z13 before
![z13-cape-henlopen-before](https://user-images.githubusercontent.com/42757252/50522456-672d9900-0b0e-11e9-8026-651f0076ba39.png)
After
![z13-cape-henlopen-after](https://user-images.githubusercontent.com/42757252/50522455-6563d580-0b0e-11e9-86de-aacd8ad9ba49.png)

**Comment by kocio-pl** [comment]
From what I see and my experience with other patterns - it never hurts to have pattern on a given zoom level when the area is small (you just don't see the pattern), but helps when the area is bigger, so I think it's **always** safe to render them earlier. I have literally found not a single case when rendering pattern did hurt anything. Especially with z13, when we have some patterns (like trees) and not the others, which can be as big. 

There are also even bigger areas where it could help to show patterns much earlier, like here:

https://www.openstreetmap.org/#map=8/63.261/174.960

but it needs testing, because z13+ has no color fading applied.

So I would start with z13+ PR for all the patterns to not waste the time, and prepare additional tests for lower zoom levels.

What do you think about it?

**Comment by jeisenbe** [comment]
Previously only the natural areas (forest, and, rock etc) were rendered at
this level, but we recently started rendering the allotments pattern at
z13, per the preference of @kocio-pl, and it seems to be working fine.

Cartographically, I don’t see any major problems, though I have yet to find
any cemeteries large enough to render more than one icon from the pattern
at z13, every other type considered would sometimes benefit.

The wetlands have a generic pattern even at z13, and most have a full color
which matches the vegetation class, but the specific patterns are helpful
for large areas.

The only issue would be if this slows down rendering performance at z13.
Hopefully that can be tested?

I can make a PR with the relevant code for testing.

**Comment by kocio-pl** [comment]
I believe our main performance problem is reading database, not painting patterns, so I would not be afraid of that. OK, so go ahead.

**Comment by jeisenbe** [comment]
Aha, here is a large cemetery, 1 km long and almost as wide. Two cemetery pattern icons render at z13 in this case. So we might as well start all of the patterns at >= z13 for consistency.

**All Saint's Cemetery, Pike Creek, Delaware:**
https://www.openstreetmap.org/#map=13/39.7096/-75.6226
z13 Before
![z13-drummond-cemetery-before](https://user-images.githubusercontent.com/42757252/50531224-edb39c00-0b49-11e9-8bd5-321fb7291d77.png)
After
![z13-drummond-cemetery-after](https://user-images.githubusercontent.com/42757252/50531226-eee4c900-0b49-11e9-962c-4ffa9c265778.png)
