### ISSUE TITLE
Render disused:power=* like power=*

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#3608]
### Expected behavior
Render `disused:power=(cable|line|minor_line)` like `power=(cable|line|minor_line)`, as `disused:*` says that the features are still present, but no longer used.

### Actual behavior
Not rendered.

Please note that I can take care of that myself, but first I would like a confirmation that this is relevant. IMO, it is, as these features are still visible in the landscape, hence justifying their display, but I can be wrong, for instance because `disused:power=*` is under a thousand occurrences. Rendering these could help spread the life cycle prefixes, though.

**Comment by Adamant36** [comment]
How do you tell the difference on the ground between a disused and used power line? There's some railroad tracks near where I live with older power lines along them. Most of the poles and lines have fallen over onto what use to be the old railroad track before they built a bridge (I should probably map that at some point). A few times I climbed up the downed poles to steal those glass covers they use to all have. Unfortunately they wouldn't come off though. So I scuttled back down. Since I'm at the age where even the slightest height makes me not want suffer the potential injury of a useless fall. 

Anyway, if they are disused like that, I don't think they are worth rendering. At least not in the same way as normal ones. There should be a way to tell if they are "live" or not. I have no clue how the difference could be told or rendered though.

**Comment by Penegal** [comment]
In fact, the French tranport network manager publishes data about these lines, and tells whose are no longer used, but still kept functional. I didn't climb to check if they are live, though.

**Comment by Adamant36** [comment]
Hhmmm interesting. Good to know that goes for France at least. You were probably better off not checking yourself. 

I should see if they have something similar here.

**Comment by sommerluk** [comment]
Usage:
line: 139
cable: 135
minor_line: 21

These values are quite low, on the other hand there would be no special rendering, so this would form a group together with the in-use counterpart, where the numbers are much higher.

The question is if to render it or not. I’m a little bit indecisive. Of course a disused supermarket should not render as a shopping feature because you cannot do any shopping any more. So in general it is a good idea not to render disused features. On the other hand maybe power lines are less a “feature” to use for average map user, but rather a landmark?

**Comment by kocio-pl** [comment]
Latest discussion about #3535 shown me that `disused:` is not as clear when applied to different kind of objects as it sounds when talking about shops. I guess this is a landmark indeed, similar to disused railways.

**Comment by Penegal** [comment]
@kocio-pl: my proposal was indeed caused by these features being a landmark.

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/keys/disused%3Apower#values - it seems that disused:power is extremely rare. I would close it and reopen once tag is more widely used (at least 1000+ uses of disused:power=cable / disused:power=line / disused:power=minor_line)

Note: it is not promise to render it once it reaches this threshold.

**Comment by jeisenbe** [comment]
I'm inclined to close this issue, both for the reasons above (https://github.com/gravitystorm/openstreetmap-carto/issues/3608#issuecomment-457585461, https://github.com/gravitystorm/openstreetmap-carto/issues/3608#issuecomment-450499002 and https://github.com/gravitystorm/openstreetmap-carto/issues/3608#issuecomment-450494287), and because it is not clear that disused:power=line is more correct than power=line + disused=yes. 

Since there is no safe way to verify whether a power line, cable or tower is in use when checking a feature in person, it is reasonable for mappers to use `power=*` and then add `disused=yes` based on official sources when this information is available. We map and render these features mainly because they are good orientation landmarks in rural areas, so whether or not the line is carrying electrical current is not as relevant to most database users.

See also #2030 where we declined to render `disused:railway` like `railway=disused`, and similar discussion about `disused:quarry` in #3535.

However, if changes in mapping practice lead to a new consensus about this tagging in the future this issue could be reopened at that time.

**Comment by jeisenbe** [comment]
Now there are [443 ways](http://overpass-turbo.eu/s/NYw) with disused:power=line/minor_line/cable

But there are 430 power=line/minor_line/cable + disused=yes - http://overpass-turbo.eu/s/NYx

**Comment by flacombe** [comment]
Hello guys,

I've properly read all previous comments of this issue and I don't intend to (re)open a tagging debate here.

Current state is:

- 3 563 features combine power=* and disused=yes (among which 772 line and 198 minor_line)
- 6 928 features use disused:power=* (among which 590 line and 137 minor_line)

This information is surveyed and disused state is set as soon as a line segment is visually unconnected.

> However, if changes in mapping practice lead to a new consensus about this tagging in the future this issue could be reopened at that time.

I think we are not likely to reach consensus because some mappers actually use disused:power=* whereas [the wiki still encourages](https://wiki.openstreetmap.org/wiki/Tag:power%3Dline#Disused_&_demolished_power_lines) to use disused=yes mostly because of renders. So the two schemes will continue their growth without clear choice between them.

As we also use construction:power (7 135), removed:power (18 664) or demolished:power (14 028) for other states, that are less prominent for render, I would be in favor of a consistent use of lifecycle prefixes for power infrastructure.
removed:power/demolished:power are only intended to prevent features to reappear after removal from ground as they could be still visible on latest aerial imagery. It's not an attempt to let them in OSM while removed from ground.

**Comment by flacombe** [comment]
It's true disused and abandoned common terms may be mistaken and require a refinement.
That would be consistent to consider energized without transit (connected at one end and disconnected elsewhere, surveyable) disused and out of service (completely disconnected) as abandoned.
Anyway it's surveyable and verifiable at any time.

From render perspective, only abandoned state (currently disused) would deserve a different color
