### ISSUE TITLE
Add rendering amenity=parking_entrance (access=private)

### ISSUE THREAD

**Issue by jaffroy62** [gravitystorm/openstreetmap-carto#3672]
refers to #3600 and #270

the am=parking_entrance w access=private was transiently rendered in the past months: 
<img width="40" alt="image" src="https://user-images.githubusercontent.com/42764343/52233859-7697c300-28c0-11e9-9e58-43159206ccbc.png">

Now the rendering of these vanished and only parking_entrances w/o access=private are rendered at the moment.

**Can you please render them again** - perhaps in a different "private" apperance (e.g. higher transparency, reduced saturation)

Pro arguments: 
- no cluttering because: taginfo count parking_entrance: n=54556 
    but in combination w/h access=private only n=14058 (about 25%)
- contains relevant information: it's clearly associating a purpose for a way - this helps to orientate in the field even if you can not open the door described

**Comment by matkoniecz** [comment]
a potential test case: https://www.openstreetmap.org/node/6048582374#map=19/50.08520/19.88597&layers=N

**Comment by kocio-pl** [comment]
To be precise: they were never displayed and it has nothing to do with #3600  - see #3505.

**Comment by jeisenbe** [comment]
I think it's unlikely that rendering the location of entrances to private underground parking garages would be helpful for a general map. These are underground parking structures, so they are not visible except for the door, and the public cannot use these.

We show a faint icon for private surface parking lots because this is needed to understand what sort of area feature is rendered. But there is no area rendering for these underground parking lots.

So I recommend declining this request.
