### ISSUE TITLE
Add rendering for amenity=watering_place

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3703]
I'd like to see rendering added for amenity=watering_place. As it would help the map to better serve the needs of more rural mappers. I know mappers are lacking in more remote areas. I think supporting tags that they would find useful can help. Plus, the tag has 6,140 uses already and is increasing at a pretty brisk pace. The wiki says it can be mapped as both an area and a node. So I guess it needs an icon or something. 

![taghistory 2](https://user-images.githubusercontent.com/30259065/53799142-9f769c80-3eee-11e9-9e52-30a476609516.png)

**Comment by matkoniecz** [comment]
Based on my experience with hiking - I would say that it is a really unimportant feature as POI - ones with drinkable water are already rendered if tagged properly.

As an orientation point it is also quite useless as this places change quite often (this may be different in other parts of the world) and are often relatively hard to interpret is it really this location.

Overall I would be strongly against rendering it, especially as it would be extremely hard to properly differentiate it from places where humans may drink water.

**Comment by imagico** [comment]
On a more general note - instead of showing a taghistory plot, which says very little about the use of a tag that is relevant here, it would be more useful to actually analyze use of the tag in question on a semantic level, i.e. what the tag is actually used for.

If you do this here you will find out that:

* the tag is sometimes used as a primary tag but also used as a supplemental tag in addition to natural=spring, man_made=water_well or natural=water.
* there is significant abuse of the tag for man_made=water_well or man_made=water_tap, for example in urban settings and on graveyards which feature historic troughs.

Both these observations indicate that trying to render amenity=watering_place without rendering man_made=water_well is not advisable and any rendering of amenity=watering_place would need to work both for use as a primary and secondary tag.

**Comment by matkoniecz** [comment]
> instead of showing a taghistory plot, which says very little about the use of a tag that is relevant here

In general - taghistory plot may be sufficient to refuse rendering (declining usage, recent jumps indicating that most uses is added by import, low usage, low usage compared to alternatives etc) it is not sufficient to justify rendering.

**Comment by Adamant36** [comment]
> On a more general note - instead of showing a taghistory plot, which says very little about the use of a tag that is relevant here, it would be more useful to actually analyze use of the tag in question on a semantic level, i.e. what the tag is actually used for.

I much rather use the tag history as a metric to render something or not compared to how a few of them might be tagged out 5,000 there are. As everything is miss-tagged to a degree and me glancing at a few "real world" use cases isn't a representative sample. 

Also, as @matkoniecz says the tag history plot is a good way to tell if the usage is "organic" or not. I wouldn't advocate for a tag to be rendered if most of its uses were added through an import. Something you can't tell simply by looking at a few uses in the real world. Ultimately the tag history is only one metric I use. 

I do actually look at the tags usage "semantically" before hand, but like I said its to open to sampling bias for me. The leisure=horse_riding issue (I think it was that one), was a good example of that, where me and @Hufkratzer found the semantic tagging to be fine but then a maintainer didn't. So it should only be one metric out of several. If anything its the worst one since the style is suppose to be encouraging proper tagging through rendering things in IMHO. Instead of not rendering things based on bad tagging. So I'm definitely not going to open a new issue based just on a tags "proper" usage or not.
