### ISSUE TITLE
healthcare=counselling no icon no text

### ISSUE THREAD

**Issue by thetornado76** [gravitystorm/openstreetmap-carto#3706]
At this node https://www.openstreetmap.org/node/1252888814 there is no icon or text.

Please add icon and text for healthcare=counselling similar healthcare=laboratory
![screenshot_20190305-175802_chrome](https://user-images.githubusercontent.com/20454020/53822860-da211900-3f70-11e9-913b-5562d91f53a3.jpg)

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/tags/healthcare=counselling - used just 37 times so lack of rendering it is not too surprising

From https://github.com/gravitystorm/openstreetmap-carto/blob/4df96c4e4927c3e029b31e34c0cf1be2dda6f637/amenity-points.mss#L716 it seems to not be list of rendered tags

**Comment by Adamant36** [comment]
Maybe it could get a dot at least so the building doesn't look un-tagged or empty (do healthcare objects even have dots? I can't remember).

**Comment by wilmaed** [comment]
> 
> 
> do healthcare objects even have dots? 

yep:
https://www.openstreetmap.org/node/5445761071

**Comment by Adamant36** [comment]
Thanks, I thought they did.

**Comment by woodmiser** [comment]
I had the same problem a couple days ago.  As a workaround, I tagged the place with
amenity=social_facility
social_facility=outreach
social_facility=mental_health
and it gets rendered now.  You might consider whether the place you are trying to tag fits that description, and tag it with that temporarily.
Anyway, I just checked taginfo and it is up to 72 now.
https://taginfo.openstreetmap.org/tags/healthcare=counselling
Also ran an overpass global query, which found 110.  So, hopefully this tag will get the attention it need soon.
Cheers

**Comment by polarbearing** [comment]
> Also ran an overpass global query, which found 110

This is incorrect, you were including the nodes in polygons probably. 

The counselling value has no wiki page and no proposal. I would expect a healthcare value to describe some _therapeutic_ approach, and not counselling. Among the values I found a WeightWatchers office, which certainly does not fit. 

It seems that in indeed 'social facility' would be a better fit in particular in the context of mental health. 

I propose to close the issue.

**Comment by Adamant36** [comment]
I wouldn't counselling a social facility. 1. Its not really "social" in the context of the tag 2. Places that are just for counselling, including ones made of up a single therapist in an office, aren't "facilities." Also, plenty of people without mental issues go to counselling. So tagging them as "mental_health" places doesn't seem right.

**Comment by jeisenbe** [comment]
“Counseling” is ambiguous. Some people call treatment by a clinical
psychologist “counseling”, but it can also refer to therapy for addictions,
marital problems, child behavioral issues and parenting, etc.

And as mentioned above, “counseling” can also refer to therapy to help lose
weight or improve fitness.

I’ve also heard people talk about financial counseling for getting out of
debt and spiritual counseling from religious organizations.

I would recommend using a more specific tag. Probably this should be
discussed on the Tagging mailing list

>

**Comment by matkoniecz** [comment]
Can someone link documentation at OSM wiki?

Note that this is not a good place to discuss how things should be tagged.

**Comment by matkoniecz** [comment]
This tagging is documented at https://wiki.openstreetmap.org/wiki/Key:healthcare#Specialities_for_healthcare.3Dcounselling

Please discuss is it bad or OK at https://wiki.openstreetmap.org/wiki/Talk:Key:healthcare or tagging mailing list and potentially update description at wiki.

**Comment by jajajaneeneenee** [comment]
Hi! I am also missing an icon or text for **healthcare=counselling**. Especially because the [german wiki ](https://wiki.openstreetmap.org/wiki/DE:Key:healthcare#Darstellung_/_Rendering) says that **all** other objects of the healthcare tagging scheme (which are not "hospital", "clinic", "centre" or "doctor") are displayed by cartoCSS with a red dot! I counted on that and was surprised that it did not work with **healthcare=counselling** (to render on openstreetmap.org). I would have to change the tagging to healthcare=yes (which would be tagging for the renderer). The [english wiki](https://wiki.openstreetmap.org/wiki/Key:healthcare#Rendering) also says for the red dot: "other healthcare places".

And the value "counselling" **is** in the list of values on [https://wiki.openstreetmap.org/wiki/Key:healthcare#Values](https://wiki.openstreetmap.org/wiki/Key:healthcare#Values). But only since March 2019, and the coding was in November 2018 (see below) ... bad ...

I think the problem comes from the decision in [#3498](healthhttps://github.com/gravitystorm/openstreetmap-carto/pull/3498), to restrict the rendering **to the list of the documented values** ([see this comment in #3498](https://github.com/gravitystorm/openstreetmap-carto/pull/3498#issuecomment-436638345)) and the following discussion ... 

The warnings that the code will have to be changed with new documented values in the wiki was ignored (or rejected). See these comments of Tomasz-W:

- [https://github.com/gravitystorm/openstreetmap-carto/pull/3498#issuecomment-436895147](https://github.com/gravitystorm/openstreetmap-carto/pull/3498#issuecomment-436895147)
- [https://github.com/gravitystorm/openstreetmap-carto/issues/2938#issuecomment-427017513](https://github.com/gravitystorm/openstreetmap-carto/issues/2938#issuecomment-427017513)

And **healthcare=counselling** is such a problem, as it was added in the wiki 03.03.2019 by Thetornado76 (and the rendering was implemented in November 2018)!

So if following the decisions in [#3498](healthhttps://github.com/gravitystorm/openstreetmap-carto/pull/3498), a rendering for healthcare=counselling should be added now .... At least this was the descision there (that any **documented value** should be added). And I would very much appreciate that. But I am new here at GitHub, and I don't know how to initiate such a change of the code. Could anyone do that? Or does it needs more discussion here? Or somewhere else?

And can this thread be added to the discussion in #3498 as areference? Like after this comment: [https://github.com/gravitystorm/openstreetmap-carto/pull/3498#issuecomment-451863048](https://github.com/gravitystorm/openstreetmap-carto/pull/3498#issuecomment-451863048) I don't know if I could do that ...

Final note: IMHO it was a bad decision not to render a red dots for ALL values of healthcare=*, even if they are not documented in the wiki. Because the taglist shows a lot of good (but rarely used values) and the danger of bad values is not a good argument I would say ... Perhaps THIS should be discussed again (to open the rendering as a red dot for ALL values). And it would be much easier and avoid discussions like this one ...

**Comment by matkoniecz** [comment]
> Especially because the german wiki says that all other objects of the healthcare tagging scheme (which are not "hospital", "clinic", "centre" or "doctor") are displayed by cartoCSS with a red dot!

That appears to be incorrect given that `healthcare=counselling` is not rendered.

> I would have to change the tagging to healthcare=yes (which would be tagging for the renderer)

Yes, please do not remove correct data solely to change rendering.

**Comment by Adamant36** [comment]
> IMHO it was a bad decision not to render a red dots for ALL values of healthcare=*, even if they are not documented in the wiki

I'm not sure where you got the idea that the only requirement for something is whether its documented in the wiki or not. There's a lot of other factors also, like real world tag usage, if the definition makes sense, and a bunch of other things. That goes for red dots as much as adding icons. Otherwise, a lot of other tags would already be rendered, not just those in healthcare=* domain. In general, anyone can create a Wiki page for anything. So its not that reliable and can't be the only deciding factor for things. 

As far as counseling goes, I guess you could make the argument that its not any more generic or ambiguous than "clinic" or "hospital" is, and those things are rendered. That doesn't mean I'm in support of it though. Id be tempted to go the other way and that healthcare=clinic and healthcare=hospital should be removed instead in favor of more specific tagging schemes (their kind of like shop=yes to me. Which other people here have a problem with), but my opinion ultimately doesn't matter and its probably off topic anyway.

**Comment by jajajaneeneenee** [comment]
@ matkoniecz: Yes it is incorrect, and I was also thinking about doing a correction in the wiki. At least the table of values at the beginning of the wiki page shows correctly that healthcare=counselling is NOT rendered, but I did not see this when doing he tagging – I first only read the text in the chapter „Rendering“ ....

@Adamant36: Yes I got the idea. I was only trying to follow the argumentation in #3498 which was the core of the current situation ...

**Comment by Adamant36** [comment]
> it is hard for other people who edit the wiki to find out what is rendered and not

Usually when something is render someone from here will almost immediately update the tags article to reflect it. Although it doesn't always happen that way. So its usually not an issue and you can generally conclude that if there is no rendering mentioned in the tags article that it isn't rendered.

Also, this isn't CartoCSS, its the Openstreetmap-Carto style. CartoCSS is just the programming language it uses to render things, but its not exclusive to this style and is only a part of what runs it. I made the same mistake myself when I started here. 

> Yes I got the idea. I was only trying to follow the argumentation in #3498

That's fine. I just thought clarify since you said you don't have much experience with things ;)

**Comment by jeisenbe** [comment]
Current usage is up to 234, almost 6 months later. https://taginfo.openstreetmap.org/tags/healthcare=counselling

I will close this issue for now. Consider documenting the tag with it's own wiki page, since currently it is only described as "healthcare counseling" on https://wiki.openstreetmap.org/wiki/Key:healthcare#Specialities_for_healthcare.3Dcounselling - so there is no clear definition. 

We can reopen this issue if the tag is fully documented and discussed, and the usage increases further. 

Also note that the key `healthcare=` will need to wait till after the next database reload for rendering.

**Comment by jeisenbe** [comment]
Now the tag is documented as "A facility where health counselling is provided, e.g. dietitian, nutrition, addiction” and usage has increased to 1 216 - however only 679 have a tag to specify the kind of counseling: https://taginfo.openstreetmap.org/keys/healthcare:counselling - “dietitian”, “antenatal” and “addiction” counseling are quite different.

**Comment by Cj-Malone** [comment]
The number is now 4.5k, of those, 1.2k also have an amenity=* tag so are likely being rendered (likely incorrectly). The OSM data here isn't great.

<img width="320" height="270" alt="Image" src="https://github.com/user-attachments/assets/e1dae70a-aa23-4123-b543-e2e49a8a83f9" />
