### ISSUE TITLE
landcover=trees in Paraguay. There is an error of information here

### ISSUE THREAD

**Issue by CarlosBrys** [gravitystorm/openstreetmap-carto#3708]
You say that "data comes from a single import in Paraguay", and that is a mistake.

First: it's not an import, and second: it's not simple.

The data was loaded for a long time by students of a research project of the Faculty of Architecture and Design of the National University of Asuncion.

See: https://cidifadauna.com/2018/10/23/presentacion-de-map-py-osm-en-state-of-the-map-latam-2018-buenos-aires/

The use of the label landcover was discussed at length with the OSM community of Paraguay and Argentina because the research project maps urban trees, and that they are not woods or forest.

There is no soil management in the squares or the houses of the cities, they are only lands covered with trees, that is why the natural wood or managed forest labels are not applicable in that context.

**Comment by Adamant36** [comment]
You could have waited for the issue to be reopened to say so. Opening a whole new issue for it instead of waiting just feeds the narrative that people for landcover tagging are "reactionary." Which ultimately doesn't help your side of the discussion. 

That aside, I think you make some valid points and you should bring them up in the original issue when it is re-opened. If the import or whatever you want to call it was widely discussed with the subsequent OSM communities of those places and @matkoniecz just missed it, that pretty much nullifies his argument. Last time I checked local mapping not something to be maligned like it seems it was in this case. 

Anyway, thanks for doing the research. Take it up in the original discussion when you can.

**Comment by imagico** [comment]
I am locking this as a restart of the discussion on #2548.  This is not a statement about the appropriateness of the comment made here.

You are welcome to continue **on topic** and **respectful** conversation on #2548 when we unlock it but in the meanwhile should take the time to reflect on the subject and what you want to say about it and if it really brings the matter forward.
