### ISSUE TITLE
No icon for shop=caravan

### ISSUE THREAD

**Issue by valhentai** [gravitystorm/openstreetmap-carto#3710]
There is no icon for **shop=caravan** ([wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcaravan) ), a shop specialized in travel trailer, motorhomes and campervan.

The lack of icon make people fallback on already rendered tag. Those shop are often mistagged as **shop=car** or **shop=outdoor**.
They are not shop=car because sometimes they only sell travel trailer which are not cars.
And they are not shop=outdoor because outdoors shop do not sell vehicles.

**Comment by Adamant36** [comment]
Its not going to be rendered any time soon with only 169 uses. Sorry.

**Comment by matkoniecz** [comment]
> The lack of icon make people fallback on already rendered tag.

This shop, like any other shop should be rendered with at least dot unless blocked by more important nearby objects.

`shop=caravan` is tagged just 208 times. Is it supported in editors like iD, JOSM, Vespucci?

**Comment by valhentai** [comment]
It is supported in iD editor as RV dealership

**Comment by matkoniecz** [comment]
Hm, maybe rendering like `shop=car` would be acceptable to not encourage mistagging for caravan only shops?

**Comment by valhentai** [comment]
It could be the same icon as tourism=caravan_site but in the purple shop color.

**Comment by Fizzie41** [comment]
> with only 169 uses

> is tagged just 208 times

Not arguing, but wondering where you get those numbers, because when I look at it today, I get 333 uses https://taginfo.openstreetmap.org/tags/?key=shop&value=caravan#overview ?

Unless it was used 40 times in 3 days between your two posts, + another 125 in <5 weeks since, which I would think would make it important enough to render!

Thanks

Graeme

**Comment by Adamant36** [comment]
Taginfo isn't usually 100% up to date. Check out https://taghistory.raifer.tech and do a search for it. There was indeed a usage spike recently. I'm not its due to mass re-tagging of other things, as the increase is still, but its possible and one of the people that isn't support for the tag is known for doing that.

**Comment by valhentai** [comment]
I have been tagging the caravan shops in the north of France. That why the usage increased on TagInfo.

Most of the shop I added where not tagged at all or with just a name on a building. Just a few were already tagged as shop=car.

**Comment by jeisenbe** [comment]
Currently used only 448 times, an increase of 115 since April. 

I will close this issue for now, since usage is still too low to consider a specific icon. 

However, the issue can be easily reopened if usage rises to a higher level. Usually for shop icons this requires over 2000 uses, though this number may be reconsidered.

**Comment by meased** [comment]
Not that I disagree with this conclusion, but the low numbers of this tag are probably due to this being a highly mistagged feaure. I made an overpass turbo query to find `shop=car` combined with "RV" somewhere in the name. I can't run this query worldwide, but any random city I zoomed into in the US has several of them.

```
[out:json][timeout:25];
// gather results
(
  // query part for: “shop=car and name="*RV*"”
  node["shop"="car"]["name"~"RV",i]({{bbox}});
  way["shop"="car"]["name"~"RV",i]({{bbox}});
  relation["shop"="car"]["name"~"RV",i]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Comment by Adamant36** [comment]
@meased, if you want a worldwide tag count you can do something like 

```
[out:csv(::count)][timeout:250];

nwr["shop"="car"]["name"~"RV",i];
  
out count;
```
It never loaded for me for some reason, but maybe you can get it to.

**Comment by jeisenbe** [comment]
Thank you, @meased. This suggests it should not take too long to achieve higher numbers of `shop=caravan` with some mapping work. They will still render with a dot icon and name for now.

**Comment by boothym** [comment]
@meased if you add **global** to the end of your query in the wizard it searches worldwide (might need to increase the timeout limit though). There are 158 total, but about 20 of them outside the USA are not related to RVs.

I've retagged the 14 shop=car features containing the name "Caravan" in the UK. In the rest of Europe there's at least 70 more, plus those tagged as shop=motorhome.

@jeisenbe Surely it's not too low to consider a specific icon - it should just be the caravan site icon but in pink - the question is if it's too low to implement the icon 😉
