### ISSUE TITLE
China's name never shows up

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3725]
Starting at e.g.,
https://www.openstreetmap.org/#map=3/34.05/93.16
no matter how you zoom in or out, China's name never shows up!

**Comment by sommerluk** [comment]
[China](https://www.openstreetmap.org/relation/270056#map=4/35.21/104.41)'s name currently actually [shows up](https://www.openstreetmap.org/?mlat=33.03&mlon=109.25#map=4/33.03/109.25) correctly at z4:

![Screenshot_20190323_060610](https://user-images.githubusercontent.com/6830724/54862386-473af980-4d3a-11e9-9f94-2c8be0c4f96f.png)

It correctly disappears at z5.

It does however not show up at z3 though it should (given the country's size).

So the only issue here is at z3.

**Comment by jidanni** [comment]
I clicked your [shows up](https://www.openstreetmap.org/?mlat=33.03&mlon=109.25#map=4/33.03/109.25) link. Alas:
![3](https://user-images.githubusercontent.com/1230959/54862482-8ab35900-4d76-11e9-8fa8-4a46f1e6d605.jpg)

**Comment by sommerluk** [comment]
Okay, seems to be a tile cache issue. The China relation has been modified recently. So this is likely a data issue. Closing.

**Comment by jidanni** [comment]
Can you please not close the bug until the issue is actually resolved.
If the problem is as you say it is, then you won't need to wait long.
Please close the bug only after 中囯 appears at both level 3 and 4.
Thank you.

**Comment by matkoniecz** [comment]
The issue you've identified looks like a tagging issue and not something wrong with the renderer.

Also, note that even for issues with a style there may be a gap between fix bug and updating rendered map - one needs to wait for a release, later for deployment on OSM servers and rerender of the map.

Given that issue is at zoom level 3 tiles will be updated once new version will be released.

Hopefully China relation will not broken during rerendering.

If you want I may give an explanation how one may use JOSM to load "only" China borders and check is it passing tests.

**Comment by jidanni** [comment]
OK. Just hope some vandal isn't laughing that he knocked the world's most populous county's name off the map for weeks...

**Comment by jeisenbe** [comment]
Unfortunately this repository does not determine the schedule for
rendering-rendering the low zoom levels.

Perhaps you can request that the OSM.org website rendering these zoom
levels more frequently, so that mistakes do not last as long.

The relevant issue is https://github.com/openstreetmap/chef/issues/184
