### ISSUE TITLE
Add rendering for golf=cartpath

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#3734]
Since openstreetmap/iD#5862, iD has had a preset “Golf Cartpath” for paths in golf courses that are intended for pedestrians and golf carts. This preset adds the [`golf=cartpath`](https://taginfo.openstreetmap.org/tags/golf=cartpath) and `golf_cart=designated` tags but no `highway` or `footway` tag ([example](https://www.openstreetmap.org/way/680409020)). These paths aren’t rendered by openstreetmap-carto:

[![indian-ridge](https://user-images.githubusercontent.com/1231218/55261819-276b7000-5229-11e9-8519-baf808aaf6ec.png)](https://www.openstreetmap.org/way/680409020#map=17/39.46092/-84.68949)

`highway=path` is another common way to tag these paths that is rendered.

/ref #661 #3675
/cc @chadrockey @bhousel

**Comment by matkoniecz** [comment]
Can you link to any documentation/description of what is the meaning of this tag? Especially, how it it differs from `highway=path`/`highway=footway`?

See https://taginfo.openstreetmap.org/tags/golf=cartpath and https://wiki.openstreetmap.org/wiki/Item:Q17294 (both automatically generated with no explanation what this tag means and why it is used).

**Comment by chadrockey** [comment]
The rationale is explained in this post:
https://github.com/openstreetmap/iD/pull/5862#issuecomment-460771112

The golf:cartpath and golf:paths don't connect into the main routing network and can exist as disconnected segments.  They aren't useful for computing navigation or directions and so can't be marked as highways or errors are generated when they don't connect.

**Comment by imagico** [comment]
Seems there is a concerted effort to push this tag against more common `highway=*` + `golf_cart=*`.

See:

https://github.com/gravitystorm/openstreetmap-carto/issues/3650#issuecomment-460465213
https://wiki.openstreetmap.org/wiki/Key:golf_cart
https://taginfo.openstreetmap.org/keys/golf_cart

Tagging discussion, in particular for organized _tagging for the router_ appeals :wink:, should go to the tagging mailing list.

I would in principle be open to dedicated rendering of golf cart paths - if we decide to render golf course features in general (which we haven't so far and which depends on a database reload).

**Comment by matkoniecz** [comment]
> The highway=* tags carry the assumption that they should always connect back to the main routable road network somehow

Is it actually general assumption or is it some assumption internal to iD? I am still unsure why https://github.com/openstreetmap/iD/pull/5862/commits/25cc522333b4025149010ba98c600a457b55987a was made - is it inventing a new tagging scheme as workaround for limitations of iD validator?

**Comment by matthijsmelissen** [comment]
> The golf:cartpath and golf:paths don't connect into the main routing network and can exist as disconnected segments. They aren't useful for computing navigation or directions

I don't think any of these are good reasons they cannot be tagged as highway.

**Comment by Adamant36** [comment]
"The golf:cartpath and golf:paths don't connect into the main routing network and can exist as disconnected segments. They aren't useful for computing navigation or directions and so can't be marked as highways or errors are generated when they don't connect." 

Shouldn't they just be tagged as highway= then and set to either private or permissive? From my understanding people that live in planned suburb areas around golf courses still ride their carts around the paths. A bunch of planned communities in Arizona that have cart paths minus the golf courses also that are used permissively by anyone in the area with a golf cart. 

Id take this up with iD editor.

**Comment by jeisenbe** [comment]
It looks like most of these features were added by imports in 2015:
![taghistory-4](https://user-images.githubusercontent.com/42757252/55779223-d9375600-5adf-11e9-9785-ebb2a5cb347e.png)

At the time this tag was undocumented. It was only added to the wiki in September 2018: https://wiki.openstreetmap.org/w/index.php?title=Key:golf&diff=prev&oldid=1835154
And the individual tag page was created 7-April 2019: https://wiki.openstreetmap.org/w/index.php?title=Tag:golf%3Dcartpath&oldid=1835163

I haven't found any discussion of the meaning for this tag except in the [ID preset PR comments](https://github.com/openstreetmap/iD/pull/5862#issuecomment-460771112) that were linked above. 

I'm surprised that ID decided to add golf=cartpath and golf=path as presets.

**Comment by matkoniecz** [comment]
> At the time this tag was undocumented. It was only added to the wiki in September 2018: wiki.openstreetmap.org/w/index.php?title=Key:golf&diff=prev&oldid=1835154

For now I added in Wiki note that standard tags for paths and service roads are likely to be preferable.

**Comment by polarbearing** [comment]
> and so can't be marked as highways or errors are generated when they don't connect.

If I pave some part of the world for the purpose of walking or driving any kind of vehicle on it, it deserves a highway tag. Connected or not. Any other descriptive subtag can be added of course. If any Q/A-tool flags that as an error, the tool should be fixed or the error ignored. 

It seems to me the majority here supports this position, so the issue can be closed.

**Comment by imagico** [comment]
This is not a matter of majority opinion but i am closing this none the less due to

* lack of support for the tag among mappers.
* lack of consistent use of the tag (it currently seems to purely indicate this is some kind of path on or around a golf course mapped by an iD user - but nothing specific as to physical or functional characteristics of it).
* lack of documentation indicating what the tag is supposed to indicate other than some kind of path on a golf course and how it relates to established tags for various types of path.
* the desire not to support meaningless tagging proliferation (see also [xkcd](https://xkcd.com/927/)).
* this style currently not rendering any golf course features and unless we do it would not make sense to render golf course paths specifically either.

**Comment by matkoniecz** [comment]
As far as I can see this tag is not indicating feature different from `highway=path` or `highway=footway` or `highway=service`.

Maybe I am mistaken, in this case I would encourage people using and promoting this tag to document it properly.

And as far as I can see claim that

> The highway=* tags carry the assumption that they should always connect back to the main routable road network somehow

and that it is OK to map `golf=*` paths with the same meaning is inherent to an iD validator.

**Comment by bhousel** [comment]
> > and so can't be marked as highways or errors are generated when they don't connect.
> 
> If I pave some part of the world for the purpose of walking or driving any kind of vehicle on it, it deserves a highway tag. Connected or not. Any other descriptive subtag can be added of course. If any Q/A-tool flags that as an error, the tool should be fixed or the error ignored.

Literally every Q/A tool out there will interpret this as an error.  KeepRight, Osmose, and the JOSM validator will warn about paths that are not connected to anything.  Also afaik every routing software will potentially try to snap to highways and get stuck on these.  This is the reason I was ok with accepting @chadrockey's PR to iD.  These paths really are not like other highways.

**Comment by imagico** [comment]
@bhousel - whatever mental image you have of _these paths_ - the iD users are not using the preset according to it.  They are using it indiscriminately for all kinds of paths and service roads on golf courses - most of them naturally being connected to other roads.  So the de facto meaning of `golf=cartpath` + `golf_cart=designated` at the moment is, as said, _some kind of path on or around a golf course mapped by an iD user - but nothing specific as to physical or functional characteristics of it_.

I don't play golf so i am not in a position to say there is for sure no basis for creating distinct tags for certain types of paths on golf courses.  But it has to be documented what these mean, when exactly to use them instead or in addition to standard tags for paths elsewhere, this meaning of the tags has to be verifiable and the tag needs to actually be used according to this meaning.  Otherwise it should not be used and it definitely should not be rendered in this style.

**Comment by polarbearing** [comment]
Thanks for the hint, I fixed my "majority" count in favour of strong arguments.

**Comment by jeisenbe** [comment]
> every Q/A tool out there will interpret this as an error. KeepRight, Osmose, and the JOSM validator will warn about paths that are not connected to anything.

I don't think this is an isolated problem for golf cart paths. 

It's quite common for footpaths and small roads to be isolated in the real world. Where I live, in Indonesia, many villages on the coast are surrounded by mangroves, and are only accessible by boat, so there is just one path connecting the houses in the village, and other travel is by boat. This is also common on small islands around the world. 

I also know of paths in universities and hospitals that are only accessible by passing through a building.

In contrast, all of the golf courses that I know in California and Arizona have clear paths between their golf cart paths and the main street or road network. In Phoenix it's common to drive right from your house to the golf course via golf cart.

**Comment by bhousel** [comment]
Ok.. _I don't really care much about which tag is used_. @chadrockey wanted to map cartpaths.  You told them to get their tag accepted first, so they wrote up documentation for it, sent me a PR, I looked through it, and I accepted it.

I am sorry for the problems that this decision caused for osm-carto project, so I will just switch the iD presets to use `highway=*` tags (this was my original suggestion anyway).  The validator issues are really no big deal for iD.  I was thinking more of KeepRight, which is receiving limited maintenance these days.  I'll even help retag the existing data.

Finally..  😓 

Many of you, but @imagico in particular, are _exhausting_.  I don't think you realize how much you are hurting the OpenStreetMap project just by how rudely you treat people who just want to improve the map.  

Also.. There was a wiki page for `golf=cartpath` and @matkoniecz and @jeisenbe removed it.  _It is really hard to take the wiki seriously._  I know that [Weekly OSM](http://weeklyosm.eu/archives/11846) thought it was funny to selectively quote me saying that I disregard the wiki.  I mean yeah, of course I'm going to disregard it if I'm watching you edit it while we discuss the thing.  What a joke!

For you guys to say "stop using an undocumented tag" while quietly [deleting the documentaion](https://wiki.openstreetmap.org/w/index.php?title=Tag:golf%3Dcartpath&action=history) for the tag is... really really disappointing. This was done, today. 

It now points to [this page](https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:golf%3Dcartpath) also written today by @jeisenbe which basically just says not to use the tag.  Some proposal!

My feelings for OSM have changed a lot in the past year.  I stepped down from the board of directors for OSM-US and I won't be attending nearly as many events this year.  It is very hard for me to continue to take this project seriously.  I don't enjoy spending my free time this way anymore.

**Comment by jeisenbe** [comment]
> There was a wiki page for golf=cartpath and @matkoniecz and @jeisenbe removed it

It was me (@jeisenbe) not @matkoniecz. 

The wiki page for golf=cartpath was made just 3 days ago, 7-April-2019, and I redirected the page to a proposal today, 10-April-2019 (Well, that's the date here in Indonesia, I suppose the wiki dates are in UTC?)

The page was not removed, but moved to [Proposed_features/Tag:golf=cartpath](http://wiki.openstreetmap.org/wiki/Proposed_features/Tag:golf=cartpath) - there is a redirect now. All of the previous documentation is there, though I added some additional comments suggesting that highway=path or highway=service could also be used, in addition to some comments that @matkoniecz added.

>  while quietly deleting the documention...

I made an official proposal page for [Key:golf_cart](http://wiki.openstreetmap.org/wiki/Proposed_features/Key:golf_cart) in addition to the existing [Key:golf_cart page](https://wiki.openstreetmap.org/wiki/Key:golf_cart)

And I submitted a RFC to the Tagging mailing list requesting discussion about which of these two tagging methods is best, so I think it is unfair to say this was done quietly. I did forget to write a comment on the Discussion page, so I'll add that now. 

I this this was the recommended way to propose and discuss new features, rather than creating a full wiki page without discussing it.

Normally I would not have considered redirecting a wiki page to a proposal, but since the page was only [3 days old](https://wiki.openstreetmap.org/w/index.php?title=Tag:golf%3Dcartpath&action=history), I felt it was reasonable in this situation. 

But if I've done wrong, I can undo the edit, or of course anyone else can edit the wiki.

**Comment by jeisenbe** [comment]
> Many of you, but @imagico in particular, are exhausting. I don't think you realize how much you are hurting the OpenStreetMap project just by how rudely you treat people who just want to improve the map.

As an American living in Indonesia, I've had plenty of experience of being considered extremely rude. This is sometimes because I am rude by American standards, but mainly due to the communication style differences. Indonesians, especially Javanese people, do not confront someone or speak directly about issues. Everything must be done in a very subtle way. Often Americans (and my Dutch and German friends) fail to understand when they are doing something wrong, because they expect to be told more directly. 

Javanese people think that only children and fools say something directly when it can read between the lines. 

I've also seen the other side of this. My expat friends from Germany and the Netherlands are much more direct and frank. Often they offend me and my American friends by saying directly: "that's a bad idea", "this work is unacceptable, do it again", etc.. But apparently this is a completely normal way of speaking in their culture. 

German people think that only children and fools are ashamed to say exactly what they mean. 

(*These are stereotypical exaggerations for rhetorical emphasis. Not all Indonesians, Germans and Americans have the same communication style.)

As contributors to an international project, we call all try harder to understand one another. 

A good first step is to always **assume good will**. This is very hard; as humans we naturally assume that when we feel hurt or confused, it's because the other person intended to hurt us and confuse us.

Some examples of not assuming good will: 

"**Seems** there is a concerted effort to **push** this tag against more common highway=* + golf_cart=*" ("seems" and "push" emphasized) 
- this is making assumptions about the intentions of other people.

- Myself (@jeisenbe): 
I wrongly assumed that @bhousel would not be willing to consider changing the presets unless the wiki was changed first and there was a clear proposal in favor, so I started working on all of that rather than just asking politely. 

Now I see that I was wrong, it would have been much easier to just ask to change the preset before changing the wiki. And changing the wiki made it appear that I had bad intentions. 

It's very difficult to get this right on the internet, with no face-to-face interaction. 

Please accept my apology for jumping to conclusions and not waiting for advice and consensus.

**Comment by imagico** [comment]
Ok, first of all i am positively surprised by @bhousel reconsidering the decision in the iD presets (and it is not easy to surprise me this way).

I have been accused of being rude and wanted to add a few comments on that matter.  @jeisenbe already explained how rudeness and friendliness are to a significant extent a matter of cultural differences, even in relatively cosmopolitic societies like in Europe and the US.  I also feel @bhousel is being rude in many cases in his reactions to commenters on the iD issue tracker.  But i try to form my opinion based on decisions made and not from the way they are communicated.  The advise to always assume good will is a very good one.  Explicitly communicating you respect others disagreeing with you is another good strategy that can help bridging cultural gaps.

I apologize for here in my initial comment focusing on perceived motivation (which considering the decision is now being revised is now also proven to be wrong - but it would have been wrong to put that in the foreground even if my perception had been correct).

In overall analysis i think the ultimate cause of the problem has been to a significant extent a failure in communication.  When @chadrockey brought up golf cart paths on this issue tracker there seemed to have been agreement that the best way for this is using normal highway tags with supplemental tags as needed - i already liked to this discussion above: https://github.com/gravitystorm/openstreetmap-carto/issues/3650#issuecomment-460465213 with @chadrockey agreeing (https://github.com/gravitystorm/openstreetmap-carto/issues/3650#issuecomment-460497200) this seemed to be settled.  But the same subject was then discussed again on the iD issue tracker (https://github.com/openstreetmap/iD/pull/5862) with a different outcome.

The traditional way to avoid this kind of problems (with different parts of the OSM community developing different conflicting tagging ideas) is the tagging proposal process with wiki and mailing list.  Yes, this is often unnecessarily elaborate and exhausting and frequently fails to yield useful results.  But just foregoing the process does lead to the kind of problem we had here.  This is somewhat out of scope here on the OSM-Carto issue tracker but i think this demonstrates that for developing editor presets some kind of RFC process on preset decisions that gives those from the OSM community who have something significant to say on the subject a well defined opportunity to do so is important.  Avoiding at the same time the cacophony of special interests and unqualified opinions is of course the tricky thing.

**Comment by matkoniecz** [comment]
> I thought it was recommend to propose and discuss new features, rather than creating a full wiki page without discussion

I replied at https://wiki.openstreetmap.org/wiki/Talk:Tag:golf%3Dcartpath#redirecting_pages_to_a_proposal (as I would prefer to not start an offtopic here)

**Comment by matkoniecz** [comment]
Both

> I don't think you realize how much you are hurting the OpenStreetMap project just by how rudely you treat people who just want to improve the map.

and

> is being rude in many cases in his reactions to commenters on

sadly reminds me about "The life cycle of contributors in collaborative online communities - the case of OpenStreetMap" article ( https://www.tandfonline.com/doi/full/10.1080/13658816.2018.1458312 )

> The hazard curve (Figure 3(b)) shows a bathtub shape typical of the stages in the life cycle of complex systems. (...) contributors potentially switch from a learning-adaptation to a cumulative-damage dominated behaviour (Bégin et al. 2017b). This switch seems to occur after years of irritation and annoyance start affecting participants’ motivation to keep contributing, which leads to the ‘detachment’ phase. The boundary between ‘engagement’ and ‘detachment’ stages fits the location of the next CCDF inflection point (6 years). Finally, the ‘detachment’ stage contains the last CCDF inflection point (9 years), a point after which most long-term contributors quit the project.

![Selection_006](https://user-images.githubusercontent.com/899988/57179328-18f22300-6e7d-11e9-8527-bff5863c52ae.png)

I am not sure how to reduce this problem beyond 

> A good first step is to always assume good will. This is very hard; as humans we naturally assume that when we feel hurt or confused, it's because the other person intended to hurt us and confuse us.

and standard "remember that other contributors are actually a living humans, not pixels in your monitor" or "do not comment/post/commit when angry"

It is a combination of people actually attempting to improve situation (but sometimes with bad ideas or good ideas that for some reason failed). Miscommunications happen. Add to it competing interests, pride and small dose of malicious actions (pretty sure that the last one is rarer than most people would expect) and we end with sometimes highly flustrating situation.

**Comment by Adamant36** [comment]
@matkoniecz, thanks for info and the link. Even if it is slightly off topic. 

Its definitely something I've been I've been struggling with lately myself. As is probably obvious to some people. I'm know were near being here 9 years though or as invested in the project as you guys are. 

A general comment, while I agree that this is as much just about the nature of contributing to an open source project and how people naturally peter out on them over time etc, there's still a large component of it that has to do with other contributors, their responses to things, and how understanding of other people they are in certain situations. 

I know from my own experiences without calling certain people out, that is a general mood of paranoia as to other peoples intentions that underlines a lot of interactions. There's a strong inclunation toward people who think they have more time or experience in the project discounting anything from people who don't. Which often makes doing even basic things much harder then it should be.

I don't think just chalking those antagonisms up to cultural differences in communcation styles or saying "well, your problems clearly just do to the natural cycle something goes through as a contributor" is   
necessarily the best way to deal with them. Even those things are true, the other stuff should also be kept in check and they aren't. 

I've noticed a strong inclination to ascribe bad behavior in others and call them out for it when its convient, but then not doing it when its that persons own behavior or the behavior of someone else higher up in the project. For instance shotting down other peoples opinions as campaigning, but then when that person is called out for doing the same its "not assuming good will" by whoever is doing it. 

Or, allowing certain users to get wrung over the coals for two years straight in various mediums at every chance for what was a newbie mistake at the time, which they have tried to remedy since then, without anyone being called out for it. Whereas, if said person says something slightly sarcastic like calling one of the people who did the coal racking a troll they immediately get called out and warned about their behavior. 

Ultimately, its not balanced and things like "natural factors" and communications differences get most of the air time. Whereas other, more individual, things often get discounted when they probably shouldn't be. Whatever it is about communication style differences, its still on individual people to act better and be more understanding when they can. I come a pretty rough, lax place in California. Most the people here have no concept of verbal restraint. Its been an extremely hard thing for me to tone it down and be more measured when participating in this project, but how I behave is ultimately on me. Know matter how laissez faire my culture may be about things. I havn't wanted or gotten any special allowences for it either. Nor have used it to handwave away my sometimes bad behavior. Neither should others. 

I'm not saying there isn't differences how we communicate. I just think those differences are not the sole or top cause of problems in this project.

**Comment by kocio-pl** [comment]
> sadly reminds me about "The life cycle of contributors in collaborative online communities - the case of OpenStreetMap" article 

I see nothing really sad in the process of people coming to and leaving the projects. The article suggests that it's quite universal law (probably similar to the "long tail" distribution pattern). In the active project all that matters is to have some balance between some people leaving (or just getting much less active) and some other joining and taking over. In the case of OSM Carto I see that we loose this balance and #2291 is not really solved.

> There's a strong inclination toward people who think they have more time or experience in the project discounting anything from people who don't.

While I believe it's a crucial problem for the project health, I think there are more of them and they are not limited to discounting less experienced participants. In general it's sparse communication, I guess, and I see too few examples of cooperation. Yet I'm not sure why is that happening and what to do with it.
