### ISSUE TITLE
Adding specific rendering for the new office=diplomatic (new tag for embassies and consulate)

### ISSUE THREAD

**Issue by lgiard** [gravitystorm/openstreetmap-carto#3737]
Hello, 

Since the **new method of tagging embassies and consulate** ([with office=diplomatic](https://wiki.openstreetmap.org/wiki/Tag:office=diplomatic)) has been approved end of last year ([look at the accepted proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/office%3Ddiplomatic)), it should be useful to support the rendering for the new tagging scheme. The old tag "amenity=embassy" is now in the process of [being deprecated](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dembassy). 

I would say that using the **same icon than "amenity=embassy"** should be enough :
-> ![embassy_logo](https://wiki.openstreetmap.org/w/images/3/36/Embassy-16.svg)

Because I don't think it is absolutely needed to visually differentiate between embassy, consulate and liaison (the three sub-category of this new tagging scheme via the sub-tag _diplomatic=*_). It is generally described in the name anyways.  

Concerning the old tag "amenity=embassy", I don't know if we generally keep the rendering of the "deprecated tag" (like during a transition phase) or remove it directly from rendering ?

**Comment by imagico** [comment]
Thanks for pointing this out.

In general proposal votes and deprecating of tags in them has no direct effect on our decisions here.  The numbers for the tags in question are quite clear, there are 12k features with `amenity=embassy`, 600 with `office=diplomatic` and 5.2k with `diplomatic=*`.  Should this change significantly we could reconsider this.

Also on a general note we do not typically render several different tags for indicating the same type of feature because this would perpetuate the use of both tags (a.k.a. tagging proliferation) rather than supporting a specific consistent tagging.  If it is clear that mappers are adopting a new tagging in favor of an existing one we'd move by removing the old one and at the same time adding the new one.

**Comment by matkoniecz** [comment]
I think that for now we should wait whatever the new scheme will be adopted by mappers. Not that `office=diplomatic` is rendered.

I would suggest to ask for support in editors first (if it is not supported and not rejected). Note also there are validators - standalone and built-in within JOSM and iD.

If there is consensus among mappers to promote `office=diplomatic` then maybe validators can suggest mappers to use this tag in addition/instead of `amenity=embassy` (or reverse, suggest to add/replace with ` amenity=embassy` if there is no consensus that new tag makes sense).

PS Please check whatever feature is already/present requested before creating issues at https://github.com/openstreetmap/iD/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc https://josm.openstreetmap.de/query?status=assigned&status=needinfo&status=new&status=reopened&col=id&col=summary&col=status&col=type&col=priority&col=milestone&col=component&col=time&order=priority&report=1

PPS I just noticed https://github.com/openstreetmap/iD/issues/6144 (validator suggestion is not explicitly mentioned, but it is probably implied).

**Comment by matkoniecz** [comment]
Please comment once: iD, JOSM and Vespucci support `office=diplomatic` over `amenity=embassy` or once `office=diplomatic` is more popular than `amenity=embassy` (and it is not a result of something violating https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct )

**Comment by Discostu36** [comment]
Current situation:

iD, Vespucci and JOSM now use `office=diplomatic` with `diplomatic=embassy` when adding an embassy. JOSM still uses `amenity=embassy`.

**Comment by jeisenbe** [comment]
The page for Key:diplomatic needs to be updated with the approved tags too:
https://wiki.openstreetmap.org/wiki/Key:diplomatic

**Comment by jeisenbe** [comment]
The page for Key:diplomatic needs to be updated with the approved tags too:
https://wiki.openstreetmap.org/wiki/Key:diplomatic

**Comment by jeisenbe** [comment]
Reopening as under discussion

**Comment by jeisenbe** [comment]
My error, we addressed this in #3886 instead, and closed it with PR #4168
