### ISSUE TITLE
Stop rendering barrier=embankment

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3744]
### Barrier=embankment vs man_made=embankment

I researched the values of barrier in taginfo to see if there were any that we could start or stop rendering. I found that barrier=embankment was not documented on the wiki.  

It turns out that most features with this tag were imported into the database in 2011, before man_made=embankment was an established tag. A few more were imported in 2013. As of April 2019, barrier=embankment is used 4750 times, less than the usage in 2013.

A better documented and supported tags this feature is man_made=embankment. This tag is well documented on the wiki and also rendered with a more specific style, and man_made=embankment has been used over 80,000 times.

The comparison graph of usage speaks loudest:
![embankment-man_made-vs-barrier](https://user-images.githubusercontent.com/42757252/56005425-22b7b900-5d0b-11e9-9ef4-fc11913cb797.png)

**Comment by matkoniecz** [comment]
I went to wiki to document it, but I see that https://wiki.openstreetmap.org/w/index.php?title=Tag:barrier%3Dembankment&action=history was created :)

**Comment by matkoniecz** [comment]
I opened https://josm.openstreetmap.de/ticket/17643#ticket

**Comment by jeisenbe** [comment]
Any objections to removing the rendering of barrier=embankment? 
This tag is now listed as deprecated in the wiki, and there is an open ticket to suggest changing the tagging when validating data with JOSM.
(Perhaps someone who know how iD works could propose a validation rule for that editor)?

**Comment by imagico** [comment]
I agree we should drop this.

Looking at the data by far the largest block of uses of this is a set of features mapped by Andrew Buck eight years ago in Egypt and Libya.  You could contact him and ask him if he wants to revisit those edits and choose a different tagging.

Note however we currently don't have a real established tag for a double/symmetric embankment not connected to some other primary feature like a road and not with a specific function like a dyke - something we in German call a 'Wall'.  Some tag this `embankment=yes` without other tags, some tag it `man_made=embankment` + `embankment=two_sided` or `embankment=both`.  So comparing numbers for `man_made=embankment` and `barrier=embankment` is somewhat misleading since they don't necessarily mean the same.

**Comment by jeisenbe** [comment]
> double/symmetric embankment not connected to some other primary feature like a road... something we in German call a 'Wall'

We have that word in English too. :-)

It could be translated "rampart" - "a large wall built round a town,
castle, etc. to protect it"?

Or "earthwork": "a raised area of earth made, especially in the past,
for defence against enemy attack"

If it's a type of fortification, it wouldn't be called an embankment
in English if it is equally steep on both sides:
Embankment: "an artificial slope made of earth and/or stones"
https://dictionary.cambridge.org/dictionary/english/embankment

**Comment by jeisenbe** [comment]
I've contacted [Andrew Buck](https://www.openstreetmap.org/user/AndrewBuck) about the planned change.

**Comment by polarbearing** [comment]
The function of an embankment is not to be a barrier, thus I agree with the removal.
