### ISSUE TITLE
Render citywalls thinner

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3747]
Currently citywalls are way too bold in comparsion with simple walls (in some places they could be even confused with some kind of power lines). Example places which shows the problem:

https://www.openstreetmap.org//#map=19/52.40885/16.93095
https://www.openstreetmap.org//#map=19/52.40556/16.93329
https://www.openstreetmap.org//#map=18/52.24915/21.01100

related to #3745

**Comment by mboeringa** [comment]
I don't agree, these are significant features compared to most "ordinary" walls. And actually, if I recall well, these features were already made thinner in the past. I also don't see how these could be confused with power lines, their location and form is very much distinct in most cases.

**Comment by imagico** [comment]
Line width of citywalls jumps from 1.5 to 3 pixels from z16 to z17 - which might sense to smooth out.

Apart from that a thorough analysis of actual use of both tags rendered (`historic=citywalls` and `barrier=city_wall`) would be good as a basis for discussing changes to rendering.

**Comment by jeisenbe** [comment]
@Tomasz-W see #3847

**Comment by jeisenbe** [comment]
I checked out the citywall rendering and adjusted it in #3847. 

Previously citywalls started at 1.5 pixels at z15 and then jumped to 3 pixels wide at z17.

Now citywall width is adjusted to start at 1.0 pixel wide at z15, increasing to 1.5 at z16, 2.0 at z17, 3.0 at z18, 4.0 at z19 and 5.0 at z20, and `barrier=hedge` matches this transition. 

At the equator, this is 0.75m wide at z20, 1.2m at z19, and 1.8m at z18 (same). This appears reasonable, and in comparison it's 30 to 60% thinner than`minor-service` highways (like driveways and parking_aisles) at each zoom level.

So they are now thinner than before at z15 and z17 (though they are wider at the highest zoom level, z19). I believe this issue is resolved.
