### ISSUE TITLE
Blue background only at specific zoom

### ISSUE THREAD

**Issue by mds08011** [gravitystorm/openstreetmap-carto#3768]
I have come across an area where an odd blue background is only shown at zoom level 17.  The same area does not look blue at z16 or z18...only z17.  I have tried to inspect the OSM data but have no idea what the bounding feature is if any.

### Links and screenshots illustrating the problem
Link to Map: https://www.openstreetmap.org/#map=17/32.82431/-117.12827

![Carto_Example](https://user-images.githubusercontent.com/8010709/56867489-a7a50280-699a-11e9-9ffa-7b115463cf4b.png)

**Comment by imagico** [comment]
This is a frequent occurrence due to different tiles being rendered at different times with different data state.  You can check the individual tiles:

https://a.tile.openstreetmap.org/17/22890/52871.png
https://a.tile.openstreetmap.org/17/22890/52872.png

https://a.tile.openstreetmap.org/17/22890/52871.png/status
https://a.tile.openstreetmap.org/17/22890/52872.png/status

If (and only if) the phenomenon occurs at different zoom levels with tiles rendered at different times (which does not seem to be the case here - i don't get any blue tiles at all) it makes sense to look for the data object that is causing the blue fill.

And that would be nothing for this issue tracker - it has nothing to do with the style but with the data.

**Comment by mds08011** [comment]
Makes sense.  Thanks for the explanation!
