### ISSUE TITLE
Feature Request: add OSMC Symbols to route relations

### ISSUE THREAD

**Issue by kolgza** [gravitystorm/openstreetmap-carto#3792]
[OSMC Symbols](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) allow way-markers to be saved in a machine readable format. These is extremely useful for hiking and mountain biking. If Carto supported them, then it would drive their adoption.

**Comment by matkoniecz** [comment]
> If Carto supported them

openstreetmap-carto is style used to generate human-readable image from OSM data. I am unsure how support of them would look like.

OSM data itself is already machine-readable (and generally human-readable).

> OSMC Symbols

It seems to be link to page describing something unrelated ("alternate routes which did not lead into the congested Golden Triangle")

**Comment by mboeringa** [comment]
> It seems to be link to page describing something unrelated ("alternate routes which did not lead into the congested Golden Triangle")

It likely should have referred to pages like these:
https://wiki.openstreetmap.org/wiki/Key:osmc:symbol
https://www.wanderreitkarte.de/symbols_en.html

**Comment by matkoniecz** [comment]
I am pretty sure that there is no enough space to display trails in addition to other data. Even waymarkedtrails.org is not doing this and they have multiple separate views.

**Comment by kolgza** [comment]
I think it's important for Carto to at-least support the symbols, but not necessarily highlight the routes.

**Comment by pkoby** [comment]
This is similar to displaying highway route shields, but probably on a smaller scale. I wouldn't display these beyond a certain high zoom level (z17?). I do like the idea of adding them in, though.

**Comment by Adamant36** [comment]
There was an issue here somewhere a while back about rendering America specific highway route shields, but it was roundly rejected as to detailed for a detailed map. Unfortunately, I can't remember where it was now. This might  fall under that since it's not universally used. Although, personally I think support for both would be cool and maybe encourage more mappers in America.

**Comment by jeisenbe** [comment]
This key `osmc:symbol` is used 82,000 times on relations, presumably of `type=route` as recommended on the wiki page. https://wiki.openstreetmap.org/wiki/Key:osmc:symbol

Unfortunately, we probably can't currently render reference numbers or symbols that are properly tagged on route relations, because the tool that we use to import data for rendering, osm2pgsql, does not handle these relations in a useful way. I believe this would prevent us from rendering these symbols at this time.

See this issue for more details: #596 
And this closed PR: ##3663
Issue about extending osm2pgsql: https://github.com/openstreetmap/osm2pgsql/issues/230

**Comment by pnorman** [comment]
> There was an issue here somewhere a while back about rendering America specific highway route shields, but it was roundly rejected as to detailed for a detailed map.

No, #508 is open, but depends on the #596 which is difficult or impossible with current architecture.

> [OSMC Symbols](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) allow way-markers to be saved in a machine readable format. These is extremely useful for hiking and mountain biking. If Carto supported them, then it would drive their adoption.

Do you have any examples of them being parsed in Lua or in SQL + CartoCSS?

**Comment by pnorman** [comment]
> Unfortunately, we probably can't currently render reference numbers or symbols that are properly tagged on route relations

We'd have no problems here because there's no duplication with on-way data.
