### ISSUE TITLE
Drop railway=rail service=yard/spur/siding from z13

### ISSUE THREAD

**Issue by Prince-Kassad** [gravitystorm/openstreetmap-carto#3801]
With buildings having been dropped from z13 in #3467, industrial areas look really funny now, because all the buildings are gone, but the railroads that would normally be drowned among all the buildings are suddenly super prominent on the map, way more prominent than their importance would suggest.

So if we are to keep not rendering buildings at z13, railway=rail service=yard/spur/siding should also be dropped from that zoom level.

**Comment by matkoniecz** [comment]
Can you give example of place where it is causing problems? Preferably not one that has mapped yard/spur/siding without mapped residential landuse.

I quickly looked at my city ( https://www.openstreetmap.org/#map=13/50.0597/19.9471  ) and it looks OK to me.

**Comment by Prince-Kassad** [comment]
For example, here: https://www.openstreetmap.org/#map=13/50.1359/8.9449&layers=N the large Dunlop factory mapped as landuse=industrial has nothing but a single railroad rendered on it, which makes the railroad extremely prominent, as if that were the most important feature of that factory.

The other industrial areas look similar bad but arguably not as bad as Dunlop.

**Comment by Adamant36** [comment]
Id totally be for this change. There's lots of cases where rendering might not be as obvious as @Prince-Kassad's example, but still looks weird due to multiple railway lines being crammed together at that zoom level since they are usually really close to each other. Plus, most industrial railroad yard rails aren't generally used as much as the main lines or other surrounding details are. So they are just a distraction and it would make sense to change rendering. 

For instance [here](https://www.openstreetmap.org/#map=13/40.7268/-122.3496) there's like 7 lines crammed together that look like one line and it's as prominent as the highway. Which it shouldn't be. Its sort of a distraction. 

[Here's](https://www.openstreetmap.org/#map=13/34.9075/-117.0783) an example where the rail lines are extremely crammed together to the point of not displaying anything useful (as a side, maybe it would be worth rendering landuse=railway slightly differently than normal industrial areas. So it would be easy to tell it's a railway yard without the rail lines). 

Also [here](https://www.openstreetmap.org/#map=13/35.3732/-119.0027) looks needlessly dense and distracting. 

Btw, it might be worth doing the same thing for railway=tram. As they can be to prominent or look weird at z13 or above also like [here](https://www.openstreetmap.org/#map=13/36.0972/-115.1997)

**Comment by matkoniecz** [comment]
> For example, here: openstreetmap.org/#map=13/50.1359/8.9449&layers=N the large Dunlop factory mapped as landuse=industrial has nothing but a single railroad rendered on it, which makes the railroad extremely prominent, as if that were the most important feature of that factory.

I admit that I see no problem here and it seems fine to me. 

Name and purple rendering of industrial area seems more prominent and rendering of railway why not too useful seems to not be terrible.

**Comment by Adamant36** [comment]
> rendering of railway why not too useful seems to not be terrible.

Yeah, I mean, to me it comes down to usefulness versus displaying it in the first place. Especially there is a general trend toward cutting down on map clutter. The argument could be made that displaying railway's in service yards are out of the range of what a general map should display. Know one, or most people, that use the map can or should go to those industrial areas. Service yards aren't usually landmarks either. Except in rare cases for graffiti artists maybe. So how is it any different then something like not displaying an icon for a tag that is to specific for the map? 

I'm not even suggesting they shouldn't be rendered, but rendering could at least be dropped down to a zoom level where people will actually be looking at the specific industrial area that contains the yard and the railway lines won't be as smashed together that way. As it is, at z13 your talking about the zoom level for looking at a large town or a couple of smaller ones. Keeping it there would be like rendering driveways at that zoom level. Which is ridiculous. 

Personally, I think starting rendering them at z14 instead would be better. That's when major power lines, houses, and other "in between" things start being rendered. Although, I still think that's pushing it and maybe starting at z15 or z16 would be better (I'm strongly leaning toward z16).

**Comment by Prince-Kassad** [comment]
z14 is when railway=level_crossing starts getting rendered, so we can't drop service rails further down until a change to that is made.

**Comment by Klaus-Tockloth** [comment]
Service railways on zl13 are a valuable information. Do not drop them from this zoomlevel.

**Comment by Adamant36** [comment]
"Service railways on zl13 are a valuable information.." 

Most of the time they can't even be accessed by 99%of the people viewing the map. If there's going to be a standard of usefulness to general map consumers applied to what's rendered in this style like there is for icons, I don't see why it shouldn't apply in this situation. It does with other types of ways also. To me its the same as not rendering abondend roads or similar things that are still visible but not useful to see on a map. Especially if map clutter is such a problem. Which it totally is where there's a bunch of them close together. Otherwise, what's so valuable about showing them?

**Comment by Klaus-Tockloth** [comment]
> Most of the time they can't even be accessed by 99%of the people viewing the map.
Isn't this a valuable info for 99% of the map users?

Many railway stations have large areas with service rails (screenshots on zl13).

https://www.openstreetmap.org/#map=13/53.4127/10.0650&layers=D
<img width="700" alt="Bildschirmfoto 2019-08-17 um 09 01 47" src="https://user-images.githubusercontent.com/5493128/63207851-b50f0580-c0cd-11e9-9381-0a750f52c512.png">

https://www.openstreetmap.org/#map=13/51.9512/7.6341&layers=D
<img width="400" alt="Bildschirmfoto 2019-08-17 um 09 03 10" src="https://user-images.githubusercontent.com/5493128/63207867-ea1b5800-c0cd-11e9-9849-70aea43f34b4.png">

**Comment by Adamant36** [comment]
"Many railway stations have large areas with service rails"

Obviously. Know on is debating that. The existance of something on the ground doesn't automatically make it worth rendering though. Note anyway that this is issue is about not rendering them at z13 anymore. Not removing rendering completely. Those are different things and know one has advocated their complete removal. 

That said, I think your example images, where you can't even tell the individual rail lines apart at that zoom just proves my point. It would be enough to know its a railway area at that point in my opinion. Buildings aren't even rendered at that level yet. Let alone major power lines, bridges, or other probably more important things. Id like to see someone make the arguement as to why they are higher in rendering priority then buildings. There's zero reason they couldn't start rendering at z14 or z15 where the individual tracks could at least be told apart. Instead of them looking like one big homogeneous grey area. Which they aren't in real life.

**Comment by jeisenbe** [comment]
`highway=track` is shown at z13, so I believe it's still appropriate to show minor railways at this level.

**Comment by pnorman** [comment]
Having experimented with not rendering service rails at z13, I believe we should still do it. In addition, looking at the other features that are present at z13, it makes sense to have them. Given that the maintainers who have commented are in favour of the status quo, I'm closing this issue.

**Comment by matkoniecz** [comment]
Thanks for making check whatever it will improve map!
