### ISSUE TITLE
Drop highway=steps from z13

### ISSUE THREAD

**Issue by Prince-Kassad** [gravitystorm/openstreetmap-carto#3808]
I think this was simply forgotten about when highway=footway was removed from z13 in #3467.

As is, highway=steps barely appear as more than a smudge of red pixels on that zoom level. See e. g. https://www.openstreetmap.org/#map=13/49.6363/7.8418&layers=N (which on that note still has a lot of staircases not mapped, it's been on my todo list for a good while...)

I can't think of a good usecase where you'd want to look at steps at z13, especially because they tend to be very short ways (the staircase in Rockenhausen is one of the longest in Germany period).

**Comment by kocio-pl** [comment]
Sounds sane for me.

**Comment by kocio-pl** [comment]
My testing environment is currently broken, but I guess if someone makes a PR, it has big chances to be merged by someone.

**Comment by imagico** [comment]
When taking the current status of z13 otherwise as a given removing steps would be an improvement.  But i like to point out that #3467 (and to some extent already #747) left z13 and the whole zoom level progression in a fairly inconsistent state with several contradicting design ideas being thrown together.  I have my doubts that in the long term  a z13 design and a zoom level progression with no footways (and accordingly no steps) at z13 makes a lot of sense.  #3467 did not really present a vision how this is supposed to work outside European urban settings and even there it has its problems.

So yes, removing the steps from z13 would be consequential in the current situation but it should not prejudice the long term strategy for z13 and around.

**Comment by LucFreitas** [comment]
![map](https://user-images.githubusercontent.com/19976610/59763319-b6f44e00-926f-11e9-807c-e0a3f717727b.png)
highway=steps in favelas (Vitória, Espírito Santo, Brasil) - z13

![2](https://user-images.githubusercontent.com/19976610/59763465-0aff3280-9270-11e9-874a-923bab339e6c.png)
highway=steps + covered=yes - z13 (black lines in image)

**Comment by Adamant36** [comment]
Id be willing to test it and probably also do a PR if I can figure out the highway code. I haven't done much if any work related to it unfortunately, but I'm willing to give a try as the steps at this level bug me also.
