### ISSUE TITLE
Make sure features are still queryable when user is told to zoom in first

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3809]
It doesn't matter what the reason is, just make sure you don't "play
bait and switch" with the user... especially as he has to mouseover the
"Zoom in to query features" button at each zoom level to see if it has
finally changed its name to "Query features".

On https://www.openstreetmap.org/#map=11/25.5688/-80.4893 user sees
plenty of airports.

User clicks the "Zoom in to query features" button... OK, he needs to
zoom in first before he can query "Redland Field".

Finally https://www.openstreetmap.org/#map=14/25.5448/-80.4574 the "Zoom
in to query features" button now is called "Query features", but alas,
it is just at this zoom level that "Redland Field" has disappeared from
the map!

Even if #2664 / #232 are resolved, it is just going to happen again for some
other feature.

All the user knows it he is told to zoom in to query, but then the thing
disappears, "like one big practical joke". He looks over his shoulder to
see if this isn't one more trick his office mate set up on his computer
like the last time he went for coffee break without locking the keyboard.

**Comment by jeisenbe** [comment]
I agree that this is a problem with airports. While the query feature
is a minor issue and isn't related to this style directly, it's true
that airport names and icons disappear from the map too soon. I'd like
to change this.

**Comment by Adamant36** [comment]
There's also #1143. Which has some good suggestions.

**Comment by jeisenbe** [comment]
@jidanni have you seen this problem with any features other than airports? If not, I believe it will be fixed by PR #3856

**Comment by jidanni** [comment]
@jeisenbe [here](https://www.facebook.com/groups/OpenStreetMap.TW/permalink/2482740028458118/) a big city is pushed off the map by little cities nearby, as apparently size, not population, is all that can be used to choose which to sacrifice. (As population has no place in the database.)

**Comment by jeisenbe** [comment]
Do you have a link that isn't through facebook, perhaps directly to the object on openstreetmap.org or the approximate location on the map? It would help to know the feature tag (`place=city`?) and `population`.

If I understand correctly, you don't like it that `place=city` labels disappear at a certain zoom level.

This is done so that `place=quarter` and `place=neighborhood` labels can be shown at zoom levels when the city is taking up the whole screen. Actually we use `population=` for this, but don't consider area, since only `place=` nodes are rendered for settlements including cities, towns and neighborhoods. If there is no `population=` tag, we guess that untagged towns are `population=1000` and untagged cities `population=100,000` (probably that should be dropped to 50k or 20k for cities).

Text labels for large cities are last rendered at z13, mid-size cities at z14, towns at z15; `place=suburb`, `quarter` and `village` at z16, `hamlet` at z18. The idea is that above these zoom levels, the larger `place` should be filling up just about the whole screen.

In my `place=city` (name="Wamena"), there is also a node with `place=neighbourhood` and `name="Kota Wamena"` meaning "City Centre" or "Downtown" in English, for the city centre neighbourhood, so this shows up at the higher zoom levels when the city label disappears. If the city label was always shown, it would block the neighborhood name at many zoom levels.

**Comment by jidanni** [comment]
@jeisenbe:
https://www.openstreetmap.org/?#map=11/23.9797/121.6070&layers=T at and
lower zooms, the big city of
https://en.wikipedia.org/wiki/Hualien_City 花蓮市
https://www.openstreetmap.org/relation/3410979
is missing, and only appears at
https://www.openstreetmap.org/?#map=12/23.9770/121.6077&layers=T and
higher zooms.

Comparing
- https://www.openstreetmap.org/?#map=9/23.9775/121.5308&layers=C
- - Good! Hualien shown, smaller population towns not shown.
- https://www.openstreetmap.org/?#map=9/23.9775/121.5308&layers=T and
- https://www.openstreetmap.org/?#map=9/23.9775/121.5308&layers=H
- - Bad: Those towns shown, Hualien not shown!
- https://www.openstreetmap.org/?#map=9/23.9775/121.5308
- - Somewhat bad: smaller towns shown along with Hualien, but all
appearing equally important.

**Comment by jeisenbe** [comment]
But the initial issue is about features disappearing too soon. Hualien (花蓮市) should be rendered from z9 to z15, so I believe this isn't a problem? At z15 Hualien appears to take up the whole screen.

Your link is to the relation with id 3410979 - this style does not render `place=town` mapped as areas (multipolygon relations or closed ways) or as boundary relations. So we are not actually rendering that, but the place node https://www.openstreetmap.org/node/60655639 - this is a `place=town` with `population=105034` and name=花蓮市

The nearest town to the north which renders is https://www.openstreetmap.org/node/60655838:
name=新城鄉 (name:en= Xincheng), a `place=town` with `population=20274`

We render all `place=town` the same; only `place=city` get a larger text label (depending on population).

(**OT**: `population=105034` is quite large for a `place=town`. I don't know what standards the Taiwan mapping community uses to map a place as `city` instead of `town`, but globally 99% of `place=town` that have a tagged population have a `population` value less than 100,000, and 38% of `place=city` have `population < 100,000`. See [Talk:Tag:place=town](https://wiki.openstreetmap.org/wiki/Talk:Tag:place%3Dtown) and [Talk:Tag:place=city](https://wiki.openstreetmap.org/wiki/Talk:Tag:place%3Dcity#Population_tag_values_of_place.3Dcity_nodes for more details. Retagging as a place=city will help some database users properly interpret this place in relation to nearby towns.)

**Comment by jidanni** [comment]
Perhaps go back to using strict population comparisons:
![4](https://user-images.githubusercontent.com/1230959/64130981-4a153c80-cdf8-11e9-8cda-41e69c70a9f3.jpg)
![5](https://user-images.githubusercontent.com/1230959/64130985-50a3b400-cdf8-11e9-8198-92d92aff40ea.jpg)

**Comment by polarbearing** [comment]
What relation has the Query Feature button on the OSM website to this style?

**Comment by pnorman** [comment]
> What relation has the Query Feature button on the OSM website to this style?

None

**Comment by jidanni** [comment]
Oops conversation drifted...

**Comment by jeisenbe** [comment]
I've set this issue as closed with #3879 because we are not directly in control of whether features can by queried at any particular zoom level - this is determined by the openstreetmap.org website team. The PR now renders airports later in most cases, so the main problem mentioned in this issue should be addressed.
