### ISSUE TITLE
Use company logos for chain stores instead of generic icons

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3828]
Long term wishlist item:

Use official promoted logo of chain stores vs. generic icons.

Example: use official 7-Eleven brand full color licensed logo for 7-Eleven stores.

Many companies publish official icon GIF / PNG packs for use on websites, maps, etc.
They are much more easy for users to identify than generic "convenience store" icons,
thus add value to the map, while still taking up the same space (thus not free extra advertising.)

This is a long term wishlish item, to be gradually accomplished on a per country / per chain basis. Note a 7-Eleven in China might be a totally different legal entity than one in Russia, and thus one cannot always use the same icon.

This would also help distinguish the case of  #3826, telephone (booth) vs. telephone (company office.)

**Comment by Prince-Kassad** [comment]
I don't think this is possible under the cc-by-sa license our tiles are currently licensed under. OpenStreetMap is hosted in the UK and that uses the sweat of the brow principle which means even the simplest logos are copyrighted. A permission to use the logos on websites doesn't help because we expressly allow usage of our tiles even for commercial purposes, e. g. printed in a book or on a map.

**Comment by Adamant36** [comment]
The way iD Editor does it through the Name-Suggestion-Index is that they query the brand logos through social media websites, using Wikidata as a source for social media account links, and don't self host them. Which supposedly gets around any possible copyright issues if I understand it correctly. There's also fair use and the fact that superficial artistic letter variations done in most brand logos can't be copyrighted because they aren't considered unique works. Which I think extends to the UK. Brand logos also have special copyright exceptions for things like map icons from what I understand. Anyway, I think not self hosting might be a way to do it. Although, who knows. I'm not a copyright lawyer and its obviously complicated. Although I think its doable. The main hurdle would probably be how the map style handles icons and it might be more viable (better/easier to implement) when the site gets vector tiles instead of doing it here in CartoCSS. That's just my opinion though.

**Comment by kennykb** [comment]
Turn the problem on its head. Offer to display the brand logos in return
for an annual contribution to OSMF. Make them get *our* permission to have
their logo displayed! Some of the chains' publicity departments will jump
at the chance.

(Only half kidding.)

**Comment by polarbearing** [comment]
This idea would provide advertising for the chain stores, and therefore be a severe disadvantage for individual ones.

**Comment by Adamant36** [comment]
> This idea would provide advertising for the chain stores, and therefore be a severe disadvantage for individual ones.

The idea in general or just @kennykb's suggestion? If it's the idea in general, individual store names would still be rendered. Although, I guess it's true that ones with specific brand icons would naturally be more appealing to click on, and it wouldn't be very cartographically balanced anyway if only some brands had unique icons. While others still had generic ones. There could never be a complete database of brand icons either, even if individual brands where included. So, you bring up a good point. As there's probably no way to not play favorites to some degree, thus disadvantaging the none favored brands, by using company logos.

**Comment by jeisenbe** [comment]
I agree that brand-specific icons are not feasible

Since all the svg icons in this style are included in the github
repository, I believe all icons need to be under a suitable license which
matches that of the style sheet as a whole. It’s unlikely that any
commercial businesses would agree to release their brand symbols under such
a license.

It’s likely that map users would assume that any brand-specific icons were
paid advertisements, because this is how it works with other online maps.
This would be misleading.

**Comment by jidanni** [comment]
Mom and pop stores could also submit their logo icon too, thus it is a
fair playing field.

In fact e.g., in the iD editor perhaps one could merely fill in

Icon = https://example.com/favicon.ico etc.

**Comment by pnorman** [comment]
> I agree that brand-specific icons are not feasible Since all the svg icons in this style are included in the github repository, I believe all icons need to be under a suitable license which matches that of the style sheet as a whole. It’s unlikely that any commercial businesses would agree to release their brand symbols under such a license.

Yes.

If someone wants to proceed with this, the first step would be to get the LWG to confirm that they are okay with company icons appearing on the map. I'm not sure that's sufficient, but it'd be the minimum I'd want before being comfortable investigating it.

**Comment by jidanni** [comment]
Well as the issue is now closed, I guess it is all over with.

**Comment by jeisenbe** [comment]
Issues can be reopened very easily, if there is any change. Closing an
issue does not mean that it will never happen: for example, issues are
often closed when a tag is still to new or infrequently used to be rendered
but this could change and the issue could be reopened.

Though in this particular case it is unlikely.

**Comment by Adamant36** [comment]
It looks like Google Maps is starting to do it. It's kind of cool. I think it would be doable here when there's vector tiles and things can be clicked on. Like with a pop window that uses brand icons the same way the name suggestion index does in iD Editor as kind of a "more information" thing. Accessing them from a third party would help get around any copyright issues that storing the brand logos themselves might cause. Plus, maintainability is easier that way. Since the icons aren't then being stored, sorted, etc etc on the style side. Not to mention if it's done in a pop up window there isn't favorites being played with the specific icons and people who don't know the brands would still know what kind of POI it is by looking at the map. That's how I imagine it at least.

**Comment by polarbearing** [comment]
This would be a nice case for an overlay map, but not within the general style.

**Comment by jidanni** [comment]
Well I give up.

**Comment by Adamant36** [comment]
> Well I give up.

Maybe put some energy into adovacting somewhere for vector maps. It seems like a lot of people want them and that having them is the only way to resolve a lot of the issues you and other people bring up lately, but there doesn't seem to be any clear direction anywhere on how to get started implementing them or even will to do it if there was. I think if there was some clear starter issues for it that people could work on that would help, but also just advocating for it and listing the benefits where you can. It seems like your good at coming up with off the wall issues that other people don't think about. So, maybe you could lend that same thinking outside of the box mindset to getting some movement on vector maps. Its at least better then just giving up on things.
