### ISSUE TITLE
Render emergency=siren

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#3836]
Outdoor warning sirens ([`emergency=siren`](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dsiren)) are relevant to public safety and are useful for pedestrian orientation (such as in a park), so it would be great if they would show up at a high zoom level. They tend to be more prominent than `power=pole`s (rendered at z16+) but less prominent than, say, `man_made=water_tower`s (z17+). They’re even more prominent when actively sounding. 🙉

Sirens are sometimes mounted on rooftops, such as fire station roofs, which raises the possibility of collisions. But if we restrict them to z18+, then there would be fewer collision issues. Maybe `location=roof` sirens could be filtered out, relegated to higher zoom levels, or given lower precedence than other POI icons, but I don’t know how feasible these approaches would be.

(I was sure I saw an issue about sirens in the past, but [GitHub insists](https://github.com/gravitystorm/openstreetmap-carto/issues?utf8=✓&q=siren) there’s no issue in this repository regarding sirens yet. Apologies if it’s a duplicate.)

**Comment by jeisenbe** [comment]
I downloaded the 4596 sirens in the database mapped as ways or nodes. All but 14 are mapped as nodes, and the wiki suggests that this is the recommended mapping method. This is relevant: the key `emergency=*` is not imported as a polygon feature when mapped as a closed way, but this isn't a problem for a rendering based on a node only.

About 350 currently render due to other tags on the same node, mainly `man_made=tower` and `man_made=mast` (since most free-standing sirens will be supported by a pole or tower), and a little over 400 have location=roof or =rooftop and might be excluded from rendering, based on how we render other man_made features.

Over half (2705) of the mapped sirens are in Germany; you can roughly see the borders of Germany in these nodes alone. However, there are still 1885 in the rest of the world, which suggests it might be a frequent enough feature to consider.

It may be difficult to find a intuitive rendering; this would be the most challenging step.

**Comment by Prince-Kassad** [comment]
I am not convinced yet that this is a suitable feature to render on a general-purpose map.

**Comment by jeisenbe** [comment]
@1ec5 the[wiki page Tag:emergency=siren](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dsiren) now suggests that `man_made=mast` + `tower:type=siren` be added to free-standing sirens on a tall mast or pole. 

If this advice is followed these features will be rendered without adding a new rule.

In theory we could have a subtle difference in the `man_made=mast` icon when combined with `tower:type=siren`, but I believe we already have too many different tower and mast type icons.

Thoughts?

**Comment by 1ec5** [comment]
I just added that after seeing the same suggestion at the [`tower:type=siren`](https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dsiren) page. Seems like this combination has been used in an import in Europe, though none of the editors currently facilitate it. The icon that results isn’t very intuitive, but it does cover freestanding sirens, as opposed to the rooftop sirens that seem likely to collide out more important POI icons.

**Comment by jeisenbe** [comment]
Do you have a rendering suggestion?

**Comment by pnorman** [comment]
I'm going to close this. Rendering sirens on rooftops doesn't help with pedestrian orientation, and for sirens on masts, there are other tags to indicate the mast.
