### ISSUE TITLE
Symbol for aeroway=airstrip

### ISSUE THREAD

**Issue by rene78** [gravitystorm/openstreetmap-carto#3853]
Do you guys think that we should have a symbol for **aeroway=airstrip**? Found this one in Commons, which would be a decent fit in my opinion (has to be rotated 45° anti-clockwise of course):

![image](https://user-images.githubusercontent.com/36115705/63843727-2335b100-c987-11e9-94eb-7c0bf8d076de.png)
https://de.wikipedia.org/wiki/Datei:Airplane_GA_Black.svg

I saw the discussion about too many symbols cluttering the map. This held me back from trying to implement it myself.

**Comment by matkoniecz** [comment]
This tag seems to be highly subjective to me

> reasonably flat area where light aircraft can land and take off from

it is not even restricted to places sometimes ever used for such purposes.

Also, out of 4.5k objects

> Most (about 3,500) airstrips in New Zealand are the result of importing LINZ data. 

https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dairstrip

**Comment by imagico** [comment]
I concur with @matkoniecz - most uses are from a New Zealand import and use elsewhere is spotty (https://taginfo.openstreetmap.org/tags/aeroway=airstrip#map), documentation is fairly vague - lacking verifiable criteria for positive identification and distinction from aeroway=aerodrome.  There also seems disagreement if this tag is to be used like aeroway=aerodrome on nodes and polygons or like aeroway=runway for the line along which aircrafts start and land.

**Comment by rene78** [comment]
Sounds reasonable. Thanks for the feedback. I was just changing tags in Borneo from aerodrome to airstrip and thought, that there must be many more of those very small airfields all over the world. But if the usage of the tag is not 100%ly clear it makes no sense to have a symbol.

**Comment by imagico** [comment]
There is traditionally no lower size limit assumed for aeroway=aerodrome.  In most parts of the world the tag is used even for the smallest agricultural/sports/etc. airfields.

My recommendation for mapping airfields:  Map what is verifiably observable.  The runway in its actual size and with a surface tag is a good indicator for the size of the airfield.  If an airfield is not for public use proper access restrictions are also useful (and we already use this in this style).  This requires on-the-ground knowledge of course.

**Comment by jeisenbe** [comment]
This map style currently looks for the presence of IATA and ICAO codes, and access=*, as a hint that an aerodrome is significant (and should be rendered at z10), since almost every aerodrome with regularly scheduled passenger service will have one of these codes. We probably should consider rendering the minor aerodromes from z12 only.

OT: I've been mapping airstrips in Indonesia as `aeroway=aerodrome` + `aerodrome=airstrip`, with the definition that an airstrip has no terminal building or other facilities, no scheduled service, just an unpaved runway.  This makes up the majority of aerodromes in Papua, Indonesia. However, I can't confirm if other mappers have been using this tag consistently.

**Comment by geozeisig** [comment]
There are now over 5000 of these small airfields. They are also scattered all over the world. Potentially, it also gives much more. We should think about whether they can be given an icon. I think a single-engine aircraft is a good choice for an icon.
