### ISSUE TITLE
Interrupted rendering of powerlines

### ISSUE THREAD

**Issue by BenediktO** [gravitystorm/openstreetmap-carto#3858]
### Expected behavior
Powerlines should be rendererd continously.

### Actual behavior
On some zoom levels powerlines are interrupted. This seems to happen when the line only covers a very small distance of a tile.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=16/65.3614/-15.6105

**Comment by kocio-pl** [comment]
Actual rendering problem:

![Screenshot_2019-09-01 OpenStreetMap](https://user-images.githubusercontent.com/5439713/64070512-ef49dc80-cc61-11e9-8f16-4a8992db0ea1.png)

**Comment by jeisenbe** [comment]
I've downloaded the data in this area but I am not able to reproduce the problem. I suspect it has something to do with the tile boundaries, because a line cuts across the corner at z18, or an old tile that was not refreshed. It doesn't appear to be caused by openstreetmap-carto.

**Comment by jeisenbe** [comment]
Let us know if you find this problem anywhere else.

**Comment by BenediktO** [comment]
I found in in various other places:
https://www.openstreetmap.org/#map=16/65.9242/-21.6249
https://www.openstreetmap.org/#map=16/65.8047/-21.7069
https://www.openstreetmap.org/#map=16/65.7859/-21.7533
https://www.openstreetmap.org/#map=15/64.9827/-14.2603
So that happens on powerlines and minor_lines and on different zoom levels
I tried to rerender the tiles using the /dirty url but nothing changed.

**Comment by jeisenbe** [comment]
The last, https://www.openstreetmap.org/#map=15/64.9827/-14.2603 actually has a gap between the two ways, so it's a mapping problem: see https://www.openstreetmap.org/way/514030123 and https://www.openstreetmap.org/way/514032045 which do not connect.

I've tried to reproduce the problem with two of the others, but on my test rendering setup there is no gap. I'm not sure why the problem is appearing on openstreetmap.org

**Screenshot 1**
https://www.openstreetmap.org/#map=16/65.9242/-21.6249
![powerline-gaps-1-screenshot](https://user-images.githubusercontent.com/42757252/65397586-4c155e80-ddec-11e9-8e35-6a8c316c286c.png)

Test rendering 1
![powerline-gaps1-test](https://user-images.githubusercontent.com/42757252/65397588-50417c00-ddec-11e9-91c4-fa2c6c92af29.png)

**Screenshot 2**
https://www.openstreetmap.org/#map=16/65.8047/-21.7069
![powerline-gaps-2-screenshot](https://user-images.githubusercontent.com/42757252/65397652-cf36b480-ddec-11e9-9310-209a8dcc1ad4.png)

Test rendering 2
![powerline-gaps-2-test](https://user-images.githubusercontent.com/42757252/65397666-da89e000-ddec-11e9-9711-df3fa736d560.png)
