### ISSUE TITLE
One edit, two renderings

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3906]
Depending on the tile server(?), for the same data, sometimes the user
will see addresses on top of buildings, sometimes the user will see
buildings on top of addresses.

![17384-1](https://user-images.githubusercontent.com/1230959/65565601-edceb400-df82-11e9-92eb-128f80d23b85.jpg) ![20530-2](https://user-images.githubusercontent.com/1230959/65565605-f58e5880-df82-11e9-8303-18c2df4dd506.jpg)

I made https://www.openstreetmap.org/changeset/74882793,
introducing "7-12" to the map, but now it is getting rendered
inconsistently for the same [URL](https://www.openstreetmap.org/?mlat=24.18319&mlon=120.86736#map=19/24.18319/120.86736).
One edit, two different renderings.

P.S., one would hope the address would be on top.

**Comment by jeisenbe** [comment]
Location is https://www.openstreetmap.org/#map=19/24.18320/120.86737
![address](https://user-images.githubusercontent.com/42757252/65568532-31cab480-df95-11e9-8800-05c866a620c0.png)
I'm seeing the opposite: address only on the top half. There is a tile border here.

A test rendering with Kosmtik on my own computer doesn't show this problem. It looks like the issue is with old tiles in the server cache. I suspect it will be fixed in a few hours when the tiles are re-rendered properly.

**Comment by jidanni** [comment]
I get it, it just happens to be right on a tile border.

**Comment by jidanni** [comment]
Posted to http://catless.ncl.ac.uk/Risks/31/44#subj16 .
