### ISSUE TITLE
Gates need to fit on a single node to get rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3929]
- Short gates, that fit on a [node](https://www.openstreetmap.org/node/6401685904) are rendered.
- Longer gates, that need a whole [way](https://www.openstreetmap.org/way/732810564) aren't.

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate#On_a_way says
gates can be ways.

So the biggest gate in the world would need fit on a single node to get rendered?

**Comment by imagico** [comment]
What the wiki says is not of that much concern here.  What matters most is how tags are actually used.  Looking at a few places practice of using barrier=gate on ways seems to vary a lot.  In some places it is used in addition to a node, in some places alone.  Sometimes there are several connected ways separately tagged as this (presumably several parts or wings of a gate).

I think independent of consistency of use just flatly rendering a symbol at `ST_PointOnSurface(way)` would be counterproductive because the correct location for rendering a gate mapped with a linear way with a point symbol would be at the intersection with the highway it spans.

**Comment by jeisenbe** [comment]
The wiki was changed back in 2010. The original proposal was that gates should be on nodes shared by the highway. See  https://wiki.openstreetmap.org/wiki/Talk:Tag:barrier%3Dgate#Mapping_on_a_way_instead_of_a_node.3F and the change https://wiki.openstreetmap.org/w/index.php?title=Tag%3Abarrier%3Dgate&type=revision&diff=462212&oldid=459004

Probably this should be discussed on the wiki first. It's also relevant for other barriers types that are only rendered on nodes, eg: 'gate', 'swing_gate', 'block', 'log', 'cattle_grid', 'stile', 'motorcycle_barrier', 'cycle_barrier', 'full-height_turnstile', 'turnstile', 'kissing_gate'.

**Comment by jidanni** [comment]
All I know is something needs to be done soon, to prevent people from
traveling miles and miles, OSM map in hand, only to be confronted by a
big, fat, locked, gate.

> Well the road would be marked private anyway, with grey dashes, so they would know in advance anyway.

Well what if the road is not private, but there is a big gate upon it, that someone edited according to best practices.

**Comment by imagico** [comment]
> How difficult is it to render an icon at the location of a node shared by a highway= way and barrier=gate way, uisng something like ST_Intersects or ST_Intersection? Is that an option or would it be too slow?

It is possible but it is also non-trivial with all the special cases and i doubt it is a good idea given the current mapping practice.  barrier=gate nodes are vastly dominating and are used very consistently on the intersections between the highway lines and the physical barrier.  barrier=gate however are used in a number of very different ways on ways, including:

* ways intersecting a highway
* ways intersecting a highway with an additional barrier=gate node
* standalone ways with no highway intersecting (which is a completely different concept of the meaning of the tag)
* physically separate parts of a gate construction

And probably there are also gates mapped with closed ways as polygons out there.

**Comment by HolgerJeromin** [comment]
Do router use ways which intersect with a "gate" way when the connection point is not tagged?

**Comment by Adamant36** [comment]
What about forgoing the icon idea and rendering gate ways as lines in a slightly lighter or darker color then fences?

**Comment by aceman444** [comment]
@HolgerJeronim
I think routers would ignore the gate if it isn't tagged on the node shared with the way. At least e.g. OsmAnd would. They are basically invisible, similarly to pedestrian crossings, bollards and other such objects.

**Comment by HolgerJeromin** [comment]
The example https://www.openstreetmap.org/way/732810564 from @jidanni is clearly tagged wrong, as the gate osm way has no shared node with the `highway`. 
So it no routing software of the world would exclude the `highway` based on the crossing `gate` object (but would because the highway itself has a private `access`). But QA tools should shout.

**Comment by HolgerJeromin** [comment]
But even when the ways share nodes like this [highway](https://www.openstreetmap.org/way/291519478) and this [gate](https://www.openstreetmap.org/way/291519493#map=19/50.77842/6.06447) the router do not "move the access restriction" to the route.
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=50.77834%2C6.06449%3B50.77850%2C6.06424

So we never should move an icon from the crossing way to the junction to support proper tagging like in https://www.openstreetmap.org/way/291520687

**Comment by jeisenbe** [comment]
It sounds like we have consensus that this issue should be closed without changes, because we want to support consistent use of these types of `barrier=` tags on a node shared with the highway. Is that correct? 

Also see some discussion on https://wiki.openstreetmap.org/wiki/Talk:Tag:barrier%3Dgate

**Comment by jeisenbe** [comment]
Closing, mappers will be supported in using these type of `barrier=gate` and related tags on nodes which are shared by the `highway=`.
