### ISSUE TITLE
Cliff not rendering with other tags

### ISSUE THREAD

**Issue by mrpulley** [gravitystorm/openstreetmap-carto#3944]
### It currently is not rendering. I suspect the problem may be with one (or both) of these other tags on the way - historic=archaeological_site or tourism=attraction. The problem can't be that the way is circular, as other circular clifflines render, e.g. [https://www.openstreetmap.org/way/265561635] (Katoomba, Australia)

**Comment by imagico** [comment]
As you already pointed out the feature in question is tagged natural=cliff, historic=archaeological_site and tourism=attraction.  The latter two imply a polygon feature, the former a linear feature.  osm2pgsql can either treat this as a polygon or a linear feature, not both.  So based on that it is interpreted as a polygon and therefore not rendered as a cliff (because we don't support cliffs mapped with polygons).

Generally the tagging used is ambiguous.  The non-verifiable tourism=attraction aside natural=cliff + historic=archaeological_site on the same feature is not a useful combination.  So the suggested solution here would be to separate the mapping of the cliff and the archaeological site and to remove the tourism=attraction.

**Comment by jeisenbe** [comment]
See also the discussion in #3833

**Comment by mrpulley** [comment]
I've separated the cliff into a separate way, and it now renders. Thanks.
