### ISSUE TITLE
Name of a leisure horse_riding not displayed on osm.org

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#3953]
### Expected behavior
show name
### Actual behavior
does not
### Links and screenshots illustrating the problem
Centre Équestre De Dolembreux
https://www.openstreetmap.org/node/6893498397

**Comment by polarbearing** [comment]
Tag is used 9.3k, de facto following a proposal 2012. 
The [wiki](https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dhorse_riding) example renders, since it is co-tagged with landuse=farm. 
Question is, should the horse_riding render on its own, or is it sufficient to render with a landuse tag (meadow might be another typical case)?
Next question, should it render on a node, or on area only?

**Comment by jeisenbe** [comment]
Thank you for reporting this issue, @a-pirard. We always appreciate new reports.

There is already an open issue about this, #2344. 
There was also a request in #3660 to add an icon but this was closed.

Please continue the discussion in #2344 and feel free to add any new ideas.

**Comment by a-pirard** [comment]
On 27/10/2019 01.38, Joseph E wrote:
    
    
      
      Thank you for reporting this issue, @a-pirard.
        We always appreciate new reports.
      There is already an open issue about this, #2344.
        There was also a request in #3660 to add an icon but this was
        closed.
      Please continue the discussion in #2344 and feel free to add any new
        ideas.
      
    
    Thanks to polarbearing's tips.
    I removed the node and I put the tags on the building.
    I "tagged for the renderer" as they say.
    This issue has nothing to do with #2344.
    It would be best for leisure to behave as amenity.
    As well as JOSM and carto to have the same rendering to minimize
    surprises (JOSM showed name and icon on the node).
    Thanks for your help.

**Comment by jeisenbe** [comment]
>
> This issue has nothing to do with #2344.


I don’t understand. The title of that issue is “Add rendering for
leisure=horse_riding” and the title of this issue is “Name of a leisure
horse_riding not displayed”

The request for rendering in this case includes displaying the name.

It would be best for leisure to behave as amenity.


Neither “amenity=“ nor “leisure=” are always rendered in this map style.
Only certain values of each key are rendered.

JOSM and carto to have the same rendering to minimize surprises


JOSM renders many more features than this style. This is appropriate
because JOSM is only for mappers, and does not attempt to render the whole
planet at once.

This style also has a goal of supporting mappers, but we also have goals of
legibility and use as a general map at many different scales (or zoom
levels), for the whole globe.

For this reason it is more difficult to add additional features to this
style than to JOSM.

**Comment by polarbearing** [comment]
>  I removed the node and I put the tags on the building. I "tagged for the renderer" as they say.

I did not recommend any retagging. 
Anyway I hardly understand how a part of a building (as in tagging the address node) or the whole small building could be a leisure facility with horses. If it is just an office, it should be tagged as such.

**Comment by ReinerMeyer** [comment]
I don't understand why leisure=horse_riding exists as a tag, but the name is not shown in the map of openstreetmap.org (way: Reitstall Wiener Neudorf (203993861), version #6).
This problem does not exist for all other leisure=*.

**Comment by imagico** [comment]
The reason why you don't see everything tagged with the key `leisure=*` with a label is because we intentionally make a conscious choice about what tags we render - following [our documented goals](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md).

As @jeisenbe mentioned above in https://github.com/gravitystorm/openstreetmap-carto/issues/3953#issuecomment-546648612 we have an open issue about rendering leisure=horse_riding in #2344.  Any discussion on the matter should go there.  Also useful to read up is #3660 with the arguments why a previous suggestion to add rendering it was rejected.
