### ISSUE TITLE
Render archeological site polygons as tourism boundary

### ISSUE THREAD

**Issue by StyXman** [gravitystorm/openstreetmap-carto#3958]
Archeological sites are usually tourist attractions. We already render them as amenity points, but some of them are frankly quite big, and mapped as polygons. Just render the same polygon effect for zoos and theme parks for those polygons.

**Comment by matkoniecz** [comment]
repeat of #732 but not a duplicate, as provides a specific rendering idea that makes sense and has decent chance to be an overall improvement

**Comment by imagico** [comment]
I suggest to close this - if an archeological site has a physically manifested verifiable boundary then that should be mapped and rendered as such (like `barrier=*`) same applies if ruins are visible and can as such be mapped.  But rendering legal bounds of sites as such (which practically is often simply guesswork or abstract wrapper polygons) is something we should reduce rather than extend IMO.

Indicating visually in some form which mapped ruins belong to a certain (named) archeological site would be something interesting to consider i think - but it would require (a) an established tagging for the ruins of an archeological site, (b) an established way to map which ruins belong to a site and (c) probably quite a bit of work to develop an efficient and visually suitable way to depict that.
