### ISSUE TITLE
Many times same name on roads

### ISSUE THREAD

**Issue by Kogacarlo** [gravitystorm/openstreetmap-carto#3960]
Hi people,
I wonder if it is possible to prevent displaying many times the same name on a road, as in the picture.
It's the Odalaan in Urmond.
![Odalaan in Urmond](https://user-images.githubusercontent.com/38103490/67901057-18092800-fb66-11e9-894b-5fa9634347f4.png)
In this case the same information is displayed eight times. This makes the map less readable.
In other cases the name in not displayed at all because every roadpiece is too short for the name to be displayed.

**Comment by polarbearing** [comment]
In this case, the highway is fragmented without further reason at each junction, all the same tagging. 
To find: https://www.openstreetmap.org/way/6776448 etc

More generally, I wonder what happens when roads are split for reasons such as turn:lanes etc?

**Comment by Kogacarlo** [comment]
> In this case, the highway is fragmented without further reason at each junction, all the same tagging.

That's right.
I as a mapper combine as many roads as possible. However, that is "tagging for the renderer" wich is "not done" in the mapper community.

> More generally, I wonder what happens when roads are split for reasons such as turn:lanes etc?

The road will have to be cut in two pieces. The name will be rendered on every piece.

**Comment by jeisenbe** [comment]
This cannot be solved fully without preprocessing `highway=` features prior to rendering the name labels.

One would need to combine all connected ways which have the same `name=` to make a single linestring, and then use that new linestring for rendering.

Generally we try to avoid preprocessing in this style, since it obscures the way that the elements are mapped in the OpenStreetMap database, and adds complexity to the rendering style. 

Since this style is used at openstreetmap.org to render the whole globe with updates every minute, it needs to work quickly.

(We could hide some of the duplicate labels by setting a larger minimum distance between repeated text labels, but this would again obscure the way that the data is entered in the database, and would sometimes cause too few labels to be shown.)

>  as a mapper combine as many roads as possible. However, that is "mapping for the renderer"

I would not call it "mapping incorrectly for the renderer". It's best for `ways` to have a reasonable length: not too long (so that mappers do not have to download 100 km long ways to edit a single neighborhood), not too short (so that mappers don't have to zoom in to z20 just to select one part of a road or river). This is "mapping for ease of editing and maintenance" - a good thing, because volunteer mappers, such as yourself, are OpenStreetMap's most valuable resource.

**Comment by matkoniecz** [comment]
In this case preprocessing should be fine as it would not distort geometry, data etc. I would hide way splits, but I think that this is technical detail on the same level as nodes - and we are not rendering individual nodes.

But anyway this is very similar to #951 (about shields) and I think that it would be nice to fix both of them.

Maybe add "and names" to #951 and close this one?

---

Also, in case of ways tagged exactly the same and without turn restrictions or other reasons for split - merging them is perfectly fine.

**Comment by jeisenbe** [comment]
Agreed, let's continue discussion at #951 - I would like to see a SQL query and check the performance implications
