### ISSUE TITLE
Weird glitch in London

### ISSUE THREAD

**Issue by hugobqd** [gravitystorm/openstreetmap-carto#3972]
I found a weird glitch in London on zoom 13:
https://www.openstreetmap.org/#map=13/51.5139/-0.1097
<img width="1088" alt="Capture d’écran 2019-11-15 à 01 09 14" src="https://user-images.githubusercontent.com/35178/68906574-0d918580-0745-11ea-8c01-1aa29c6a0a12.png">

**Comment by jeisenbe** [comment]
Thank you for reporting this problem @hugobqd.

I am not seeing this problem now. Here is a current screenshot of this area from openstreetmap.org (I am in southeast Asia, so I may be seeing tiles from a different server):

![z13-city-of-london-current-screenshot](https://user-images.githubusercontent.com/42757252/68913285-1f534700-079e-11ea-9174-ddc7327cd63a.png)

Since it is not visible to me, this appears to have been a data issue or perhaps a temporary issue with just one of the servers, rather than a problem with this stylesheet. This happens occasionally but is usually fixed quickly when the tile is re-rendered.

**Comment by hugobqd** [comment]
thanks

**Comment by HolgerJeromin** [comment]
This was probably an old tile (buggy changeset was reverted).
reported and analysed here: https://github.com/openstreetmap/operations/issues/340
