### ISSUE TITLE
prevent name hiding housenumber

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#3983]
When some name="pita Céline" is coded, addr:housenumber=69 disappears.
Many contributors fight against that ("map for the renderer") in uncoordinated ways.
Why not simply display "69, Pita Céline" (69 taken from number)???
Or, to be more general, design some syntax like
like name=[num, ]blah blah or blah blah[, num]
so that the name alone can be extracted from the map.
It seems that the case when only an icon hides the number can be solved by coding a dummy name=[num] but I'll let you think about that and discuss it.

**Comment by Adamant36** [comment]
> Many contributors fight against that ("map for the renderer") in uncoordinated ways.

Do you have some examples? I do a lot of business POI mapping and I've never seen anyone map things differently if the business has an address (like intentionally leaving out the business name/address/or whatever).

**Comment by Prince-Kassad** [comment]
I have seen it in some city (can't remember which city) where the housenumbers were added to the name= so they still show up even when there is a name.

I don't think there's a good solution to that until we get vector tiles and addresses become toggleable at will.

**Comment by jeisenbe** [comment]
@a-pirard thank you for opening this issue. Do you have a link or a screenshot of a place where this is a problem? I wasn't able to find the feature "pita Céline".

It would be difficult to display both the `housenumber` and `name` for the same feature in this style, in a way that would not cause confusion. For example, a supermarket like "[99 Ranch Market](https://overpass-turbo.eu/s/OQ4)" could have the first part of it's name confused for a house number if this was not done carefully. Moving the number to the end would cause confusion with places like "[Cafe 89](https://www.openstreetmap.org/node/5231670007)"

Ideally we might have the building address number rendered in a different font and color, in a different location than the shop icon or the name, but I am not aware of a feasible way to do this in Mapnik, the rendering software which we use.

**Comment by Prince-Kassad** [comment]
We currently render both addr:housename and addr:housenumber separated by a linebreak if both are tagged on an object. But since name renders in a much larger font that's not a solution that would work well in that case.

**Comment by jeisenbe** [comment]
I'm not aware of a technically feasible and cartographically sensible way to solve this problem. In most cases the name of a POI such as a shop or cafe is more relevant than the address number, which should be shown by routing applications and search. In this style we want to provide consistent feedback to mappers about their edits, so we would not want to provide confusion about the number of the address versus a name containing a number. Therefore I will close this issue.

**Comment by joshinils** [comment]
> I'm not aware of a technically feasible and cartographically sensible way to solve this problem. In most cases the name of a POI such as a shop or cafe is more relevant than the address number, which should be shown by routing applications and search. In this style we want to provide consistent feedback to mappers about their edits, so we would not want to provide confusion about the number of the address versus a name containing a number. Therefore I will close this issue.

That appears not to be the case for me here: https://www.openstreetmap.org/way/79675409 does not get rendered with it's `addr:housenumber=7`
this one: https://www.openstreetmap.org/way/68196116 has nodes with the addresses which I guess moves the name down that far.
This one https://www.openstreetmap.org/way/79675280 hides the address nodes via the name.

All of these are old historical houses hence why they have a name.
But since they are residential houses I think the housenumber is more important than their name.

Maybe a solution could be to favor the housenumber if the building is tagged as where people live like residential or house.

**Comment by a-pirard** [comment]
On 17/02/2021 06.31, joshinils wrote:
    
    
      
      
        I'm not aware of a technically feasible and cartographically
          sensible way to solve this problem.
        
      
    
    It's important that someone searching OSM.org for an address can see
    and not guess the numbers.
    There must certainly be an algorithm determining what area is
    covered by the POIs and names and finding a place, even the best
    one, to put the number in. The software does that already to fold
    and put the name inside the walls.
    Mappers are fighting against carto, they call it "map for the
    renderer", to make what they map visible and often put the number on
    a wall, what I have
      done lately (if you can see number 1) although there is plenty
    of room in the upper right part of the house.
    The algorithm can also display the numbers on the wall.
    BTW that number 1 is really too small and barely visible.
    BTW too, it shouldn't be flagged as an error when wall, POIs and
    inside have the same number.

**Comment by Adamant36** [comment]
> Maybe a solution could be to favor the housenumber if the building is tagged as where people live like residential or house.

That seems like the sensible solution to me. Rarely if ever is someone looking the name of a residential over the address unless it's like a group home or something, but then tagging the building as residential instead of something like commercial is questionable in the first place.

Also, I've seen some instances of tagging random residential houses with names like "moms house" , "meeting place", or "drug dealers place" before and I don't think that type of name tagging should be encouraged. So, there would be a benefit to not rendering names on residential buildings outside of just the address rendering instead.

**Comment by joshinils** [comment]
Coming back to this, I think the biggest problem is when the address is tagged on a building, i.e.
`building=*` + `addr:housenumber=31` + `name=Haus Rumland`,
then the name always takes precedence over the number, which in Germany makes no sense (at least to me).

example: https://osm.org/way/78443448

A "tagging for the renderer" solution would be to duplicate the address for these named buildings and have it be a separate node (again) only for the renderer to display it too, but I don't want to do that, nor do I think it's a good idea.

**Comment by imagico** [comment]
This issue was closed because

* it is difficult with our current setup to render both the house number and the name of a building in a non-confusing and globally usable way.
* in most cases the name of a building (when correctly tagged) is more significant for the target map user than the house number.

The situation is still non-satisfying because of the first point and because use of the name tag on `building=*` is largely not correct tagging, either

* because there is some other tag on the building, referring to something located in the building and the name tag refers to that rather than the building while being ambiguously tagged this way or
* because the name tag is used for label painting rather than specifying a proper name.

For the second case it would help if we'd simply stop rendering `name=*` for `building=*` .  Unfortunately this would not help with the first case.  In any case removing the rendering of `name=*` on `building=*` would be based on such consideration, not for making house numbers show up.  So this would be a separate issue.
