### ISSUE TITLE
Overhead power=cable should in most cases render as power=minor_line

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#3984]
It is not uncommon to use insulated cables for power distribution at 22kV and below. Especially in coastal areas with harsh conditions with salt spray this will extend the lifetime of these lines.
It is also the tag to use for overhead cables at 400V and lower found in many residential areas.

Problem is they are rendered the same as power=lines which is kind of silly considering there is a thinner line for power=minor_line that is the one used for lower voltage lines.

These cables should always have location=overhead, so maybe that is a way to find them?

IMO there should be a minor_cable value, but that's a different matter.

**Comment by jeisenbe** [comment]
Thank you for reporting this issue, @Gazer75

As mentioned, there is not currently an established way to tag minor cables used for distribution. Sometimes voltage is tagged, but this is uncommon for minor cables. With "lines" we have the distinction of `power=line` (usually on towers) vs `power=minor_line` (usually on poles). This difference is easier to see in the field and easier to verify, since the voltage can be hard for mappers to find.

See the discussion in #3460 , #3019 , #510 and #297

> These cables should always have location=overhead, so maybe that is a way to find them?

There are 604 ways with `power=cable` + `location=overhead` out of 1200 with a `location` that we render, so it's not very common but it's a significant part of the small fraction that are rendered: https://overpass-turbo.eu

I checked all a sample of these ways and compared with those with `location=overground` (the next most common value). Most are clustered in a few patches in Europe (Franch, Switzerland, Germany, Czech Republic, Slovakia, Poland, Norway and Russia), there are a few in the Philippines. 

A surprisingly high percentage have a `voltage=` tag, 543 out of 604, and 480 are less than 40k which usually means "low-voltage"; 319 are voltage<1000. All of these appear to be carried by poles, rather than towers (though some connect to a tower at one end), and most are short: only 21 are longer than a kilometer. 

But the location=overground cables are not too different: there are 553 ways, and only 4 are over a kilometer long. There only only 15 places with 80 power=tower nodes, and only one way is suspended from multiple towers: [way 368610817](https://www.openstreetmap.org/way/368610817/#map=14/52.7780/-0.3077). In contrast, there are over 4000 power=pole nodes connected to the 1157 ways. 

One difference is that a majority of location=overground cables with a voltage tag are >40k (250 out of 413), in contrast to the overhead cables which were almost all low to medium voltage. But most of these are short cables within substations or power stations, not long transmission lines.

Based on this, it appears that `power=cable` is almost never used in a way similar to `power=line` - these are almost never major transmission features carried by large towers. 

Therefore, it would make more sense to render all overground and overhead `power=cable` features at the same zoom level as `power=minor_line` and `power=pole`, rather than rendering them the same as `power=line`

**Comment by jeisenbe** [comment]
@Gazer75 would you be interested in submitting a Pull Request to address this issue?

**Comment by Gazer75** [comment]
I don't know the code unfortunately.

It was an observation on my part when mapping some 22kV lines in Gulen, Norway.

Using location=overhead would be a simple way of not relying on voltage and can be verified on ground.
It will also avoid rendering cables with location=overground as minor lines. These can be sometimes seen in substations going to/from the transformer low voltage side.

In the picture you'll see a 300/132kV transformer, a shunt reactor and two 300/66kV transformers.
You can see the cable canal for the 132kV cables coming down top right, and the 66kV cables out the back from the other two. These would be location=overground/underground.
https://www.openstreetmap.org/#map=19/59.32983/10.38112
![transformers](https://user-images.githubusercontent.com/13599949/70474325-ab713980-1ad2-11ea-90d0-252fb69937d4.jpg)

**Comment by jeisenbe** [comment]
> It will also avoid rendering cables with location=overground as minor lines

The distinction between power=line and power=minor_line is mainly whether they are carried on poles or towers, according to the wiki. 

We render power=line at z14 because these are large, long-distance features which are useful for orientation in rural areas, as well as forming the most important parts of the power network, not because they are higher voltage than power=minor_line features.

**Comment by Gazer75** [comment]
Minor line should be used for distribution at less than 40kV as mentioned at https://wiki.openstreetmap.org/wiki/Tag:power=line
These lines are "usually" carried on poles due to their size.

**Comment by matkoniecz** [comment]
It seems to me that claim that `power=cable` is for all insulated electricity lines is dubious.

"Overhead `power=cable`" sounds to me like "`highway=motorway` only for bicycles".

-----

https://wiki.openstreetmap.org/wiki/Tag:power%3Dcable claims that it is "Opposite of uninsulated power=line."

I am not aware about that power=line is supposed to be just for uninsulated ones and I am highly dubious that it is used in this way. How one may distinguish insulated vs uninsulated? Both in survey and in mapping from aerial images?

AFAIK power=cable is for underground power transmission, not for all insulated power transmission. Note that this wiki page has no examples of overhead `power=cable`

**Comment by sommerluk** [comment]
Fun fact: https://wiki.openstreetmap.org/wiki/Tag:power%3Dminor_line says:

> Uninsulated power lines […] are tagged as power=minor_line.

But later:

> Minor lines may be anything […] from […] 20,000 volt lines […] to a single cable running from a street lighting pole to the next one.

Which is strange, because the use case with the street lightning poles normall means insulated conductors.

But again, later than, insulated conductors are forwarded to power=cable:
> See Also […] power=cable For insulated, underground or sea cables.

**Comment by Gazer75** [comment]
There is a lot of inconsistency on the wiki unfortunately...

**Comment by Gazer75** [comment]
@matkoniecz The difference is quite easy to spot on survey btw.
No pictures of my own, but here is a couple of streetview examples.
https://goo.gl/maps/F6RwmZYfYcGcCUd66
https://goo.gl/maps/j1es2f1cUjWuFHGW9

**Comment by jeisenbe** [comment]
@matkoniecz are you suggesting that we should remove the rendering of power=cable + location=overhead as a mistake? Or would it be ok to render them the same as power=minor_line, since that is probably the same except for the presence of insulation around the cable?

**Comment by matkoniecz** [comment]
> are you suggesting that we should remove the rendering of power=cable + location=overhead as a mistake?

No, I think that it should not be treated in a special way that hides data issues.

**Comment by Gazer75** [comment]
What data issues would that be?
Having it render as a thinner line if its an overhead cable should be the easiest way to separate them. If people map local 230V cables then you'll have a lot of these rendering as the same as transmission lines. That is not good IMO, and would also clutter the map at lower zoom levels.
Only other option is to use voltage, but that is not available to public in many areas.

**Comment by jeisenbe** [comment]
> power=cable is for underground power transmission, not for all insulated power transmission. 

Should we even render power=cable then? 

Almost all of the properly-tagged features will be underground or underwater, and none are major orientation landmarks on huge towers like power=line, so at most the could be considered similar to power=minor_line (wires on poles, rendered at z16 and up only) and telephone lines (not rendered)

Looking back at my research into how this tag is used (https://github.com/gravitystorm/openstreetmap-carto/issues/3984#issuecomment-563424077) there are now only 576 ways with location=overground (http://overpass-turbo.eu/s/PH0) and 630 with location=overhead (http://overpass-turbo.eu/s/PH1) - but there does not seem to be a clear difference between these two tags. Both are usually found on ways that are connected to power=pole features, so it appear that location=overground and location=overhead are synonyms in this case.

The other 3 "location=" values that we a render are 'surface', 'outdoor', and 'platform' - there are only 191 ways with these. http://overpass-turbo.eu/s/PH9 - 

Meanwhile, almost all cables with a 'location=' are underground or underwater: http://overpass-turbo.eu/s/PHe shows 14909 (mostly location=underground), out of 16382 total with location (https://taginfo.openstreetmap.org/tags/power=cable#combinations) - so that is 91%

It looks like the best option is to no longer render`power=cable`, and certainly we should not render it the same as `power=line`

**Comment by jeisenbe** [comment]
I also now think it's appropriate to use the tag `power=minor_line` for low-voltage distribution power lines suspended overhead on poles.

**Comment by matkoniecz** [comment]
> What data issues would that be?

power=cable used for something that is not underground or underwater.

I am not sure whatever to treat it as a tagging mistake (unsupported, can look bad on the map) or as a popular and accepted tagging scheme (and support it despite that it is a really bad idea and design).

**Comment by Gazer75** [comment]
Well a cable is insulated and can have location=overhead. I don't see a problem.

Editing the wiki to suit something else during this issue is kind of low...

**Comment by jeisenbe** [comment]
To clarify, I've edited the wiki - not @matkoniecz - after reviewing how the tag `power=cable` is used in practice. Please feel free to discuss at the relevant talk pages there, but here is a summary of what I found:

Historically, the page [Tag:power=cable](url) [originally said](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dcable&oldid=826550) that this feature was only for underground or undersea cables (2009 to 2012, and again from [2015](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dcable&oldid=1213385) to [2016](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dcable&oldid=1282192)). In[ March 2016](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dcable&oldid=1282570) it was added that cables might be on poles.

Note that this was around the time of the rejected proposal [Power_transmission_refinement](https://wiki.openstreetmap.org/wiki/Proposed_features/Power_transmission_refinement) by the same user, which doesn't actually seem to clarify the distinction between power=cable and power=line, though the examples of power=cable are underground.

While power=line was used for overhead power lines on towers, and power=minor_line for small power lines carried on poles originally, some users have suggested that these should be "transmission" vs "distribution" lines, distiguished by usage or voltage, but this practice seems to vary by country and region. The poles vs towers distinction seems to be still widely used. 

Some have suggested that power=line and power=minor_line must be uninsulated, but this was never part of the original definition of these tags: see [2015 wiki page for power=line](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dline&oldid=1213384) and [2015 wiki page for power=minor_line](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dminor_line&direction=prev&oldid=1268770) - these were mostly unchanged since 2009 or 2010. In 2016 the pages were [both](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dline&oldid=1282576) [changed](https://wiki.openstreetmap.org/w/index.php?title=Tag:power%3Dminor_line&direction=next&oldid=1213382) to mention "uninsulated" vs "insulated" as a criteria for cable vs line / minor_line.

Links to talk pages for discussion:
https://wiki.openstreetmap.org/wiki/Talk:Tag:power%3Dminor_line - first topic mentions that minor lines are insulated in some places (e.g. Taiwan)
https://wiki.openstreetmap.org/wiki/Talk:Tag:power%3Dcable - discussion about underground only vs insulation.

**Comment by jeisenbe** [comment]
@matkoniecz to clarify your views:

1) Do oppose rendering power=cable (with location=overhead) like power=minor_line?

2) Do you support removing rendering of power=cable, since almost all of these features should be underground and many of the location=overhead examples might be tagged power=minor_line instead?

I am considering submitting a PR which would remove the rendering of power=cable with location=overhead/overground.

**Comment by jeisenbe** [comment]
@matkoniecz ping? Is removing rendering of power=cable our consensus option? @pnorman has given a "thumbs up" to the idea.

**Comment by matkoniecz** [comment]
I would be fine with removing rendering of `power=cable` given that it is not useful for orientation, not something that would be visited or directly used by people, it is not useful for mappers during survey as generally it is not visible.

If mapped - its route would be either guessed or imported so it is also not something that is a good example of strength of OSM data.

Also, its rendering is conflicting with features that are more important going by criteria mentioned (overhead lines, railways, paths, borders, barriers).
