### ISSUE TITLE
Render highways other than residential as areas

### ISSUE THREAD

**Issue by newtestaccount4949** [gravitystorm/openstreetmap-carto#3985]
### Expected behavior
highway=secondary, highway=primary, highway=trunk and highway=motorway render when area=yes is in the tags

### Actual behavior
nothing appears at all

**Comment by jeisenbe** [comment]
@newtestaccount4949 thank you for opening this issue. 

Could you provide a link to an example location where there is a `highway=secondary` or `highway=primary` with `area=yes`?

Usually the tag `area=yes` plus a `highway` area is used to represent a plaza, square or similar feature which allows travel in any direction. The most common use is with `highway=pedestrian`.

Note that there is also a key `area:highway=*` for mapping the area of linear highways. See https://wiki.openstreetmap.org/wiki/Key:area:highway - this is more common for roads which are used by motor vehicles.

**Comment by jeisenbe** [comment]
Related to #1967 and #699
Also see #180 about rendering `area:highway=*`

**Comment by IgorEliezer** [comment]
> Could you provide a link to an example location where there is a highway=secondary or highway=primary with area=yes?

Not the OP, but I have an example of a tertiary area: https://www.openstreetmap.org/way/664093445

Note that I put both `area:highway` and `highway + area=yes` because back then I wasn't sure of how to get it working, now I know they have different purposes.

Perhaps monstrosities like this (https://www.openstreetmap.org/#map=19/52.33492/14.90347) would look better if a single surface could be rendered instead of rendering individual ways in a toll area.

**Comment by jeisenbe** [comment]
Here is aerial imagery of way 664093445 - where a highway=unclassified way meets a highway=tertiary:

<img width="575" alt="Unclassified highway area aerial imagery" src="https://user-images.githubusercontent.com/42757252/70960030-af510e80-2032-11ea-99d5-276be57b7736.png">

<img width="356" alt="unclassified-highway-area-map" src="https://user-images.githubusercontent.com/42757252/70960112-f4754080-2032-11ea-8f23-53558cae5f1c.png">

It doesn't appear that drivers can use this as a multi-directional space, so area:highway would be more appropriate.

Re: https://www.openstreetmap.org/#map=19/52.33492/14.90347 - the second link - this currently looks odd because each lane has been tagged as a separate way:

<img width="560" alt="Screen Shot 2019-12-16 at 18 38 18" src="https://user-images.githubusercontent.com/42757252/70960199-3e5e2680-2033-11ea-88c2-6daf3c8fe3e8.png">

But rendering the whole area as the same fill color would not be an improvement. We can get an idea of how this would look from the current rendering at z17:
<img width="590" alt="Screen Shot 2019-12-16 at 18 40 13" src="https://user-images.githubusercontent.com/42757252/70960311-84b38580-2033-11ea-82f6-454698d9cfbf.png">

**Comment by newtestaccount4949** [comment]
![area 1](https://user-images.githubusercontent.com/58494167/71021650-bb9e9f80-20f6-11ea-8926-21bab8bdc1db.PNG)
![area 3](https://user-images.githubusercontent.com/58494167/71021651-bb9e9f80-20f6-11ea-9dec-90ed36873470.PNG)

**Comment by jeisenbe** [comment]
@newtestaccount4949 thank you for the example. The object shown is appopriately tagged with `area:highway=primary` because it is a linear highway with one-way flow.

Rendering of `area:highway` was discussed in issue #180 and declined with this comment: https://github.com/gravitystorm/openstreetmap-carto/issues/180#issuecomment-249563060

**Comment by matkoniecz** [comment]
> It doesn't appear that drivers can use this as a multi-directional space, so area:highway would be more appropriate.

I changed tagging to correct `area:highway`

> @newtestaccount4949 thank you for the example. The object shown is appopriately tagged with area:highway=primary because it is a linear highway with one-way flow.

+1

> highway=secondary, highway=primary, highway=trunk and highway=motorway render when area=yes is in the tags

Is there even single case where such tagging is a correct one?

**Comment by matkoniecz** [comment]
Looking at https://overpass-turbo.eu/s/PhV it seems clear that rendering of `highway=unclassified` + `area=yes` should be dropped as it encourages poor mapping with disjoint road graph like at https://www.openstreetmap.org/way/158049754 .

I went through several examples and every single one was incorrect (I fixed ones except this one linked above)

**Comment by jeisenbe** [comment]
@matkoniecz could you open a separate issue about removing the rendering of `highway=unclassified` + `area=yes`?

@newtestaccount4949 - thank you for bringing up this issue. So far it looks like `area:highway=*` is the accepted tagging for these features, and we have #180 for that tag, so I will close this issue.
