### ISSUE TITLE
Missing comma in fonts.mss may hide Armenian font

### ISSUE THREAD

**Issue by Sjord** [gravitystorm/openstreetmap-carto#3986]
[fonts.mss](https://github.com/gravitystorm/openstreetmap-carto/blob/master/fonts.mss#L80) contains this:

    @book-fonts:    "Noto Sans Regular",
                    "Noto Sans CJK JP Regular",
                    "Noto Sans Adlam Regular", "Noto Sans Adlam Unjoined Regular"
                    "Noto Sans Armenian Regular",
                    "Noto Sans Balinese Regular",

There is no comma between _Noto Sans Adlam Unjoined Regular_ and _Noto Sans Armenian Regular_. The result seems to be that _Noto Sans Armenian Regular_ disappears from the created mapnik.xml:

```
  <FontSet name="fontset-0">
    <Font face-name="Noto Sans Regular" />
    <Font face-name="Noto Sans CJK JP Regular" />
    <Font face-name="Noto Sans Adlam Regular" />
    <Font face-name="Noto Sans Adlam Unjoined Regular" />
    <Font face-name="Noto Sans Balinese Regular" />
```

After adding a comma after "Noto Sans Adlam Unjoined Regular", the Armenian fonts appear in the mapnik XML again.

I am not affected by this issue, and I am not familiar with Armenian mapping fonts. It was just something I noticed while working with these MSS files.

**Comment by jeisenbe** [comment]
Thank you for catching this bug, @Sjord - would you have time to submit a pull request to fix this bug?

Here is a screenshot of Armenia at the moment:

z7
![z7-armenia-currrent](https://user-images.githubusercontent.com/42757252/70396379-57286580-19bd-11ea-80e6-699c4236e07e.png)

z8
![z8-armenia-current](https://user-images.githubusercontent.com/42757252/70396384-6c9d8f80-19bd-11ea-9065-5a946f7efb6d.png)

Compare with this sample of https://fontinfo.opensuse.org/fonts/NotoSansArmenianRegular.html
![NotoSansArmenianRegular Armenian s](https://user-images.githubusercontent.com/42757252/70396390-7c1cd880-19bd-11ea-8cfc-70fde1eae65b.png)

I believe the style has been falling back to Unifont for rendering Armenian characters, but it would be good to fix this bug so that the Armenian characters match the usual style of the Noto font family which is normally used.

**Comment by Sjord** [comment]
> would you have time to submit a pull request to fix this bug?

Yes, I can make a pull request somewhere this week.
