### ISSUE TITLE
render addr:flats same as addr:unit

### ISSUE THREAD

**Issue by richlv** [gravitystorm/openstreetmap-carto#3988]
#264 added rendering of addr:unit.
There are ~170 000 instances of addr:flats, and the usage is very similar to addr:unit.

It would be wonderful to render addr:flats on osm.org same as addr:unit - both to help with spotting mistakes or missing data, and to motivate surveying.

**Comment by jeisenbe** [comment]
This was included in issue #264 but that issue was closed by mistake when addr:unit was rendered. I think we can discuss this here instead

There were also 2 previous PR attempts which were closed because we did not yet have addr:flat in the rendering database: #605 and #1665

Also consider this comment: https://github.com/gravitystorm/openstreetmap-carto/pull/1665#issuecomment-123257745
“ Some things to consider when it comes time:
“what if all the addresses have a flat? Then housenumber/housename wouldn't appear at all. Is this a common situation?
“flat numbers shouldn't be a higher label placement priority than housenumbers. the right approach is probably to filter out flat numbers from the housenumber/housenamelayer, this way if there is a conflict between a nearby housenumber/housename and a flat number, the latter gets displayed.
“Should all three address layers be combined into one?”

**Comment by jeisenbe** [comment]
Also note that addr:flats is not identical to addr:unit - https://wiki.openstreetmap.org/wiki/Key:addr:flats
“ Use addr:flats=* for marking range of numbers of flats behind a door, for example, addr:flats=1-20. If there is gap in numeration, mark numbers and intervals with semicolon: addr:flats=3-7;10;14;16-18.”

**Comment by richlv** [comment]
Thank you for looking into this.
To clarify, this is about rendering `addr:flats`, not `addr:flat` - the latter is not documented and is used only 141 times.

I'd suggest to apply the exact same rendering rules for `addr:flats` as for `addr:unit`.
Simpler implementation, simpler maintenance.

**Comment by richlv** [comment]
Also seeking rendering of `addr:flats` in JOSM at https://josm.openstreetmap.de/ticket/18094 .

**Comment by jeisenbe** [comment]
@richlv would you be interested in submitting a [pull request](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md) to address this issue? This would be relatively simple, since you could copy the code currently used to render `addr:unit`

**Comment by Adamant36** [comment]
If @richlv isn't interested in doing a PR for it I'd be willing to.

**Comment by richlv** [comment]
I started looking at the code, but it might take me a bit longer, having never done this.
If you could submit a PR, I would be very grateful.

**Comment by jeisenbe** [comment]
@Adamant36 do you want to submit a PR?

**Comment by Adamant36** [comment]
Sure. I think I need to setup things again though. So it might take a few days.

**Comment by richlv** [comment]
Played around in #4082.
It adds rendering of addr:flats similar to addr:unit.

Not quite sure how useful is it to support all the combinations.
Taginfo said there are 747 instances of both addr:flats + addr:unit used (no idea how many of those have identical values or might have other data issues).
In Latvia, there were very few cases of both addr:housenumber and addr:flats, most were redundant/accidental tagging.

**Comment by jeisenbe** [comment]
Also see #3568

**Comment by jeisenbe** [comment]
See my comment on the related PR: https://github.com/gravitystorm/openstreetmap-carto/pull/4082#issuecomment-605380027

Most usage is in Russia, and most of the rest is in Belarus and Ukraine. This tag is very rare outside of the former USSR, and in other countries it is often used as a synonym for `addr:unit`.

Perhaps this tag is not widespread enough or used consistently enough to be supported by this global map style, at this time.
