### ISSUE TITLE
Render landuse=churchyard like landuse=religious

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3991]
Currently landuse=churchyard doesn't render. It would be good if it rendered like landuse=religious.

**Comment by jeisenbe** [comment]
The term "churchyard" is ambiguous in British English: it can be any area around a church but it is usually a graveyard (cemetry) or burial ground, due to the historic use of churchyards in Europe and Britain.

Cambridge Dictionary (UK):
"an area of land around a church, where dead bodies are buried "

Merriam-Webster (US):
"a yard that belongs to a church and is often used as a burial ground."

However, the wiki page for [landuse=churchyard](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dchurchyard) claims "Used to map the area surrounding a christian church or chapel, particularly when this does not contain a graveyard" - this conflicts with the common English definition of the value.

To avoid ambiguity, mappers can use the two tags [landuse=religious](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dreligious) + religion=christian OR [amenity=graveyard](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgrave_yard) + religion=christian, depending on the situation. These two tags are currently rendered by this style, and they are several times more common than landuse=churchyard, and they are not specific to one religion.

**Comment by Adamant36** [comment]
> To avoid ambiguity, mappers can use the two tags landuse=religious + religion=christian OR amenity=graveyard + religion=christian, depending on the situation. These two tags are currently rendered by this style, and they are several times more common than landuse=churchyard, and they are not specific to one religion.

That's fine. I wasn't aware of the ambiguity. To me it's just a subclass of a religious area that's specific to a religion. Which is kind of how the wiki frames it with "See also landuse=religious, a more general tag with the same purpose, but not related to a specific religion." Unfortunately iD Editor supports both and which gets used when seems to be random. Would you mind at least updating the wiki to make it clear landuse=charchyard is ambiguous and why?

**Comment by polarbearing** [comment]
Indeed churchyard is the duck-tagging style, specific to one particular religion. 
It is good to see that landuse=religious as the neutral tag has developed so well. 
We might open an issue with iD to stop promoting the unstructured one to reduce tag fragmentation.

**Comment by matkoniecz** [comment]
There is a tagging mailing list discussion, not very active but with a clear support for deprecating this tag.

This issue was valuable as it allowed to document more clearly why this tag is undesirable, but I think it should not be implemented.

**Comment by matkoniecz** [comment]
Thanks for a report, I think that `landuse=churchyard` should not be rendered but rather eliminated. I opened https://github.com/openstreetmap/iD/issues/7187 and https://josm.openstreetmap.de/ticket/18469#ticket

Thanks to @jeisenbe for starting tagging mailing list thread.

I also edited https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dchurchyard
