### ISSUE TITLE
Lake Michigan rendering issue

### ISSUE THREAD

**Issue by reschultzed** [gravitystorm/openstreetmap-carto#4007]
I'm not entirely sure if this is the right place to make this report, please point me to a better one if necessary. At various zoom levels, mostly zoom=15+, parts of southwestern Lake Michigan (especially around Milwaukee and Chicago) don't render as water. I was unable to find the same issue elsewhere on the lake, or on the other Great Lakes, but Lake Huron is labeled as "Lake Huron;Lett Island;Parsons Island;Spotted Island;Norquay Island;Greenway Island;White Island", despite the fact that its name in OSM is simply "Lake Huron" as far as I can see.
![image](https://user-images.githubusercontent.com/450459/72685921-5b639a80-3ab4-11ea-80c8-7848e72188dc.png)
![image](https://user-images.githubusercontent.com/450459/72685925-6f0f0100-3ab4-11ea-9a75-3948e64b54dd.png)

**Comment by imagico** [comment]
That is not a style issue.

The first problem is a broken multipolygon which is meanwhile probably fixed.

The second i am not sure about - there is no feature with a name like that in the database any more but triggering a re-rendering of the tile does not change it so there might be a database update problem on the render servers.  In general low zoom tiles are only re-rendered once per month or on style updates.  This style does not generate aggregate names like this on its own so the problem is not here.

**Comment by oinag** [comment]
It was an incorrect name that somehow remained a long time in the database and was fixed a short while ago.
