### ISSUE TITLE
`covered` tagging/rendering for `railway=platform`

### ISSUE THREAD

**Issue by sun-geo** [gravitystorm/openstreetmap-carto#4008]
### Expected behavior
Not sure yet
a) change the rendering colour of objects with tag combination `covered=yes` + `railway=platform` to a average colour between current colour of `railway=platform` and current colour of `covered=yes` + `railway=platform`

b) give an idea how to tag a platform which is partly covered. Maybe assumed from building and `building:part` tagging scheme (even I don't like this scheme) like `railway:part` and so on, or using a relation?

c) ...?

### Actual behavior
Using covered=yes for an partly covered platform shows no rendering at all

### Links and screenshots illustrating the problem
Partly uncovered but not rendered at all:
https://www.openstreetmap.org/#map=18/51.42328/12.22250
https://www.openstreetmap.org/way/103695160#map=18/51.42328/12.22344
As contrast a example of a not covered and rendered platform:
https://www.openstreetmap.org/relation/5755375

![image](https://user-images.githubusercontent.com/47290585/73095615-4d15e400-3ee3-11ea-8c2c-63ef3436d946.png)

**Comment by jeisenbe** [comment]
Welcome, @sun-geo! 

The current rendering hides platforms which are tagged with "covered=yes", because this normally means that the platform is underneath a roof, and the roof will be rendered instead.

Generally the tag `covered=yes` is only used for platforms which are completely covered, though it could be used only on the section of the platform which is under the roof, if the platform has an uncovered section. 

In these cases it might be confusing to show the platform, because it then appears to be rendered above the building or roof. Using transparence or mixing the colors would also cause similar problems, as well as being more difficult to distinguish from the large number of other features which are rendered in this style. 

(For detailed questions about how something should or could be tagged, please discuss at https://help.openstreetmap.org or the [Tagging mailing list](https://lists.openstreetmap.org/listinfo/tagging) or another forum, if the Openstreetmap [wiki](https://wiki.openstreetmap.org/wiki/Key:covered) [pages](https://wiki.openstreetmap.org/wiki/Tag:railway=platform) are not clear. We try not to getting into discussions of how things ought to be tagged here.)

**Comment by jeisenbe** [comment]
The current rendering, which does not show platforms with `tunnel=yes`, `location=underground` or `covered=yes`, began with PR #3162 - this PR was merged without a review or comments by other maintainers, so it's not clear if there was consensus in favor of this change or not.

See also the discussion in the previous issues #2037 and #2504

**Comment by jeisenbe** [comment]
Anyone have comments about this issue or about #3162 and #3421 in general?

**Comment by jragusa** [comment]
Covered platform should be rendered regarding #2475

A very pale colour could be considered for underground platform as in the new version of Apple Map. See these screenshots for example (pink pale stuff): https://twitter.com/SongPKM/status/1229768596617908225?s=20

**Comment by sun-geo** [comment]
@jeisenbe Thanks for your comments. In # 3421 [message](https://github.com/gravitystorm/openstreetmap-carto/issues/3421#issuecomment-425901372) i found a temporary solution by using `covered=partial`.

But maybe it could be interesting to use a mixed colour for `railway=platform` which are fully covered (`covered=yes`)

Btw, randomly i saw it seems that <code><b>high</b>way=platform</code> +`covered=yes` is currently rendered, see example object:
https://www.openstreetmap.org/way/671588469/history (v5)
So what is the difference to not render <code><b>rail</b>way=platform</code> + `covered=yes` but render <code><b>high</b>way=platform</code> + `covered=yes` ?

**Comment by jeisenbe** [comment]
> So what is the difference to not render railway=platform + covered=yes but render highway=platform + covered=yes ?

I agree this does not make sense. It would be easiest to fix by restoring the rendering of railway=platform + covered=yes. 

Would you be interested in submitting a PR to make that change?

**Comment by sun-geo** [comment]
> Would you be interested in submitting a PR to make that change?

I would, but I never did a change of any Github project source code. Seems I'm still good for reporting so far. I would have to fork the entire project first before editing code lines?

**Comment by jeisenbe** [comment]
Forking the project is easy. The download is only a couple dozen megabytes. However, setting up Docker to do test renderings is a little more work, and nearly 1 gigabyte of downloads, mainly shapefiles which are needed to render the oceans and seas. 

But if you are interested in become a contributor here (and perhaps at other open source projects in the future), the steps are described here:

https://github.com/gravitystorm/openstreetmap-carto/issues/3869#issuecomment-574114367

And a more detailed explanation is here: https://github.com/gravitystorm/openstreetmap-carto/issues/3782#issuecomment-495926741
