### ISSUE TITLE
Add rendering for tourism=apartment

### ISSUE THREAD

**Issue by nounours77** [gravitystorm/openstreetmap-carto#401]
Hello,

there is a new key tourism=apartment. Which is similar to tourism=chalet, but likely to be in more crowded areas. I suggest to render it with the same symbol as tourism=chalet, but starting at lower zoom-level.

thanks, nounours77

**Comment by matkoniecz** [comment]
I think that it would be overkill. Such features are not too important and in some areas it would result in a really bad rendering - there are towns where nearly every house rent apartments. airbnb and similar are making situation significantly worse for such rendering.

I propose closing this request.

**Comment by pnorman** [comment]
Usage is also fairly low

**Comment by pnorman** [comment]
I still find the low usage (2.8k) is a concern. I also don't find it as relevant as other tourism features for a general purpose map. A large part of this is relative insignificance on the ground.

Downtown Vancouver has many apartments to rent
![image](https://cloud.githubusercontent.com/assets/1190866/17681798/a6eac1d8-62fc-11e6-8459-d7066df50ca5.png)

I doubt you could see any of these if you were there in person. They'd be unsigned, even inside the building.

**Comment by geowOSM** [comment]
tourism=apartment are particularly **popular and important** in Austria, Germany, Switzerland and parts of northern Italy, but are widely distributed throughout Europe and the world. https://taginfo.openstreetmap.org/tags/tourism=apartment#map

The current usage of tourism=apartment is relatively low, because mappers are massively inclined to use descriptive names and **misuse tourism=chalet** instead to get holiday apartments rendered. 

Examples from Austria and Italy/South Tyrol 
("Ferienwohnung" means holiday apartment)
http://www.openstreetmap.org/#map=19/47.64739/12.20317&layers=N
![osm_apartment_2016-08-16 um 09 49 44](https://cloud.githubusercontent.com/assets/13821303/17691807/ecb7403e-6396-11e6-8738-7037b15512ff.png)

http://www.openstreetmap.org/#map=18/46.68174/11.07463&layers=N
![osm_apartment_it_2016-08-16 um 10 03 46](https://cloud.githubusercontent.com/assets/13821303/17692184/d977f228-6398-11e6-8cac-ee57564fa5fc.png)


The number of the actually existing tourism=apartment are significantly higher than the low usage might imply on first sight. And to my experience they are almost always visible on spot due to outdoor advertising.

I would suggest to render tourism=apartment with the same symbol as tourism=chalet, but starting at a lower zoom-level.

Thanks
geow

**Comment by tyrasd** [comment]
> I still find the low usage (2.8k) is a concern.

Even though the total numbers seem relatively low, mapping of this feature seems to be quite active and anything from stale: 

![taghistory 4](https://cloud.githubusercontent.com/assets/1927298/18207946/9eb044e0-712d-11e6-9fb8-431ed24d2485.png)

**Comment by aceman444** [comment]
Yes, this type of accommodation are also popular e.g. in Croatian places along the seashore, where every other house may rent some apartments (even most of a house may be designated for apartment rentals). They often have names (of the house/villa) and outdoor advertising, so they are visible on the spot. Rendering them would be useful.

**Comment by kocio-pl** [comment]
> I suggest to render it with the same symbol as tourism=chalet, but starting at lower zoom-level.

I like this suggestion - what about z18 for example?

**Comment by geowOSM** [comment]
@kocio-pl  z18 would be fine!

**Comment by pnorman** [comment]
I stayed at a tourism=apartment this SOTM, and I still believe it is something we shouldn't render. The visibility on the ground is very limited, so it doesn't help you with orientation. A specific apartment is unlikely to be a feature you are going to in an area because they have limited size.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 26 set 2016, alle ore 10:36, Paul Norman <notifications@github.com> ha scritto:
> 
> I stayed at a tourism=apartment this SOTM, and I still believe it is something we shouldn't render. The visibility on the ground is very limited, so it doesn't help you with orientation. A specific apartment is unlikely to be a feature you are going to in an area because they have limited size.
> 

yes, it depends;-)
There are nowadays a lot of "invisible" tourist apartments (airbnb, booking etc), and there are apartments with hotel-like signage (i.e. very prominent, especially in remote areas they might be the most significant feature), sometimes even offered by actual hotels (the latter case is not interesting either, because we would already show the hotel).

**Comment by pnorman** [comment]
After reviewing the additional discussion I think the original decision to decline remains the right one.

**Comment by tyrasd** [comment]
@pnorman could you please reiterate what the *original decision* was actually based on?

In my opinion, I think that most (or all?) of the early arguments against rendering these objects have been falsified: For example the low usage numbers (see updated graph in https://github.com/gravitystorm/openstreetmap-carto/issues/401#issuecomment-244398155).

Also, I haven't seen any example of where:

> it would result in a really bad rendering [because of too high density of markers]

As far as I can see, the `tourism=apartment` tag is currently not really used to map airbnb-style apartments, but much more often for "serious" tourism businesses (which typically *do* have a name/sign on the building, own websites, proper contact information, etc.). Actually, I think that it would not even make sense to map *unsigned (even inside the building)* apartments-for-rent, because that would simply be against OSM's on-the-ground rule!?

I find the current situation very annoying where people [continue](http://www.openstreetmap.org/note/905905) to actively misuse other tags such as `tourism=guest_house` to map this kind of tourism businesses.

**Comment by dieterdreist** [comment]
sent from a phone

> On 5 Mar 2017, at 18:26, Martin Raifer <notifications@github.com> wrote:
> 
> Actually, I think that it would not even make sense to map unsigned (even inside the building) apartments-for-rent, because that would simply be against OSM's on-the-ground rule!?


I'm not sure if it makes sense to map them, but it wouldn't be against the on the ground rule, as long as there are tourist apartments, signed or not.

**Comment by tyrasd** [comment]
…but if it's not signed, you cannot find out if there is actually a tourism apartment or not (except for checking on the airbnb website which is of course no viable source for OSM). One mapper might have stayed at such an "invisible" apartment, but others cannot verify it on the ground -> ergo it should not be mapped. Isn't that one of the basic working rules for mapping?

**Comment by geowOSM** [comment]
> In my opinion, I think that most (or all?) of the early arguments against rendering these objects have been falsified: For example the low usage numbers (see updated graph in #401 (comment)).

+1 According to [taginfo](https://taginfo.openstreetmap.org/tags/tourism=apartment) by today there are 5.4 k occurrences in the db.  

Both of the main editors (iD and JOSM) provide presets for tourism=apartment.

>I find the current situation very annoying where people continue to actively misuse other tags such as tourism=guest_house

+1 Another misused tag to get it rendered is tourism=chalet, like [here](http://www.openstreetmap.org/note/892081)

So I would deeply like to ask for rendering!

Thanks for considering
geow

**Comment by dieterdreist** [comment]
sent from a phone

> On 5 Mar 2017, at 19:05, Martin Raifer <notifications@github.com> wrote:
> 
> …but if it's not signed, you cannot find out if there is actually a tourism apartment or not (except for checking on the airbnb website which is of course no viable source for OSM). One mapper might have stayed at such an "invisible" apartment, but others cannot verify it on the ground -> ergo it should not be mapped. Isn't that one of the basic working rules for mapping?


we should continue this discussion on talk or tagging, but there are other means of finding it out, e.g. you see new tourists arriving every 3 days, you ask one of them, or they ask you for the way, you ask someone who is living there, ...

**Comment by geowOSM** [comment]
> As far as I can see, the tourism=apartment tag is currently not really used to map airbnb-style apartments,

More than true, actually there is only [a single item](https://taginfo.openstreetmap.org/search?q=airbnb) referring to airbnb. 

tourism=apartment are one (if not) the most popular and important accommodation in Austria, Germany, Switzerland and parts of northern Italy and they are quite visible and verifiable from survey.

**Comment by nebulon42** [comment]
I think there are cultural differences in how important apartments for rent are. I believe the situation is not so much different from Bed & Breakfasts which are part of `tourism=guest_house`. In some countries they are quite insignificant and in others more important. For B&Bs I think there is also often not much signage.

I may be a bit biased because I live and map in Austria, but I also see frequent misuse of `tourism=chalet` when instead `tourism=apartment` should be used. In the Alps especially in some regions apartment houses are quite an important thing.

I don't agree with all the reasons on which the rejection was based and I'm reopening this issue. That does not mean that I don't understand the concerns that the map could be off worse when this is rendered. But I'm not seeing an immediate danger for that so we should try.

What is also clear that this does not need more discussion but more code (which is true in general for osm-carto). And of course a suitable icon, I don't think using the icon for chalet is a good idea.

**Comment by geowOSM** [comment]
>And of course a suitable icon, I don't think using the icon for chalet is a good idea.

With currently more than 8.3k `tourism=apartment` I created a preliminary sample icon (.svg) based on elements from hotel and wilderness_hut, here are the PNGs

14 px   ![holiday_apartment](https://user-images.githubusercontent.com/13821303/29496231-d94fc56a-85ce-11e7-9e54-1e1f09485c05.png)

28 px   ![holiday_apartment-28](https://user-images.githubusercontent.com/13821303/29496282-aa1bf948-85cf-11e7-8bea-8f580b57ef45.png)

Please let me know what you think. 

Thanks.

**Comment by kocio-pl** [comment]
I couldn't recognize beds with 14 px version. Maybe single bed with a roof would be better idea.

**Comment by geowOSM** [comment]
Here you are: single bed with a roof:   ![holiday_apartment_single2](https://user-images.githubusercontent.com/13821303/29496525-83659a2a-85d4-11e7-9f23-ece9312e518f.png)

**Comment by polarbearing** [comment]
Roof does not work, it looks like a homeless shelter. 

The symbol needs to be consistent with other accommodations (which all have roofs):
* Hotel has just a bed, that's a classic. 
* Hostel has a bunk bed.
* Motel has a bed over a car.
* Chalet has a hut with something unrecognisable, ok, the focus is on the hut. 
* Guest house has a bed in front of a house background.
* Wilderness hut has a hut with an oven.

The typical tourism=apartment I know has its _**own kitchen**_ (and often a living room) as a distinguishing factor, all other accommodations make you go to the restaurant.

**Comment by dieterdreist** [comment]
sent from a phone

> On 20. Aug 2017, at 23:41, polarbearing <notifications@github.com> wrote:
> 
> The typical tourism=apartment I know has its own kitchen (and often a living room) as a distinguishing factor, all other accommodations make you go to the restaurant.


+1, although I have recently been to a (relatively new) Hotel in Berlin which offered a guest kitchen for its clients, so maybe there's a segment where things are changing

**Comment by HolgerJeromin** [comment]
There are always exeptions. https://www.openstreetmap.org/way/124775382 is imo clearly a hotel but had kitchens in many rooms in 2011

**Comment by dieterdreist** [comment]
sent from a phone

> On 23. Aug 2017, at 07:15, Holger Jeromin <notifications@github.com> wrote:
> 
> There are always exeptions. https://www.openstreetmap.org/way/124775382 is imo clearly a hotel but had kitchens in many rooms in 2011
> 


anyway, adding a kitchen reference to the bed seems a good idea (if possible with the limited space) to differentiate apartments from hotels and hostels

**Comment by geowOSM** [comment]
> @polarbearing wrote: 
Roof does not work, it looks like a homeless shelter.

A simple roof design is not uncommon for accomodation icons and is easily recognized with limited space.

> @polarbearing wrote
The symbol needs to be consistent with other accommodations (which all have roofs):

Our icons have grown historically, they are not designed from scratch and are graphically not consistent. Actually only 4 out of 7 accommodation icons have roofs or are roof-ish (alpine_hut, wilderness_hut, guest_house and chalet.

> @polarbearing wrote
The typical tourism=apartment I know has its own kitchen (and often a living room) as a distinguishing factor, _all other_ accommodations make you go to the restaurant.

Almost - chalet and wilderness_hut are also self-catering facilities.

> @dieterdreist wrote
anyway, adding a kitchen reference to the bed seems a good idea (if possible with the limited space) to differentiate apartments from hotels and hostels

I agree! It's not easy to squeeze something self-explanatory into 14px. Here's another try, can you recognize the cooking zone?  ![holiday_apartment_kit2](https://user-images.githubusercontent.com/13821303/29637808-97db3982-8855-11e7-86e4-d27943618a23.png)

**Comment by kocio-pl** [comment]
I can't, but maybe a roof should just have a chimney (like wilderness_hut)?

**Comment by geowOSM** [comment]
IMHO wilderness_hut is by far the best accommodation icon! The chimney-oven-combo is beautiful and consistent. But for a normal house or building a chimney is far less characteristic and adds clutter, specifically with 14px.

**Comment by dieterdreist** [comment]
sent from a phone

> On 23. Aug 2017, at 23:13, geowOSM <notifications@github.com> wrote:
> 
> IMHO wilderness_hut is by far the best accommodation icon! The chimney-oven-combo is beautiful and consistent. But for a normal house or building a chimney is far less characteristic and adds clutter, specifically with 14px.


+1, modifying the house puts emphasis on the building, while apartments usually are only a part of the building.

**Comment by geowOSM** [comment]
FYI, came across this, at least a plain cs comment
http://www.openstreetmap.org/node/4319738851

**Comment by kocio-pl** [comment]
That's just bad tagging (for rendering).

**Comment by geowOSM** [comment]
Of course, I am well aware that mappers abuse hotel/guest_house/hostel/chalet/motel.... just to get holiday apartments rendered, but rarely use such a strikingly honest comment 😉

So what might the next steps be toward an improvement?

**Comment by my-na-me** [comment]
Any update to render these (tourism=apartment) category?
Jan. 10th 2018 status:
https://taginfo.openstreetmap.org/tags/tourism=apartment
more than 14k osm-elements

**Comment by kocio-pl** [comment]
I guess we still need a proper icon.

**Comment by my-na-me** [comment]
Hi kocio-pl - thanks for reply.

I agree polarbearing: "Roof does not work, it looks like ...." anything else.

 geowOSM first proposal: 

![apartment-icon-with-roof](https://user-images.githubusercontent.com/27923772/34806897-f93c445c-f685-11e7-8a13-60460bcff7a7.jpg)

.

  
  
OK, simple modification to this proposal:

![apartment-icon-no-roof](https://user-images.githubusercontent.com/27923772/34806905-01a3e5dc-f686-11e7-9902-b2e182a9efa4.jpg)

**Comment by HolgerJeromin** [comment]
@my-na-me These icons are 28x28 but we need 14x14 pixel :-(

**Comment by my-na-me** [comment]
28²:
![apartment-icon-no-roof](https://user-images.githubusercontent.com/27923772/34822157-3afac806-f6c6-11e7-9df8-8dee31e33af7.jpg)

14²:
![apartment-icon-no-roof_14x14-2](https://user-images.githubusercontent.com/27923772/34822340-e4a5e070-f6c6-11e7-8a2b-fc6c7055ea91.jpg)

**Comment by polarbearing** [comment]
Have added the current svg views to my [post from 20 Aug 2017](#issuecomment-323613843) for quick comparison. 

The two beds in 14x14 are not recognisable. 

Following the guest_house having one bed with grey hut behind, I suggest a single bed with a grey horizontal line above and below, symbolising the apartment block around.

**Comment by geowOSM** [comment]
Far out in the uncharted backwaters of the near infinite OSM universe might be a creative and skilful person with a convincing self-explanatory 14x14 px icon. Please spread the word!

**Comment by polarbearing** [comment]
@geowOSM - Sarcasm does not help to solve the issue.

**Comment by kocio-pl** [comment]
What if we reuse guest house icon - or make them a bit different (just modify it slightly or use different initial zoom level)? If "people continue to actively misuse other tags such as tourism=guest_house to map this kind of tourism" it may mean that they are somewhat similar - and they probably are. Misuse of tourism=chalet likely occurs because the mentioned apartments are in Austria and Italy/South Tyrol, so it's just a coincidence based on location (mountains).

In the background we might also show a window, which relates to a room (instead of a house). That would be using principle of similar look for similar objects when absolute recognizability is hard to achieve (and I can show pretty much examples already where our symbols are not guaranteed to be understood without a context or just familiarity with this style).

What do you think?

**Comment by kocio-pl** [comment]
JOSM for example used an entrance in the background, which is also a part of the building (like window), so the basic concept seems to be the same: 

https://github.com/openstreetmap/josm/commit/d7d199612de2678b84e275728dd4d2c3b7d0ec16
https://github.com/openstreetmap/josm/blob/master/images/presets/accommodation/apartment.svg

**Comment by kocio-pl** [comment]
BTW (see https://github.com/gravitystorm/openstreetmap-carto/issues/401#issuecomment-323613843 ):
> Chalet has a hut with something unrecognisable, ok, the focus is on the hut.

That's supposed to be a mountain peak. It's the same shape we use for peaks, so in theory it matches best practices, but one could also make it less regular (for example two peaks with different height) to make it more apparent, because it's not so much clear currently.

**Comment by polarbearing** [comment]
this way you can show an svg icon from a repository here inline:
```<img src="https://cdn.rawgit.com/gravitystorm/openstreetmap-carto/master/symbols/hotel.svg">```
So the JOSM icon is: <img src="https://cdn.rawgit.com/openstreetmap/josm/master/images/presets/accommodation/apartment.svg"> which is hard to recognise. 

What about my proposal with the two grey lines ![image](https://user-images.githubusercontent.com/8266355/34857815-1f4c8068-f74d-11e7-8f19-41358ec04ba7.png) ? Not fully self-explanatory, but neither are chalet nor guest house.

**Comment by kocio-pl** [comment]
Thanks, didn't know this! You're right, JOSM was used just as a proof that somebody else thought about using part of the building too.

If window in the background won't work, rendering guest house would be still preferable for me (with z18+ instead of z17+), because this would give us a benefit of "similar but smaller" association.

BTW: your design reminds me that we could make hospital to be more neutral - mirrored red bed in the circle might work.

**Comment by geowOSM** [comment]
> @polarbearing wrote
@geowOSM - Sarcasm does not help to solve the issue.

Sorry, it's not meant sarcastic or arrogant, but there is a serious point. Apparently the participants in this thread are not graphic designers. My intention was, to suggest, that we seek some assistance from outside.

**Comment by polarbearing** [comment]
I'd be not happy with the same icon for guest house and apartment, since the service concept is different. In the guest house you typically get breakfast and room service (just not full hotel attendance), while in the apartment you are on your own once you get the key.
Hm, key... what about a bed and a grey key in the background?

**Comment by kocio-pl** [comment]
> I'd be not happy with the same icon for guest house and apartment, since the service concept is different.

Sure, it's my second choice exactly because they are not the same. However they are similar and if we have no better idea, making a difference by zoom level is still enough for me.

> Hm, key... what about a bed and a grey key in the background?

Yes, that sounds good to me! We would still have house vs room (house vs key) analogy plus we already have a small key element tested and used (bicycle station for example - "renting a bed" also sounds like plausible analogy :smile:), so designing this icon should be easy.

**Comment by matkoniecz** [comment]
> Apparently the participants in this thread are not graphic designers. My intention was to suggest that we seek some assistance from outside.

AFAIK we asked some time ago on mailing list and nobody was interested. If somebody has a good how to encourage people to contribute icons it can be done (or discussed in a separate issue if it involves some changes to a project).

**Comment by polarbearing** [comment]
Added the bicycle key to the drafts above (4) - my favourite so far. The SVGs are in my [gist](https://gist.github.com/polarbearing/d6fcc0becbac190aaa804580d5efc430).

**Comment by kocio-pl** [comment]
Thanks, 4 is exactly what I have envisioned for z18+! Could you prepare a PR with it?

**Comment by geowOSM** [comment]
> If somebody has a good how to encourage people to contribute icons it can be done

If you agree I would like to submit the topic for the next weeklyOSM.

**Comment by matkoniecz** [comment]
> If you agree I would like to submit the topic for the next weeklyOSM.

Good idea, it is better than posting to mailing list (that feels spammy for me to keep doing it again and again) and there is chance that somebody relevant will read it.

In general any feedback is useful (except "why it is not yet implemented" comments or people posting "+1" instead of using reaction feature).

**Comment by kocio-pl** [comment]
I guess we need both icon designers and code newbies (osm-carto is specific project, so even if one knows SQL and git, there's still CartoCSS, cartographic POV and local conventions). There are tons of issues that can be fixed with a little guidance from maintainers mainly by extending/fixing current code, but even small feature takes some time and focus usually and I can't handle more than few of them at once, for example. 

Unfortunately there was no response from new people when I asked lately on Talk list if anyone is willing to join us and learn the basics. So we're still looking.

**Comment by polarbearing** [comment]
Should do, probably, so the skills don't get rusty. 
Does it make sense to create a new directory under symbols to tidy up? There is ```shop``` already, so we could either use ```tourism``` or more specifically ```accommodation```?

**Comment by kocio-pl** [comment]
I guess tidying should be separate (and simple) ticket.

**Comment by dieterdreist** [comment]
sent from a phone

> On 12. Jan 2018, at 04:01, polarbearing <notifications@github.com> wrote:
> 
> What about my proposal with the two grey lines  ? Not fully self-explanatory, but neither are chalet nor guest house.


+1, icon works for me

**Comment by geowOSM** [comment]
> If you agree I would like to submit the topic for the next weeklyOSM.

Got feedback, it's scheduled for the next edition (391).

**Comment by polarbearing** [comment]
@dieterdreist - which one works better for you, the 

 ![image](https://user-images.githubusercontent.com/8266355/34857815-1f4c8068-f74d-11e7-8f19-41358ec04ba7.png) two grey lines or
<img src="https://cdn.rawgit.com/polarbearing/d6fcc0becbac190aaa804580d5efc430/raw/8385f901add6135419f7746f4cb056abd201d3d7/bed_rentalkey.svg"> 4, hotel bed with key from rental_bicycle (mirrored) ?

I spent last night setting up docker/kosmtik, was expecting this a bit more lightweight than it comes.

**Comment by geowOSM** [comment]
@polarbearing 

For me the key in 4 is too vague/unspecific as most forms of accommodation provide you a key.

I like the "bed with two grey lines" for its simplicity, resembling a room or flat.

**Comment by dieterdreist** [comment]
sent from a phone

> On 13. Jan 2018, at 12:42, polarbearing <notifications@github.com> wrote:
> 
>  two grey lines or
>  4, hotel bed with key from rental_bicycle (mirrored) ?


for me both are ok, but I’d prefer the grey lines “box”

**Comment by polarbearing** [comment]
![z19_apartment_choice](https://user-images.githubusercontent.com/8266355/34911750-e6ab5506-f8d0-11e7-98ec-c296ec5b7c2b.png)

**Comment by kocio-pl** [comment]
Key version is more readable for me.

**Comment by polarbearing** [comment]
Any more votes? Looks like a draw currently:
Key @kocio-pl @polarbearing 
Box @dieterdreist @geowOSM

**Comment by nounours77** [comment]
Box +1

**Comment by HolgerJeromin** [comment]
+1 for Light box (right). the dark box is too heavy

**Comment by gc-web** [comment]
+1 for light box right

**Comment by my-na-me** [comment]
Thanks all for following up this ticket, for new fresh ideas and for nice preview picture.

+1 for all three proposals (bed with light box, bed with dark box and bed with key icon)

If I should tell my preferred order of these 3 options, it looks like:
1. key (because for apartment it is more usual that you hold the key for the whole time of rent in your pocket/responsibility. If I'm living in a hotel room, I tend to give the key daily back to reception, for example that they know the daily room cleaning is welcome)
2. light box
3. dark box

**Comment by polarbearing** [comment]
Yes the reasons you name for the key version were what I thought as well. Anyway there were more votes for the box version, which also symbolises the situation well, thus why I made the PR with that icon. 
@kocio-pl - anything else to do?

**Comment by kocio-pl** [comment]
Since PR is ready, somebody needs to look at the code and test it, so now it's work for repo maintainers.

**Comment by matkoniecz** [comment]
For potential visitors from WeeklyOSM: rendering is added in https://github.com/gravitystorm/openstreetmap-carto/pull/3024 - but if anybody has idea for a new, better icon of this object or any other - please open a new issue ( https://github.com/gravitystorm/openstreetmap-carto/issues/new )
