### ISSUE TITLE
To OSM Carto developers: Regarding OSM Azerbaijan map

### ISSUE THREAD

**Issue by doguhan82** [gravitystorm/openstreetmap-carto#4074]
Hello

In this map https://www.openstreetmap.org/#map=7/40.493/47.860

As you can see below, there are some corrections needed I think, which will make it complete:

The borderline which is painted yellow should be removed and put the names of Azerbaycan cities and regions in that area, for example Nagorni-Karabakh must be there. Can this be done ?

<img width="509" alt="76311632-6d0e3500-62e2-11ea-83fe-e6f681ee20f6" src="https://user-images.githubusercontent.com/62017600/76618987-ebfdaa80-653a-11ea-9e1b-1b83cfa0d6c0.png">

Original conversation is in https://help.openstreetmap.org/questions/73358/regarding-very-critical-error-in-azerbaijan-map

Thanks in advance
Doguhan

**Comment by skfd** [comment]
I see that this issue is created based on what somebody recommended on Openstreetmap Help site:
>"What data OSM has" and "how a particular map chooses to display it" are two different things. If you believe that an admin_level=3 border looks too much like an admin_level=2 border at certain OSM Carto zoom levels then please raise that issue with the OSM Carto developers. It's not the first time that that has been mentioned, but please be aware that it is difficult to show every possible nuance on a single map that people will interpret for different things.

**Comment by imagico** [comment]
I can see that on help.openstreetmap.org someone suggested to open an issue here but that was an incorrect suggestion.  There is no problem here with the map style that needs addressing.

The marked boundary is currently an admin_level 3 boundary (https://www.openstreetmap.org/relation/2374762) - i won't comment on if this is correct mapping here, this is something to determine by the mapping community.  These admin_level 3 boundaries are rendered as intended and from what i see the rendering is also up-to-date with the data here.

As far as placenames are concerned - that is a matter of the size of these places (place class and population) and (at z8+) also a matter of #1391.

**Comment by jeisenbe** [comment]
Hello, @doguhan82. This github repository is the right place to discuss changes to how features are rendered in the Openstreetmap Carto style, the map style that is used to render the "Standard" layer on openstreetmap.org. 

However, it appears that your concerns are not about this particular map style, but about the information in the Openstreetmap database which was added by local mappers.

Our source of data is the current information in the Openstreetmap database, so the borders, cities and administrative names which are displayed in this style are the ones that are found in the Openstreetmap database at the moment that the tiles are rendered. As mentioned on the Help website, this only happens once a month, normally, for low zoom levels like z7, so changes to the database will not be immediately visible at that level. But if you zoom in to z11, you should see changes sooner.

> The borderline which is painted yellow should be removed

That border is in the Openstreetmap database, so it will be shown in this style. It appears to be a real border which exists in fact, between Azerbaijan (http://overpass-turbo.eu/s/RdA) and the "Artsakh Republic" (http://overpass-turbo.eu/s/RdB). 

Openstreetmap seeks to represent the real-world situation accurately. I don't know much about this area, but according to Wikipedia (https://en.wikipedia.org/wiki/Republic_of_Artsakh): "The Republic of Artsakh ... also known by... the Nagorno-Karabakh Republic is a breakaway de facto state". Since in fact this area is not controlled by the government of Azerbaijan and it functions as an independent country, it can be mapped in Openstreetmap Apparently it is currently mapped as an sub-national region (admin_level=3 rather than admin_level=2 which is used for independent countries).

> put the names of Azerbaycan cities and regions in that area, for example Nagorni-Karabakh

If there are any missing names of cities or places, please add them to the map. You can use the "edit" box on openstreetmap.org and use the iD to add missing towns and villages, and their names.

But perhaps the cities and regions are there, but are using the locally-preferred language (Armenian) rather than Azerbaijani? 

It is normal for the most common local language to be used in the "name=" tags which are rendered for the names of cities and other places. It appears that Armenian is the most common language in this region.

Since these concerns cannot be fixed by changes to this map style (Openstreetmap Carto), I will close this issue, but I'm happy to answer more questions if you need help, here or at https://help.openstreetmap.org/questions/73358/regarding-very-critical-error-in-azerbaijan-map

**Comment by soshial** [comment]
@jeisenbe Dear Joseph, do you mind if I ask additional question?
I understand that this multilingual name problem happens in many places in the world. Is it possible to make a map with JSON regions, that specifies, that Nagorno-Karabakh shows not the `name` tag, but both `name-hy` and `name-az`?

By map with regions I mean something like this: https://osmlab.github.io/editor-layer-index/.
I am asking since in Latvia we also have a region with a local minority language which I'd like to show together with the state official language.

**Comment by jeisenbe** [comment]
> Is it possible to make a map with JSON regions, that specifies, that Nagorno-Karabakh shows not the name tag, but both name-hy and name-az? I am asking since in Latvia we also have a region with a local minority language which I'd like to show together with the state official language.

Are you asking about how to make your own map style which shows these name tags? That question might be off-topic for this repository, but we have discussed it before here: #3870 and #4091 - and there is a branch of this style where it is done for German. You might be interested in https://github.com/giggls/mapnik-german-l10n/issues/18 and https://github.com/giggls/openstreetmap-carto-de/tree/upstream+l10n

Or are you requesting that this map style )OpenStreetMap Carto, which is most prominently used as the “Standard” map style layer on openstreetmap.org) show the different names in Latvia and in Nagorno-Karabakh?

**Comment by soshial** [comment]
@jeisenbe I was thinking of adjusting OpenStreetMap Carto logic for regions that have minority languages, to show several names automatically.

Because currently editors must cram all local names into one field by hand — this is a big pain in the ass and it doesn't look nice, when names are short. Compare two cities with both names in a `name` tag:

![image](https://user-images.githubusercontent.com/100644/106982790-2b9a3a00-677e-11eb-8323-15a269ccfd22.png)

We could specify regions and a list of languages to be used for labels on map, so that everything happens automatically.

**Comment by imagico** [comment]
> I was thinking of adjusting OpenStreetMap Carto logic for regions that have minority languages, to show several names automatically.

That is a perfectly reasonable request.  However at the moment there is no established method in OSM to record what languages are locally used in a country or region to determine what the suitable local form to label features is.  Ideas how to do that::

https://wiki.openstreetmap.org/wiki/Proposed_features/Default_Language_Format
http://blog.imagico.de/you-name-it-on-representing-geographic-diversity-in-names/

so far did not find sufficient support.  That means a map style would need to make assumptions on the locally used languages and hardcode them into the style - which is not compatible with our goals in OSM-Carto.

I would encourage you to try establishing a method for recording locally used languages in OSM in your area and document that and if that is successful i would be in favor of supporting that in OSM (which is technically non-trivial though - so no promises).

In most countries with multiple locally used languages mappers so far have chosen the short sighted route to abuse the name tag to record compound labels ([tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer)) - Like Morocco, Algeria, Ethiopia, Somalia.
