### ISSUE TITLE
Add rendering for boundary=protected_area; class 21

### ISSUE THREAD

**Issue by Caseyb87** [gravitystorm/openstreetmap-carto#4109]
I would like to see rendering for boundary=protected_area class 21 : Community life: religious, sacred areas, associative locations, recreation.

Rendering for this tag was heavily discussed in #603 , however, rendering was not added for this class. Discussion for different styles for different classes also in #3656 

I appreciate class 21 is a diverse class covering a range of OSM features. In [my instance](https://www.openstreetmap.org/changeset/82973329), it has been used to tag a "town green" - a [legally protected space](http://www.legislation.gov.uk/ukpga/2006/26/contents) for recreational use (in the UK). The land is not, however, a park or recreational area in the sense that it is not managed by a local authority. 

Whilst it shares the same legal protection as a "[village green](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dvillage_green)" their characteristics are very different. Additionally, "village green" is a legal status rather than a land use. It seems that current examples of "village green" should really use the boundary=protected_area schema.

Issues:
The name of the area is not rendered. 
The boundary of the area is not rendered.

Suggestions:
Render the name
Render the boundary. In my example, a green boundary (e.g. nature reserve or park) works but I appreciate it may not for other members of this class (e.g. religious). 

![Capture](https://user-images.githubusercontent.com/63111813/78378287-ad529180-75c8-11ea-8393-3624a3c23b47.PNG)

**Comment by jeisenbe** [comment]
I believe this is the link to the feature? 

Freeman's Woods: https://www.openstreetmap.org/way/181597678

It is the patch of woodland and the grass area inside, in the screenshot from the original post.

Tags:
boundary = protected_area
name = Freeman's Woods
note = Application for Town Green (common land) granted by Lancashire County Council on 2020-02-12: https://council.lancashire.gov.uk/ieListDocuments.aspx?CId=1596&MId=10738&Ver=4
protect_class = 21
protection_title = common
protection_title2 = town_green
start_date = 2020-02-10

For this particular example, the current rendering of the woodland area and the patch of grass is a good representation of the actual features on the ground at this location. But I wonder - is "Freeman's Wood" also the commonly-used name for the natural=wood feature which makes up most of this area?

Looking at the tag `protect_class=21`, this includes a wide variety of cultural features: 

"Social-protected-area - Important social interests. Visualize sociopolitical assets: "
"21 - Community life: religious, sacred areas, associative locations, recreation"

That's a very wide variety of features: sacred sites and recreational locations are not very similar. I'm not sure what "associative locations" means: perhaps this is something about a place for community gatherings?

It would not be appropriate to render these features the same as national parks or nature reserves.

**Comment by Caseyb87** [comment]
> I believe this is the link to the feature?

Indeed. Apologies I linked to my edit, rather than the feature itself.

> But I wonder - is "Freeman's Wood" also the commonly-used name for the natural=wood feature which makes up most of this area?

The name covers the whole bounded area - the wood and the grass area. Though this is, of course, specific to my example. Other areas might be totally different. The Wiki suggests some US state parks make use of this tag also.

> It would not be appropriate to render these features the same as national parks or nature reserves.

Agreed - the class is diverse and not all members should be rendered as national parks/nature reserves. 

Is there a more generic "community" colour that could be used for the boundary?

**Comment by pnorman** [comment]
> I appreciate class 21 is a diverse class covering a range of OSM features.

> In my example, a green boundary (e.g. nature reserve or park) works but I appreciate it may not for other members of this class

It sounds like what the tag is used for varies too much to be able to render it with one rendering.

**Comment by jeisenbe** [comment]
There is a proposal to update the sub-tagging for `boundary=protected_area`, to fix problems like the use of numbers instead of English words, and the mixing of different features in one group (sacred religious sites and recreational areas should not be the same feature): 

https://wiki.openstreetmap.org/wiki/Proposal:_Named_protection_class_for_protected_areas

That would provide separate tags for `protection_class=recreation` which might be appropriate for some areas like "commons" in England (though I'm not certain if your particular example is protected for recreation or not?), and "National / State recreation areas" in North America. This is much clearer than protect_class=21, and more specific since it excludes religious / sacred areas. 

Also note that we previously removed the rendering of `leisure=common` which used to be rendered as a green area, like grass or a garden. That was the old usual tag for "common land" in England, but was not well defined and is rather England-specific, so was not appropriate to render like a garden or grass.

**Comment by Caseyb87** [comment]
> It sounds like what the tag is used for varies too much to be able to render it with one rendering.

Two naive questions:

1. Is there a "community" -eque colour scheme in use for other "community" related items/areas on the carto map? 
2. If not, could we not at least render the name and boundary in a non-descript colour (i.e. just black text and a black/grey line for the boundary)?

Otherwise I feel like we're encouraging mapping for the renderer (e.g. adding other tags such as "park" or "recreation ground") or the map is missing important community sites.

**Comment by Caseyb87** [comment]
> That would provide separate tags for `protection_class=recreation` which might be appropriate for some areas like "commons" in England (though I'm not certain if your particular example is protected for recreation or not?), and "National / State recreation areas" in North America. This is much clearer than protect_class=21, and more specific since it excludes religious / sacred areas.

This would certainly make this issue easier to solve. Yes, the area is legally protected for recreation. The problem is that the recreation is more of the form of hiking/bird watching/children building dens etc, rather than ball games etc.

> Also note that we previously removed the rendering of `leisure=common` which used to be rendered as a green area, like grass or a garden. That was the old usual tag for "common land" in England, but was not well defined and is rather England-specific, so was not appropriate to render like a garden or grass.

Yes, I noted that. It's a shame to see this removed but I understand that the tag was being misused outside of the UK. Village Greens, Town Greens, Commons etc are British legal terms that essentially all mean the same thing - areas of land (that can have various characteristics) that are legally protected for public use. 

That's why the protected_class system works well - we can easily fit local/national schemes into it... so long as they're rendered.

**Comment by kennykb** [comment]
On Sun, Apr 5, 2020 at 6:18 AM Caseyb87 <notifications@github.com> wrote:

> It sounds like what the tag is used for varies too much to be able to
> render it with one rendering.
>
> Not quite, exactly.  The last time I looked at the objects,
protect_class=21 was used extensively for recreation areas. It particularly
is used to solve the problem of tagging the ones in North America and
Australia that comprise a mix of developed facilities (playing fields,
picnic grounds, swimming beaches and the like) and back-country areas;
neither 'nature reserve', nor 'recreation ground', nor 'park' is really
appropriate to these.  In practice, 21 means 'land protected for
recreational uses; land use often mixed between "nature reserve", "park",
"recreation ground", "historic site", and occasionally specific features
such as "beach" and even "golf course".'

The typical US 'state park' is just such a mixed-use thing, but all of the
recreational features share a common boundary, and a name, and locals will
expect to see the named entity on a map. It's a concept that's painfully
hard to express in UK English, because the UK plans its land use
differently, and simply doesn't have such things.

There are non-recreational protect_class=21 areas that have been tagged,
but if memory serves, no more than a couple of dozen worldwide. (The last
time I checked, a few ancient churches accounted for most of these.)


> Two naive questions:
>
>    1. Is there a "community" -eque colour scheme in use for other
>    "community" related items/areas on the carto map?
>    2. If not, could we not at least render the name and boundary in a
>    non-descript colour (i.e. just black text and a black/grey line for the
>    boundary)?
>
> Otherwise I feel like we're encouraging mapping for the renderer (e.g.
> adding other tags such as "park" or "recreation ground") or the map is
> missing important community sites.
>

The only reason that a lot of these sites aren't missing from the map is
that those of us who curate them also over-tag with marginally-appropriate
tagging. The practice is 'tagging for the renderer', if you will, but not
committing the real sin of 'lying to the renderer'. Rather, it's simply
using over-broad tagging because more-precise tagging is not yet rendered.

I'm satisfied with the practice for the most part, except for the fact that
we lack a concept of 'recreation area, with a mixture of uses often
encompassing bot back-country (nature reserve) and front-country
(recreation ground, campground, park, beach, golf course, ...) features.'
which is a common land use pattern for recreational lands in the US. I have
heard at length from mappers who claim that the only correct way to map
such a feature is to break it up and map the individual land uses.
Following this advice loses the fact that the uses are all enclosed within
a common boundary and share a common name. The locals will expect to see
that common boundary and common name rendered. For this reason, the usual,
albeit controversial, approach is to tag the whole area with what appears
to be the predominant use.

I don't demand a distinctive rendering for 'mixed use recreation,' but it
would be really nice to have some rendering, rather than have to fudge the
tagging like this.

(Feel free to stop reading here: from here on, I'm delving into details.)


Perhaps the thorniest example that I'm familiar with is Bear Mountain State
Park https://www.openstreetmap.org/relation/6467468 (and the coterminuous
Harriman https://www.openstreetmap.org/relation/4080499 and Sterling Forest
https://www.openstreetmap.org/relation/6437484 State Parks. All are
administered together; the separate naming is a historical artefact). An
outing there could be a sedate picnic by Hessian Lake with a ride on the
carousel; a luxurious brunch and spa treatment at the Bear Mountain Inn, a
swim in Lake Welch, or a pick-up ball game on one of the playing fields.
But it could also be a drive to check out the view atop Bear Mountain;
climbing Bear Mountain afoot on trails ranging from a broad footway with
granite stairs in all the steep parts, to a narrow, rocky path with some
rock scrambling; a day hike to explore the ghost town Doodletown; techincal
rock climbing at The Powerlinez; car camping at Lake Tiorati; or a
strenuous three-day backpack on some of the park's 300+ km of trails. The
tagging of 'nature reserve' is wrong, but there's nothing better. (For this
specific example, I'd consider 'national park', but concede that the ice is
thin.) The land use is higgledy-piggledy. There are youth camps, swimming
beaches, MTB courses, and what-have-you sprinkled throughout, all embedded
in second-growth forest in what, a century ago, was an industrial
wasteland. Despite the heterogeneity, 'Bear Mountain State Park' or
'Harriman State Park' are what the locals will look for first on a map, and
be puzzled not to see them; 'nature reserve' is the nearest thing to the
truth.


I can give a plethora of other specific examples from New York State, where
I actively curate such things. I've lived in several, diverse, other states
(New Hampshire, Illinois, Arizona, California); while the details differ,
the land use patterns are actually rather similar. Many state parks offer
the same problems as Bear Mountain (in miniature; I chose Bear Mountain as
a specific example because it seems to have one of everything!). Other
state lands are, for the most part, more straightforward. Major categories
that I've identified in New York:

State Forest Preserve: These are two _sui generis_ features: the Adirondack
and Catskill Parks. These are unapologetically tagged
'boundary=national_park' because that is the function that they serve.
(They're not Federal because New York State got the idea first, and we
protect them more strongly than the US government protects its national
parks. They're actually enshrined in the State Constitution.) Were they to
need a protect_class, it would be 'protect_class=2'. I've not spotted
anything really similar in other states: the closest thing would have been
the Yosemite Valley and Mariposa Grove, which belonged to the State of
California prior to Theodore Roosevelt's endorsement of the bill that
created Yosemite National Park in 1906.

State Park: In New York, these encompass a mix of things. They are tagged
with protect_class=21, since they're all recreational resources. They're
overtagged with the tag that appears best to describe the predominant land
use: nature_reserve, recreation_ground, beach, golf_course, camping_site,
and even park. (Parks in the UK English sense are vanishingly rare in the
US: landscaping as a medium of public art never really caught on here.)
They're all 'protect_class=21' - except for the handful of undeveloped
parks that really are nature reserves (protect_class=3 or 5 for the most
part)

State Multiple Use Area: These are 'protect_class=21' and are
'recreation_ground'. The difference between these and State Parks is
political and rather complicated.

State Historic Site: Tagged according to function, usually 'museum'.
They're all 'protect_class=22'

State Forest: These are overtagged as 'nature reserve', because 'nature
reserve' can encompass a lot of things. They are all 'protect_class=6'
since one of their purposes is sustainable timber harvesting.

State Wildlife Management Area: All are 'protect_class=4', except for the
special case of the Rosendale bat caves, which is at least temporarily
(since 2009) 'protect_class=1a'. They're overtagged 'nature_reserve'

State Wilderness, Wild Forest, Primitive Area, Canoe Area - All are
'protect_class=1b', and all are overtagged 'nature_reserve'. (The
protection class is debatable for Wild Forest, but in practice these are a
'slightly lower grade' of wilderness, in which mountain biking, float-plane
operations, and motorized access for persons with disabilities may be
allowed. A very few have designated 'highway=track tracktype=grade4 or
grade5' where ATV's or snowmobiles may be operated. The trails, together
with primitive support facilities such as bridges, wells, privies, and
lean-to's, are the only developed features in the WIld Forests.)

New York City Watershed Recreation Area: protect_class=12
protection_object=water. These are tagged 'nature reserve'. They are open
to limited public recreation (many are permit-only, but the permits are
free and easy to obtain) for passive activities such as hiking, bird
watching, fishing, hunting, and non-motorized boating. They are
undeveloped, although many bear signs of former habitation.
'protect_class=12' is unusual enough that I'm reasonably happy with the
'nature_reserve' overtagging, and don't ask for rendering.

There's a whole zoo of other designations, which I'm not going to list here
- this is enough to give the flavor of the decisions.

-- 
73 de ke9tv/2, Kevin

**Comment by jeisenbe** [comment]
Since @kennykb has an active proposal for a new tag, `protection_class=recreation`, to replace `protect_class=21` and because the old tag is not well defined, I will close this issue for now.

If `protection_class=recreation` gets approved and commonly used, or if that tag is rejected and instead `protect_class=21` become more clearly defined and more common, we can reopen this discussion or open a new issue as appropriate.
