### ISSUE TITLE
barrier=hedge + area=yes doensn't fill the polyon

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#4111]
### Expected behavior
Polygon area should be filled

### Actual behavior
Polygon area is transparent

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=19/48.51838/9.05482
![image](https://user-images.githubusercontent.com/2878623/78467891-109c0b00-7712-11ea-8ac2-6e4f6ca22d56.png)

**Comment by HolgerJeromin** [comment]
This was intentional
See #3844 an linked items

**Comment by imagico** [comment]
The reason for the current rendering is that we interpret barrier=* tags on polygons to mean *this polygon is enclosed by a barrier of specified type*.  This is the by far most widespread use of barrier=* tags on polygons.

As is this issue would need to be closed as wontfix because we will not interpret `area=yes` on features to mean something other than that the feature in question being to be imported as a polygon.  In other words:  We will not render barrier=hedge + area=yes differently from barrier=hedge + leisure=playground w.r.t. the barrier tag.

But that is not meant to say that we will not consider changes to the current rendering of barrier=hedge.  As outlined in https://github.com/gravitystorm/openstreetmap-carto/pull/3844#issuecomment-583848782 there are two options i consider to have the chance to reach consensus here:

* remove rendering of barrier=hedge due to the lack of clear and universally agreed on semantics in use.
* interpret barrier=hedge as implying a polygon and as a landcover tag when tagged on a polygon.

If you want to reformulate this issue to pursue either of these options i would support that.  It would still be subject to a discussion of the merits of such a change of course.
