### ISSUE TITLE
The name of a building doesn't show up

### ISSUE THREAD

**Issue by maro-21** [gravitystorm/openstreetmap-carto#4129]
The name of a building doesn't show up
https://www.openstreetmap.org/way/101424849

**Comment by jeisenbe** [comment]
Screenshot:

<img width="760" alt="Screen Shot 2020-04-28 at 21 52 37" src="https://user-images.githubusercontent.com/42757252/80561819-99693800-899a-11ea-879c-4cd314618a00.png">

It appears that the building text is blocked the icons for the doctor's office, Luxmed, which is inside of the building at the point where the label should render.

This is a bit surprising, but because of the odd shape of the building, the label is supposed to appear in the right corner.

At z20 the building name is rendered, on my test server:

![export-5](https://user-images.githubusercontent.com/42757252/80562932-25c92a00-899e-11ea-925a-5c831e177b8c.png)

Unfortunately, with the current tools used to render this style, there is not a good option for adjusting the position of text labels. With a new version of Mapnik it might be possible to use a different label placement strategy (grid) - but this might not work with vector tiles

We could adjust the priority of building names to be higher than doctor's offices, but in that case the doctor's office symbol or name would not be rendered.

**Comment by maro-21** [comment]
I added the name of this building and Luxmed at the same time and I thought the name will appear in the middle, so that's why I chose such position for the doctors.
Luxmed is not necessarily at this side, it is inside the building somewhere, so I can move the icon, it doesn't matter where it is. But this doesn't solve the issue for other buildings with similar shape.

I was expecting the name to appear in the middle. Why is it on the right? The building is symmetrical, I think.

**Comment by jeisenbe** [comment]
The name label for buildings (and other polygons with a text label) is placed on a point which is calculated by `ST_PointOnSurface` in PostGIS. Calculating the "center" of a complex area, from a human standpoint, can get quite complex, so to save processing time the algorithm is not so fancy.

https://gis.stackexchange.com/questions/76498/how-is-st-pointonsurface-calculated

"ST_PointOnSurface() works roughly like this, if the geometry is a polygon:"

"Trace an east-west ray, lying half-way between the northern and southern extents of the polygon.
Find the longest segment of the ray that intersects the polygon.
Return the point that is half-way along said segment."

Actual code used is here: https://github.com/libgeos/geos/blob/38b479b73be2535925e268ec6a5a0af0a278f364/src/algorithm/InteriorPointArea.cpp#L163

In the past, the Mapnik "interior" algorithm was used for labels. This sometimes resulted in better label placesments, but other times the placement was worse. Unfortunately, good label placement algorithms are complex and computationally expensive, so they are difficult to use with this map style, which is primarily intended for the standard map on openstreetmap.org, which needs to provides very frequent updates for the whole globe. 

If someone is interested in developing a better algorithm for use in PostGIS, I would be interested in trying that here. But it would need to be not too much slower than `ST_PointOnSurface`.

**Comment by jeisenbe** [comment]
See #3857 to continue discussion about this issue.
