### ISSUE TITLE
Complicated boundary multipolygons refuse to render

### ISSUE THREAD

**Issue by paulw1010** [gravitystorm/openstreetmap-carto#4181]
### Expected behavior
National Forests with extensive checkerboarding and other land ownership oddities render correctly.
### Actual behavior
They are unable to be rendered.
### Links and screenshots illustrating the problem

**Does not render on standard layer...**
 <img width="801" alt="Screen Shot 2020-07-20 at 9 22 31 AM" src="https://user-images.githubusercontent.com/55370518/87942418-8da58300-ca6a-11ea-8927-08cc4579dab7.png">

**But renders on other layers, such as Humanitarian**
<img width="914" alt="Screen Shot 2020-07-20 at 9 22 00 AM" src="https://user-images.githubusercontent.com/55370518/87942486-a7df6100-ca6a-11ea-92b7-a50535ead980.png">

I've had to simplify some national forest boundaries to allow them to render on the standard layer, defeating the purpose of showing private inholdings in the first place. I believe the problem stems from how the style processes [checkerboarding](https://en.wikipedia.org/wiki/Checkerboarding_(land)) of national forest boundaries.

**Comment by imagico** [comment]
This is not an issue for this style.

Background info:  We use osm2pgsql to assemble PostGIS polygons from OSM multipolygon relations.  osm2pgsql will not import most geometrically invalid multipolygon relations.  Although this was not a choice of this style but of osm2pgsql developers we consider this desirable to make life simpler for other data users.  Osm2pgsql changed this some time ago - see https://www.openstreetmap.org/user/imagico/diary/44711 so maps using an older version of osm2pgsql or a different conversion tool show features not visible in the standard style on osm.org.

There are in principle three possibilities here:

* The multipolygon relation is invalid.  Then you need to fix it. See https://wiki.openstreetmap.org/wiki/Multipolygon for what makes a valid multipolygon and what errors can make it invalid and https://tools.geofabrik.de/osmi/?view=areas for a QA tool identifying multipolygon errors.  To practically analyze multipolygon validity in real time while trying to fix it you can also use https://docs.osmcode.org/osmium/latest/osmium-export.html and https://github.com/osmcode/osm-area-tools.
* The multipolygon relation is valid but libosmium fails to correctly build it.  That is unlikely but given the complexity of your relation here it is not impossible.  You would need to check processing it with the latest version of osmium (see above) and if possible reduce it to a simple test case and if a clearly valid polygon does not assemble file a bug report on https://github.com/osmcode/libosmium
* There is a glitch in the database on the OSMF servers.  That is unlikely as well but if the polygon builds fine with osmium then this would be the most likely explanation.

None of these can be fixed in this style so i am closing this issue.
