### ISSUE TITLE
Render watershed protection areas (boundary=protected_area, protect_class=12)

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4201]
Watershed protection areas are defined by boundary=protected_area, protect_class=12.  Currently, protect_class=12 does not render, though most other protect_class values do render.

One example of this type of area is https://www.openstreetmap.org/relation/11163819, which is a watershed protection area around a reservoir that allows NO public access and thus doesn't render.  However, there are also examples of this tag such as https://www.openstreetmap.org/way/481482895 where (e.g.) hunting is allowed.

protect_class=12 is inconsistently used because it does not render, causing mappers use other tags such as leisure=nature_reserve or a different protect_class to demarcate these areas.  However, for areas which have no public access (for strict water protection), the leisure tags are insufficient.

A suggested render for protect_class=12 is similar to landuse=military, except with perhaps a different coloring (perhaps gray or a green; blue would be too confusing against wetland rendering).  This render should be lower in precedence leisure=* tags so as to only take effect for cases where the land is a strict water protection area with no other define renderable usage.

**Comment by jeisenbe** [comment]
We are not likely to render `protect_class=12` because this tag is not well defined. This is a problem with most of the values of protect_class which are not yet rendered by this style. The ones that do render are mostly equivalent to IUCN protection levels, which are at least somewhat systematic.

For the areas that you mentioned which do not allow any access, they may be better mapped as `protect_class=1a` - which is a strict nature reserve. "strictly protected areas ... strictly controlled and limited”. IUCN classes can apply to all kinds of areas, including protected watersheds.

In contrast, https://www.openstreetmap.org/way/481482895 seems to be a "Watershed Recreation Unit” which allows recreational fishing, hunting, walking and perhaps other activities. This is quite different than  https://www.openstreetmap.org/relation/11163819, which "allows NO public access” as you mentioned.

**Comment by kennykb** [comment]
> In contrast, https://www.openstreetmap.org/way/481482895 seems to be a "Watershed Recreation Unit” which allows recreational fishing, hunting, walking and perhaps other activities

I appear to have been the first US mapper to use protect_class=12 on a large scale.  I was following the (rather obscure) guidance of the Wiki. The project was discussed on talk-us and imports at the time.

That part of New York has a about 400 recreation areas preserved in a largely natural state (or being returned to a largely natural state; some are farms that failed a century or so ago and have their buildings fallen to ruin and their pastures grown to trees). They are protected largely to keep them from development in order to protect New York City's water supply, which comes from the mountain streams in that part of the state. They are not strict, or even loose, wilderness; the city, where it deems it safe, occasionally will close one of the areas temporarily and lease it to a timber company for harvest, If I were to force-fit them into the IUCN system, it would be as category VI.

It appears that others saw my example and have emulated it. I suspect - without proof - that the situation in other regions is similar.

https://www.openstreetmap.org/way/481482895 : In the case of that particular area, I was kind of winging it with the access tagging. The city allows walking there only to fish or hunt; one must be in the season for fishing or hunting, and possess an access permit from New York City (the landowner) and the appropriate hunting or fishing license. (Plus the appropriate deer or bear tag in big game season.) That's essentially the strictest classification of the New York City areas. 

https://www.openstreetmap.org/way/424230766 is an intermediate level; foot access is by permit only, but hiking (rather than access to hunt or fish), bird watching, and similar passive activities are allowed.

And https://www.openstreetmap.org/way/424227080 is open to all - no access card required.

(The access card is a minimal formality - it's free, they just want a file of who has them and to be assured that everyone's received a copy of the rules.)

(There's also rowboat, kayak, and canoe access to some of the areas, but the rules are complicated)

There are a bunch of New York City watershed units that are 'no public access', and I haven't mapped them at all - considering them to be little different from privately-owned cadastre, which I also don't map. I haven't mapped the boat-only-access ones, either, simply because I don't have good machine-readable data sources for them and don't want to make work for the already-overburdened GIS people at the Bureau of Water Supply.

I have no idea what the corresponding situation in Massachusetts is, and had no role in mapping those areas.

For the New York City areas, I overtagged 'leisure=nature_reserve' because at the time that I put them in, there was no rendering of protected areas at all, and because their significance to the map is chiefly in the recreational opportunities that they offer. I've kept records of what I did on those, and if there were ever a convincing reason to do so, I could manage a mechanical edit to revise the protect_class (likely from 12 to 6) with relatively little effort.

**Comment by Adamant36** [comment]
> We are not likely to render protect_class=12 because this tag is not well defined. This is a problem with most of the values of protect_class which are not yet rendered by this style. The ones that do render are mostly equivalent to IUCN protection levels, which are at least somewhat systematic.

From what I remember watersheds themselves aren't really well defined either and there's hardly a use case of mapping them general map consumers that I can think of. Unless they are the same area as something like a nature reserve etc like in the examples by kennykb, but then it would be better just to map the area as whatever the tag would be in those situations. Outside of that, I view them similar to bays or the similar ill defined things that are likely problematic to render.

**Comment by ZeLonewolf** [comment]
> From what I remember watersheds themselves aren't really well defined either

A _watershed_ is simply the area that drains into a body of water.  That is not what is being described here.

There are very well-defined areas ([for example](https://upriseri.com/wp-content/uploads/2019/02/2019-02-16-Scituate-Reservoir-08.jpeg)) which are explicitly prohibited access for public water supply protection.  Some areas take their clean drinking water more seriously than others!

In any case, if you actually read the IUCN definitions, this case is perfectly covered by protect_class=6 (which is what I've now tagged the specific area in question).  IUCN Class VI includes areas set aside for preservation of natural resources, which is exactly what a watershed _protection area_ is.

I have come to understand that the protect_class values outside of 1a, 1b, and 2-6 were simply a half-baked invention by wiki authors, and the renderer is correct to not render them.
