### ISSUE TITLE
Is there a way to update for a specific layer without having to reload the map tiles each time?

### ISSUE THREAD

**Issue by kevjp** [gravitystorm/openstreetmap-carto#4207]
Hi
I would like to display the location of specific agents in real time (or pseudo-real time as it relates to a simulation) on a map. I am happy to begin with to explore movement of the agents within a specific set of bounds so the zoom and area of the map can stay constant. Is there a way of being able to update the page with the new locations of the agents without having to render the tiles for the whole map each time. I have been able to add a layer relating to the agents which appends to the project.mml file (although there may be a more appropriate way of doing this - I am pretty new to openstreetmap-carto). This allows me to plot the agents on the map. I have a second container which calculates the new location for each agent which updates the project.mml file and this is eventually updated on the rendered map. However the rendering is not fast enough to show the agents moving across the map. I think if I could update the map with just the layer relating to the agents location it should speed things up significantly.

**Comment by jeisenbe** [comment]
Your question is not specific to this map style. I expect that you will the best results, as you have conjectured, by rendering the “location of the agents” separately from the rest of the map. I suggest searching https://help.openstreetmap.org and if you do not find an answer to your question, then try asking for help there, or also on the [Dev mailing list](https://lists.openstreetmap.org/listinfo/dev) for OpenStreetMap developers.

I will close this issue, because this github repository is for issues and problems with the OpenStreetMap Carto style, specifically.

**Comment by kevjp** [comment]
Thank you for responding to my query and for redirecting me to https://help.openstreetmap.org
