### ISSUE TITLE
Show both name and housenumber when there's no POI-specific icon available

### ISSUE THREAD

**Issue by Mannivu** [gravitystorm/openstreetmap-carto#4216]
At the moment, Carto shows only the `addr:housenumber` value when there's no specific icon for a POI. However, this can be really hard for those users that know a POI is around a certain area, they no the POI's name but don't know the address. So, showing the [name](url) value (maybe something like "_Name; housenumber_" or "_Name`<br/>`hosuenumber_") would be really useful.

**Comment by jeisenbe** [comment]
This issue is similar to #962.

We do not show the `name=*` tag for all `building=*` features. Only `addr:housename` is shown for the rare cases where a building as a name used as the mailing address or physical address, rather than a number. 

This is intentional, because showing the `name=*` tag for all buildings will often show the name of a type of feature which is not otherwise supported or rendered in this style. If we show the `name=` tag in all cases, mappers would be likely to start adding this alone without adding a proper tag for the feature. (See for example #288)

In the past this style used to show many features via “catch-all” renderings, but there was an intentional move to only render specific features (See #1 and #240, and also #3730).

**Comment by jeisenbe** [comment]
In our Cartography guidelines, the first purpose of this style mentioned is: 

"It's an important feedback mechanism for mappers to validate their edits and helps to prevent unfavorable fragmentation of tag use.”
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md

So we should not render everything that has a name, because many tags are typos, mis-spellings, or rarely-used alternatives to more common tags. And rendering the name for any tag will lead to mis-tagging of names to get certain text rendered. 

I recommend closing this issue.

**Comment by jidanni** [comment]
All I know is in some cultures that the place is \#768 is more important than that it is whatever shop, in other cultures everybody is too busy to know about house numbers, which are viewed only as important to navigation as e.g., gas meter numbers... unless somebody takes the bold step of also showing them on the map, whereupon the public there would slowly start to grasp their usefulness.

**Comment by Mannivu** [comment]
I can see your point, but I think that on some POIs should display the name instead of the house number. For example, most of the healthcare values don't have an icon so, it would be hard to find them in the map (yes, I know, OSM is a database, but the users should be able to easily find pois in order to fix them).

**Comment by imagico** [comment]
A feature tagged with `addr:housenumber=*` and `name=*` the name has no well defined meaning.  An address has no name.  It could be the name of a building (in which case it would need to be tagged `building=*`) or the name of some other structure/facility present at said address (which would likewise deserve a distinct classifying tag).  We should not just render labels for names tagged with unknown semantics because that would incentivize mappers to label things just by adding name tags without additional semantic information (which is essential for interpreting the data).

Therefore closing this.  If there are specific feature classes that could well be shown with a name label opening a specific issue for those could be appropriate.
