### ISSUE TITLE
Add rendering of healthcare=blood_donation

### ISSUE THREAD

**Issue by TheAdventurer64** [gravitystorm/openstreetmap-carto#4222]
Quick question, why was the rendering for [this approved proposal](https://wiki.openstreetmap.org/w/index.php?oldid=1206637)  never added?

**Comment by polarbearing** [comment]
Apparently the issue opener refers to https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dblood_donation

According to the code, the feature is rendered as a healthcare-coloured dot, see
``` [feature = 'healthcare_blood_donation']``` in amenity-points.mss

Could somebody make the issue title more meaningful, and close for being invalid?

**Comment by imagico** [comment]
Because:

* proposal approval itself has no bearing on this style
* the tag is not very widely used
* it is questionable if this is suitable for rendering in a general purpose map style like this
* we have currently no consensus on the strategy for POI feature additions (#3635)
* a previous addition of rendering of this without consensus in bulk with various other healthcare tags (#3498) was reverted in #3731, see also #4183.

**Comment by crse** [comment]
As for December 2025, the tag is approved and have emerging usage, with 2300+ usage.
https://taginfo.openstreetmap.org/tags/healthcare%3Dblood_donation
