### ISSUE TITLE
Add rendering of aeroway=taxilane

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#4223]
We currently render ```aeroway=taxiway``` as the major aircraft paths, from zoom level 13 with increasing line width. 
```aeroway=taxiway``` has about 4k uses so far, for minor aircraft paths. 
https://wiki.openstreetmap.org/wiki/Tag%3Aaeroway%3Dtaxilane
https://taginfo.openstreetmap.org/tags/?key=aeroway&value=taxilane

I propose to render, with the same colour, from zoom level 15 with a line, visibly narrower than taxiway.

**Comment by imagico** [comment]
There does not appear to be consensus on if and where to use aeroway=taxilane and not aeroway=taxiway.  Also it seems to conflict with the use of aeroway=parking_position (https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dparking_position) on ways which according to the documentation and common practice is used "from the relevant taxiway and to the nose wheel position". See also #3869.  So far the tag seems to be used mostly in Ukraine (more than half of the uses) and very sporadic outside.  Documentation is poor and there are many cases where use is not according to the documentation or inconsistent within an airport (https://www.openstreetmap.org/way/500136192 https://www.openstreetmap.org/way/704711279 https://www.openstreetmap.org/way/756508406).

Therefore suggestion to close this.

**Comment by polarbearing** [comment]
I'm not pushing too hard for it. However, I've seen it being used by mappers in preparation of the BER airport opening (rumours say it might indeed happen this month). Usage seems plausible to me. Also, I'm always skeptical when a small number of incorrect use is taken as argument against rendering.

**Comment by imagico** [comment]
If i am linking to examples that does not mean these are all the cases i found.  They are just meant to illustrate the kind of use i am talking about.  You can easily find more cases using overpass.

I think this is a perfectly valid idea to try improving mapping of airports (though not without issues of course) but at this stage clearly not suitable for rendering here because of the mentioned reasons.

**Comment by polarbearing** [comment]
Could you please kindly elaborate what the specific inconsistency is for the example you gave, and what the proportion is in relation to consistent use? Your examples show different airports, so I cannot deduce inconsistency within one particular airport.

**Comment by jeisenbe** [comment]
The inconsitent usage is that features that small taxiways on the gate side of the airport are most commonly tagged `aeroway=taxilane` at most airports, but at some they are tagged `aeroway=taxilane` instead. In other cases, the way between the parking position and the nearest small taxiway is tagged as `aeroway=taxilane`, but at other airports these same features are tagged as`aeroway=parking_position` ways. 

Perhaps someone can make a proposal to clarify when `aeroway=taxilane` should be used instead of the other two tags, and once that is clear we could support it.

**Comment by polarbearing** [comment]
Thanks. You used taxilane twice in the first sentence, is that a typo?

**Comment by jeisenbe** [comment]
Yes, I’ve fixed it.

**Comment by polarbearing** [comment]
Ok so taxiway is the older tag, taxilane the more recently introduced for a subset of the former. Thus naturally there is a situation when both tags are used for the minor way.

**Comment by Nic787** [comment]
Hi, I was editing an airport and I found out that the documentation and consistency between airport is missing.

First of all, I agree that taxilane should be rendered as a smaller line than taxiway. Taxilane should be used to taxi to parking area (gate, general aviation parking, etc).

Parking position should be added as a point and not a line or shape.

Another inconsistency is to use area=aeroway taxiway as well as the taxiway line, which is redundant in most case, but the documentation is not clear about that.

**Comment by dktue** [comment]
While taxiways have `ref`-Tags, taxilanes don't. Taxilanes connect the parking position to the taxiway. Taxilanes neither intersect multiple taxiways nor any other taxline.

I vote for rendering them.

**Comment by nickvet419** [comment]
Still currently not rendered. example https://www.openstreetmap.org/way/4368904 

More widely used now than in original request.

aeroway=taxilane is used within apron areas inside holding_position:type=movement points. Major airports assign ref to taxilanes for navigating though restricted movement areas. 

Openairportmap renders them corectly, but osm defult map does not. For example.. https://openairportmap.org/KORD#map=13/41.977805/-87.906590

Rendering style would be same color as aeroway=taxiway but a thinner line and zoom like service=parking_aisle roads.

**Comment by nickvet419** [comment]
@imagico can this tag be reopened for rendering?

**Comment by imagico** [comment]
Is there any change in de facto meaning of the tag?  Is there any documented suggestion anywhere of a semantic delineation between `aeroway=parking_position` (#3869, 76k uses on ways, much more widely and much more consistently used) and `aeroway=taxilane`?

**Comment by nickvet419** [comment]
@imagico  I added information to the Taxilane, and Taxiway osmwiki on its definition and it is being used and tagged. 

A taxilane is part of the taxiway system. it is a taxiway used within apron/hangar  "Non-Movement Area" to safely traverse between parking positions and the "Movement Area" taxiways.  

aeroway=parking_position is used only to mark an aircraft parking spot.

**Comment by imagico** [comment]
That does not answer my question.  I am interested in actual use of the tag, not in what people think the tag should be used for.

> aeroway=parking_position is used only to mark an aircraft parking spot.

Evidently not - as can be easily seen by [sampling the data](https://overpass-turbo.eu/?key=aeroway&value=parking_position&type=way&template=key-value-type)

**Comment by nickvet419** [comment]
> I am interested in actual use of the tag, not in what people think the tag should be used for.

Taxilane is a designated path on an airport apron or ramp area used solely for aircraft to maneuver between parking stands, hangars, and the main taxiway system.  https://www.tarmacview.com/glossary/taxilane/ on overpass it looks like it is being mapped correctly. now that the wiki is updated, people shouldn't be misusing it. 

Many ways that should be tagged as taxilanes are still tagged as taxiways because that was the old/only tag used in the past and some are reluctant to use taxilane because it is not rendered. 

> Evidently not - as can be easily seen by [sampling the data](https://overpass-turbo.eu/?key=aeroway&value=parking_position&type=way&template=key-value-type)

A node or way that marks the parking position of an aircraft. Not the same as a taxilane of taxiway.  Look like 99% of them are marked correctly but I don't think parking positions have a need to be rendered on the default map as gate numbers usually do the trick.
