### ISSUE TITLE
Missing icon/label for Give box

### ISSUE THREAD

**Issue by forteller** [gravitystorm/openstreetmap-carto#4227]
### Expected behavior

Show where there are [amenity=give_box](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgive_box)

### Actual behavior

They do not show up at all, so I'm guessing there's no icon for them. Hope you can add this. Thank you so much for your great work!

### Links and screenshots illustrating the problem
![Skjermdump fra 2020-10-19 14-57-19](https://user-images.githubusercontent.com/343561/96453910-6aca6c80-121b-11eb-8119-0ba81f159f41.png)
![Skjermdump fra 2020-10-19 14-57-03](https://user-images.githubusercontent.com/343561/96453914-6bfb9980-121b-11eb-9f69-093a095995cc.png)

**Comment by imagico** [comment]
Thanks for the suggestion.

Less than 100 uses so far, all but a handful in Germany, France, USA and Norway.

Going to close this because lack of clear broad acceptance of the tag by mappers and too little use so far to evaluate mapping quality.

See also #3302 (#1869), #3462 (#1288) - and #3635 regarding the general problem of POI icon additions.
