### ISSUE TITLE
Add rendering for `barrier=yes`

### ISSUE THREAD

**Issue by GoodClover** [gravitystorm/openstreetmap-carto#4229]
### Expected behaviour
`barrier=yes` should render.

### Actual behaviour
`barrier=yes` does not render.

### Links and screenshots illustrating the problem
The tag `barrier=yes`, like many `=yes` tags, should preferably be replaced with a more accurate tag, however it does get used in cases when telling what the barrier is is hard (e.g. from aerial imagery).
Having it not render at all makes it seem like there is no barrier there when there is.

Here is an image of where `barrier=yes` is used to separate gardens, and it doesn't get rendered:
![image](https://user-images.githubusercontent.com/27222523/96657401-0e11a380-133a-11eb-86bc-246bef3fcd79.png)
[view on OSM.org](https://www.openstreetmap.org/#map=19/53.75733/-0.43696)

*I would have made a pr myself if I didn't get lost navigating the code*

**Comment by imagico** [comment]
Rendering of barrier=yes on lines was removed in #1986.

Reasoning from back then still applies IMO:

* tag is essentially undocumented
* its use is strongly discouraged by most mappers
* there are practically very few cases where a mapper can verifiably map a barrier but has no ability to determine the type of barrier.

Most uses of barrier=yes seem to be cases of mapping of plots where the existence of a barrier is inferred rather than observed, often fully enclosing areas which are evidently accessible from the outside.

Suggest we close this as wontfix upholding the decision in #1986.

**Comment by GoodClover** [comment]
1. It's a `=yes` tag, not much needs to be said about what it means.
Anyways, there's a wiki page now: [Tag:barrier=yes](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dyes)

2. I agree with discouraging the use of `barrier=yes`, this applies to any tag of the sort.
But this doesn't mean not to render it because the type isn't known, what if we decided to not render `building=yes`?
Knowing there is a barrier, no matter the type, is good.
Not having it render encourages people to make up a value for the tag so it will appear on the standard layer.

3. I disagree on this, especially for mapping when you are only using aerial imagery it can be hard to tell what it is unless you are blessed with high-res imagery.
![image](https://user-images.githubusercontent.com/27222523/96732821-ad717d80-13b0-11eb-9214-094197ee72f4.png)

**Comment by jeisenbe** [comment]
I agree with @imagico above, and the decision by @nebulon42 and @matthijsmelissen to remove this rendering in #1986 - if mappers survey the areas in question, it is easy to add a more precise value like `barrier=fence` or `barrier=hedge`. Even with good aerial imagery this can often be determined. And if it’s not certain that there is a wall or fence or hedge, then it may not be clear that there is a real barrier instead of a patch of shrubs or a line of posts without any true fence, or even a kerb. 

This means that a feature tagged `barrier=yes` is too ambiguous to be useful for a general map user. Therefore I will close this issue.
