### ISSUE TITLE
Inconsistent fill behavior when large natural=wood area overlaps amenity=university

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4240]
The following relation is a college campus, tagged with amenity=university:
https://www.openstreetmap.org/relation/11546981

It is almost entirely covered by natural land cover, as it is used for ecological research.  There are a number of natural=wood polygons which overlap the campus.  All of these polygons render with a wood pattern and green fill (as natural=wood), with one exception.

The following large polygon also overlaps the university campus.  It is a very large and complex contiguous wooded area, tens of miles long:
https://www.openstreetmap.org/relation/11634595

For that polygon, the broadleaf wood pattern renders, but the green fill does not; the yellow university fill is rendered instead.  

Below is a screenshot of the behavior.
![image](https://user-images.githubusercontent.com/3254090/97793873-6f523600-1bc8-11eb-9b96-71ca8bddeff9.png)

**Comment by jeisenbe** [comment]
We use the size of the polygon to determine the rendering order in the `landcover` layer (which includes natural vegetation and landuse). Larger polygons are rendered first, the smaller polygons are rendered later. If there is overlap, the smaller polygons are shown. Then the patterns are rendered later, in another layer, which ends up on top of all of this. 

This is done because mappers often add small areas inside of a larger feature without creating multipolygons.

So in this case, apparently the smaller `natural=wood` areas are smaller than the `amenity=university` area, so they render on top. But the huge `natural=wood` relation is larger than the university, so it is rendered first and ends up covered by the university.

**Comment by ZeLonewolf** [comment]
Fascinating, and that certainly explains the behavior perfectly.  This layering scheme does open up some interesting tagging for the renderer possibilities where polygons can be subdivided or not based on the mapper's desire for which thing renders on top of which other thing.

**Comment by jeisenbe** [comment]
Re: tagging for the renderer possibilities

Unfortunately, there does not seem to be an alternative which would make that behavior impossible.

**Comment by map-per** [comment]
> Unfortunately, there does not seem to be an alternative which would make that behavior impossible.

One could make tagging for the render impossible by distinguishing between landuse and natural landcover like suggested in #4418
