### ISSUE TITLE
Type=group names not rendered

### ISSUE THREAD

**Issue by atorger** [gravitystorm/openstreetmap-carto#4242]
In my area it's common that small islets or small lakes are grouped together with a single name. In the official maps it's thus printed a single name for all those entities. I've asked how to tag this in OSM, and got the answer to make a relation with "type=group" and name that. I've done that but no name appears in the render.

The image below shows an example from an official government map. The lake on top "Gustav-Adolftjärnen" is named as a single entity, and the two below "Bävertjärnarna" (= "The Beaver Ponds") is named together. As far as I understand a clear use case for "type=group", but it doesn't render.

![image](https://user-images.githubusercontent.com/13962807/97850188-f5b76680-1cf3-11eb-99f1-fc992e982702.png)

**Comment by HolgerJeromin** [comment]
proposed feature with only 92 uses:
https://wiki.openstreetmap.org/wiki/Proposed_features/Group_Relation

**Comment by imagico** [comment]
See also

https://wiki.openstreetmap.org/wiki/Relations/Proposed/Site
https://wiki.openstreetmap.org/wiki/Relations/Proposed/Cluster

Closing due to 

1. Lack of consensus among mappers on the mapping of such concepts.
2. Lack of support for any of these in osm2pgsql and the inherent complexity of supporting recursive relations (i.e. relations that can have relations as members).

See also #3394 (which is about the similar concept of archipelagos - which are however mapped by convention with classic multipolygons).
