### ISSUE TITLE
Remove rendering for tourism=information without supported value of information=*

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#4247]
### Expected behavior
* The tag `tourism=information` can be used for a wide variety of barely-related features. 
* 93% of features have the key `information=*` which more clearly specifies the feature. 
* The most common values are already supported with specific icons in this style: information=guidepost is most common, followed by information=board,   information=map, information=office. A tourism office is quite different from a guidepost or a public map and should not be confused. 
* Therefore, we should not be showing a symbol for features missing information=* or features with undocumented values of information=*

### Actual behavior
* We are rendering a non-specific “i” icon for all `tourism=information` objects
* This includes misleading uses such as `information=route_marker` and `information=trail_blaze` - the later appears to be a simple cut or paint blotch on a tree which helps mark the location of a rural pathway or trail, though it’s undocumented. See https://taginfo.openstreetmap.org/keys/information#values
* We are also rendering this symbol for the 7% of `tourism=information` objects which have no sub-tag, and could be anything from a guidepost to a visitor centre to a tourism office or a public map. 
 
### Examples with location

https://www.openstreetmap.org/node/7656793394
<img width="630" alt="Screen Shot 2020-11-07 at 12 05 41" src="https://user-images.githubusercontent.com/42757252/98450498-fd12b180-20f1-11eb-9989-a7d3bf32fa6f.png">

Link to image of this feature: https://images.mapillary.com/6kr3SGuwakA3RAxMDut2Ax/thumb-2048.jpg

https://www.openstreetmap.org/node/929360773
<img width="597" alt="Screen Shot 2020-11-07 at 12 07 58" src="https://user-images.githubusercontent.com/42757252/98450500-01d76580-20f2-11eb-9865-850dfbde3663.png">

**Comment by imagico** [comment]
Good idea.  It is doubtful if information=route_marker and information=trail_blaze should be rendered at all in a general purpose map style and definitely not with the 'i' symbol.

**Comment by lizzyd710** [comment]
Is this still something that is in need of a fix? I'm willing to take a stab at it.

**Comment by imagico** [comment]
Yes, this is definitely something that would be good to have fixed.

**Comment by sfkeller** [comment]
Thank you for your great work.

I like the idea of this issue. But it seems that not all consequences were taken into account.

There is information=visitor_centre, which is very similar to information=office but has a crucial difference, as it is correctly described in the wiki https://wiki.openstreetmap.org/wiki/Tag:information%3Dvisitor_centre .

In my opinion, information=visitor_centre must be represented with an icon as before, like information=office. There are currently worldwide 417 tags "information=visitor_centre" https://taginfo.openstreetmap.org/tags/information=visitor_centre , e.g. here https://www.openstreetmap.org/node/1330855837

That's why I want to open this issue again.

That the representation of "visitor_centre" can be seen also by the fact that the iD-Editor explicitly displays "Visitor Centre" (but then saves the tag information=office) in the feature selection when entering an object: See e.g. here: https://www.openstreetmap.org/node/5806243475 (cf. image below).

Image: 
![grafik](https://user-images.githubusercontent.com/43340/214076972-3746f98d-802a-4e58-9053-63dea84fb192.png)

**Comment by imagico** [comment]
Rendering `information=visitor_centre` in a similar way as `information=office` would be a new issue.  Please open one if you think this should be rendered.

**Comment by sfkeller** [comment]
Thx for your hint. I'll open a new issue.

**Comment by imagico** [comment]
@sfkeller - just a reminder: There is no issue about this yet.

**Comment by sfkeller** [comment]
Thx for reminding: See #4773 now.
