### ISSUE TITLE
Render social centers...

### ISSUE THREAD

**Issue by Ivans-Git** [gravitystorm/openstreetmap-carto#4257]
Could be rendered the same as community centers, better than nothing...

amenity=social_centre

**Comment by imagico** [comment]
See https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dsocial_centre

Documentation and delineation in practical use towards amenity=community_centre and amenity=social facility are poor.

See also:

#3867
#4123
#4199

**Comment by jeisenbe** [comment]
The wiki page for the tag mentions that one should "Also consider using more popular amenity=community_centre or amenity=social facility.” The tag `amenity=social_center` has been used a little under 5000 times. Most were added since mid-2019: https://taginfo.openstreetmap.org/tags/?key=amenity&value=social_centre#chronology - when iD added support, though the maintainers there did not appear to know how the tags were used either: https://github.com/openstreetmap/iD/issues/6077

Though they associated the tag with “American Legion” and the terms: "'terms: event,fraternal,fraternity,hall,organization,professional,society,sorority,union,vetern’” - probably the last was supposed to be `veteran`.

It’s not exactly clear how these differ from `[amenity=community_centre](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcommunity_centre)` or `[club=*](https://wiki.openstreetmap.org/wiki/Key:club)`

The wiki page also suggests seeing the Wikipedia page for “social center” but this redirects to “community center”.

I don’t think we can support this tag until it is more clear when it should be used instead of `club=` or `amenity=community_centre` or `office=` or ` amenity=social_facility`.

**Comment by imagico** [comment]
I concur.

From a map usefulness perspective it seems also rather questionable to render a tag that aggregates public and non-public facilities like this.

**Comment by polarbearing** [comment]
Oh we have a Chrolology tag in taginfo, first time I see that - is that for long already? Hooray anyway.

on topic, I agree with @jeisenbe and @imagico not to render to prevent tag fragmentation.

**Comment by HolgerJeromin** [comment]
> Oh we have a Chronology tag in taginfo, first time I see that - is that for long already? Hooray anyway.

Since about a month:
https://blog.jochentopf.com/2020-11-08-10-years-of-taginfo.html

**Comment by Ivans-Git** [comment]
Why did you decide to make the map less rich? Osmand is a good example, he has a symbol for everything, almost even for what does not exist...

**Comment by imagico** [comment]
@Ivans-Git - different projects have different goals and priorities.  Osmand in particular has the option to turn on and off different parts of the map for the user which makes it very different in nature to this style which produces a static map.

**Comment by polarbearing** [comment]
More specifically for this map style, one of the goals is "to prevent unfavorable fragmentation of tag use". See [CARTOGRAPHY.md](/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md)
