### ISSUE TITLE
render boundary=census

### ISSUE THREAD

**Issue by Korgi2** [gravitystorm/openstreetmap-carto#4266]
Now before this is possibly dismissed let me explain why I think this would be a positive change for carto. The current argument in favor for not having boundary=census be rendered on carto OSM is that they are only arbitrary areas for the purpose of population data and not concrete town/village boundaries. However in practice, the boundaries imported under census do in fact act as a de-facto boundary for many CDP towns, cities and villages. As a result many local councils for these places(at least in Ohio where I am) treat these CDP boundaries as boundaries for towns/villages no different then one mapped under boundary=administrative would be. Another main argument in favor of keeping them unrendered is the potential for inaccuracy due to outdated information. While this is true and many old CDP's need to be updated, Tiger 2015 and the upcoming 2020 census data will provide us and OSM with the newest and freshest information for CDP's overall allowing for a accurate and useful outline. If rendered using the more modern 2015 and 2020 outlines, consumers and users of OSM will have an easier time locating and understanding the boundaries of more then just official cities within the US. On top of this, some CDP's are actually quite large and can be just as large or larger then some of the incorporated settlements within the state or county. Because of this, it is not only inconvenient to keep these boundaries unrendered, it actively is detrimental to the average consumer of OSM in regards to accurate location data. It could easily be rendered as a variation of the administrative dashed line to differentiate itself from the proper "incorporated" communities or could simply share the same dotted pattern.

**Comment by imagico** [comment]
Thanks for the suggestion.

Arguments speaking against it:

* Boundary rendering in this style is already severely overloaded and at times massively affects readability of the map.
* boundary=census is essentially a US-only feature - see https://taginfo.openstreetmap.org/tags/boundary=census#map.
* Data seems to come exclusively from imports meaning mapper feedback has only low significance.
* The idea of mapping boundaries with no practical verifiability on the ground is at odds with some of the basic premises of OSM and as a result we want to and we should be very careful endorsing such practice and thereby take influence on the discourse in the OSM community whether such features belong in OSM or not.  Finding consensus on removing existing boundary rendering in light of that is hard but at least we can try to avoid further adding to the problem.
* Boundary rendering in a world wide map is hard due to the huge variety of boundary concepts and classifications in different parts of the world.  We are due to the technical constraints of a real time updated map further hampered.  Avoiding adding to this problem by rendering more types of boundaries is a prudent strategy.

I do appreciate the sentiment of locals in the US that these boundaries are practically on the same or a similar level of significance as administrative boundaries we do render.  I personally would resolve this by removing rendering of higher admin_level boundaries in this style - but that is unlikely to achieve consensus.

**Comment by StyXman** [comment]
> boundary=census is essentially a US-only feature - see https://taginfo.openstreetmap.org/tags/boundary=census#map.

it's a shame osm.us does not have it's own style, it would be the perfect match for this issue.

**Comment by Korgi2** [comment]
> 
> 
> > boundary=census is essentially a US-only feature - see https://taginfo.openstreetmap.org/tags/boundary=census#map.
> 
> it's a shame osm.us does not have it's own style, it would be the perfect match for this issue.

Really is a shame since its only a few lines to add.

**Comment by matkoniecz** [comment]
> it's a shame osm.us does not have it's own style, it would be the perfect match for this issue.

Yes, that would be perfect place for styling focused on USA-specific features.

**Comment by matkoniecz** [comment]
Important problem with adding country-specific features is that it open gates to far more country specific features what would kill already strained maintainability, legibility, clarity and adaptability.

Making your own version of map style is not easy (I needed about 20 hours of work to run first rendering of empty database when I started), but it is possible.

See https://lists.openstreetmap.org/pipermail/talk-gb/2020-December/025580.html for very useful advice.
