### ISSUE TITLE
render housenumbers in buildings when using name or poi-tag

### ISSUE THREAD

**Issue by thomasschmiedl** [gravitystorm/openstreetmap-carto#4271]
Hi,

I am a hobby homeland researcher and have recorded old maps in the region of my ancestors with JOSM. Now I want to render with Mapnik (openstreetmap-carto-style).

How do I have to adapt the CartoCSS so that house numbers (addr: housenumber) are always rendered with buildings (polygons). Even if a name and an additional poi-tag (e.g. shop, amenity or tourism) are added to the building-polygons.

Thank you, Thomas

**Comment by matkoniecz** [comment]
You can use a separate layer, see `amenity-low-priority`

**Comment by jeisenbe** [comment]
As @matkoniecz mentions you might want a separate layer, but if you want to prioritize housenumbers over rendering of names of buildings and POIs, the easiest option is to put the housenumber layer earlier in the project.mml file.

Unfortunately this will sometimes block the rendering of the building name or POIs in the building. There are ways to get around this by using shields or moving the numbers or text around to different locations, but it will never be perfect, as long as you are placing the labels and icons automatically. 

Since this issue is not about this particular map style, I am closing this issue. If you need more help, try https://help.openstreetmap.org and perhaps the developer email list (https://lists.openstreetmap.org/listinfo/dev).
