### ISSUE TITLE
service should render above pedestrian

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#4289]
### Expected behavior
highway=service should render above highway=pedestrian
### Actual behavior
highway=service renders below highway=pedestrian
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/95404734#map=18/41.85266/12.41293
![Screenshot 2021-01-19 at 13 36 40](https://user-images.githubusercontent.com/581288/105035632-9b5cb500-5a5b-11eb-9b69-539ee58a75fa.png)
The service roads seem interrupted, but in the data they are not

**Comment by jeisenbe** [comment]
I don’t think this is a renderng problem. 

We render wider highways on top: motorways are the top layers since they are normally the widest, and higher priority in the network.

A highway=pedestrian by definition is a wide road (otherwise it would be highway=footway if it were narrow), and often is a major connection in the road network which has been converted to pedestrian use, while a highway=service is often narrow and always of rather low importance since they are the final connections to a premises or a private building. 

The example above is unusally because there are short segments of highway=pedestrian in the middle of a longer highway=service way. This might be incorrect tagging, since otherwise how do vehicles access the highway=service way which is highlighted? 

Aerial imager of the area above, in iD editor:
<img width="584" alt="Screen Shot 2021-01-24 at 15 51 54" src="https://user-images.githubusercontent.com/42757252/105647680-207d0b00-5e5c-11eb-9828-0d2aa618f3eb.png">

**Comment by dieterdreist** [comment]
the iD image might be misleading, because there is a bridge covering the ground, but the pedestrian size is certainly given at these spots.

**Comment by matkoniecz** [comment]
Contrast with for example https://www.openstreetmap.org/?mlat=41.90051&mlon=12.47174#map=19/41.90051/12.47174

![screen21](https://user-images.githubusercontent.com/899988/106191680-7bd83180-61ab-11eb-8cc0-b4b3b72e6a39.png)

where this new rendering would be worse. Overall, without smart and location dependent (and unfeasible with that technology stack) ordering there will be always some problems.

**Comment by dieterdreist** [comment]
sent from a phone

> On 28 Jan 2021, at 20:58, Mateusz Konieczny <notifications@github.com> wrote:
> 
> Contrast with for example https://www.openstreetmap.org/?mlat=41.90051&mlon=12.47174#map=19/41.90051/12.47174
> 
> 
> 
> where this new rendering would be worse.
> 


it would be worse for 2 and better for 1, the alley cutting through via dei Tre Archi is now interrupted in the rendering but isn’t in reality

**Comment by jeisenbe** [comment]
I think we have to decline this suggestion. As @matkoniecz shows, most often the rendering would be worse with this change, since `highway=pedestrian` is often the main street in a pedestrianized city center, and there may be small service ways or alleys that intersect which should not render above. 

While the original example is a real problem, we don’t have a technically feasible way to fix it.

**Comment by dieterdreist** [comment]
The question is what is worse. Having a service stub going to the center of the road may not be beautiful, but having a service interrupted by a pedestrian where there is actually continuity (my second example close to Mateusz’) is a real problem.
