### ISSUE TITLE
Use short_name for features with undisplayable name field

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#430]
In some places name cannot be displayed as it would collide with icons or other labels. The typical technique on maps created manually it to use some shorter form of name.

It is not possible to easily find shorter form in an automatic way, but some objects have short_name tag. It is not highly popular (used over 20k times - http://taginfo.openstreetmap.org/keys/?key=short_name ), but it probably would change once it is really used.

Examples of where it would be useful:

http://www.openstreetmap.org/?mlat=50.06491&mlon=19.92483#map=17/50.06491/19.92483

https://www.openstreetmap.org/way/157902552#map=15/50.0672/19.9172

https://www.openstreetmap.org/way/157902552#map=14/50.0656/19.9218

https://www.openstreetmap.org/way/157902552#map=13/50.0631/19.9307

https://www.openstreetmap.org/way/102365228#map=15/50.0972/19.9402 ( https://www.openstreetmap.org/#map=15/50.0972/19.9477 )

**Comment by VA00** [comment]
Examples of single-segment streets, where name is not rendered until zoom 17,18 because it is too long:

https://www.openstreetmap.org/way/172987394
https://www.openstreetmap.org/way/172987396
https://www.openstreetmap.org/way/172987388
https://www.openstreetmap.org/way/172987398 

Situation is quite typical in Poland, because of many long forenames and surnames, combined with short streets. Use of short_name for display  is a good idea for them.
