### ISSUE TITLE
Infer platform name from parent relation

### ISSUE THREAD

**Issue by ManDay** [gravitystorm/openstreetmap-carto#4332]
This is potentially an instance of a more general theme pertaining to a larger set of relations types, but just to focus on one example, the `name=*` of the parent `type=public_transport=stop_area` should be transferred to the child `public_transport=platform` node, if the latter doesn't have a `name=*` tag on its own. The ÖPNV renderer from osm.org does this (rendering the stop_area as a whole) well. [Example](https://www.openstreetmap.org/relation/12320416)

**Comment by matkoniecz** [comment]
First question: is it accepted as a valid tagging? In such case I would map anyway names on `highway=bus_stop`

**Comment by jeisenbe** [comment]
I don’t think we currently include this type of relation in the rendering database, if I understand this line correctly. It looks like we only import route, boundary and multipolygon type relations: https://github.com/gravitystorm/openstreetmap-carto/blob/361886107f0423ca90c2f2648fb8bcb68141a0ba/openstreetmap-carto.lua#L329

That would mean that it would not be possible to render this feature without a database reload, were it to be desireable.

**Comment by pnorman** [comment]
We do not render public_transport relations: https://github.com/gravitystorm/openstreetmap-carto/issues/311. In particular we do not render public_transport=platform at all.

For this specific request, public_transport=platform is normally on a node, and with the toolchain we use right now, we cannot do any logic based on node relation members.

**Comment by ManDay** [comment]
Okay, but shouldn't there remain at least an open bug for this? Using `public_transport=platform` instead of `highway=bus_stop` is a new (widely accepted, I suppose, at least it's in the wiki) method to designate a bus stop and, optionally, grouping them by a parent relation is also an available piece of new semantics.

**Comment by matkoniecz** [comment]
If toolchain is fundamentally incapable of supporting it then it makes no sense of having an open issue.

In addition, I am quite dubious is such omitting of name accepted as valid - even among people who want to remove simpler `highway=bus_stop` and replace it by `bus=yes + ...` tagging.

**Comment by aceman444** [comment]
True, the use of stop_area relations is still unclear (e.g. whether it should contain 1 stop + 1 platform, or all stops and platforms with the same name in the same station area), also people give it a name and them put a different name onto each contained platform (e.g. name=1 to render a platform number instead of name (as supposedly it would be too crowded on the default osm.org style (others like OPNV do cope with that fine))). This seems to go against PTv2, but some large stations are mapped like this.
Anyway, OPNVKarte does support stop_area (as said in the report) so it is unclear whether the default osm.org style should handle these specifics.
