### ISSUE TITLE
Rendering style for unpaved / ungraded / track roads

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4337]
A recent and ongoing [discussion](https://lists.openstreetmap.org/pipermail/talk-us/2021-February/020878.html) on talk-us (and subsequent changes to the [highway=track](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack) wiki page) indicated differences in the global meaning of highway=track.  Part of the reason for the difference is that the Carto rendering for highway=track looks and feels like like a dirt road, and reinforces mapper behavior in tagging unpaved, ungraded two-track roads with highway=track.

As an alternative, could we render the track style (specifically, tracktype=grade3-grade5 styling) when it is applied to highway=unclassified or certain cases of highway=service?  That way a mapper could properly tag the surface of a road and have that appear in a logical way in the render without "downgrading" it to highway=track.  That would give a renderable alternative to possibly overbroad interpretations of highway=track.

**Comment by matkoniecz** [comment]
Part of the problem with that solution is that it would further encourage misuse of `highway=track` for unpaved `highway=residential` and `highway=service` :(

I thought about it multiple times and invented nothing useful, except that making "deprecate highway=track" proposal was tempting.

**Comment by ZeLonewolf** [comment]
I realize my original suggestion might not have been clearly stated - I'm suggesting that, for example, a road tagged `highway=unclassified` + `tracktype=grade4` could be rendered in the `tracktype=grade4` style with the brown dashes, rather than the `highway=unclassified` style.

**Comment by imagico** [comment]
highway=unclassified + tracktype=* has 107k uses.

Note that outside the US highway=track and highway=unclassified are used for very different things warranting very different rendering.  We generally render roads primarily on their functional classification rather that physical characterization.

Rendering things with different primary tags that are normally rendered distinctly (highway=track, highway=unclassified) in identical fashion based on the presence of a secondary tag (tracktype=*) would also be confusing feedback to mappers.

This suggestion also kind of clashes with #4322.

Related to #110/#3399/#4137.

**Comment by ZeLonewolf** [comment]
I think the suggested course of action in #4322 is the better idea (using `surface`), and I agree that `tracktype` has too many grades.  So if everyone's on board with that, I'd suggest we close this ticket in favor of #4322.

**Comment by imagico** [comment]
Well - #4322 is only about rendering surface on highway=track, not on highway=unclassified (which is covered by #110/#3399/#4137).

**Comment by jeisenbe** [comment]
Right, I think @ZeLonewolf is really asking for #110 - rendering unpaved roads differently. While #3399 is going for a subtle rendering which still makes it clear that an unpaved `highway=secondary` is mostly a `highway=secondary`, @ZeLonewolf’s suggestion to use a presumably dashed rendering (more like highway=track) for other unpaved roads would make all unpaved roads more similar to each other and less clearly related to the highway classification.

I can certainly see the benefits of doing this from a map usability standpoint in areas where there are a mix of paved and unpaved roads, but getting that right would require a very large effort to re-write all the roads styles. #3399 and #4137, our most recent attempts to render unpaved roads differently, are already quite complicated and difficult to get right. 

Rendering unpaved residential or tertiary highways in an identical style to highway=track is not an option, because it will provide confusing feedback for mappers, with a secondary tag (surface=*) overriding the main tag (highway=) to greatly change the rendering in a non-intuitive way.

**Comment by ZeLonewolf** [comment]
Closing as duplicate of #110 (and others).  If anyone disagrees, feel free to reopen.
