### ISSUE TITLE
Speed camera rendering?

### ISSUE THREAD

**Issue by cicku** [gravitystorm/openstreetmap-carto#4338]
Just wonder if cameras being tagged on the line segment can be rendered?

**Comment by jeisenbe** [comment]
@cicku welcome! 
When requesting rendering for a new feature, please include the precise OpenStreetMap tag which you wish to request. In this case, I believe you are referring to the tag `highway=speed_camera` which is documented at https://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera - correct?

This tag has been used 48k times, almost exclusively on nodes rather than ways or relations. Usage is fairly concentrated in Europe and a few other areas like Japan, Brazil, Malaysia and Iran, perhaps representing real-world distribution or where local mappers have been interested in these, and usage has been growing steadily since 2009. However, it of fairly limited use for a general-purpose map. Perhaps it is more useful for routing applications, though I do not see any projects listed which are currently using this tag, except for iD and Geofabrick, according to Taginfo: https://taginfo.openstreetmap.org/tags/?key=highway&value=speed_camera#projects

**Comment by polarbearing** [comment]
Speed camaras, tagged on highway nodes and enforcement relations, are typically used in routing/navigation software (and indeed they are, e.g. OsmAnd). However I see no value rendering them on a general purpose map. 

@jeisenbe - do you know how the projects tab in taginfo is generated?

**Comment by HolgerJeromin** [comment]
@polarbearing  https://wiki.openstreetmap.org/wiki/Taginfo/Projects

**Comment by Adamant36** [comment]
> This tag has been used 48k times, almost exclusively on nodes rather than ways or relations. Usage is fairly concentrated in Europe and a few other areas like Japan, Brazil, Malaysia and Iran, perhaps representing real-world distribution or where local mappers have been interested in these, and usage has been growing steadily since 2009. However, it of fairly limited use for a general-purpose map.

As far as I know map rendering of speed cameras is illegal in a lot of countries. I know OsmAnd has warning not to enable their rendering in places where it's illegal to. So that could be one of the reasons why they aren't mapped more widely. Also, given the legal issues they probably should not be rendered on the main style. Especially given that there is no option to selectively disable rendering of certain objects based on geographical location or user preference.

**Comment by pnorman** [comment]
> However I see no value rendering them on a general purpose map.

This is my conclusion too.

**Comment by jeisenbe** [comment]
Closing this issue since there are no clear benefits of rendering this feature.
