### ISSUE TITLE
solar plants (power=plant) as multipolygon not rendered on top of fragmented landuse

### ISSUE THREAD

**Issue by vincentvd1** [gravitystorm/openstreetmap-carto#4347]
Solar farms often consist of multiple fields with solar panels. The correct way of drawing them is grouping them in a multipolygon. These solar panels are often drawn on top of for example a grass field. 

### Expected behavior
I expect that that a multipolygon solar farm always renders on top of the landuse (grass in the example case below). 

### Actual behavior
Because the solar farm is fragmented over several seprate grassfields, the solar farm is not rendered above the grass fields because the total multipolygon area is larger than individual grass fields. Normally the render rule is, smaller areas render on top of the larger areas. The total area of the multipolygon is counted. When the multipolygon is removed, all the individual pieces render correctly over on top of the grass fields.

### Links and screenshots illustrating the problem
See here an example.
https://www.openstreetmap.org/#map=18/51.16711/5.95624

**Comment by Adamant36** [comment]
IMO it's pretty questionable that in your example those should be mapped as individual solar "farms" (even with the multiplygon relation) and not just a single solar "farm." The existence of a few track roads between them does not make them different "farms." As it's all still the same compound/object, and there's the "one object, one OSM element" rule. Again this is just my opinion, but you should the whole area as a solar farm and map the individual solar panel areas as such. Since panels alone are not necessarily farms. The larger compound that the solar panels are in is one though.

**Comment by imagico** [comment]
I think rendering works just as intended here.  We explicitly want to support people micromapping landcover within power=plant polygons and the size based drawing order facilitates that. See for example:

https://www.openstreetmap.org/way/775138906
https://www.openstreetmap.org/relation/8941141
https://www.openstreetmap.org/way/22943608

See also https://wiki.openstreetmap.org/wiki/Tag:power=plant?uselang=en#Dispersed_power_plants by the way - if you tag the individual solar generators as power=generator they will show up.

**Comment by WebMaster50** [comment]
But the proposed tagging does not work for all solar farms. Take for example this one below. Because it is seperated by a ditch, I grouped the 2 solar farms into one power plant relation. The outline of the two parts is the same as the outline of the solar panels. Also, I don't want to micromap the solarpanels so the two areas as power=plant seem totally fine to me. It is not rendered though.

Another posibility is that I tag the two fields in the example below as power=generator + ... and group them in a relation with power=plant + ...

https://www.openstreetmap.org/#map=17/52.24401/6.60312
https://i.imgur.com/fixUbUn.png

**Comment by aceman444** [comment]
Yes, if it is a single farm (same operator, same name), then you can group them as one power=plant into a relation, or as a single polygon encompassing both, including the ditch (if it is part of the farm, e.g. is inside the common fence).
The 2 arrays of panels can be tagged as power=generator.

**Comment by WebMaster50** [comment]
Alright, I think it is clear then. In the example above, I just need to add `power=generator + ...` to the areas.

**Comment by rivermont** [comment]
Can this be closed?

**Comment by imagico** [comment]
Yes, thanks.

We have > 400k solar power generators in the database meanwhile btw. so we could consider rendering that in a way that shows the specific type of power generator.  Not with a blocking POI symbol probably but in a subtle way that works well with the various geometries these can have.
