### ISSUE TITLE
Cannot increase street name text-size more than 20px

### ISSUE THREAD

**Issue by EnGoPy** [gravitystorm/openstreetmap-carto#4349]
At the beginning I would like to thank everyone for that great tool for generating OSM tiles.

I have forked openstreetmap-carto project and create my own tile style.
I try to enlarge street name for specific zoom, but it seems that max pixel value of text-size: is around 20 (I write 'around' because it's hard to see differences between 1 or 2 pixels height).
I thought maybe road width value is a "top border" which limits size, but even if I increase that value, street name stays the same.
I edit pure .mss styles files, and I didn't find anything related to this limitations.

What I tried is:
[zoom >= 19] {
        text-size: 23;
      }
Is it some global limitation of Mapnik or it may be related to other values?

### Expected behavior
When I increate `text-size` above 20 than I would like to get exact bigger font.

### Actual behavior
Every `text-size` above 20 stays the same size

**Comment by StyXman** [comment]
Hi @EnGoPy . Here we just discuss the specific issues of OSM's main tile style, but your issue is either with the rendering engine, https://github.com/mapnik/mapnik/; or the carto-css to mapnik-xml converter https://github.com/mapbox/carto. Maybe you can open a issue against them. 

You can also try the developer room at the OSM's international discord. More info [here](https://wiki.openstreetmap.org/wiki/Discord#Servers).

Can we close this? I don't have the rights.

**Comment by EnGoPy** [comment]
Fortunetelly everything works correct. At the end I discovered that another CSS override my previous settings...
My bad.
