### ISSUE TITLE
Volcanic features request

### ISSUE THREAD

**Issue by Nic787** [gravitystorm/openstreetmap-carto#4354]
With the volcano spreading lava in Iceland right now, it's been a mess how it's rendering in OSM.
What I mean is that using bare_rock for lava field just doesn't do it, since we can't really see the difference when it's a lava field inside a bare_rock environment.

I know it has been discussed in the past about using natural=lava, but I think it's something that we need. Currently people are using Geological=volcanic_lava_field, but I don't think it's right for active volcano.

My suggestion : 

- Natural=Lava (No render)
- Lava_type=hot or fluide (Render fill red)
![image](https://user-images.githubusercontent.com/11185348/112566102-bda0e500-8db4-11eb-91e8-879e11be5d7f.png)
- Lava_type=Lava_field (Render like bare_rock or a bit different to differentiate it?)
![image](https://user-images.githubusercontent.com/11185348/112566191-e2955800-8db4-11eb-8a36-06eb474ff294.png)
- Lava_type=solid (Render red dots)
![image](https://user-images.githubusercontent.com/11185348/112566264-02c51700-8db5-11eb-8e2d-ab06a46cb3df.png)

Another thing that could be added is Lava_flow= for the direction of the Lava.

Thank you

**Comment by mxdanger** [comment]
Sorry, but this isn't the place for making tag proposals. None of the suggested tags you mentioned are used anywhere in the OSM database. You may have to close this issue and make a new one once you have an accepted proposal with high tag usage that you can base your issue on.

**Comment by imagico** [comment]
As @mxdanger has already pointed out this is not the right place to suggest and discuss new tagging ideas, see:

https://wiki.openstreetmap.org/wiki/Any_tags_you_like
https://wiki.openstreetmap.org/wiki/Creating_a_page_describing_key_or_value
https://wiki.openstreetmap.org/wiki/Proposal_process

Closing as invalid because of that, suggestions to render tags that are in consistent active use are welcome of course.
