### ISSUE TITLE
Please add render man_made=bridge or relations

### ISSUE THREAD

**Issue by NikolasHuan** [gravitystorm/openstreetmap-carto#436]
Look at this bridge http://www.openstreetmap.org/#map=19/59.94944/30.28617&layers=N
You see 6! of parallel bridges. 

But in reality, there is one big bridge.
https://www.google.com/maps/@59.948502,30.286034,18z
http://maps.yandex.ru/?ll=30.285315%2C59.948903&spn=0.036607%2C0.003939&z=15&l=map%2Csta%2Cstv&ol=stv&oll=30.285315350000005%2C59.948902800000006&ost=dir%3A449.91807102816733%2C-9.790156534541136~spn%3A90.84049622101732%2C41.66051179728965

Please add render man_made=bridge http://wiki.openstreetmap.org/wiki/Key:bridge or relations http://wiki.openstreetmap.org/wiki/Relations/Proposed/Bridges_and_Tunnels

**Comment by daganzdaanda** [comment]
I like @mkoniecz  gray example, but make it even lighter. Maybe RGB CCC, the current colour of the living_street fill, would be good? As it should not get an outline It just needs to be a tiny bit different from landuses, especially residential gray. But it does not need to stand out a lot IMHO.

**Comment by daganzdaanda** [comment]
Just thinking: When we render big man-made bridges, lots of details will be under them. These things should get tagging added (covered=yes) but there might still be new problems showing up. Think of all the open issues about layering order... 
Would it be a terrible sacrilege to try some transparency with bridges?

**Comment by Sundercloas** [comment]
What about mountains and buildings or any underground traffic system ? 
Tag what you see and dont add what is out of sight, without proper levels or layers.

**Comment by RicoZ-OSM** [comment]
@daganzdaanda:

covered=yes is not designed for this use. man_made=bridge + layer should be sufficient to map it.

Rendering is a different story, I think roads, railways etc bellow man_made=bridge could be rendered similar like if they were in a tunnel.

**Comment by kocio-pl** [comment]
Still no action? I think https://github.com/gravitystorm/openstreetmap-carto/issues/436#issuecomment-58668437 proposition is quite reasonable. What are the missing details or still unresolved controversy? 

For me it's important to see the bridges (and viaducts!) how they really are made, not just virtual lanes hanging over the river.

**Comment by gravitystorm** [comment]
> Still no action?

The developers here aren't sitting around twiddling their thumbs wondering what to do next. Please, be patient.

**Comment by kocio-pl** [comment]
Oh, I'm sorry for a rude wording. :((( Unfortunaltely you could understand it this way, however my intention was definitely not "move your *ss!" ;) - the "action" may be actually "decision" as well, because sometimes I don't know what's the current status of the open issue (approved/incomplete/waiting-for-something) and was afraid it's just forgotten.

**Comment by RicoZ-OSM** [comment]
Meanwhile I am working on refining man_made=bridge tagging: 
  http://wiki.openstreetmap.org/wiki/Proposed_features/Simplify_man_made%3Dbridge_mapping

The main rendering related change would be that (during a transition period) ways on a man_made=bridge are tagged with location=bridge + layer=*  instead of bridge=* + layer=*
This should make rendering better and easier at the same time as the thick lines on the sides of the single ways on the bridge would be no longer drawn.

Sometimes in the far future the necessity to tag all ways across a bridge with something like bridge & layer might be dropped altogether if the data can be easily derived from man_made=bridge and common nodes.

**Comment by spectrokid** [comment]
Why not render it in the same way as bridge:support=pier ?  It is about avoiding that roads, cycle lanes and railroads look like they are flying through the air.

http://www.openstreetmap.org/way/206233686#map=19/55.51825/9.71151&layers=D

**Comment by matkoniecz** [comment]
@spectrokid bridge:support=pier is not rendered. In that example building=yes was added to make it rendered (what is http://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer)

**Comment by mboeringa** [comment]
> Next solution, simple gray seems to be acceptable or maybe even optimal.

@matkoniecz , for your reference, from my renderer, here you can see man_made = bridge in an even lighter base grey color:

![arcgis_renderer_for_openstreetmap_man_made_bridge](https://cloud.githubusercontent.com/assets/7635726/8396071/76a3baa4-1d96-11e5-9e38-db3aebfe0399.jpg)
