### ISSUE TITLE
Default style does not show bilingual names of cities, villages etc

### ISSUE THREAD

**Issue by syntex1** [gravitystorm/openstreetmap-carto#4404]
### Expected behavior

The default style should have the ability to show two names in places with bilingual names. It could be done for example by showing the other name just below the other.  Just like it is shown today in the city of Constantine in Algeria (though it was made  by adding two names to the name tag, but this is how it should look like if the deafult style would start to render the second name below the first)
https://www.openstreetmap.org/node/27564946

### Actual behavior

This issue was made after a heated discussion in polish osm forum https://forum.openstreetmap.org/viewtopic.php?pid=829182#p829182, after I have added bilingual names to the village of Puńsk in Poland.
https://www.openstreetmap.org/node/31521038 
The bilingual name is present on the road signs, here is an example:
https://zw.lt:8443/resize/1280x/puńsk-3-e1434098867838.jpg

The conclusion of the discussion was that adding the second name after the first name using "/" or "-" is breaking the data and making it unnecessarily complicated. Though this practice of using "/" or "-" instead is common in many countries for example in: 

Belgium 
https://www.openstreetmap.org/node/1635651356

Germany
https://www.openstreetmap.org/node/1628927045

Switzerland
https://www.openstreetmap.org/node/240097197

Spain
https://www.openstreetmap.org/node/3230345391

Algeria
https://www.openstreetmap.org/node/27564946

Slovenia
https://www.openstreetmap.org/node/1640456909

Also the names of the following countries have more than one name added to the default "name=" tag for example:
Switzerland, Belgium, Montenegro, Bosnia and Herzegovina, Kosovo, Algeria, Cyprus, Ireland, Somalia, Ethiopia, Eritrea, Somaliland, Chad, Central African Republic, Morocco, Iraq and Mongolia
Sub-national: Provinces of Canada, Switzerland, Ethiopia, Chad, Algeria, Italy etc.

I guess adding the option to render two names in the default osm style could fix many of these problems.

**Comment by imagico** [comment]
This is a perfectly reasonable request.  However we can only render what mappers actually consistently map.  And despite repeated suggestions from maintainers of this map style (@jeisenbe [here](https://wiki.openstreetmap.org/wiki/Proposed_features/Default_Language_Format) and myself [here](http://blog.imagico.de/you-name-it-on-representing-geographic-diversity-in-names/)) to separate the mapping of names in different languages from the mapping of the locally used language(s) - which is the prerequisite for us doing what this issue is suggesting to do - there is so far no notable movement among mappers to map things in such way.  At the same time there is - as you describe - a sustained trend to map labeling strings rather than names in the name tag,

I have been considering to suggest us simply stopping to render labels for name tags containing typical characters indicative of the name tag being used to store a compound labeling string rather than an actual name.  But we traditionally do not want to use our influence to steer mappers actively into a certain direction - no matter how clear it is that this would be good for the project.

I would encourage you to work together with other bilingual/multilingual local communities to establish tagging to separately map the names in the different local languages used and to document as well which names/languages are actually used locally.  If such a scheme starts being actively used by local mappers in bilingual areas i would be very much in favor of supporting this by rendering it here.

**Comment by matkoniecz** [comment]
I think that for now it should be closed as sadly there is no accepted or widely used way to mark name as bilingual - except tagging for renderer with incorrect putting multiple names into `name` tag :(

**Comment by imagico** [comment]
Agreed.  If any suitable tagging to document multiple locally used languages gets adopted in bilingual areas please mention or open a new issue for supporting it.
