### ISSUE TITLE
Wrong placement of roads-text-name and roads-text-ref

### ISSUE THREAD

**Issue by alfmarcua** [gravitystorm/openstreetmap-carto#4436]
### Expected behavior
After clone of the master branch and performed an import of data of [the center of Italy](https://download.geofabrik.de/europe/italy/centro.html). Roads labels should not collide neither between them or with its shields.

### Actual behavior
I have observed that there are collisions between roads and roads' shields and between the roads itself.
The test was made in a docker deployment with Kosmtic. I have also tested some releases (v5.3.1, v5.3.0, v5.2.0 and v4.25.0) with the same output.

### Links and screenshots illustrating the problem
Kosmtik comparison view: 
- Left: OpenStreetMap
- Right: master branch of OpenStreetMap-Carto

![road-shield](https://user-images.githubusercontent.com/25908318/124917631-566e1000-dff4-11eb-97bf-a376f2fb4d6d.png)

After hiding the layer roads-text-ref collision between roads can be observed:

![road-road](https://user-images.githubusercontent.com/25908318/124917665-60900e80-dff4-11eb-86d0-5108c26b6c6f.png)

**Comment by alfmarcua** [comment]
I do not know if the reason could relay in the scope of the data. Maybe by taking a small region instead of the whole world, labels are moved and those errors appear.

**Comment by imagico** [comment]
I have troubles parsing your problem description.  The place you are referring to is:

https://www.openstreetmap.org/#map=16/43.6121/13.4127

I see nothing wrong there beyond the problems already documented in #951 and #4401.

If you are concerned about the rendering results in kosmtik differing somewhat from those on osm.org - that is due to kosmtik rendering much smaller metatiles and therefore metatile edge errors being more frequently observed.  Turning on the tile grid display in kosmtik will help you see where this is the case.

The issues with labels  at tile edges is a problem that is generally hard to solve in map rendering and within the limits of our rendering framework and the constraints of a real time map that is not really feasible.

**Comment by alfmarcua** [comment]
Exactly, it is due to metatile edge errors. Thank you so much for your detail answer.

![kosmtic-grid](https://user-images.githubusercontent.com/25908318/125050893-b1f6d700-e0a2-11eb-9403-d01615df05a0.png)
