### ISSUE TITLE
leisure=swimming_pool not visible when overlapping with buildings

### ISSUE THREAD

**Issue by Hufkratzer** [gravitystorm/openstreetmap-carto#4443]
### Expected behavior

[leisure=swimming_pool](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dswimming_pool) + [location=roof](https://wiki.openstreetmap.org/wiki/Key:location#Values) should always be visible on the map (blue). Shouldn't they?

### Actual behavior

Most are visible, but **some are not**, reason unknown (to me)

### Links and screenshots illustrating the problem

Here some invisible pools with location=roof:

1. [pool](https://www.openstreetmap.org/way/822892174) on [building=yes](https://www.openstreetmap.org/way/822892173)
2. [pool](https://www.openstreetmap.org/way/893924424) on [building=yes](https://www.openstreetmap.org/way/892422119)
3. [pool](https://www.openstreetmap.org/way/714953315) on [building=civic](https://www.openstreetmap.org/way/714953314) 
4. [pool](https://www.openstreetmap.org/way/866351164) on [building=yes + building:levels=2](https://www.openstreetmap.org/way/146410605)

**Comment by imagico** [comment]
I suppose what you mean is that buildings are drawn after swimming pools and you think it should be the other way round.

**Comment by Hufkratzer** [comment]
I think the swimming pools **that are on the rooftop of buildings** should be seen on the map because they are also seen on aerial views. (The indoor pools not.) So, yes, probably they should be drawn after the buildings. Isn't this the reason to use location=roof? Or what do you have to add that these pools become visible on the map?

**Comment by imagico** [comment]
We currently do not interpret location=roof on any features an i have not checked if it is used consistently - in general or on swimming pools.  I also have my doubts about the usefulness of adding significant complexity to this style to facilitate a rendering that is rarely of use for map users (since almost all rooftop swimming pools will be private).

**Comment by Hufkratzer** [comment]
@imagico : If you don't want to fix that, I don't really care much. But why then have you recommended to tag indoor pools with "`location=indoor` and possibly `level=*`" in https://github.com/gravitystorm/openstreetmap-carto/issues/3665#issuecomment-459998625? Do these tags have an impact on the rendering in OSM carto? Or should they have it?

**Comment by imagico** [comment]
I think you are overinterpreting what i write.  I advised care when interpreting location=roof and expressed doubt about adding significant complexity to swimming pool rendering in form of a separate layer just for rooftop pools.

Not showing labels for indoor pools is a different matter - although there is competing tagging for that it seems (location=indoor vs. indoor=yes).

**Comment by Hufkratzer** [comment]
> Not showing labels for indoor pools is a different matter - although there is competing tagging for that it seems (location=indoor vs. indoor=yes).

I don't understand this. The `name=*` is also shown for pools tagged with `location=indoor` ([example pool](https://www.openstreetmap.org/way/650049795)) or `indoor=yes` ([example pool](https://www.openstreetmap.org/way/349149615)). `location=*`is used more for pools, `indoor=yes` is used more for pitches ([example indoor pitch](https://www.openstreetmap.org/way/475672138), name visible). Isn't it intended this way?

**Comment by imagico** [comment]
I am talking about the hypothetical option to take into account location=indoor or indoor=yes to show/not show a label for pools.

**Comment by jeisenbe** [comment]
There are only 933 leisure=swimming_pool + location=roof - https://overpass-turbo.eu/s/1big

The main arguement for rendering these seems to be that they are visible in aerial imagery. However, a good map is not like an aerial image. We need to chose which features not to render as well. 

Looking at a few areas with these, they appear to be mostly at private residential buildings, with a few at hotels, so the assumption that these are unlikely to be open to the public is correct. Rendering these would not provide much benefit to general map users. 

Drawing these over buildings only with location=roof would add some complexity to the code and also would make the rendering more confusing for mappers, since it would not be immediately clear why some pools were visibile and others not.
