### ISSUE TITLE
Historic=castle_wall not rendered

### ISSUE THREAD

**Issue by harrija0** [gravitystorm/openstreetmap-carto#4444]
### Links and screenshots illustrating the problem: 
Location of castle: https://www.openstreetmap.org/#map=19/50.15421/7.70513
Wiki to tag: https://wiki.openstreetmap.org/wiki/Tag:historic%3Dcastle_wall

I think this tag could be better used than city walls for everything.  Perhaps add a slight 50% opacity of the border color for area objects.  I have attached a screenshot of JOSM with a custom style for historic=castle_wall that creates a grey fill.
![Burg Rheinfels](https://user-images.githubusercontent.com/43661400/127055219-309b2580-b5d3-449e-9009-83a268e911d4.png)

**Comment by imagico** [comment]
historic=castle_wall is used 438 times, [wall=castle_wall](https://wiki.openstreetmap.org/wiki/Tag:wall%3Dcastle_wall) 2497 times.  Currently use of historic=castle_wall is concentrated on Europe and very often combined with barrier=wall/barrier=city_wall/barrier=retaining_wall.  There does not seem to be a clear distinction (in either use or documentation) between historic=castle_wall and historic=citywalls.

In general i would be in favor of more differentiated rendering of different types and subtypes of wall barriers but this is probably not a very good starting point because there is no well established tagging.

**Comment by harrija0** [comment]
I concur there is not really any differentiation between the tags. But now that historic=castle_walls exists I feel bad misusing barrier=retaining_wall for free standing castle walls.  Many of them do bear the function of a retaining wall. But not all.  Same issue with city wall.  And while we don't tag for the rendering it may help people use the "appropriate" tag if it is rendered.  So I put the request here.  And in an absence of distinction we can possibly render the same as other walls.  A grey fill for areas would be really great and encourage other mappers to use the tag for historic castle walls.

**Comment by harrija0** [comment]
Great.  Thanks for the advice.
