### ISSUE TITLE
[Regression] water=river rendering inner object, rendered as water.

### ISSUE THREAD

**Issue by james2432** [gravitystorm/openstreetmap-carto#4446]
### Expected behavior
![image](https://user-images.githubusercontent.com/498547/127544341-973ad542-4b60-4185-b8b5-353a4f1c0eb2.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/498547/127544245-323901d5-f1f6-4acb-8fe0-b8b21d810235.png)

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/424541845

**Comment by imagico** [comment]
I see nothing wrong in the map at the moment - the water feature in question is https://www.openstreetmap.org/relation/13034298 - your screenshot probably depicts a different and faulty past mapping.

If you observe weird rendering in an area and in the context of recently made edits it is always advisable to wait a bit and see if the weirdness persists as the map is updated.

**Comment by james2432** [comment]
seems to be fixed, 🤷🏻‍♂️🤦‍♂️ Closing

**Comment by Kars-de-Jong** [comment]
I’m still seeing this issue here, no recent edits.

https://www.openstreetmap.org/#map=16/52.6649/6.0638

I find no issues with the tagging, it renders fine in OsmAnd.

**Comment by imagico** [comment]
The area in question seems to render as intended, 

https://www.openstreetmap.org/way/88964139

is a water feature and as such rendered above the landcover layer with the fills for:

https://www.openstreetmap.org/relation/1315379
https://www.openstreetmap.org/way/88964227

Yes, that area contains some weird, redundant/contradicting mapping making it easy to get confused.  But it is generally advisable not to quickly assume there is a bug in rendering, especially not w.r.t. features that number in the millions in the database and hence where correct rendering has been tested really extensively over the years.

If OsmAnd renders this differently that is possibly a bug in OsmAnd - maybe due to continued interpretation [old style multipolygons](https://wiki.openstreetmap.org/wiki/Old_style_multipolygons) - which were abolished in 2017/2018.

**Comment by Kars-de-Jong** [comment]
Ah, OK. I will remove the tags from the outer way (the relation is already tagged). Thanks for your response!

**Comment by Kars-de-Jong** [comment]
Yes, the area renders fine now. Thanks again!
