### ISSUE TITLE
Release 5.4.0 

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#4454]
I plan to make a 5.4.0 release soon, since some changes has been made and not yet deployed for months.

**Comment by imagico** [comment]
I don't mind you making a new release.  But just for info: There are currently three PRs in need of a review by someone other than me (#4331, #4381 and #4384) and at least one that needs testing and review (#4313).  Given that there have not been many changes since the last release it would IMO be good to prioritize clearing up that backlog.

**Comment by pnorman** [comment]
#4467 should make it in if possible pre-release.

Aside from that, I think we have enough stuff for 5.5

**Comment by kocio-pl** [comment]
I don't understand what do you propose right now with #4467 and why do you say about 5,5 when we have 5.4 ahead, could you make it more clear?

**Comment by pnorman** [comment]
Released with db9abe26d70db365a9f58acc62ad344fef4a58d0

**Comment by kocio-pl** [comment]
https://github.com/openstreetmap/chef/issues/450
