### ISSUE TITLE
domain doesn't resolve - naciscdn.org

### ISSUE THREAD

**Issue by denali443** [gravitystorm/openstreetmap-carto#4461]
### Expected behavior

domain resolves and zip file is downloaded

### Actual behavior

domain does not resolve - script crashes

### Links and screenshots illustrating the problem
(link in external-data.yml)
https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundar
y_lines_land.zip

**Comment by andyrozman** [comment]
Same problem. Followed instructions in Docker, and got this errors:
import_1   | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe773a3e588>: Failed to establish a new connection: [Errno -5] No address associated with hostname
snip
import_1   | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='naciscdn.org', port=443): Max retries exceeded with url: /naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe773a3e588>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

**Comment by mothlight** [comment]
Yes, I'm struggling with this as well.

I know that file is available at
naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip
but I don't know how to change the url in the docker.
https://github.com/Overv/openstreetmap-tile-server/issues/211

**Comment by SomeoneElseOSM** [comment]
It's an upstream issue - see https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-913988101 .

 If you want to edit the download location directly, your copy of https://github.com/gravitystorm/openstr … l-data.yml is the file to edit.

The fact that the failure isn't handled nicely by the script here is logged as https://github.com/gravitystorm/openstreetmap-carto/issues/4358 .

**Comment by audour** [comment]
Same issue here.

Updating `external-data.yml` by replacing current url (https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip) by https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip makes script work.

I also tried https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip (found here https://www.naturalearthdata.com/downloads/110m-cultural-vectors/) but I get a timeout too.

**Comment by ZeLonewolf** [comment]
Thanks for the fix @audour.  Is there a reason we shouldn't update `external-data.yml` with the AWS URL?

**Comment by SomeoneElseOSM** [comment]
> Thanks for the fix @audour. Is there a reason we shouldn't update `external-data.yml` with the AWS URL?

Based on what happened the last twice that Natural Earth data became inaccessible (about a year ago and January this year), I'd suggest just updating the .yml file to "whatever works currently" - or even host a copy in this repository (the one file used is fairly small).
