### ISSUE TITLE
High voltage towers should have their reference number rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4478]
Houses have their address rendered, so should high voltage towers have
their reference numbers rendered!
- They are e.g., 60 meters tall: 20 times taller than a house, and can
be seen for miles.
- Their number plates are much larger than  houses'.

No, nobody lives in them, but the same goes for e.g., telephone
switching buildings, that have their addresses rendered.

And while you are at it, you might as well render the names of the
powerlines themselves: "Nerdsberg - Norfelwitz Line", as these "rivers
of electricity" form lines when seen from a hiker's eye much bigger than
named creeks.

So carto rendering towers and lines, but not showing their references, does not give such mammoth features the respect they deserve. It is like "Sally the homemaker doesn't need to know."

> Just use https://openinframap.org/ .

Yes, but then for two features, we throw away many more.

Yes, from a Google Maps point of view, rendering this information will simply distract users from finding the nearest hamburger mart. But OSM should be more than a beeline to businesses. 

That's what keeps the lines and towers off Google Maps in the first place.

**Comment by imagico** [comment]
Please specify what tags you would like to see rendered so we don't have to guess that.

power=tower + ref=* has 226k uses - 1.65% or all power=tower.

I don't see a good reason to render those here - they don't seem to typically have a meaningful function for the target map users.  I don't know of any general purpose map that labels power towers with that either.  It is unlikely that rendering those would have a meaningful positive effect on mapping since most of these references seem to come from either imports or from extrapolation of a consecutive numbering scheme.

**Comment by pnorman** [comment]
I also don't see the value in rendering either.

@jidanni When writing up issues, please review them to make sure you're complying with the code of conduct. In particular, avoid
> Snarking (pithy, unproductive, sniping comments)

**Comment by jidanni** [comment]
The "ref" tag.

Sure, from a city person's perspective these are unimportant.
