### ISSUE TITLE
Rendering of boundary=hazard

### ISSUE THREAD

**Issue by serhii-muchychka** [gravitystorm/openstreetmap-carto#4483]
**boundary=hazard** - a recently approved tag. Can carto render areas with it like **landuse=military** or in some other way?

https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dhazard

**Comment by imagico** [comment]
Tag is used about 150 times to map a broad range of subjective risks using mostly non-verifiable polygons.  Like:

https://www.openstreetmap.org/way/904264846
https://www.openstreetmap.org/way/145401143
https://www.openstreetmap.org/way/916160167
https://www.openstreetmap.org/way/917390205

We support mapping verifiable access limitations like fences or barriers and access restrictions on roads.  But we likely don't want to render a very vague and broadly used tag (already in the first 150 cases) indicating subjective and largely non-verifiable risks in a way that indicates something specific.  See also #2670.

**Comment by ZeLonewolf** [comment]
I am the author of the hazard proposal, and don't think this tag should be rendered on a general purpose map.  My motivation for `boundary=hazard` was to extract hazard boundaries from `boundary=protected_area` because hazard boundaries are not protected areas (in the conservation sense).  While osm-carto only renders some `boundary=protected_area` when combined with other tagging, there are other renderers which do render `boundary=protected_area` universally and `boundary=hazard` gives a home for these objects that can be more easily ignored by renderers.  Thus this portion of my proposal was in part intended to reduce the number of objects that were being inappropriately rendered (though not necessarly by this style).

I concur with @imagico's objections regarding low usage and rendering subjective hazards.  While a case might possibly be made for rendering authoritative hazard boundaries from some defined government source (I am _not_ making that case - just positing that such an argument might be made), there is no tagging that I'm aware of that can reliably distinguish such hypothetical authoritative features from subjective polygons.

**Comment by imagico** [comment]
Closing for reasons explained above.

**Comment by abdullahO2** [comment]
As I mentioned to you most of the other editors don't put the tag boundary=hazard and I saw them putting the tag military=danger_area and natural=sinkhole to refer to large digging places that we call locally "دحل" and they are dangerous for those in the desert, and the current style of the map doesn't show it as a dangerous place, and you can see the places I mean from here:
https://overpass-turbo.eu/s/1g21 & https://overpass-turbo.eu/s/1g22
I expect it is appropriate for those places to put the tag:
sinkhole=pit & natural=sinkhole
see:
https://taginfo.openstreetmap.org/tags/natural=sinkhole
https://taginfo.openstreetmap.org/tags/sinkhole=pit

What if places tagged natural=sinkhole can be shown?

**Comment by imagico** [comment]
I see what you mean now.  `sinkhole=pit` is not very widely used in Saudi Arabia either.  I am reopening #2414 for the purpose of newly evaluating how consistently `natural=sinkhole` is used and to evaluate if we can introduce a rendering of this.  

Generally speaking we want to render concrete and specific features tagged in a consistent fashion rather than generic characterizations like boundary=hazard that can be applied to a wide range of very different features.

**Comment by abdullahO2** [comment]
I understand your reasons, thank you, and I hope that places with the tag natural=sinkhole will be displayed on the map for the benefit of map users
