### ISSUE TITLE
Rendering barrier=tank_trap

### ISSUE THREAD

**Issue by Anazaar** [gravitystorm/openstreetmap-carto#4498]
barrier=tank_trap
tank_trap=dragons_teeth

[dragons_teeth](https://en.wikipedia.org/wiki/Dragon%27s_teeth_(fortification))

Currently, you cannot see COMPLETE NOTHING, and this is a solid barrier that will never be removed by anyone and will stay for thousands of years.

**Comment by imagico** [comment]
barrier=tank_trap has 820 uses, half nodes, half ways, almost exclusively in Europe, mostly in UK, Finland, Germany, Switzerland.  These are overwhelmingly historic artefacts with no present day function.

Hardly any of these forms a continues physical barrier to human movement so rendering the same way as other barriers would be misleading.

**Comment by Anazaar** [comment]
very wrong approach to the topic.  This barrier is very permanent.  It was built by the Germans before the world war.  Nobody will ever remove it and, due to its construction and material, it will last several thousand years.  It is a very unusual object found in Europe and comparing it to a non-durable plastic mesh fence is not the correct approach.  Please look for photos of such objects on the internet.

https://en.m.wikipedia.org/wiki/Dragon%27s_teeth_(fortification)

https://polska-org.pl/7266310,Pniewo,Zapora_przeciwczolgowa_tzw_zeby_smoka_Pniewo.html

**Comment by Anazaar** [comment]
there is no rendering for these huge objects, that's the reason no one is drawing them because they won't be visible anyway :-(

**Comment by Anazaar** [comment]
quote: Anti-tank barrage (the so-called dragon's teeth) in the vicinity of the Scharnhorst fortified group of Międzyrzecki Fortified Region.
 The total length of the four-row anti-tank barriers and the preceding ditch in the Międzyrzecki Fortified Region is about 15 km.  These dams, known as the Russian Dragon's Teeth (Zuby Dragon), are very solid, and at the same time clever work: made of reinforced concrete, connected by a common reinforced concrete bench at a depth of 1.4 m, they are designed in such a way that the armored vehicle would hang on top of it, without  the possibility of retreat, becoming an easy target for tank destroyers.

**Comment by HolgerJeromin** [comment]
>  they will ALWAYS be an impassable barrier.

We can not render all stuff we have in the database.
Tankers driving cross-country are not the main audience of this rendering style. :-)
If they are blocking a street they should already be tagged as `barrier=block` on the osm way it blocks.

Like every new feature we need to decide if it is worth rendering and how to do it.

**Comment by Anazaar** [comment]
Thanks for taking the time to read this topic.  These facilities are very large and very characteristic and very attractive for tourists.  It is a pity, then, that it is invisible on OSM.  regards

**Comment by Adamant36** [comment]
I'm not a super expert on this, but as far as I'm aware tank traps can also be trenches, As well as crossing metal poles, barb wire, random junk on the ground, holes with boards over them that are covered in dirt, etc etc. Given that it likely be hard to impossible to render them in a universally recognizable way. Maybe if they were all mapped as areas then there could be a fill color, but even that wouldn't  be super great and they aren't being tagged as areas anyway. Nor should they be. But it would be impossible to have a universal icon. 

In the case of Dragon's teeth specifically I wonder why they aren't just mapped as bollards since that's essentially what they are. At least at this point when they aren't actively being used to trap tanks. I'd wouldn't be surprised if some of them, and the other types, aren't tagged that way. Their sorta similar to bell bollards.

**Comment by Anazaar** [comment]
these are uniform structures, they are not barriers in the form of cones.  One element consists of 4 columns of gradually increasing height, each individual structure made of steel and concrete is buried at about 1.5 m and these structures are from several hundred meters to probably even several dozen kilometers

**Comment by Adamant36** [comment]
> these are uniform structures, they are not barriers in the form of cones.

I'm not sure what you mean by uniform structures or how it's relevant. Bollards are usually uniform and they aren't confined to cones. Outside of that the Wikipedia article for bollards has a section on dragon teeth. Not that I think necessarily think it's authoritative, but you cited Wikipedia in one of your comments. So I assume your willing to accept it as a possible "source" of knowledge. If that's the case, the it's far to say dragons teeth are bollards. If not, then I'd question why you cited Wikipedia at all. That said, there are many websites out there that sell and talk about "dragons teeth" bollards. They aren't something that are just confined to German or World War 2 anti-tank usage. Although that usage one type of them.

**Comment by Anazaar** [comment]
these are uniform structures, they do not constitute a barrier in the form of cones, it is a type of building with a very solid foundation and above-ground part, with a non-incidental structure and NOT an incidental height of individual elements, very durable, specific and due to its location indelible, removal will not pay off  of this structure.  It cannot be treated on a par with randomly scattered metal road blockers or fences and posts.

**Comment by Adamant36** [comment]
> These are uniform structures, they do not constitute a barrier in the form of cones

I'm afraid just repeating yourself isn't going to move this discussion forward. I heard you the first time. I just disagree with what you said. 

> non-incidental structure and NOT an incidental height of individual elements, very durable, specific and due to its location indelible, removal will not pay off of this structure. It cannot be treated on a par with randomly scattered metal road blockers or fences and posts.

As far as I'm aware bollards don't have incidental heights of individual elements either. Also they are often pretty durable, and aren't randomly scattered fences and posts. So I don't really see the relevance of what your saying.  Except that it seems like you think tank traps/dragons teeth are somehow special compared to other barriers. When that's not that the case. 

Random characteristics of tank traps don't really have anything to do with the merits of rendering them either. Not to speak for the maintainers, but I doubt they will agree to rendering them just because their durable or whatever. There really needs to be more then that, like much greater usage then 820 and wider adoption then a few places in Europe. There isn't a description of how to use the tag in the Wiki article for it yet. So your really jumping the gun by expecting it to be rendered at this point.

**Comment by Anazaar** [comment]
repetition is for attention and complete understanding.  Comparisons to cones sound like a JOKE.  When someone writes nonsense about it, I repeat the previous content and explain it further.  I don't think anyone can be persuaded here, but I just wanted to draw attention to this object.  I want him to understand well what I am writing about.  I do not hope that the pedestal in this topic will be made :-) I want to clarify all doubts to the end.  Understanding the specifics is very difficult.  Each area has its own specificity.  Such facilities will never be built again, but as I have repeated with 4x, they will easily survive 1000 years.  It's not really bollards and a fence in the woods.  REGARDS.

**Comment by Anazaar** [comment]
So I repeat once again that such a large structure should be visible at OSM.  Objects such as a single bush are visible, and an object that stretches for many kilometers and is about 10m wide is not visible.  REGARDS

**Comment by Adamant36** [comment]
> Comparisons to cones sound like a JOKE.

Your the one that brought up cones. Your also the one that brought up fences. Which I agree is a ridiculous analogy. So I guess your the one writing nonsense then since you made it.

> Understanding the specifics is very difficult.

Not really. I understand them fine. I think other people do also. That doesn't mean they can't be better clarified, but that has nothing to do with this repo or the merits of rendering tank traps. Usually the place to better clarify tags is the tagging mailing list. Which is my suggestion for your next step in the process of getting them rendered. Along with improve the Wiki article. There's nothing wrong with clarifying tags and expanding their usage before rendering them. If they are going to be around 1000 years there isn't really a reason to rush rendering them is there? I say we revisit this in 600 years 😆  

> It's not really bollards and a fence in the woods.

Like I said, no one compared them to simple fences in the woods. They are bollards though and that's not an insult to tank traps like you seem to think it is. The purpose of bollards are to divert traffic and that's exactly what tank traps do. Divert tanks. So it's a perfectly reasonable to call them bollards. 

> So I repeat once again that such a large structure should be visible at OSM

Might I suggest building=whatever for the ones that are "building with a very solid foundation and above-ground part, with a non-incidental structure"? I don't think it would be tagging for the rendering at that point and it's not like you can't tag the objects with barrier=tank_trap along with it. Then the building=whatever tag could be removed if (or when) this issue is eventually resolved, or not. It doesn't really matter. That's probably what I'd do though.

**Comment by Anazaar** [comment]
- whether I am understood or not, it is not verifiable.  I would like it to be visible on OSM in any form in some time.  Maybe someone willing to dig this topic out in a few hundred years :-)

**Comment by rivermont** [comment]
I suggest closing this unless there are new reasons for adding it. The tag usage has not changed in the last month.

There also seems to be a slight misunderstanding with regard to OSM/OSM carto. Just because something is not rendered on this particular style does not mean it shouldn't be added to the database. As pointed out above, this style has a purpose, which is to be a general-purpose map (among others).

As an aside suggested by @Adamant36 above, it looks like some tank traps definitely count as bollards, which DO render! So I personally don't think mapping them as bollards would be tagging for the renderer.

**Comment by Anazaar** [comment]
this one is only unique among tank traps because it is the largest.

https://www.google.pl/search?q=z%C4%99by+smoka+mru&client=safari&prmd=ivnx&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjk29vWzLX1AhVfhP0HHVXeBL8Q_AUoAXoECAEQAQ&biw=320&bih=449&dpr=2

**Comment by imagico** [comment]
Closing for reasons described in https://github.com/gravitystorm/openstreetmap-carto/issues/4498#issuecomment-982567708

We mostly render things in the map based on their present day function, not on their historic purpose.  I would in principle be fine with rendering either tank traps that presently function as such (impeding the movement of armored vehicles) in a way that indicates that (similar to other barriers we render) or historic artefacts from past wars as a type of memorial or ruins.  But established tagging in OSM does not allow for this distinction at the moment.

**Comment by BertMule** [comment]
The point is that they are very visible large objects, encountered by hikers, e.g. along the Dutch coast.
They not only exist in the form of teeth but also as concrete walls stretching for miles.

This is a related topic that refers to samples.
[tank_traps invisible](https://github.com/gravitystorm/openstreetmap-carto/issues/4551)
