### ISSUE TITLE
Render buildings pass through highway+`tunnel=*` without rounded corners

### ISSUE THREAD

**Issue by LaoshuBaby** [gravitystorm/openstreetmap-carto#4499]
### Expected behavior

When a road (especially a high-level one) passes through a building, the interface between the inside and outside of the building can be sharply divided.

### Actual behavior

For each road that passes through the building, because the part inside the building is labelled differently from the outside part, the outside part will have a rounded corner overlaid on the building.
I hope this problem can be solved in any zoom level, not just the listed levels.

### Links and screenshots illustrating the problem

[Link to position](https://www.openstreetmap.org/#map=17/22.21059/113.57738)

#### z17

Current:  (z17)
![图片](https://user-images.githubusercontent.com/42690037/144539942-29dd8289-e452-4e29-bd12-e1770e6dc25a.png)

Hoped:  (z17)
![图片](https://user-images.githubusercontent.com/42690037/144539199-98182d3e-a12e-4acf-b33a-d2e270489e47.png)

#### z16

Current:  (z16)
![图片](https://user-images.githubusercontent.com/42690037/144540067-1b905beb-1d4b-4ff4-8895-dab8e6ca5a27.png)

Hoped:  (z16)
![图片](https://user-images.githubusercontent.com/42690037/144540456-6c33d185-526e-4f0a-ac1a-69a8e5cd7594.png)

#### z19

Current:  (z19)
![图片](https://user-images.githubusercontent.com/42690037/144540152-791b4a1d-b8f9-4c11-9b8e-ed43691007fe.png)

Hoped:  (z19)
![图片](https://user-images.githubusercontent.com/42690037/144541146-24bf421d-8d2c-4c76-838b-beb8733160d7.png)

**Comment by HolgerJeromin** [comment]
This will be tricky. The rounded corner on all highways is to have nice roundings at corners. So to fill the pink edge in the following picture:
![image](https://user-images.githubusercontent.com/2410353/144562708-abab27fc-6a8a-486e-b50c-6d09f5b326e7.png)
But perhaps mapnik has some more tricks to fix both problems.

**Comment by LaoshuBaby** [comment]
> is to have nice roundings at corners

Yes, this is the problem, we still need to round the link between roads. 

So the fix of building through highway shouldn't affect already existed rounding at corners.

(But the fix is needed in the future)

**Comment by LaoshuBaby** [comment]
And another anonnying feature is when 2 different level roads meet

the higher level road will have a outer part

For example：[Simple position](https://www.openstreetmap.org/#map=19/39.70841/116.16055)

![图片](https://user-images.githubusercontent.com/42690037/144575019-95de55ff-6ab0-46a2-9f89-77aa07c581dd.png)

I don't know whether this had been raised as a issue before.

**Comment by imagico** [comment]
This design element is an inherent part of the way we render roads - changing that would require giving up the current paradigm of independently rendering road ways and making rendering of road ways depend on which other roads they connect to.  That would require compound queries just about everywhere in the road layers and would significantly increase the volume of code.

I do this partially in the ac-style for ground unit rendering of roads.  I am not aware of any other styles that do anything like that.

**Comment by pnorman** [comment]
This isn't unique to building passages, most tunnels would be better with a square transition between the normal road and the tunnel colour

![image](https://user-images.githubusercontent.com/1190866/180634153-1295c06e-3f49-472e-b5f5-281216e759eb.png)

I can see a few ways to tackle this, none of which are practical.

1. Detect that the surface road is touching a tunnel and set its line-cap to butt. The first part is difficult because you can't just check intersects, you have to only check touching points in the linestring, and it increases complexity to the most complex level. If it were possible to do this query, it could break the other end of roads in some situations
2. Change the ordering to put tunnels on top of other roads and set their line-cap to butt. This is practical to implement, but would break tunnels made of multiple ways, causing gaps where the ways touch. In addition, re-ordering would almost certainly cause side-effects elsewhere. 
3. Combine the two. This would be impractical to implement, and still cause some problems where a tunnel is made from multiple ways.

Because this is not practical with known techniques, I'm going to close this issue.
