### ISSUE TITLE
Add rendering for leisure=hackerspace

### ISSUE THREAD

**Issue by devjb** [gravitystorm/openstreetmap-carto#451]
I just noticed that the standard renderer does not label leisure=hackerspace in the map. The bike map does render the label. Maybe it might nice to have the names of hackerspaces also in the standard map.

**Comment by matkoniecz** [comment]
It is neither widely used nor passed through wiki proposal process. I propose to close this ticket.

**Comment by xamanu** [comment]
I don't think hackerspaces are a niche thing.

> making icon of hackerspace that would be clearly recognisable would be really hard.

There is quite a good symbol by [Eric Steven Raymond](https://en.wikipedia.org/wiki/Eric_S._Raymond): the glider [hacker emblem](http://www.catb.org/hacker-emblem/)

![hackerspace svg](https://user-images.githubusercontent.com/97706/64209517-40d7ae80-ce90-11e9-84ba-c51f237446bd.png)

Anyway, just made a PR: #3867

**Comment by dreua** [comment]
Rendering it with a blue dot like association/offices would be better than hiding it imho. Can we reopen this to reassess the situation? Or would you rather have a new issue?

The wiki lists it as "de facto", used over 1500 times: https://wiki.openstreetmap.org/wiki/Tag:leisure=hackerspace?uselang=en

I'm considering to tag it as "office" or something else just to have it on the map, but nobody wants that, right?

**Comment by immanuel-h** [comment]
Good point actually, there has always been a close connection between the OSM and hacking communities so this decision to not represent that connection seems rather weird.

**Comment by imagico** [comment]
Reasons for not rendering this other than the low use volume have been provided in #3867.  I particular important:

* the tag seems to be deliberately non-generic and culture specific.  The wiki text is full of _definition by example_ and weasel words like 'normally', 'typically' and 'often'.
* delineation of the tag is unclear, the tag seems widely used for commercially run places as well as community run places.  At the same time it is unclear if something like a community workshop providing classical engineering tools qualifies (and if not: if that is because those are not primarily for recreational use or because they are non-digital).

And keep in mind that our target audience is the potential global map user, we are not a special interest map for groups with strong voices on digital channels.

As i wrote in https://github.com/gravitystorm/openstreetmap-carto/pull/3867#issuecomment-527998308:

>  In general i think the whole domain (community infrastructure for common use and cooperation) is a worthy field to render in this style - maybe even to the level that we can throw out some less important things for it. But doing so would require there to be well defined tags that are used consistently according to a broadly accepted meaning.

**Comment by dieterdreist** [comment]
sent from a phone

> On 13 Nov 2023, at 10:04, Christoph Hormann ***@***.***> wrote:
> 
> the tag seems to be deliberately non-generic and culture specific. The wiki text is full of definition by example and weasel words like 'normally', 'typically' and 'often'.


if you only render things that occur everywhere on the globe it will lead to significant holes. We also have other culture specific tags like Japanese Baths, Churches, tobacco and alcohol shops, wayside crosses and what not. I can see one would prefer a generic tag applicable to “community run places with technology related services” or similar, but ultimately we use the tags that evolve through our community process, so if the process has led to a specific tag it is not the duty of OpenStreetMap carto to push for a different system without any trace so far.


> delineation of the tag is unclear, the tag seems widely used for commercially run places as well as community run places



can you provide evidence this is more of a problem here compared to other fields? Some SEO can be expected for any tag, and it’s more than 1,5 years that the wiki clearly states these should be community run places, so maybe just retag those commercial outliers which do not fit?

**Comment by imagico** [comment]
>> the tag seems to be deliberately non-generic and culture specific. The wiki text is full of definition by example and weasel words like 'normally', 'typically' and 'often'.

> if you only render things that occur everywhere on the globe it will lead to significant holes.

Please don't derail the discussion by making completely unsubstantiated claims about our criteria for rendering and not rendering things.  If you disagree with the assertion that the deliberately non-generic and at the same time vague and poorly delineated nature of the tag is causing problems just say so.  But stay specific and always assume good faith.

For those unfamiliar with tagging and rendering of the features mentioned:

* a _church_ is a well delineated culture specific feature that we tag consciously with the generic tagging `amenity=place_of_worship` and that is consistently used in that generic meaning world wide and that we therefore render as such.
* _Japanese bath_ is an umbrella term for several well delineated culture specific features (onsen, sentō, ashiyu) that we tag consciously with the generic tagging `amenity=public_bath` and that we render based on that.
* a _wayside cross_ is a well delineated culture specific feature that we tag with two largely synonymous deliberately non-generic but together fairly well defined tags (`historic=wayside_cross`, `man_made=cross`) which came to be in this form due to the origin of OSM in a christian cultural context) that we render both based on historic tradition (like we do for other legacy synonyms) and where we also render the more generic and not culture specific variant `historic=wayside_shrine`.
* _tobacco shops_ are a specific but not culture specific (tobacco consumption got fully assimilated into cultures world wide after about 1500) type of shops tagged in the established tradition in OSM to differentiate shops primarily by the products sold (which is evidently very well defined for tobacco).  We render this with a not fully generic but fairly universally understandable symbol.

If anyone has insights into changing de facto meaning of `leisure=hackerspace` such information is always welcome.  I noticed for example that use of the tag for _Joven Clubs_ in Cuba has substantially widened (Cuba is now the largest user of the tag outside of Europe and North America).  But i am not familiar enough with those to assess if this constitutes a substantial change in de facto meaning of the tag.

Here an incomplete list of other tags partly overlapping in de facto use with `leisure=hackerspace`:

* `club=*` (in particular `club=computer`, `club=linux`, `club=amateur_radio`)
* `amenity=workshop`
* `workshop=*` (in particular `workshop=fablab`)
* `amenity=internet_cafe`
* `amenity=social_centre`
* `amenity=community_centre`
* `amenity=coworking_space`
* `office=coworking`
* `office=it`
* `repair=assisted_self_service`

This is not meant to invite discussion on the meaning of those tags, just as a starting point for analysis or working on discussing and improving tagging elsewhere.

**Comment by imagico** [comment]
As i already said: The list of tags is not meant to invite a tagging discussion here.

**Comment by dieterdreist** [comment]
sent from a phone

> On 13 Nov 2023, at 13:16, Christoph Hormann ***@***.***> wrote:
> 
> ﻿
> As i already said: The list of tags is not meant to invite a tagging discussion here
> 


what I understood from your replies was that the current tag is generally not welcome because it is referring to a specific category of places at the first level where you believe it should be set inside a more generic umbrella tag for easier extendibility, and that it is used for different kinds of places in Cuba and possibly elsewhere than what is described in the wiki?
