### ISSUE TITLE
rendering boundary=protected_area

### ISSUE THREAD

**Issue by Mahabarata** [gravitystorm/openstreetmap-carto#4517]
Hi,

I don't understand the rendering of this tag :
* sometimes we have a rendering : like [here](https://www.openstreetmap.org/way/475440248) or [here](https://www.openstreetmap.org/way/230067527) or [here](https://www.openstreetmap.org/way/740574063)
* sometimes we don't : like [here](https://www.openstreetmap.org/way/480285588) or [here](https://www.openstreetmap.org/way/52091672) or [here](https://www.openstreetmap.org/way/543024312)

Best regards

**Comment by imagico** [comment]
We render `boundary=protected_area` only for specific values of `protect_class`:

https://github.com/gravitystorm/openstreetmap-carto/blob/871804d13f561c416c4423fc10ca2e7ea4aa413a/project.mml#L1169

See also https://wiki.openstreetmap.org/wiki/Key:protect_class

**Comment by Mahabarata** [comment]
I was thinking there was something like that but the [third example with rendering](https://www.openstreetmap.org/way/740574063) has no protected_class

And [the second example with no rendering](https://www.openstreetmap.org/way/52091672) is a ramsar, an international protection : should be rendering, no ?

**Comment by imagico** [comment]
> I was thinking there was something like that but the [third example with rendering](https://www.openstreetmap.org/way/740574063) has no protected_class

That is rendered as `leisure=nature_reserve`.

> And [the second example with no rendering](https://www.openstreetmap.org/way/52091672) is a ramsar, an international protection : should be rendering, no ?

I just explained the technical reasons for the rendering you see.  If that should be changed in some way is a different matter.

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/480285588 and https://www.openstreetmap.org/way/52091672 are not specifying type of protection in any standard format

If it is nature reserve then `leisure=nature_reserve` would be a good tagging.

If someone wants to use `boundary=protected_area` then at least specify `protect_class` tag - see https://wiki.openstreetmap.org/wiki/Key:protect class But maybe some more clear tags are appropriate here.

(I am treating it as request for help in understanding rendering and therefore closing it as answer was given)

**Comment by Mahabarata** [comment]
Another problem of your choice : you render only site with a UICN code. Many protected areas have no IUCN code.
The consequence is that some contributors put false protect_code to have a rendering. The example 2 [https://www.openstreetmap.org/way/230067527](https://www.openstreetmap.org/way/230067527) in my first post is one of them (on the iucn website, search "Lagarpampa" and you will see).

On the other end, the ramsar site [https://www.openstreetmap.org/way/52091672](https://www.openstreetmap.org/way/52091672) is not on the iucn website too and according to the wiki page, the protect_class should be 98 which means no rendering, clearly an error.

Please open back this issue and fix the rendering for International protection at least : code 97, 98 and 99.
(it will be ok for me if you don't render others protect_class).

Best regards

**Comment by matkoniecz** [comment]
See https://wiki.openstreetmap.org/w/index.php?title=Mistagging_for_the_renderer in general.

Note that for https://www.openstreetmap.org/way/230067527 `leisure = nature_reserve` would already result in rendering, without adding fake data damaging OSM.

https://www.openstreetmap.org/way/52091672 is rendered due to `natural=water` tag and is show as water

**Comment by imagico** [comment]
This issue was closed because it is about a question that was answered.

Keep in mind that `boundary=protected_area` is a tag meant and used to map classification of areas by an administrative authority of some kind (and as such has issues with [Verifiability](https://wiki.openstreetmap.org/wiki/Verifiability) of course).  But it does not depend on an area *having and IUCN code* (whatever that means exactly).  The [wiki page for protected_class=*](https://wiki.openstreetmap.org/wiki/Key:protect_class) contains an [extensive list of classifications in different countries](https://wiki.openstreetmap.org/wiki/Key:protect_class#Protect_classes_for_various_countries) and how they map to `protected_class=*`.  Anything that qualifies as `boundary=protected_area` can by definition also be assigned a `protected_class=*`.

If you want to suggest changes in rendering i suggest opening a new issue where you make a specific suggestion of what you would like to have changed and why.  The reasoning should take the actual use of the tagging in question in OpenStreetMap into account.  So if you want to suggest rendering additional `protected_class=*` values it is highly advisable to take a look at how these values are used practically first.

And it is also a good idea to read up on the extensive past discussion on the matter in #603, #3509 and #3887.

**Comment by Mahabarata** [comment]
A missing link : #4113, in fact the more appropriate answer to my question
