### ISSUE TITLE
Incorrect layering of breakwater at z=18

### ISSUE THREAD

**Issue by AndrewKvalheim** [gravitystorm/openstreetmap-carto#4518]
### Expected behavior

`man_made=pier`+`layer=1` (way [60786491](https://www.openstreetmap.org/way/60786491)) renders in front of `man_made=breakwater` (way [942959325](https://www.openstreetmap.org/way/942959325)).

### Actual behavior

At zoom 18, the breakwater renders in front of the pier.

### Screenshots illustrating the problem

Correct at zoom 19:

> ![z19](https://user-images.githubusercontent.com/1844746/155897571-ac9e20ed-4eaf-4475-883a-356c14100455.png)

Incorrect at zoom 18:

> ![z18](https://user-images.githubusercontent.com/1844746/155897570-0d785974-759b-4bdd-8084-dc3ee29c440e.png)

Correct at zoom 17:

> ![z17](https://user-images.githubusercontent.com/1844746/155897569-01f291e6-780c-40b4-bb88-01f08272c4af.png)

**Comment by imagico** [comment]
Thanks for the report.

This is not a zoom level problem and has nothing to do with the layer tag.  It is because the layers `piers-poly` and `piers-line` lack explicit ordering so the drawing order is undefined and varies arbitrarily between tiles and zoom levels.

https://github.com/gravitystorm/openstreetmap-carto/blob/871804d13f561c416c4423fc10ca2e7ea4aa413a/project.mml#L365-L390

Related to #330 by the way.
