### ISSUE TITLE
Text rendering messed up

### ISSUE THREAD

**Issue by davidak** [gravitystorm/openstreetmap-carto#4519]
### Expected behavior

Text should  not be messed up

### Actual behavior

Text **is** messed up

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/#map=19/52.27617/8.03748&layers=N

![Screenshot from 2022-02-27 21-12-37](https://user-images.githubusercontent.com/91113/155898181-8d1d8fe1-291d-4435-a45d-3f3d711d267e.png)

**Comment by HolgerJeromin** [comment]
I am pretty sure there are multiple tiles involved.
Some were updated, some were not,
The problem should be solved in a few hours automatically.

**Comment by imagico** [comment]
Yes, this looks like a tile update issue after changes in mapping.  It appears to be fine now.

In principle there can be inconsistencies in label rendering at metatile boundaries - but typically that happens in more complex cases, not in relatively simple situations like this.

Closing since almost certainly not a problem of the style.

**Comment by davidak** [comment]
I can confirm it's fixed now. Thank you!

![Screenshot from 2022-03-01 21-09-55](https://user-images.githubusercontent.com/91113/156241322-90368c05-c12c-482e-af2e-527a73ef5f26.png)
