### ISSUE TITLE
Render boundary=forest

### ISSUE THREAD

**Issue by nevw** [gravitystorm/openstreetmap-carto#4526]
The tag boundary=forest is approved for delimited forestry areas.  
https://wiki.openstreetmap.org/wiki/Tag … y%3Dforest   
Currently on the name of the forest only is displayed on the standard layer of OSM and most are complex multi-polygon areas in my country and often covering large areas and I feel it is important to see where the boundaries are as strict conditions apply within these bounds. The tree covered areas are often mapped with natural=wood or landuse=forest or landcover tags and the gazetted or otherwise defined boundaries of the delimited forests cannot be discerned.
The boundaries of some of the protected areas works very well and I expect something similar in a light brown shade might be appealing and distinguished from those currently rendered.
This link displays on the standard layer of OSM how the forest bounds are only displayed when the state forest way is selected and if unselected is lost in the tree cover areas https://www.openstreetmap.org/way/56392739#map=14/-27.0405/152.7997

**Comment by pnorman** [comment]
With 389 uses, it does not have enough widespread consistent usage to be considered yet.

**Comment by imagico** [comment]
See also #2567.

**Comment by Kitsee** [comment]
Hello,
I would like to restart this conversation as its been a number of years since it was closed and I believe the arguments against its addition are no longer valid. 

`boundary=forest` currently has 3,769 uses with concentrations in Europe, USA, India and Australia. It is important to also factor in that forests and therefor boundary=forest tend to be large in scale. The 3769 uses represent a land covering of 28,534 km2, roughly equal to the size of Albania (28,748 km2) or Belgium (30,688 km2). `boundary=forest` fills a gap in the tagging of forests allowing for a named forest areas to be separated from the actual areas of woods and non-woods contained within them. There is no alternate tags for this purpose.

I believe simply rendering the name tag of `boundary=forest` objects would be sufficient in most cases. I'm not sure if rendering the perimeter would be of any additional use.

**Comment by imagico** [comment]
I am re-opening this for a renewed discussion based on current use of the tag.

I am unfamiliar with this tag, i have never practically observed it in the database.  What would be important to get is first hand info on:

* how mappers practically map this on the ground, both in terms of classification (how do you determine if something you see qualifies as `boundary=forest`) and in terms of of geometry (since it is almost exclusively mapped with polygons: how do you delineate these).
* how the resulting information is of practical significance for our map users.

I am somewhat familiar with these two points regarding forest compartments (see #2567), but not for `boundary=forest`.

Note i am not asking for recitation of the wiki here, that describes how some people thought the tag should be used at some point, which is not of much concern for us here - we want to look at actual use.

> I believe simply rendering the name tag of boundary=forest objects would be sufficient in most cases. I'm not sure if rendering the perimeter would be of any additional use.

`name` is widely tagged on these (about 3.4k times).

Since we have very bad experience with basing label design on geometry sizes of features we do not otherwise display (see #4546)  this would mean a constant label size and starting zoom level independent of polygon size.

**Comment by dch0ph** [comment]
> I believe simply rendering the name tag of `boundary=forest` objects would be sufficient in most cases. I'm not sure if rendering the perimeter would be of any additional use.

Surely if the boundary is the defining characteristic, then rendering the boundary is the key thing? Rendering a fixed size name label will not convey anything about the boundary.

As noted, the priority is to establish what how mappers are using this tag, e.g. is it primarily a legal definition (a bit like the old "forest laws") where the areas covered may or not be wooded?

The taginfo chronology suggests to me that usage hasn't really stabilised. `boundary=forest_compartment` looks more stable.

**Comment by Kitsee** [comment]
> I am unfamiliar with this tag, I have never practically observed it in the database. What would be important to get is first hand info on:
> 
> how mappers practically map this on the ground, both in terms of classification (how do you determine if something you see qualifies as boundary=forest) and in terms of of geometry (since it is almost exclusively mapped with polygons: how do you delineate these).
> how the resulting information is of practical significance for our map users.

In many cases a named forest includes more than just the wooded areas. It can include roads, grassland patches, car parks, buildings etc. all of which may not be part of the wooded area but are within the named forest. `boundary=forest` allows for this separation.

I'll start with two examples of my own, the first one ([Way: Garn-Cam-Isaf](https://www.openstreetmap.org/way/196935941)) is a very small forest I converted to a `boundary=forest` some time ago. in this example the wooded area is divided into three by a road and a power line. Without `boundary=forest`, the three separate `natural=wood` would have to have identical names or be all part of a named MP implying that the road and the area around power line are not part of the forest. This implication I believe does not match common sense as most people would describe the road and power line as passing through the forest rather than not being part of the forest. As presently `boundary=forest` is not rendered, the name of this forest is not displayed in any way.

The second example is a forest I wish to convert but have not done so yet [Relation: Taf Fechan Forest](https://www.openstreetmap.org/relation/14693258). This forest I feel is a very good example of why `boundary=forest` are needed as this forest has been heavily developed for leisure and has numerous car parks and footpaths within it. many of the cars parks have signage on the ground describing themselves as within the forest but are not covered in woods such as this car park [Way: Pont Cwm-y-fedwen](https://www.openstreetmap.org/way/1100712022).

A large number of `boundary=forest` relations have been added in India mostly by a single user. [Relation: Kajalmata Rf](https://www.openstreetmap.org/relation/16561783) (Kajalmata Reserved Forest) is one example, these relations appear to be very large is size covering large areas of land, much of which is not wooded, much being what appears to be meadows or farmland.  

A handful of examples exist in the USA, largest of which is [Relation: Hoosier National Forest](https://www.openstreetmap.org/relation/2992980). This relation appears to mostly follow official boarders often stopping far short of the actual cut line of the wooded areas. in this instance the relation is also a `leisure=nature_reserve` therefor it is rendered.

Finally there is a large number of example on the eastern side of Australia. [Relation: Expedition State Forest](https://www.openstreetmap.org/relation/1504517) is one such example. in this example the relation has also been incorrectly tagged with `landuse=wood` causing it to render. I say this is incorrect as looking at imagery the area appears to follow official lines rather than the actual extent of the wooded areas. 

>  Surely if the boundary is the defining characteristic, then rendering the boundary is the key thing? Rendering a fixed size name label will not convey anything about the boundary.

In most cases, the actual visual extent of a forest would be made obvious by the wooded area contain within however this is not always the case with this tag and I have observed cases where multiple forests having a shared boarder and shared wooded areas. The primary purpose is to denote the extent of a named area that is a forest, it does not replace land coverings such as `landuse=wood` and `natural=forest` which will still exists but remain unnamed. maybe a label at all zoom levels combined with a faint boarder closer in would be appropriate but I will admit I have not given how it would be rendered significant amount thought other than it should be rendered in some way.

**Comment by imagico** [comment]
Thanks for the examples and the explanations.

My impression is that the examples you show can be classified into to very different things:

1. politically/legally defined boundaries of some kind, like state forests/national forests or similar concepts, which are more commonly tagged with `leisure=nature_reserve`/`boundary=protected area`.
2. abstract polygons that are not defined through something observable on the ground but through something you call _common sense_.

Regarding https://www.openstreetmap.org/way/196935941 you write:

> This implication I believe does not match common sense as most people would describe the road and power line as passing through the forest rather than not being part of the forest.

This means you use the term forest here not in the sense of a physical wooded area.  But you don't say why you think common sense dictates that the road and the power line are within the forest in the abstract, non physical sense.  And you, in particular, don't indicate how a mapper can verifiably determine if a road is within the forest or if it is between different parts of the forest.

This directly connection to my second question:

> how the resulting information is of practical significance for our map users.

In your example cases of the forest with the road and power line and the forest with the car parking inside - how is separately mapping the abstract concept of the forest with those in addition to the physical forest without those (as `natural=wood`/`landuse=forest`) providing meaningful information to the data users?

While i am interested in understanding these things it also seems to me already that the fact that the two different things listed above that seem to be equally and without distinction mapped with `boundary=forest` speaks strongly against  us interpreting this tagging.  For the former we would use a design similar to that of `leisure=nature_reserve`/`boundary=protected area` (though we would not want to render synonyms for much more widely used tags we already render).  But we would not want to use the same design for the second, which is quite clearly something very different.

Independent of all of that i am skeptical about rendering a tag that is clearly not representing physical geography but that is none-the less explicitly meant to be climate specific.  This does not go very well with our global scope.
