### ISSUE TITLE
Add toll gantry rendering

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#4565]
I was asked to resubmit this from #3699 so here I am. The use has increased to over 4000 now after a few years.

**Comment by imagico** [comment]
Comment from https://github.com/gravitystorm/openstreetmap-carto/pull/3699#issuecomment-468916864 still applies - there are now 3000 enforcement relations with enforcement=toll, predominantly in Hungary and Germany.

**Comment by Gazer75** [comment]
These are not the same. They are just checkpoints, no toll collected when passing them.

**Comment by jeisenbe** [comment]
This issue is requesting a rendering for `highway=toll_gantry`, a transponder or camera gantry that exists for the purpose of electronically collecting tolls, now used 4000 times, though distribution is focused in a few regions and countries: https://taginfo.openstreetmap.org/tags/?key=highway&value=toll_gantry#map

Similar tags:

`enforcement=toll` is used 3000 times, mostly as relations, apparently common in Germany especially: https://taginfo.openstreetmap.org/tags/enforcement=toll

`toll=yes` is used with `highway` on 363 640 ways - https://taginfo.openstreetmap.org/tags/toll=yes#combinations - we do not render this information. 

`highway=speed_camera` is used 54,000 times, world-wide: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera - but we declined rendering this in #4338

`man_made=surveillance` is used 159,000 times: https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance - we declined to render in #3367

`man_made=gantry` is used 10,000 times, mainly on ways:
https://taginfo.openstreetmap.org/tags/man_made=gantry

I find it difficult to support adding rendering for this less common tag when we have already rejected rendering speed cameras, which have a similar function, and do not render toll highways in a particular way.

I also do not know of an intuitive rendering which would not be confused with `man_made=gantry`

We do render `barrier=toll_booth` which is used 54,000 times, because you usually have to stop or at least slow down for a toll booth, making them much more significant navigational features - https://taginfo.openstreetmap.org/tags/barrier=toll_booth

**Comment by Gazer75** [comment]
highway=toll_booth is also used, at least in Norway, for private manual payment on private roads. Typically roads to shielings and cabin areas. Basically a self service spot to pay before driving on the road by writing on a form and putting that and cash in a box. Though it is more and more common to use apps or even their own transponder these days.
Didn't check numbers individually, but pretty sure there are more booths than gantries due to this.

**Comment by jeisenbe** [comment]
Closing this for reasons in comment above, also see #4338 where we declined rendering the more common feature highway=speed_camera for similar reasons. There is not a clear benefit in showing these on a general-purpose map. There might be a benefit in rendering highways differently when tagged with`toll=yes` but unfortunately the highway rendering is already complex, and other properties such as `surface=` and `access=` are more important than `toll=`

**Comment by Gazer75** [comment]
But having like 30+ different shop icons is ok for a "general purpose" map? Add up all amenities and POIs there are probably hundreds of different icons. Fint it amusingly contradicting.

There are several examples over the years of tags getting rendered and the use count takes off.
Automatic tolling is the future so these things will become more and more common.
