### ISSUE TITLE
Remove rendering of leisure=recreation_ground (synonym of landuse=recreation_ground)

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#4572]
[leisure=recreation_ground](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Drecreation_ground) is a less common synonym of [landuse=recreation_ground](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Drecreation_ground)

https://taginfo.openstreetmap.org/compare/landuse=recreation_ground/leisure=recreation_ground

I believe `leisure=recreation_ground` was added as a mistake in 2009 based on the history graph, and it has been strongly declining for several years now

https://taghistory.raifer.tech/#***/leisure/recreation_ground&***/landuse/recreation_ground

<img width="800" alt="Screen Shot 2022-06-08 at 10 00 02" src="https://user-images.githubusercontent.com/42757252/172674549-705d9ce8-2e5a-44b6-86b3-88481e187a79.png">

**Comment by imagico** [comment]
That is definitely a good idea.  I would go a steps further and suggest to also drop rendering of `landuse=recreation_ground` as this is used essentially as an umbrella tag for `leisure=park`, `leisure=sport_centre`, `leisure=water_park` and `leisure=playground`.  Doing so would encourage and support mappers to use the semantically more precise tags.

**Comment by zekefarwell** [comment]
> I would go a steps further and suggest to also drop rendering of `landuse=recreation_ground`

It certainly is a bit of a catchall tag, the usage of which has strayed from the original intent.  However I doubt removing rendering for it will improve the situation.  Clearly there are many recreation areas where mappers consider `leisure=park` and `leisure=sport_centre` innappropriate, but `landuse=recreation_ground` close enough.  Removing rendering for this tag will probably just annoy people and not improve the situation much.  Adding rendering for more specific recreation area tags sounds great.  For example, adding support for [landuse=winter_sports](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dwinter_sports) would be good as that would encourage mappers to stop using `landuse=recreation_ground` for ski areas.

**Comment by boothym** [comment]
I cannot see a reason why both leisure and landuse need to be rendered when there is no difference in meaning between the tags. The change would certainly fit in with the goals of the style, namely "... and helps to prevent unfavorable fragmentation of tag use."

iD already suggests "upgrading" the leisure tag to landuse, so it will likely continue to fall anyway.

**Comment by Adamant36** [comment]
> I would go a steps further and suggest to also drop rendering of landuse=recreation_ground as this is used essentially as an umbrella tag for leisure=park, leisure=sport_centre, leisure=water_park and leisure=playground. 

From what I've seen, that seems to be the case in most of a California and some other states. I use to have the opinion that leisure=park shouldn't be used in more ambiguous situations where landuse=recreation_ground would make more sense, but that doesn't seem to be the consensus in the United States. Mostly American's just want to tag everything even slightly related to recreation as a park. The fact that landuse=recreation_ground is also render has led to a lot of needless miss-tagging, edit waring, and bad blood in the meantime. So personally I'd support not rendering it anymore. Even if such issues didn't exist I can't think of a situation where leisure=park, leisure=sport_centre, leisure=water_park, or one of the other tags that essentially cover the same concept wouldn't work better anyway.

**Comment by DaveF63** [comment]
Here are my thoughts on this subject from a discussion on the Tagging forum.

[Is landuse=recreation_ground different than leisure=park](https://lists.openstreetmap.org/pipermail/tagging/2022-June/064829.html)

Specific to this actual issue:

>  I've never understood why recreation ground is tag with the key 
> 'landuse'.
>   Given the close association of other leisures features such as pitch 
> park, playground, picnic table, seating, dog park etc I firmly believe it should also 
> be tagged as leisure.

> The official name containing either 'recreation ground' & 'park'  also 
> has a bearing.

Using landuse for recreation_ground allows duplicating tags to use 'leisure'. 
These are both primary tags, designed to be used in isolation. It causes conflicts so should not be used together.

[way[leisure=park][landuse]]( https://overpass-turbo.eu/s/1kbr)
 
> recreation_ground is used essentially as an umbrella tag.
 
Contributors' failure to understand the purpose of a tag is not a reason to rescind it.

**Comment by LaoshuBaby** [comment]
> `landuse=recreation_ground` as this is used essentially as an umbrella tag for `leisure=park`, `leisure=sport_centre`, `leisure=water_park` and `leisure=playground`.

I was confused by this, is park located in a recreation_ground?

**Comment by DaveF63** [comment]
> this is used essentially as an umbrella tag

It's an individual feature in it's own right. In the real world & within OSM. 
OSM-carto reinterpreting reality to suit their world is a problem for OSM-carto contributors to rectify. 

> for `leisure=park`, `leisure=sport_centre`, `leisure=water_park` and `leisure=playground`

Again. removing a valid tag just because some (US?) contributors fail to understand is a really poor idea.

Substituting all those `leisure` features for a `landuse` feature shows why `recreation_ground` should be a part of the `leisure` key family.

>  the maintainers are against rendering umbrella tags.

`natural=water` \<cough\>

**Comment by Adamant36** [comment]
> Removing a valid tag just because some (US?) contributors fail to understand is a really poor idea.

Not like the reverse hasn't happened where a tag wasn't rendered just because some (German?) contributors failed to see the tags usefulness and thought it was someone's pet project or whatever. `amenity=parcel_locker` < cough cough >, but sure the style should keep rendering an ambiguous 'umbrella tag because "who cares about American contributors :vomiting_face:" or whatever. Right.

**Comment by DaveF63** [comment]
It's only "ambiguous" to those why fail to comprehend its meaning. This lack of knowledge & "umbrella" misuse within OSM is not a reason for OSM-carto to make unilateral decisions on a tags usage.

**Comment by Adamant36** [comment]
> It's only "ambiguous" to those why fail to comprehend its meaning.

You can say that for anything though. In this case the article for `landuse=recreation_ground` says it's used for "An open space for general recreation" and the article for `leisure=park` says "A park is an area of open space for recreational use." Maybe it's just because I'm an ignorant American or whatever, but I don't know how anyone can reasonably argue that `landuse=recreation_ground`  isn't a pointless umbrella tag when it has literally the exact same definition as leisure=park, but with only 1/10th the usage. Hell, the image used on the `landuse=recreation_ground` article is exactly the same as the one for  `leisure=fitness_station` and even there looking at  1/5th the usage `landuse=recreation_ground` when compared to the competing tag. 

But forget all that though and just look at the usage trends for all three tags. There's clearly a "winner" there and it isn't `landuse=recreation_ground`. If anything the tag is on the decline compared to the other tags. Especially leisure=park. So your really fighting a losing battle. The style might as well just stop rendering the tag and be done with it. Or I guess you can yell into the wind about stupid Americans or whatever while the tag's usage continues to decrease and it's eventually removed anyway. 

![Tag usage](https://user-images.githubusercontent.com/30259065/180267272-c9f0831b-281c-4bf1-8815-0637f525d76b.png)
