### ISSUE TITLE
Render harbour=yes

### ISSUE THREAD

**Issue by tntchn** [gravitystorm/openstreetmap-carto#4639]
Carto is not rendering harbour now. Actually there are no other map styles rendering harbour.

Example of a normal harbour: https://www.openstreetmap.org/node/252026088
According to OSM Wiki, a harbour which only includes trawlers can only tagged with harbour=yes + landuse=harbour. A landuse=harbour should include the water and ground facility in theory. I saw some harbour wrongly tagged as leisure=marina which is for yacht marina. Other mappers add natural=water tag or tag harbour as a bay.

The style of the harbour feature can be blue text for the name as like the water or the bay feature matching the style that many mappers are using now.

**Comment by imagico** [comment]
Tag has 4500 uses, very limited documentation.

Tag is used both over water (sometimes in combination with `natural=water`, there is also `water=harbour` with 466 uses), over land, or covering both land and water areas (sometimes in combination with `industrial=port` which has 2500 uses).

There is also `seamark:type=harbour` with >15k uses.

**Comment by jeisenbe** [comment]
This tag is used in combination with landuse=harbour, landuse=industiral, waterway=dock, leisure=marina and some other tags or rarely alone, it is often used for the area of land in a port, rather than the water area of an actual harbour (as the word is normally used in English). Since this tag is not clearly defined we should not render it.
