### ISSUE TITLE
way_pixels thresholds as variables?

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#4641]
Would it make sense to add the following code

```mss
@areasize1: 750;
@areasize2: @areasize1 * 4; // 3000
@areasize3: @areasize2 * 4; // 12000
@areasize4: @areasize3 * 4; // 48000
@areasize5: @areasize4 * 4; // 192000
@areasize6: @areasize5 * 4; // 768000
```

to `style.mss` and then use these variables instead of hard-coded numbers in the other `.mss` files? (Note: Many, but not all, of our current way_pixels thresholds use those above-mentioned values.)

**Comment by sommerluk** [comment]
@pnorman @imagico Do you think this would be an improvement or rather not?

**Comment by imagico** [comment]
I am not sure (which is why i was hesitant to comment).

In the form you quoted i don't think it is beneficial because `areasize4` much more cryptic than the literal `48000` and this way it would make reading the actual styling code much more difficult for the sole benefit to adjust the values at a single place.  If you want to do this i'd suggest to use functionally defined variables - like `areasize_threshold_label_bigger` or similar.

The real problem is IMO that we have so much duplicate code for the font size logic at many places.  If we could have that only once and then refer to it that would have a much larger benefit.  But this ultimately is a question of code complexity vs. code volume.  The way we have it right now has the benefit that we typically have all styling rules for a single element relatively close together and if we'd try to de-duplicate this kind of rule that would mean the styling rules would be more compact but also more interwoven.

**Comment by sommerluk** [comment]
Closing as this seems to have more disadvantages than benefits.
