### ISSUE TITLE
Access restriction dashing and unpaved pattern should be removed on very narrow road signatures

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#4657]
Follow-up issue to #3399.

On very narrow roads with casing, that is in particular:

* `highway=service` and `highway=road` at z14/z15
* minor service roads at z16

and to a slightly lesser extent:

* `highway=tertiary` at z12
* `highway=residential` and `highway=unclassified` at z13
* `highway=service` and `highway=road` at z16
* minor service roads at z17

the access restriction dashing and the unpaved pattern are poorly readable and it would probably be a good idea to drop them in these cases to reduce noise in the map.

See [z12](https://imagico.de/files/road_unpaved_access_12_40.png), [z13](https://imagico.de/files/road_unpaved_access_13_40.png), [z14](https://imagico.de/files/road_unpaved_access_14_40.png), [z15](https://imagico.de/files/road_unpaved_access_15_40.png), [z16](https://imagico.de/files/road_unpaved_access_16_40.png), [z17](https://imagico.de/files/road_unpaved_access_17_40.png).

**Comment by sommerluk** [comment]
I've taken a look on this, particularly on the unpaved pattern.



>     * `highway=service` and `highway=road` at z14/z15
> 
>     * minor service roads at z16

Width is `2.0`. I agree this is noisy.



>     * `highway=residential` and `highway=unclassified` at z13

Width is `2.5`. I agree this is noisy, and I think the reason is that often the road network is dense in such situations:
![residentialunpaved13](https://user-images.githubusercontent.com/6830724/186118497-53bfaf6e-b95c-4085-81ee-a03cda5c8891.png)



>     * `highway=tertiary` at z12

Width is `2.5` (same as for residential/unclassified at z13). I think this is less a practical problem than for residential/unclassified at z13, because typically the road network of tertiary roads at z12 is less dense, and even the unpaved tertiary roads are a bit noisy anyway yet. But I'm also fine removing it.
![tertiaryz12](https://user-images.githubusercontent.com/6830724/186121259-7a5518de-151b-4b89-bc77-c8db6e45d1ea.png)
![tertiaryz12b](https://user-images.githubusercontent.com/6830724/186121283-e2e5fe97-bd47-41bd-8a82-9e8d86b5ed22.png)



> and to a slightly lesser extent:
>     * `highway=service` and `highway=road` at z16
>     * minor service roads at z17

Width is `3.5` here. Not much, but it does not seem to create much noisy either. I would leave those as-is.

![grafik](https://user-images.githubusercontent.com/6830724/186122689-995b85da-0b8b-4b88-85da-924e7f792d45.png)
