### ISSUE TITLE
false positive with aeroway=holding_position (ways only)

### ISSUE THREAD

**Issue by phd0** [gravitystorm/openstreetmap-carto#4660]
### Expected behavior
false positive with ```aeroway=holding_position``` when the object is a WAY. the wiki does confirm that NODEs and WAYs are allowed.
no alarms reported for NODEs
more than 20000 nodes in service but only 600 ways.

### Screenshots with links illustrating the problem
https://www.openstreetmap.org/edit#map=19/39.91587/-105.12737
![image](https://user-images.githubusercontent.com/1939211/185869979-d2726c02-259e-48ac-ac09-0c7026e55481.png)
![image](https://user-images.githubusercontent.com/1939211/185870069-28ddae57-3913-40e9-9b8a-622f1a9216c1.png)

**Comment by imagico** [comment]
This looks like an iD issue to me, the screenshot is from iD, not OSM-Carto.

iD issue tracker is here:

https://github.com/openstreetmap/iD/

**Comment by mboeringa** [comment]
@phd0 , I agree with @imagico that this isn't an openstreetmap-carto issue.

However, I would like to add one more comment: I think we are in need of a **_new_**, separate tag for holding positions as **lines**, rather than **points**, to tag the true extent and length of the line visible on the tarmac. I think this would be beneficial, as there are essentially two, quite different, uses of holding positions:

- In flight simulators, to be able to "route" simulated planes on the network of taxiways and runways, this essentially requires **nodes / points** objects.
- As a cartographic feature to display the actual line on the tarmac with the correct symbology for the type of holding position. This requires a **way / line** object.

These two uses are slightly in conflict with each other, if we have a "dual" node/way tagging scheme as we have now.

E.g. last year, I converted all nodes in the Amsterdam AMS Schiphol airport to way objects to be able to correctly render them cartographically. Then this year, some other editor, probably from a flight simulator company, came along and converted them back to nodes.

This therefor potentially leads to edit wars.

I would therefor suggest to introduce a new tag, e.g. simply **aeroway=holding_position_line**, to tag the actual extent and exact position of the holding position line on the tarmac. This tag would then be used next to the existing **aeroway=holding_position** tag, that should then be limited to "nodes" only (as it seems currently in the iD editor), and that should preferably be positioned on the line object of the separate **aeroway=holding_position_line**.

Although I have had some ideas for documenting this on the Wiki, I have unfortunately not found the time to create a proposal page for this on the Wiki. I did leave a comment, with some screenshots, on the Discussion page of the **aeroway=holding_position** tag: 

https://wiki.openstreetmap.org/wiki/Talk:Tag:aeroway%3Dholding_position

See my _"Runway and ILS holding position digitization direction needs a standard"_ remark there.

**Comment by phd0** [comment]
hi, @mboeringa 
I quite like your analysis, and I would like to complete it to try to simplify the cases (without knowing if rendering is possible simply):

As the screenshot , if we just use the nodes but add a ```direction```, is it possible to take into account the zoom, and therefore the width of the taxiway to draw there a line perpendicular to the direction of the same width as the tawiway?
With if possible an SVG symbol to define the direction of operation (including for ```holding_position:type=ILS``` but with a another SVG image).

i use the 18C of Amsterdam AMS Schiphol for this exemple. 
https://www.openstreetmap.org/#map=18/52.33067/4.74203

![image](https://user-images.githubusercontent.com/1939211/186148481-75ddfbe7-b9ab-40c0-afb8-66c6df7de549.png)

Philippe, French User

**Comment by imagico** [comment]
This is not the place to discuss the best way to map and tag things, please move that discussion to somewhere else.
