### ISSUE TITLE
Add brigading to the code of conduct

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#4671]
brigading is the act of mass up voting or down voting a specific message or mass sending of otherwise non-constructive messages by a particular side for the purposes of making it look like there's more support for something then there actually is. As well as to pressure and intimidate participates in the discussion and/or the maintainers. Or in the case of mass down voting a message, doing so serves to harass specific editors. Usually brigading is done by people who aren't regular users. 

Although not super common here, brigading clearly occurred in #4512 and to a lesser extent in #1603. An argument could be made that #4512 was mainly (or only) merged due to the pressuring of the maintainers that went on throughout the process. To give a few examples, the first comment (made by @ttomasz), received 32 emojis in it's favor Most of the emojis were left by people who were not contributors to the discussion or the tracker more generally. 32 emojis in favor of rendering the icon was both extremely disproportionate to the support it had until then and the number of people who had participated in either the PR or issue. Whereas, https://github.com/gravitystorm/openstreetmap-carto/pull/4512#issuecomment-1030830141 had 18 thumbs up, only four of which were made by people who were contributing to the discussion. There was nothing inherent to the comment that warranted it receiving that many thumbs up except that the mass emojiing helped to continue making it look like @ttomasz had a substantial amount of support from people. In both cases the large amount of emoji's added nothing useful to the discussion. 

There's a point where such behavior is clearly non-constructive and only serve as a pressure/intimidation tactic.  Especially in cases where it involves the mass down voting of specific messages or users. Even in minor instances it can still be antagonistic. Brigading also raises issues about off tracker campaigning. What PRs are accepted should never come down to who is able to drum up more support for their side on a random OSM forum or whatever. Let alone should come down to who's side of the discussion is more able to pressure or intimidate the maintainers more then the other. 

Although I don't necessarily want to call brigading Bullying or systematic harassment, it can easily veer into being used as a tool for both if it's not put in check quickly. Whether that means asking people to stop doing it or locking the discussion when it reaches a certain point. Either way, it's still not something that should be allowed because of it's potential to pressure and intimidate other contributors. I'll leave it up to the maintainers to decide if or how the code of conduct should be changed to include brigading, but I think it's an issue regardless of if anything comes out of this or not. 

Thanks

**Comment by CorruptComputer** [comment]
Hello there, just wanted to hop in here with my thoughts.

I haven't really contributed to Carto, other than with the :+1:/:-1: reactions on some posts. I have mostly just watched the discussions happening here, and simply voted for the things that I agreed and disagreed with. As an active OSM contributor, this seemed like a way for me to give my opinion and help shape what I would like to see rendered on openstreetmap.org.

Also, when you don't have anything additional to add to what someone said but you agree with what they have said, is it not better to just give a simple thumbs up to let them know that there are others out there that agree with what they are proposing? If there are a ton of just "I agree with this" comments left, it will just cause more notifications and emails to be sent out to folks. Whereas the :+1:/:-1: reactions simply silently cast your vote of approval or disapproval for a suggestion someone has made.

**Comment by Adamant36** [comment]
> is it not better to just give a simple thumbs up to let them know that there are others out there that agree with what they are proposing?

Sure it is. Which is why this issue has nothing to do with random users giving a thumps up or thumps down once in an issue once in a while if they have nothing else to add to it. I'm assuming you know the difference between that and "the act of mass up or down voting a specific message for the purposes of pressuring or intimidating participates in the discussion and/or the maintainers."

**Comment by Eiim** [comment]
> I assume you know the difference between that and "the act of mass up or down voting a specific message for the purposes of pressuring or intimidating participates in the discussion and/or the maintainers"

I can't speak for CorruptComputer, but I'm not sure that I do. It seems to me like you're under the impression that people are going, "hey, everyone, go upvote my PR, then surely the Carto maintainers will merge it!" I don't think anyone's under the illusion that that is the way Carto's decision process works. I certainly do see users sharing PRs/issues, perhaps to bring more attention them, but also to elicit and respond to legitimate critiques from the community, rather than just the maintainers. I recently have given feedback in just one such case, #4666. I see only two differences between that PR and the two you provided: a) More people responded to the calls in those cases, and b) there were a number of non-constructive comments, which are a problem, but are already covered by the CoC.

Finally, while I'm certainly no maintainer myself, I'm not sure how 👍s are supposed to be "pressuring" them. They're overall quite small and unintrusive, and easy to ignore. If people are wielding them as a weapon against the maintainers, saying that they should accept something because of the emojis which appear beneath it, then it is those people, not the ones leaving the reactions, that are pressuring the maintainers. To the extent that the maintainers may feel intrinsic pressure from such "votes", I would argue that such pressure is simply the result of knowing the feelings of (at least a small, non-randomized subset of) the wider OSM community. If opinions are not voiced here, they are and will be voiced elsewhere, and it is likely that the contributors would still hear them, and the same effect would be had.

**Comment by Adamant36** [comment]
> It seems to me like you're under the impression that people are going, "hey, everyone, go upvote my PR, then surely the Carto maintainers will merge it!"

I think it's a lot more likely that @ttomasz asked people somewhere to show their support for the PR by upvoting it. Since his messages are the only ones seem to get mass upvotes and it's happened in several different issues. Otherwise you'd have to argue that 34 people who aren't regular followers of the issue tracker all decided completely independently of each to thumbs up a couple of random comments by the same user, and all within hours of each other. I'm sure you'd agree that's not a very plausible explanation. 

> I don't think anyone's under the illusion that that is the way Carto's decision process works. 

I don't know why they wouldn't be under that illusion since most of them aren't regular participants. It's not like vote stacking proposals has any chance of working but that doesn't stop people from doing it. They usually just do whatever someone tells them to regardless. Generally people don't do things for no reason though. I don't know what else it be in this case except to effect the decision process. 

>  certainly do see users sharing PRs/issues, perhaps to bring more attention them, but also to elicit and respond to legitimate critiques from the community, rather than just the maintainers.

I could really care less if someone shares a PR/issue to elicit critiques from the community. most of the 38 people who thumbs upped #4512 provided any criticism of it. If @ttomasz or whoever did the canvasing had asked people in the community to provide legitimate criticism though, cool. I don't have a problem with that. 

>If people are wielding them as a weapon against the maintainers, saying that they should accept something because of the emojis which appear beneath it, then it is those people, not the ones leaving the reactions, that are pressuring the maintainers.

Although the purpose of this isn't to place blame on anyone, I think the responsibility should lye on both the person who asked people to thumbs up the PR and the people who did it. Just like when there's vote staking in a proposal both the person who originally did the canvasing and the people who voted due to it are in the wrong. 

> If opinions are not voiced here, they are and will be voiced elsewhere, and it is likely that the contributors would still hear them, and the same effect would be had.

It's not the maintainers job to browse random discussion boards to figure out what people's opinions are on a particular issue. The place for people to voice their support or opposition to something is in the issue or PR. Every thumbs up by a random user is a lost opportunity to hear what their actual opinion about the PR is. 

I don't agree that the emoji's don't act as a tool to pressure the maintainers with. Otherwise people wouldn't do it. And there's a direct correlation in the meantime between @ttomasz getting 38 thumbs up and going off in multiple forums about how the maintainers should have just merged the PR because it had wide community support. So even if the thumbs up themselves don't pressure the maintainers, people clearly use the them as part of pressure campaigns that do. Although it's still a matter of context and degrees just like everything else. Do I think 3 thumbs up have an effect on what the maintainers do? No. But 35 emojis that someone is specifically citing as a reason why the maintainers should do something? Yes.

**Comment by wmisener** [comment]
I am one of these folks who's up- (and occasionally down-) voted comments more than I've contributed to this repository, and I just wanted to share my perspective; I hope it's not too off-topic. I've been editing OSM for two years, but it probably took me a year to find that this repository is where decisions are made to render things on the "Standard" osm.org map. I came across it like I'd guess many new users do: I wondered why POIs that I had added to the map didn't render. At first I commented in support of rendering a few types of places that I had added, and thought that displaying them would enhance the map in my area. But frankly, I found the process intimidating, and came out of it feeling like my comments were neither respected nor valued, but that instead these decisions would be made by others, decided using criteria that weren't at all clear to me. But as long as Carto is the standard osm.org renderer, I remain invested and interested in what's decided here. So now I mostly stick to quietly supporting choices I think would enhance this map and its goals with upvotes.

I respect that lots of folks here, maintainers and others, have more experience than me with both the technical and cartographic sides of the project. Of course, if it's decided not to merge something, I can't argue much because in the end, it's not my map and I haven't put in the work. But I hope more experienced folks here also consider that up- and down-voting is likely the entry-level way for people to be engaged in this project, or at the very least, it is for me. So out-of-hand dismissing the wide support of some ideas by users who haven't contributed much to the repository as "brigading" may not serve the project well in the long run. In fact, sometimes such upvotes might represent the viewpoints of people who aren't usually heard in these discussions. I don't support the bullying of anyone, but I'm also unclear about what the line is supposed to be between a demonstration of widespread community support for an idea and an attempt to "pressure and intimidate participants in the discussion and/or the maintainers". But I don't mean to speak to the backstory or specifics of the issues and users mentioned here, because I don't really know the story beyond what's written in the issues themselves.

**Comment by imagico** [comment]
I don't want to comment on the actual subject of this issue - there is not much to add on that from my side beyond what i had already commented in https://github.com/gravitystorm/openstreetmap-carto/pull/4554#issuecomment-1132861108

What i want to comment a bit on is the use of emoji reactions to comments on this tracker.  This is a github feature that - like all technical features in social interactions - can have benefits and can cause problems.  Useful and productive applications are in particular

* review work of changes, in particular for quick confirmations of agreement between reviewer and developer.
* expression of appreciation of someone's volunteer work.
* shorthand in decision making among the maintainers (like: i have read your comment, i have no objections against closing the issue/merging the PR etc.)

It is however also frequently the source of problems, in particular:

* in many situation the emoji you can use in reactions are inherently ambiguous.  For example a thumb-up to a PR can mean *i would support merging this PR as is* but can likewise mean *i thank you for working on this matter*.  It does not allow for any nuanced communication.
* while emoji reactions lower the barrier for active contribution in a limited way they naturally also discourage more meaningful contributions.  Someone who might be reluctant to contribute their thoughts on a matter will likely feel less need to actually do so if they already have the impression they contributed through an emoji reaction.
* people can get the impression (in particular due to the way github presents the reactions) that they have the function of some kind of poll or even vote, i.e. that the number of reactions has meaning and not just the individual reaction as a form of communication.  This wrong impression can lead to frustration when people realize that this impression is wrong.

It would therefore probably be useful if we'd include in our contributing guidance some information on these risks and on how our decision making process works to avoid people starting off with the wrong impression and as a result having a bad experience.

Personally i read reactions only as individual communication.  That means once there are so many reactions to a comment that github stops showing them individually (the 'and x more' in the tooltip) i ignore them.  In general the emoji reaction of someone who is not otherwise actively involved in a discussion to me feels a bit like when you are at a meeting/conference discussing with some people and someone else walks by and gives you a thumb-up/thumb-down/smile/frown.  That is potentially well intended and nice and could be a first step in actually participating in the discussion but on its own it is of rather limited value for the discourse on the matter.  And if someone does it over and over again in different discussions without otherwise contributing it will become annoying at some point.

Useful practical rules of thumb:

* If on an issue more people have contributed with emoji reactions than with actual substantial comments then it is usually wise to not further pile up on the emoji reactions and think about if you actually have something meaningful to contribute as a comment.
* If you contribute lots of emoji reactions but no more substantial comments, consider what would happen if everyone would do like you do:  The project would stop to work immediately.  While OSM-Carto could definitely function without emoji reactions it could not function without people engaging in verbal communication.

**Comment by Eiim** [comment]
I don't have much else to add, but I would like to respond to this:

> I don't know why they wouldn't be under that illusion since most of them aren't regular participants.

I think here you underestimate the [1% Rule](https://en.wikipedia.org/wiki/1%25_rule). Vastly more people observe the goings-on here than actively participate in them. Obviously, I cannot know the true numbers here, but at least 9 people on the OSM World Discord (not including me, as I haven't joined the discussion there) have expressed at least 7 distinct opinions about this particular issue. An untold number more have observed but not joined the discussion there, too. A few of those have expressed their opinion here, either in comment or emoji form, but most have not. Perhaps it would be better if they each wrote a long, thoughtful comment here about their opinion on the issue, but that is not the nature of the internet. I would guess that a large number of people observe this repo enough to understand its processes in at least rough sketches, even if they do not comment regularly or have never commented. In light of the fact that many more people view issues than contribute or respond to them, the idea that, in particular on contentious, well-known, or highly-discussed proposals, a larger-than-usual number of them would choose to react, does not seem so far-fetched, nor does it seem harmful.

**Comment by natrius** [comment]
Reactions SHOULD be used as intended, to show your support (or the opposite) for an issue or PR and maintainers can choose to ignore it like they did since beginning of developing (in general, not this project specifically). No need to bake something like this in CoC. And yeah, a 👎 would be better with a comment, but a 👍 not really.
This would prevent people from discussing or mentioning this in a chat or in the forum. 

Reference: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/

**Comment by Adamant36** [comment]
> It would therefore probably be useful if we'd include in our contributing guidance some information on these risks and on how our decision making process works to avoid people starting off with the wrong impression and as a result having a bad experience.

The reasons you gave for why up voting can be problematic sometimes are extremely cogent. I'm more then willing to accept the inclusion of some guidance on the risks you mentioned of over using emoji's and how decisions are made in the contributing guidelines as a compromise to adding something specifically about brigading. Since at the end of the day the important thing is to encourage more actual, constructive contributions and discourage non-constructive ones. So I support whatever you think the best way to do that is. 

> If that was brigading then we would need to outright ban all mentions of carto issues/prs from all channels used by OSM community (forum/discourse/discord/mailing lists/osmweekly/etc.).

I'm willing to give you the benefit of the doubt that you didn't specifically ask people to up vote the PR. Here's the thing though, plenty of people mention carto issues/PRs in channels used the OSM community and those issues/PRs rarely (if ever) subsequently receive 38 up votes from it. Even the original proposal for the tag didn't have that much support. Plus the up votes were specifically targeted at your comments. So if you weren't specifically asking for anyone to up vote the PR, cool, but I'd be interested to know you think there was such an inordinate amount of support for it compared to normal and why the support was specifically targeted at you then? 

Also, I find it hard to believe that wasn't your original intent since you went off repeatedly later about how the maintainers were ignoring what the community wanted by not merging the PR. I can guarantee you wouldn't have been able to make the same argument if the PR had of only received a couple of up votes and a few down votes. 

> in particular on contentious, well-known, or highly-discussed proposals, a larger-than-usual number of them would choose to react, does not seem so far-fetched, nor does it seem **harmful.**

The original proposal/issue wasn't particularly contentious, well-known, or highly-discussed though. The original proposal only had like 2/3's the amount of support that he PR did and quit a lot of people didn't support it. It only become contentious, well-known, and highly-discussed after @imagico didn't immediately accept the PR and @ttomasz went on a slash and burn campaign and made negative comments about repository/maintainers everywhere. No one really cared about it before that though.

**Comment by pnorman** [comment]
I don't see the issue that needs resolving, and I don't believe this is something commonly added to other CoCs. The behavior of pushing a bunch of people to issue a reaction isn't helpful, but also doesn't cause harms.

Referring to them as votes is misleading. They're not votes. I've never looked at an issue or comment, tallied up reactions, and concluded I need to act a certain way as a maintainer because of them. See #4574

**Comment by Adamant36** [comment]
> Referring to them as votes is misleading. They're not votes.

I don't think their necessarily votes either, but that does seem to be how people view the thumbs up emoji in particular since I've seen people reference how many thumbs up or thumbs down a message got as evidence that it had support or not. If the thumbs up wasn't a sort of vote there'd be zero point in using it since like @Imagico said it's rather ambiguous otherwise (just to be clear though, I'm purely talking about when there's a lot of thumbs up emoji's being used on a single message. Not just one off occurrences). Like @imagico stated, "people can get the impression (in particular due to the way github presents the reactions) that they have the function of some kind of poll or even vote." 

While I don't think anyone is going to get that impression from one thumb up they will if they aren't contributors, it's like 25, and there's very few messages in the meantime. Since it gives the false impression that they factor into the process. If not more so them comments do. Like say you say only a few messages and the first message has 15 thumbs up emojis that were added to it within the first several minutes of the PR being opened. It would be ridiculous to claim that the thumbs up at that point aren't going to be viewed as a sort of poll or vote by people who aren't regular contributors. All the more so because that's how they are sometimes used in other repositories.

**Comment by Adamant36** [comment]
I'm going to close this since the maintainers don't seem to think it's a problem. Thanks for the feedback about it at least if nothing else. Especially https://github.com/gravitystorm/openstreetmap-carto/issues/4671#issuecomment-1234035675. I still think it would be worth putting @imagico's suggestions into the contributing file, but if no one else does then whatever 🤷‍♂️ There's no point in leaving this open.
