### ISSUE TITLE
Rendering for aeroway=aerodrome should not paint its interior as land.

### ISSUE THREAD

**Issue by c933103** [gravitystorm/openstreetmap-carto#4681]
### Expected behavior
w322815282 include a pier structure constructed above water surface: w1093379907, as well as a number of bridges that connect to the pier structure. The space within these area is outside coastline and thus should be rendered as ocean.

### Actual behavior
After deleting w500203545, the water area is rendered in solid grey color, which mislead people into believing this area is land instead of water.

### Screenshots with links illustrating the problem
![image](https://user-images.githubusercontent.com/1525293/189512486-0e75d479-4790-4087-b0ca-84113e6ef788.png)
https://www.openstreetmap.org/changeset/126020549

**Comment by imagico** [comment]
Your issue description is not quite clear to me.  Could you please be specific which feature in that area you think is incorrectly rendered (and how so)?

Please keep in mind that the coastline data [has not been updated since early August](https://osmdata.openstreetmap.de/data/water-polygons.html) so if your issue is in any way related to the depiction of ocean polygons you need to take that into account.

**Comment by imagico** [comment]
@c933103 - the coastline is updated now so could you check if the problem you observed is still there and if yes, please describe what exactly you think should be different.

**Comment by c933103** [comment]
Oh now the rendering seems to work as expected. I guess it was just the
rendering not updaed yet.

在 2022年9月25日週日 17:16，Christoph Hormann ***@***.***> 寫道：
