### ISSUE TITLE
New render for historic=venta

### ISSUE THREAD

**Issue by Elme122** [gravitystorm/openstreetmap-carto#4686]
Hello,

I'm not sure if that's the correct category for this kind of request or if that's even possible, but I'd like to ask for a render to be made for a tag (historic=venta).

### Expected behavior

A render similar to that of historic=mansion.

### Actual behavior

There is no render for that tag.

### Screenshots with links illustrating the problem

<img width="795" alt="Captura de Pantalla 2022-09-14 a las 17 14 09" src="https://user-images.githubusercontent.com/113532690/190194359-ef04267e-9afa-4ba8-9010-2d8c0930be93.png">

**Comment by imagico** [comment]
Thanks for the suggestion.

`historic=venta` has three uses, all three on buildings and all in Spain.  Tag has no documentation on the wiki.

There might also be a misunderstanding of our rendering rules since we do not render `historic=mansion` - which has 60 uses and no documentation on the wiki either.  We do render `historic=manor` - which has 11k uses.

I am going to close this because the tag in question is not in any way established and it is unclear to mappers not familiar with Spanish terminology and Spanish culture what the tag is to be used for and what not.  For tags specifically documenting regional particularities of the geography a documentation that makes it clear to mappers from all over the world what the tag means and how it is delineated towards other tags is essential.

**Comment by jeisenbe** [comment]
It is documented on the Openstreetmap website wiki: https://wiki.openstreetmap.org/wiki/Tag%3Ahistoric%3Dventa

Description
Typical Spanish inns generally located in unpopulated and remote rural areas.

But I agree that this tag is too uncommon to be rendered.

**Comment by Elme122** [comment]
Thank you! May I ask why only common features can be rendered? I'm totally new so my question comes from absolute ignorance. :)

**Comment by imagico** [comment]
Ah, ok - that page was created today so it was not in the search yet when i looked.

**Comment by imagico** [comment]
The reason why we require tags to be well established before we consider rendering them is that we do not want to preempt or steer consensus building among mappers.  Tags with low use numbers used so far only used by a hand full of mappers have a high likeliness to change in meaning or being replaced by other tags.  We also need to consider that we cannot render everything mappers map so we need to prioritize features that are of broad interest to our target audience.
