### ISSUE TITLE
render trees with variable size according to `diameter_crown=*`

### ISSUE THREAD

**Issue by endim8** [gravitystorm/openstreetmap-carto#4690]
what about rendering trees according to their crown diameter?
something like this:
![Screenshot 2022-09-17 at 13 04 52](https://user-images.githubusercontent.com/26939824/190855892-eea6781e-a020-4f0e-89b9-26e62b1cdef3.png)

**Comment by imagico** [comment]
Would require revisiting the idea of ground unit rendering - see #1290.

The current semi-transparent fill style of tree rendering is poorly suited for this because it would obscure everything under the trees (which can in areas with many trees be a large percentage of the map area). It also increases the likeliness that tree symbols are confused with mapped woodland geometries (especially when you have multiple overlapping trees). See also discussion on #4448.

`diameter_crown=*` has about 250k uses, of which however a significant percentage come from imports.  `leaf_type`, `leaf_cycle`, `species`, `height`, `genus` and `circumference` are all significantly more common secondary tags on trees.

**Comment by tjur0** [comment]
I like the idea rendering bigger and older trees more prominently. The current rendering looks great on tree rows, but not so much if you have one big important tree. Would it be technically possible to render according to diameter_crown but decrease the size if there are features nearby?

![tree](https://user-images.githubusercontent.com/52704747/192041078-5f1bbfe2-bcb0-40e7-ad0a-e00063ad61a4.PNG)
[tree](https://www.openstreetmap.org/node/5807154383)

**Comment by pnorman** [comment]
> decrease the size if there are features nearby?

This is not practical.

**Comment by SK53** [comment]
Some quick testing assuming the crown diameter is represented true to scale suggests that this really only shows a noticeable difference at zoom 19. There are considerable issues with this _inter alia_: 

- crowns which overlap at this scale (various notations are used to resolve such overlaps in architectural drawings which are the main example of such mapping). Presumably this is largely because trees are of different heights; 
- extreme patchiness of the tag ([this avenue](https://www.openstreetmap.org/#map=19/52.20676/0.11287) in Cambridge has the inner lines of trees tagged, but the same size trees in the two outer rows lack tags) except in areas (such as Troisdorf) where tree data has been imported.
- existing issues of trees mapped on darker green background layers (natural=scrub & landuse=cemetery particularly noticeable with the Troisdorf data)
- there are other parameters associated with trees which may be more relevant in any discussion of which trees to render and how to render them, notably height. The 1:1000 maps from IGN Catalunya (the only mapping agency I could think of which currently maps trees as areas) [only shows ](https://www.icgc.cat/en/Public-Administration-and-Enterprises/Land-planning-and-urban-planning/Topographic-cartography/Topographic-cartography-1-1-000) "Arbre allat" (tall trees) 
- most representations do not use a simple circular area, but show some scalloping or other detailing

Broadly speaking I think this is largely a specialised requirement which lies outwith the general terms of reference of Carto-OSM. 

One minor remark is that people do continue to map trees as areas, often using natural=wood, [example](https://www.openstreetmap.org/way/216527141#map=17/51.49279/-3.21066&layers=N) in Cardiff.

**Summary:** I don't think this is appropriate for Carto-CSS, but could be added to a repertoire of desiderata for any specialist render for woods and trees. If wanted in Carto-CSS, then much more research on rendering on various backgrounds is needed.

**Comment by imagico** [comment]
I would agree on all points.

The Catalunya 1:1000 maps indeed show some interesting design ideas - thanks for pointing to those.

We should strive for displaying some more widely tagged properties of trees (https://github.com/gravitystorm/openstreetmap-carto/issues/4690#issuecomment-1250064005 - in particular leaf_type and leaf_cycle come to mind).  If we manage to do that in a way that works well, if mappers more widely come to tag sizes of trees in some form and if we in general make progress in developing a viable concept for the highest zoom levels (z19+), we can think about if and how something in this direction would also be possible here.

I am closing this as declined for these reasons.
