### ISSUE TITLE
Put one-way arrow before street name

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4694]
Maybe always putting the one-way arrows before street names could
- avoid risk of the arrow sticking out too far into oncoming traffic. Less confusing than the name sticking out too far.
- avoids pointing to a road and making people think the road pointed at is named that. 

Anyway I'm just saying if there is an urge to put the arrow right after a name, then instead put the arrow right before the name. Of course if the arrow was away from any names then keep it away.

![Screenshot_20220922-215106_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/191881140-6602262e-488c-4a41-bc79-7e78f10117e8.jpg)
![Screenshot_20220922-215955_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/191881150-2c58b371-b081-4414-a32e-979e763dd319.jpg) 
[Map](https://www.openstreetmap.org/?mlat=43.08132367039523&mlon=-79.06688678748604#map=18/43.08132367039523/-79.06688678748604).

**Comment by sommerluk** [comment]
I do not see a problem with the status quo. Nowhere, we use arrows to point to the “real” position of offset-labels.

The proposed alternative would likely not work reliably for multiple reasons:
- Text goes not always for left to right (like the Latin script), but can also go from right to left (like the Hebrew script and others).
- When a slightly curvy one-way road goes from north to south and the label has many characters, it is likely that at the actual rendering position of the arrow, the direction of the arrow is wrong, because with long text labels it is unpredictable where exactly the arrow renders and therefore how to turn it correctly.

**Comment by jidanni** [comment]
(Maybe related: the lack of _pairs_ of one way arrows at certain zoom levels:)
![Screenshot_20220923-133823_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/192025616-8ed19d6f-5ece-4ee1-8809-0119f175aefb.jpg)

Ah,  now it is more understandable:
![Screenshot_20220923-133832_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/192026170-a916c880-dc84-430f-be9f-0b7f3867cf93.jpg)
Location: just to the south of the previous set of images.
