### ISSUE TITLE
Please render shop

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4698]
https://www.openstreetmap.org/#map=19/51.75357/3.85196

I have added a shop as follows.

`shop=surf
`

Only a dot shows up.
Frustrating as ever.

Maybe there is some magic combination of tags to succeed, which I have not yet discovered.
But this should be simple.

Please render this.

Adding a name renders that.
But I would expect some icon without a name.

**Comment by jeisenbe** [comment]
The tag shop=surf is rendered like other uncommon types of shop: the name and a filled circle or “dot” is displayed. 

There are hundreds of kinds of shop= and we only have special icons for the more common values.

Currently the tag ‘shop=surf’ is documented but only used 139 times. 
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dsurf

**Comment by imagico** [comment]
Closing as invalid (we render shops for any value other than 'yes', 'no', 'vacant', 'closed', 'disused', 'empty') and declined (for the request of a specific design because the lack of broader use - see comment by @jeisenbe).

Please pay some more attention to precisely formulate when you open an issue - _Please render shop_ as issue title when it is evident that we render shops (and you state so yourself) is not very productive.

**Comment by BertMule** [comment]
I really wish you would at least apply generic icons or name-behaviour to entities.
This is already strongly suggested by the use of one within the ID-editor (a basket).
So often the icons are already available. 
Even more specific, like for pitches.

**Comment by HolgerJeromin** [comment]
The dot is a generic symbol.

The id icons are not usable because of their size and style.
Pitch icons are another open topic for this style with an existing github issue.

**Comment by jeisenbe** [comment]
We already use a basket icon for `shop=convenience` so it cannot be used as a generic `shop=*` icon. 

The current use of a “dot” (small filled circle” for uncommon values `shop=*` helps to make it clear that this is not a specific, more common tag such as `shop=sports` - which does have a specific icon since it is a widely used tag.
