### ISSUE TITLE
Please render folly

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4700]
Just give me an icon, as already used while editing.
As frustrating as ever,

Example of a landmark in a park.
https://www.openstreetmap.org/#map=19/51.99853/4.77250 

I also tried ruin.
Neither is rendered.

**Comment by sommerluk** [comment]
386 usages in total. That does not seem enough for rendering here.

Nous that you might consider using building=yes which is rendered.

**Comment by BertMule** [comment]
Thanks for the advise, but...
- I tagged building=yes, it did not make a difference.
- Neither did making it just building=ruins.
- Nor adding a name.

I really wish you would at least apply **generic** icons or name-behaviour to entities.

Not being rendered creates another story of the chicken and the egg.

**Comment by jeisenbe** [comment]
The node https://www.openstreetmap.org/node/10064523476 is tagged as `building=ruins`

This map style will render all areas (closed ways and multipolygons) which are tagged with `building=` - current the object above  is not rendered because it is only mapped as a node

In future reports please include a link to the map feature (node, way, or relation) if possible
