### ISSUE TITLE
Runways wrongly rendered on top of paths

### ISSUE THREAD

**Issue by dmgroom** [gravitystorm/openstreetmap-carto#4709]
In the absence of any layer tags "aeroway=runway" is currently drawn on top of paths,  runways are typically surface features which you could walk over, and therefore paths should render above them.

See 
[https://www.openstreetmap.org/#map=19/50.68102/-1.10790](https://www.openstreetmap.org/#map=19/50.68102/-1.10790)  and
[https://www.openstreetmap.org/#map=17/50.65108/-1.18321](https://www.openstreetmap.org/#map=17/50.65108/-1.18321)

**Comment by HolgerJeromin** [comment]
But a plane can land at this place without interference of a path.
So perhaps the current order is better.

**Comment by jeisenbe** [comment]
I belive the current drawing order is correct. We have chosen to render aeroways above roads and paths, because generally when a road or path crosses a runway or taxiway, the ground traffic must give way to air traffic, and because the runway or taxiway is usually the dominant feature for orientation.
