### ISSUE TITLE
Adjust parking (P) label size for new street parking values

### ISSUE THREAD

**Issue by SupaplexOSM** [gravitystorm/openstreetmap-carto#4754]
### Expected behavior
Parking areas (`amenity=parking`) with the [new street parking values](https://wiki.openstreetmap.org/wiki/Proposed_features/street_parking_revision) `on_kerb`, `half_on_kerb` and `shoulder` should be rendered with a small P symbol, as is already the case for parking areas with the values `street_side` and `lane`.

 ### Actual behavior
Parking areas tagged with the [values](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking#Additional_tags) `on_kerb`, `half_on_kerb` and `shoulder` are rendered with a large P symbol - in contrast to the already existing street parking values `street_side` and `lane`.

### Screenshots with links illustrating the problem
[Example](https://www.openstreetmap.org/way/1108013673)
![grafik](https://user-images.githubusercontent.com/66696066/207859666-363b8dc4-5b1f-48b1-90b6-e1c11d93a8f6.png)

**Comment by imagico** [comment]
Thanks for the suggestion.

Current use numbers:

* `on_kerb`: 10
* `half_on_kerb`: 2
* `shoulder`: 7

Compared to `lane`: 39k and `street_side`: 260k.

All three tags are poorly documented so far and it is unclear what the semantic delineation towards `parking=street_side` is.

Independent of the evidently too low numbers to make any kind of assessment about adoption of the tagging by mappers i would also be reluctant to support this without also supporting the implicit tagging of street side parking through `parking:left`/`parking:right`/`parking:both` - which is also not very widely adopted so far but which seems much more semantically differentiated in use at this time.

I suggest to close this because of the lack of adoption of the suggested tagging by mappers but would support looking into rendering of implicitly mapped street side parking (though this is also still be somewhat early because the few thousand use cases of this are all very new and mostly limited to a few urban places in Europe and the US).

**Comment by pnorman** [comment]
The usage numbers are too low to consider adding support for it, even if it's just adding it to an existing list.
