### ISSUE TITLE
Releasing v5.7.0

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4763]
I plan to release v5.7.0 this week. The biggest change is unpaved road rendering.

**Comment by sommerluk** [comment]
Great to hear.

Shouldn’t be [the version number 6.0](https://github.com/gravitystorm/openstreetmap-carto#mapnik-and-cartocss-update-v6x) because of [updated CartoCSS and Mapnik requirements](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#additional-deployment-dependencies)?

**Comment by pnorman** [comment]
> Shouldn’t be [the version number 6.0](https://github.com/gravitystorm/openstreetmap-carto#mapnik-and-cartocss-update-v6x) because of [updated CartoCSS and Mapnik requirements](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#additional-deployment-dependencies)?

I don't see a need to go to 6.0 for Mapnik 3.0.22.

**Comment by mboeringa** [comment]
@sommerluk,
Maybe better to reserve 6.0 for the transition to the osm2pgsql flex output (https://github.com/gravitystorm/openstreetmap-carto/pull/4431), which I think is a more fundamental change offering a lot of new options in the future.

@pnorman, any idea when you consider https://github.com/gravitystorm/openstreetmap-carto/pull/4431 done?

I have been personally running a customized version of that flex output style, and it has proven solid up to now. The only thing I haven't tested is updates, because I only do initial imports.

What are your ideas going further with this, especially related to your doubts expressed in https://github.com/gravitystorm/openstreetmap-carto/pull/4431#issuecomment-1186723756 whether or not keep or ditch the new transport tables?
