### ISSUE TITLE
Exact hits should divide into two to avoid zapping names

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4782]
- The right island's name is in good health,
- - https://www.openstreetmap.org/relation/3958223
- The middle island gets its name zapped at all zoom levels, presumably due to being part of a refuge
- - https://www.openstreetmap.org/relation/3958159
- but the left one doesn't, even though also part of the refuge
- - https://www.openstreetmap.org/relation/3959025

The user sees the middle island but is helpless, despite well-oiled mousewheel, to descern its name.
![20230228T142408](https://user-images.githubusercontent.com/1230959/221771503-470f8f08-52fa-43ed-9b52-6726f4e1f3b6.jpg)

**Comment by imagico** [comment]
This works as expected:

* multipart multipolygons get labeled on the largest part
* starting zoom levels and drawing order are based on polygon size

This could be changed of course - but it will be hard to find a method that is (a) technically feasible (b) produces good results and (c) can achieve consensus support.  Concrete, practical suggestions for that are welcome.

In the specific case the rendering result is of course the result of wrong mapping of the nature reserve in question - see https://pubs.er.usgs.gov/publication/70202617.

Please choose a reasonable title for the issue, the one used here just guarantees the issue will never be found again when someone looks for it.

**Comment by jidanni** [comment]
Probably just like on a bowling alley, if it's an exact hit the pins scatter.

So both names would occur. The only question left would be which one to put on the right side and which one to put on the left.

**Comment by imagico** [comment]
Closing this as the example shown illustrates a subjectively undesirable but ultimately intended result of our labeling system.  No suggestion is provided how this could be avoided.  The issue title remains non-helpful for what this issue is (that is documenting a side effect of our labeling) - instead it indicates a concrete suggestion to change something ('should') - which, however, is not to be found in the issue.

As indicated suggestions to improve labeling should provide concrete, practical suggestions that are (a) technically feasible (b) produce good results and (c) have a chance to achieve consensus support.
