### ISSUE TITLE
 Names of areas should spread out

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4787]
Names of areas should spread out.
They shouldn't be exactly like points' names.
Else [it looks like a Youth Activity Center fell in the middle of a lake](https://www.openstreetmap.org/relation/6595090).
Nobody would think that it is the name of the orange box, unless they
use the special link as I have used here.

Even if they spread out just a little, that would at least alert the reader to look for an area's boundaries, and not assume a (submerged) point.

**Comment by imagico** [comment]
Like #4782 this is pointing out a subjectively undesirable but ultimately intended result of our labeling system. No actual suggestion is made how to change this though the title suggests so ('should').

Frankly in this case the label/symbol location is not only very reasonable for the polygon in question, it is also actually a good choice in this context because it (a) avoids blocking other symbols/labels within said polygon and (b) avoids being misinterpreted as applying to a smaller geometry within the polygon (like an individual building).

Side note:  Tagging in this example is odd - this is not an established use case of `tourism=hostel`.

**Comment by jidanni** [comment]
![Screenshot_20230312-204805.jpg](https://user-images.githubusercontent.com/1230959/224545694-1e5193a1-0929-4ba4-99e7-cce76d12f044.jpg)

Here we see clearly the INDIAN RESERVATION is an area, not a point.

**Comment by imagico** [comment]
So you would like to see the labels of polygons to be letter spaced to extend across the whole polygon?

That would only work for label only rendering, not for symbol + label like in the example shown.

Practically it would result in a substantial increase in label collisions.

Still it would be interesting to see this in a practical demonstration in automatically rendered maps.  This would be very hard to do in a practically useful way with Mapnik probably.

**Comment by jidanni** [comment]
Well if the symbol must "tag along", then maybe put it at the front, back, or middle of the string, while testing:
- 𐇛 INDIAN RESERVATION 
- INDIAN 𐇛 RESERVATION
- INDIAN RESERVATION 𐇛

Hmm, not ideal. Well then just drop it:
- INDIAN RESERVATION

**Comment by imagico** [comment]
This is not a matter of formal 'must', it is a matter of good and practically feasible map design.  I know of no maps (digital or not) that combine graphical symbols and letter spaced labels.  A concrete suggestion of a labeling method along these lines would be needed.  If anyone develops something along these lines this would be highly welcome (like any other innovative design ideas).
