### ISSUE TITLE
Users can't guess what iconless polygons represent

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4790]
### Expected behavior
Able to figure out what each item on the map is supposed to represent, at least after checking all zoom levels.
### Actual behavior
I'm sure no user could tell you what sport the green/blue rectangle was supposed to represent, or even that it was a sport.

And the purple polygon, few users would guess the right answer.

They should be like the church, Even without a name we can guess right away by the cross.
### Screenshots with links illustrating the problem
https://www.openstreetmap.org/#map=17/40.15945/-89.36190
![20230319T125337](https://user-images.githubusercontent.com/1230959/226154481-a955568b-720a-4908-8a59-bddbaf6a2fd2.jpg)

**Comment by HolgerJeromin** [comment]
I think we have more specific addressable issues already
#844 #1126 #3398

And also the opposite: #3635

**Comment by imagico** [comment]
Because of our goals, specifically the fact that we render labels in the locally used language everywhere and hence no map user is able to universally read all the labeling in the map, we aim the map to be intuitively readable even in the absence of labels.  We are not perfect in accomplishing that goal, not by a long shot, but we are not bad at that either, especially considering how many different features the style shows.

I don't think we need a generic meta-issue for this.  This is clearly part of our core goals and needs to be pursued with every single concrete design decision. Because of that i am closing this as it lacks a concrete problem definition.

In terms of ways to improve on this - this is a matter of mostly non-technical design work - developing symbology and color combinations (#2270) that are intuitively recognizable across different cultures and geographic settings.  As we have discussed in #3635 static point symbols are a rather limited way to visualize things - hence new design paradigms are needed - like what is being discussed in #844.

The concrete example shown also relates to #4543.
