### ISSUE TITLE
name of cemetery multipolygon not rendering

### ISSUE THREAD

**Issue by nevw** [gravitystorm/openstreetmap-carto#4795]
name of cemetery should render whether multipolygon or polygon

name of this cemetery is not rendering for me https://www.openstreetmap.org/relation/1795473#map=18/-28.91506/153.31833

Screenshots with links above illustrating the problem
<img width="1613" alt="Screenshot 2023-03-27 at 11 00 17 pm" src="https://user-images.githubusercontent.com/44488237/227946525-a17d5a62-081b-47bb-bc43-86205d740474.png">

**Comment by imagico** [comment]
Thanks for the report.

This is likely due to collision of the cemetery label with one of the symbols - symbols have higher priority than labels.

What can possibly be done in that regard under the constraints we have is covered by #3857 and #3880.  Solutions to either of these issues would probably address this problem.  Therefore i am closing this as duplicate.
