### ISSUE TITLE
golf pond multipolygon miseries

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4823]
```
golf	water_hazard
natural	water
type	multipolygon
water	pond
```

Looks
- bad  https://www.openstreetmap.org/relation/15924443#&layers=M
- good https://www.openstreetmap.org/relation/15924443#&layers=Y

https://wiki.openstreetmap.org/wiki/Talk:Tag:golf%3Dwater_hazard#With_an_island_in_the_middle

**Comment by HolgerJeromin** [comment]
Can you explain what you see for a problem instead of letting us guess?

Screenshot from osm-carto (titled from you as bad)
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/2410353/6b1c4328-d806-4af8-b069-63b3cc3a5dd0)
cyclo osm (titled as good)
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/2410353/1df6d643-b2c3-4a81-87f7-57edfab5b286)

**Comment by jidanni** [comment]
Or maybe it never refreshes?
![20230603T090154](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/db05b890-13f5-4884-a82d-b773bab7f50a)
Date:
Sat, 03 Jun 2023 14:03:59 GMT
Etag:
"e22fdb5544899cf3f0f9c3af3a076285"

**Comment by pnorman** [comment]
Screenshots show no osm-carto problem.

**Comment by HolgerJeromin** [comment]
Osm infrastructure does not support /dirty url anymore.
You can try shift-f5 or ctrl-f5 in your browser

**Comment by jidanni** [comment]
![Screenshot_20230605-055151.jpg](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/bd4fe0ab-2a4b-4880-8231-53c7a8c72783)

I just borrowed somebody's cell phone, hasn't updated even yet.

**Comment by jidanni** [comment]
Got any URLs which will show me what you see?
