### ISSUE TITLE
Something wrong with quarry?

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4826]
I changed a quarry from misleading 'grass' to 'quarry': [ENCI](https://www.openstreetmap.org/#map=16/50.8233/5.6856).
Despite this being hours ago, and I re-cached several times, nothing has changed in rendering, it still looks like grass.
It's not a gigantic quarry. It does not have conflicting tags or enclosing land-use.

I also removed 'disused' (it actually is), though that should not make a difference. 

Confusingly there is a tiny quarry on the west side that looks fine.

So I wonder: am I missing something, or is there some problem in rendering?

Update. Rendered now. Can't delete this, it seems.

**Comment by imagico** [comment]
This is not a style problem so off-topic here.

You can close your own issues.

**Comment by sommerluk** [comment]
To explain further:

Here in this Git repository, we are only developing the map rendering style, but we do not provide an online live version of the map here.

The OSM Operation Working Group, which is a different group, takes our style, installs it at their servers and provides the resulting online map at openstreetmap.org. OSM Operation Working Group has their own Git repositories, but I don't have the link at hand right now.

A slowly updating online map is indeed not good for mapper feedback. Occasionally, I even observed that it takes up to almost a week to update, but this depends also heavily on the country from which you are accessing openstreetmap.org. This makes things more difficult to track, because users in different countries might see differently up-to-date maps.  I think the Operation Working Group does whatever they can to provide updates as fast as possible within the limits of the infrastructure they have.

**Comment by imagico** [comment]
The operations issue tracker is on https://github.com/openstreetmap/operations/.  But if you want to open an issue there you should make sure you analyze the problem sufficiently to determine if this is actually an actionable issue.

I opened #4827 it collect ideas what more substantial improvements in style deployment might be of benefit for mapper feedback.

**Comment by BertMule** [comment]
I just looked again. 
There is no way I can close my own issues.
Probably because of roles/rights. I am no developer here.

Pretty inconvenient. I would have remove/closed this myself if possible.

**Comment by BertMule** [comment]
> I opened #4827 to collect ideas what more substantial improvements in style deployment might be of benefit for mapper feedback.

Appreciate that.
