### ISSUE TITLE
Rendering of historic=high_cross

### ISSUE THREAD

**Issue by b-unicycling** [gravitystorm/openstreetmap-carto#4833]
### Expected behavior
It would be great if [historic=high_cross](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dhigh_cross) could be rendered in some way, the easiest would be, if they were rendered like [historic=wayside_cross](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dwayside_cross).
More than half are National Monuments; it would be useful to have those shown on the map.

### Actual behavior
Not rendered at all, because the tag didn't go through proposal process.

### Screenshots with links illustrating the problem
![Screenshot 2023-06-22 165136](https://github.com/gravitystorm/openstreetmap-carto/assets/120184625/1449d948-0ced-4269-b9e1-ceec1ffccd31)

**Comment by Sirorezka** [comment]
I agree, noticed same issue. Some historic objects and especially points are not rendered at all. One more example:
<img width="1179" alt="image" src="https://github.com/gravitystorm/openstreetmap-carto/assets/10659800/88f5517f-11cd-4850-9018-89508162dd2a">
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/10659800/20a03a9e-b230-4072-b5af-1e01a8fccc7b)

**Comment by imagico** [comment]
Thanks for the suggestion.  `historic=high_cross` currently has 56 uses, almost all of them in Ireland, almost all of them added in the last 6 months.  So too little basis so far to assess if the tag is sufficiently accepted by mappers and consistently used with a well defined meaning.

It is somewhat odd that given that

* we render `man_made=cross`
* `man_made=cross` would by most be considered valid tagging for the features in question
* tagging `man_made=cross` would not collide with `historic=high_cross` in any way

hardly any of the 56 use cases are tagged `man_made=cross`.

And to be clear - proposal processes have very little bearing on if or not we render a tag.

@Sirorezka - different issue - see #331.

Closing this for the moment because lack of sustained broader use so far makes proper assessment impossible.  This does not in any way prejudice a later assessment based on a better data basis.
