### ISSUE TITLE
Add support for slipway ways 

### ISSUE THREAD

**Issue by finetjul** [gravitystorm/openstreetmap-carto#484]
Right now, only slipway points are visible. But >20% of those slipways are ways.
- http://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dslipway
- http://taginfo.openstreetmap.org/tags/leisure=slipway#overview

How about:
- always render slipways points as icons
- for zoom >= ?, render slipway ways with blue lines

**Comment by boothym** [comment]
There are a couple of slipways near me with the same issue, e.g. https://www.openstreetmap.org/edit#map=19/56.06853/-3.17367 - see http://c7.alamy.com/comp/G100NF/elevated-view-of-kinghorn-fife-scotland-april-2016-G100NF.jpg for a view of the area.

In this case I created it as a way because it's more information than just a node and it's not at the end of a road. Or should I be adding a node to the current service road or making the slipway a service road instead?

I don't want to be tagging for the renderer by just creating a node, so it would be good if this issue can be fixed for ways.
