### ISSUE TITLE
Inner of inner of water becomes water

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4840]
It seems impossible to something NOT become water if it is an inner of an inner of water.

I'm talking of https://www.openstreetmap.org/way/1189874447

I had the surrounding as a floating pier (which it is), then as a pedestrian as inner of water.
Neither way I avoided a water 'hole'.
I also tried the garden as inner of the water too.

Is there proper way to get what I wanted, or this a flaw of the rendering?

**Comment by imagico** [comment]
Since this is a mapping question rather than a rendering question this is not the right place for it.  I will quickly try to explain the situation none the less.  Please discuss further questions what is and what is not correct mapping here on a suitable channel of your local community.  You have a:

* garden https://www.openstreetmap.org/way/1189874447

and a

* ring shaped pedestrian area https://www.openstreetmap.org/relation/16095158

within a

* water area https://www.openstreetmap.org/relation/13075964

You see the pedestrian area because this is rendered - like other roads - after the water layers.  You don't see the garden because that is rendered - like other landcovers - before the water layers.

**Comment by mboeringa** [comment]
As to fixes, you could consider adding natural=coastline as tag to the outer of the pier.

This is of course a matter of taste, but for permanently moored structures like this that even contain landuses, I think considering it as a fixed coastline is fine. It is essentially a "floating" island and permanent barrier from the perspective of any shipping traffic that might be around, as such, considering it as "land" seems fine IMO.

**Comment by BertMule** [comment]
I don't see a solution in what you wrote.
This is no seawater, so a coastline is out of place.

I should be able to just make it an 'island', with everything on it.
That just does no seem possible, after more experimenting.

I still consider it a flaw, unless I am overlooking something.

**Comment by BertMule** [comment]
My problems suddenly is solved, apparently by my own latest change.
