### ISSUE TITLE
Render `barrier=jersey_barrier`

### ISSUE THREAD

**Issue by ppete2** [gravitystorm/openstreetmap-carto#4854]
Please render `barrier=jersey_barrier`, as it is an important optical info on a map if the connection between 2 streets is blocked by this type of barrier. It's frequently used, and documented on: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Djersey_barrier

Used on nodes it's kind of similar to `barrier=block` which is already rendered

**Comment by imagico** [comment]
`barrier=jersey_barrier` is the most common linear barrier tag currently not rendered.  16k uses on ways, compared to 1.4k uses of `barrier=wall` + `wall=jersey_barrier`.

**Comment by dch0ph** [comment]
Rendering `barrier=jersey_barrier` as `barrier=wall` if a way and as `barrier=block` if a node would seem a good functional description of a jersey barrier. The only argument for a specific styling would be mapper feedback, but the best mapper feedback is rendering in the first place! Implementation not obvious to me since both linear and point barriers are extracted from `planet_osm_polygon`.
