### ISSUE TITLE
Map key mixes signatures for no access with construction

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#4865]
Highway _construction_ is rendered as alternating white/colour, while _no access_ is rendered as oval dots on full colour.
The map key mixes those up, in particular, the '_no access'_ rendering is explained as construction. 

In the screenshot, the lower part of the motorway is '_no access_', the upper part is construction. 
The map key for 'private access' and 'destination' is nearly invisible, that should be shown on darker background.  

![Screenshot from 2023-08-23 12-00-03](https://github.com/gravitystorm/openstreetmap-carto/assets/8266355/6312e314-f89f-4c1a-8752-c81bdc038a65)

**Comment by imagico** [comment]
The map key on openstreetmap.org is not part of this project, issues with that would go to https://github.com/openstreetmap/openstreetmap-website.  See also #4211.

We have had in the past thoughts about creating a legend of this style (#1928) but because of the size of such a project this would probably not be feasible to maintain as part of the style.

There are external projects maintaining information that can serve as a map key, in particular [on the wiki](https://wiki.openstreetmap.org/wiki/OpenStreetMap_Carto/Key)  and [my own Styleinfo](https://imagico.de/map/styleinfo/#style=osmcarto&section=style).
