### ISSUE TITLE
White road ends in "midair" "over" red road

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4871]
Something's very wrong at
https://www.openstreetmap.org/node/5021355401
causing the white road to seemingly end in midair above
the red road.
![20230917T102811](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/153e07b1-5487-4ab4-b750-4a4d3259f73b)

But in the editor things look fine.
![20230917T102731](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/d431d10c-161f-4fb9-964c-86724939c0c8)

**Comment by imagico** [comment]
This is intentional, link roads are drawn below all other roads.

In the concrete case this is a tagging error.  Quoting from https://wiki.openstreetmap.org/wiki/Tag:highway=motorway%20link:

_In most countries, if a road leads from a motorway to a non-motorway, only the portion that solely carries traffic to or from the motorway should be tagged as motorway_link._

**Comment by jidanni** [comment]
That wiki page goes on to say
> in the United States is that motorway_link is based on physical characteristics alone, and that they end where the ramp meets the surface street regardless of direction or use by other transportation modes.

OK, I'll edit the road.
