### ISSUE TITLE
Rendering natural=hill

### ISSUE THREAD

**Issue by comentiscode** [gravitystorm/openstreetmap-carto#4877]
### Expected behavior
natural=hill should be rendered i the same manners as natural=peak and natural=volcano
As for now the current value for marking a named hill is to give it the tag peak.
I am living in a flat area (Denmark) and here peaks seems to be a too much oversized. We have lots of hills and they have names and elevations. A rendering into the maps will be most valued.
The icon could be a "brown bump" in the same color as peak.

### Actual behavior
natural=hill is not rendered per default
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dhill

### Screenshots with links illustrating the problem
There are only hills in these areas, but the rending shows a lot of peaks. There are no mountains in DK as I know of so this is a overkill to show the hills this way.

![Skærmbillede 2023-09-29 114642](https://github.com/gravitystorm/openstreetmap-carto/assets/146412518/a82f1b70-63bc-441b-9f98-429257b31bea)

![Skærmbillede 2023-09-29 114823](https://github.com/gravitystorm/openstreetmap-carto/assets/146412518/15183ff2-d92a-4018-801b-efc17093614d)

**Comment by imagico** [comment]
Thanks for the suggestion.  `natural=hill` is a tag without consensus among mappers.  It is an attempt to separate out a subset of what is predominantly tagged `natural=peak` in a - so far - deliberately subjective fashion (i.e. without a verifiable definition).  Its use is patchy, dominated by mass additions (and a few collective reverts of those):

https://taginfo.openstreetmap.org/tags/natural=hill#chronology

I suggest not to render this because broad consensus among mappers is that `natural=peak` is universally suitable for local maxima in the topography.  Further differentiation based on topographic context is potentially useful (see #3722) - but so far consensus among mappers on this is that this is something that does not belong in OSM (because such are computable characteristics based on information already in OSM and readily available open topography data).

**Comment by xozahl** [comment]
There are lots of instances where tag selection need sound consideration. I live in a country where there are no physical peaks. With the current default many named mounds over 10m are tagged and shown as mountain tops. As to physical names, we have lots of hills from 10m and up amd mountains from 20. 

There should be a difference. Two suggestions

1) By elevation, leaning to the old British/Irish  
- Hills below 300m /1000feet
- Peaks above 600m/2000feet
- In between use your judgment

or 2) Shape
- A hill is rounded, a peak is pointed. You walk up a hill, you climb a peak. 

Anyway the current default with a pointed 'mountain top' is totally misguiding for Denmark.

This leans to National Geographic: "Hills are easier to climb than mountains. They are less steep and not as high. But, like a mountain, a hill will usually have an obvious summit, which is its highest point. According to the U.S. Geological Survey, there is no official difference between hills and mountains. 14 jul. 2023"

It does not take into account book titles like the Norwegian "Guide to the Danish mountains", written by Roger Pihl "Probably the only Norwegian to climb all Danish peaks over 100m".

**Comment by imagico** [comment]
Closing this as - like pointed out in https://github.com/gravitystorm/openstreetmap-carto/issues/4877#issuecomment-1740660719 - the tag has no broad support among mappers and is deliberately subjective in definition and there is broad consensus that `natural=peak` is universally suitable for local maxima in the topography.  A few examples illustrating the broad scope:

https://www.openstreetmap.org/node/3272706341
https://www.openstreetmap.org/node/1409025116
https://www.openstreetmap.org/node/529459463

Points mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/4877#issuecomment-1742583618 are about how tags should be used (based on the meaning of the values in the English language) and as such do not belong here - these can be of value to further develop consensus among mappers but that is a matter for a different venue.
