### ISSUE TITLE
Stop rendering highway=road?

### ISSUE THREAD

**Issue by dch0ph** [gravitystorm/openstreetmap-carto#4905]
### Expected behavior

`highway=road` is agreed to be poor tagging, at best a "fixme" for a better road type classification. Given that OSM Carto is generally conservative about rendering, it is odd that `highway=road` is both rendered and given a distinctive render.

### Screenshots with links illustrating the problem

(https://www.openstreetmap.org/#map=17/54.83907/-2.25666)

![image](https://github.com/gravitystorm/openstreetmap-carto/assets/20069699/dba881af-c95b-446b-8fea-ec442fb4e820)

Note bad join, caused by `highway=road` (grey fill) having same priority as highways with white fill:
>        residential     = {z = 330, roads = false},
>        unclassified    = {z = 330, roads = false},
>        road            = {z = 330, roads = false},

Usage peaked over 400k in 2012, and has been continually dropping since to just over 50k currently:
(https://taghistory.raifer.tech/#***/highway/road)
Presumably being gradually squeezed out by validators (JOSM at least warns about `highway=road`).

Options:
1. Stop rendering. Provides direct feedback that feature is not "map ready". Simplifies lengthy road code, and frees up some "colour space".

2. Rendering *as* unclassified would have most of these advantages, but runs counter to providing mapper feedback.

4. Just fixing the fill problem by lowering the priority of `highway=road` would be easy, but require a database reload.

Option 1 seems the best.

**Comment by imagico** [comment]
`highway=road` is the generally accepted tagging for roads when characteristics are insufficiently known to the mapper to apply a more specific tagging.  Its use has decreased substantially over the years mainly for three reason:

* more extensive surveying of larger parts of the planet with sufficient knowledge for a proper assessment.
* availability of higher resolution imagery for a larger fraction of the planet that often allows more reliable assessment even without ground survey.
* the lack of support for `highway=road` in many map styles has lead mappers to frequently just guess a highway class instead of conservatively applying `highway=road`.

We have rendered `highway=road` since the beginning of this project to support this as consensus tagging in the described use case while using a styling that clearly communicates this is not part of the normal road classification system.

Not rendering it any more would nudge mappers to guess a different road class (see last point above) - which would be counterproductive.  Rendering it like `highway=unclassified` would communicate this to be a synonym rather than a distinct tagging with very different meaning.  Putting it in z-order below all the other road classes rather than in the middle as right now would be worth considering.  If anyone sees any problems with that please raise them.

Generally speaking i think we should more widely render tagging well established to be specifically used for indicating missing relevant information as such.  We are also inconsistent in that regard - see #4906.

**Comment by dch0ph** [comment]
Good point that `highway=road` is relevant/useful in regions without good imagery. 

Dropping priority would be an easy fix.

Thee are some other weirdnesses in the priority table that could be addressed at the same time, e.g. why link roads appear well down the table, when I would assume that, say `motorway_link` should be ordered below `motorway` and above `trunk` so that things of the same colour are definitely filled above another?  The link roads are always going to be "more significant" than `highway=pedestrian` and `highway=living_street`.

**Comment by imagico** [comment]
No, the z_order is not a significance rating, it defines the drawing order.  That links are drawn below all other connecting  road types is a fundamental aspect of the way we depict roads.  Motorway links do not exclusively connect to trunk roads for example, primary, secondary and tertiary are just as common - like here:

https://www.openstreetmap.org/#map=16/48.2482/12.0424

motorway_link to unclassified is more rare but perfectly valid in principle.

If `highway=road` should be above or below link roads is of relatively low practical significance - i would be fine with either.  But since i would probably put it below tracks and paths it would automatically also be below link roads.

**Comment by dch0ph** [comment]
Thanks for explaining!

**Comment by imagico** [comment]
Closing this as declined for the removal of `highway=road`.  Opened #4908 for the z-order change.
