### ISSUE TITLE
Natural_reserve seems to have no purpose, and is to be confused with nature_reserve.

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4920]
Wanting to map leisure=nature_reserve, I confused it with landuse=natural_reserve.
I ended up without rendering, and wandering what was wrong. Like in #603.

So it seems that natural_reserve could be removed, or replaced by nature_reserve.

By the way nature_reserve is confusing to map anyway. 
I would expect it to be an area, multi polygon, or boundary, but it turns out to be just a (closed) line, so polygon.
I have to find out every couple of times I have been creating one.

**Comment by BertMule** [comment]
Sorry, not a matter of styling.
How do I remove this?

**Comment by danieldegroot2** [comment]
Ref https://community.openstreetmap.org/t/natural-reserve-seems-to-have-no-purpose-and-is-to-be-confused-with-nature-reserve/107638

@BertMule You should propose an automated edit (in your thread), see
https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct#Document_and_discuss_your_plans

Seems largely due to https://www.openstreetmap.org/changeset/73055500
