### ISSUE TITLE
House number hides building names when rendering tiles

### ISSUE THREAD

**Issue by Vectorial1024** [gravitystorm/openstreetmap-carto#4926]
### Expected behavior
Buildings with names AND with house numbers should perhaps show/contain the building name. (Whether the house number should be shown together is not a problem; could make them both show, I have no problem with that).

### Actual behavior
Buildings with names AND with house numbers show only the house number when rendering tiles.

### Screenshots with links illustrating the problem
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/17726797/02cedec0-cc0f-4b6a-9988-0f35ea9bb82a)
https://www.openstreetmap.org/#map=19/22.33664/114.14750

Building is labeled as "883" ("what even is 883????"), but when we look into it:
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/17726797/b2de6898-e0b6-4449-883c-c5b7e33fa284)

https://www.openstreetmap.org/way/354995748

The building actually has a name, which somehow was not rendered, picking the house number instead.

**Comment by imagico** [comment]
Building names have priority over housenumbers - see #3983.  Hence what you claim, that the housenumber is hiding the name here - is likely not true.

What probably happens instead is that the name rendering for the building collides with the POI label and therefore is not displayed - but the much smaller housenumber label is.

The underlying problem is the use of the name tag to tag lengthy multilingual labeling strings - which sometimes result in very large labels (with up to 12 lines in some cases in this area apparently) and therefore frequent collisions.  See also #4404.

**Comment by pnorman** [comment]
Yep, if the housenumber were not rendered it does not appear that there would be any text rendered for the building.
