### ISSUE TITLE
Unsandy desert rendering

### ISSUE THREAD

**Issue by Volodimir50** [gravitystorm/openstreetmap-carto#4929]
Good day. Is it possible to make natural=desert render in color on the main map and not only on humanitarian?
Deserts are not only sandy. It is a mistake to think that the desert is sand. I am now drawing the territory of Kazakhstan, there are deserts, but not from sand. There will be many such objects and I would like to see them in color. For example, on the humanitarian layer, it is perfectly visible. Add color rendering to the base layer as well.
Why are you closing my appeal, we haven't discussed it yet. I can't read the previous ones. Moreover, if such a question has already been addressed several times, it means that it is really relevant.

**Comment by HolgerJeromin** [comment]
ref closed #4928 from one hour ago...

**Comment by Volodimir50** [comment]
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/158048347/50c19c23-09e7-4643-ad48-775acfa01ae0)
it is a desert, but it is not sandy

**Comment by Volodimir50** [comment]
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/158048347/8f20e753-a458-471b-84ce-414da19be359)
it is a desert, but it is not sandy
it occupies a large area

**Comment by Volodimir50** [comment]
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/158048347/0cec3d38-2832-47f5-ae3a-4261368c9a12)

there are many such deserts here

**Comment by Volodimir50** [comment]
So why not make a color rendering for such deserts, as in the humanitarian layer

**Comment by Volodimir50** [comment]
I can't read the previous ones because I don't know English and I work exclusively with a translator

**Comment by imagico** [comment]
Any arguments regarding the rendering of natural=desert should go to #4488.  We like to not spread the discussion on a matter across many different issues opened over time so please refrain from opening new issues on this subject.

I suggest you read the previous discussion there and add any relevant new considerations you have that have not been discussed so far.  The diversity of desert environment has, however, already been discussed quite in depth in that issue.

Anyway - what you seem to be having here is a mapping problem rather than a rendering problem (there are currently four natural=desert polygons in Kazakhstan - three of which cover completely different geographic settings).  I suggest to discuss what concrete aspect of the local geography you like to map (like vegetation, non-vegetation surface material, landforms or other) and what is the best tagging to do so with you local community.  And whatever it is you like to map - reusing the old tagging natural=desert with all of its largely dysfunctional history is likely not a good idea.

As mentioned in #4488 we would look favorably on any new, well defined and consistently used tagging concepts for mapping aspects of arid regions.

> I can't read the previous ones because I don't know English and I work exclusively with a translator

I can't imagine what prevents you from translating other issues when you seem to be able to translate comments here.  In any case - being able to read, possibly through translation, previous comments made by others, is a necessity to participate in discussion here.  You are welcome to comment in your own language if that makes it easier to express yourself, but you have to be able to read what others write across different issues.
