### ISSUE TITLE
Remove rendering of shop=jewellery (but keep jewelry)

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#4962]
https://wiki.openstreetmap.org/wiki/Tag:shop%3Djewellery
has been deprecated but the **single existing** node in the osm database is still rendered:

https://www.openstreetmap.org/node/10798568929

![image](https://github.com/gravitystorm/openstreetmap-carto/assets/2410353/85845c10-c1fd-4dac-a020-dc46fea4a75d)

I have no rendering stack available, so I could only do a blind fix.

Ref deprecation in iD editor since 2019:
https://github.com/openstreetmap/iD/pull/6266

**Comment by imagico** [comment]
In general i am wary about removing support for tags that have gone out of use due to mechanical edits (and potentially subsequent suppression of continued use by self appointed tagging police).

In this case, however - while the reduction to almost zero use is largely due to a mechanical edit in late 2022 - the tag has never had wide adoption in the first place with peak use in 2018 being around 350 while the competing tag back then had already about 100 times as much use.  Hence i would be in support of removing this .
