### ISSUE TITLE
Rendering for POIs

### ISSUE THREAD

**Issue by MortalEngineXXII** [gravitystorm/openstreetmap-carto#4968]
* The following tags need to be displayed: [healthcare=blood_donation](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dblood_donation), [healthcare=sample_collection](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dsample_collection), [healthcare=psychotherapist](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dpsychotherapist)
* The specified tags are not displayed in OSM Carto
* Examples of POIs that are not displayed in OSM Carto: https://www.openstreetmap.org/node/11916144027, https://www.openstreetmap.org/node/11080571405, https://www.openstreetmap.org/node/9894462149

**Comment by imagico** [comment]
Thanks for the suggestions.  However for unrelated tags like this please create feature requests separately for every tag you want to see rendered because design work and the decision if or not to render need to be done individually for every tag.

* `heathcare=blood_donation` is already covered in #4222.
* `healthcare=psychotherapist` had been suggested back in #2938 but has never been individually assessed.  See #4183.  6797 uses.
* `healthcare=sample_collection` was mentioned in #3584 but has not been discussed on its own.  1163 uses, about 200 of these with `sample_collection=*`.
