### ISSUE TITLE
Render name=* on landuse=religious

### ISSUE THREAD

**Issue by BorutAtGit** [gravitystorm/openstreetmap-carto#4999]
### Expected behavior
name=* for landuse=religious shown (parhaps at , or above zoom levels 15-16)

### Actual behavior
name=* for landuse=religious not shown at any zoom level

### Screenshots with links illustrating the problem
https://www.openstreetmap.org/way/802140932#map=18/41.24871/21.60784

###Background
If I am not wrong, Carto is currently not showing name=* for landuse=religious at any zoom level. I am currently traveling through N.Macedonia. There are quite a lot of monasteries tagged with that combination arround, but apparently their names are not shown. Thanks!

**Comment by imagico** [comment]
Thanks for the report.

`landuse=religious` is indeed not rendered with a name label.  There is dead code in `amenity-points.mss` for this - but the corresponding SQL query does not include `landuse=religious` features.

I have doubts that adding name label rendering for `landuse=religious` is a good idea for us.  In most cases where a name is tagged (which is only around 21 percent) - including this one -  the name refers to a more specific feature.  In this case that would be the monastery (`amenity=monastery`) - for which we have an open issue #3036.  I would prefer us rendering specific religious features like that with a name label rather than generically `landuse=religious`.

**Comment by HolgerJeromin** [comment]
This was reported in #4214

**Comment by imagico** [comment]
Indeed, thanks @HolgerJeromin - closing as duplicate.
