### ISSUE TITLE
Niagara Falls Double vision

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#5001]
### Expected behavior
![Screenshot 2024-08-11 17 56 59](https://github.com/user-attachments/assets/0209807a-b732-4959-8ef6-71dd433987a8)

### Actual behavior
![Screenshot 2024-08-11 17 56 45](https://github.com/user-attachments/assets/e0d8f2f1-ec36-43a3-99ce-98600611518f)

I'm not sure how Google manages to avoid the "Niagara Falls Double vision" problem.

They must use some pretty fancy algorithms, else they would end up with what we see on the second image.

I am just saying the second image, although 100% correct (as indeed there are two Niagara Falls cities there), is not as refined as the first (Google) image. So maybe some refinements could be made.

Yes, upon zooming in, a second Niagara Falls eventually does appear on Google. But by that time both are safely on either side of the river too.

**Comment by imagico** [comment]
Thanks for the report.

Please comply with our [contributing guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md). This lacks link to the location in question.

I am closing this as _wontfix_ because there are two cities mapped hence we display two cities.  We intentionally display two names in that case as mandated by our goal to provide mappers with intuitively understandable feedback on their work.  There is no way for us to determine if this is a case of duplicate mapping or if it is a case of two verifiably distinct features that happen to have the same name without relying on outside sources.  Should mappers in the future develop consensus on a way to indicate that difference we could discuss taking that into consideration.
