### ISSUE TITLE
Name does not show on leisure=park when relation

### ISSUE THREAD

**Issue by harrija0** [gravitystorm/openstreetmap-carto#5015]
Leisure=park features often have names. Would expect each park to display the name. 

This works when it is a simple area. When the area is a multipolygon to comply with no overlapping lines the names do not show for relations. The wiki page says leisure=park is supported on areas and multipolygon relations. https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpark

The below image shows many smaller parks named on the left side. However the area to the right of the golf course is also a park named Patton Recreation Area. The name does not display. The area is hashed red because this is on a military installation.
![image](https://github.com/user-attachments/assets/7b215342-8766-42d8-8a9c-63ced50cc643)
https://www.openstreetmap.org/#map=16/32.36241/-84.94498

**Comment by imagico** [comment]
The assumption you make here can be easily proven wrong:

https://www.openstreetmap.org/relation/4092807

The reason the label is not shown in your case (https://www.openstreetmap.org/relation/14523405) is probably because it is blocked by another symbol/label, here most likely the Gray Hill symbol.

Closing this as invalid - concrete suggestions for changing out label/symbol prioritization would be a separate matter, see also #3880.
