### ISSUE TITLE
Power lines on standard map Map Key

### ISSUE THREAD

**Issue by Fizzie41** [gravitystorm/openstreetmap-carto#5016]
We've had a query come into the DWG from somebody asking if the lines shown on the standard map are actually power lines? he was confused as there is no listing on the Map Key for them.

Is the Map Key controlled by Carto, & if so, could power lines be included on it?

**Comment by mmd-osm** [comment]
The map key is independently managed in the osm website repo. You need to raise an issue here:

https://github.com/openstreetmap/openstreetmap-website/issues

**Comment by imagico** [comment]
Yes, the map key on osm.org is not maintained by us.

There is an equally independently maintained hand curated list of features of OSM-Carto on the osm wiki:

https://wiki.openstreetmap.org/wiki/OpenStreetMap_Carto/Lines

which is pretty good but naturally not guaranteed to be completely accurate.  And there is [StyleInfo](https://imagico.de/map/styleinfo/) - which is probably currently the most exhaustive reference of OSM-Carto features - but, due to the way it is created, not guaranteed to be complete.  And it is not updated regularly because of the lack of capacity to do so.  Power lines you find there in:

https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=power&value=line
https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=power&value=minor_line

and you can also see that they are very similar in appearance to line barriers like:

https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=barrier&value=fence

We have had discussion on creating a map key ourselves in #1928 - but because the documentation on the wiki was (and still is) not too bad and because of the significant work that would be required to produce and maintain something sustainable and practically useful this never went beyond principal considerations.

Closing, as the question is answered i think.
