### ISSUE TITLE
Leisure=track should not be an area

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#574]
Leisure=track is currently rendered as area. However, it should be rendered as way.

This requires a change to the osm2pgsql style sheet.

See also https://trac.openstreetmap.org/ticket/2339

**Comment by kocio-pl** [comment]
According to [Wiki](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtrack) it should be rendered as area if there is also area=yes. However I'm not able to prepare PR resolving this issue, because I don't know what changes should be done exactly.

**Comment by math1985** [comment]
This could be fixed by https://github.com/openstreetmap/osm2pgsql/pull/346. If osm2pgsql doesn't accept ths change we could also create our own .lua file.

However, I'm still not fully sure what the desired behaviour is?

**Comment by kocio-pl** [comment]
For me by default it should be rendered as a line and as an area when a closed line is tagged with area=yes.

**Comment by polarbearing** [comment]
... and as an area when it is a multipolygon.

**Comment by SomeoneElseOSM** [comment]
@math1985 as Lonvia said in https://github.com/openstreetmap/osm2pgsql/pull/346#issuecomment-187372890 if you're going to move to lua processing in OSM's "standard" style, surely you're going to use custom lua processing for that style, and not whatever standard/example "style.lua" is included with osm2pgsql?

There are places where using lua instead of SQL to do processing would vastly simplify the resulting SQL that needs to be written - I think it would be very beneficial to make use of that capability where appropriate.

(naturally "moving to lua processing" assumes that the drawbacks of that, such as database reloads if e.g. tag consolidation is done have been considered and the change is thought to be beneficial overall - that's a much larger issue than just one style change)

**Comment by math1985** [comment]
> @math1985 as Lonvia said in openstreetmap/osm2pgsql#346 (comment) if you're going to move to lua processing in OSM's "standard" style, surely you're going to use custom lua processing for that style, and not whatever standard/example "style.lua" is included with osm2pgsql?

I haven't thought of that yet really. The process of moving to hstore is going extremely slow (it's already on the agenda for multiple years), so at the moment I'm inclined towards rolling out a solution that is as simple as possible first, so at least we can get something done, rather than keep discussing without ever accomplishing something.

Also, some of our users (for example @gravitystorm himself) use a single PostGIS database for multiple rendering styles, which also suggests not making to complex / style-specific decisions in the lua file.

**Comment by kocio-pl** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2238 (lua branch).

**Comment by HolgerJeromin** [comment]
I think this should be renamed and reopened. Or we need a new issue.

https://www.openstreetmap.org/way/144179903 is not rendered on [master and lua](https://lua.osm-carto.paulnorman.ca/#18/51.18102/6.69429), so we have no style definition.

**Comment by imagico** [comment]
Opened new issue #2632.
