### ISSUE TITLE
Recommend -G flag for multipolygons

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#59]
Relations with multiple members like http://www.openstreetmap.org/?lat=57.011&lon=-6.428&zoom=10&layers=M are rendered multiple times and are a bit of a cartographic disaster.

One possible fix is to import with osm2pgsql in -G mode to create a MULTIPOLYGON instead of multiple POLYGONs. @springmeyer informs me that mapnik should render the label on just the largest POLYGON within the MULTIPOLYGON by default. 

Do we know anyone running with -G?

**Comment by math1985** [comment]
With the upcoming database import, I think we should decide what we want to do with this issue.

I'm not sure if the G option always has a good effect. If a company is spread over multiple buildings some distance apart, is it really an improvement to only label one of them? Or is this not a good use of multipolygons?

Also, would -G have the effect that Denmark is no longer rendered as Denmark, since Greenland will receive the Denmark label as biggest area?

**Comment by imagico** [comment]
Cartographically you should split this into two questions:

1. should features with multiple components receive multiple labels
2. if not should the label be placed on the largest element or somewhere around the center of weight of the whole feature.

The answer to both depends on the geometric configuration (i.e. size and position of the individual components compared to the whole).  When you place multiple labels you will usually want to change those of the smaller elements in content, i.e. not label 'Denmark' but 'to Denmark' - this is tricky with the multitude of languages of course.  But more importantly these should have lower priority than the main label.

Denmark/Greenland is not a problem though - in OSM Greenland is fully independent.  In general there are very few admin units where the largest component is not the primary one.

**Comment by HolgerJeromin** [comment]
The rendering of this [mosque](http://www.openstreetmap.org/relation/3006134) looks like a tagging error...

**Comment by jojo4u** [comment]
One more example to consider: University with many sites scattered throughout a city: https://www.openstreetmap.org/relation/5294212
This was changed recently by @matkoniecz from type=site to type=multipolygon. If only one label gets rendered we need another tagging style for this "collection style" of multipolygons, perhaps site get's a comeback?

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 17 mag 2016, alle ore 20:21, jojo4u <notifications@github.com> ha scritto:
> 
> One more example to consider: University with many sites scattered throughout a city: https://www.openstreetmap.org/relation/5294212
> This was changed recently by @matkoniecz from type=site to type=multipolygon. If only one label gets rendered we need another tagging style for this "collection style" of multipolygons, perhaps site get's a comeback?
> 


the situation is a little broken on a semantic level, nothing this style sheet can fix.
We are missing a standardized way to say what kind of university facility/entity it is, and to which university it belongs. Is every room that is used by an university "a university" by itself? Likely not.

**Comment by matkoniecz** [comment]
I am unsure whatever it is a good idea. For start, original example that used to be 

![isles-duplicate](https://f.cloud.github.com/assets/1190866/1234178/a8f584f0-2960-11e3-929e-86ea3f63a6ee.png)

is now rendered as (with label disappearing, as big area on this zoom level is too large, it is visible one zoom earlier)

![selection_003](https://cloud.githubusercontent.com/assets/899988/15942657/9a2a3fc4-2e85-11e6-9f43-12933cba3204.png)

And in many cases, for example for

![selection_004](https://cloud.githubusercontent.com/assets/899988/15942761/26ea101a-2e86-11e6-9566-e974649e3860.png)

I think that -G would make here situation worse. Zooming to islets like http://www.openstreetmap.org/#map=18/57.05311/-6.36605 gives more questionable results like

![selection_005](https://cloud.githubusercontent.com/assets/899988/15942808/621b0518-2e86-11e6-89e6-020405190b07.png)

Other examples where -G would make situation worse - http://www.openstreetmap.org/#map=16/50.0676/19.9190 (Akademia Górniczo-Hutnicza, university label)

![selection_006](https://cloud.githubusercontent.com/assets/899988/15942854/94a9a55c-2e86-11e6-8190-d31aec809b4f.png)

http://www.openstreetmap.org/#map=15/50.0710/19.9933 (Park Lotników Polskich, park label)

![selection_007](https://cloud.githubusercontent.com/assets/899988/15942903/c2828e6c-2e86-11e6-9ada-88540928bd8a.png)

http://www.openstreetmap.org/#map=16/50.0454/19.8382 (vineyard Winnica Srebrna Góra)

![selection_008](https://cloud.githubusercontent.com/assets/899988/15942923/df3ed542-2e86-11e6-9180-a6d51e488e80.png)

http://www.openstreetmap.org/#map=17/50.07908/19.89490 - allotments Złoty Róg

![selection_009](https://cloud.githubusercontent.com/assets/899988/15943064/83e1c532-2e87-11e6-9587-d08c3009142a.png)


I would argue that -G will result in more harm than benefits, though I admit that I did no testing with this places and some may be tagged as separate closed ways rather than as a single multipolygon - but "informs me that mapnik should render the label on just the largest POLYGON within the MULTIPOLYGON by default" is quite clear.

All places are from my city as this way I was able to quickly find places split by roads, but I would not expect Kraków to be outlier for how often such situation happens in proportion to islet example from original report.

But I am unaware about any cases where -G would significantly improve situation and many that would make it worse.

**Comment by matkoniecz** [comment]
Note that it may depend on cultural factors - situations like http://www.openstreetmap.org/relation/3006134#map=19/51.16621/6.91938 may be common in places where towers are typically not connected to main structure (minaret entry on enwiki has "usually either **free-standing** or taller than associated support structure").

**Comment by SomeoneElseOSM** [comment]
Re whether -G would on balance improve things or not - I've used it with an osm-carto based stylesheet for a couple of years, and I think that on balance things work better.  If you can think of somewhere within http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=-5.380469,51.533914,2.155273,54.603809 you'd be interested in seeing the effect from, I can post an image if it helps.

**Comment by imagico** [comment]
> And I am unaware about any cases where -G would significantly improve situation

The most important one is probably the brainless admin unit labeling happening right now:

http://www.openstreetmap.org/#map=7/-58.066/-26.724
http://www.openstreetmap.org/#map=5/59.911/-173.914
http://www.openstreetmap.org/#map=8/28.739/-16.867

In some cases like place=archipelago but possibly also for other multipart multipolygon cases selecting the labeling points from SQL either based on convex hull or using several points for subpolygons could be an alternative.  Of course ultimately mapnik should offer better labeling options on its own.

**Comment by matkoniecz** [comment]
Especially for http://www.openstreetmap.org/#map=8/28.739/-16.867 

![selection_011](https://cloud.githubusercontent.com/assets/899988/15943692/87181460-2e8a-11e6-81c3-e485412ce8f1.png)

-G in my opinion would make situation worse. Currently it is at least possible to know which island belongs to each country. The same applies in my opinion to USA/Russia

![selection_012](https://cloud.githubusercontent.com/assets/899988/15943741/c2980b58-2e8a-11e6-93b2-0aa74bc77e23.png)

Some better labelling would be better but for me in this cases for -G/without -G choice I would prefer too many duplicated labels over missing data.

And

![selection_013](https://cloud.githubusercontent.com/assets/899988/15943796/fc1259c4-2e8a-11e6-8610-548de8fe4803.png)

is hilariously horrible in way that makes clear that it was labelled by a simple computer program.

> you'd be interested in seeing the effect from, I can post an image if it helps.

If it would not be too much trouble examples are welcomed.

**Comment by imagico** [comment]
I disagree - showing duplicate labels here is nonsense.  It might appear to be a way to show which admin units certain islands belong to but quite clearly one of the worst and most wasteful ways to do this.  You will probably hardly find any other map that does this.

Not showing these duplicate labels will free room for showing labels for the islands which makes much more sense.

In any case keep in mind that with non-flattened multipolygons in the database you have more freedom since you can at least in principle generate separate labels for the different components.  If you have them flattened however you cannot do it the other way round.  So it seems it is the more flexible approach.

What i wrote in https://github.com/gravitystorm/openstreetmap-carto/pull/1134#issuecomment-66908771 still applies here - implementing rules like that might be difficult but with flattened multipolygons it is definitely impossible.

**Comment by gravitystorm** [comment]
> In any case keep in mind that with non-flattened multipolygons in the database you have more freedom since you can at least in principle generate separate labels for the different components. If you have them flattened however you cannot do it the other way round. So it seems it is the more flexible approach.

Exactly. If there's a situation where duplicate labels makes sense, we can write an easy SQL query to label each polygon within the multipolygon. But without -G we're stuck in the current situation and have no good options.

I'm sure the -G thing in osm2pgsql is just for historical reasons - i.e. it should really be on by default, and not even provide an option to switch it off, but hey-ho.

**Comment by jojo4u** [comment]
All country borders and the "[Small Isles National Scenic Area"](https://www.openstreetmap.org/relation/284135) are tagged as type=boundary. Perhaps a type=boundary and type=multipolygon can be treated differently?

**Comment by pnorman** [comment]
> Perhaps a type=boundary and type=multipolygon can be treated differently?

No, the option is for all geometry formation.
