### ISSUE TITLE
Use alternate source for world_boundaries-spherical.tgz

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#61]
We should use an alternate source for this file. I think it's vmap0 but I'm not sure

**Comment by matthijsmelissen** [comment]
Re-opening as well. Would osm-data be disastrous (due to the coastline paradox)?

**Comment by pnorman** [comment]
We've changed enough stuff around since we did this, so it's worth rechecking.

**Comment by jeisenbe** [comment]
How is this file currently used? 

1) I don't see where any of the components are used in the current project.mml code. The strings "world_bnd_m" and "world_boundaries_m" are only found in install.md in the instruction about downloading shapefiles, and in get-shapefiles.py. The string "builtup_area" is only found in the downloaded data files themselves. 

2) The data files have not been modified since 2007 (world_bnd_m.*) and 2008 (world_boundaries_m.*), it appears. 

3) I've deleted the whole `/world_boundaries` directory and found that the map renders without problems down to z2, but I had issues at z0 and z1

**Comment by jeisenbe** [comment]
Actually, it renders fine at z0 and z1 now that I've change my localconfig.json file back to `metatile: 2`
I couldn't render the current master branch at z0 or z1 with `metatile: 8` even with the `/world_boundaries` directory in the correct place, so that's probably not related?

**Comment by jeisenbe** [comment]
@pnorman - is this file still needed? It doesn't appear to be necessary for rendering

**Comment by pnorman** [comment]
I haven't touched that part of the code in ages so don't know.

**Comment by sommerluk** [comment]
The last usage of world_boundaries-spherical.tgz had been removed in 5327dbb (buildup areas). Closing.
