### ISSUE TITLE
Pipeline should be visible

### ISSUE THREAD

**Issue by Cetusek** [gravitystorm/openstreetmap-carto#640]
Why are pipelines not rendered?
They are good landmarks.

**Comment by kocio-pl** [comment]
> Maybe dark gray line, wider than barriers? It is a special kind of barrier, so it should be OK to have it similar. With bridge casings for elevated ones (with bridge=*).

Sounds good for me. 

I'm also thinking about segmented line, resembling pipe joinings (rough ASCII sketch):

`|——||——||——||——||——|`

**Comment by javbw** [comment]
> Maybe With bridge casings for elevated ones (with bridge=*).
> 
> I'm also thinking about segmented line, resembling pipe joinings (rough ASCII sketch):
> 
> |――||――||――||――||――|
> 
Where I am there are a lot of "pipe bridges" - a buried 1m pipe pops out of the ground, crosses a river, and goes back underground. 

Any render that would help people not confuse them with a pedestrian crossable bridge would be wonderful - as they are often near or go over other ways. I know that the routing engines would ignore them, but visually would look like a bridge a person could cross (but are gated off and very dangerous). 

Javbw

**Comment by kocio-pl** [comment]
It looks like Mapnik currently offers only simple line endings - and of course CartoCSS too:

https://github.com/mapnik/mapnik/wiki/LineSymbolizer#linesymbolizer
https://www.w3.org/TR/SVG/painting.html#StrokeLinecapProperty
https://carto.com/docs/carto-engine/cartocss/properties#line-cap-keyword

**Comment by kocio-pl** [comment]
I have finally found a way to do it:

![screenshot-2018-5-2 openstreetmap carto kosmtik](https://user-images.githubusercontent.com/5439713/39498616-60569230-4da9-11e8-8027-4438121e9a8b.png)

The trick was to use image (`LinePatternSymbolizer` in Mapnik), the same as in the cliff rendering - above rendering is done simply with replacing the [SVG file](https://gist.github.com/kocio-pl/5db38f80ca0db92b60d22d829486546b#file-pipeline-svg). The only problem was that segments had no space between them, despite the space on both ends. However adding invisible blocks (alpha=0) helped.

Now we can get back to design. What color should be used? What segment length (currently 13 px total, with endings x 1 px), endings size (5x1 px) and the space between segments (1+1=2 px)?

**Comment by Tomasz-W** [comment]
Surely it's too strong at the moment. It also is too sililar to aerialway=* rendering, eg.
https://www.openstreetmap.org/#map=16/46.2161/6.7975

**Comment by kocio-pl** [comment]
The spaces are too small? What's your proposition?

[All the lines are similar](https://wiki.openstreetmap.org/wiki/LinesTab) and it's just the convention. I believe the context will make it clear - aerialways consist of short straight lines and have stations on both ends, pipelines tend to be long and curved.

**Comment by turnsole80** [comment]
I like it. If you can get it to work, i'll the same ideas to carry over to #1999 , because right now i'm drawing a blank there.

Colour wise, i'd go with that generic grey you use for things like bunkers, etc

**Comment by eigenwillig** [comment]
Could you please publish the code with LinePatternSymbolizer here?

**Comment by kocio-pl** [comment]
Sorry but no, I lack the time for the project currently, I focus on next release now. But anyone can copy the code for a cliff rendering and tune it using my SVG file as a base (it can be adjusted too). Anybody willing to make the PR?

**Comment by kocio-pl** [comment]
I wanted to wait a bit before some colors for borders are decided (especially country borders), but it seems to be resolved now, so the question is what color should be used for showing pipelines?

**Comment by kocio-pl** [comment]
I guess z14 would be good (the same as power lines) probably using some dark purple - grey is too generic and may resemble railways, while pipelines are much less dense, so it should not take too much attention anyway (dense items should be muted, sparse can be brighter).

**Comment by jeisenbe** [comment]
@flacombe this would be good to work on prior to #3180 or #3179.

**Comment by IgorEliezer** [comment]
> Now we can get back to design. What color should be used? What segment length (currently 13 px total, with endings x 1 px), endings size (5x1 px) and the space between segments (1+1=2 px)?

Could the segment length be longer, like on the map below?

![image](https://user-images.githubusercontent.com/4673289/64756543-b7fee980-d505-11e9-840d-135b08215c57.png) (OSM: https://www.openstreetmap.org/#map=17/-23.81522/-46.50371)

 I just think it will be a bit too dense in places where there are packs of pipelines running close together, such as this: https://www.openstreetmap.org/#map=18/-23.86584/-46.45869.

**Comment by jeisenbe** [comment]
I agree with the comment above https://github.com/gravitystorm/openstreetmap-carto/issues/640#issuecomment-46413344 - could be similar to barriers, but wider (at least at high zoom levels). The dashed / segmented idea is worth testing, but perhaps suggests an underground pipeline? 

I checked a few map legends which I've previously downloaded. The French, British and Norwegian maps did not list this as a feature.

The Australian topo maps showed this:
![pipeline-australian-topo-map-legend](https://user-images.githubusercontent.com/42757252/64763721-917b9580-d57b-11e9-8dd6-1b52fac6f2ff.png)

Old USGS topo maps showed this:
![pipeline-legend-old-USGS-topo-maps](https://user-images.githubusercontent.com/42757252/64762864-e1595d00-d579-11e9-84bf-69fb04330b4a.png)

Newer USGS legend:
![pipeline-legend-new-usgs](https://user-images.githubusercontent.com/42757252/64762875-e8806b00-d579-11e9-84bc-957f8409b848.png)

Since those styles also show contour lines, they tend to show many features in black. We can consider using gray or another less prominent color instead, and we have the complication of different zoom levels to consider, and rendering many more features, including dashed gray lines for some types of underground / under contruction railways.

**Comment by jeisenbe** [comment]
@flacombe - I highly recommend trying Docker, it works quite easily, if you have a good internet connection and a little time.

**Comment by jeisenbe** [comment]
OK, I said I wasn't going to work on this issue, but then I did.

https://www.openstreetmap.org/#map=17/54.74094/20.32948.png
z19
![z19-pipeline3-after1](https://user-images.githubusercontent.com/42757252/67732898-2bba6e80-fa40-11e9-85ad-9aa7660051f5.png)
z18
![z18-pipeline3-after1](https://user-images.githubusercontent.com/42757252/67732902-2d843200-fa40-11e9-96ed-58a0371f4cdc.png)
z17
![z17-pipeline3-after1-17:54 74094:20 32948](https://user-images.githubusercontent.com/42757252/67732903-2e1cc880-fa40-11e9-82c5-80d284a9559b.png)

I was surprised that it is hard to find long, straight pipelines. These turn out to be mainly underground (except in Alaska), so most of the rendered pipelines are only a few hundred meters or few kilometers long. Many are water pipelines associated with hydroelectric facilities or water aquaducts, though there are also many oil and gas pipelines connecting industrial facilities and ports. 

котельная  - https://www.openstreetmap.org/#map=15/54.6602/21.0624
![z19-котельная-pipeline-after1](https://user-images.githubusercontent.com/42757252/67732767-c5cde700-fa3f-11e9-8e3e-b18db3fa7fa3.png)

![z17-котельная-pipeline-after1](https://user-images.githubusercontent.com/42757252/67732779-cebeb880-fa3f-11e9-8144-8b0bf90155a3.png)

![z16-котельная-pipeline-after1-15:54 6602:21 0624](https://user-images.githubusercontent.com/42757252/67732796-e26a1f00-fa3f-11e9-93b0-ada5196f4cb8.png)

I checked if we could try `usage=transmission` vs `usage=distribution` to render pipelines earlier or later, but these tags are not very common yet, especially together with `location=overground/overhead` which are the ones that will render.

I've found that at high zoom levels would might be able to render a different center line color depending on the `substance=*` - e.g. blue for water, something different for natural gas or oil.

Any ideas on what colors would be appropriate for gas and oil pipelines?

https://www.openstreetmap.org/#map=19/53.19025/-3.84260
z19 water pipelines
![z19-snowdonia-water-pipelines](https://user-images.githubusercontent.com/42757252/67734571-c026d000-fa44-11e9-8bf0-fd32e4514c92.png)

z18 water
![z18-snowdonia-water-pipelines-after](https://user-images.githubusercontent.com/42757252/67734579-c2892a00-fa44-11e9-902f-1f45ef3547d9.png)

z16
![z16-snowdonia-pipelines-substation-after](https://user-images.githubusercontent.com/42757252/67734581-c61cb100-fa44-11e9-97cb-bec9fc62e21d.png)

z14
![z14-snowdonia-pipelines-after](https://user-images.githubusercontent.com/42757252/67734589-ca48ce80-fa44-11e9-91a6-cc28424c8d46.png)

z13 - probably the lowest possible level, since we don't have a way to distinguish short and long pipelines, though z14 may be the best limit. z12 would be fine for usage=transmission, if this were actually a common tag. 
![z13-snowdonia-dolgarrog-pipeline](https://user-images.githubusercontent.com/42757252/67734634-e5b3d980-fa44-11e9-9edc-717be46a73af.png)

**Comment by jeisenbe** [comment]
Test with very short pipelines, substance=gas (rendered in `#d0d0d0`):

https://www.openstreetmap.org/#map=18/53.23763/-3.05405
![z19-gas-pipelines-#d0d0d0](https://user-images.githubusercontent.com/42757252/67743644-9f6d7300-fa62-11e9-850f-5038e0669863.png)

**Comment by IgorEliezer** [comment]
> Any ideas on what colors would be appropriate for gas and oil pipelines?

Based on pipe color code standards, which may vary a bit depending on the region:
- blue = water
- green = sewage
- yellow = gas
- orange = corrosive fluids
- brown = combustible fluids

----

If you want to test overground pipelines:
- Water penstock (8 lines): https://www.openstreetmap.org/#map=18/-23.86580/-46.45821
- Gas (4 lines): https://www.openstreetmap.org/#map=17/-23.85063/-46.50240

**Comment by kocio-pl** [comment]
Another idea might be to use some dots inside, since it's hollow. I don't know however if it's technically possible or how to use it exactly.

In general this solution looks quite good, I think it's better than my original idea.

**Comment by javbw** [comment]
I am wondering what the "bridge" rendering is for pipelines. Will it use a similar dark gray casing? 

The renderings so far look really great. 

There are a lot of pipeline bridges in Japan - a large structure With an integrated pipeline supported for the distance where it crosses a river above-ground (and then disappears back underground). 

 I map a lot of pipeline bridges, which are more than just "a pipe that happens to cross a stream" - there are plenty of those too, but there are also plenty of these large "pipeline bridges" as well. 

For all the exposed hydroelectric pipelines on mountainsides, the current renderings will look great. 

Keep up the great work! 

Javbw

**Comment by kocio-pl** [comment]
Looking at https://wiki.openstreetmap.org/wiki/Key:substance and https://taginfo.openstreetmap.org/tags/man_made=pipeline#combinations it looks like the most popular substances are:

- 14.78% | substance=gas
- 11.29% | substance=water
- 6.97% | substance=oil

with all the others below 1000 usage limit (or unused), which means (41.61%-33.14%) 8.47% combined. It might be good to test even the low usage to 

There is also https://taginfo.openstreetmap.org/keys/pipeline#values with some values like water, aqueduct, sewer,␣water, heating_pipeline or sewer, but all below 1k.

There is also usage defined on the wiki, but only 5.34% of cases are defined, with not a single one above 1k limit.

**Comment by jeisenbe** [comment]
@kocio-pl, `substance=gas`, `substance=water` and `substance=oil` are by far the most common, making up 80% of all uses of the key, so these are the 3 that have been tried so far.  

The next is `substance=heat` but this isn't recommended on the wiki (should be `steam` or `hot_water`, but these are still rare: [640 ways](https://overpass-turbo.eu/s/NyC) overground or overhead combined). After that is `substance=sewage` but this is still under 2000 uses overall, and only [238](https://overpass-turbo.eu/s/NyB) are `location=overground/overhead`, so probably rendering the top 3 is enough.

The main benefit is rendering `substance=water` so that water pipelines are logically connected to canals and water tunnels.

`type=water` is also still quite common, with 7000 uses, but this has been replaced by `substance=water`, so we should not render it.

@IgorEliezer - thank you.

> - blue = water

This one is logical and the rendering is intuitive

> - green = sewage

If this tagging becomes more common we could consider it later, perhaps a blue-green hue?

> yellow = gas

I tried this, but it looks too similar to secondary roads, I'm afraid. That's why I tried `#d0d0d0` above

> orange = corrosive fluids

Not very common (less than 200 of the top two, `substance=ammonia` and `substance=chemical`). And orange would also look similar to primary or trunk roads.

> brown = combustible fluids

For this `substance=oil` is quite common. I'll need to find some different locations to test this, as well as darker gray (maybe `999`), my first thought.

**Comment by jeisenbe** [comment]
> There are a lot of pipeline bridges in Japan - a large structure With an integrated pipeline supported for the distance where it crosses a river above-ground

I've included `bridge=yes` and `=aqueduct` as an equivalent to `location=overhead` in the code, so they will render. 

Currently the rendering tests have been done with all pipelines above bridges and below aerialways (actually in the aerialways layer, but rendered underneath them - they could also go in the bridges layer so that they could render below bridges that have a higher layer tag, but this would be more complicated), so like bridges they go above all roads and waterways, since this seems to match actual practice: if they are overground/overhead they have to go above roads, or else they should be location=underground for that section. 

I don't think it would be easy to make an intuitive pipeline-bridge rendering, but it is not necessary: these are not bridges which you can walk across, unlike a railway, road or waterway bridge.

**Comment by javbw** [comment]
> On Oct 30, 2019, at 4:24 PM, Joseph E <notifications@github.com> wrote:
> 
> I don't think it would be easy to make an intuitive pipeline-bridge rendering, but it is not necessary: these are not bridges which you can walk across, unlike a railway, road or waterway bridge.

Perhaps the rendering is unneeded, but when you have a large bridge structure (long arching Steel supports and pier structures similar to a regular bridge, but the load it carries is a pipeline, it seems like it should be rendered similarly to other ways that have bridge=* also tagged on it. 

I’m not talking about an overhead pipe on some supports that happens to over a stream, not a long section of plain pipeline that crosses a river, but a very large and elaborate structure that crosses a river that contains within it a pipeline. 

https://www.openstreetmap.org/way/304370909 here is an example. It might be mapped incorrectly, but you can see the size of the structure I am talking about in imagery. 

If you feel that rendering a bridge outline is unnecessary, okay. But in the same way a bridge carries a road bed, a set of rails, or concrete footway, these large structures also carry pipeline across a difficult crossing, and are more than a mere tunnel that happens to be above ground or overhead. 

I think you have done a good job with the regular pipe rendering, and if it is too difficult to implement, that’s okay - but I do think there is a reason to have a “bridge” version of pipeline. 

Javbw.

**Comment by jeisenbe** [comment]
> rendering a bridge outline

The physical outline of a bridge structure is rendered from the tag `man_made=bridge`, which is mapped as an area. This tag is also appropriate for pipeline bridges, though it's not exactly what you were asking for.

**Comment by javbw** [comment]
> the tag man_made=bridge, which is mapped as an area. This tag is also appropriate for pipeline bridges, though it's not exactly what you were asking for.
> 
I was thinking the same thing, and I guess it's the solution for now, but there are a couple dozen pipe bridges like this in my region of Japan alone (Whereas I can't remember seeing one before in California), so eventually a simple way-only rendering for a pipelines+bridge=yes should be developed if it's not impossible or ruins the current rendering ('cause it is a great rendering for a pipeline). 

Thanks for the replies. 

Javbw

**Comment by jeisenbe** [comment]
Tests with different colors for the main types of `substance=` - water, gas and oil, as well as null:

Dark brown for oil, gray for gas, water-color for water:
![z19-pipeline-colors-brown-gray-blue](https://user-images.githubusercontent.com/42757252/68104520-bad2f500-ff1e-11e9-8230-5cc828886551.png)
![z18-pipeline-colors-brown-gray-blue](https://user-images.githubusercontent.com/42757252/68104538-cc1c0180-ff1e-11e9-9690-31c448f91a1e.png)
![z16-pipeline-colors-brown-gray-blue](https://user-images.githubusercontent.com/42757252/68104527-beff1280-ff1e-11e9-8d3b-2720afb75c4d.png)
![Uploading z17-pipeline-colors-brown-blue-gray.png…]()

Dark gray for oil, light gray for gas and water same:
![z19-pipeline-test-blue-grays](https://user-images.githubusercontent.com/42757252/68104558-d9d18700-ff1e-11e9-9399-c1fe5c5cab0f.png)
![z17-pipelines-colors-blue-gray](https://user-images.githubusercontent.com/42757252/68104571-f241a180-ff1e-11e9-8e9a-7ea2e081a8a5.png)

**Comment by kocio-pl** [comment]
I think brown for oil makes more sense and makes bigger visual difference (another color). Name is another property worth showing (as on the examples).

Is this ready for deployment in your opinion? I see no missing pieces now.

**Comment by daniel-callejas-sevilla** [comment]
I'm a humble user of OSM who wants to see pipelines rendered. This issue is labeled "help wanted". How can I help?

**Comment by kocio-pl** [comment]
First thing - do you have our Docker environment container running? The basic instructions are here:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by daniel-callejas-sevilla** [comment]
Apologies for polluting here. The Docker environment fails to build at step `node-pre-gyp install --fallback-to-build`.

**Comment by jeisenbe** [comment]
Is your problem related to issue #3907?

What is your operating system and version of Docker and Docker-compose?

**Comment by jidanni** [comment]
Yes one would expect a [massive](https://www.openstreetmap.org/way/756801798)
```
bridge	aqueduct
diameter	2000
location	overhead
man_made	pipeline
substance	water
```
to be somewhere on the map. All that is currently left are the steps leading up to it, giving the impression that it was destroyed.

Such giant pipelines over rivers would be important escape routes in cases of disaster and need to be on the map soon.

**Comment by HolgerJeromin** [comment]
> Such giant pipelines over rivers would be important escape routes in cases of disaster

Many / all of those are not public accessible. This osm way lacks a footway tag probably for a reason.

You can not escape velociraptors on pipelines like this one:
https://s3.amazonaws.com/american-rivers-website/wp-content/uploads/2016/02/24211115/oil-pipeline-above-river-credit-Travis-flickrCC.jpg

> and need to be on the map soon.

This map is no live saving device!

**Comment by javbw** [comment]
Javbw

> On Dec 19, 2019, at 6:54 PM, Holger Jeromin <notifications@github.com> wrote:
> 
> Many / all of those are not public accessible. This osm way lacks a footway tag probably for a reason.


While I agree that: 

- these don’t have a footway that is accessible (fence blocks to the narrow service “path” on top and shouldn’t be tagged)

- OSM should be used as a guide in an emergency,

- such informal “evacuation sites” shouldn’t me mapped as such

But these pipeline bridges are landmarks that people recognize - locals would go to them in a tsunami/disaster as a last resort because the approaches are often much higher than the surrounding land. 

For the pure landmark value (whatever importance is derived from that), these pipeline “bridges” should be mapped in some manner. 

I would suggest the person use man_made=bridge on the area (to map the area the bridge occupies, which will be rendered) but the pipeline ways should have a black casing (if possible), similar to all other ways commonly tagged as a bridge.

Javbw.

**Comment by jidanni** [comment]
(As a quick check to see if this bug still exists, one can look at the [Trans Alaska Pipeline](
https://www.openstreetmap.org/relation/3624822#map=14/69.9015/-148.7533) and click "edit" and zoom. Even though on the imagery the road is as big as the pipeline, but alas the latter is not rendered, not even at highest zoom.)

**Comment by jidanni** [comment]
Better footing on [this massive water pipeline / aqueduct / bridge](https://goo.gl/maps/NA1oRCorNeVNNzZG8) tagged as [above](#issuecomment-567329483) but not rendered.

**Comment by daniel-callejas-sevilla** [comment]
> You are welcome. I have a number of PRs open, so I hope someone else can continue to work on this one, but I look forward to reviewing it.

Where can I find the PR with your changes? I'd like to try it in local.

**Comment by jeisenbe** [comment]
https://github.com/jeisenbe/openstreetmap-carto/tree/pipeline

**Comment by jeisenbe** [comment]
@daniel-callejas-sevilla were you interested in submitting an PR to add this feature? Do you need any help?

**Comment by Adamant36** [comment]
@jeisenbe, would the PR be at a mergable point close to where your test branch has it or would it still need any major modification?

**Comment by jeisenbe** [comment]
It's usable for testing. It would be good to check the rendering in
several different places and look for any potential problems with the
data or rendering.

**Comment by Adamant36** [comment]
A place in Poland with the pipelines running next to each other. It looks fine from z19-z17, but starts getting iffy after that. 

z19
![Poland 1 z19](https://user-images.githubusercontent.com/30259065/72212078-0065ee00-348b-11ea-8bf2-694660b6fa43.png)
z18
![Poland 1 z18](https://user-images.githubusercontent.com/30259065/72212080-08be2900-348b-11ea-987f-3b48740063df.png)
z17
![Poland 1 z17](https://user-images.githubusercontent.com/30259065/72212082-0e1b7380-348b-11ea-8db4-33df53a2f173.png)
z16
![Poland 1 z16](https://user-images.githubusercontent.com/30259065/72212085-196e9f00-348b-11ea-970c-720983eeba39.png)
z15
![Poland 1 z15](https://user-images.githubusercontent.com/30259065/72212087-21c6da00-348b-11ea-951e-500fb846379f.png)
z14
![Poland 1 z14](https://user-images.githubusercontent.com/30259065/72212088-27242480-348b-11ea-96e0-a59ef2d8c1e9.png)

**Comment by flacombe** [comment]
Easier for me to write than to do, it may be an option to make them disappear or even show like solid lines < z17

**Comment by Adamant36** [comment]
I think making not display at anything more zoomed out then z17 is probably the answer. If we make them solid lines it would be hard to tell them from other things. They don't look good sooner then z17 by themselves anyway. 

Single pipeline z16 (check out the last two parts on the left side. Doesn't look good due to the pipeline doing a little zigzag)

![Poland single pipeline z16](https://user-images.githubusercontent.com/30259065/72212522-c39df500-3492-11ea-9f0b-1b9eb7d46210.png)

Doesn't look to bad at z15 or z14 if they are straight. 
z15
![Stright pipelines containing water next to each other at z15](https://user-images.githubusercontent.com/30259065/72212509-7b7ed280-3492-11ea-93c6-462819a9c420.png)
z14
![Stright pipelines containing water next to each other at z14](https://user-images.githubusercontent.com/30259065/72212510-89345800-3492-11ea-8cfd-2ddab1ed6469.png)
Single pipeline over water at z18. I was looking for a water pipeline over water but couldn't find one. 
![Single pipeline z18 over water](https://user-images.githubusercontent.com/30259065/72212362-37d69980-348f-11ea-94b0-cf24babd36a9.png)

**Comment by jeisenbe** [comment]
We show even minor power lines, streams, private driveways and private
footways at z16 or sooner, so it would be strange to limit pipelines
to z17.

**Comment by jidanni** [comment]
Note these are often thousands of kilometers long structures.
It would be very frustrating needing to zoom in and out hunting for these like a blind man.

**Comment by jeisenbe** [comment]
> these are often thousands of kilometers long structures

Most of the very long pipelines are underground, though I understand
that Alaska and other areas with tundra are exceptions, and there are
some water aqueduct pipelines that are 10s of kilometers long which I
tested.

**Comment by Adamant36** [comment]
> We show even minor power lines, streams, private driveways and private
footways at z16 or sooner, so it would be strange to limit pipelines
to z17.

Yeah, I agree.

**Comment by jidanni** [comment]
I can thankfully see this underground canal
https://www.openstreetmap.org/way/219361140#map=12/24.1175/120.9406
all the way down to zoom 12.

If you think of it from the point of view of oil companies, they would rather not have the public know about their pipelines.

But from the point of view of environmentalists, it is important to know about pipelines.

I recall opening up great (paper) atlases of the world in the library, and seeing the whole Russian infrastructure, Trans-Siberian pipeline, railroad, highway, all on the same big map. That's what made them great.

**Comment by jidanni** [comment]
If people are concerned about the Amazon forests, the would like to see where pipelines have got to, not only roads, at the same zoom levels.

**Comment by jidanni** [comment]
Goo*** etc. commercial, and especially government maps, have all kinds of pressures to keep various multinational corporations' stuff off the map. This is where OSM can outshine them.

**Comment by jidanni** [comment]
Also if you think about it, this is where we can get the most bang for
the buck: well at least for high voltage lines, as they are straight,
one needs only to add their towers from imagery, and connect them with
straight lines. Sure the electric company and governments won't
cooperate by even telling you what the name of the power line is (due to
national security for high voltage infrastructure). But all one needs is
one trip to one tower to read the tower label sign to get the name of
the line. Voila. Line complete. I suppose pipelines are similar.

**Comment by Adamant36** [comment]
@jeisenbe, any suggestions since its your design and code?

**Comment by jeisenbe** [comment]
You could try adjusting the different colors for different
`substance=` values and test if you think they work intuitively or
not. You can also try adjusting the width at the different zoom levels
if you notice any problems.

I would recommend testing in several different real-world locations
where there are a variety of other features mapped nearby

For the initial zoom level, I tried z12 and z14, I believe, and it's
currently set to z14. You could try changing this, but right now it's
the same as `power=line` and major barriers like `barrier=hedge` and
`barrier=city_wall`, which makes sense - an overground pipeline is a
major barrier (can't walk or drive under it), and an overhead pipeline
is a significant landmark like a power line.

But if you have other ideas it would be reasonable to try a different z level.

Treat it like you are the maintainer reviewing the PR, and submit what
you would be willing to approve, if you were making the final
decision.

**Comment by javbw** [comment]
Just my two cents: it may not be perfect, but it looked decent enough to me at z19 to be implemented. 

Javbw

**Comment by jeisenbe** [comment]
@Adamant36 - were you considering opening a PR for this?

**Comment by Adamant36** [comment]
uuummm, yeah. But it doesn't look good at certain zoom levels and everyone thinks they should still be rendered at those levels. So, that needs to be worked out first.

**Comment by jeisenbe** [comment]
Remind me, what was the problem with the rendering tests at z16?

**Comment by Adamant36** [comment]
I don't know. I just thought it could have looked better. Although I don't have an exact, specific problem with it though. We really could just do the PR as is. Since it looks good otherwise and I don't think the problem on z16 (if there even is one) is worth holding it up.

**Comment by Adamant36** [comment]
@jeisenbe, you want me to do the PR for it?

**Comment by jeisenbe** [comment]
Yes. Opening a PR will help us get ideas from other contributors.

If you don’t think it is ready yet, then you can add “[WIP]” for now, and
ask for help with the parts that you think need improving.

**Comment by pnorman** [comment]
> If you don’t think it is ready yet, then you can add “[WIP]” for now, and
> ask for help with the parts that you think need improving.

It's better to do it as a draft PR if you don't think its ready.
