### ISSUE TITLE
Provide installation script

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#657]
Version for Ubuntu 14.04: https://github.com/gravitystorm/openstreetmap-carto/issues/657#issuecomment-121279334

Current setup instructions require unnecessary figuring out what and how it should be done.

But it is possible to assume that user have certain Linux (for example in VM) and provide installation script. It would be possible to provide entire installation instruction also in form:

install Lubuntu 14.04, it may be a virtual machine
$ sudo apt-get install git
$ git clone openstreetmap-carto
$ sudo sh ./openstreetmap-carto/lubuntu14.04_installation_script.sh

script would include
- set up of PostGIS database
- installing listed dependencies and fonts
- running get-shapefiles.sh
- fetching some small area suitable for testing and loading this data into database

Note that currently some people even make pull requests without testing them (see for example #654 ).

I may make and test the installation script (it would be mostly copy of http://switch2osm.org/loading-osm-data/ ).

**Comment by mkoniecz** [comment]
I tested and improved previous comment (mostly wording - and two instructions "Open Tilemill and close it" + final one).

**Comment by math1985** [comment]
As far as I'm concerned, we add this to https://github.com/math1985/openstreetmap-carto/blob/master/INSTALL.md .

**Comment by pnorman** [comment]
I have had nothing but problems with ppa:developmentseed/mapbox causing conflicts with other versions.

**Comment by mkoniecz** [comment]
> I have had nothing but problems with ppa:developmentseed/mapbox causing conflicts with other versions.

So what is the proper way of installing Tilemill? There are recommending this method on their website.

Or is there a suitable replacement for Tilemill?

**Comment by pnorman** [comment]
I'd prefer recommending Kosmtik over Tilemill.

* Kosmtik is better suited to large complex stylesheets. Tilemill tries to be a text editor, but can't deal with more than 3-4 .mss files
* Tilemill is essentially abandoned. Kosmtik is more of a community driven effort
* Kosmtik is smaller

The main differences with Kosmtik install and setup are

* You need to install it from source (@yohanboniface, any progress there?)
* You point it directly at the project.yaml file
* While running, it only deals with one project

For a new user creating new projects which will only involve 1 MSS file, I could see recommending Tilemill, as the built-in text editor makes it easier to start, but it just doesn't work on large projects.

**Comment by yohanboniface** [comment]
> You need to install it from source (@yohanboniface, any progress there?)

Nope, sadly. Creating a Debian package is not really an issue in se, but I need to sit down a bit to find the best way to deal with Mapnik.

**Comment by mkoniecz** [comment]
Kosmtik sounds nice (I am not fan of Tilemill but I was unaware that alternative exists), lets hope that standard installation from source is straightforward.

BTW, is there any performance difference compared to Tilemill?

**Comment by kocio-pl** [comment]
I try to install from source on Ubuntu Utopic, but I get this error (I got node package from regular repositories) - is it the same as @yohanboniface was talking?:

$ npm install
npm WARN package.json leaflet-formbuilder@0.0.6 No README data
-
> mapnik@1.4.17 install /home/kocio/devel/kosmtik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

**Comment by pnorman** [comment]
> BTW, is there any performance difference compared to Tilemill?

For map development, not really. You're still bottlenecked by Mapnik, which on machines with slow disks and low RAM means you're bottlenecked by the database. There's also the metatile size tradeoff between throughput and responsiveness. I can't speak to time to export tilesets or images.

It's probably marginally quicker in some ways, as it does less.

**Comment by pnorman** [comment]
> Nope, sadly. Creating a Debian package is not really an issue in se, but I need to sit down a bit to find the best way to deal with Mapnik

I was thinking of via `npm install kosmtik` but I see that works now

**Comment by math1985** [comment]
I also switched to kosmtik.

For me it's slightly faster with a stylesheet reload, which is the main bottleneck when I'm developing. On my computer it's about 23 seconds with tilemill, and about 17 seconds with kosmtik.

**Comment by math1985** [comment]
I do have a bit more problems with cut labels on meta tile boundaries. Is there anything that can explain the difference between tilemill and kosmtik in this respect? CC @yohanboniface

**Comment by yohanboniface** [comment]
> I do have a bit more problems with cut labels on meta tile boundaries. Is there anything that can 
> explain the difference between tilemill and kosmtik in this respect? 

That should not be the case. Things that can have an impact:

- metatile size
- map buffer
- Mapnik version

Fist two points should be exactly the same when loading project on Tilemill or Kosmtik. So maybe you have not the same Mapnik version? Can you check the one you are using on your Tilemill install?

**Comment by yohanboniface** [comment]
Tilemill seems to be using latest mapnik version since [October 2014](https://github.com/mapbox/tilemill/commit/818826c3f32162dd4a337f9fcb1c8ca60d29ba1b) so if you are using the master you certainly are on the latest mapnik.

I wonder if we should do the same think on Kosmtik. Note that I'm already using the master locally, but by default kosmtik still require the (old) stable mapnik.

Also note that I don't think OSM servers are already on Mapnik 3.

Anyway, if you want to try to update mapnik on your Kosmtik install, just run `npm install mapnik@3.1.2` from Kosmtik root, and see if you have the same rendering as when using Tilemill (which then may not be the same as on OSM servers).

**Comment by yohanboniface** [comment]
Suggestion: you can use [kosmtik-map-compare](https://github.com/kosmtik/kosmtik-map-compare) plugin to compare your local version with the one currently in production.

**Comment by math1985** [comment]
I use the last tagged version of Tilemill, which is 0.10.1. Does that mean that my Mapnik version in Tilemill [0.7.15](https://github.com/mapbox/tilemill/blob/v0.10.1/package.json) is?

**Comment by math1985** [comment]
Which mapnik version do we run in production?

**Comment by math1985** [comment]
And does the problem I experience might have to do with the different default of the clip setting across Mapnik versions?

**Comment by pnorman** [comment]
We run 2.2 in production. And there is some way to make Tilemill use a system mapnik

**Comment by math1985** [comment]
@pnorman So you don't have problems with metatile boundaries in Kosmtik? My Kosmtik either ignores or cuts all labels stretching metatile boundaries, while Tilemill renders the same labels fine.

**Comment by pnorman** [comment]
I have lots of metatile boundary label problems with 2.2 and Kosmtik. I just don't debug them.

**Comment by kocio-pl** [comment]
@math1985: 

in https://github.com/gravitystorm/openstreetmap-carto/issues/657#issuecomment-56023323 "install" is missing in:

sudo apt-get mapnik-utils ogr2ogr python-yaml

**Comment by math1985** [comment]
@kocio-pl Thanks, added.

Sorry for little comments on other issues, I'm very busy at the moment.

**Comment by kocio-pl** [comment]
No problem. =} 

I think the task of providing installation script (and updating it) is too big, because it takes us too long. So I have another idea - in my regular work I lately got to know Docker, which is quite interesting Linux virtualization software. It's not typical full-VM system, so it's much faster, but it isolates "containers" from the system and let them be connected in different ways, so one can have different software pieces and combine them (for example postgres-latest + tilemill-git + tile-server). Another nice Docker feature are "recipes" (Dockerfile) for building such containers, which are so readable, that are kind of self-documenting installation script. To my surprise, there are already some of OSM-related containers in the repository - here's a short recipe as an example:

https://registry.hub.docker.com/u/openfirmware/postgres-osm/dockerfile/

The downside is Docker requires 64-bit Linux as a host to run containers. I don't know what kind of people would be interested in osm-carto rendering, but worst case scenario is Windows and 32-bit Linux users can just use full-VM solution like VirtualBox to run 64-bit Linux with Docker containers inside. The performance overhead should be not much worse than full-VM alone (which is quite popular now, I guess), while we would have standard, easy to modify and combine rendering "bricks".

What do you think about this direction?

**Comment by pnorman** [comment]
> What do you think about this direction?

It might be interesting, this isn't the place for it - see https://github.com/gravitystorm/openstreetmap-carto/pull/1342#issuecomment-76924304

**Comment by kocio-pl** [comment]
@pnorman: OK, I see.

@matkoniecz: 
> fetching some small area suitable for testing and loading this data into database

What areas should it be? Most probably we would need different areas for testing different features, so:
1. We have to have the list of interesting "testing" places (I remember you're trying to make such collection, am I right?).
2. The script should download all of them - or we can ask the user which ones does he want?

**Comment by matkoniecz** [comment]
@kocio-pl I am using my home city, it is at the same time well known to me (so it is easier to notice Bad Things Happening), with various features (not everything but quite close) and well mapped. There are even some areas where rendered features are fully mapped.

But always recommending to load well known area is not perfect (mapping may just start or it may be without variety of different features). Advising to always load Kraków (or other location) also would not be a food advise for most people. Add discussing good testing locations would be too long and distracting.

My list of varied testing places is on https://github.com/matkoniecz/CartoCSSHelper/blob/master/CartoCSSHelper.rb (current state: https://github.com/matkoniecz/CartoCSSHelper/blob/c03ff739972102aa552ee14e8524c098d3677bbc/CartoCSSHelper.rb ).

**Comment by kocio-pl** [comment]
So what do you recommend? I'm lost a bit. =}

**Comment by matkoniecz** [comment]
@kocio-pl In your case Warsaw is probably a good idea - AFAIK it fulfills all requirements (well known to you, well mapped, variety of features).

**Comment by kocio-pl** [comment]
Sure, but I was asking about how to solve this problem in general installation script.

**Comment by kocio-pl** [comment]
What is the meaning of `--style` option in:

`osm2pgsql -d gis ~/osm/liechtenstein-latest.osm.pbf --style openstreetmap-carto.style`

I was not able to read about it [here](https://github.com/openstreetmap/osm2pgsql) nor [there](http://wiki.openstreetmap.org/wiki/Osm2pgsql#Usage).

**Comment by yohanboniface** [comment]
http://wiki.openstreetmap.org/wiki/Osm2pgsql#Import_style should help

**Comment by kocio-pl** [comment]
I know it control things, but I still don't know the meaning for the end user: is it for limiting the data (to get rid of not used in this style), making something faster or what?

**Comment by yohanboniface** [comment]
You may be confused by the name. Let's say it's called `mapping` instead of `style`, because it has nothing to do with rendering: it maps the data to an SQL schema. So it decides *how* the data will be stored in the DB, which is important then for the carto project because it expects some columns and tables with given names.

**Comment by matkoniecz** [comment]
> for limiting the data (to get rid of not used in this style)

This is part of its purpose (currently not everything is loaded into database). See also https://github.com/gravitystorm/openstreetmap-carto/milestones/3.x%20-%20Needs%20upgrade%20to%20openstreetmap-carto.style - things impossible to do as some tags are not stored in the database.

**Comment by kocio-pl** [comment]
OK, now I understand! 

I was surprised it works on my machine even without this option (probably because I didn't know where to find openstreetmap-carto.style and just forgot to report this problem). The reason is [it just happens that default osm2pgsql "style" is the same as what we use currently on osm-carto](https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.style). However in the future they may be different, so probably we should run it with full path to .style file - in this case:

`osm2pgsql -d gis ~/osm/liechtenstein-latest.osm.pbf --style ~/osm/openstreetmap-carto/openstreetmap-carto.style`

**Comment by matkoniecz** [comment]
Given previous steps current directory should be ```~/osm/openstreetmap-carto```, but this version should be less likely to fail later. I changed it in https://github.com/gravitystorm/openstreetmap-carto/issues/657#issuecomment-56711313

**Comment by kocio-pl** [comment]
Thanks!

Is it ready now to be published or we should test it more?

What about putting this version to some permanent place ([like INSTALL.md ](https://github.com/gravitystorm/openstreetmap-carto/issues/657#issuecomment-76622550))? If we want to test the procedure further, I suggest announcing it to Talk or maybe OSM-dev mailing list, because I doubt anybody outside is aware it exists.

**Comment by pnorman** [comment]
> So it decides how the data will be stored in the DB, which is important then for the carto project because it expects some columns and tables with given names

It also defines what is an area and what is a linear feature.

**Comment by kocio-pl** [comment]
Is anybody contributing here interested in [showing potential new developers how do we do it](https://lists.openstreetmap.org/pipermail/dev/2015-November/028858.html)?

**Comment by math1985** [comment]
This is also still an open item, and related to #2291.

Would providing a docker image help here? There already exists a docker image which is quite close to what we need: https://github.com/geo-data/openstreetmap-tiles-docker/
I think we'd only need to add support for openstreetmap-carto and kosmtik.

I never worked with docker before, so I'm not quite sure how to approach this. Does anybody know what the standard workflow is for developing code in a docker image? I suppose keeping the git checkout within the docker instance is not a good idea, because it will be lost when destroying the instance. So should the git checkout be outside the instance, and somehow be called by docker? But than you lose the advantage of providing everything in one bundle. Any suggestions?

**Comment by kocio-pl** [comment]
Docker is fairly user friendly technology in my opinion. You can mount host directory (which is used for PostgreSQL data for example):

https://docs.docker.com/engine/tutorials/dockervolumes/

We could do the same for Kosmtik code, but it can be also included in the image and updated during image rebuilding. Docker instance (container) would just inherit this code, but we could just make the script at the boot time, which will download fresh Kosmtik and install it, since this is a public code and "destroying" it is not a big thing (if we believe the repo will not disappear and we don't care for possible additional time and network usage during boot).

I would make one bundle with Kosmtik and make an updating script at the container boot. Other tools used there are pulled at the time of image creation and probably don't try to update later, which is safer of course, but it means images should be recreated to catch up with development of these tools.

The image you mentioned could be updated to run Ubuntu 16.04 and newer PostgreSQL, by the way.

**Comment by Ircama** [comment]
Just (too) quick check to this [installation script](https://github.com/geo-data/openstreetmap-tiles-docker/blob/master/Dockerfile); I wonder whether the following packages are really needed for Kosmtik and openstreetmap-carto:

* postgresql-9.3-postgis-2.1 vs. more recent versions
* Mapnik library
* mod_tile and renderd
* Apache vs. node-js
* osm2pgsql compilation with different method than the README (it should be updated); tmp is not deleted also.

**Comment by math1985** [comment]
@kocio-pl Yes, installing kosmtik during image building is probably best. But what about the openstreetmap-carto code?

**Comment by kocio-pl** [comment]
We could do the same. Image may contain latest release version and the script inside the container could update it to the latest git. This script could be also used for replacing the repo with the user's fork.

**Comment by math1985** [comment]
>  postgresql-9.3-postgis-2.1 vs. more recent versions

More recent versions are preferred.

>  Mapnik library

Isn't this the package we need for shapeindex (in the installatino instructions) by any chance?

>  mod_tile and renderd

This is not necessary for development, only for running a tile server.

> Apache vs. node-js

Not sure what you mean.

> osm2pgsql compilation with different method than the README (it should be updated); tmp is not deleted also.

Also not sure what you mean.

**Comment by Ircama** [comment]
> Isn't this the package we need for shapeindex (in the installatino instructions) by any chance?

Yes, Mapnik Utilities

    $ sudo apt-get install mapnik-utils

Apache should not be needed.

I guess osm2pgsql should be compiled this way:

```
# Needed dependencies
sudo apt-get install make cmake g++ libboost-dev libboost-system-dev \
  libboost-filesystem-dev libexpat1-dev zlib1g-dev \
  libbz2-dev libpq-dev libgeos-dev libgeos++-dev libproj-dev lua5.2 \
  liblua5.2-dev

# Download osm2pgsql
cd /tmp
git clone git://github.com/openstreetmap/osm2pgsql.git 

# Prepare for compiling
cd osm2pgsql
mkdir build && cd build
cmake ..

# Compile
make

# Install
sudo make install

# Clean-out temporary files
cd ../..
rm -rf osm2pgsql
```

**Comment by kocio-pl** [comment]
Do we really need to compile it? There's a 0.88.1 for Ubuntu 16.04 (and 0.90.1 for  yakkety):

http://packages.ubuntu.com/xenial/osm2pgsql

**Comment by pnorman** [comment]
Any install script/docker image/instructions should not involve compiling anything from source. There is no need.

**Comment by kocio-pl** [comment]
If geo-data image will not work for us (no open license, stale development), we could make our own image. I guess the hardest part would be proper installation of PostgreSQL, so I would find such image and base our set of tools on it (Docker allows this). However [its official images](https://hub.docker.com/_/postgres/) are based on Debian, which would make it harder to maintain, because Ubuntu seems to be current standard.

**Comment by pnorman** [comment]
> However its official images are based on Debian, which would make it harder to maintain, because Ubuntu seems to be current standard

It doesn't matter what OS the postgresql image is running since with docker you should have kosmtik and the db on different images.

**Comment by Ircama** [comment]
> Do we really need to compile it? There's a 0.88.1 for Ubuntu 16.04 (and 0.90.1 for yakkety):

Not needed. I was just referring to [this](https://github.com/geo-data/openstreetmap-tiles-docker/blob/master/Dockerfile#L33-L38).

**Comment by math1985** [comment]
> Any install script/docker image/instructions should not involve compiling anything from source. 

With the exception of kosmtik, right? Assuming you consider running nodejs as compiling.

> It doesn't matter what OS the postgresql image is running since with docker you should have kosmtik and the db on different images.

This is currently not the case on the geo-data image, right?

**Comment by kocio-pl** [comment]
> It doesn't matter what OS the postgresql image is running since with docker you should have kosmtik and the db on different images.

That would be along Docker philosophy (one service per container), but on the other hand typical Postgres image won't have PostGIS probably and we have to add it anyway, so I have thought it would be easier to maintain just one image.

However I've just found a popular PostGIS image on MIT license and with current software versions (also fresh 9.5+2.2 with current builds available), which could be just fine for us in case we would need to fork it:
https://github.com/appropriate/docker-postgis
https://hub.docker.com/r/mdillon/postgis/builds/

We also need a Kosmtik image - but there is also a few and this one is on Apache license and has fresh builds from git (latest build has some problems):
https://github.com/Joxit/docker-kosmtik
https://hub.docker.com/r/joxit/kosmtik/builds/

So we could just make a simple script running latest postgis and kosmtik containers. We just need to decide how to deal with data and style, which are to be swapped probably: 
- do we want to download and import - let's say - Lichtenstein by default or leave it entirely to the user? 
- what about osm2pgsql - do we need to create our own small container with it? or maybe we could have it added by other images we use?
- do we want to download standard osm-carto by default (latest release or just latest git) or leave it to the user to define her own fork somehow?

These are questions about where we draw the line between what we want to have by default and where we think it's better to not do it.

**Comment by pnorman** [comment]
> That would be along Docker philosophy (one service per container), but on the other hand typical Postgres image won't have PostGIS probably and we have to add it anyway, so I have thought it would be easier to maintain just one image.

There's a fairly standard postgis image out there. We don't need to do anything to it

**Comment by pnorman** [comment]
> do we want to download standard osm-carto by default (latest release or just latest git) or leave it to the user to define her own fork somehow?

Neither, we want to use the osm-carto in the current working directory

**Comment by kocio-pl** [comment]
I see. So the script for dockerized Kosmtik needs to be run with something like `kosmtik serve ./openstreetmap-carto/project.yml`.

And what about the data? I've found docker-osm2pgsql images, but it's rather old and has a common problem with lack of the license:

https://github.com/openfirmware/docker-osm2pgsql
https://hub.docker.com/r/openfirmware/osm2pgsql/

So maybe we could just install osm2pgsql from package, without container?

**Comment by math1985** [comment]
Now I think of it, it would also be really cool if we could provide an image (or series of images? not sure how this works) that would provide a complete tile server. I think that would really stimulate people to run their own tile servers. 

CC @systemed

**Comment by kocio-pl** [comment]
That's exactly why geo-data/openstreetmap-tiles-docker would be so interesting - if they have a license and continue to maintain this project - because this is exactly what they do and they even have [nice tools for managing data](https://github.com/geo-data/openstreetmap-tiles-docker/blob/master/help.txt). 

But if they won't, we can use existing images and use them as a service boxes, or build upon them to add what we need - or mix these two methods. It's not a rocket science to create it, but it's better to think twice, because it's a different code than style itself and will need some care for quite a long time probably.

**Comment by pnorman** [comment]
link for kosmtik: https://github.com/Joxit/docker-kosmtik

We should be able to put together this, a postgis docker, and a small one with the style using docker-compose

**Comment by math1985** [comment]
> a small one with the style 

I'm still not sure if I fully understand the docker philosophy. Would we need to be able to run get-shapefiles in this repository? In that case, we probably should make it a repository extending ubuntu or something like that, right?

**Comment by math1985** [comment]
I created https://github.com/math1985/openstreetmap-carto-docker as a starting point for the discussion. Is this the right way to think about it, or am I doing something wrong? @pnorman  @kocio-pl

**Comment by pnorman** [comment]
> Is this the right way to think about it, or am I doing something wrong? @pnorman @kocio-pl

Have a look at https://github.com/openstreetmap/openstreetmap-website/pull/1290

**Comment by kocio-pl** [comment]
Default Ubuntu image is currently 14.04, so I would use rather `FROM ubuntu:16.04`. But we can also use minimal image, which is supposed to [solve some Docker-specific issues](https://github.com/phusion/baseimage-docker#why-use-baseimage-docker), so probably `FROM phusion/baseimage`.

**Comment by kocio-pl** [comment]
There are also known [best practices for using apt-get](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run) in Docker, related to its extensive caching. Basically - always use `apt-get update` in the same line as `apt-get install`.

If we want to always have fresh git content from osm-carto (every time the container is started, not only when building new image), we should update it [through ENTRYPOINT](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/entrypoint).

And when we have all the needed containers, we have to start them in a coordinated way - it can be made with a simple script, but there also exists Vagrant, which is popular VM "orchestrating" software. See [this example](https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md).

**Comment by math1985** [comment]
@kocio DId you get the geo-data image to work? I repeatedly get '2016-10-14 20:42:37 UTC FATAL:  could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied'.

**Comment by kocio-pl** [comment]
No, I didn't try it because of lack of the license - I don't like to waste the time with such uncertain project. I can test it however in a few days, if it would be useful to you in any way.

**Comment by kocio-pl** [comment]
I have some problems building, but you could also try with a fork which has quite fresh build available:

`$ docker run xingfuryda/openstreetmap-tiles-docker`

**Comment by pnorman** [comment]
Here's the dockerfile I have

```Dockerfile
FROM debian:testing

# Install style dependencies and Kosmtik dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
    nodejs nodejs-legacy npm \
    zip unzip curl git ca-certificates \
    fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted ttf-unifont \
    && rm -rf /var/lib/apt/lists/*

RUN npm install kosmtik

RUN mkdir -p /openstreetmap-carto
WORKDIR /openstreetmap-carto

# Get the shapefiles
ADD get-shapefiles.sh ./
RUN ./get-shapefiles.sh
```

Next steps would be to make a docker-compose file which
* Maps `.` to `/openstreetmap-carto`
* Exposes port 6789
* Has a container for PostGIS
* Runs Kosmtik on start

The data loading also requires another dockerfile for osm2pgsql which will load the data into the PostGIS container.


I'm doing an OS upgrade so might not get back to this for a few days.

**Comment by kocio-pl** [comment]
I was not aware of [Docker Compose](https://docs.docker.com/compose/overview/), but it looks like a better way than Bash scripts or Vagrant rules - thanks!

**Comment by pnorman** [comment]
OS upgrade finished, and I have something that partially works

https://github.com/gravitystorm/openstreetmap-carto/compare/master...pnorman:docker starts two containers, one for the DB, the other for Kosmtik, and docker-compose up brings them up together. I'm still working on the import side.

**Comment by kocio-pl** [comment]
Why don't you use Joxit/docker-kosmtik, which you mentioned yourself, or kosmtik/kosmtik for example?

**Comment by pnorman** [comment]
> Why don't you use Joxit/docker-kosmtik, which you mentioned yourself, or kosmtik/kosmtik for example?

I'd have needed to do just as much work modifying it, or end up with another container which does the work of downloading the shapefiles.

**Comment by math1985** [comment]
So currently the import process fails (amongst others) because it has no `createdb` executable. Should we add postgresql-client-9.3 to the import Dockerfile? Still trying to understand how this works.

**Comment by pnorman** [comment]
> So currently the import process fails (amongst others) because it has no createdb executable. Should we add postgresql-client-9.3 to the import Dockerfile? Still trying to understand how this works.

Yes. Well, not that version, `postgresql-client` is what should be used, but I've done this change locally and haven't pushed the changes.

**Comment by math1985** [comment]
Thanks. Do you have any other local changes? Half implementations are fine.

**Comment by math1985** [comment]
The issue I'm not having is:

`import_1   | createdb: could not connect to database template1: FATAL:  the database system is starting up`

In other words, at the moment createdb is executed, the psql server is not yet fully running. Is there a way to handle this?

**Comment by pnorman** [comment]
> In other words, at the moment createdb is executed, the psql server is not yet fully running. Is there a way to handle this?

Not sure.

**Comment by math1985** [comment]
I added a `sleep 10` now. There must be a better way though...

**Comment by pnorman** [comment]
https://docs.docker.com/compose/startup-order/

**Comment by math1985** [comment]
Good point.

**Comment by math1985** [comment]
Next problem: the import Docker file contains `WORKDIR /openstreetmap-carto` and `RUN npm install kosmtik`, but when doing a CMD,  /openstreetmap-carto/node_modules does not exist. What am I missing?

**Comment by kocio-pl** [comment]
I would try to look at this, since I consider having easy toolset for developers to be quite important thing - getting to know some details takes me years, so it's good to have some developers to take care for some easier tasks, so we have more people ready to work with the code in the longer perspective.

**Comment by math1985** [comment]
See also https://www.reddit.com/r/openstreetmap/comments/5i6tif/how_to_attract_new_mappers_for_osm/db6kupn/

**Comment by Ircama** [comment]
Sometimes [this](https://ircama.github.io/osm-carto-tutorials/) could be of help...

**Comment by math1985** [comment]
Would https://shinesolutions.com/2016/12/30/generating-high-res-maps-with-mapnik-and-docker/ help us with the docker work?

**Comment by pnorman** [comment]
they're using a flag file to indicate if the DB is initialized and hard-coding the location of the data that gets imported. It doesn't help with what we still need to work out.

**Comment by nebulon42** [comment]
I have updated the branch (https://github.com/gravitystorm/openstreetmap-carto/compare/master...nebulon42:docker) and added some documentation. It basically works. The only thing I have not looked at is if we can prevent `get-shapefiles.py` from indexing every time and if there need to be other improvements with this script.

Another thing is that the shapefile data currently is owned by the user with UID 1000. First it was root which was even worse. We have to think of something for systems where 1000 is not the default user.

We also have to think about if we should build the containers and upload them to the registry to avoid that everybody has to re-build them.
