### ISSUE TITLE
Add rendering for golf=*

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#661]
Please consider importing the "golf" key and render its values, they are documented here:
http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course
Particularly golf=
bunker (rendered as sand)
hole (the hole area)
pin (zoom 18/19?)
green
fairway
rough (rendered like natural=scrub)

**Comment by geozeisig** [comment]
A long time has passed and nothing has happened. So everybody uses tags that are rendered. That may be landuse=grass, leisure=pitch, highway=path (with golf=hole) etc. That is **"Tagging for the renderer"** and it is provoked when golf=* has not been rendered.
It is right that there may be up to 4 tee boxes on a given hole. In most cases, however, only one (the furthest) is drawn. In any case, this should not prevent us from finding a solution.
How it made on osm.fr is quite a discussion basis.

**Comment by nebulon42** [comment]
"Nothing has happened" is not quite correct. This depends on the rendering database schema change, which is covered in #2533. So there is already a PR for the prerequisite to this issue and it is close to being merged.

**Comment by eFrysTon** [comment]
Given that all the prerequisites should be in place now, any chance something can be done about this in the near future?

I just tried mapping part of a golf course, and while this is how it looks in josm:

![image](https://user-images.githubusercontent.com/27037648/37750264-d07ed348-2dd7-11e8-8eab-2bd7d84d913b.png)

and this is how it's being rendered:

![image](https://user-images.githubusercontent.com/27037648/37750315-0bd27436-2dd8-11e8-9ec1-20d935037b96.png)

which is... somewhat disappointing.

As a minimum, I would be happy if areas (closed way or multipoly) with the following tags could just be rendered in different colors:

golf=bunker (as sand)
golf=rough (green, lighter than natural=scrub, darker than landuse=grass)
golf=fairway (green, either same or slighly lighter than landuse=grass)
golf=green (green, lighter than landuse=grass)
golf=tee (green, same as golf=green or between golf=fairway and golf=green)

Also, I would VERY much like leisure=golf_course to use a different color than natural=scrub.

Anything more complex than just coloring these areas can wait for later. But just these would greatly improve the visual feedback mappers get from mapping golf courses and would hopefully reduce the instances were golf features are tagged with nonsensical tags purely to make them show up in some way in the map.

**Comment by kocio-pl** [comment]
Would you like to prepare the code for this?

**Comment by geozeisig** [comment]
`golf=pin` (node) should be a small flag like this
![golf_pin-14](https://user-images.githubusercontent.com/17127509/37890809-3fdd12b6-30d2-11e8-978e-7c809f60e25b.png)
The circle is almost in the middle because here the line for the hole ends.
![golf_pin](https://user-images.githubusercontent.com/17127509/37890881-6a665d94-30d2-11e8-9c0e-a8db029ef9fe.png)

`golf=hole` The way into the hole as a gray line.
`golf=tee` (node) As a small gray circle

**Comment by Tomasz-W** [comment]
I think it's too specialized for general map and we should reject this tha same as https://github.com/gravitystorm/openstreetmap-carto/pull/3161

**Comment by kocio-pl** [comment]
I guess you're right, it's even more specialized.

**Comment by Adamant36** [comment]
Darn, I was totally in the process of testing it out too. Although I agree its rather specialized, I think we should render golf related stuff anyway because its being miss tagged quite a lot. Plus, its being rendered properly on the French and German maps also. So why not? 
As an example, I was only able to find a few golf courses in Northern California that didn't have greens tagged as landuse=grass and there are a lot of golf courses here. The wiki says there's currently 40,164 uses of just fairways and 82.32% are tagged as landuse=grass. There's 63,248 uses of golf=tee, 49,853 uses of golf=green of which 70.13% are tagged with a landuse tagged, and 110,003 uses of golf=bunker. I would hardly call those numbers specialized. Things with 1/10th those numbers are rendered. If for nothing else it would be helpful if they could be rendered properly just to encourage good tagging practices, instead of just leaving it for people to map for the render when its clearly such a big problem.

**Comment by Tomasz-W** [comment]
@Adamant36 In the topic of golf courses, you can taka a look at https://github.com/gravitystorm/openstreetmap-carto/issues/2069 and try with an outline, because area filling seem to not working good there.

**Comment by imagico** [comment]
Note rendering `golf=*` features is currently complicated due to the database scheme not treating them as polygons by default.

**Comment by jeisenbe** [comment]
I think it would be worth rendering some of the golf tags. It would be straightforward to render fairways, tees and greens the same as grass and bunkers as sand. While it is somewhat specialized, the tags are used frequently are they are better than using landuse=grass and natural=sand to get the same rendering.

@kocio-pl, would you consider reopening this?
@Adamant36, do you want to try this?

**Comment by kocio-pl** [comment]
Sure, I will reopen if there will be a pending discussion, to reflect that there's some progress.

**Comment by Adamant36** [comment]
Sure. I had them rendering a while back. It was a little complicated and took an extra .mss file for some reason. But im sure I can figure it out again.

**Comment by jeisenbe** [comment]
Reopened; requires database reload but we should decide first if these features should be added to the lua schema, so this requires some discussion about if it's worth considering. 

While I'm not a fan of golf myself, since these are such prominent features and double-tagging for rendering is some common, I think rendering might be worthwhile to improve the tagging . Most of the features could be rendered similarly to a common type of landcover, so it would not add to the burden of finding new colors, nor would new svg icons be required. The French style provides some ideas for implementation.

**Comment by jeisenbe** [comment]
#4017 is now open to import the features properly as polygons when mapped as closed ways.

**Comment by jeisenbe** [comment]
These features are now imported with the correct schema, so it is possible to open a PR to solve this issue. 

I would suggest looking at how golf features are rendered in the French style (https://github.com/cquest/osmfr-cartocss/blob/master/sports.mss) and the alt-colors style (https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/golf.mss).

**Comment by Adamant36** [comment]
@jeisenbe, would it be coded like a normal feature now or does it still take the work around other styles use? I had it rendering fine before it was imported and I fail to see what the difference would be now. Less code and increased speed or something else?

**Comment by jeisenbe** [comment]
All closed ways with `golf=` tags which represent an area, like water hazards, faireways, greens, sandtraps etc, are now imported as polygons, so nothing fancy is required to render these with a fill color now.

The tags are in the hstore "tags" column, I believe, so you would need to select the features like this:

```
'golf_' || CASE WHEN tags->'golf' in ('bunker', 'fairway', 'green', <etc>) THEN tags->'golf' END,
```

**Comment by leijurv** [comment]
https://www.reddit.com/r/openstreetmap/comments/gkq32t/why_does_golf_course_fairway_render_on_top_of/fqt0xw1/

**Comment by dktue** [comment]
I support the suggestion to render `golf`-tags. Yes, it's specialized but on a vast area like a golf course, where nothing else is of interest, I think it should be rendered.

**Comment by jgruca** [comment]
I've opened #4212 based on what I understand the current state of this issue is. All comments welcome.

**Comment by Silleroco** [comment]
Hello good,

We are looking for a database already made that contains the maps of the fields and fairways of a golf course or people who help us to do it. It's for a pilot project, can someone help or guide me?

Thank you very much in advance.
