### ISSUE TITLE
Drop rendering permissive access

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#682]
We currently render a lot of different features and line styles on the map. I wonder if we can reduce the number of different styles by one, by no longer rendering permissive access.

Permissive access is defined as follows: "Open to general traffic until such time as the owner revokes the permission which they are legally allowed to do at any time in the future."

I think that it is not interesting to know for the average map user whether a road owner has the right to revoke access in the future or not. A map user mainly needs to know whether he has the right to use a road or not, and access=permissive and access=yes are equivalent in that respect. In practice, permissive access is not usually suddenly retracted, so it also doesn't really have a strong predictive character that a road might be closed.

We currently render permissive access as green dashes on top of the road (as opposed to blue dashes for destination access, and red dashes for no access).

I also have the impression that the 'permissive' dashes are one of the hardest features to understand for new users.

**Comment by kvlahromei** [comment]
As we had now the impression of how OSM looks without rendering this tag, I would like to ask, if we might reconsider to introduce it?

Yes, I understand and support the idea to reduce the visual clutter for road features, but on the other hand I see the problem, that:

1. Users don't recognize the limitation
2. Mappers don't recognize the (already mapped) limitation

Esp. no 1. seems to be bad, as the current styling (IMHO) seduce users to enter restricted areas, even if he would't if he had the information that it's just permissive access.  
Don't get me wrong, nobody will enter an danger area, but it seems that healthcare facilities, zoos and other areas look as easy to pass. This might confuse people that don't use routers (which avoid such highways).

So what do you think?

**Comment by math1985** [comment]
What does access=permissive mean according to you? In which situations do you use it?

**Comment by kvlahromei** [comment]
As I mentioned it's in between a public and private access, so for highways that can't be used (safely, all the time, without fee, ...) all the time. I saw it for some gardens/parks, for areas as campus/hospital/ sites or 

Because to my suprise for example access=destination is rendered anyway, even it's (IMHO) less important for a map (bringing people from A to B) and not often in use.

**Comment by HolgerJeromin** [comment]
destination is more important, as i am not allowed to short cut a way through this highway. 
If i have a permission via the owner (aka access=permissive) or by the city/state/country (access empty) it does not restrict my movement.

**Comment by SK53** [comment]
Generally for me access=permissive should imply that generally it is accessible, *but* with the explicit permission of the landowner rather than through a legal right. For a general purpose map such ways should not need to be distinguished from fully accessible ways. Widespread examples are University & Hospital campuses, many paths in public parks, many privately owned shopping centres/malls. 

access=permissive under this sense should not really be used in situations where there is a fee paid (zoos, theme parks etc.). Generally I only use this tag when there is a sign saying access is by permission (often needed in England & Wales to stop a path becoming a legal right of way), but I dont tag paths in campuses with this.

**Comment by math1985** [comment]
> As I mentioned it's in between a public and private access, so for highways that can't be used (safely, all the time, without fee, ...) all the time. I saw it for some gardens/parks, for areas as campus/hospital/ sites or school sites. IMHO it says "you can pass if needed, but try to avoid it".

No, that's not the correct use of access=permissive (and the misuse of access=permissive for situations like this is exactly the reason why we dropped it from the rendering). SK53 correctly explains the use of this tag. It is rather specific for the British situation, I don't think using this tag makes much sense in Germany.

**Comment by kvlahromei** [comment]
Ok, thanks for explanation :-)

**Comment by dieterdreist** [comment]
2015-01-07 15:50 GMT+01:00 math1985 <notifications@github.com>:

> I don't think using this tag makes much sense in Germany.



there are lots if situations where it does make sense in Germany, in cases
where a way is private and there is no public right to use it, but the
owner consents (explicitly or silently/by habit) that people use the way,
sometimes there are also signs like "access on your own risk", by which the
owner is trying to reject liability for accidents).
