### ISSUE TITLE
Render brand if name isn't present on amenity=fuel, shop=supermarket etc

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#698]
I admit that in this case I am unsure what would this rule or adding name name keys would be preferable, but I am unsure that at least one of these two should be done.

brand tag is in database, so it could be done before 3.0

example: http://www.openstreetmap.org/node/1111319733

migrated from trac https://trac.openstreetmap.org/ticket/3471

**Comment by Skippern** [comment]
Yes, it makes sense for ``amenity=bank``, I see a lot of examples where they add ``operator`` and ``name`` because ``brand`` is not rendered on the map. IMO it is more appropriate to tag these locations with ``brand``, and adding the exact same information in ``operator`` and name is duplication of information. For a bank the operator is generally the brand, unless it is a multi-national brand (HSBC, where the brand remains HSBC in every country while the operator is ``operator=HSBC do Brasil``)

**Comment by kocio-pl** [comment]
>I am surprised how clean the brand key is. operator is much more chaotic ("DB Netz" next to "DB Netz AG").

Exactly the same here in Poland: ""Euronet" vs "Euronet Sp. z o.o.". Brand is the most visible and important thing for the user/customer (this is the main function of brands) and sometimes brands are being sold to another operator as they are - probably to use well known and trusted label.

**Comment by 1ec5** [comment]
Often in the U.S., a gas station or fast food restaurant may have the city name or location number included in `name`, the franchisee (only ever visible on a plaque inside the building) in `operator`, and a much more common-sense name in `brand`.

The downside to this fallback is that labels become a bit less predictable.

**Comment by Skippern** [comment]
That is some of my opinion, but I feel the purpose of this map is rather to promote correct tagging than ideal way to display things. I am working with a Brazilian specific rendering style, where we propose to promote brand of certain gas stations, banks, fast food chains etc. i.e. letting HSBC banks be displayed on the map with a HSBC logo instead of a generic bank symbol. That kind of things are for special interest maps, but in your case it would be rather more friendly if the displayed ``brand=Burger King`` instead of ``name=Burger King I-123 Oklahoma City`` or ``operator=Burger King fc 123456``. I have similar cases with supermarkets, where a local supermarket is ``brand=Santo Antônio``, while it also could be tagged ``operator=Zchen Hue Supermercados Ltda`` which wouldn't give users of the map any intelligent clues (Zchen Hue is not a common Brazilian name) though it could also be ``name=Santo Antônio do Rua Guitilio Vargas`` where the main entrance, though it have entrance from another road, calling it ``name=Santo Antônio do Centro`` will be plain wrong, as there are 2 others in the same suburb. In such cases I tend to fall back on only mapping the ``brand`` tag.

**Comment by rmikke** [comment]
I'm totally for displaying brand=* if name=* is absent.
Also, if name=* is absent and both brand=* and operator=* are present, brand=* should have precedence over operator=*

**Comment by pnorman** [comment]
I've gone back and forth on this, but after much thought, I'm against it. The biggest reason is that it adds a complication to what a mapper *may reasonably expect to be simply handled*, resulting in non-obvious behavior.

**Comment by math1985** [comment]
+1.

**Comment by matkoniecz** [comment]
On the other hand - current state encourages misuse of name tag.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 27.07.2015 um 10:26 schrieb Paul Norman <notifications@github.com>:
> 
> I've gone back and forth on this, but after much thought, I'm against it. The biggest reason is that it adds a complication to what a mapper may reasonably expect to be simply handled, resulting in non-obvious behavior.


IMHO this is encouraging the use of the name tag as a label (eg the brand of the petrol company providing the fuel) and push more precise formalizations like the operator and brand tags into a specialist corner.

**Comment by kocio-pl** [comment]
Given that brand is a popular feature in many shops/amenities, it makes sense to "learn" people that name is not everything. Important part of it should be adding such field in respective presets in iD and JOSM, so the mappers feel that brand/network name is also first class citizen.

**Comment by Skippern** [comment]
> 
> Given that brand is a popular feature in many shops/amenities, it makes sense to "learn" people that name is not everything. Important part of it should be adding such field in respective presets in iD and JOSM, so the mappers feel that brand/network name is also first class citizen.
> 
+1

**Comment by rmikke** [comment]
@pnorman What do you mean by non-obvious behavior?
Presenting brand if no specific name is given seems to be the most obvious behavior. It's nothing by natural to say e.g."turn left by the Shell station"...

**Comment by Skippern** [comment]
I thought some of the purpose of the default slippy map was to promote correct tagging, and if users is not getting the expected behaviour of ``brand`` they will ignore this tag and put that information in ``operator`` and/or ``name``. Generally ``name=Shell`` is wrong for a gas station, just as ``name=McDonalds`` is wrong for a fast-food shop. Users will continue to tag this way as long as they don't get the desired behaviour.
I have seen several examples where users obviously didn't get the desired behaviour from ``brand=<some brand>`` so they added ``operator=<some brand>`` and ``name=<some brand>``, probably to get the brand name rendered next to the icon.

**Comment by neiljp** [comment]
This is probably something more relevant for a tagging discussion, but I have hardly ever come across 'brand', and 'operator' is rather uncommon too (and I haven't seen a good reason for it to be rendered, certainly not in preference to a name). I can see why name=McDonalds and name=Shell could be wrong in a data sense, ie. they are the 'brand', but I've always considered (and heard said by other mappers) that 'name' is what I see, and that would be McDonalds or Shell. That said, I have seen eg. car rental companies or hotels with a chain name, branch name, and obviously operator could be separate again, so I see the utility of having the data. IMO converting however many chain POIs with name=[chain-name] to brand and putting a 'full' version in name is a lost cause; brand could be used to emphasise that it is the same as the name (ie. a chain), but I would be much more in favour of an additional tag to supplement the 'short' name, such as name:branch or branch_name - which could then be concatenated in different ways (or not) at different zoom levels, such as "[name] ([branch_name])", but as only "[name]" at lower zoom levels.

**Comment by rmikke** [comment]
Why put some "full name"on McDonald's? If we have brand rendering, then mapper fills the brand and can see on the map. No name is necessary.

**Comment by Skippern** [comment]
I see no reason to give preference to ``brand`` over ``name``, but seeing so many cases where mappers add what should clearly be ``brand`` as ``name`` because it is not rendered, IMO time to render ``brand``, either as 1st fall back before ``operator``, or as a further fall back from ``operator``. The order ``brand``/``operator`` is debatable, and should in my opinion vary between types of objects.

**Comment by kocio-pl** [comment]
Fuel station preset in JOSM has brand on the top and all the rest (including name) are presented as additional properties, so this is nothing new or strange to rank the brand above everything else. ATM preset even doesn't include name field. Changing fast food and other presets is next logical step.

**Comment by pnorman** [comment]
> This is probably something more relevant for a tagging discussion

Yes. I'd like to remind everyone that this is the **OpenStreetMap Carto** issue tracker and not a general tag discussion forum. If you want to discuss tagging, editor presets, and other non-stylesheet matters, this is not the appropriate place.

**Comment by kocio-pl** [comment]
This subject is project-wide and I can happily start the discussion somewhere else and report conclusions here, but I don't know where and what to ask? Should we ask on Tagging if this is the legitimate tag? It has proper, clearly defined Wiki page and is widely used (141 110), so no doubt about it.

I guess it's still mostly about our decision and all the discussion just shows some aspects of this tag outside rendering dept. as a support for claims that brand tagging should be used. As far as I understand [notes about distinguishing brand/name/operator Wiki](http://wiki.openstreetmap.org/wiki/Key%3Abrand#Distinguishing_between_Brand.2C_Name.2C_Operator.2C_etc.) it is said that:
- if the name is less known, the brand is more important - so it should have precedence in rendering (`"It is of most value where the name of the outlet is less well-known than the brand of goods or services that are sold."`)
- if the name is the same as brand, only name should be used - so still the precedence rule works, because in case of missing brand the name will be used, and even if the user gives both tags, there's no problem with rendering, because they are the same by definition (`"Where a well-known brand is trading under their own name, then name=* is expected by most data users, and should be used by contributors."`)

**Comment by Skippern** [comment]
@pnorman Yes I know this is **OpenStreetMap Carto**, and that is exactly why I ask here to have ``brand`` rendered. I agree that this is not the place to discuss tagging, but given the current usage, the discussion should not be wether or not ``brand`` is a legit tag, but rather if ``brand`` should have priority before or after ``operator``. I find it quite strange that the OpenStreetMap Carto team does not want to render ``brand`` to help promote an approved and widely used key, while they have done what is in my opinion the mistake of rendering ``shop=yes``.
I can very well open this discussion on the tagging list, but feel that given from other documentation and usage data the answer will be clear.

**Comment by pnorman** [comment]
> if the name is the same as brand, only name should be used

Just to note, this is one case when it doesn't matter what is rendered - if they're the same, you can't tell the difference

**Comment by kocio-pl** [comment]
Sure, it was just re-wording of the Wiki statement - and that was written what should *mapper* do (not renderer), I just wanted to make it crystal clear what was the intention. 

Back to the subject: what do you think now about brand>name rendering priority?

**Comment by pnorman** [comment]
> Back to the subject: what do you think now about brand>name rendering priority?

I think this was answered with https://github.com/gravitystorm/openstreetmap-carto/issues/698#issuecomment-125123616 https://github.com/gravitystorm/openstreetmap-carto/issues/698#issuecomment-125125825 when the issue was closed. I can't speak for @math1985, but I didn't expect everyone to agree, and I don't feel that anything new has been presented since then.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 01.08.2015 um 01:01 schrieb Paul Norman <notifications@github.com>:
> 
> think this was answered with #698 (comment) #698 (comment) when the issue was closed. I can't speak for @math1985, but I didn't expect everyone to agree, and I don't feel that anything new has been presented since then.


yes, rarely everyone agrees, but in this particular case nobody seemed to agree with your comment or the decision to close the issue.

**Comment by matkoniecz** [comment]
> in this particular case nobody seemed to agree with your comment or the decision to close the issue

That is also untrue, see https://github.com/gravitystorm/openstreetmap-carto/issues/698#issuecomment-125125825

**Comment by fred702** [comment]
I'm not sure why this issue was closed.

@pnorman
Would you please explain your reasons why you oppose it? I don't quite understand this statement:

>The biggest reason is that it adds a complication to what a mapper may reasonably expect to be simply handled, resulting in non-obvious behavior.

It seems to me that you're suggesting conflating name=* and brand=* tagging which at times may be the same, but in many situations is not.

I agree with @matkoniecz that the "current state encourages misuse of name tag".

What a mapper may "reasonably expect" is that rendering match adopted standards in practice and in the wiki.

**Comment by matkoniecz** [comment]
Note that #972 is still open.

**Comment by kocio-pl** [comment]
@pnorman I think we should not oversimplify things if they're not that simple in reality. Current state encourages tagging for renderer, which would be very unfortunate consequence and I'd like to avoid it.

I have a helper question then: do you think we should never-ever drop name label priority over brand or could you consider some conditions which would justify such a change? Could it be making brand much more prominent than name as with fuel station preset in JOSM (or something like this)?

**Comment by dieterdreist** [comment]
sent from a phone

> Am 03.08.2015 um 02:10 schrieb kocio-pl <notifications@github.com>:
> 
> I have a helper question then: do you think we should never-ever drop name label priority over brand or could you consider some conditions which would justify such a change? Could it be making brand much more prominent than name as with fuel station preset in JOSM (or something like this)?
> 


for gas stations I would always prefer brand over name for labeling a map, the name is something I d only want to see in search results or similar...

**Comment by kocio-pl** [comment]
@pnorman I think we still have a problem and I suggested a helper question to look further. Could you respond what do you think about "conditional" rendering brand? I guess editors showing brand field on top of the name (or even with no name field) is a strong case against calling it "non-obvious behavior" - it is obvious to tag the brand then. Or maybe there are some other conditions for you to feel satisfied? Or just you feel using brand field is a broken tagging at all? 

The details are important - knowing what is acceptable at least and what is out of any question in such a hard problem is crucial.

**Comment by naoliv** [comment]
I am seeing a lot of people here in Brazil including the `brand` in `name` (for banks and fuel stations) because the brand isn't rendered.
Could we have both `brand` and `name` rendered for `amenity=fuel` and `amenity=bank`, please?

One quick example: http://overpass-turbo.eu/s/bwO (click on Run)

**Comment by kocio-pl** [comment]
@pnorman Could you reply to my [helper questions](https://github.com/gravitystorm/openstreetmap-carto/issues/698#issuecomment-131064660)? 

I guess the problem won't go away anytime soon (see also [new comments](https://github.com/gravitystorm/openstreetmap-carto/issues/1548#issuecomment-131367861) to the still open #1548), so I'd still like to find a compromise solution.

**Comment by kocio-pl** [comment]
...and we have brand new issue too. I really think it was too soon to close this issue, before we have tried to find the consensus (at least stating the limits of possible agreement).

**Comment by nighto** [comment]
In my opinion `brand` should always be rendered in addition to `name`. Could be either `name (brand)` or `name<br>brand`. I prefer the latter.

**Comment by bonix-git** [comment]
Hello,

I would suggest that the brand was informed first and then the company name .

I understand that the user can more easily identify the gas station , bank or supermarket with the presentation in this order: band <b> name .

**Comment by tuxayo** [comment]
Does anyone understands what is the disagreement about the the precise choice about whether or not displaying brand if name isn't present?

https://github.com/gravitystorm/openstreetmap-carto/issues/698#issuecomment-47897581
> Agree, it would stimulate correct tagging.

Is it the key point? (Correct as in complete I suppose)

**Comment by imagico** [comment]
First of all this issue is about the specific suggestion to render a brand label on features without a name tag in a way that is not limited to specific feature classes.  We have another issue on a more specific suggestion (#1874) that is open and we also had a pull request previously (#972) which was closed not because it was rejected but because it was stale.

The question of the role of brands in identifying and characterizing commercial establishments of various kinds is highly multi-faceted, especially if you look at it from a international, multi-cultural perspective.

There are concerns that when rendering (name OR brand) (or `COALESCE(name, brand)` in SQL) in an indiscernible styling that would be confusing and would not support our goal of providing constructive mapper feedback.  It might for example encourage mappers explicitly not to tag the name when they want the brand to show up or to not tag the brand in case the priorities are reversed and they think the name is the more relevant label.  That especially would apply if such a rule is applied broadly to various labeled features and not just specific feature classes as this issue suggests (and unlike #1874).  Suggestions have been made (like in #972) to solve some of this issue by rendering both in the label - but these come with their own problems.

Beyond that and what has been discussed so far displaying brands can have a culture-imperialist subtext, especially in parts of the world that use a non-latin script since for economic reasons most brands are written in latin script which would then be a foreign object in the map appearance.  In some parts of the world this integrates naturally into the local use of language and script while in other parts of the world the brand identity is perceived purely graphically based on logos and the latin script brand name is a truly alien artefact in the local cultural context.
