### ISSUE TITLE
Rendering international names

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#803]
It might make sense to render int_name in addition to name for placenames, in particular for places not in the Latin alphabet.

See also https://trac.openstreetmap.org/ticket/3065.

**Comment by sommerluk** [comment]
I would suggest to close this ticket as NOT_A_BUG.

**Comment by math1985** [comment]
I hear this issue coming up a lot when talking to people about our style. It's often the first 'problem' of the style they mention. For Gnome, it was even stated as one of the two reasons not to use this style for Gnome Maps.

Perhaps we should really partially reconsider our stance, and at least render on the country level names in English as well.

**Comment by matkoniecz** [comment]
>  For Gnome, it was even stated as one of the two reasons not to use this style for Gnome Maps.

Do you have a link to this discussion? I am curious what was the second problem.

**Comment by math1985** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=764841

**Comment by math1985** [comment]
@matkoniecz https://bugzilla.gnome.org/show_bug.cgi?id=764841

**Comment by kocio-pl** [comment]
int_name could be especially important for big geographical entities like continents, oceans, seas, mountains, rivers etc. - that's part of the problem with rendering on low zoom levels (see #2688), where human related objects are not too visible and natural objects can span across many countries.

**Comment by dieterdreist** [comment]
2017-09-12 22:15 GMT+02:00 kocio-pl <notifications@github.com>:

> int_name could be especially important for big geographical entities like
> continents, oceans, seas, mountains, rivers etc. - that's part of the
> problem with rendering on low zoom levels (see #2688
> <https://github.com/gravitystorm/openstreetmap-carto/issues/2688>), where
> human related objects are not too visible and natural objects can span
> across many countries.
>

int_name is not really defined, and the wiki suggests to use different tags
_instead_: "International name (note: consider using language specific
names instead; e.g., *name:en*=... - see above – International does not
(necessarily) mean English)". There is no such thing as an "international"
language hence neither there is an "international name".

**Comment by kocio-pl** [comment]
Maybe some international institution could be a source - unfortunately UN for example uses 6 languages:

https://unstats.un.org/unsd/geoinfo/geonames/

**Comment by math1985** [comment]
The openstreetmap.org website is English only right?

**Comment by pnorman** [comment]
> The openstreetmap.org website is English only right?

No.

**Comment by math1985** [comment]
It follows browser language? I don't see a way to switch.

**Comment by HolgerJeromin** [comment]
There is a switch in your account settings

**Comment by sommerluk** [comment]
Even the categories in the Nominatim search results and and country names in Nominatim and GeoNames search results are localized.

**Comment by kocio-pl** [comment]
The problem is that website elements and name searches are dynamic, while default tile layer is static. Using our current toolset we can't make it dynamic from inside the style.

There is however the possibility to do it on the deployment level - there could be for example rendering made with "name" substituted with "name:xx" for each language/region, but that would be overkill for the servers, so it's just a fantasy. There could be however layers with names - they could be rendered as vector overlay probably, which also takes some resources, but doesn't mean making ~100 parallel renderings. But this is outside the scope of this repo.

That's why we're looking for a compromise, which is not perfect, but at least makes sense. For some objects the "name" is simply a collection of names - it's quite easy in Belgium and in case of a river on a border ([Oder/Odra](http://www.openstreetmap.org/way/89253786)), but for big objects of international importance (like oceans and mountain ranges) it would be impractical to show every 150 names in one row.

There is also a possibility to go on with [a vector fork of osm-carto](https://github.com/geofabrik/openstreetmap-carto-vector-tiles), but it's also something related to deployment.

**Comment by math1985** [comment]
@gravitystorm How does opencyclemap deal with international names? Is it 'name:en' for countries, 'name'-newline-'name:en' for cities and 'name' for anything else?

**Comment by kocio-pl** [comment]
Hm, I guess that for some big objects like the oceans we could follow UN rule and show int_name according to their official languages - for example:

_المحيط الأطلسي / 大西洋 / Atlantic Ocean / Océan Atlantique / Атлантический океан / Océano Atlántico_

* looks decent (just 6 instead of 150!)
* covers 4 different major scripts
* covers different parts of the world
* covers probably majority of people that can read (about 85% out of ~7,2 mld -> ~6,12 mld) - ~3,518 mld using rough numbers of [total speaking](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers): 
 Arabic - ~422 mln
 Chinese ~1,09 bln 
 English - ~983 mln
 French - ~229 mln
 Russian - ~267 mln
 Spanish - ~527 mln
* follows established rule of the largest international (country-level) organization

It would mean that int_name tagging should be first [defined on a wiki](https://wiki.openstreetmap.org/wiki/Key:int_name) (currently just "User defined"), but it's doable at least.

**Comment by matkoniecz** [comment]
> It would mean that int_name tagging should be first defined on a wiki

Why? Names in specific languages are already provided by name:lang tags, such label may be build from such tags.

**Comment by pnorman** [comment]
I prefer our policy of using name, the name of the feature in the local language.

**Comment by sommerluk** [comment]
> I prefer our policy of using name, the name of the feature in the local language.

Me too.

**Comment by math1985** [comment]
To be clear, the areas with which people have problems are areas like this:
<img width="328" alt="screen shot 2017-09-20 at 10 28 00" src="https://user-images.githubusercontent.com/5251909/30634184-8a470306-9dee-11e7-9339-6066bdc0f8e6.png">



Or this:
<img width="298" alt="screen shot 2017-09-20 at 10 28 16" src="https://user-images.githubusercontent.com/5251909/30634161-75a23baa-9dee-11e7-9582-c22c4ec7122f.png">

**Comment by matkoniecz** [comment]
UN rule seems interesting, especially for labels like oceans where local language rule breaks down

**Comment by dieterdreist** [comment]
I think this map is interesting in the context:
https://de.wikipedia.org/wiki/Datei:WritingSystemsOfTheWorld.svg

still keep in mind that looking only on the surface area doesn't account
for the population. And the population are our potential users, not the
actual ones.

principal scripts besides latin are arabic, chinese, cyrillic plus maybe
"indian" variants

**Comment by kocio-pl** [comment]
Hindi has been proposed for some time:

https://en.wikipedia.org/wiki/Official_languages_of_the_United_Nations#New_proposed_languages

We could make our modification of "composite_int_name", for example:
- adding Hindi in Devanagari, to use more scripts (more diversity)
- removing other latin names leaving just English as the most popular with latin script (less space)

This might make sense. For example latin geonames can look similar, so "Atlantic Ocean" might be enough for someone who speaks only Polish ("Ocean Atlantycki") or only German (Atlantischer Ozean""), so we would cover even more users, especially because the map uses only written form (not spoken):

المحيط الأطلسي / Atlantic Ocean / अटलांटिक महासागर / Атлантический океан / 大西洋

The downside could be that UN rule is simple and ready, while reaching agreement for rules in OSM community (like tagging) tends to be very hard and time consuming.

**Comment by gravitystorm** [comment]
> @gravitystorm How does opencyclemap deal with international names? Is it 'name:en' for countries, 'name'-newline-'name:en' for cities and 'name' for anything else?

Pretty much - currently the country names come from Natural Earth, and there's a little more logic around city names (to do with avoiding adding newlines if either name or name:en is blank, and checking if name and name:en are identical).

I have a the flexibility with my own styles to choose English as the fallback in "name (newline) name:en", because I speak English, and so hey it's my choice. :-) Whether that's appropriate or not for this layer is a decision that should be made by a wider variety of viewpoints. 

Similar to @kocio-pl thoughts above, I choose English more for reasons of character recognisability (to other Latin-script-based first and/or second-language readers) rather than anything specific about the English language or where sometimes the English name is wildly different from other Latinised names. Potentially other choices, like German or Spanish, could fulfil similar Latin-based goals and still be widely understood.

**Comment by math1985** [comment]
I consulted the talk mailinglist: https://lists.openstreetmap.org/pipermail/talk/2017-September/078808.html

**Comment by stephankn** [comment]
The main site map (carto style) is (or at least was in the past) intended as a support tool for local mappers to also see their edits visualized.

Someone pointed to a map showing Thailand and claims people have problems with it. Let me assure you that local mappers have absolutely no problem with a map labeled in their language.

And others can use a bilingual rendering like http://thaimap.osm-tools.org/

By rendering bilingual you will notice that map-space is eaten up by additional label text which could otherwise show meaningful content to local mappers.

So leave the main map labeling as it is, supporting local communities. For "international" audience a dedicated rendering is easy to implement and can handle specific preferences with the fallback order as well.

**Comment by pnorman** [comment]
Coming back to this after the mailing list discussion

- Lots of discussion was about issues unrelated to osm-carto like how a new vector tile based style could have multiple languages. While true, its out of scope here.
- For their own use, people ["want a map with local names except where [they] can't read them"](https://lists.openstreetmap.org/pipermail/talk/2017-September/078818.html), which is also expressed here.
- There were various strange suggestions like Latin

I don't consider anything other than rendering the local name (status quo), rendering the English name, or a combined local and English rendering a serious option. Of these, the first and last are probably the best options. They're what I'm focusing on for the rest of this message.

I've gone back and forth on my opinion multiple times while writing *this reply*.

Adding English to the labels would have both advantages and disadvantages, so I looked back over [our goals](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md#main-goals). These are **our** goals and may not correspond to the goals of the osm.org frontpage, which is what people were more concerned with in the mailing list discussion.

- Legibility and clarity: I think this favours adding English labels. The downside is adding more text.

- Being understandable and supportive for mappers: Given the history of putting the English name into the name tag and the requests we get, I think this also favours adding English labels, although there are cases when it doesn't.

- Diversity: This favours the status quo.

- A rich map: Neutral. English labels shows that the data exists for multiple languages, but the status quo takes less space, giving more room for other labels.

- Maintainability: Neutral. Normally the status quo would be easier, but for reasons related to the next point, there shouldn't be significant code differences

- Adaptability and ease of use: Neutral. Normally, this favours English labels, as it's a change people deploying it would frequently like. But regardless of our decision, we should make it so that it's possible to easily pick which you want.

-----

We want people to be able to switch the style of names in their deployment easily. I think the best way to do this is wrap all names in a function call in the SQL. The function would have the signature of `name(text, hstore) RETURNS text IMMUTABLE STRICT`.

This also means that our choice of how to handle names doesn't have to be the same as the OSMF.

**Comment by sommerluk** [comment]
I am a little bit reluctant to give a special status to English only.

The main point about “English” seems to be more about “legibility”, and less about “language”. (If it would be about language, the first choice would be Chinese that has more speakers than English.) Legibility is about the writing system: I am German, so I can recognize the letters in Italian text, even though I do not speak Italian, because both use the Latin alphabet/writing system. If I see “北京市” in the map, I’m maybe not even available to type it on my keyboard to search for it. But for “Beijing” I can, even if I do not speak English very well. The languages with Latin writing system together have far more speakers than Chinese, so that would be a valid argument for Latin script instead of Han script.

Within the group of languages with Latin script, considering native and foreign speakers, English is the first one, followed by Spanish, Malay (but only partially with Latin script), Portuguese, French (and many more). It might be useful to consider these as fallback if English is not available?

Disclaimer: I still tend to render local names only.

**Comment by dieterdreist** [comment]
sent from a phone

> On 12. Oct 2017, at 17:00, Lukas Sommer <notifications@github.com> wrote:
> 
> Disclaimer: I still tend to render local names only.


+1, it’s a strong statement and differentiates us from us-dominated commercial maps, although admittedly it reduces significantly the individual usefulness in areas where you can’t read the script

**Comment by stephankn** [comment]
@pnorman  sounds like a good idea to enable the style to be easily localized. That way the rendering can be easily customized based on the map makers decisions.

Have you considered merging in the changes done by @giggls to enable easy localization? Is is based on functions in PostgreSQL as well:  https://github.com/giggls/mapnik-german-l10n/tree/master/plpgsql

**Comment by giggls** [comment]
I also have a localized version of osm carto:
https://github.com/giggls/openstreetmap-carto-de/tree/upstream+l10n

Slippymap (with english l10n) here:
https://tile.iosb.fraunhofer.de//#map=5/30.1198/33.2703/3

**Comment by math1985** [comment]
Bases on the responses here and on the mailing list, there seems to be no support for adding English names. I'm there going to close this issue. Thank you all for your contributions to the discussion!
