### ISSUE TITLE
Special rendering for intermittent waterways

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#805]
There is an approved proposal for key intermittent=yes applicable to waterways:

 http://wiki.openstreetmap.org/wiki/Proposed_features/Intermittent_river

Please add rendering of intermittent waterways as dashed blue line.

See also https://trac.openstreetmap.org/ticket/3681.

**Comment by RAytoun** [comment]
This is great news and will be very helpful. 
The usual cartographic practice for wadi is a pecked line but brown, not blue. The brown renders very well in arid areas as it does not look as though there is loads of water but still shows that there is a watercourse. I do not at this stage know how that will clash with other line symbols that may be in a similar colour.

**Comment by pnorman** [comment]
tracks use a dashed brown line.

**Comment by liotier** [comment]
Seasonality is a specific sort of intermittency - variation is according to seasons instead of more randomly weather-related. I came here to ask for waterways with seasonal=yes to be rendered the same way as intermittent=yes

For now, seasonal waterways appear as solid lines and it is a bit disconcerting.

Treating seasonal=yes the same way as intermittent=yes feels quite correct and it would also minimize the work necessary to take this extra tag into account.
