### ISSUE TITLE
Render building=* single nodes

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#806]
Currently we render only building polygons.

Many buildings with known position and unknown shape have been submitted as a single node, and should be rendered with a small square (size depending on zoom).

See also https://trac.openstreetmap.org/ticket/2613.

**Comment by bjohas** [comment]
I'd like to raise this issue again.

https://wiki.openstreetmap.org/wiki/Key:building suggests that nodes tagged as buildings are fine. It seems that if the node is named, it does appear. Not sure about what else makes the node appear. However, building=yes doesn't seem to be sufficient.

https://taginfo.openstreetmap.org/keys/?key=building says there's just under 1m buildings as nodes (about 0.5% of buildings that are areas, which is about 220m in total). 

Running some overpass queries, I'd say there are around 60,000 buildings as nodes in sub-Saharan Africa - seems a shame to not render these, when otherwise map data is still sparse in many areas (despite the amazing work of Missing Maps).

By way of a picture: Buildings as nodes in West Africa: http://overpass-turbo.eu/map.html?Q=%2F%2F%20Fiwila%20buildings%0A%5Bout%3Ajson%5D%5Bbbox%3A3.5134210456400448%2C-19.62158203125%2C19.08288436934017%2C1.8017578124999998%5D%5Btimeout%3A360%5D%3B%0A(%0A%20%20node%5Bbuilding%5D%3B%0A)%3B%0Aout%20skel%20qt%3B%0A

Many thanks for your views!

**Comment by imagico** [comment]
I still don't think we will want this.

The numbers:

900k building nodes, 550k of those also have an address tag, 150k have a name tag.  I have not checked how many have both.

These numbers also indicate a significant portion of these nodes have the building tag inferred - for example from address imports where people simply assumed all or some addresses imply a building.  Or mappers who mapped addresses in the ground in an area where no high resolution imagery was available and simply adding `building=house` to all of them.

Rendering a building just with a dot marker of some sort would be very non-intuitive and confusing for the map user.  There is no precedent for this kind of rendering in other maps either AFAIK.  And i also don't think this kind of rendering would create a mapping incentive for improving the mapping to actual building geometries compared to when nothing is rendered at all.

**Comment by pnorman** [comment]
I am also in agreement with not rendering. Right now we render buildings with a fill. To have a rendering which works for points we would need some kind of icon. This would not work well with most buildings.

**Comment by polarbearing** [comment]
Still agree in not to render them (as long as the house number is rendered if an address exists, which we do). Even poking into the Africa example shows polygon buildings next to nodes.

> There is no precedent for this kind of rendering in other maps

Well I know 1:50000 printed maps on which buildings are little square dots, however they do not print building outlines otherwise.

**Comment by imagico** [comment]
> Well I know 1:50000 printed maps on which buildings are little square dots, however they do not print building outlines otherwise.

Ultimately not really relevant here but if you can point me to a map design that renders buildings using abstract geometric symbols that are not house icons or actual mapped geometries (which would already be the case if the dots are oriented in actual building direction) that would be interesting.

**Comment by polarbearing** [comment]
Indeed there seems to be some orientation, however the squares are only used for isolated houses. For residential settlements, a grey filling for the whole town is used. As the pixel count for the house drawings is so small, they look very similar to the height points. Confirms my opinion to keep the style here as is. 
![1_50000_example](https://cloud.githubusercontent.com/assets/8266355/26249175/b1c8d47c-3ca5-11e7-9f79-cc946d02a847.png)

**Comment by dieterdreist** [comment]
2017-05-19 15:14 GMT+02:00 polarbearing <notifications@github.com>:

> Indeed there seems to be some orientation, however the squares are only
> used for isolated houses. For residential settlements, a grey filling for
> the whole town is used. As the pixel count for the house drawings is so
> small, they look very similar to the height points. Confirms my opinion to
> keep the style here as is.



yes, 1:50000 maps usually don't use actual geometries (would be too
detailed) but use abstracted generalizations, not just for houses but also
for industrial buildings, train stations etc. Still, these do represent (in
the cases I know of) more than just the information yes/no (there is
abstraction of shape, orientation and spaces between). Also they usually do
filter out least important buildings and do not render _every_ building

**Comment by bjohas** [comment]
I guess it may be more of an HDM carto issue really, as my concern was primarily sub-Saharan Africa - so continuing the discussion there. https://github.com/hotosm/HDM-CartoCSS/issues/289
