### ISSUE TITLE
Please render amenity=parking + capacity:disabled>0

### ISSUE THREAD

**Issue by achadwick** [gravitystorm/openstreetmap-carto#81]
As noted at https://trac.openstreetmap.org/ticket/4067, parking with one or more disabled spaces - _capacity:disabled>=1_ - should receive a distinctive icon. There's a nice one in the contact sheet at http://www.sjjb.co.uk/mapicons/contactsheet#transport as mentioned in the original report.

**Comment by Adamant36** [comment]
@pnorman now that individual parking spaces are rendered as areas is there any chance this could reopened? It might be cool to add a wheelchair icon to individual handicap parking spaces mapped as areas.

**Comment by imagico** [comment]
Re-opening this - since it does not really make much sense to consider #4955 while not considering this.  If either of these is feasible to do in this style will need to be determined, but lets not rule out this up front while considering #4955.

**Comment by dch0ph** [comment]
Yes, it would make sense to indicate whether a parking area has disabled spaces as part of considering whether / how to indicate the spaces themselves, since the latter would only be feasible at the highest zoom.

But I don't think the symbol proposed, with the wheelchair tucked into the P is ideal for indicating `capacity:disabled > 0`. I think it works better for "this car park has exclusively disabled spaces" (`capacity` = `capacity:disabled`). The "P with X tucked inside the symbol" is currently used as parking (exclusively) _for_ X. It would be useful to clearly indicate exclusively disabled parking since this helps the map user understand the significance of multiple car parks at a given venue (and reduce the use of misuse of descriptions-s-names, e.g, `name=Disabled parking`).

I appreciate that we don't have good rendering support for "augmented symbols", but a better symbology for "has X feature" would be an added small non-overlapping symbol to one side of the P e.g. top right.

**Comment by imagico** [comment]
Yes, since we use the 'P' plus small symbol on bottom right for bicycle/motorcycle parking the analog interpretation of the wheelchair would be misleading.  That does not rule out the idea to indicate the presence of dedicated disabled parking spaces in general though.

> but a better symbology for "has X feature" would be an added small non-overlapping symbol to one side of the P e.g. top right.

The problem with that is that this would have to be part of the same SVG because we don't want the addon symbol to show while the base symbol is blocked by something else.  So - if we have a number of different addon symbols we would need a substantial number of different SVGs for the different permutations.  And - since blocking calculations in Mapnik are always based on bounding boxes - placement would be somewhat inefficient, i.e. quite a few symbols for which there would be space would not be placed because the empty space in the other corners of the symbol would still be considered blocking.

**Comment by dch0ph** [comment]
> The problem with that is that this would have to be part of the same SVG because we don't want the addon symbol to show while the base symbol is blocked by something else. So - if we have a number of different addon symbols we would need a substantial number of different SVGs for the different permutations. And - since blocking calculations in Mapnik are always based on bounding boxes - placement would be somewhat inefficient, i.e. quite a few symbols for which there would be space would not be placed because the empty space in the other corners of the symbol would still be considered blocking.

Yes, that's true. Realistically you wouldn't want more than two "add ons" and would try to get everything into a single 14 x 14 px SVG.
