### ISSUE TITLE
Render access=private for highway=service and area=yes

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#829]
It would be nice if also the tag access=private is been tagged for highway=service and area=yes.

See also https://trac.openstreetmap.org/ticket/4460.

**Comment by pnorman** [comment]
After this time without any progress or interest in *how* to render this combination, I'm going to close this issue.

**Comment by matkoniecz** [comment]
I will try to find something as part of road refactoring.

**Comment by jojo4u** [comment]
A solution to this should be in accordance to a migration vom highway=service + area=yes to highway:area=service or at least a discussion about it. IMHO highway=* + area=yes hat many problems and should not be proliferated.

**Comment by matkoniecz** [comment]
highway=service + area=yes is frequently misused (for example - instead of highway:area=motorway) but sometimes it is a valid tagging.

**Comment by matkoniecz** [comment]
I failed to find styling that would work properly.

**Comment by jeisenbe** [comment]
Closing, since we have not found a feasible way to render this differently, per https://github.com/gravitystorm/openstreetmap-carto/issues/829#issuecomment-134954784 and https://github.com/gravitystorm/openstreetmap-carto/issues/829#issuecomment-102755183

 I also think it would make more sense to render `surface=*` first.

It can be reopened if there is a good idea about how this access information can be shown for highway areas in addition to `surface=*`
