### ISSUE TITLE
Add rendering for amenity=police area

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#848]
Areas mapped as amenity=police should be rendered.

[Example](http://www.openstreetmap.org/#map=18/51.91870/-0.65427)

See also https://trac.openstreetmap.org/ticket/3622.

**Comment by matkoniecz** [comment]
I think that it is impossible to continue increasing number of different landcovers.

Also number of different outlines is limited.

I propose to close this as this area is not critically important to render.

**Comment by math1985** [comment]
I would still prefer to reserve a colour for 'other' types of amenity - I think it'd be helpful to visually group buildings within an area, be it schools, police buildings or hospitals, together.

**Comment by kocio-pl** [comment]
+1

**Comment by polarbearing** [comment]
> I think it'd be helpful to visually group buildings within an area

Outline ->  #1624

**Comment by matkoniecz** [comment]
> I would still prefer to reserve a colour for 'other' types of amenity - I think it'd be helpful to visually group buildings within an area, be it schools, police buildings or hospitals, together.

Maybe just use this pale yellow colour - it is anyway used now for educational areas and hospitals. But assuming that it would be done - what is the threshold? I think that rendering areas of individual shops or restaurant (within building or outside) is certainly too much and rendering hospital/police/etc area may make sense.

Overall I would prefer to stop rendering hospital/educational areas rather than adding more features rendered as areas.

**Comment by polarbearing** [comment]
> Overall I would prefer to stop rendering hospital/educational areas

Please don't before we have another method to visualise their boundaries. We should start working on mock-ups for boundaries for the cases in #1624.
