### ISSUE TITLE
Render closed roads tagged with sport=running as line instead of area

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#854]
A closed way tagged with highway=path, sport=running is currently rendered as area.

See also https://trac.openstreetmap.org/ticket/4350.

**Comment by dieterdreist** [comment]
> Am 31.12.2014 um 21:32 schrieb Paul Norman <notifications@github.com>:
> 
> Changing sport from a polygon to a linear would probably fix this, but I'm not sure of other impacts that would have.


sport is really an attribute and not a tag to constitute a feature anyway=

**Comment by math1985** [comment]
> sport is really an attribute and not a tag to constitute a feature anyway=

So would hstore fix this, if we drop sport from the list of keys in the style file?

**Comment by math1985** [comment]
Best done with osm2pgsql on import.

**Comment by scaidermern** [comment]
Apparently this issue also leads to `highway=raceway` not being rendered if combined with `sport=motor`, see [Odd "highway=raceway" rendering issue](https://help.openstreetmap.org/questions/19608/odd-highwayraceway-rendering-issue).

**Comment by pnorman** [comment]
I'm tempted to punt this to be changed upstream in osm2pgsql first. If it's wrong, it's wrong for everyone.

Yes, I'm a maintainer on both.

**Comment by math1985** [comment]
> I'm tempted to punt this to be changed upstream in osm2pgsql first.

+1

**Comment by sorcrosc** [comment]
any news?

**Comment by Wuzzy2** [comment]
This bug applies to highway=raceway as well. If you tag a way as highway=raceway + sport=karting, the raceway becomes invisible.
I can reproduce the bug and can point you to a specific example. Here's a screenshot:
https://i.imgur.com/ipts8Y1.png

OSM link: https://www.openstreetmap.org/#map=18/48.12027/7.78816
Way ID: 91525275
This raceway was rendered before I added `sport=karting`.

Note the wiki explicitly encourages `sport` to be set for `highway=raceway`, so this looks like a clear renderer fail.
I hope this information helps. :-)


@sorcrosc: I think suggesting mappers to introduce redundant tags because of a renderer bug is tagging for the renderer and thus a bad idea.

**Comment by sorcrosc** [comment]
Of course I can't disagree but maybe a slight sin to set an implicit tag and this prevents people spending time trying to understand the problem. The title here also doesn't help so much finding the bug.

**Comment by kocio-pl** [comment]
I guess both problems are now fixed with v4.0.0 release?

**Comment by math1985** [comment]
Yes, should be fixed.
