### ISSUE TITLE
clipped ref shield

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#950]
A two-line `ref` shield for a primary road is cut in half at a tile boundary at zoom level 11:

![US 22;SR 3](https://cloud.githubusercontent.com/assets/1231218/4268299/39f78958-3cac-11e4-9b7b-7bddf1eed1a9.png)

This issue was reported as [note #237488](http://www.openstreetmap.org/note/237488#map=11/39.1977/-84.3729&layers=N) at OpenStreetMap. I don’t know if there’s anything more to be done about clipping issues, but I figured this would be a better place to discuss possible solutions than at OSM.

**Comment by talaj** [comment]
Fixed in Mapnik by https://github.com/mapnik/mapnik/issues/2929.

**Comment by pnorman** [comment]
> Fixed in Mapnik by mapnik/mapnik#2929.

No it's not. Results being returned in an indeterminate order still can cause differences in label order. As Dane said in https://github.com/mapnik/mapnik/issues/2929#issuecomment-119042471, having the same placement can require consistent sorting.

**Comment by talaj** [comment]
That's true, determinate order is also important.

**Comment by pnorman** [comment]
This issue is all about determinate order - the database is the only real potential cause of differences between orm and yevaud. The Mapnik issue was somewhat misnamed, it was about label placement being influenced by bounding box, but here at least part of the issue involves an indeterminate result where the cut off labels can chance with the order data is loaded into the database.

**Comment by pnorman** [comment]
I think we're done with this issue - people can open new ones if there's something specific we can act on.
