### ISSUE TITLE
Add rendering for toll_booth

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#958]
I am on mobile so i am not 100% sure it is missing (or there is an issue about it) but rendering barrier=toll_booth would be nice.

Osmand renders it same as a lift gate plus an $

**Comment by sommerluk** [comment]
Or maybe an icon based on the toll road sign http://upload.wikimedia.org/wikipedia/commons/6/64/BAB-Grenze.svg ?

**Comment by math1985** [comment]
That's not a toll road sign but a border control sign.

**Comment by matkoniecz** [comment]
Maybe rendering it like barrier=lift_gate would be OK?

**Comment by pnorman** [comment]
Given we're not rendering toll *roads*, which are generally considered more important, I'd rather not render the booths.

**Comment by polarbearing** [comment]
barrier=lift_gate alone would be a bit confusing, since they are a common feature of private parking which belongs on membership and not simple payment. Further, toll is nowadays often collected flee-flow without the physical barrier. 

I'd rather follow @pnorman and neither render booths nor roads (#593).

**Comment by pnorman** [comment]
Closing - if we ever figure out a way to render tolls on roads, we can reconsider it.

**Comment by kocio-pl** [comment]
Maybe some kind of tickets or car near the wall or car under the lift gate (in transportation blue, I guess)?

**Comment by dieterdreist** [comment]
in Italy most motorways are toll roads. The toll booths are significant landmarks and I don't think we have to render toll roads in order to render the booths, I'm in favor of rendering them.

**Comment by sommerluk** [comment]
I would also render it.

Currently there is no special rendering for toll roads. But there are various other barrier=* tags that are currently rendered. So when are yet some other barriers that are rendered, and so IMHO it would be logical to render also barrier=toll_booth.

@kocio-pl 
> Maybe some kind of tickets or car near the wall or car under the lift gate

I like this idea. Maybe in conjunction with some symbol for money?

**Comment by vbertola** [comment]
I would really like to add a comment in favour of rendering toll booths in some clear way, _especially_ because you're not rendering toll roads. In Italy, some motorways are free, others are paid with a "closed" system (i.e. a toll booth on every entrance/exit), others are "open" i.e. you only pay when you encounter a toll booth in the middle of the motorway, so some stretches are free and others are not. For this latter type of roads, knowing at a glance where the toll booth is really makes a difference, because most people choose their routes so to avoid the paid stretches if they can. For this reason, all Italian road atlases traditionally have a specific, well prominent symbol for toll booths, and OSM is really at a disadvantage on this.

**Comment by kocio-pl** [comment]
Could you provide the 14px icon for this?

**Comment by vbertola** [comment]
There already are proposed icons here:
http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth
The first one in particular looks good (though I'd rather have the € symbol in Europe instead of $, but I don't know if it's possible to change the icon according to the geographic area - in that case I'd be happy to make a € version of the icon).

**Comment by pnorman** [comment]
> The first one in particular looks good

It's over 14x14. We also try to have our symbols region-agnostic.

**Comment by vbertola** [comment]
Ok, let me work on this, I assume that the guidelines are the ones listed here:
http://wiki.openstreetmap.org/wiki/Map_Icons#Standard_tile_layer_.28openstreetmap-carto.29
Should it be light blue (like bus stops, parkings etc) or grey (like traffic lights, gates etc)?

**Comment by kocio-pl** [comment]
I'm reopening, since you're ready to try.

I was thinking about colors (also brown), but have no conclusion yet, so we could just check them when a shape is more or less ready.

More detailed icon guidelines are here:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines

**Comment by pnorman** [comment]
> Ok, let me work on this, I assume that the guidelines are the ones listed here:

Our guidelines are at https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines. Any other page is not official.

**Comment by math1985** [comment]
To avoid confusion and duplication of information, I replaced the info on the wiki by a Github link.

**Comment by kocio-pl** [comment]
What about using [lift gate icon](https://github.com/gmgeo/osmic/blob/master/barrier/lift-gate-14.svg), but blue (or brown) - not black as the other barriers? It could be enough to know that this is not ordinary gate.

**Comment by sommerluk** [comment]
Sound good to me.

**Comment by kocio-pl** [comment]
Preview of [A2 toll booths in Poland](https://www.openstreetmap.org/#map=17/52.16344/20.73031) using `lift-gate-14.svg` (standard gate icon is visible nearby):

z16
![xbux3al](https://user-images.githubusercontent.com/5439713/30773969-cc6455ce-a07b-11e7-9c5c-39a2b9305551.png)

z17
![sdifhan4](https://user-images.githubusercontent.com/5439713/30773970-d11ca422-a07b-11e7-96ae-d7ce9bb80044.png)

z18
![xucbqcyz](https://user-images.githubusercontent.com/5439713/30773972-d3beb364-a07b-11e7-9bfc-5241d236e200.png)

z19
![quflbs0m](https://user-images.githubusercontent.com/5439713/30773974-d6872aa4-a07b-11e7-9c78-021cbfca4412.png)

The same with `lift-gate-10.svg`:

z16
![0eenkyil](https://user-images.githubusercontent.com/5439713/30774016-88a0b71e-a07c-11e7-878c-94bcec631bd3.png)

z17
![er2agdl](https://user-images.githubusercontent.com/5439713/30774018-8a4d928a-a07c-11e7-87b3-cea6acb2f030.png)

z18
![ypqhok1u](https://user-images.githubusercontent.com/5439713/30774019-8c707d98-a07c-11e7-956a-98782ad8ee7f.png)

z19
![qmcjl1wr](https://user-images.githubusercontent.com/5439713/30774021-8f73822e-a07c-11e7-9a59-a8ab2be5f99b.png)

And with our standard `liftgate.svg` icon:

z16
![qvumrk3h](https://user-images.githubusercontent.com/5439713/30774050-0fd1a428-a07d-11e7-91d0-2200b8ac1ed0.png)

z17
![c9dfgnnf](https://user-images.githubusercontent.com/5439713/30774051-112dd6c0-a07d-11e7-8b01-1e484629a1b1.png)

z18
![jeceqsws](https://user-images.githubusercontent.com/5439713/30774052-135b1804-a07d-11e7-82b9-bc248f5b33dd.png)

z19
![qxqtk9ii](https://user-images.githubusercontent.com/5439713/30774055-15ed16b2-a07d-11e7-9d1c-2e6ac4e7568d.png)

**Comment by MaestroGlanz** [comment]
I've got another suggestion:

https://wiki.openstreetmap.org/w/images/0/08/Tollbox.svg

**Comment by kocio-pl** [comment]
Could you make rendering test? The code is here, you just need to replace `toll_booth.svg`: https://github.com/kocio-pl/openstreetmap-carto/tree/toll

**Comment by vbertola** [comment]
Thanks for the work, I have been traveling a lot and did not have time to work on this. But any icon more or less is fine - I'd be interested in how it shows up at geographical scale, though. In Italy, toll booths are being mapped not as individual gates but as a single node per each direction:

https://www.openstreetmap.org/node/2542231532
http://www.openstreetmap.org/node/936954809

So one would really like the "toll booth" symbol to appear (once) even at a very high scale, e.g.:

https://www.openstreetmap.org/node/2542231532#map=14/45.3493/9.3090

I don't know how this is made, i.e. how is the renderer going to decide which elements are shown at higher scales and which are not.

**Comment by kocio-pl** [comment]
The renderer decides which one of a few POIs will be rendered if there's a place only for one, but if there are no other obstacles, it will show it as early as we decide, so don't worry.

The question is however which initial zoom level they should start appearing. What do you think about it?

**Comment by vbertola** [comment]
In Italy, motorway junction names start appearing at 12x, doing the same would be a good choice (if possible, the toll booth name could be shown as well near the icon, however that is not as essential as for junctions).

**Comment by MaestroGlanz** [comment]
@kocio-pl Not really or not right now. I'm still getting into creating maps from data. So this may take a while.

**Comment by kocio-pl** [comment]
OK, just tell me if you will need some help. I guess this discussion goes quite well, so we can wait a bit longer with a final solution.

**Comment by kocio-pl** [comment]
Any news here?

**Comment by MaestroGlanz** [comment]
I fail to create maps. So no so far.

**Comment by sommerluk** [comment]
I still think this feature would be important to render.

Indeed, the proposal by @kocio-pl to use a barrier icon in blue is reasonable.

I’ve tried to combine some symbol for money (banknotes and coins like https://commons.wikimedia.org/wiki/File:Zeichen_391_-_Mautpflichtige_Strecke,_StVO_2003.svg) with a barrier, but it doesn’t work on a 14×14 icon. Even when using only banknotes and coins without a barrier, it doesn’t work – simply not enough space.

Other icon sets often use one of these:
- A barrier combined with a dollar sign. This idea to use a dollar-sign is not region-agnostic. There exists a generic currency symbol (U+00A4 ¤ CURRENCY SIGN) but likely post people won’t recognize it, so that’s not a good option either.
- A completely abstract shape (like a circle or a square). That would not be so nice for openstreetmap-carto as we are a quite feature-rich map yet.
- Just a barrier icon. I think that’s also the best option for us.

About the rendering examples of @kocio-pl: The `lift-gate-14.svg` icon is difficult to recognize for me. I would prefer the versin with `liftgate.svg` or – to make it even more clear and also different from our standard barrier icon – something like ![bitmap](https://user-images.githubusercontent.com/6830724/34601259-0d048df6-f1f3-11e7-8265-d4c67fbd20fc.png) which I could provide as pixel-aligned SVG if desired.

**Comment by SomeoneElseOSM** [comment]
In another style I also went with lift gate + money symbol: https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/symbols/tollbooth.png .  See for example https://map.atownsend.org.uk/maps/map/map.html#zoom=20&lat=53.2605242&lon=-0.771353 .

**Comment by kocio-pl** [comment]
@sommerluk: 

> I still think this feature would be important to render.

I'm just waiting for a code ready to be merged. Currently I like the @MaestroGlanz design the most (https://github.com/gravitystorm/openstreetmap-carto/issues/958#issuecomment-333561836), but it hasn't been tested yet:

https://wiki.openstreetmap.org/wiki/File:Tollbox.svg

Do you want to test it and make the PR?

**Comment by vbertola** [comment]
Sorry for not having been able to work on this. But I also think that the booth + barrier design, without money symbols, is the most neutral option.
