### ISSUE TITLE
osm-carto for TagInfo

### ISSUE THREAD

**Issue by sabas** [gravitystorm/openstreetmap-carto#961]
The new feature of Taginfo allows to give information about usage for a selected tag in a project
openstreetmap-carto is a natural fit
http://wiki.openstreetmap.org/wiki/Taginfo/Projects

I did a list some time ago, perhaps it's useful https://github.com/sabas/doesitrender/blob/gh-pages/taglist.md

**Comment by nebulon42** [comment]
@giggls proposed an alternative in #2614. To manually create the file and then make sure that each change updates it. Still there is the risk that the file gets outdated. Would this be worth a try?

**Comment by giggls** [comment]
I don't think that keeping such a file in line with the current version of the style would be a problem, if pull requests would require changing this file as well. The main effort would certainly be the creation of the initial version.

**Comment by imagico** [comment]
A few thoughts on the matter:

* to have this would be good and IMO worth a bit of work in maintenance when making changes to the style.
* it would be an obvious and fairly trivial byproduct of generating a map style legend so it certainly makes no sense to separately maintain a legend and a taginfo list.  Since we currently have no legend this is not really practically relevant at the moment of course.
* having a plain list of tags a taginfo json file is produced from via script is probably easier to maintain than writing a json file by hand.
* it might make maintenance easier if we'd structure the list by layer - which would of course require removing duplicates in processing.

**Comment by giggls** [comment]
I like the Idea of having a Text file which is ordered by layer and a script which will generate the Taginfo file. In this case it would even be possible to add tag combinations which are currently not supported in Taginfo project format.

**Comment by pnorman** [comment]
I'm iffy on if this is worth the maintenance burden. If we do do it, we should make sure that we can build a legend from it, and that we're not doing it as JSON, because that will lead to difficult to solve merge conflicts.

**Comment by kocio-pl** [comment]
While it would be nice to have osm-carto on Taginfo, this is beyond our manpower and nobody seems to be interested to even start, so I close it now. If there will be some automatic solution or somebody ready to take care of it, it can be reopened.

**Comment by ImreSamu** [comment]
My "poor man" suggestions: just add the  osm keys:

not perfect  - Proof Of Concept : 

```bash
$ cat project.mml | grep -oP "tags[^']*'.+?'"  | cut -d"'" -f2 | cut -d"=" -f1 | sed 's/"//g' | sort -u
addr:unit
advertising
capital
denomination
ele
emergency
entrance
ford
generator:source
height
highspeed
iata
icao
indoor
intermittent
leaf_type
memorial
operator
population
power_source
public_transport
recycling_type
seasonal
tower:construction
tower:type
usage
wetland
$ cat openstreetmap-carto.style |  grep '^[[:blank:]]*[^[:blank:]#;]' | tr -s ' ' | cut -d' ' -f2 | awk '!/(z_order|way_area)/' | sort -u
access
addr:housename
addr:housenumber
addr:interpolation
admin_level
aerialway
aeroway
amenity
barrier
bicycle
boundary
bridge
building
construction
covered
foot
highway
historic
horse
junction
landuse
layer
leisure
lock
man_made
military
name
natural
oneway
place
power
railway
ref
religion
route
service
shop
surface
tourism
tracktype
tunnel
water
waterway
```

for detecting  the `object_types` ( `node`,`way`,`area`,...) need some extra magic.

**Comment by kocio-pl** [comment]
OK, more automatic tools would be needed. What would be the goal however, just the information in Taginfo that osm-carto uses this tag or what?

**Comment by HolgerJeromin** [comment]
@ImreSamu 
highway is missing. 
man_made, landuse, leisure is quite useless imo.
Examples that this is not easy to pull out of the sources. 8-/

**Comment by ImreSamu** [comment]
Sorry for not being clear enough

My idea:
* `openstreetmap-carto.style`  - parsed for database column  ( and the `highway` is here !  )
*  `project.mml`  parsed for HSTORE osm keys  ( always start with `tags` )  some example:
      * `tags->'advertising'`
      * `tags->'memorial'`   
      * `tags @> 'ford=>stepping_stones'`
      * `tags @> '"generator:source"=>wind'`
      * `tags?'ele'`
* merge the two result + format

My Minimal result :
* openstreetmap-carto -  [taginfo_project.json](https://gist.githubusercontent.com/ImreSamu/fb70553e69e7337c956576920f416149/raw/331aa73104cc2b1367dbbe3a7d8c810568e3559c/taginfo.json)
* example screenshot ( on my test taginfo )  what you can expect:
![screenshot from 2018-03-27 19-17-56](https://user-images.githubusercontent.com/2217320/37983479-e3cd1f16-31f3-11e8-8bd9-e721225ac336.png)

Extra:  We need a strict SQL guideline for a good parsing.
  *  https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#sql-style-guidelines

imho:
*  this is useful for the average OSM mappers, not for the project members.
*  the minimal version is better than the nothing
*  later we can improve: Iterative and incremental development 

@HolgerJeromin : 

>highway is missing.

Sorry for the confusion...
this on the second part ...  ( see after `$ cat openstreetmap-carto.style ` ... ) 

>man_made, landuse, leisure is quite useless imo.

imho:  there are another minimal project here
 *  https://taginfo.openstreetmap.org/keys/man_made#projects
![screenshot from 2018-03-27 19-54-37](https://user-images.githubusercontent.com/2217320/37985318-bcd3dc56-31f8-11e8-8937-7a2fb3ee9080.png)

and according to the "taginfo"
"This table shows all projects known to taginfo that use OSM tags in some way."  - and IMHO it is useful for the new mappers, that this key is used by the "openstreetmap-carto" project.

**Comment by kocio-pl** [comment]
I agree that you can start with this and fine tune it later on. What would you need from this project to make it happen in Taginfo? I guess you can make it on your own, because the source is publicly available, but if there is something you need, just tell and we can think (and I will reopen this ticket). We could host the script, but maybe it's more related to Taginfo?

**Comment by kocio-pl** [comment]
I prefer Python, since it makes it more platform independent. You think it's better to add it into the style then develop and run it independently?

This way or another I reopen the issue, since there is a genuine progress.

**Comment by HolgerJeromin** [comment]
The json file could be updated before release (like the chicago preview image here in the repository).

**Comment by ImreSamu** [comment]
I have started working on this ...
* rewritten in Python
* added some extra

see more : https://github.com/gravitystorm/openstreetmap-carto/pull/3151

Don't expect fast result ...

**Comment by HolgerJeromin** [comment]
And remove "mapnik" from the title. It is not complete wrong worded, but there are too many which calls this style still "mapnik"

**Comment by kocio-pl** [comment]
Right, I would change it like this:
"OpenStreetMap.org mapnik style, in CartoCSS" -> "Default OpenStreetMap.org style using CartoCSS"

**Comment by ImreSamu** [comment]
a little statistics  ...  

"new keys"  == new keys in the ~ taginfo-project file

version change  | N of "new keys" | List of "new keys" 
----------------|--------------------------------|----------------------------
v4.0.0 - v4.1.0 | 2 | iata, icao
v4.1.0 - v4.2.0 | 4 |  highspeed, leaf_type, memorial, usage
v4.2.0 - v4.3.0 | 2 |  emergency, ford
v4.3.0 - v4.4.0 | 1 |  addr:unit 
v4.4.0 - v4.5.0 | 1 | public_transport
v4.5.0 - v4.6.0 | 0 |
v4.6.0 - v4.7.0 | 4 | entrance, indoor, recycling_type, seasonal
v4.7.0 - v4.7.1 | 0 |
v4.7.1 - v4.8.0 | 0 |
v4.8.0 - v4.9.0 | 4 | advertising, height, tower:construction, tower:type

**Comment by ImreSamu** [comment]
updated statistics ...


version change  | N of "new osm keys" | New osm keys  | Removed osm keys 
----------------|----------------------------------|------------------------- | ------
v4.0.0  - v4.1.0  | 2 | iata, icao
v4.1.0  - v4.2.0  | 4 | highspeed, leaf_type, memorial, usage
v4.2.0  - v4.3.0  | 2 | emergency, ford
v4.3.0  - v4.4.0  | 1 | addr:unit 
v4.4.0  - v4.5.0  | 1 | public_transport
v4.5.0  - v4.6.0  | 0 |
v4.6.0  - v4.7.0  | 4 | entrance, indoor, recycling_type, seasonal
v4.7.0  - v4.7.1  | 0 |
v4.7.1  - v4.8.0  | 0 |
v4.8.0  - v4.9.0  | 4 | advertising, height, tower:construction, tower:type
v4.9.0  - v4.10.0 | 2 | castle_type, office
v4.10.0 - v4.11.0 | 1 | location
v4.11.0 - v4.12.0 | 2 | information, lock_name
v4.12.0 - v4.12.1 | 0 |
v4.12.1 - v4.13.0 | 0 |
v4.13.0 - v4.14.0 | 0 |            
v4.14.0 - v4.15.0 | 1 | attraction |
v4.15.0 - v4.16.0 | 1 | sport |
v4.16.0 - v4.17.0 | 5 | artwork_type, basin, parking, telescope:diameter, telescope:type |
v4.17.0 - v4.18.0 | (+2) + (-1) | healthcare, station | power_source

**Comment by jeisenbe** [comment]
The demo project above is no longer at the link (http://as-af.taginfo-dev.opengeodata.hu/projects/osmcartov2#tags), and the related PR was closed (#3151). 

It does not look like there is an easy way to do this.

There is now a maintained legend of most features rendered in this style at:
- https://wiki.openstreetmap.org/wiki/SymbolsTab
- https://wiki.openstreetmap.org/wiki/AreasTab
- https://wiki.openstreetmap.org/wiki/LinesTab

And most feature pages on the wiki have a rendering sample, which can be used by taginfo's taglists. 

So, is this still needed, or can we close this issue?

**Comment by pnorman** [comment]
Closing for the reasons above.

**Comment by SomeoneElseOSM** [comment]
Whilst there may not be the appetite for the OSM Carto developers to advertise what keys and values this style uses at taginfo, I think it's worth sharing my experience of doing exactly the same thing with a map style derived from OSM Carto:

* Yes, it was relatively easy to do.  There's an amount of work to do initially (look at keys and values in the .mml, and for wildcards like amenity the .mss) but it's not technically difficult and would actually make a great way for a newcomer to OSM Carto to contribute.
* Yes, when changes to the style add new keys or values taginfo.json needs to be updated, but that is literally just a text file.  Json validity can easily be checked with jsonlint prior to update.
* No, some wiki pages such as https://wiki.openstreetmap.org/wiki/OpenStreetMap_Carto/Symbols are not a substitute.  They don't appear to be regularly maintained with the style and don't show actual usage.
* I've found https://taginfo.openstreetmap.org/projects/someoneelse_style#tags extremely useful as a style developer to show what tags actually get used and how many times.

**Comment by SomeoneElseOSM** [comment]
@imagico As an aside, perhaps it's worth writing about https://imagico.de/map/styleinfo/ somewhere a bit more public so that more people know about it?  As an aside, I've no idea what https://imagico.de/map/styleinfo/#style=ajt&section=style is showing, and do wonder whether it's taking into account the lua preprocessing that that style uses at all.

You have said that "An accurate index of what tags are affecting rendering and how is hard to produce for most non-trivial map styles".  To be clear, "and how" is something you have added to the requirement yourself there, and that can be complicated (especially when tags are used in combination - "access=private; foot=yes" for example) but the what ("does style X no about tag Y") is not difficult.

I don't entirely understand the rest of your comment but it seems to be "doing a perfect job would be hard"?  If that's what you're trying to say I don't disagree, but it's not really relevant.

**Comment by imagico** [comment]
> @imagico As an aside, perhaps it's worth writing about https://imagico.de/map/styleinfo/ somewhere a bit more public so that more people know about it?

I am not sure what you mean by 'more public'.  I don't remember if this specifically was mentioned on weeklyOSM - but most people involved in OSM map style design read my blog so are aware of this.

> As an aside, I've no idea what https://imagico.de/map/styleinfo/#style=ajt&section=style is showing, and do wonder whether it's taking into account the lua preprocessing that that style uses at all.

Of course it does, as written in the blog post - the analysis can only exclude the database import step if the database content fairly directly represents the OSM data.  That is not the case with your style.  Which makes the analysis several times slower than for the other OSM-Carto forks.

If the Styleinfo UI does not work for you you can use the API directly - for example

https://imagico.de/map/styleinfo/api/ajt/renderings/?key=amenity&zoom=19&secondary_key=brand

gets you all the renderings of `amenity=*` at z19 where `brand=*` affects the rendering results.

https://imagico.de/map/styleinfo/api/ajt/preview/?key=amenity&value=pharmacy&ftype=polygon&zoom=19&secondary_key=brand

will get you the rendering of `amenity=pharmacy` with `brand=*` at z19 on polygons:

![amenity=pharmacy](https://imagico.de/map/styleinfo/api/ajt/preview/?key=amenity&value=pharmacy&ftype=polygon&zoom=19&secondary_key=brand)

> You have said that "An accurate index of what tags are affecting rendering and how is hard to produce for most non-trivial map styles". To be clear, "and how" is something you have added to the requirement yourself there, and that can be complicated (especially when tags are used in combination - "access=private; foot=yes" for example) but the what ("does style X no about tag Y") is not difficult.

The 'how' is primarily about if a tag is interpreted as a primary tag or as a secondary tag.  But also just producing a list of tags that - when they exist in the data - under some circumstances affect the rendering result, is not much easier if it is supposed to be reliable.  In other words:  A detailed _how_ is essentially an automatic byproduct of reliably determining _if_.

Of course just producing a list of tags that *might* be interpreted by the style because there is code somewhere literally referencing these tags is much easier.  Not as easy as the list of keys (as discussed above) because you need to look at both the SQL and the MSS code but still easy compared to determining what actually leads to a rendering difference.  Between #3731 and #4591 we had for example code in the style referencing healthcare tags without there being actual rendering based on those.  Therefore such a list is practically of rather limited use.
