### ISSUE TITLE
Names of POIs instead of their housenumbers

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#962]
We have some unnecessary data drop, because some points show only their address's housenumbers instead of names, like this:

http://www.openstreetmap.org/way/32256425

This is the building, where we have also cafe (visible) and two more points:

http://www.openstreetmap.org/node/3073006499
http://www.openstreetmap.org/node/3073006498

both of which have their names, but we see only the numbers (the same as the building, of course!).

I propose to get rid of that numbers (if only the name tag is given) and show the name instead. Those points should also have a dot in size of the pink one (the one we use for less popular and unnknown shops), but in the color of the name text we will show.

If the name is not given, maybe we should still show the numbers (I would be against it in my home city, but maybe there are some good cases supporting current rendering - who knows). However I would add the dots to all of them to show that there is a POI, not the strange house numbering.

Another improvement would be adding more icons and showing them, but I see a reluctance for adding them, plus there are still a tons of "numbered" points we will probably never catch in the iconized styles.

**Comment by math1985** [comment]
>  let's make all the POI's with housenumbers visible as fat dots, and let's decide when we're safe to add names to some of them.

I don't think the fact that a POI has a housenumber alone is a reason to render it.

> can't we have both, e.g. write the housenumber above, below or aside the name?

Personally I think it would make the map to crowded.

**Comment by kocio-pl** [comment]
> I don't think the fact that a POI has a housenumber alone is a reason to render it.

Well - maybe it shouldn't, but now it looks like it IS the reason in many cases. What I want is to have something more consistent regarding to rendering of POIs. What we have now is:

1. name+proper icon if available
2. ...then name+plain purple dot...
3. ...and then just the housenumber with no name, if the housenumber is available, but the POI doesn't fit in 1. or 2.

I prefer dropping rendering of housenumbers of POI's completely and treat this case as in case 2.

**Comment by Rovastar** [comment]
I thought the purple dot was just for shops on our whitelist that didn't have a specific icon....It is not for all POIs

I am really not sure what they issue is here you cannot display everything.

The issue seem to be certain POIs don't get displayed.

Yes we know doctors is one that has been crying out for ages and will solve one of your issues.
But we are actively making a point of only displaying things that are specifically on a valid list of things to display. The shops is one example of this, I expect more in the future.
If there are no valid POI we display the house number. I am not sure it is inconsistent. It seems very simple and consistent to me.

And remember boys and girls every change or absence of a change will result in someone not being happy by it.

Math, why has this been reopened? *shrug*

**Comment by kocio-pl** [comment]
> If there are no valid POI we display the house number. I am not sure it is inconsistent. It seems very simple and consistent to me.

I try to be as accurate as I can, but it seems I fail at explaining... It surprises me a lot that you don't see the inconsistency, I see the problem exactly at this point:
If they are "valid" - the name is what is the most interesting thing, not the number.
If they are "invalid" (and what are the definition of "validity": just a technical or something more?) - why we show them at all?

I speak from the point of view of big city micromapper. There are a lot of shops/craft/services POI in some areas, and you can expect all those places are more or less similar. I can even live with degradation pattern: icon+name -> dot+name - > dot without name. But then suddenly you see the housenumbers a few times on the building - looks like they're not the points, but multiple number rendering of given building, aren't they?

That example looks just like a messy building housenumber rendering if you don't know that these are other POIs: 

http://www.openstreetmap.org/way/32256425

We can't not only identify them as something different than the property of the building, but also we can't distinguish one from the another. Dot-with-no-name rendering also suffers from this second problem, but at least we avoid the first one.

**Comment by kocio-pl** [comment]
I guess after office is rendered as dot, the remaining part is mainly craft (see #3126) and some amenities. Maybe we won't get rid of housenumbers for POIs, but it would be enough for me if they will be rare.

**Comment by jidanni** [comment]
In https://help.openstreetmap.org/questions/70669/house-numbers-not-shown-on-map?
addresses are not rendered despite plenty of room remaining for them.
Perhaps in some cultures addresses aren't important?
Well in others they are vital. More vital than the building title.

**Comment by jidanni** [comment]
I think names places should always have their house number shown.

[Here](https://www.openstreetmap.org/?mlat=51.50343&mlon=-0.12762#map=19/51.50343/-0.12762) we see
https://en.wikipedia.org/wiki/10_Downing_Street has its house number
shown twice, while
11 https://www.openstreetmap.org/way/105957600
12 https://www.openstreetmap.org/way/37743391
lack them.

**Comment by jeisenbe** [comment]
> 10_Downing_Street has its house number shown twice

Ah, that's happening because there are 2 different features: the entrance node at the door https://www.openstreetmap.org/node/1931404517 and the building area https://www.openstreetmap.org/relation/1879842 which both have the same `addr:housenumber=10`.

However, the housenumber of the building relation is only shown right now because building names are labeled with ST_PointOnSurface, while the addr:housenumber is rendered with Mapnik's label-placement algorithm. 

We can fix this by changing addresses to also use ST_PointOnSurface - see #1644, and PRs #3233, #3690, #3712, #3781, and #3874

**Comment by jidanni** [comment]
@jeisenbe OK. Let's hope one day even normal places with plenty of room to show their house numbers,
https://www.openstreetmap.org/way/717830616
https://www.openstreetmap.org/way/340547893
will get them rightfully restored. Thanks.

**Comment by jeisenbe** [comment]
If you want to make sure that a particular house number can be rendered, note that this style also renders house numbers for nodes with `entrance=*` + `addr:housenumber=*`. 

Most of the numbers in this example are from such entrance nodes, and displaying them at the location of the entrance usually leaves room for POIs in the building or the building name:

![z19-monop-before](https://user-images.githubusercontent.com/42757252/65382366-81fc0980-dd3e-11e9-82b0-2293c596a266.png)
https://www.openstreetmap.org/#map=19/50.63295/3.06320

In the case of https://www.openstreetmap.org/way/340547893 - this is an `amenity=school` grounds, so showing the `addr:housenumber` at the centre would be less helpful than at the `entrance`, located at the entrance to the the main office or reception where map users should be routed.

https://www.openstreetmap.org/way/717830616#map=19/24.20949/120.83998 is a 15 by 20 meter building at 24 degrees north, so there is only room to show the name in the center of the building at z19, but there might be room to show the `addr:housenumber` if it is added to an `entrance=yes` or `entrance=main` node, and this will also help routing and navigation.

**Comment by jeisenbe** [comment]
Reading the comments above, especially https://github.com/gravitystorm/openstreetmap-carto/issues/962#issuecomment-69221306 by @kocio-pl, I agree that it's odd to show the `addr:housenumber` for all points, including those that have other main feature tags.

Currently the code is: 
```
FROM planet_osm_polygon
          WHERE (("addr:housenumber" IS NOT NULL) OR ("addr:housename" IS NOT NULL) OR ((tags->'addr:unit') IS NOT NULL))
            AND building IS NOT NULL
```
and
```
 FROM planet_osm_point
          WHERE ("addr:housenumber" IS NOT NULL) OR ("addr:housename" IS NOT NULL) OR ((tags->'addr:unit') IS NOT NULL)
```

This means that for polygons, the housenumber is only displayed if there is a `building` tag, but for points, the housenumber is displayed for anything in the database, leading to duplicate rendering when there is both an `entrance=` node and another poi node with the same `addr:housenumber`, or when an unnamed building has an `entrance=` node or any POI node with an `addr:housenumber` inside. 

A properly tagged building with a POI node and entrance node could have 3 copies of the number rendered at high zoom levels. This may imply that tagging each of the features with the `addr` is a mistake, but I'm not sure that is true. Tagging both the entrance and the POI is probably correct, so that the `addr` is linked to the POI.

I suppose fixing this would require either intersecting ways and nodes in SQL to remove duplicates?

**Comment by jidanni** [comment]
One major consideration is that we are just normal users using the iD Editor to enter businesses. We simply fill out the fields offered and save the edit. As far as fancy items like where the entrance is, well, that could be left for later when some expert comes along to refine the area.

So I guess you could say a basic business would just have a rectangle for the area, the name of the business, and the house number.

So all three should be displayed. Sure maybe later when some local mapping team comes along to make everything perfect then we can talk about more fancy items but given these basic things then, well, they should be shown. Thanks.

**Comment by jidanni** [comment]
The ID editor doesn't pause to ask us where the entrance is so we would never think of it.

**Comment by jidanni** [comment]
Plus usually the entrance is in the front of the building because there's neighbors to either side so  only in very special cases wood they're not be an  entrance in the front of the building so I think iD fits the most common use. At least here in crowded Taiwan.

**Comment by jidanni** [comment]
Yes, you could do a cross database tally, and only show one of three identical addresses. However please don't show 0 of 1 identical address.

**Comment by jidanni** [comment]
Plus it still seems you would need to show at least two for important big buildings.

 Prime minister's residence  10

And then another 10 at the exact entrance.

**Comment by jeisenbe** [comment]
> The ID editor doesn't pause to ask us where the entrance is so we would never think of it.

You could try opening an issue at the iD github to suggest adding an
entrance node when mapping a building? See
https://github.com/openstreetmap/iD/issues

**Comment by jeisenbe** [comment]
This issue was reopened with the idea: 

"let's make all the POI's with housenumbers visible as fat dots, and let's decide when we're safe to add names to some of them.”

As several comments have mentioend above, this sort of catch-all rendering is not a good idea (see #1 and #240) - this style has a main goal of preventing tag fragmentation and supporting mappers with feedback.

There is also a different idea. that we should not render the addr:housenumber label for nodes which also have another main key like amenity= or shop= or office= - but that is a different rendering idea and should probably be a separate issue with a title like “Do not render housenumbers for nodes which also have a POI main feature tag which is not rendered”, if anyone thinks that is worth pursuing.

So I would recommend closing this issue, and the similar issue #4216, as not a good idea to fix.

**Comment by imagico** [comment]
My reading of the suggestion this issue makes (see https://github.com/gravitystorm/openstreetmap-carto/issues/962#issuecomment-57391574) is to render features tagged with `addr::housenumber` and `name` but no further classifying tags with a name label instead of a housenumber label - essentially a slight variation of #4216.  As such i agree this should be closed for the reasons explained in https://github.com/gravitystorm/openstreetmap-carto/issues/4216#issuecomment-713604119.

If there are other ideas meant to be pursued by this issue it would as @jeisenbe points out probably be best to open a separate issue explaining the specific idea.  Note however anything involving a catch-all or in other words basing rendering decisions on the presence of some key independent of the specific tag used is to be seen critically under the goal of constructive mapper support, avoiding tagging fragmentation and for an intuitive and easy to understand relationship between the data and the resulting rendering.
