### ISSUE TITLE
Rendering hedge as area is not always correct

### ISSUE THREAD

**Issue by SK53** [gravitystorm/openstreetmap-carto#971]
A closed way tagged as barrier=hedge is interpreted as an area for zoom 16 and greater (landcover.mss line 425 & seq). Fields mapped as an area of farmland with a surrounding hedge are now shown exactly the same as woodland.

Example area is Cherry Hinton (z16 and z15):

![cherry_hinton_hedges](https://cloud.githubusercontent.com/assets/5452818/4360004/911a7148-4277-11e4-9b32-5052a12b89c1.jpg)

In this cases the hedges surrounding the fields are uninterrupted.

**Comment by jeisenbe** [comment]
This can be corrected now that area=yes is available as a tag in hstore, so I recommend reopening this issue.

I downloaded most of the features mapped as `way["barrier"="hedge"]["area"!="yes"]["tourism"]`. I found 31 closed ways tagged with hedge and tourism without area=yes. These should not be rendered with the hedge fill color.

Current screenshot:
![campsite-barrier-hedge](https://user-images.githubusercontent.com/42757252/55922479-419b4a00-5c3c-11e9-8879-2dcd62a2ced3.png)
https://www.openstreetmap.org/way/225683577/#map=17/51.1651/-0.04265
way 225683577
barrier=hedge
name=Long Acres Caravan & Camping
tourism=caravan_site

After checking for "area=yes". (I've also changed the outline color to match the fill color).
- This can be done in the SQL query to exclude all types of barrier=* without area=yes, or it could just be done in the CSS for hedges only. 
![z16-campground-hedges](https://user-images.githubusercontent.com/42757252/55936442-50502400-5c71-11e9-87e2-0939ff3acd68.png)

Alternately, we could get rid of the polygon fill and just render the 3 pixel wide green line on the outline of the area, similar to the current rendering for barrier=wall when mapped as an area.

**Comment by matkoniecz** [comment]
> I would suggest retagging the field with a double line, one for the field and one for the area. I think that's also conceptually better, because it feels strange that a single object represents both an area and a field.

I agree, in my opinion tagging hedge around area and area with the same closed way is a tagging mistake.

But this appears to not be shared by wider OSM community (for example I proposed validator warning in JOSM for that), so workaround in rendering adding support for this tagging would not be unwelcomed.

**Comment by pnorman** [comment]
We've always had access to the `area` tag, it's nothing that's changed in 4.0. I stand by the object being an area or not - not some combination of both.

**Comment by matkoniecz** [comment]
I also agree with that and I would be OK with closing this issue again.

But I am also not happy about divergent ideas how such object should be tagged. I am not sure is it preferable is it better to continue with approach different than most(?) of OSM community or to change it to one that is introducing some mixed status of a single element.

**Comment by jeisenbe** [comment]
I checked out this issue again after learned that the ID editor always requires `area=yes` with tags that are allowed to be tagged on a linear way or an area, for example, barrier=wall, barrier=fence. [See comment].(https://github.com/gravitystorm/openstreetmap-carto/issues/3453#issuecomment-481400006)

It sounds like JOSM also follows the principle most of the time? And the wiki pages for barrier=hedge and barrier=wall are also clear that area=yes is required when mapping a closed way that is meant to be considered an area. 

Since we can distinguish between closed ways tagged with area=yes or not, I believe it is reasonable to use this to adjust rendering, so that our rendering is consistent with the wiki documentation and with the editors function.

However, I'm also happy to submit a PR to remove the area fill for hedges, instead, if that's the best option.

**Comment by jeisenbe** [comment]
> We've always had access to the area tag, it's nothing that's changed in 4.0

I used `AND tags->'area' = 'yes'` as a filter
When I tried using `AND "area" = 'yes'` or `AND area = 'yes'` I got errors, so I thought it must be in hstore. 

Is there a way to find out which keys are imported into separate columns by osm2pgsql and which ones are only in the hstore column?

**Comment by sommerluk** [comment]
The file [openstreetmap-carto.style](https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.style) lists the columns that are imported namely.

**Comment by pnorman** [comment]
> Is there a way to find out which keys are imported into separate columns by osm2pgsql and which ones are only in the hstore column?

Prior to 4.0 we used the [default osm2pgsql .style file](https://github.com/openstreetmap/osm2pgsql/blob/master/default.style)

**Comment by jeisenbe** [comment]
OK, there are 2 options for fixing this:

1) Use the presence of "area=yes" to determine if the area fill is rendered. We would also use the standard-width green line for polygons with `barrier=hedge` but without `area=yes`, so that they rendered the same as hedges on lines. 

2)Remove the area fill rendering from hedges. There are few examples where this improves the cartography, and this would make it consistent with `barrier=wall` with `area=yes` where there is no fill.

**Comment by matkoniecz** [comment]
Or consider the current behavior as correct.

**Comment by Adamant36** [comment]
> this would make it consistent with barrier=wall with area=yes where there is no fill.

Wouldn't make it consistent with reality though. In what examples would it improve the cartography?

**Comment by imagico** [comment]
In contrast to what i said in 2014 i would now be in favour of completely dropping filled polygon rendering of hedges.  I have the impression there is no significant volume of intentional and correct uses of this.

**Comment by jeisenbe** [comment]
>  In what examples would it improve the cartography?

The map will definitely improve for closed ways that are tagged `barrier=hedge` and another feature tag like `tourism=` or `landuse=` or `amenity=` which causes the closed way to be imported as a polygon, and rendered with the solid hedge-color fill. 

For `barrier=hedge` that are intentionally mapped as areas (mainly those tagged `area=yes` as recommended), the rendering will usually be the same at z16 and z17. Hedges over a meter in width will look different at 18 and z19 in high latitudes.
