### ISSUE TITLE
Make icon size consistent

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#974]
Add the moment, we are using a mixture of 16px, 20px, and even 24px icons, without clear reasoning why some icons are bigger than others.

Would using the 16px versions for all icons be an improvement?

Here an overview of all icons in different sizes can be found: http://www.sjjb.co.uk/mapicons/contactsheet

**Comment by kocio-pl** [comment]
We now have a 14px as a standard, I guess this issue can be closed now.

**Comment by math1985** [comment]
It seems like we still have a couple of 'old' icons with different sizes, like for golf and slipway.

Also, it seems some of the icons are 14px, and others are 16px including a white border. It would be nice if we could unify that too.

**Comment by kocio-pl** [comment]
Now I doubt if that's possible - like I said in https://github.com/gravitystorm/openstreetmap-carto/issues/1145#issuecomment-324384353, we have some 20 px icons (slipway - probably it's hard to make it smaller without compromising readability) and some 10 px (waste basket - by design). 

I can live with that and I think it's enough to have a common size mentioned in our [icon guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines).
