### ISSUE TITLE
amenity=charging_station to use similar render to fuel station

### ISSUE THREAD

**Issue by Stalfur** [gravitystorm/openstreetmap-carto#989]
Issue #108 says to render names of amenities. Charging station is high on the list there but I believe it should be treated similarly to fuel_station, you still hook your car up to a pump like thing only it is electricity and not liquid that flows.

**Comment by nebulon42** [comment]
I have added a charging station icon to [Osmic](https://github.com/nebulon42/osmic): ![charging-station-16](https://cloud.githubusercontent.com/assets/3531092/7711218/5df6178c-fe69-11e4-95d2-13afb71ba53a.png)

**Comment by kocio-pl** [comment]
Great!

**Comment by brycenesbitt** [comment]
@math1985 there are already dedicated mapping sites for this type of feature such as http://www.plugshare.com/ .  50,000 sites.  This is a case where OSM probably won't be the "go to" site for mappers or users.  But showing the feature if mapped is fine.

**Comment by Barthwo** [comment]
Times have changed. Electrical powered cars are coming in numbers. So I would like to see this point with a higher priority. 
The rendering could even use different icons for fast chargers (more than 32 amp) like a filling station and destination chargers (parking lots with a possibility of charging) up to 32 amp with a smaller (?) icon.

**Comment by math1985** [comment]
> Times have changed. 

Agree.

The new problem: won't there be too many of them? In my city, the government has decided to install 1000 additional charging stations this year alone.

**Comment by nebulon42** [comment]
As always this depends on the region. In my region charging stations are present but scarce. I guess choosing a suitable zoom level high enough would work. More detailed and earlier display should be left to specialised maps.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 08 mag 2016, alle ore 10:31, math1985 <notifications@github.com> ha scritto:
> 
> The new problem: won't there be too many of them? In my city, the government has decided to install 1000 additional charging stations this year alone.
> 


are these isolated / distinct locations, because if you have e.g.  5 in a row they will likely render as one.

**Comment by math1985** [comment]
I think these are isolated locations. See http://www.oplaadpalen.nl/. I only expect the number to grow over the next few years.

**Comment by Barthwo** [comment]
amenity=charging_station is defined with a NUMBER of charging points, so it can be rendered as ONE point even if more than one car can use it simultanuously. 
There is a growing number of "fast charging" stations (amperage>32, more than 22 kW), which could be handled similar to fuel stations. 
And there will be an even much bigger number of "destination charging" stations, which, in fact, are parking lots with the possibility to charge with 16 or max 32 ampere (3.7 - 22 kW) while being in a restaurant, theme park, shopping mall ... These could be rendered differently and at higher zoom levels.

**Comment by nebulon42** [comment]
The only realistic possibility I see to get this rendered anytime soon is with some icon (e.g. see above) and with a name or operator. Then the best starting zoom level has to be found. More detailed rendering is rather not feasible for this general purpose map.

**Comment by Barthwo** [comment]
Fuel stations are rendered starting with zoom level 17 and it would be fine to do the same with charging_stations. The name is not very important, but the operator is, because very often the usage is dependent on the operator.
If an icon like a "fuel station with a plug" like proposed in the wiki is used, this is not very good distinguishable from a gas station, so I would popose to use an icon of a car with plug like: http://publicdomainvectors.org/photos/eco_green_car_plug_icon.png or http://ivo.co.za/wp-content/uploads/2013/05/e-car.png or a  plug without car like: http://www.freepik.com/free-icon/plug-silhouette_782498.htm or https://pixabay.com/de/netzstecker-symbol-icon-stecker-309142/

**Comment by dieterdreist** [comment]
2016-05-08 19:19 GMT+02:00 Barthwo <notifications@github.com>:

> amenity=charging_station is defined with a NUMBER of charging points, so
> it can be rendered as ONE point even if more than one car can use it
> simultanuously.



if you are to use the tag for more than one charging point it would be
better to use an area for this, as there will be significant spatial
extension (especially if we are talking about many charging points). Still,
tagging singular charging points does make sense to convey information
about the layout.

Cheers,
Martin

**Comment by Barthwo** [comment]
See it comparable to gas stations. Your are not mapping each pump.
Same here. 
There was a proposal for something which is containing severals charging_stations. In my eyes this is not a good idea.
But I think if really needed a charging station could be mapped as an area with several "charging_points" under it, which would be the equivalant to a gas pump.

**Comment by dieterdreist** [comment]
2016-05-09 13:36 GMT+02:00 Barthwo <notifications@github.com>:

> See it comparable to gas stations. Your are not mapping each pump.
> Same here.
>


it is not comparable, as charging takes up much more time, so you will have
to use a different concept when planning them.

**Comment by Barthwo** [comment]
Fast chargers take 30 min or so optimum, destination chargers are blocked for hours.
But this is not the problem. The problem is that there are charging_points and charging_stations and charging_stations are comparable to gas stations, charging_points with gas pumps, one car at one time. So it would be problematic to use the tag charging_station an in fact mean a charging_point.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 09 mag 2016, alle ore 13:42, Barthwo <notifications@github.com> ha scritto:
> 
> So it would be problematic to use the tag charging_station an in fact mean a charging_point.
> 


yes of course dedicated tags should be used for distinction

**Comment by Barthwo** [comment]
At the moment there is only charging_station which I would prefer to be rendered like a gas station. But there could be a second more detailed tag charging_point, which does not exist until now.
A charging_point CAN (MUST? SHOULD?) belong to a charging_station. How to map that in the database?  Or should it be used alternatively, which I do NOT think to be a good idea.

**Comment by dieterdreist** [comment]
2016-05-09 16:09 GMT+02:00 Barthwo <notifications@github.com>:

> How to map that in the database?


this should go to the tagging ML.
The alternatives are e.g.
- charging station area, inside which are the charging points (prefer)
- tag on the charging point to indicate the station it belongs to
- relations (not desirable IMHO)

**Comment by Barthwo** [comment]
I also think that the first alternative is a possible one. But it has TWO new tags and is not compatible with the existing tag charging_station.
So in THIS moment we can (and should) render a point with amenity=charging_station (more than 7500 at the moment) up from zoom=17 with an icon like: https://github.com/osmandapp/OsmAnd-resources/blob/master/icons/svg/transport/charging_station.svg and a text with the operator.

**Comment by dieterdreist** [comment]
2016-05-09 16:41 GMT+02:00 Barthwo <notifications@github.com>:

> I also think that the first alternative is a possible one. But it has TWO
> new tags and is not compatible with the existing tag charging_station.



there are already some amenity=charging_station mapped as areas (currently
just 1% of all), so there would be only one new tag IMHO to invent (for
individual charging points).
http://taginfo.osm.org/tags/amenity=charging_station#overview

**Comment by Barthwo** [comment]
I think we are discussing a problem which can be looked at later.
But NOW the 99% of charging_stations which are points should be rendered.

**Comment by brycenesbitt** [comment]
I own and drive an EV.  Some of the discussion above seems insensitive to some important points about EV charger mapping.

- If the connector does not match your car, the station is useless.  The amperage is important, but second to the connector type.
- Brand matters.  If I pull up to a Blink station, my Chargepoint card won't work.  The connector must match, the network must match, and the station must be available which leads me to:
- A huge fraction of paid charging stations are online.
- There are well established crowdsourced mapping efforts for charging stations.
- Bad mapping of charging stations hurts a lot.  Any real EV owner who really needs a charge is going to choose a data source that's better suited to updates and community comments, compared to OSM.

There's a tussle between open mapping of charging stations (brand neutral) and brand specific efforts (like single apps dedicated to a given paid charging network).

One of the open mapping efforts is http://www.plugshare.com/ .  Displaying plugshare locations on OSM would be great.  Duplicating plugshare seems unlikely to gain the momentum it would need in order to serve actual EV drivers.

**Comment by Stalfur** [comment]
@brycenesbitt 
We already have connector types mapped, operator as well as voltage - adding other values is as easy as we know it is. 
Example: http://www.openstreetmap.org/node/2944174209#map=19/64.10113/-21.87295

I don't see why OSM should stay away from mapping these - we can make easy tools for people to update values - example of two approaches are Wheelmap.org and [Coffeedex ](http://www.macwright.org/coffeedex/) - perhaps plugshare might want to migrate to OSM - lots of tools they would gain.

**Comment by pnorman** [comment]
This issue tracker is for discussing rendering, not tagging. Proposing new tags does **not** belong here.

**Comment by Barthwo** [comment]
I also do own and drive an electric car, the VW Golf. In Germany we have quite good maps showing charging stations like: http://www.goingelectric.de/stromtankstellen/ but these are based on google, not OSM. What a pity.
Europe has decided on Type 2 (1 or 3 phases, which means 240 or 380 Volt with 16 or sometimes 32 Amp, giving 3.7, 11 or 22 kW AC) for use at home, work and destination chargers and fast chargers using CCS DC with as of today mostly 50 kW as standard but most cases combined with Chademo at the charging point. So normally all cars are carrying the equipment to be technically able to connect to nearly all of the charging points. Remember: In Europe we have a 240 Volt 3-phase systems in nearly all houses, which can deliver 11 kW at 16 amp with ease everywhere. All this can be tagged with the existing scheme!

I think all these charging stations should be mapped, because gas stations are mapped too. I would prefer to distinguish between fast chargers (more than 32 amp)  and the others (up to 32 amp), but thats not obligatory.
But its a very good idea to give the name of the operator, because then you have an idea if your "charging card" is working there. But in future we will see that most of these stations will operate with normal credit or debit cards. 
What does all this mean for mapping: Please map charging stations with an icon like this which osmand is using, which I posted here, beginning with zoom level 17 and the operator as text. The means of payment can change but the operator will stay constant.

**Comment by pnorman** [comment]
I've removed some of the pure tagging discussion - like I said, it does not belong in this issue tracker.

-----

> I think all these charging stations should be mapped, because gas stations are mapped too.

Do you mean rendered on OpenStreetMap Carto or mapped? What is mapped is not something we have direct control over here, only what is rendered.

**Comment by Barthwo** [comment]
Excuse me, I mean this should be RENDERED. 
This is a language problem of mine. Im my mother tongue german the word "kartiert = mapped" is normally used for what you "see on the map", not what is known or in a database.

**Comment by brycenesbitt** [comment]
In the USA things are moving away from credit card payment, toward payment plans and network membership cards.  Thus the USA centric mapping renders icons based on a combination of network and charging plug.  Tesla has it's own network, so that's often separate also.  There's also a whole subculture of home chargers that people invite others to use for emergency top ups (network of "personal charger").

Thus a charger specific map needs fairly rich rendering and filtering.

I'd put the utility of rendering charging stations in carto quite low, and well below that of various other currently non-rendered features.

**Comment by Barthwo** [comment]
We do not speak of US centric mapping but worldwide. As I wrote before, each region does have maps, often for special chains or even show if a charging point is occupied.

Of course there are payment plans and network membership cards here in Europe also. Often, but not always, they have "roaming agreements" with other chains. This situation is very bad for e-car users on long distance trips. A multi purpose map cannot and must not show all this. 

And if someone wants to show his "personal charger" in the map, because its open to the public, he can do this also here. And Tesla chargers will be shown with operator=Tesla and everybody will know if he can use this or not.

But I think the charging stations should be rendered on the detailed map (zoom 17 and more) because it is a valueable information not only for people with e-cars.

**Comment by pnorman** [comment]
Information like number of outlets, capacity, connectors and similar specialized information belongs on a specialized map and won't be something we add.

**Comment by Barthwo** [comment]
In a specialized german POI map they are now rendering the charging_station now with icons based on the type of vehicle: http://www.flosm.de/html/POI-Karte.html#740000.00/51.3600000/10.4800000/1/chargingbike/chargingcar/chargingscooter/chargingstation/chargingtruck/chargingwheelchair

But I am not 100% happy with the icons, so I proposed the following icons:
- CAR=yes - socket undefined, Icon pump with plug: grey on white
- CAR=yes - "fast charger" socket ..._combo, tesla..., chademo,  Icon pump with plug: white on green
- CAR= yes - "destination charger"  socket Typ 1,2,3, Icon P (parking) white on green
- e-Bike or Scooter or wheelchair =yes (all LEV = light electric vehicles, no car or truck), icon only plug white on green
- vehicle undefined, icon only plug grey on white

**Comment by daganzdaanda** [comment]
> Information like number of outlets, capacity, connectors and similar specialized information belongs on a specialized map and won't be something we add.

agree, but I still think a simple icon like the one proposed on #2239 would be nice to have. The bigger decision would be at what zoom it should first be shown. z17 should be OK now, maybe it would need to be tweaked later.

**Comment by kocio-pl** [comment]
This issue has gone wild somehow - judging by the original entry it should be closed, as #2239 resolves it. I also believe that universal style is not intended for showing subtypes.
